force-app/main/default/objects/Apttus_Approval__Approval_Request__c/Apttus_Approval__Approval_Request__c.object-meta.xml
<CustomObject>
    <description>Designates an approval request created from an approval process</description>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Approval__Approval_Request__c/fields/Apttus_Approval__Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approver_Comments__c</fullName>
    <label>Approver Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Approval_Tracker__c/Batch_Approval_Tracker__c.object-meta.xml
<CustomObject>
    <description>Stores the batch approval progress (CLM) information such as total number of records to be processed , submitted by , status (eg in progress,completed) , submitted date.Prevents the user from opening the tab Pending Approval Requests (CLM) while the batch execution is in progress</description>
    <label>Batch Approval Tracker</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>Batch Approval Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Approval Trackers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Approval_Tracker__c/fields/Failed_Records__c.field-meta.xml
<CustomField>
    <fullName>Failed_Records__c</fullName>
    <defaultValue>0</defaultValue>
    <description>[DCP-39772] -  Total records failed in the batch processing.</description>
    <label>Failed Records</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Approval_Tracker__c/fields/Records_Processed_Successfully__c.field-meta.xml
<CustomField>
    <fullName>Records_Processed_Successfully__c</fullName>
    <defaultValue>0</defaultValue>
    <description>[DCP-39772] - Specifies total successful records processed by batch.</description>
    <label>Records Processed Successfully</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Approval_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>[DCP-39772] - Specifies current status of the batch.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchApprovalRequests.cls
/**
*    @author: Rishab Wali
*    @date:   3-Sep-2020
*    @description:  Batch class to approve/reject .
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*            Nishan Shetty                  03-Jun-2022         Implementing Batch Manager Framework DCP-50962
*            Nishan Shetty                  22-Aug-2022         [TASK0802266] Constructor added to fix ilib_BatchRunner runtime instantiation issue of no-arg constructor.
*    ------------------------------------------------------------------------------------ 
*                    
*/
global without sharing class BatchApprovalRequests extends ilib_BatchDeferrable {  
   global static final string STRINGAPPROVE = 'Approve'; 
   global integer successRecords = 0;
   global integer failedRecords = 0;
   global static final String STRINGBATCHAPPROVALSTATUSCOMPLETED = 'Completed';
   global Set<Id> appreqIdSet;

   private Inputs inputs;
   public final static String LOG_TITLE = 'BatchApprovalRequests';


    /*
    *  @Author      : Nishan Shetty
    *  @Description : Parameter wrapper for easy serialization[DCP-50962]
    */
    public class Inputs {
        public Map<Id,String> appreqIdToCommentMap;
        public String appOrRejString;
        public String batchApprovalRecId;

        /*Constructor*/
        public Inputs(Map<Id,String> appreqIdToCommentMap, String appOrRejString, String batchApprovalRecId) {
            this.appreqIdToCommentMap = appreqIdToCommentMap;
            this.appOrRejString = appOrRejString;
            this.batchApprovalRecId = batchApprovalRecId;
        }
    }

    /*
    * @Author : Nishan Shetty[TASK0802266]
    * @Description : Constructor added to fix ilib_BatchRunner runtime instantiation issue of no-arg constructor.
    */
    global BatchApprovalRequests() {
      super();
    }
    
   /*Constructor*/
   global BatchApprovalRequests(Map<Id,String> appreqIdToCommentMap , String appOrRejString , String batchApprovalRecId) {
       super();
       this.inputs = new Inputs(appreqIdToCommentMap,appOrRejString,batchApprovalRecId);
       appreqIdSet = inputs.appreqIdToCommentMap.keySet();
   } 
  
   /*START*/
   global override Database.QueryLocator start(Database.BatchableContext bc) {       
      return Database.getQueryLocator('SELECT Id,Apttus_Approval__Approver_Comments__c FROM Apttus_Approval__Approval_Request__c WHERE Id In : appreqIdSet');
   }
   
   /*EXECUTE*/
   global override void execute(Database.BatchableContext bc, List<sObject> appReqList) {
    ilib_LogEvent.setBatchTitle(LOG_TITLE, transactionId); 
    ilib_LogEvent.push(LOG_TITLE + '.execute()');
       try {
           for(Apttus_Approval__Approval_Request__c objAppReq : (List<Apttus_Approval__Approval_Request__c>)appReqList) {
               Boolean result = false;
               if(inputs.appOrRejString == STRINGAPPROVE) { 
                   if(!test.isRunningTest()) {
                       result = Apttus_Approval.ApprovalsWebService.approveRequest(objAppReq.Id,inputs.appreqIdToCommentMap.get(objAppReq.Id));
                   } 
                   ilib_LogEvent.message('Result' + result);
                   ilib_LogEvent.message('Approval Request Id' + objAppReq.Id);
                   if(result) { successRecords = successRecords + 1;}
                   else
                   {
                       failedRecords = failedRecords + 1; 
                   }
               }
           }        
       }
       Catch(Exception e){ ApexExceptions.emit('BatchApprovalRequests',appReqList[0].Id,e); }

    ilib_LogEvent.pop();
    ilib_LogEvent.emit();
    }
   
   /*FINISH*/
   global override void finish(Database.BatchableContext bc) {
       ilib_LogEvent.setBatchTitle(LOG_TITLE, transactionId);
       ilib_LogEvent.push(LOG_TITLE + '.finish()');
       Batch_Approval_Tracker__c objBatchApproval = new Batch_Approval_Tracker__c(Id = inputs.batchApprovalRecId);
       objBatchApproval.Status__c = STRINGBATCHAPPROVALSTATUSCOMPLETED;
       objBatchApproval.Failed_Records__c = failedRecords;
       objBatchApproval.Records_Processed_Successfully__c = successRecords;
       update objBatchApproval;
       ilib_LogEvent.message('objBatchApproval' + objBatchApproval);
       ilib_LogEvent.pop();
       ilib_LogEvent.emit();
    }

    // ************************************************************************************************
    // Deferrable implementation DCP-50962
    // ************************************************************************************************
    
    /*
    *  @Author      : Nishan Shetty
    *  @Description : Method to simple input serialization
    *  @Param       : None
    *  @Return      : String
    */
    public override String serializeInputs() {
        return JSON.serialize(inputs);
    }

    /*
    *  @Author      : Nishan Shetty
    *  @Description : Method to simple input deserialization
    *  @Param       : String
    *  @Return      : void
    */
    public override void restoreInputs(String serializedInputs) {
        this.inputs = (BatchApprovalRequests.Inputs)JSON.deserialize(serializedInputs, BatchApprovalRequests.Inputs.class);
    }
    
}