force-app/main/default/objects/Campaign/fields/Funnel__c.field-meta.xml
<CustomField>
    <fullName>Funnel__c</fullName>
	<description>This field tracks Campaign funnel stage (Top, Middle, Bottom) that helps marketing ops to better identify metrics of Tactics applied throughout the campaign funnel.</description>
    <inlineHelpText>Top: Awareness resources addressing prospect’s unique pain points with problem/solution content.
Middle: Consideration resources for product/service to fit prospect’s needs.
Bottom: Decision resources with in-depth product/service/competitive content.</inlineHelpText>
    <label>Funnel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top</fullName>
            </value>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Bottom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <description>DCP 10583</description>
    <label>Marketing Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academics (Defend)</fullName>
                <isActive>false</isActive>
                <label>Academics (Defend)</label>
            </value>
            <value>
                <fullName>Accelerate (RH)</fullName>
                <isActive>false</isActive>
                <label>Accelerate (RH)</label>
            </value>
            <value>
                <fullName>Accelerator</fullName>
                <isActive>false</isActive>
                <label>Accelerator</label>
            </value>
            <value>
                <fullName>Ag Research (AG)</fullName>
                <isActive>false</isActive>
                <label>Ag Research (AG)</label>
            </value>
            <value>
                <fullName>Ag Testing (AG)</fullName>
                <isActive>false</isActive>
                <label>Ag Testing (AG)</label>
            </value>
            <value>
                <fullName>AmpliSeq</fullName>
                <isActive>false</isActive>
                <label>AmpliSeq</label>
            </value>
            <value>
                <fullName>APJ Regional Campaign (RH)</fullName>
                <isActive>false</isActive>
                <label>APJ Regional Campaign (RH)</label>
            </value>
            <value>
                <fullName>BGI Compete</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Brand/Compete</fullName>
                <isActive>false</isActive>
                <label>Brand/Compete</label>
            </value>
            <value>
                <fullName>Breeding Managers and SPs (Grow)</fullName>
                <isActive>false</isActive>
                <label>Breeding Managers and SPs (Grow)</label>
            </value>
            <value>
                <fullName>Cancer Research</fullName>
                <isActive>false</isActive>
                <label>Cancer Research</label>
            </value>
            <value>
                <fullName>Clinician Education and Awareness</fullName>
                <isActive>false</isActive>
                <label>Clinician Education and Awareness</label>
            </value>
            <value>
                <fullName>Comprehensive Genomic Profiling (OT)</fullName>
                <isActive>false</isActive>
                <label>Comprehensive Genomic Profiling (OT)</label>
            </value>
            <value>
                <fullName>Consumer Genomics</fullName>
                <isActive>false</isActive>
                <label>Consumer Genomics</label>
            </value>
            <value>
                <fullName>Core Cross Segment Platforms (Platforms)</fullName>
                <isActive>false</isActive>
                <label>Core Cross Segment Platforms (Platforms)</label>
            </value>
            <value>
                <fullName>Core New Product Introductions (Platforms)</fullName>
                <isActive>false</isActive>
                <label>Core New Product Introductions (Platforms)</label>
            </value>
            <value>
                <fullName>Core On-Market Products (Platforms)</fullName>
                <isActive>false</isActive>
                <label>Core On-Market Products (Platforms)</label>
            </value>
            <value>
                <fullName>Customer Success</fullName>
                <isActive>false</isActive>
                <label>Customer Success</label>
            </value>
            <value>
                <fullName>Customer Success (RH)</fullName>
                <isActive>false</isActive>
                <label>Customer Success (RH)</label>
            </value>
            <value>
                <fullName>Discover more with NGS (Micro)</fullName>
                <isActive>false</isActive>
                <label>Discover more with NGS (Micro)</label>
            </value>
            <value>
                <fullName>Does Not Support a Marketing Initiative</fullName>
            </value>
            <value>
                <fullName>Do More Surveillance with NGS (Micro)</fullName>
                <isActive>false</isActive>
                <label>Do More Surveillance with NGS (Micro)</label>
            </value>
            <value>
                <fullName>DO NOT USE: EXPIRED</fullName>
            </value>
            <value>
                <fullName>Dx Platforms</fullName>
                <isActive>false</isActive>
                <label>Dx Platforms</label>
            </value>
            <value>
                <fullName>Education and Influence</fullName>
                <isActive>false</isActive>
                <label>Education and Influence</label>
            </value>
            <value>
                <fullName>Emerging Microbiome Pharma (Micro)</fullName>
                <isActive>false</isActive>
                <label>Emerging Microbiome Pharma (Micro)</label>
            </value>
            <value>
                <fullName>Expectant Parent (RH)</fullName>
                <isActive>false</isActive>
                <label>Expectant Parent (RH)</label>
            </value>
            <value>
                <fullName>G4G</fullName>
                <isActive>false</isActive>
                <label>G4G</label>
            </value>
            <value>
                <fullName>GC MarCom</fullName>
                <isActive>false</isActive>
                <label>GC MarCom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Marketing_Segment__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segment__c</fullName>
    <description>DCP 10583</description>
    <label>Marketing Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agrigenomics</fullName>
            </value>
            <value>
                <fullName>Cancer Research</fullName>
            </value>
            <value>
                <fullName>Cell And Molecular Biology</fullName>
                <isActive>false</isActive>
                <label>Cell And Molecular Biology</label>
            </value>
            <value>
                <fullName>Cell And Molecular Biology Research</fullName>
            </value>
            <value>
                <fullName>Consumer Genetics</fullName>
                <isActive>false</isActive>
                <label>Consumer Genetics</label>
            </value>
            <value>
                <fullName>Consumer Genomics</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
                <isActive>false</isActive>
                <label>Education</label>
            </value>
            <value>
                <fullName>Forensics</fullName>
            </value>
            <value>
                <fullName>Genetic Disease Research</fullName>
            </value>
            <value>
                <fullName>Genetic Disease Testing</fullName>
            </value>
            <value>
                <fullName>Infectious Disease Testing</fullName>
            </value>
            <value>
                <fullName>Microbiology</fullName>
            </value>
            <value>
                <fullName>Non-Segment Activity</fullName>
            </value>
            <value>
                <fullName>Oncology Testing</fullName>
            </value>
            <value>
                <fullName>Pharmacogenomics</fullName>
                <isActive>false</isActive>
                <label>Pharmacogenomics</label>
            </value>
            <value>
                <fullName>Platforms</fullName>
            </value>
            <value>
                <fullName>Population Genomics</fullName>
            </value>
            <value>
                <fullName>Precision Health</fullName>
            </value>
            <value>
                <fullName>Preventive Health</fullName>
                <isActive>false</isActive>
                <label>Preventive Health</label>
            </value>
            <value>
                <fullName>Public Health Surveillance</fullName>
            </value>
            <value>
                <fullName>Public Outreach</fullName>
            </value>
            <value>
                <fullName>Reproductive Health</fullName>
            </value>
            <value>
                <fullName>Technical Training/Education</fullName>
            </value>
            <value>
                <fullName>Transplant Genomics</fullName>
                <isActive>false</isActive>
                <label>Transplant Genomics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>Field defines the type of program segment for the campaign</description>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Based</fullName>
            </value>
            <value>
                <fullName>Advisory Board</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
                <isActive>false</isActive>
                <label>Advocacy</label>
            </value>
            <value>
                <fullName>Awareness</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Evidence Generation</fullName>
                <isActive>false</isActive>
                <label>Evidence Generation</label>
            </value>
            <value>
                <fullName>Guidelines</fullName>
                <isActive>false</isActive>
                <label>Guidelines</label>
            </value>
            <value>
                <fullName>Influence Segment Ecosystem</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>KOL/Society Engagement</fullName>
                <isActive>false</isActive>
                <label>KOL/Society Engagement</label>
            </value>
            <value>
                <fullName>KOL Operations</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Market Assessment</fullName>
            </value>
            <value>
                <fullName>Market Intelligence</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Partnership / Consortia</fullName>
            </value>
            <value>
                <fullName>Pipeline Acceleration</fullName>
            </value>
            <value>
                <fullName>Product Notification</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Sales Enablement</fullName>
            </value>
            <value>
                <fullName>Society and KOL Engagement</fullName>
            </value>
            <value>
                <fullName>Tradeshow/Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_Attribution__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Attribution__c</fullName>
    <description>DCP-16865</description>
    <label>Campaign Attribution</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Attribution__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Attribution__c</fullName>
    <description>DCP-16865</description>
    <label>Campaign Attribution</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPardotSyncCampaignAttribution.cls
/**
*    @author: Pankaj 
*    @date:   05-Jun-2019
*    @description:  Test class for BatchUpdateCampaignMembersAttendedStatus
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Pankaj                        05-Jun-2019        Initial Build
*    ------------------------------------------------------------------------------------ 
*                    
*/

@isTest(SeeAllData=false)
/*See All data is true as campaignMemberStatus is not available when it is false.*/
public class TestPardotSyncCampaignAttribution {
    /**
    *  @author Pankaj Singla
    *  @description Test Method for Process Builder Functionality
    *  @param None
    *  @return None
    **/ 
    static testMethod void testInsertCampaignMember(){
        Id userId = userinfo.getUserId();
        User u1 = [SELECT id,UserPermissionsMarketingUser from User WHERE id=:userId];
        if(u1.UserPermissionsMarketingUser==false){
            u1.UserPermissionsMarketingUser=true;
            update u1;
         }
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('PardotSynCampaignAttributionMoc');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        system.runAs(u1){
            List<Campaign> lstCampaign=new list<Campaign>();
            Contact objCon=TestDataMarketing.createContact('FirstName','LastName','Test@f.com');
            objCon.Campaign_Attribution__c='testCATCon';
            update objCon;
            Lead objLead=TestDataMarketing.createLead('FirstName','LastName','Test1@f.com','USA','USA');
            objLead.Campaign_Attribution__c='testCATCon';
            update objLead;
            Campaign objCampaignWebinar=new Campaign(name='testing',type='Webinar', Marketing_Segment__c = 'Microbiology' , Marketing_Campaign__c = 'Brand' , Program_Type__c = 'Education',Funnel__c='Top'); 
            
            insert objCampaignWebinar;
            Test.startTest();
            
            CampaignMember objCampaignMember10=TestDataMarketing.createCampaignMember(objLead.id,objCampaignWebinar.id,'Attended');
            CampaignMember objCampaignMember11=TestDataMarketing.createCampaignMemberContact(objCon.id,objCampaignWebinar.id,'Attended On-Demand');
            List<id> lstId=new list<id>();
            lstId.add(objCampaignMember10.id);
            lstId.add(objCampaignMember11.id);
            //PardotSyncCampaignAttribution.getMemberEmailIds(lstId);
            Test.stopTest();
            Lead objLd=[select id,Campaign_Attribution__c from lead where id=:objLead.id];
            system.assertEquals('NULL',objLd.Campaign_Attribution__c);
            Contact objcc=[select id,Campaign_Attribution__c from Contact where id=:objCon.id];
            system.assertEquals('NULL',objcc.Campaign_Attribution__c);
        }
    }
    /**
    *  @author Pankaj Singla
    *  @description Test Method for Queable class
    *  @param None
    *  @return None
    **/ 
    static testmethod void testQueableMethod(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('PardotSynCampaignAttributionMoc');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        List<String> lstEmails=new List<String>();
        lstEmails.add('abc@test.com');
        PardotQueableForCampaignAttribution obj=new PardotQueableForCampaignAttribution(lstEmails,'test.com');
        System.enqueueJob(obj); 
    }
    /*******************************************************
    *Method Name : coverCatchBlockPardotQueableForCampaignAttribution()
    *Description : method to cover catch block
    *params      : NA
    *return type : void
    ******************************************************/
    @isTest
    public static void coverCatchBlockPardotQueableForCampaignAttribution(){
        try{
            PardotQueableForCampaignAttribution.catchException = true;
            PardotQueableForCampaignAttribution pd = new PardotQueableForCampaignAttribution(null, null);
            Test.startTest();
            System.enqueueJob(pd);
            Test.stopTest();
        }
        catch(Exception e){
            System.assert(e!=null, 'e is not empty');
        }
    }
}