force-app/main/default/objects/Case/fields/Attempt_Case_Completion__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Case_Completion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will capture values of Attempt case completion field on Work order when Work Order is completed and will be used in escalations rules for notifying users.</description>
    <label>Attempt Case Completion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Case_Completed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To hold the user who has completed the case</description>
    <label>Case Completed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Eligible_for_Logistics_Review__c.field-meta.xml
<CustomField>
    <fullName>Case_Eligible_for_Logistics_Review__c</fullName>
    <description>The checkbox is checked when the conditions for the case being in pending logistics review are met.
    DCP-51200 [removed subtype and categories]</description>
    <formula>AND( 
	RecordType.Name = $Label.CaseRecordTypeBusinessIssue,
	Contains_Logistics_Analysis_Code__c  
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Eligible for Logistics Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Eligible_for_QA_Review__c.field-meta.xml
<CustomField>
    <fullName>Case_Eligible_for_QA_Review__c</fullName>
    <description>The checkbox is checked when the conditions for case being in QA review are met.</description>
    <formula>OR(
AND(
TEXT(Sub_Type__c) = $Label.CaseSubTypeComplaint,
OR(
 IVD_Product_Identifier_Additional_Prod__c = true,
 IVD_Product_Identifier__c = true,
 ISPICKVAL(PAE_PFA_Evaluation_Required__c , &apos;Yes&apos;)
)),
AND(
TEXT(Sub_Type__c) = $Label.CaseSubTypeGeneralIssue,
Routed_from_Logistic__c = true)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Eligible for QA Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Record_Updated_from_SFM__c.field-meta.xml
<CustomField>
    <fullName>Record_Updated_from_SFM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when Record Updated from SFM</description>
    <label>Record Updated from SFM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Attempt_case_completion__c.field-meta.xml
<CustomField>
    <fullName>Attempt_case_completion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field signifies that should case be automatically completed when work order is completed or not.</description>
    <label>Attempt Case Completion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
    <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Status__c</fullName>
    <description>Current status of the service order</description>
    <inlineHelpText>Current status of the service order</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
                <default>true</default>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assignment Accepted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Technician Onsite</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Revisit Required</fullName>
            </value>
            <value>
                <fullName>Estimate Approved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Technician Acknowledged</fullName>
            </value>
            <value>
                <fullName>Technician Enroute</fullName>
            </value>
            <value>
                <fullName>Work Complete</fullName>
            </value>
            <value>
                <fullName>Requires Revisit</fullName>
            </value>
            <value>
                <fullName>Reopen Requested</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Closed-Duplicate</fullName>
            </value>
            <value>
                <fullName>Awaiting Parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/WO_Completed_by__c.field-meta.xml
<CustomField>
    <fullName>WO_Completed_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field Will hold the user of that person who is completing the Work Order</description>
    <label>WO Completed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Orders_Completed_by</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchAttemptAutoCloseCase.cls
/**
    *    @author : Nitin Sood
    *    @date   : 02-March-2020
    *    @description : Class to attempt to auto-close cases
    *    Modification Log:
    *    ------------------------------------------------------------------------------------ 
    *    Developer                      Date                Description
    *    Nitin Sood                  02-March-2020          Initial Version.
    *    ------------------------------------------------------------------------------------ 
    *                    
    */
    global class BatchAttemptAutoCloseCase extends ilib_ScheduleAndBatch implements Database.Batchable<sObject>, Database.Stateful{
         
        public static final Id BUSINESS_ISSUE_CASE_RECORDTYPE = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.CaseRecordTypeBusinessIssue).getRecordTypeId();  
		List<Database.SaveResult> lstSaveErrors = new List<Database.SaveResult>();
		Map<Id, String> mapRecIdToErrors = new Map<Id, String>();
		ID batchprocessid;
        Map<String, List<CaseIdError>> mapEmailToCaseIdError =  new Map<String, List<CaseIdError>>(); // final map to store email and case id and error          
        /*
		*@Description: Excute method of Schedulable Context
		*/
		global Override void execute(SchedulableContext ctx) {
            integer defaultBatchsize = 200;
            Map < String, String > params = UtilsSettings.getCustomMetadataMap('Attempt_auto_case_completion');
            Integer batchSize = UtilsSettings.parseIntegerFromSettingsMap(params, 'AttempCaseCompletion', defaultBatchSize);

            if (batchSize < 1 || batchSize > 200) {
              batchSize = defaultBatchSize;
            }
            batchprocessid = Database.executeBatch(new BatchAttemptAutoCloseCase(), batchsize);
        }
        
        /*
		*@Description: Start method of Batchable Context
		*/
        global override Database.QueryLocator start(Database.BatchableContext bc){
            
            Set<String> setClosedStatuses = new Set<String>{'Completed', 'Closed'};

            Set<String> setIntegrationStatuses = new Set<String>{'Success', 'Not Required'};
			if(Test.isRunningTest()){
				setIntegrationStatuses.add('In Progress');
			}
			List<AsyncApexJob> lstCompletedJobs = [Select Id, ApexClass.Name, CreatedDate, JobType, Status FROM AsyncApexJob WHERE JobType = 'BatchApex' AND Status = 'Completed' AND ApexClass.Name = 'BatchAttemptAutoCloseCase' AND NumberOfErrors	= 0 Order By CreatedDate DESC NULLS LAST Limit 1 ];
            
			DateTime lastCompletionDateTime = NULL;
            if(lstCompletedJobs != null && lstCompletedJobs.size() > 0){
				lastCompletionDateTime = lstCompletedJobs[0].CreatedDate;
			}
            System.debug('!!!!!!!!!!!!!lastCompletionDateTime after time set!!!!!!!!!!!!!!!!!!!!'+lastCompletionDateTime);

            String sQuery = 'SELECT id, SVMXC__Case__c, OwnerId, SVMXC__Case__r.Status, SVMXC__Case__r.OwnerId, SVMXC__Case__r.CaseNumber , Owner.Email, Owner.Name, SVMXC__Case__r.Case_Eligible_for_QA_Review__c, SVMXC__Case__r.Case_Eligible_for_Logistics_Review__c, SVMXC__Case__r.RecordTypeId, WO_Completed_by__c  FROM SVMXC__Service_Order__c WHERE SVMXC__Order_Status__c IN: setClosedStatuses AND Attempt_case_completion__c = true AND Integration_Status__c IN: setIntegrationStatuses AND SVMXC__Case__r.Status NOT IN: setClosedStatuses';	
			
			if(lastCompletionDateTime != null ){
				sQuery = sQuery +' AND LastModifiedDate >: lastCompletionDateTime';
			}

            return Database.getQueryLocator(sQuery);
        }
		
        /*
		*@Description: Execute method of Batchable Context
		*/
        
        global override void execute(Database.BatchableContext bc, List<sObject> lstScope){
       
            List<Case> lstCasesToBeUpdated = new List<Case>(); //to store cases whcih needs to be updated
            Map<Id, String> mapCaseIdOwnerEmail =  new Map<Id, String>(); //map for storing case id and email and case number
            Map<Id, String> mapCaseIdError = new Map<Id, String>(); // map to store failed case Ids and their error

            //iterating over completed work orders
            for(SVMXC__Service_Order__c objWorkorder: (list < SVMXC__Service_Order__c > ) lstScope){
                if(objWorkorder.OwnerId == objWorkorder.SVMXC__Case__r.OwnerId){
                    Case objCase = new Case(); 
                    objCase.Id = objWorkorder.SVMXC__Case__c;
					if(objWorkorder.SVMXC__Case__r.Case_Eligible_for_Logistics_Review__c){
						objCase.status = 'Pending Logistics Review';						
					}
					else if(objWorkorder.SVMXC__Case__r.Case_Eligible_for_QA_Review__c && objWorkorder.SVMXC__Case__r.RecordTypeId == BUSINESS_ISSUE_CASE_RECORDTYPE ){
						objCase.status = 'Pending QA Review';						
					}
					else{
						objCase.status = 'Completed';
						objCase.Case_Completed_By__c = objWorkorder.WO_Completed_by__c;						
					}
                    objCase.Record_Updated_from_SFM__c = true;//INC0325752
                    lstCasesToBeUpdated.add(objCase);
                    mapCaseIdOwnerEmail.put(objWorkorder.SVMXC__Case__c, objWorkorder.Owner.Email+'~'+ objWorkorder.SVMXC__Case__r.CaseNumber+'~'+ objWorkorder.Owner.Name);
                }               
            }
          
            //iterating over update list and capturing errors for failed cases
            if(lstCasesToBeUpdated.size() > 0){
                List<Database.SaveResult> lstSR = Database.update(lstCasesToBeUpdated, false);

                for(Integer i=0;i<lstSR.size();i++) {

                    if (!lstSR.get(i).isSuccess()){
                        
                        mapCaseIdError.put(lstCasesToBeUpdated.get(i).Id, lstSR.get(i).getErrors()[0].getMessage());
						mapRecIdToErrors.put(lstCasesToBeUpdated.get(i).Id, lstSR.get(i).getErrors()[0].getMessage());
						lstSaveErrors.add(lstSR.get(i)); 
                    }
                }               
            }
            
            //iterating over failed list and preparing map for emial ids with case number and failed error 
            for(Id caseId : mapCaseIdError.keyset()){

                if(mapEmailToCaseIdError.containsKey(mapCaseIdOwnerEmail.get(caseId).split('~')[0])){
                    CaseIdError objCaseIdError = new CaseIdError();
                    objCaseIdError.caseNumber = mapCaseIdOwnerEmail.get(caseId).split('~')[1];
                    objCaseIdError.ownerName = mapCaseIdOwnerEmail.get(caseId).split('~')[2];
                    objCaseIdError.error = mapCaseIdError.get(caseId);
                    mapEmailToCaseIdError.get(mapCaseIdOwnerEmail.get(caseId).split('~')[0]).add(objCaseIdError);
                }
                else{
                    List<CaseIdError> lstCaseIdError =  new List<CaseIdError>();
                    CaseIdError objCaseIdError = new CaseIdError();
                    objCaseIdError.caseNumber = mapCaseIdOwnerEmail.get(caseId).split('~')[1];
                    objCaseIdError.ownerName = mapCaseIdOwnerEmail.get(caseId).split('~')[2];
                    objCaseIdError.error = mapCaseIdError.get(caseId);
                    lstCaseIdError.add(objCaseIdError);
                    mapEmailToCaseIdError.put(mapCaseIdOwnerEmail.get(caseId).split('~')[0],lstCaseIdError);
                    
                }
                
            }
          
        }
        /*
		*@Description: Finish method of Batchable Context
		*/
        global override void finish(Database.BatchableContext bc){
            
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
			if(!mapEmailToCaseIdError.isEmpty()){
				for(String receipientEmail : mapEmailToCaseIdError.keyset()){
					
					String tableBody = getTableEmailBody(mapEmailToCaseIdError.get(receipientEmail));
					String caseOwnerName = mapEmailToCaseIdError.get(receipientEmail)[0].ownerName;        
					Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
					String[] toAddresses = new String[]{receipientEmail};
					String subject = 'ACTION NEEDED: Unsuccessful Completion of Case(s)';
					email.setSubject(subject);
					email.setToAddresses(toAddresses);
					email.setHtmlBody('Dear ' + caseOwnerName+ ',<br>'+'<br>DCP automation processes were NOT able to automatically complete the following Case(s): <br>'+tableBody + '<br> Please note, your action is required to Complete the Case(s) above.  Please log into DCP, make any necessary updates and manually complete the Case(s) as soon as possible.<br>'+'Thank you.');
					mails.add(email);
						
				}
				
				Messaging.sendEmail(mails);
			}
					
			// code for error logging and sending MS Teams notification
			try{
				if(Feature.isOn('ServiceBatchErrorNotifications')){				
					String source = 'BatchAttemptAutoCloseCase';
					if(!lstSaveErrors.isEmpty()){
						ApexExceptions.emitSaveErrors(lstSaveErrors, source);
					}
					if(!mapRecIdToErrors.isEmpty()){
						ilib_Queueablethread  queueableThread=new ilib_Queueablethread('MSTeamsNotification'); 
						queueableThread.logandQueue(new QueueableMSTeamsNotificationSender(mapRecIdToErrors, source, batchProcessId),'QueueableMSTeamsNotificationSender','getTableEmailBodyAndSendNotification');		

						if(!queueableThread.lstQueueableJobs.isEmpty()){
							ilib_QueueableManager.enqueueJob(queueableThread,ilib_LogEvent.SERVICE);
						}						
					}
				}
			}
			catch(Exception e){
				System.debug('!!!!!!!!!!!!!!!exception!!!!!!!!!!!!'+e.getMessage());
			}						
		}
        /*
		*@method: getTableEmailBody
		*/
        public static string getTableEmailBody(List<CaseIdError> lstCaseIdError){

            String htmlBody = '';

            //open table..
            htmlBody = '<table border="1" style="border-collapse: collapse"><tr><th>Case Number</th><th>Error Message</th></tr>';

            //iterate over list and output columns/data into table rows...
            for(CaseIdError objCaseIdError : lstCaseIdError){

                String caseNumber = objCaseIdError.caseNumber; 
                String error = objCaseIdError.error; 

                htmlBody += '<tr><td>' + caseNumber + '</td><td>' +error + '</td></tr>';

            }

            //close table...
            htmlBody += '</table>';

            system.debug('Email Body: ' + htmlBody);   

            return htmlBody;

        }
        /*
		*@Inner class: CaseIdError
		*/
        public class CaseIdError{
            public string caseNumber;
            public string error;
            public string ownerName;
        }
    }