force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>US-681
To select Category of case, dependent on Sub Type picklist
Generated manuaaly</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SQ Instrument &amp; Control Software</fullName>
            </value>
            <value>
                <fullName>Analysis Software</fullName>
            </value>
            <value>
                <fullName>Library Preparation</fullName>
            </value>
            <value>
                <fullName>Microarray</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>LIMS</fullName>
            </value>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Application / Reagent Performance</fullName>
            </value>
            <value>
                <fullName>Change Order Confirmation</fullName>
            </value>
            <value>
                <fullName>Conversion / Ship Schedule</fullName>
            </value>
            <value>
                <fullName>Documentation &amp; Support Tool</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Instrumentation</fullName>
            </value>
            <value>
                <fullName>Logistics / Supply Chain</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>MyIllumina</fullName>
            </value>
            <value>
                <fullName>MyIllumina Feature Request</fullName>
            </value>
            <value>
                <fullName>New Order</fullName>
            </value>
            
            <value>
                <fullName>Oligo Orders</fullName>
            </value>
            <value>
                <fullName>Order Entry Error</fullName>
            </value>
            <value>
                <fullName>Order Expedite</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>PCN</fullName>
            </value>
            <value>
                <fullName>PON</fullName>
            </value>
            <value>
                <fullName>PQN</fullName>
            </value>
            
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Quotes</fullName>
            </value>
            <value>
                <fullName>Redirect - Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Redirect - Sales</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Upgrades</fullName>
            </value>
            <value>
                <fullName>Unplanned Maintenance</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Shipment Status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Closed_with_Associated_Codes__c.field-meta.xml
<CustomField>
    <fullName>Closed_with_Associated_Codes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-25233 this field has been used to check when a case is closed with associated codes attached to it</description>
    <label>Closed with Associated Codes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Call_Resolution__c.field-meta.xml
<CustomField>
    <fullName>First_Call_Resolution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-1304 -  As a Technical Support, Customer Support and Field Service user can view the Inquiry  case record 
Manually check on checkbox</description>
    <label>First Call Resolution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Qualtrics_Survey_Link__c.field-meta.xml
<CustomField>
    <fullName>Qualtrics_Survey_Link__c</fullName>
    <description>Qualtrics survey link for a contact on Case.</description>
    <label>Qualtrics Survey Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sent_to_Qualtrics__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Qualtrics__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Qualtrics Surveys: This checkbox will be checked whenever a case record triggers a Qualtrics Survey</description>
    <label>Sent to Qualtrics</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>US-681
To select Sub Type of Case
Generated manually</description>
    <label>Sub Type</label>
<!--QACM-40-->
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Customer Facing Notifications</fullName>
            </value>
            <value>
                <fullName>Billable Service</fullName>
            </value>
            <value>
                <fullName>Repair Center (Depot)</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Service Support</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>General Issue</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/WeChatFollower__c.field-meta.xml
<CustomField>
    <fullName>WeChatFollower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to WeChat Follower.</description>
    <label>WeChat Follower</label>
    <referenceTo>Charket__WeChatFollower__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Inquiry.recordType-meta.xml
<RecordType>
    <fullName>Inquiry</fullName>
    <active>true</active>
    <businessProcess>Inquiry</businessProcess>
    <description>A communication that concerns procedural matters that can be resolved through training or guidance, requests information related to product after it has been released for distribution or seeks information regarding services offered by Illumina.</description>
    <label>Inquiry</label>
</RecordType>

force-app/main/default/objects/Charket__WeChatAccount__c/Charket__WeChatAccount__c.object-meta.xml
<CustomObject>
    <label>WeChat Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charket__WeChatAccount__c/fields/Charket__AppId__c.field-meta.xml
<CustomField>
    <fullName>Charket__AppId__c</fullName>
    <label>App ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charket__WeChatAccount__c/fields/Charket__Type__c.field-meta.xml
<CustomField>
    <fullName>Charket__Type__c</fullName>
    <inlineHelpText>Subscribe: 订阅号
Service: 服务号
Provide businesses and Organization a more robust business services and user management capabilities. Mean to help companies quickly implement the new number of public service platform.
Subscription
Provide a new way of in</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subscription Account</fullName>
            </value>
            <value>
                <fullName>Service Account</fullName>
                <default>true</default>
                <label>Service Account</label>
            </value>
            <value>
                <fullName>Mini Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charket__WeChatAccount__c/fields/Charket__WeChatOriginId__c.field-meta.xml
<CustomField>
    <fullName>Charket__WeChatOriginId__c</fullName>
    <externalId>true</externalId>
    <label>WeChat Origin ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Charket__WeChatFollower__c/Charket__WeChatFollower__c.object-meta.xml
<CustomObject>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charket__WeChatFollower__c/fields/Charket__Contact__c.field-meta.xml
<CustomField>
    <fullName>Charket__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>WeChat Followers</relationshipLabel>
    <relationshipName>WeChatFollowers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charket__WeChatFollower__c/fields/Charket__IsFollowing__c.field-meta.xml
<CustomField>
    <fullName>Charket__IsFollowing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Following</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Charket__WeChatFollower__c/fields/Charket__Type__c.field-meta.xml
<CustomField>
    <fullName>Charket__Type__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charket__WeChatFollower__c/fields/Charket__WeChatAccount__c.field-meta.xml
<CustomField>
    <fullName>Charket__WeChatAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WeChat Account</label>
    <referenceTo>Charket__WeChatAccount__c</referenceTo>
    <relationshipLabel>WeChat Followers</relationshipLabel>
    <relationshipName>WeChatFollowers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charket__WeChatFollower__c/fields/IsEmailVerified__c.field-meta.xml
<CustomField>
    <fullName>IsEmailVerified__c</fullName>
    <description>Checkbox to check whether the email id is verified or not.</description>
    <defaultValue>false</defaultValue>
    <label>Email Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>DCP-857 Indicate the contact is active or not.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestQualtricsAPISurveyLinkReader.cls
/* @ author      : Vaibhav
* @ date         : 15 Jun 2021
* @ Description  : TestQualtricsAPISurveyLinkReader is the test class for the QualtricsAPISurveyLinkReader
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Vaibhav               15 Jun 2021                 DCP-46141        Initial version
* Vineeta				24 Nov 2023					INC0500807		To tet oagination in getQualtricsSurveyLink
*/
@isTest
public with sharing class TestQualtricsAPISurveyLinkReader {
    /*  @author      :Vaibhav
     *  @description :Setup method
     **/
	@TestSetup
    static void setupData()
    {
        Account objAcc = TestDataAccount.getNewAccount();   
        Contact con = new Contact(FirstName = 'testfirstname', LastName = 'testlastname', Is_Active__c = true, AccountID = objAcc.Id ,Email='test@gmail.com.invalid' , Phone = '1234567890');
        insert con;
        Charket__WeChatAccount__c weChatAcc = new Charket__WeChatAccount__c(Charket__AppId__c='wx5be7c34117b39da9',Name='WeChat Account',Charket__Type__c='Service Account',Charket__WeChatOriginId__c='gh_322a115b01e1');
        insert weChatAcc;
        Charket__WeChatFollower__c weChatFollower= new  Charket__WeChatFollower__c( Charket__WeChatAccount__c=weChatAcc.Id ,Charket__Contact__c=con.id,Charket__IsFollowing__c=true,IsEmailVerified__c=true);
        insert weChatFollower;
        Case cs = TestDataCase.initServiceRequestCase(con);
        cs.recordTypeid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Inquiry').getRecordTypeId();
        cs.Sub_Type__c = 'Order';
        cs.Category__c = 'New Order'; 
        cs.Status = 'In Progress';
        cs.SuppliedEmail = 'test@gmail.com.invalid';
        cs.Closed_with_Associated_Codes__c = false;
        cs.origin=cases.STRING_CASE_ORIGIN_WECHAT;
        cs.WeChatFollower__c = weChatFollower.Id;
        cs.status=System.label.CaseStatusReopenedInProgress;
        cs.First_Call_Resolution__c=true;        
        insert cs;        
    }
    /*  @author      :Vineeta Verma
     *  @description :To test Qualtrics API Callout for Survey Link Generation when contact found in First callout response 
    **/
    @isTest
    public static void testQualtricsCallout() {
        StaticResource endpoint = [SELECT Id,Name, Body FROM StaticResource WHERE Name = 'QualtricsSurveyFirstEndpoint' LIMIT 1];
        String qualtricsSurveyFirstEndpoint = endpoint.Body.toString();
        MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
        multimock.setStaticResource(qualtricsSurveyFirstEndpoint+Label.Qualtrics_Survey_ID,'QuatricsSurveyWIthContactMock');
        multimock.setStatusCode(200);
        multimock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, multimock);
        Case caseObj = [Select Id,Sent_to_Qualtrics__c from Case where SuppliedEmail = 'test@gmail.com.invalid' limit 1];
        caseObj.Sent_to_Qualtrics__c = true;
        Test.StartTest();
        update caseObj;
        Test.StopTest();
        Case caseObjUpdated = [Select Id,Sent_to_Qualtrics__c,Qualtrics_Survey_Link__c from Case where SuppliedEmail = 'test@gmail.com.invalid' limit 1];
        System.assertNotEquals('', caseObjUpdated.Qualtrics_Survey_Link__c, 'Qualtrics Survey Link Generated');
        
    }
    /*  @author      :Vineeta Verma
     *  @description :To test Qualtrics API Callout for Survey Link Generation when contact found in next callout response 
    **/
    @isTest
    public static void testQualtricsCalloutNextPg() {
        Map<String,String> endpoints = new Map<String,String>();
        for(StaticResource endpoint : [SELECT Id,Name, Body FROM StaticResource WHERE Name = 'QualtricsSurveyFirstEndpoint' or Name='QualtricsSurveySecEndpoint' LIMIT 2]){
            endpoints.put(endpoint.Name, endpoint.Body.toString());
        }
        MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
        multimock.setStaticResource(endpoints.get('QualtricsSurveyFirstEndpoint')+Label.Qualtrics_Survey_ID, 'QualtricsSurveyNoCononFirstMock');
        multimock.setStaticResource(endpoints.get('QualtricsSurveySecEndpoint'),'QuatricsSurveySecondMock');
        multimock.setStatusCode(200);
        multimock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, multimock);
        Case caseObj = [Select Id,Sent_to_Qualtrics__c from Case where SuppliedEmail = 'test@gmail.com.invalid' limit 1];
        caseObj.Sent_to_Qualtrics__c = true;
        Test.StartTest();
        update caseObj;
        Test.StopTest();
        Case caseObjUpdated = [Select Id,Sent_to_Qualtrics__c,Qualtrics_Survey_Link__c from Case where SuppliedEmail = 'test@gmail.com.invalid' limit 1];
        System.assertNotEquals('', caseObjUpdated.Qualtrics_Survey_Link__c, 'Qualtrics Survey Link Generated');
        
    }
    /*  @author      :Vineeta Verma
     *  @description :To test Qualtrics API Callout for Survey Link Generation when no contact found in any callout response 
    **/
     @isTest 
    public static void testQualtricsCalloutNoContact() {
        Map<String,String> endpoints = new Map<String,String>();
        for(StaticResource endpoint : [SELECT Id,Name, Body FROM StaticResource WHERE Name = 'QualtricsSurveyFirstEndpoint' or Name='QualtricsSurveySecEndpoint' LIMIT 2]){
            endpoints.put(endpoint.Name, endpoint.Body.toString());
        }
        MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
        multimock.setStaticResource(endpoints.get('QualtricsSurveyFirstEndpoint')+Label.Qualtrics_Survey_ID, 'QualtricsSurveyNoCononFirstMock');
        multimock.setStaticResource(endpoints.get('QualtricsSurveySecEndpoint'),'QualtricsSurveyNoCononSecMock');
        multimock.setStatusCode(200);
        multimock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, multimock);
        Case caseObj = [Select Id,Sent_to_Qualtrics__c from Case where SuppliedEmail = 'test@gmail.com.invalid' limit 1];
        caseObj.Sent_to_Qualtrics__c = true;
        Test.StartTest();
        update caseObj;
        Test.StopTest();
        Case caseObjUpdated = [Select Id,Sent_to_Qualtrics__c,Qualtrics_Survey_Link__c from Case where SuppliedEmail = 'test@gmail.com.invalid' limit 1];
        System.assertNotEquals('', caseObjUpdated.Qualtrics_Survey_Link__c, 'Qualtrics Survey Link Generated');
        
    }
}