force-app/main/default/objects/Case/fields/Date_of_Issue_Awareness__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_Awareness__c</fullName>
    <description>Date of issue awareness</description>
    <inlineHelpText>Date Illumina became aware of a Business Issue</inlineHelpText>
    <label>Date of Issue Awareness</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/Field_Action_Item__c.object-meta.xml
<CustomObject>
    <description>Junction object to relate Cases/Work orders with Field Actions &amp; Notifications.</description>
    <label>Field Action Item</label>
    <nameField>
        <displayFormat>FAI-{00000}</displayFormat>
        <label>Field Action Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Action Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Action_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the case for field actions &amp; notification</description>
    <inlineHelpText>If this field is blank, it will be populated when this record is saved (if applicable)</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Field_Action_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/fields/Field_Action_Notification__c.field-meta.xml
<CustomField>
    <fullName>Field_Action_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Field Action &amp; Notification</description>
    <label>Field Action &amp; Notification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 4) AND (3 OR 2)) OR (1 AND ( NOT (2) OR NOT (3)))</booleanFilter>
        <errorMessage>This is a locked FAN for formal monitoring that cannot be associated to this case/work order. For further information contact Product Support.</errorMessage>
        <filterItems>
            <field>Field_Action_Notification__c.Status__c</field>
            <operation>notContain</operation>
            <value>Locked</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Commercial and Revenue Operations</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.Name</field>
            <operation>equals</operation>
            <value>GIS</value>
        </filterItems>
        <filterItems>
            <field>Field_Action_Notification__c.Status__c</field>
            <operation>contains</operation>
            <value>Locked</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Field_Action_Notification__c</referenceTo>
    <relationshipLabel>Field Action Items</relationshipLabel>
    <relationshipName>Field_Action_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/fields/Field_Action_Notification_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Action_Notification_Record_Type__c</fullName>
    <description>To capture the record type of the field actions &amp; notification</description>
    <formula>Field_Action_Notification__r.RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/Field_Action_Notification__c.object-meta.xml
<CustomObject>
    <description>This object keeps track of Recalls, Tracking Escalations, and Notifications such as PQN, PCN, PON, etc.</description>
    <label>Field Action &amp; Notification</label>
    <nameField>
        <displayFormat>FAN-{0000}</displayFormat>
        <label>Field Action &amp; Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Actions &amp; Notifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Action_Notification__c/recordTypes/Notification.recordType-meta.xml
<RecordType>
    <fullName>Notification</fullName>
    <active>true</active>
    <label>Notification</label>
</RecordType>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Field_Action_Notification_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Action_Notification_Record_Type__c</fullName>
    <description>To capture the record type of FAN. Populated from SFM.</description>
    <label>Field Action &amp; Notification Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
    <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestFieldActionItemsSelector.cls
/***************************************************************************************************************************************
 * NAME   : TestFieldActionItemsSelector
 * DESCRIPTION  : TestClass for FieldActionItemsSelector
 *    
 * @AUTHOR : Prashanth
 * @DATE   : 24-June-2019 
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Prashanth             24-June-2019             Initial Version
  ****************************************************************************************************************************************/ 
@isTest
private class TestFieldActionItemsSelector {
    static Case cs;
    static Field_Action_Notification__c fAN;
    /**
    * method : createdata
    * Description: method is to create test data.
    * params: NA
    * return: void
    * author: prashanth
    **/
    @testSetup
    static void createData(){
        //create Case record
        cs = TestDataCase.initNewCase('Business Issue', 'Initiated', 'Phone - Field');
        cs.Date_of_Issue_Awareness__c = Date.Today();
        insert cs;
        // To create a fAN record of record type "Notification"
        fAN =TestDataFieldService.createFAN('Notification');
        insert fAN;
    }
     /**
    * method : testFieldActionItemsSelector
    * Description: method is to test selectFieldActionItemsByFANRecType,selectFieldActionItemsByCaseId methods.
    * params: NA
    * return: void
    * author: prashanth
    **/
    static testMethod void fieldActionItemsSelectorTest(){ 
        createData();
        // To create a new fAI record With fAN record type "Notification"
        Field_Action_Item__c fAI =TestDataFieldService.createFAI(CS.Id,fAN.Id);
        SVMXC__Service_Order__c woObj=[Select Id from SVMXC__Service_Order__c where SVMXC__Case__c=:CS.Id];
        insert fAI;
        Test.StartTest();
            //test selectFieldActionItemsByFANRecType method 
            FieldActionItemsSelector selector = new FieldActionItemsSelector();
            List<Field_Action_Item__c> lstFieldActionItemsList = selector.selectFieldActionItemsByCaseORWOId(new set<Id>{woObj.Id},new set<Id>{CS.Id});
            System.assertEquals(lstFieldActionItemsList[0].Id , fAI.Id);
            List<Field_Action_Item__c> lstFieldActionItems = selector.selectFieldActionItemsByFANRecType(new Set<Id> {CS.Id}, 'Notification');
            System.assertEquals('Notification',lstFieldActionItems[0].Field_Action_Notification_Record_Type__c);
            //test selectFieldActionItemsByCaseId method
            List<Field_Action_Item__c> lstFieldActionItems1 = selector.selectFieldActionItemsByCaseId(new Set<Id> {cs.Id});
            System.assertEquals(lstFieldActionItems1[0].Case__c ,cs.Id);
        Test.StopTest();
    }
}