force-app/main/default/objects/Case/fields/Date_of_Issue_Awareness__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_Awareness__c</fullName>
    <description>Date of issue awareness</description>
    <inlineHelpText>Date Illumina became aware of a Business Issue</inlineHelpText>
    <label>Date of Issue Awareness</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_Information__c.field-meta.xml
<CustomField>
    <fullName>Requested_Information__c</fullName>
    <description>Provide requested information in detail.</description>
    <label>Requested Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Suspected_Causes_Experiments_Done__c.field-meta.xml
<CustomField>
    <fullName>Suspected_Causes_Experiments_Done__c</fullName>
    <description>Describe the causes suspected or the experiments performed.</description>
    <label>Suspected Causes / Experiments Done</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component SN</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Case1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product for which customer is seeking support. Reference to Product2 object.</description>
    <inlineHelpText>Choose or enter the Product name for which the customer is seeking support.</inlineHelpText>
    <label>Component Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/Field_Action_Notification__c.object-meta.xml
<CustomObject>
    <description>This object keeps track of Recalls, Tracking Escalations, and Notifications such as PQN, PCN, PON, etc.</description>
    <label>Field Action &amp; Notification</label>
    <nameField>
        <displayFormat>FAN-{0000}</displayFormat>
        <label>Field Action &amp; Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Actions &amp; Notifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Action_Notification__c/fields/Affected_Product__c.field-meta.xml
<CustomField>
    <fullName>Affected_Product__c</fullName>
    <description>To capture the products that are affected</description>
    <label>Affected Product</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Customer_Messaging__c.field-meta.xml
<CustomField>
    <fullName>Customer_Messaging__c</fullName>
    <description>To capture the impact of escalation on customer or business.</description>
    <label>Customer Messaging</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Escalation_Type__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Type__c</fullName>
    <description>To capture the type of escalation.</description>
    <label>Escalation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Array Consumables</fullName>
            </value>
            <value>
                <fullName>Sequencing Consumables</fullName>
            </value>
            <value>
                <fullName>Library Prep Consumables</fullName>
            </value>
            <value>
                <fullName>Instrumentation Hardware</fullName>
            </value>
            <value>
                <fullName>Control Software &amp; Networking</fullName>
            </value>
            <value>
                <fullName>Analysis Software</fullName>
            </value>
            <value>
                <fullName>Documentation &amp; Support Tools</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Mitigations__c.field-meta.xml
<CustomField>
    <fullName>Mitigations__c</fullName>
    <description>To capture the customer messages.</description>
    <label>Mitigations</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Original_Case__c.field-meta.xml
<CustomField>
    <fullName>Original_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the Original Case. Lookup to cases</description>
    <label>Original Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Field_Action_Notification1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Requested_Information__c.field-meta.xml
<CustomField>
    <fullName>Requested_Information__c</fullName>
    <description>To capture the information.</description>
    <label>Requested Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Resolution_Date__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Date__c</fullName>
    <description>To capture the resolution date.</description>
    <label>Resolution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>To define the severity of the escalation.</description>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Customer - Low &amp; Business - Low</fullName>
            </value>
            <value>
                <fullName>Customer - Low &amp; Business - Medium</fullName>
            </value>
            <value>
                <fullName>Customer - Low &amp; Business - High</fullName>
            </value>
            <value>
                <fullName>Customer - Medium &amp; Business - Low</fullName>
            </value>
            <value>
                <fullName>Customer - Medium &amp; Business - Medium</fullName>
            </value>
            <value>
                <fullName>Customer - Medium &amp; Business - High</fullName>
            </value>
            <value>
                <fullName>Customer - High &amp; Business - Low</fullName>
            </value>
            <value>
                <fullName>Customer - High &amp; Business - Medium</fullName>
            </value>
            <value>
                <fullName>Customer - High &amp; Business - High</fullName>
            </value>
            <value>
                <fullName>To Be Determined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To capture the status of the escalation.</description>
    <inlineHelpText>The status of the Field Action &amp; Notification reflects if it is Open, Locked or Closed. Locked FANs are used for formal monitoring. For further information contact Product Support.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Monitoring - no investigation</fullName>
            </value>
            <value>
                <fullName>Investigation ongoing</fullName>
            </value>
            <value>
                <fullName>Investigation complete - monitoring</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Locked Assessment</fullName>
            </value>
            <value>
                <fullName>Locked Monitoring - no investigation</fullName>
            </value>
            <value>
                <fullName>Locked Investigation ongoing</fullName>
            </value>
            <value>
                <fullName>Locked Investigation complete - monitoring</fullName>
            </value>
            <value>
                <fullName>Locked Open</fullName>
            </value>
            <value>
                <fullName>Locked Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Suspected_Causes_Experiments_Done__c.field-meta.xml
<CustomField>
    <fullName>Suspected_Causes_Experiments_Done__c</fullName>
    <description>To capture the causes and the experiments conducted on escalations.</description>
    <label>Suspected Causes / Experiments Done</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/fields/Symptom__c.field-meta.xml
<CustomField>
    <fullName>Symptom__c</fullName>
    <description>To capture the sympton of escalations.</description>
    <label>Symptom</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Field_Action_Notification__c/recordTypes/Notification.recordType-meta.xml
<RecordType>
    <fullName>Notification</fullName>
    <active>true</active>
    <label>Notification</label>
</RecordType>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
    <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>R00N70000001hzchEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Status__c</fullName>
    <description>Current status of the installed product.</description>
    <inlineHelpText>Current status of the installed product.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipped</fullName>
                <default>true</default>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>Returned Vendor</fullName>
            </value>
            <value>
                <fullName>Non Calibrated</fullName>
            </value>
            <value>
                <fullName>Awaiting Installation</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Scrapped</fullName>
            </value>
            <value>
                <fullName>Loaned</fullName>
            </value>
            <value>
                <fullName>De-Installed</fullName>
            </value>
            <value>
                <fullName>Calibrated</fullName>
            </value>
            <value>
                <fullName>Not Calibrated Expired</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestFieldActionNotification.cls
/**
* @File Name : TestFieldActionNotification.cls
* @Description : TestClass for Field_Action_Notification__c : After Insert and Update Flow
* @Author : Dhairya Shah
* @Last Modified By : Dhairya Shah
* @Last Modified On : December 2, 2024
**/
@isTest(seeAllData = false)
public class TestFieldActionNotification {
	public static final string STRING_CASE_RECORDTYPENAME = 'Business Issue';
    public static final string STRING_CASE_STATUS = 'Initiated';
    public static final string STRING_CASE_ORIGIN = 'Phone - CS';
    public static final string STRING_FAN_RECORDTYPENAME = 'Tracking Escalation';
    public static final string STRING_FAN_SUBJECT = 'Testing Tracking Escalation';
    public static final string STRING_FAN_STATUS = 'Closed';
    public static final string STRING_IP_STATUS = 'Installed';
    
    static Field_Action_Notification__c recFAN;

	static testMethod void testFieldActionNotificationMethod(){
	
        // Set up the test user with the appropriate profile
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Integration SAP Service' LIMIT 1];
        User testUser = new User(
            Username = 'testuser1234@examillu.com',
            Email = 'testuser@example.com',
            LastName = 'TestIllu',
            Alias = 'test',
            ProfileId = testProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive = true
        );
        insert testUser;

        // Set the context user to the test user
        System.runAs(testUser) {
            // Create an installed product
            SVMXC__Installed_Product__c insproduct = new SVMXC__Installed_Product__c();
            insproduct.Name = 'Test install product';
            insproduct.SVMXC__Status__c = STRING_IP_STATUS;
            insert insproduct;
            
            // Create a product
            Product2 prod = new Product2();
            prod.Name = 'Test Product';
            insert prod;
            
            Case cs = TestDataCase.initNewCase(STRING_CASE_RECORDTYPENAME, STRING_CASE_STATUS, STRING_CASE_ORIGIN);
            cs.SVMXC__Component__c = insproduct.Id;
            cs.SVMXC__Product__c = prod.Id;
            cs.Status = 'New'; // Set to a status that won't trigger the validation
            cs.Date_of_Issue_Awareness__c = Date.Today();  
            Cases.skipCaseTrigger = true;
            insert cs;

            // To create a FAN record of record type "Notification"
            recFAN = TestDataFieldService.createFANForTE(STRING_FAN_RECORDTYPENAME, STRING_FAN_SUBJECT,STRING_FAN_STATUS);
            recFAN.Original_Case__c = cs.Id;
            recFAN.Severity__c = 'Low';
            recFAN.Escalation_Type__c = 'Array Consumables';
            recFAN.Symptom__c = 'Test';
            recFAN.Customer_Messaging__c = 'Test';
            recFAN.Requested_Information__c = 'Test';
            recFAN.Mitigations__c = 'Test';
            recFAN.Affected_Product__c = 'Test';
            recFAN.Suspected_Causes_Experiments_Done__c = 'Test';

            Test.StartTest();
            insert recFAN;
            Test.StopTest();
            
            Field_Action_Notification__c fieldActionRetrieved = [SELECT Resolution_Date__c, Status__c FROM Field_Action_Notification__c WHERE Id = :recFAN.Id];
            if(System.today() < fieldActionRetrieved.Resolution_Date__c){
                System.assertEquals(System.today().addDays(1), fieldActionRetrieved.Resolution_Date__c,'Resolution date should be today');
            } else {
                System.assertEquals(System.today(), fieldActionRetrieved.Resolution_Date__c,'Resolution date should be today');
            }
           
        }
	}
}