force-app/main/default/objects/Case/fields/Investigation_Summary_Comments__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Summary_Comments__c</fullName>
    <description>To capture the Review comments of QA</description>
    <label>Investigation Summary/Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Review__c.field-meta.xml
<CustomField>
    <fullName>QA_Review__c</fullName>
    <description>To capture details of QA review</description>
    <label>QA Review</label>
<!--QACM-40-->
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refer to Existing/Prior Investigation</fullName>
            </value>
            <value>
                <fullName>See Investigation Summary/Comments</fullName>
            </value>
            <value>
                <fullName>No Further Investigation Required</fullName>
            </value>
            <value>
                <fullName>Further Investigation Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
			<value>
                <fullName>In Progress - Awaiting Internal SME Review</fullName>
            </value>
            <value>
                <fullName>Transferred to ETQ</fullName>
            </value>
            <value>
                <fullName>Non IVD Product</fullName>
            </value>
            
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Quick_Text__c/Custom_Quick_Text__c.object-meta.xml
<CustomObject>
    <description>Used to capture templated quick text that can be added and concatenated to
configurable text fields within SFDC.</description>
    <label>Custom Quick Text</label>
    <nameField>
        <label>Custom Quick Text Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Quick Text</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Quick_Text__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <description>Specific templated text that is added and appended to a text field.  Filled by SS_Edit Quick Text Template permission set assignees.</description>
    <label>Template</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QaReviewTemplateController.cls
/**
 *    @author Avina
 *    @date   24-Aug-2022
 *    @description: Controller Class for LWC insertQuickText
 *    Modification Log:
 *    --------------------------------------------------------------------------------------------------- 
 *    Developer                      Date                Description
 *    Avina                          24-Aug-2022         QACM-88 Created QaReviewTemplateController class
 *    ---------------------------------------------------------------------------------------------------
 *                    
 */
public with sharing class QaReviewTemplateController {
    private static final String LOG_TITLE = 'QaReviewTemplateController';
    public static final Integer CHARACTER_LIMIT = 32000;
    public static final String CASE_OBJECT_API = 'Case';
    public static final String SUCCESS_MESSAGE = 'Successfully Updated';
    public static final String LIMIT_EXCEED = 'Limit Exceed' ;
    public static final String QA_REVIEW_IS_EMPTY = 'QA Review Field Is Empty' ;
    public static final String QA_REVIEW = 'In Progress' ;

    /**
    *  @author Avina
    *  @description - QACM-88 Method to retieve Custom Quick Text records.
    *                 
    *  @PARAM :  Map<string,string> getTemplateData
    *  @RETURN:  String
    */ 

    @AuraEnabled(cacheable=true)
    public static Map<string,string> getTemplateData(string objectName) {
        ilib_LogEvent.push(LOG_TITLE + '.getTemplateData()');
        Map<String,string> templateDataMap = new Map<string,string>();
        try {
            List<Custom_Quick_Text__c> quickTextList = new CustomQuickTextSelector().selectCustomQuickTextbyObject(objectName);
            ilib_LogEvent.info('quickTextList-->:'+quickTextList);
            for ( Custom_Quick_Text__c quicText : quickTextList) {
                templateDataMap.put(quicText.Name,quicText.Template__c);
            }
            ilib_LogEvent.pop();
            return templateDataMap; 
        } Catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }         
    }

    /**
    *  @author Avina
    *  @description - QACM-88 Method to Update Investigation Summary field with search template value.
    *                 
    *  @PARAM :  Id recordId,String impactValue,String objectAPI
    *  @RETURN:  Boolean
    */ 
    @AuraEnabled
    public static String upsertSummaryField(Id recordId,String impactValue,String objectAPI) {
        String isUpdated;
        ilib_LogEvent.push(LOG_TITLE + '.upsertSummaryField()');
        String templateDataWithNewLine;
        String templateDataWithoutNewLine;
        Set<Id> caseId = new Set<Id>();
        caseId.add(recordId);
        try {
            Date todayDate = date.today();
            String currentDateFormat = DateTime.newInstance(todayDate.year(),todayDate.month(),todayDate.day()).format('dd-MMM-YYYY');
            String[] currentDateArray = currentDateFormat.split('-');
            String currentDate = currentDateArray[0]+'-'+currentDateArray[1].toUpperCase()+'-'+currentDateArray[2];
            
            if(objectAPI == CASE_OBJECT_API) {
                List<Case> caseRecord = new CasesSelector().selectCases(caseId);
                if(caseRecord[0].QA_Review__c == null || caseRecord[0].QA_Review__c == '' || String.isBlank(caseRecord[0].QA_Review__c)) {
                    ilib_LogEvent.pop();
                    return QA_REVIEW_IS_EMPTY;
                }
                templateDataWithNewLine = caseRecord[0].Investigation_Summary_Comments__c+'\n'+currentDate+' '+(UserInfo.getFirstName()).substring(0,1)+'.'+UserInfo.getLastName()+': '+impactValue;
                templateDataWithoutNewLine = currentDate+' '+(UserInfo.getFirstName()).substring(0,1)+'.'+UserInfo.getLastName()+': '+impactValue;

                if(caseRecord[0].Investigation_Summary_Comments__c!=null && templateDataWithNewLine.length()<=CHARACTER_LIMIT) {
                    isUpdated = updateSummaryField(caseRecord[0].Id,templateDataWithNewLine);
                } else if(caseRecord[0].Investigation_Summary_Comments__c==null && templateDataWithoutNewLine.length()<=CHARACTER_LIMIT) {
                    isUpdated = updateSummaryField(caseRecord[0].Id,templateDataWithoutNewLine);
                } else {
                    isUpdated = LIMIT_EXCEED;
                }
            }
            
            ilib_LogEvent.pop();
            return isUpdated;
        } Catch(Exception e) {
           throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    *  @author Avina
    *  @description - QACM-88 Method to Update Investigation Summary field with search template value.
    *                 
    *  @PARAM :  Id caseId,String summaryValue
    *  @RETURN:  Boolean
    */ 
    public static String updateSummaryField(Id caseId,String summaryValue) {
        ilib_LogEvent.push(LOG_TITLE + '.upsertSummaryField()');
        Case updateCase = new Case();
        String status;
        try {
            updateCase.id=caseId;
            updateCase.Investigation_Summary_Comments__c = summaryValue;
            if(updateCase!=null) {
                    update updateCase;
                    ilib_LogEvent.info('updateCase-->:'+updateCase);
                    status = SUCCESS_MESSAGE;                    
            }
            
            ilib_LogEvent.pop();
            return status;
        } Catch(Exception e) {
           throw new StringException(e);
        }
        
    }

}