force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field will get value from Territory Region field of Account</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMR</fullName>
            </value>
	    <value>
                <fullName>AMEA</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
		<isActive>false</isActive>
                <label>APJ</label>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
	    <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <isActive>false</isActive>
                <label>EMEA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interface_Log__c/Interface_Log__c.object-meta.xml
<CustomObject>
    <description>Details from integration calls between Salesforce and other systems</description>
    <label>Interface Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interface Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_Team_Notification__c/MS_Team_Notification__c.object-meta.xml
<CustomObject>
    <description>Junction object between Case and Notification detail used to send notification.</description>
    <label>MS Team Notification</label>
    <nameField>
        <displayFormat>MSTN-{00000}</displayFormat>
        <label>MS Team Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MS Team Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_Team_Notification__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This is a lookup to a case record</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>MS Team Notifications</relationshipLabel>
    <relationshipName>MS_Team_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MS_Team_Notification__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Flag to determine active MS Team Notification</description>
    <defaultValue>true</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MS_Team_Notification__c/fields/Last_NotificationTime__c.field-meta.xml
<CustomField>
    <fullName>Last_NotificationTime__c</fullName>
    <description>This is to capture last notification datetime</description>
    <label>Last NotificationTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MS_Team_Notification__c/fields/Notification_Detail__c.field-meta.xml
<CustomField>
    <fullName>Notification_Detail__c</fullName>
    <description>This is to determine notification detail</description>
    <label>Notification Detail</label>
    <referenceTo>Notification_Detail__c</referenceTo>
    <relationshipLabel>MS Team Notifications</relationshipLabel>
    <relationshipName>MS_Team_Notifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MS_Team_Notification__c/fields/Notification_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Notification_Eligible__c</fullName>
    <description>This formula field is to determine the eligibility of notification</description>
    <formula>IF(
   Notification_Detail__r.Is_Instant_Notification__c,
   false,
   ( NOW()-Case__r.CreatedDate)*24 &gt;  Notification_Detail__r.Trigger_Notification_After_in_HRS__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notification Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MS_Team_Notification__c/fields/Re_Trigger_Count__c.field-meta.xml
<CustomField>
    <fullName>Re_Trigger_Count__c</fullName>
    <description>Field to capture the trigger count of notification</description>
    <defaultValue>0</defaultValue>
    <label>Re-Trigger Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/Notification_Detail__c.object-meta.xml
<CustomObject>
    <label>Notification Detail</label>
    <nameField>
        <label>Notification Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Detail__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>Flag to Determine notification detail is active</description>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Is_Instant_Notification__c.field-meta.xml
<CustomField>
    <fullName>Is_Instant_Notification__c</fullName>
    <description>Flag to determine instant creation of notification details</description>
    <defaultValue>false</defaultValue>
    <label>Is Instant Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/MS_Teams_Recipient__c.field-meta.xml
<CustomField>
    <fullName>MS_Teams_Recipient__c</fullName>
    <description>Endpoint of webhook</description>
    <label>MS Teams Recipient</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Notification_Template__c.field-meta.xml
<CustomField>
    <fullName>Notification_Template__c</fullName>
    <description>To capture notification Template</description>
    <label>Notification Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Recipient_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Name__c</fullName>
    <description>Name of queue or Person</description>
    <label>Recipient Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region for which notification will work</description>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
	    <value>
                <fullName>AMEA</fullName>
            </value>
            <value>
                <fullName>AMR</fullName>
            </value>
            
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Rule_Syntax__c.field-meta.xml
<CustomField>
    <fullName>Rule_Syntax__c</fullName>
    <description>To capture rule syntax of notification</description>
    <label>Rule Syntax</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Send_Only_After_Hours__c.field-meta.xml
<CustomField>
    <fullName>Send_Only_After_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, notifications will only be sent during holidays and non-business hours.</description>
    <inlineHelpText>If this is checked, notifications will only be sent during holidays and non-business hours.</inlineHelpText>
    <label>Send Only After Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Send_Only_During_Office_Hours__c.field-meta.xml
<CustomField>
    <fullName>Send_Only_During_Office_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, notifications will only be sent during office hours. Notifications will not be sent on holidays.</description>
    <inlineHelpText>If this is checked, notifications will only be sent during office hours. Notifications will not be sent on holidays.</inlineHelpText>
    <label>Send Only During Office Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/Trigger_Notification_After_in_HRS__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Notification_After_in_HRS__c</fullName>
    <description>The notification will be triggered once all criteria have been met for the amount of time defined here.</description>
    <inlineHelpText>The notification will be triggered once all criteria have been met for the amount of time defined here.</inlineHelpText>
    <label>Trigger Notification After (in HRS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Detail__c/fields/User_Group__c.field-meta.xml
<CustomField>
    <fullName>User_Group__c</fullName>
    <description>User group for which notification is defined.</description>
    <label>User Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>TS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This field is used to indicate where the user is located</description>
    <inlineHelpText>This field is used to indicate where the user is located</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMR</fullName>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>APJ</fullName>
        <isActive>false</isActive>
        <label>APJ</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ScheduleBatchSendCaseTeamsNotification.cls
/**
 *    @author KD
 *    @date   30-March-2021
 *    @description  Scheduled batch to send MS teams notification
 *    Modification Log:
 *    ---------------------------------------------------------------------------------------------------------------------------------
 *     Developer                      Date                Description
 *    ------------------------------------------------------------------------------------------------------------------------------------------------
 */
global with sharing class ScheduleBatchSendCaseTeamsNotification extends ilib_ScheduleAndBatch implements Database.Stateful, Database.AllowsCallouts{
    public List<MS_Team_Notification__c> lstMSTeamsNotificationToUpdate = new List<MS_Team_Notification__c>();
    public Map<Id,List<String>> mapOfNotificationIdtoCaseNumber = new Map<Id,List<String>>();
    public Map<Id,List<MS_Team_Notification__c>> mapOfNotificationIdToMSTeamNotification = new Map<Id,List<MS_Team_Notification__c>>();
    public static final Integer HTTP_SUCCESS_CODE = 200;
    public static ilib_LogInterface.LogDetails log;
    public DateTime dtTimeNow;
    public Set<String> setRegionGroupHoliday = new Set<String>();
    public static final String CODEPARAMTER_FREQUENCY = 'Case_Notification_Batch_Frequency';
    /*
    Constructor
    */
    public ScheduleBatchSendCaseTeamsNotification(){
        dtTimeNow = Datetime.now();
        setRegionGroupHoliday = CaseChangeEventsService.getHolidaysAndWorkingHours(dtTimeNow);
    }
    /* execute method */
    global override void execute(SchedulableContext sc)
    {   
        Datetime dtTimeNowScheduled = Datetime.now();
        Database.executeBatch(new ScheduleBatchSendCaseTeamsNotification(),100);
        String strHour =new CodeParametersSelector().selectCodeParameterByDeveloperName(new Set<String>{CODEPARAMTER_FREQUENCY})[0].Value__c;
        Integer offset = UserInfo.getTimezone().getOffset(dtTimeNowScheduled);
        Datetime dtlocal = dtTimeNowScheduled.addSeconds(offset/1000);
        Datetime dtdueDateTime = dtlocal.addHours(Integer.valueOf(strHour));
        String strCron = '0 0 '+String.valueOf(dtlocal.hourGMT()+Integer.valueOf(strHour))+' '+dtdueDateTime.dayGMT()+' '+dtdueDateTime.monthGmt()+' ? '+dtdueDateTime.yearGmt();
        System.debug(strCron);
        if(dtlocal.dayGMT() == dtdueDateTime.dayGMT() && !Test.isRunningTest()){
            system.schedule('ScheduleBatchSendCaseTeamsNotification'+String.valueOf(dtdueDateTime),strCron,new ScheduleBatchSendCaseTeamsNotification());
        }

    }
    /* start method to query records */
    global override Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'Select id,IsActive__c,Last_NotificationTime__c,Notification_Detail__c,Notification_Detail__r.Send_Only_During_Office_Hours__c,Notification_Detail__r.Send_Only_After_Hours__c,Notification_Detail__r.User_Group__c,Re_Trigger_Count__c,Case__c,Case__r.CaseNumber,Notification_Eligible__c,Case__r.Region__c,Case__r.Origin,Case__r.Owner.Type,Case__r.Owner.Name from MS_Team_Notification__c where IsActive__c = TRUE and Notification_Eligible__c = TRUE AND Notification_Detail__r.Is_Active__c = true';
        return Database.getQueryLocator(query);
    }
    /* method to execute logic for each chunk of records*/
    global override void execute(Database.BatchableContext bc, List<sobject> lstMSTeamsNotification){
        for(MS_Team_Notification__c objMSTeamNotification : (List<MS_Team_Notification__c>)lstMSTeamsNotification){
            //Check for holiday by checking region and user group
            if(objMSTeamNotification.Notification_Detail__r.Send_Only_During_Office_Hours__c && !setRegionGroupHoliday.isEmpty() && objMSTeamNotification.Case__r.Region__c != null && objMSTeamNotification.Case__r.Owner.Type == 'Queue' && String.isNotBlank(objMSTeamNotification.Notification_Detail__r.User_Group__c))
                if(setRegionGroupHoliday.contains(objMSTeamNotification.Case__r.Region__c+'-'+CaseChangeEventsService.getCaseUserGroup(objMSTeamNotification.Case__r.Owner.Name)) && objMSTeamNotification.Notification_Detail__r.User_Group__c == CaseChangeEventsService.getCaseUserGroup(objMSTeamNotification.Case__r.Owner.Name))
                    continue;
            if(objMSTeamNotification.Notification_Detail__r.Send_Only_After_Hours__c && objMSTeamNotification.Case__r.Region__c != null && objMSTeamNotification.Case__r.Owner.Type == 'Queue' && String.isNotBlank(objMSTeamNotification.Notification_Detail__r.User_Group__c)){
                if(setRegionGroupHoliday.isEmpty() || !setRegionGroupHoliday.contains(objMSTeamNotification.Case__r.Region__c+'-'+CaseChangeEventsService.getCaseUserGroup(objMSTeamNotification.Case__r.Owner.Name)) && objMSTeamNotification.Notification_Detail__r.User_Group__c == CaseChangeEventsService.getCaseUserGroup(objMSTeamNotification.Case__r.Owner.Name))
                    continue;
            }
            if(!mapOfNotificationIdtoCaseNumber.containsKey(objMSTeamNotification.Notification_Detail__c))
                mapOfNotificationIdtoCaseNumber.put(objMSTeamNotification.Notification_Detail__c,new List<String>());
            mapOfNotificationIdtoCaseNumber.get(objMSTeamNotification.Notification_Detail__c).add(objMSTeamNotification.Case__r.CaseNumber);
            if(!mapOfNotificationIdToMSTeamNotification.containsKey(objMSTeamNotification.Notification_Detail__c))
                mapOfNotificationIdToMSTeamNotification.put(objMSTeamNotification.Notification_Detail__c,new List<MS_Team_Notification__c>());
            mapOfNotificationIdToMSTeamNotification.get(objMSTeamNotification.Notification_Detail__c).add(objMSTeamNotification);
        }
    }
    /* Final method */
    global override void finish(Database.BatchableContext bc){
        try{
            MSTeamsNotificationSender instantiated = new MSTeamsNotificationSender();
            ilib_RestInterface.InterfaceDetails interfaceDetails = instantiated.interfaceDetails;
            List<Interface_Log__c> lstInterfaceLog = new List<Interface_Log__c>();
            List<Notification_Detail__c> lstAllNotificationDetails = [Select id,Is_Instant_Notification__c,MS_Teams_Recipient__c,Trigger_Notification_After_in_HRS__c,Notification_Template__c,Recipient_Name__c,Region__c,Send_Only_During_Office_Hours__c,Rule_Syntax__c,User_Group__c from Notification_Detail__c];
            for(Notification_Detail__c objNotification : lstAllNotificationDetails){
                if(!mapOfNotificationIdtoCaseNumber.containsKey(objNotification.id))
                    continue;
             
                MSTeamsNotificationSender.EmailResult  emailResult = MSTeamsNotificationSender.sendTeamsNotificationForCase(objNotification.MS_Teams_Recipient__c,objNotification.Notification_Template__c,objNotification.Recipient_Name__c,mapOfNotificationIdtoCaseNumber.get(objNotification.Id));
                log = ilib_LogInterface.initiateLog(interfaceDetails,'EndPoint : '+objNotification.MS_Teams_Recipient__c+' Body: '+emailResult.sendEmailBody);
                lstInterfaceLog.add(ilib_LogInterface.returnLogRecord(log,emailResult.sendEmailResultObject.isSuccess() ? ilib_LogInterface.RESULT_SUCCESS :ilib_LogInterface.RESULT_FAIL,emailResult.sendEmailBody,null,null));

                for(MS_Team_Notification__c objMSTeamNotification : mapOfNotificationIdToMSTeamNotification.get(objNotification.id)){
                    
                    if(emailResult.sendEmailResultObject.isSuccess()==false && Test.isRunningTest()==false)
                        objMSTeamNotification.Re_Trigger_Count__c = objMSTeamNotification.Re_Trigger_Count__c + 1;
                    else
                        objMSTeamNotification.Last_NotificationTime__c = dtTimeNow;
                    lstMSTeamsNotificationToUpdate.add(objMSTeamNotification);
                }

            }
            if(!lstMSTeamsNotificationToUpdate.isEmpty())
                update lstMSTeamsNotificationToUpdate;
            if(!lstInterfaceLog.isEmpty())
                upsert lstInterfaceLog;
        }catch(Exception e){
            
            ApexExceptions.emit('ScheduleBatchSendCaseTeamsNotification',e);
        }
    }
}