force-app/main/default/objects/Case/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component SN</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Case1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product for which customer is seeking support. Reference to Product2 object.</description>
    <inlineHelpText>Choose or enter the Product name for which the customer is seeking support.</inlineHelpText>
    <label>Component Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the work order for elevation case</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Elevation Case</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/Field_Action_Item__c.object-meta.xml
<CustomObject>
    <description>Junction object to relate Cases/Work orders with Field Actions &amp; Notifications.</description>
    <label>Field Action Item</label>
    <nameField>
        <displayFormat>FAI-{00000}</displayFormat>
        <label>Field Action Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Action Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Action_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the case for field actions &amp; notification</description>
    <inlineHelpText>If this field is blank, it will be populated when this record is saved (if applicable)</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Field_Action_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/fields/Field_Action_Notification_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Action_Notification_Record_Type__c</fullName>
    <description>To capture the record type of the field actions &amp; notification</description>
    <formula>Field_Action_Notification__r.RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/fields/Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the installed product on case and work order</description>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Field_Action_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the product related to case or work order.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Field_Action_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Action_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the work order for field action &amp; notification</description>
    <inlineHelpText>If this field is blank, it will be populated when this record is saved (if applicable)</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipName>Field_Action_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Field_Action_Notification_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Action_Notification_Record_Type__c</fullName>
    <description>To capture the record type of FAN. Populated from SFM.</description>
    <label>Field Action &amp; Notification Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
    <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Component</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product in which specialization would be required to service the work order. Calculated from installed product by OptiMax pre-calculation engine</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FieldActionItems.cls
/***************************************************************************************************************************************
* NAME   : FieldActionItems
* DESCRIPTION  : Domain class for FieldActionItemTrigger.
*                    
* @AUTHOR : Debanka
* @DATE   : 8-Sept-2018  
* 
* MODIFICATION LOG:  
* --------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
* --------------------------------------------------------------------------------------------------------------------------------------
* Debanka            	8-Sept-2018         Initial Version. Added logic to handle events handled before insert and before update
****************************************************************************************************************************************/ 
public class FieldActionItems extends ilib_SObjectDomain{

    public static final String STRING_FAN_RECORDTYPE = 'Notification';
    public static List<SVMXC__Service_Order__c> listWorkOrders = new List<SVMXC__Service_order__c>();
    public static List<Case> listCases = new List<Case>();

		/*
         * Constructor
         */
    public FieldActionItems(List<Field_Action_Item__c> sObjectList)
    {
        super(sObjectList);
    }

/*
* Boilerplate which is required for base class instantiation logic
*/
    public class Constructor implements ilib_SObjectDomain.IConstructable
    {
	/*Param - sobjectList  */
        public ilib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new FieldActionItems(sObjectList);
        }
    }
    /**
*  @author Debanka
*  @description - To be executed before inserting records for checking number of notifications 
*  @parameters : null
*  @return : void              
**/
    public override void onAfterInsert()
    {
        checkNoOfNotificationOnCase(); 
    }

		/*
		 * description - onAfterUpdate method
         */	
    public override void onAfterUpdate(Map<Id, SObject> oldRecords)
    { 
        checkNoOfNotificationOnCase(); 
    }

/**
*  @author Digvijay
*  @description - (DCP-39744)To be executed before inserting records for checking number of notifications 
*  @parameters : null
*  @return : void              
**/
     public override void onBeforeInsert()
    {

         Map<id,Id> mapWOtoCaseassociation=new Map<Id,Id>();
         //update the map with Case or  Work Order Id's as key
        for(Field_Action_Item__c objFAI : (List<Field_Action_Item__c>)records)
        {
                if(objFAI.Work_Order__c!=null ){
                    mapWOtoCaseassociation.put(objFAI.Work_Order__c,null);
                }else if(objFAI.Case__c!=null && objFAI.Work_Order__c==null){
                    mapWOtoCaseassociation.put(objFAI.Case__c,null);
                }

                
        }
    //update the map to create a mapping between related Case and WorkOrder
        if(!mapWOtoCaseassociation.IsEmpty()){
            for(SVMXC__Service_Order__c objworkOrder:new WorkOrdersSelector().selectWorkOrderLstFromIds(mapWOtoCaseassociation.keySet(),mapWOtoCaseassociation.keySet())){
                if(mapWOtoCaseassociation.containsKey(objworkOrder.Id))
                    mapWOtoCaseassociation.put(objworkOrder.Id,objworkOrder.SVMXC__Case__c);
                
                if(mapWOtoCaseassociation.containsKey(objworkOrder.SVMXC__Case__c))
                    mapWOtoCaseassociation.put(objworkOrder.SVMXC__Case__c,objworkOrder.Id);
            }
            
            //update the Field Action Item Record 
            for(Field_Action_Item__c objFAI : (List<Field_Action_Item__c>)records)
            {
                    if(objFAI.Work_Order__c!=null && objFAI.Case__c==null){
                        objFAI.Case__c=mapWOtoCaseassociation.get(objFAI.Work_Order__c);
                    }else if(objFAI.Case__c!=null && objFAI.Work_Order__c==null){
                        objFAI.Work_Order__c=mapWOtoCaseassociation.get(objFAI.Case__c);
                    }else if(objFAI.Case__c!=null && objFAI.Work_Order__c!=null ){
                                 if(!mapWOtoCaseassociation.IsEmpty() && mapWOtoCaseassociation.get(objFAI.Work_Order__c)!=objFAI.Case__c)
                                    objFAI.addError(Label.CaseWorkOrderMisMatchError);
                    }

            }
        }
        updateFieldActionItemFields((List<Field_Action_Item__c>)records);
    }

/**
*  @author Debanka
*  @description - To check that only one notification is associated to a case
*   @parameters : Set<Id>
*  @return : void             
**/
    public void checkNoOfNotificationOnCase(){ 
        Set<id> setCaseIds = new Set<id>();
     
        for(Field_Action_Item__c objFAI : (List<Field_Action_Item__c>)records){
          // To check the record type of the associated Field Actiion Notification
          
            if (objFAI.Field_Action_Notification_Record_Type__c == STRING_FAN_RECORDTYPE && objFAI.Case__c!=Null)
            {
                setCaseIds.add(objFAI.Case__c);
                    
            }
              
      }
        Set<id> setCaseNotificationIds = new Set<id>();
        List<Field_Action_Item__c> lstFAI = new  List<Field_Action_Item__c>();
        lstFAI =new FieldActionItemsSelector().selectFieldActionItemsByFANRecType(setCaseIds,STRING_FAN_RECORDTYPE);
        
        // To fetch the Field Action Items related to this case and FAN record type is "Notification"
        
        if(lstFAI.size()>1){
            for(Field_Action_Item__c objFAI :lstFAI){
                setCaseNotificationIds.add(objFAI.Case__c);
            }    
    
            for(Field_Action_Item__c objFieldAction : (List<Field_Action_Item__c>)records){
                if(setCaseNotificationIds.contains(objFieldAction.Case__c))
                {
                    objFieldAction.addError(system.label.FANTriggerErrorMessage);
                }
            }
        } 
    }
/**
*  @author Kumar Gaurav
*  @return : void             
**/
    public static void updateFieldActionItemFields(list<Field_Action_Item__c> fieldActionItemList){
        set<id>caseIdset = new set<id>();
        set<id>workOrderIdSet = new set<id>();
        Map <id,SVMXC__Service_order__c> workOrderMap = new map <id,SVMXC__Service_order__c>();
        Map <id,case> casesmap = new map <id,case>();
        
        for (Field_Action_Item__c fieldAction : fieldActionItemList){
            if (fieldAction.case__c!= null){
                caseIdset.add(fieldAction.case__c);
            }
            if(fieldAction.Work_Order__c!=null){
                workOrderIdSet.add(fieldAction.Work_Order__c);
            }
        }

        if(listWorkOrders.isEmpty() && !workOrderIdSet.isEmpty()){
            listWorkOrders = new workOrdersSelector().getWorkOrderId(workOrderIdSet);
        }

        if(listCases.isEmpty() && !caseIdset.isEmpty()){
            listCases = new casesSelector().getCaseId(caseIdset);
        }

        if(listWorkOrders!=null && !listWorkOrders.isEmpty()){
            for(SVMXC__Service_order__c  workorder : listWorkOrders){
                workOrderMap.put(workorder.id,workorder);
            }
        }

        if(listCases!=null && !listCases.isEmpty()){
            for (Case  caseIns : listCases){
                casesmap.put(caseIns.id,caseIns);
            }
        }

        for(Field_Action_Item__c fieldAction : fieldActionItemList){
            if(casesmap!=null && casesmap.containsKey(fieldAction.case__c)){
                Case relatedCase = casesmap.get(fieldAction.Case__c);
                fieldAction.Installed_Product__c = relatedCase.SVMXC__Component__c;
                fieldAction.Product__c=relatedCase.SVMXC__Product__c;
            }
            else if(workOrderMap!=null && workOrderMap.containsKey(fieldAction.Work_Order__c)){
                SVMXC__Service_order__c relatedWorkOrder = workOrderMap.get(fieldAction.Work_Order__c);
                fieldAction.Installed_Product__c = relatedWorkOrder.SVMXC__Component__c;
                fieldAction.Product__c = relatedWorkOrder.SVMXC__Product__c;
            }
        }
    }

}