force-app/main/default/objects/Approval_Priority_Combination__mdt/Approval_Priority_Combination__mdt.object-meta.xml
<CustomObject>
    <description>Approval Priority Combination for Priority Check</description>
    <label>Approval Priority Combination</label>
    <pluralLabel>Approval Priority Combinations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Country_Blank__c.field-meta.xml
<CustomField>
    <fullName>Country_Blank__c</fullName>
    <description>Flag to check if Region Blank</description>
    <defaultValue>false</defaultValue>
    <label>Country Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Country_Check__c.field-meta.xml
<CustomField>
    <fullName>Country_Check__c</fullName>
    <description>Flag to check Country</description>
    <defaultValue>false</defaultValue>
    <label>Country Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Currency_Blank__c.field-meta.xml
<CustomField>
    <fullName>Currency_Blank__c</fullName>
    <description>Flag to check if Currency Blank</description>
    <defaultValue>false</defaultValue>
    <label>Currency Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Currency_Check__c.field-meta.xml
<CustomField>
    <fullName>Currency_Check__c</fullName>
    <description>Flag to check currency</description>
    <defaultValue>false</defaultValue>
    <label>Currency Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Distribution_Channel_Blank__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel_Blank__c</fullName>
    <description>Flag to check if Distribution Channel Bank</description>
    <defaultValue>false</defaultValue>
    <label>Distribution Channel Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Distribution_Channel_Check__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel_Check__c</fullName>
    <description>Flag to check Distribution Channel</description>
    <defaultValue>false</defaultValue>
    <label>Distribution Channel Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Price_List_Type_Blank__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type_Blank__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to check if Price List Type Blank</description>
    <label>Price List Type Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Price_List_Type_Check__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to check if Price List Type Check</description>
    <label>Price List Type Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Region_Blank__c.field-meta.xml
<CustomField>
    <fullName>Region_Blank__c</fullName>
    <description>Flag to check if Region Blank</description>
    <defaultValue>false</defaultValue>
    <label>Region Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Region_Check__c.field-meta.xml
<CustomField>
    <fullName>Region_Check__c</fullName>
    <description>Flag to check Region</description>
    <defaultValue>false</defaultValue>
    <label>Region Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Sales_Org_Blank__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Blank__c</fullName>
    <description>Flag to check if Sales Org Blank</description>
    <defaultValue>false</defaultValue>
    <label>Sales Org Blank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Sales_Org_Check__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Check__c</fullName>
    <description>Flag to check Sales Org</description>
    <defaultValue>false</defaultValue>
    <label>Sales Org Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Priority_Combination__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores priority value</description>
    <label>Value</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApprovalPriorityMetadataSelector.cls
/**
*    @author: Roopal 
*    @date:   02-Nov-2020
*    @description:  selector class for Approval Priority Combination Metadata
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Roopal                       02-Nov-2020        Selector class for Approval_Priority_Combination__mdt
*    ------------------------------------------------------------------------------------ 
*                    
*/
public with sharing class ApprovalPriorityMetadataSelector extends ilib_SObjectSelector {

    /**
     * @Roopal
     * Getting Approval priority combination metadata schema
     */
    public Schema.SObjectType getSObjectType()
    {
        return Approval_Priority_Combination__mdt.sObjectType;
    }
    
    /**
     *  @author  Roopal
     *  @description Retrieve list of fields for Approval Priority Combination Metadata
     *  @return sObjectFieldList list of Schema.SObjectField
     **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Approval_Priority_Combination__mdt.Country_Blank__c,
            Approval_Priority_Combination__mdt.Country_Check__c,
            Approval_Priority_Combination__mdt.Currency_Blank__c,
            Approval_Priority_Combination__mdt.Currency_Check__c,
            Approval_Priority_Combination__mdt.Distribution_Channel_Blank__c,
            Approval_Priority_Combination__mdt.Distribution_Channel_Check__c,
            Approval_Priority_Combination__mdt.Price_List_Type_Check__c,
            Approval_Priority_Combination__mdt.Price_List_Type_Blank__c, 
            Approval_Priority_Combination__mdt.Region_Blank__c,
            Approval_Priority_Combination__mdt.Sales_Org_Blank__c,
            Approval_Priority_Combination__mdt.Sales_Org_Check__c,
            Approval_Priority_Combination__mdt.Value__c,
            Approval_Priority_Combination__mdt.Region_Check__c
        };
    }    
    
    /**
     *  @author  Roopal
     *  @description Fetch the list of all records in Approval_Priority_Combination__mdt
     *      
     **/
     
    public List<Approval_Priority_Combination__mdt> selectAllPriorityCombinations() 
    {
        return (List<Approval_Priority_Combination__mdt>) Database.query(
        newQueryFactory().toSOQL());
    }   
    
    
}