force-app/main/default/objects/Associated_Codes__c/Associated_Codes__c.object-meta.xml
<CustomObject>
    <label>Associated Code</label>
    <nameField>
        <displayFormat>CODE-{0}</displayFormat>
        <label>Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Codes__c/fields/Code_Title__c.field-meta.xml
<CustomField>
    <fullName>Code_Title__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up field on the code library</description>
    <label>Code Title</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Code_Library__c.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Code_Library__c</referenceTo>
    <relationshipLabel>Associated Codes (Code Title)</relationshipLabel>
    <relationshipName>Associated_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Codes__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US: DCP-672
Links to a Work Order</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Associated Codes</relationshipLabel>
    <relationshipName>Associated_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Answer_1__c.field-meta.xml
<CustomField>
    <fullName>Answer_1__c</fullName>
    <description>Field to Store Answer 1 for PAE/PFA Business Cases</description>
    <label>pAE Answer 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Answer_2__c.field-meta.xml
<CustomField>
    <fullName>Answer_2__c</fullName>
    <description>Field to Store Answer 2 for PAE/PFA Business Cases</description>
    <label>pAE Answer 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Answer_3__c.field-meta.xml
<CustomField>
    <fullName>Answer_3__c</fullName>
    <description>Field to Store Answer 3 for PAE/PFA Business Cases</description>
    <label>pAE Answer 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Answer_4__c.field-meta.xml
<CustomField>
    <fullName>Answer_4__c</fullName>
    <description>Field to Store Answer 4 for PAE/PFA Business Cases</description>
    <label>pFA Answer 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Answer_5__c.field-meta.xml
<CustomField>
    <fullName>Answer_5__c</fullName>
    <description>Field to Store Answer 5 for PAE/PFA Business Cases</description>
    <label>pFA Answer 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Investigation_Summary_Comments__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Summary_Comments__c</fullName>
    <description>To capture the Review comments of QA</description>
    <label>Investigation Summary/Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/pAE_pFA_Awareness_Date__c.field-meta.xml
<CustomField>
    <fullName>pAE_pFA_Awareness_Date__c</fullName>
    <description>To capture awareness date for cases where pAE/pFA is &apos;Yes&apos;</description>
    <inlineHelpText>Date Illumina became aware of an Adverse Event</inlineHelpText>
    <label>pAE/pFA Awareness Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PAE_PFA_Evaluation_Required__c.field-meta.xml
<CustomField>
    <fullName>PAE_PFA_Evaluation_Required__c</fullName>
    <defaultValue>$Label.CasePAEStatusPending</defaultValue>
    <description>Picklist to determine the pAE/pFA Evaluation Required value. Auto updated from pAE/pFA values in other fields.</description>
    <label>pAE/pFA Evaluation Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Potentially_Reportable__c.field-meta.xml
<CustomField>
    <fullName>Potentially_Reportable__c</fullName>
    <description>QACM-4 This field will be checked by QA Reviewer when they agree with the Frontline decision of pAE/pFA required = Yes</description>
    <inlineHelpText>Does QA determine the case as a potential reportable event?</inlineHelpText>
    <label>Potentially Reportable?</label>
<!--QACM -40 -->
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Predicted_QA_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Predicted_QA_Product_Family__c</fullName>
    <description>Used for Einstein classification</description>
    <label>Predicted QA Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Predicted_QA_Sub_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Predicted_QA_Sub_Product_Family__c</fullName>
    <description>Used for Einstein classification</description>
    <label>Predicted QA Sub Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Predicted_QA_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>QA_Sub_Product_Family</valueSetName>        
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>QA_Product_Family__c</fullName>
    <description>Product family is used for categorization business issue cases by Quality assurance team. Data in this field can be added and updated by QA profile user. These family values are independent of family on product object.</description>
    <label>QA Product Family</label>
<!--QACM-40-->
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Partnership Product</fullName>
            </value>
            <value>
                <fullName>Bead Assay</fullName>
            </value>
            <value>
                <fullName>COVIDSeq</fullName>
            </value>
            <value>
                <fullName>MiSeq DX</fullName>
            </value>
            <value>
                <fullName>NextSeq DX</fullName>
            </value>
            <value>
                <fullName>NovaSeq Dx</fullName>
            </value>
            <value>
                <fullName>NIPT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>TSO Comp</fullName>
            </value>
            <value>
                <fullName>Non IVD Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Review__c.field-meta.xml
<CustomField>
    <fullName>QA_Review__c</fullName>
    <description>To capture details of QA review</description>
    <label>QA Review</label>
<!--QACM-40-->
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refer to Existing/Prior Investigation</fullName>
            </value>
            <value>
                <fullName>See Investigation Summary/Comments</fullName>
            </value>
            <value>
                <fullName>No Further Investigation Required</fullName>
            </value>
            <value>
                <fullName>Further Investigation Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
			<value>
                <fullName>In Progress - Awaiting Internal SME Review</fullName>
            </value>
            <value>
                <fullName>Transferred to ETQ</fullName>
            </value>
            <value>
                <fullName>Non IVD Product</fullName>
            </value>
            
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Sub_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>QA_Sub_Product_Family__c</fullName>
    <description>Sub Product family is used for categorization business issue cases by Quality assurance team. Data in this field can be added and updated by QA profile user.</description>
    <label>QA Sub Product Family</label>
<!--QACM-40-->
    <type>Picklist</type>
    <valueSet>
        <controllingField>QA_Product_Family__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Partnership Products</fullName>
            </value>
            <value>
                <fullName>CF 139</fullName>
            </value>
            <value>
                <fullName>CF Clinical Sequencing</fullName>
            </value>
            <value>
                <fullName>CN High Output Reagent</fullName>
            </value>
            <value>
                <fullName>CN Medium Output Reagent</fullName>
            </value>            
            <value>
                <fullName>COVIDSeq</fullName>
            </value>
            <value>
                <fullName>MiSeq DX Reagent Kit v3</fullName>
            </value>
            <value>
                <fullName>MiSeq DX Reagent Kit v3, Micro</fullName>
            </value>
            <value>
                <fullName>High Output Reagent Kit v2.5 (75 cycles)</fullName>
            </value>
            <value>
                <fullName>High Output Reagent Kit v2.5 (300 cycles)</fullName>
            </value>
            <value>
                <fullName>NextSeq DX Instrument</fullName>
            </value>
            <value>
                <fullName>NIPT 16</fullName>
            </value>
            <value>
                <fullName>NIPT Solution v1</fullName>
            </value>
            <value>
                <fullName>NIPT Solution v2</fullName>
            </value>
            <value>
                <fullName>Hamilton</fullName>
            </value>            
            <value>
                <fullName>iScan Dx</fullName>
            </value>
            <value>
                <fullName>Non-IVD product</fullName>
            </value>
            <value>
                <fullName>TruSeq Custom Amplicon Kit Dx</fullName>
            </value>
            <value>
                <fullName>MiSeq Dx Instrument</fullName>
            </value>
            <value>
                <fullName>TSO Comp Kit</fullName>
            </value>
            <value>
                <fullName>TSO Comp Software</fullName>
            </value>
            <value>
                <fullName>TruSight Oncology DNA Controls</fullName>
            </value>
            <value>
                <fullName>TruSight Oncology RNA Controls</fullName>
            </value>
            <value>
                <fullName>TSO Comp NTRK CDx</fullName>
            </value>
            <value>
                <fullName>DNA Prep with Enrichment</fullName>
            </value>
            <value>
                <fullName>TruSight Cystic Fibrosis Library Prep</fullName>
            </value>
            <value>
                <fullName>NovaSeq Dx Instrument</fullName>
            </value>
            <value>
                <fullName>NovaSeq Dx v1.5 kit (300 cycles)</fullName>
            </value>
            <value>
                <fullName>TruSight Whole Genome Analysis Application</fullName>
            </value>
            <value>
                <fullName>TruSight Whole Genome Dx Library Prep with UD Indexes, 24 sample</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the work order for elevation case</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Elevation Case</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Code_Library__c/Code_Library__c.object-meta.xml
<CustomObject>
    <description>To store the codes used for case and work order closure</description>
    <label>Code Library</label>
    <nameField>
        <label>Code Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code Library</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/QA_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3rd Party Partnership Product</fullName>
    </customValue>
    <customValue>
        <fullName>Bead Assay</fullName>
    </customValue>
    <customValue>
        <fullName>COVIDSeq</fullName>
    </customValue>
    <customValue>
        <fullName>MiSeq DX</fullName>
    </customValue>
    <customValue>
        <fullName>NextSeq DX</fullName>
    </customValue>
    <customValue>
        <fullName>NovaSeq Dx</fullName>
    </customValue>
    <customValue>
        <fullName>NIPT</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>TSO Comp</fullName>
    </customValue>
    <customValue>
        <fullName>Non IVD Product</fullName>
    </customValue>
    <masterLabel>QA Product Family</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/QA_Sub_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3rd Party Partnership Products</fullName>
    </customValue>
    <customValue>
        <fullName>CF 139</fullName>
    </customValue>
    <customValue>
        <fullName>CF Clinical Sequencing</fullName>
    </customValue>
    <customValue>
        <fullName>CN High Output Reagent</fullName>
    </customValue>
    <customValue>
        <fullName>CN Medium Output Reagent</fullName>
    </customValue>
    <customValue>
        <fullName>MiSeq DX Reagent Kit v3</fullName>
    </customValue>
    <customValue>
        <fullName>MiSeq DX Reagent Kit v3, Micro</fullName>
    </customValue>
    <customValue>
        <fullName>High Output Reagent Kit v2.5 (75 cycles)</fullName>
    </customValue>
    <customValue>
        <fullName>High Output Reagent Kit v2.5 (300 cycles)</fullName>
    </customValue>
    <customValue>
        <fullName>NextSeq DX Instrument</fullName>
    </customValue>
    <customValue>
        <fullName>NIPT 16</fullName>
    </customValue>
    <customValue>
        <fullName>NIPT Solution v1</fullName>
    </customValue>
    <customValue>
        <fullName>NIPT Solution v2</fullName>
    </customValue>
    <customValue>
        <fullName>Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>COVIDSeq</fullName>
    </customValue>
    <customValue>
        <fullName>Non-IVD product</fullName>
    </customValue>
    <customValue>
        <fullName>TruSeq Custom Amplicon Kit Dx</fullName>
    </customValue>
    <customValue>
        <fullName>MiSeq Dx Instrument</fullName>
    </customValue>
    <customValue>
        <fullName>iScan Dx</fullName>
    </customValue>
    <customValue>
        <fullName>TSO Comp Kit</fullName>
    </customValue>
    <customValue>
        <fullName>TSO Comp Software</fullName>
    </customValue>
    <customValue>
        <fullName>TruSight Oncology DNA Controls</fullName>
    </customValue>
    <customValue>
        <fullName>TruSight Oncology RNA Controls</fullName>
    </customValue>
    <customValue>
        <fullName>TSO Comp NTRK CDx</fullName>
    </customValue>
    <customValue>
        <fullName>DNA Prep with Enrichment</fullName>
    </customValue>
    <customValue>
        <fullName>TruSight Cystic Fibrosis Library Prep</fullName>
    </customValue>
    <customValue>
        <fullName>NovaSeq Dx Instrument</fullName>
    </customValue>
    <customValue>
        <fullName>NovaSeq Dx v1.5 kit (300 cycles)</fullName>
    </customValue>
    <customValue>
        <fullName>NovaSeq Dx Library Tube</fullName>
    </customValue>
    <customValue>
        <fullName>DRAGEN for DNA Prep with Enrichment for NovaSeq Dx</fullName>
    </customValue>
    <masterLabel>QA Sub Product Family</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CaseQueueableHelper.cls
/**************************************************************************************************************************************
 * NAME   : CasesHelper
 * DESCRIPTION  : Helper class for Case trigger class.                   
 * @AUTHOR : Susmitha Mogidi 
 * MODIFICATION LOG:  
* --------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
* --------------------------------------------------------------------------------------------------------------------------------------
*
* Susmitha              13-09-2022           QACM-108 Method to clear case field values on Record type change
**/
public without sharing class CaseQueueableHelper {
    private static final String LOG_TITLE = 'CaseQueueableHelper';
    /*
     *@DESCRIPTION = QACM-108 Whenever case record type chnages form BI to Sr, the code tite on associated code should be changed to code dis associated
    *  @PARAM :  Map<Id, Case>
    *  @RETURN: void
    *  @AUTHOR - Susmitha Mogidi
    */
    public static void updateCodeTitleonRTChange(Map<id,Case> casesRecord){
        ilib_LogEvent.push(Cases.LOG_TITLE + '.updateCodeTitleonRTChange()');
        try{ 
            List<Associated_Codes__c> lAssocodes =  new List<Associated_Codes__c>(); 
            ilib_LogEvent.info('lAssocodes: '+lAssocodes); 
            if(!casesRecord.IsEmpty() && casesRecord != null) {
                List<Code_Library__c> lstDisassociatedCode= new CodeLibrarySelector().selectDisassocaiatedCodeLibrary();
                for(id caseId :casesRecord.keySet()) {
                    for(Associated_Codes__c objRemoveACode: new AssociatedCodeSelector().selectAssociatedCodesForWOAndCase(casesRecord.get(caseId).Work_Order__c,caseId)) {
                        objRemoveACode.Code_Title__c=lstDisassociatedCode[0].id;
                        lAssocodes.add(objRemoveACode);
                    }
                }
                if(!lAssocodes.isEmpty()) {
                    Update lAssocodes;
                }
            }
            ilib_LogEvent.pop();
        } 
        catch(Exception e){
        ApexExceptions.emit('updateCodeTitleonRTChange',e);
        }      
    }
    /*
     *@DESCRIPTION = QACM-108 Whenever case record type chnages form BI to Sr, Update the case fields 
    *  @PARAM :  Map<Id, Case>
    *  @RETURN: void
    *  @AUTHOR - Susmitha Mogidi
    */
    public static void updateCase(map<id,Case> mapOfoCaseRecords){
        List<Case> updateCaseList =  new List<Case>();
        ilib_LogEvent.setTitle(LOG_TITLE,ilib_LogEvent.SERVICE);
        ilib_LogEvent.push(LOG_TITLE + '.execute()');
        try{
            System.debug('List of update cases'+mapOfoCaseRecords);
            if(!mapOfoCaseRecords.IsEmpty() && mapOfoCaseRecords != null){
				for(Case oldCase:mapOfoCaseRecords.Values()){
                    oldCase.QA_Review__c = '';
                    oldCase.Predicted_QA_Product_Family__c = '';
                    oldCase.Predicted_QA_Sub_Product_Family__c = '';
                    oldCase.QA_Product_Family__c = '';
                    oldCase.QA_Sub_Product_Family__c = '';
                    oldCase.Investigation_Summary_Comments__c = '';
                    oldCase.Potentially_Reportable__c = '';
                    oldCase.pAE_pFA_Awareness_Date__c = NULL;
                    oldCase.PAE_PFA_Evaluation_Required__c = '';
                    oldCase.Answer_1__c = '';
                    oldCase.Answer_2__c = '';
                    oldCase.Answer_3__c = '';
                    oldCase.Answer_4__c = '';
                    oldCase.Answer_5__c = '';
                   updateCaseList.add(oldCase);
                }
            }
            if(!updateCaseList.isEmpty()){
                update updateCaseList;
            }
            ilib_LogEvent.pop();
        }
        Catch(Exception e){
            ApexExceptions.emit(LOG_TITLE,e);
            ilib_LogEvent.message(LOG_TITLE+'.Exception: ' + e.getMessage());
        }
    }
}    