force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/SVMXC__RMA_Shipment_Line__c.object-meta.xml
<CustomObject>
    <description>ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both. Parts Order Line lists parts returned or shipped.</description>
    <label>Parts Order Line</label>
    <nameField>
        <displayFormat>LN-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/Decontamination_Required__c.field-meta.xml
<CustomField>
    <fullName>Decontamination_Required__c</fullName>
    <description>To Populate the Decontamination Required of the associated Product. 
Automatically Populated if Product is associated to the Parts Order Line.</description>
    <formula>AND( SVMXC__Product__r.Decontamination_Required__c , NOT(ISPICKVAL(Return_Reason__c, &quot;Unused/Good Stock&quot;)) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Decontamination Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/Is_DCIR_Filled__c.field-meta.xml
<CustomField>
    <fullName>Is_DCIR_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To determine whether DCIR is generated.</description>
    <label>Is DCIR Filled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/Parts_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order_Type__c</fullName>
    <description>To Populate the Order Type of the associated Parts Order. 
Automatically Populated if Parts Order is associated to the Parts Order Line.</description>
    <formula>TEXT(SVMXC__RMA_Shipment_Order__r.SVMXC__Order_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parts Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/SVMXC__RMA_Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__RMA_Shipment_Order__c</fullName>
    <description>RMA/Shipment number. Is a lookup to an existing RMA/Shipment record in ServiceMax</description>
    <inlineHelpText>RMA/Shipment number. Is a lookup to an existing RMA/Shipment record in ServiceMax</inlineHelpText>
    <label>Parts Order</label>
    <referenceTo>SVMXC__RMA_Shipment_Order__c</referenceTo>
    <relationshipName>RMA_Shipment_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/SVMXC__RMA_Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Parts Order is an object to handle parts logistics. With record type RMA, it is a document that authorizes products or parts to be returned to the manufacturer/repair center/warehouse. With record type Shipment,  it is an internal document that authorizes products or parts to be shipped to a customer or field inventory location. ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both.</description>
    <label>Parts Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Parts_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order_Type__c</fullName>
    <description>This field is used to create part order type on Mobile apps.</description>
    <label>Parts Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Submit_for_Approval_CP__c.field-meta.xml
<CustomField>
    <fullName>Submit_for_Approval_CP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To initiate Channel Partner Approval Process.</description>
    <label>Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CheckDCIR_POLHelper.cls
/**
* @author Shivani Jain
* @date 29 Nov 2021
*
* @description DCP-42926 Helper Class for Parts Order Line Trigger to run DCIR logic 
*/ 
public class CheckDCIR_POLHelper {
    
    /*******************************************************************************************************
    * @description Check if the Part Order is Submitted for Approval and if any related POL faling a DCIR check
    * @param isChannelPartner True if logged in user is CP
    * @param records List <SVMXC__RMA_Shipment_Line__c>
    * @return
    */
    public static void checkDCIR(Boolean isChannelPartner, List <SVMXC__RMA_Shipment_Line__c> records) {

        for(SVMXC__RMA_Shipment_Line__c objPartOrderLine: (List <SVMXC__RMA_Shipment_Line__c>) records) {
            if(isChannelPartner && objPartOrderLine.Parts_Order_Type__c == 'Return' 
                    && objPartOrderLine.Decontamination_Required__c && !objPartOrderLine.Is_DCIR_Filled__c) {
                if(PartsOrderLines.partsOrderIdToPartsOrder != null 
                        && PartsOrderLines.partsOrderIdToPartsOrder.containsKey(objPartOrderLine.SVMXC__RMA_Shipment_Order__c) 
                        && PartsOrderLines.partsOrderIdToPartsOrder.get(objPartOrderLine.SVMXC__RMA_Shipment_Order__c).Submit_for_Approval_CP__c) {
                    objPartOrderLine.addError(Label.PODCIRCheckErrorCP);
                }
            }
        }
    }
}