force-app/main/default/objects/Applied_Contract__c/Applied_Contract__c.object-meta.xml
<CustomObject>
    <description>This object is used to relate Service Contract records that are used to entitle Cases, Work Orders and Parts Orders with one or more Service Contract entitlements.</description>
    <label>Applied Contract</label>
    <nameField>
        <displayFormat>SCJN-{000000}</displayFormat>
        <label>Applied Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Applied_Contract__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to relate one or more Service Contracts to a Case for the purpose of Entitling Cases using one or more Service Contracts. This field is auto populated.</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Applied_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_of_Issue_Awareness__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_Awareness__c</fullName>
    <description>Date of issue awareness</description>
    <inlineHelpText>Date Illumina became aware of a Business Issue</inlineHelpText>
    <label>Date of Issue Awareness</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component SN</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Case1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</description>
    <inlineHelpText>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</inlineHelpText>
    <label>Service/Maintenance Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
    <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Cases Reported From This Site</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used by Reverse Logistics Module. Reference to the latest service contract for this installed product. Derived automatically upon creating/updating service contract</description>
    <label>Service Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipName>Installed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing location record</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>R00N70000001hzcqEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Status__c</fullName>
    <description>Current status of the installed product.</description>
    <inlineHelpText>Current status of the installed product.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipped</fullName>
                <default>true</default>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>Returned Vendor</fullName>
            </value>
            <value>
                <fullName>Non Calibrated</fullName>
            </value>
            <value>
                <fullName>Awaiting Installation</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Scrapped</fullName>
            </value>
            <value>
                <fullName>Loaned</fullName>
            </value>
            <value>
                <fullName>De-Installed</fullName>
            </value>
            <value>
                <fullName>Calibrated</fullName>
            </value>
            <value>
                <fullName>Not Calibrated Expired</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/SVMXC__Service_Contract__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/Consumables_Included__c.field-meta.xml
<CustomField>
    <fullName>Consumables_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This entitles 100% discount on Consumables when entitling Cases and Work Orders with applicable Service Contract Line.</description>
    <label>Consumables Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/SVMXC__Service_Contract_Products__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed products, part numbers, or groups of products entitled by this service contract.</description>
    <label>Covered Product</label>
    <nameField>
        <displayFormat>SCPN-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Covered Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/fields/SVMXC__Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the installed product covered by the service contract. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Name of the installed product covered by the service contract. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>R00N70000001hzdkEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <description>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</description>
    <inlineHelpText>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</inlineHelpText>
    <label>Service/Maintenance Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipName>R00N70000001hzdaEAA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestSendEmailToASOPFromCase.cls
/***************************************************************************************************************************************
 * NAME   : TestSendEmailToASOPFromCase
 * DESCRIPTION  : TestClass for SendEmailToASOPFromCase Class
 * @AUTHOR : Vaibhav
 * @DATE   : 3-Sep-2020  
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 ****************************************************************************************************************************************/
@isTest
public with sharing class TestSendEmailToASOPFromCase {

    public static final boolean BOOLEAN_CONSUMABLES_INCLUDED = false;
    public static final string STRING_INSTALLED_PRODUCT_NAME = 'Test IP';
    public static final string STRING_CURRENCY = 'USD';
    public static final string STRING_INSTALLED_PRODUCT_STATUS = 'New';
    public static final string STRING_CASE_RECORDTYPENAME = 'Business Issue';
    public static final string STRING_CASE_STATUS = 'Initiated';
    public static final string STRING_CASE_ORIGIN = 'Phone - CS';

    @TestSetup
    static void setupData() {

        //create a case and associate it with an emailMessage record.
        Account objAccount = TestDataAccount.getNewAccount();

        Test.startTest();
        SVMXC__Service_Contract__c objServiceContract = TestDataFieldService.createServiceContract(objAccount.Id);
        insert objServiceContract;
        SVMXC__Service_Contract__c insertedServiceContract = [Select Consumables_Included__c from SVMXC__Service_Contract__c where Id =: objServiceContract.Id];
        System.assertEquals(insertedServiceContract.Consumables_Included__c, BOOLEAN_CONSUMABLES_INCLUDED);

        SVMXC__Site__c objLocation = TestDataFieldService.createLocation('Test Location', 'Test Street', 'Ireland', '123456', 'USD');
        insert objLocation;

        SVMXC__Installed_Product__c objInstalledProduct = TestDataFieldService.createInstalledProduct(STRING_INSTALLED_PRODUCT_NAME, STRING_CURRENCY, STRING_INSTALLED_PRODUCT_STATUS);
        insert objInstalledProduct;
        SVMXC__Installed_Product__c insertedInstalledProduct = [Select SVMXC__Status__c from SVMXC__Installed_Product__c where Id =: objInstalledProduct.Id];
        System.assertEquals(insertedInstalledProduct.SVMXC__Status__c, STRING_INSTALLED_PRODUCT_STATUS);

        SVMXC__Service_Contract_Products__c objCoveredProduct = TestDataFieldService.createCoveredProduct(objInstalledProduct.Id);
        objCoveredProduct.SVMXC__Service_Contract__c = objServiceContract.Id;
        insert objCoveredProduct;
        SVMXC__Service_Contract_Products__c insertedCoveredProduct = [Select SVMXC__Installed_Product__c from SVMXC__Service_Contract_Products__c where SVMXC__Installed_Product__c =: objInstalledProduct.Id];
        System.assertEquals(insertedCoveredProduct.SVMXC__Installed_Product__c, objInstalledProduct.Id);

        Case objCase = TestDataCase.initNewCase(STRING_CASE_RECORDTYPENAME, STRING_CASE_STATUS, STRING_CASE_ORIGIN);
        objCase.SVMXC__Component__c = objInstalledProduct.Id;
        objCase.SVMXC__Site__c = objLocation.Id;
        objCase.Date_of_Issue_Awareness__c = Date.Today();
        insert objCase;
        Case insertedCase = [Select SVMXC__Component__c from Case where Id =: objCase.Id];
        System.assertEquals(InsertedCase.SVMXC__Component__c, objInstalledProduct.Id);

        Applied_Contract__c objEntitlement = new Applied_Contract__c();
        objEntitlement.CurrencyIsoCode = 'USD';
        objEntitlement.Case_Number__c = objCase.id;
        insert objEntitlement;
        List<Applied_Contract__c> insertedEntitlement = [Select Case_Number__c from Applied_Contract__c where Case_Number__c =: objCase.Id];
        System.assertEquals(insertedEntitlement[0].Case_Number__c, objCase.Id);

        Test.stopTest();

        //create an email message record and associate it with a case.
        EmailMessage objEmail1 = new EmailMessage();
        objEmail1.FromAddress = '';
        objEmail1.ToAddress = '';
        objEmail1.CcAddress = '';
        objEmail1.BccAddress = '';
        objEmail1.Subject = 'Test email';
        objEmail1.TextBody = 'Test Text Body';
        objEmail1.htmlBody = 'Test HTML Body';
        objEmail1.ParentId = objCase.Id;

        insert objEmail1;
        
        //Create Document - //DCP-34276
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
         
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
         
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = objEmail1.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;

    }

    /*
     *  @author Vaibhav Parashar
     *  @description - testSendingEmailWithAttachmentFromCaseScreen.
     */
    testMethod static void testSendingEmailWithAttachmentFromCaseScreen() {
    
        Case caseRec = [Select Id from Case Limit 1];
        
        Test.StartTest();
        //execute main method
        SendEmailToASOPFromCase.EmailMessageWrapper emailMessageWrapper = SendEmailToASOPFromCase.runASOPEmailBusinessLogic(caseRec.Id,'Case','OnLoad','',null);
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(1, invocations, 'An email has been sent');
        System.assertEquals('Success: Email Sent to ASOP successfully.', emailMessageWrapper.uiDisplayMessage, 'Email Sent Successfully');
        
    }
    
    /*
     *  @author Vaibhav Parashar
     *  @description - testSendingEmailWithAttachmentFromEmailScreen.
     */
    testMethod static void testSendingEmailWithAttachmentFromEmailScreen() {

        EmailMessage emailMessageObj = [Select Id from EmailMessage Limit 1];
        
        Test.StartTest();
        //execute main method
        SendEmailToASOPFromCase.EmailMessageWrapper emailMessageWrapper = SendEmailToASOPFromCase.runASOPEmailBusinessLogic(emailMessageObj.Id,'EmailMessage','OnLoad','',null);
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(0, invocations, 'An email has not been sent');
        System.assertEquals('', emailMessageWrapper.uiDisplayMessage, 'Stopped at UI for email Message screen');
        
        
    }
    
    
    /*
     *  @author Vaibhav Parashar
     *  @description - method to test upload of files from lwc ui.
     */
    testMethod static void testSendingEmailFromEmailScreenUploadFiles() {
    
        List < Map < String, Object >> files = new List < Map < String, Object >>();
    
        files.add(new Map < String, Object >{
        'pathOnClient' => 'Salesforce Report Filters.PNG',
        'title' => 'Salesforce Report Filters',
        'versionData' => 'iVBORw0KGgoAAAANSUhEUgAAAjQAAADXCAYAAAANxMsGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAEDrSURBVHhe7Z3Pa11Jm981f8XNUuBFHLxoZWXtrKEXVsaLPoMXUeiFR+mFxRBeNGZolB6II96FufTCqAcajQlvkBdvRiZ0Rg3Tg0ziIBMaZJoGmdBBXjREGS/uogl3oDN49aTq/Kh6quqpOnV/6N57pG/Dh/atUz+eeqrO83x1zrn3LJH678OHDwAAAAAAnQWCBgAAAACdB4IGAAAAAJ0HggYAAAAAnQeCBgAAAACdB4IGAAAAAJ0HggYAAAAAnQeCBgAAAACdpxQ0P/zwAwAAAABAZ4Gg'
        });
 
        EmailMessage emailMessageObj = [Select Id from EmailMessage Limit 1];
        
        Test.StartTest();
        //execute main method
        SendEmailToASOPFromCase.EmailMessageWrapper emailMessageWrapper = SendEmailToASOPFromCase.runASOPEmailBusinessLogic(emailMessageObj.Id,'EmailMessage','sendEmailClicked','searchterm',files);
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(1, invocations, 'An email has been sent');
        System.assertEquals('Success: Email Sent to ASOP successfully.', emailMessageWrapper.uiDisplayMessage, 'Email Sent Successfully');
        
     }
    

}