force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>Represents Account Plans created for an account. Stores customer-specific information like customer growth, challenges, and metrics entered by sales users</description>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <description>Stores objectives on an Account plan, that represents the action items associated to an Account plan. These objectives are tasks/actions that will help sales user communicate plan to leadership to meet account goals.</description>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <description>Master-Detail relation to Account Plan</description>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objective</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataObjectives.cls
/**
*    @author: Kushagra Desai
*    @date:   19-Sept-2019
*    @description:  Test data creation for Objective
*    Modification Log:
*    -----------------------------------------------------------------------------------
*             Developer                      Date                Description
*    ------------------------------------------------------------------------------------ 
*                    
*/
@isTest
public with sharing class TestDataObjectives {
    /*
    *@author: Kushagra Desai
    *@Desc: Method to get new Objective__c Record
    */
    public static Objective__c getNewObjective(Account_Plan__c ap)
    {
        Objective__c ob  = initObjective(ap.Id);
        insert ob;
        return ob;
    }
	/*
    *@author: Kushagra Desai
    *@Desc: Method to get new Objective__c Record with Account_plan__c and rest other field as defaults
    */
    public static Objective__c initObjective(String apId){
        Objective__c ob =  new Objective__c();
        ob.Name = 'Test Objective';
        ob.Account_Plan__c = apId;
        return ob;
    }
}