force-app/main/default/objects/Company_Code_Address__mdt/Company_Code_Address__mdt.object-meta.xml
<CustomObject>
    <description>Metadata containing the address details which can be used to retrieve via Company Code calculated on Opportunity.</description>
    <label>Company Code Address</label>
    <pluralLabel>Company Code Addresses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Represents Address Line 1 from Company Address</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Represents Address Line 2 from Company Address</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>Represents Address Line 3 from Company Address</description>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_4__c</fullName>
    <description>Represents Address Line 4 from Company Address</description>
    <label>Address Line 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Address_Line_5__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_5__c</fullName>
    <description>Represents Address Line 5 from Company Address</description>
    <label>Address Line 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Address_Line_6__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_6__c</fullName>
    <description>Represents Address Line 6 from Company Address</description>
    <label>Address Line 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Represents City from Company Address</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Field used to match the Company Code on Opportunity</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>Represents Company Name from Company Address</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Represents Country from Company Address</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Represents Currency used based on Company Address</description>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Footer_City__c.field-meta.xml
<CustomField>
    <fullName>Footer_City__c</fullName>
    <description>Represents Footer City from Company Address</description>
    <label>Footer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Footer_Full_Street__c.field-meta.xml
<CustomField>
    <fullName>Footer_Full_Street__c</fullName>
    <description>Represents Footer Full Street from Company Address</description>
    <label>Footer Full Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/PO_Box__c.field-meta.xml
<CustomField>
    <fullName>PO_Box__c</fullName>
    <description>Represents PO Box from Company Address</description>
    <label>PO Box</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Represents Postal Code from Company Address</description>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Code_Address__mdt/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Represents Address Line 1 from Company Address</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Populates Address Line 1 from metadata based on Company Code of Opportunity </description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Populates Address Line 2 from metadata based on Company Code of Opportunity </description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>Populates Address Line 3 from metadata based on Company Code of Opportunity </description>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_4__c</fullName>
    <description>Populates Address Line 4 from metadata based on Company Code of Opportunity </description>
    <label>Address Line 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Line_5__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_5__c</fullName>
    <description>Populates Address Line 5 from metadata based on Company Code of Opportunity </description>
    <label>Address Line 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address_Line_6__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_6__c</fullName>
    <description>Populates Address Line 6 from metadata based on Company Code of Opportunity </description>
    <label>Address Line 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>This field is used to determine based on 'Company Code Address' metadata</description>
    <label>Company Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>Populates Company Name from metadata based on Company Code of Opportunity </description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Footer_City__c.field-meta.xml
<CustomField>
    <fullName>Footer_City__c</fullName>
    <description>Populates Footer City from metadata based on Company Code of Opportunity </description>
    <label>Footer City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Footer_Full_Street__c.field-meta.xml
<CustomField>
    <fullName>Footer_Full_Street__c</fullName>
    <description>Populates Footer Full Street from metadata based on Company Code of Opportunity </description>
    <label>Footer Full Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CompanyCodeAddressesSelector.cls
/**
*    @author Satya Swain
*    @date   2018-10-23
*    @description    Class to get the Custom Metadata records for Company Code Address based on different conditions 
*    Modification Log:
*   ------------------------------------------------------------------------------------ 
*    Developer                      Date                Description
*    Satya Swain                  2018-10-23          Initial Version
*    Himanshu                2022-03-30               Code Scan Fixes  
*    ------------------------------------------------------------------------------------                  
*/

public with sharing class CompanyCodeAddressesSelector extends ilib_SObjectSelector 
{
  /*
   *   @author Satya Swain       
   *   @date   2018-10-23  
   *   @description  Describe the object
   *
 */
 public Schema.SObjectType getSObjectType()
 {
    return Company_Code_Address__mdt.sObjectType;
 }
  
  /**
   *  @author  Satya Swain
   *  @description Retrieve list of fields for Company Code Address Metadata type 
   *  @return sObjectFieldList list of Schema.SObjectField
   **/
  public List<Schema.SObjectField> getSObjectFieldList()
  {
     return new List<Schema.SObjectField> {
    Company_Code_Address__mdt.Company_Code__c,
		Company_Code_Address__mdt.Company_Name__c,
		Company_Code_Address__mdt.Country__c,
		Company_Code_Address__mdt.Street__c,
		Company_Code_Address__mdt.City__c,
		Company_Code_Address__mdt.Postal_Code__c,
		Company_Code_Address__mdt.PO_Box__c,
		Company_Code_Address__mdt.Currency__c,
		Company_Code_Address__mdt.DeveloperName,
		Company_Code_Address__mdt.MasterLabel,
    Company_Code_Address__mdt.Address_Line_1__c,
    Company_Code_Address__mdt.Address_Line_2__c,
    Company_Code_Address__mdt.Address_Line_3__c,
    Company_Code_Address__mdt.Address_Line_4__c,
    Company_Code_Address__mdt.Address_Line_5__c,
    Company_Code_Address__mdt.Address_Line_6__c,
    Company_Code_Address__mdt.Footer_Full_Street__c,
    Company_Code_Address__mdt.Footer_City__c
     };
  }
  
  /**
   *  @author Satya Swain
   *  @description Fetch Related Company Code Addresses for the Opportunity's Company Code
   *  @param setCompanyCodes set of Company Codes
   *  @return list of Company Code Address records
   **/
  public List<Company_Code_Address__mdt> selectCompanyCodeAddress(Set<String> setCompanyCodes) 
  {
      return (List<Company_Code_Address__mdt>) Database.query(
      newQueryFactory().setCondition('Company_Code__c  IN :setCompanyCodes').toSOQL()
      );
  }
  
}