force-app/main/default/objects/SVMXC__Service_Group_Product__c/SVMXC__Service_Group_Product__c.object-meta.xml
<CustomObject>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group.</description>
    <label>Product Serviced</label>
    <nameField>
        <displayFormat>SGPN-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Serviced</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Product__c/fields/SVMXC__Group_Member__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Group_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Technician that specializes in this product. Reference to an existing Technician record in ServiceMax</description>
    <label>Technician/Equipment</label>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipName>Service_Group_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Product__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product supported by the group. Is a lookup to an existing product in Salesforce</description>
    <inlineHelpText>Product supported by the group. Is a lookup to an existing product in Salesforce</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Service_Group_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Confirm_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Assignee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be filled by user when they see validation error “The Field Service assignee is not trained on the product. Please review the event and assign the Work Order to a trained FS employee.” while assigning the WO from dispatch console to FS user who are not trained on that product.</description>
    <label>Confirm Assignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Group_Member__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Group_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</description>
    <inlineHelpText>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</inlineHelpText>
    <label>Technician</label>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Locked_By_DC__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Locked_By_DC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Locked By DC</description>
    <inlineHelpText>Locked By DC</inlineHelpText>
    <label>Locked By DC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product in which specialization would be required to service the work order. Calculated from installed product by OptiMax pre-calculation engine</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ValidateProductServiced_WOHelper.cls
/*
*    @author Romi Taskar
*    @date   15-06-2022
*    @description    Class to restrict Dispatcher if the Product Serviced's Product and WO's Product doesnt match
*    Modification Log:
*    ------------------------------------------------------------------------------------ 
*    Developer              Date                    Description
*    Romi                 15-June-2022             Initial Version
*    Nancy                13-Feb-2024               CMCM-5307 Work Order Trigger Query Optimization
*    ------------------------------------------------------------------------------------
*/
public with sharing class ValidateProductServiced_WOHelper {

    public static final String DISPATCHER_PERMISSION_SET = 'SS_Service_Dispatch_Console';
    public static Boolean hasPermission = false;
    private static Boolean hasConfirmAssigneeLogicRun = false;

    public static List<SVMXC__Service_Group_Product__c> productServicedRecs = new List<SVMXC__Service_Group_Product__c>(); //CMCM-5307

    /**
    *  @author Romi Taskar 
    *  @description - 53211 - To restrict Dispatcher if the Product Serviced's Product and WO's Product doesnt match
    *  @return: Void              
    **/
    public static void populateWorkOrdersToValidate(List<Sobject> records, Map<Id, SObject> oldRecords) {

        ilib_LogEvent.push(WorkOrders.LOG_TITLE + '.populateWorkOrdersToValidate()');

        Map<Id, SVMXC__Service_Order__c> workOrderMap = new Map<Id, SVMXC__Service_Order__c>(); 
        Set<Id> technicianIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        hasPermission = FeatureManagement.checkPermission(DISPATCHER_PERMISSION_SET);

        if(!hasPermission || hasConfirmAssigneeLogicRun) {
            ilib_LogEvent.pop();
            return;
        }

        for(SVMXC__Service_Order__c objWorkOrder : (List<SVMXC__Service_Order__c>)records) {
            SVMXC__Service_Order__c objOldWorkOrder = (SVMXC__Service_Order__c)(oldRecords.get(objWorkOrder.Id));

            if(!objWorkOrder.Confirm_Assignee__c && objWorkOrder.SVMXC__Group_Member__c != objOldWorkOrder.SVMXC__Group_Member__c 
            && objWorkOrder.SVMXC__Group_Member__c != null && !objOldWorkOrder.SVMXC__Locked_By_DC__c && objWorkOrder.SVMXC__Locked_By_DC__c) {
                workOrderMap.put(objWorkOrder.Id, objWorkOrder);
                technicianIds.add(objWorkOrder.SVMXC__Group_Member__c);
                productIds.add(objWorkOrder.SVMXC__Product__c);
            }

            if(objWorkOrder.Confirm_Assignee__c) {
                objWorkOrder.Confirm_Assignee__c = false;
                hasConfirmAssigneeLogicRun = true;
            }
            
        }

        throwErrorOnDC(workOrderMap, technicianIds, productIds);

        ilib_LogEvent.pop();
    } 

    /*******************************************************************************************************
    * @param workOrderMap Work Order Record
    * @param technicianIds Field Support record
    * @param productIds product set
    * @return void 
    */
    public static void throwErrorOnDC(Map<Id, SVMXC__Service_Order__c> workOrderMap,set<Id> technicianIds, Set<Id> productIds) {
        if(!workOrderMap.isEmpty()) {
            //CMCM-5307 - Add empty check for WO trigger Optimization
            if (productServicedRecs.isEmpty() || Feature.isOn(System.label.Feature_Work_Order_Optimization)){
                productServicedRecs = new ProductServicedSelector().selectProductServicedRecs(technicianIds, productIds);
            }
            Map<String, Boolean> productTechnicianMap = new Map<String, Boolean>();

            for(SVMXC__Service_Group_Product__c psRecord : productServicedRecs) {
                productTechnicianMap.put(psRecord.SVMXC__Group_Member__c + '_' + psRecord.SVMXC__Product__c,true);
            }
            
            for(SVMXC__Service_Order__c woRec : workOrderMap.values()) {
                if(!productTechnicianMap.containsKey(woRec.SVMXC__Group_Member__c + '_' + woRec.SVMXC__Product__c )) {
                    woRec.addError(Label.Check_Confirm_Assignee_ErrorMsg);
                }
            }

        }         
    }  

}