force-app/main/default/objects/Apttus__AgreementLineItem__c/Apttus__AgreementLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus__AgreementId__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AgreementId__c</fullName>
    <description>ID of the associated agreement</description>
    <label>Agreement</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Agreement Line Items</relationshipLabel>
    <relationshipName>AgreementLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <description>Approval status of the agreement line item</description>
    <inlineHelpText>Approval status of the agreement line item</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Material_Group_1__c.field-meta.xml
<CustomField>
    <fullName>Material_Group_1__c</fullName>
    <description>Field to store Material Group of product</description>
    <label>Material Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Group_1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>This field stores the priority for the agreement line item to determine the sorting on the approval email notifications.</description>
    <inlineHelpText>Agreement Lineitems priority for sorting order on approval email notifications.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <inlineHelpText>This field states the current approval status of the Agreement.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Code_Parameter__mdt/Code_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>Values used by Apex or Lightning code</description>
    <label>Code Parameter</label>
    <pluralLabel>Code Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Code_Parameter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Usually will be name/value pairs. Each pair on a line and separated by a colon</description>
    <inlineHelpText>Usually will be name/value pairs. Each pair on a line and separated by a colon</inlineHelpText>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Material_Group__mdt/Material_Group__mdt.object-meta.xml
<CustomObject>
    <label>Material Group</label>
    <pluralLabel>Material Groups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Material_Group__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>This field stores the priority of the MG1 to determine the sorting order on the approval email notifications.</description>
    <inlineHelpText>Priority of the MG1 to determine the sorting order on approval email notifications.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Material_Group_1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AIM</fullName>
    </customValue>
    <customValue>
        <fullName>AIP</fullName>
    </customValue>
    <customValue>
        <fullName>AIR</fullName>
    </customValue>
    <customValue>
        <fullName>AIS</fullName>
    </customValue>
    <customValue>
        <fullName>ASQ</fullName>
    </customValue>
    <customValue>
        <fullName>BG1</fullName>
    </customValue>
    <customValue>
        <fullName>BGS</fullName>
    </customValue>
    <customValue>
        <fullName>BSC</fullName>
    </customValue>
    <customValue>
        <fullName>CGA</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <customValue>
        <fullName>CRT</fullName>
    </customValue>
    <customValue>
        <fullName>CSP</fullName>
    </customValue>
    <customValue>
        <fullName>CU1</fullName>
    </customValue>
    <customValue>
        <fullName>DLP</fullName>
    </customValue>
    <customValue>
        <fullName>ELP</fullName>
    </customValue>
    <customValue>
        <fullName>EP1</fullName>
    </customValue>
    <customValue>
        <fullName>FTS</fullName>
    </customValue>
    <customValue>
        <fullName>GEX</fullName>
    </customValue>
    <customValue>
        <fullName>GGA</fullName>
    </customValue>
    <customValue>
        <fullName>GGG</fullName>
    </customValue>
    <customValue>
        <fullName>GLS</fullName>
    </customValue>
    <customValue>
        <fullName>GNS</fullName>
    </customValue>
    <customValue>
        <fullName>GSC</fullName>
    </customValue>
    <customValue>
        <fullName>HLS</fullName>
    </customValue>
    <customValue>
        <fullName>HWA</fullName>
    </customValue>
    <customValue>
        <fullName>HX1</fullName>
    </customValue>
    <customValue>
        <fullName>ICP</fullName>
    </customValue>
    <customValue>
        <fullName>IMQ</fullName>
    </customValue>
    <customValue>
        <fullName>IMS</fullName>
    </customValue>
    <customValue>
        <fullName>INF</fullName>
    </customValue>
    <masterLabel>Material Group 1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/BatchUpdateAgreementLineItemPriority.cls
/**
* @ author       : Nishan Shetty
* @ date         : 27-June-2022
* @ Description  : DCP-52703 Batch Class for updating Priority Field on Agreement Line Item.
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                   Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Nishan Shetty        27-June-2022               Initial version
**********************************************************************************************************************/
public without sharing class BatchUpdateAgreementLineItemPriority extends ilib_BatchDeferrable {

  //Class Variables.
  public final static String LOG_TITLE = 'BatchUpdateAgreementLineItemPriority';
  public final static String STRING_BATCH_SIZE_PARAMETER ='BatchUpdateAgreementLineItemPrioritySize';
  Map<String,Material_Group__mdt> mapMaterialGroupMetaData = new Map<String,Material_Group__mdt>();
 
  /*Constructor.*/
  public BatchUpdateAgreementLineItemPriority() {
    super();
    this.mapMaterialGroupMetaData=Material_Group__mdt.getAll();
  }
 
  /* Batch Start Method to query records */
  public override Database.QueryLocator start(Database.BatchableContext bc) {
     String query = 'Select Id,Apttus_Approval__Approval_Status__c,Apttus__AgreementId__r.Apttus_Approval__Approval_Status__c,Material_Group_1__c,Priority__c from Apttus__AgreementLineItem__c where Apttus_Approval__Approval_Status__c = \'Approval Required\' and Apttus__AgreementId__r.Apttus_Approval__Approval_Status__c =\'Approval Required\' and Material_Group_1__c!=null ';
     return Database.getQueryLocator(query);
  }
 
  /* Batch Execute Method to process records */
  public override void execute(Database.BatchableContext bc, List<sobject> lstAgreementLineItems) { 
     ilib_LogEvent.setBatchTitle(LOG_TITLE,transactionId);
     ilib_LogEvent.push('BatchUpdateAgreementLineItemPriority.execute');

     for(Apttus__AgreementLineItem__c objAgreementLineItem:(List<Apttus__AgreementLineItem__c>)lstAgreementLineItems) {
      if(mapMaterialGroupMetaData.containsKey(objAgreementLineItem.Material_Group_1__c) 
      && mapMaterialGroupMetaData.get(objAgreementLineItem.Material_Group_1__c).Priority__c!=null) {
          objAgreementLineItem.Priority__c=mapMaterialGroupMetaData.get(objAgreementLineItem.Material_Group_1__c).Priority__c;
      }
      }
      ilib_LogEvent.message('lstAgreementLineItems:'+lstAgreementLineItems);
      List<Database.SaveResult> lstSaveErrors = Database.update(lstAgreementLineItems,false);
      ApexExceptions.emitSaveErrors(lstSaveErrors,LOG_TITLE);
     ilib_LogEvent.pop();
 
  }
 
   /* Batch Finish Method for post execute logic */ 
   public override void finish(Database.BatchableContext bc) {
 
   }
 
 /************************************************************************************************
   Deferrable implementation
 *************************************************************************************************/
   
   /*
   *  @Author      : Nishan Shetty
   *  @Description : Method to simple input serialization
   *  @Param       : None
   *  @Return      : String
   */
   public override String serializeInputs() {
     return JSON.serialize('No input for this class');
 }
 /*
 *  @Author      : Nishan Shetty
 *  @Description : Method to simple input deserialization
 *  @Param       : String
 *  @Return      : void
 */
 public override void restoreInputs(String serializedInputs) { }   
 
 /*
 *  @Author      : Nishan Shetty
 *  @Description : Method to get default val
 *  @Param       : None
 *  @Return      : Integer
 */
 public override Integer getDefaultBatchSize() {
 List<Code_Parameter__mdt> lstCodeParameter = new CodeParametersSelector().selectCodeParameterByDeveloperName(
      new Set<String> {STRING_BATCH_SIZE_PARAMETER}
  );
  return Integer.valueOf(lstCodeParameter[0].Value__c);
 }
      
}
 