force-app/main/default/objects/Apttus__AgreementLineItem__c/Apttus__AgreementLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus__AgreementId__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AgreementId__c</fullName>
    <description>ID of the associated agreement</description>
    <label>Agreement</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Agreement Line Items</relationshipLabel>
    <relationshipName>AgreementLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected product or service</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Agreement Line Items</relationshipLabel>
    <relationshipName>AgreementLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__LineStatus__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__LineStatus__c</fullName>
    <description>The line status</description>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Customer_Election__c.field-meta.xml
<CustomField>
    <fullName>Customer_Election__c</fullName>
    <description>Discount Option elected by the customer.</description>
    <label>Customer Election</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Supply Agreement</fullName>
            </value>
            <value>
                <fullName>Universal Grid</fullName>
            </value>
            <value>
                <fullName>PSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Customer_ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_ERP_Number__c</fullName>
    <description>Field to store ERP Number of Customer Account</description>
    <label>Customer ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount applied like % Discount, Fixed Price etc.</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <description>Specifies type of line added. Ex: Material Group 1</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Material Group 1</fullName>
            </value>
            <value>
                <fullName>Price Group - Material</fullName>
            </value>
            <value>
                <fullName>Price Group - Material Group 1</fullName>
            </value>
            <value>
                <fullName>Quota</fullName>
            </value>
            <value>
                <fullName>UC - Material</fullName>
            </value>
            <value>
                <fullName>UC - Material Group 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Open_Offer_Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Line_Type__c</fullName>
    <description>Describes the type of line item related to Open offer Agreements</description>
    <label>Open Offer Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>PSP Category</fullName>
            </value>
            <value>
                <fullName>PSP Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Field to store Sales Org</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Account_ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_ERP_Number__c</fullName>
    <description>Field to store the Account's erp number</description>
    <formula>Apttus__Account__r.ERP_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ERP Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/ALIs_with_UC_Material_Discount__c.field-meta.xml
<CustomField>
    <fullName>ALIs_with_UC_Material_Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of the numer of line items with UC Material Discount % - DCP-47006</description>
    <label>ALIs with UC Material Discount %</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/ALIs_with_UC_Material_Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>ALIs_with_UC_Material_Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of the line items with  UC Material Discount Amount - DCP-47006</description>
    <label>ALIs with UC Material Discount Amount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/ALIs_with_UC_Material_Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>ALIs_with_UC_Material_Fixed_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of the number of line items with  UC Material Fixed Price - DCP-47006</description>
    <label>ALIs with UC Material Fixed Price</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/ALIs_with_UC_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>ALIs_with_UC_Material_Group__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of the number of line items with UC Material Group discounts - DCP-47006</description>
    <label>ALIs with UC Material Group</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Open_Offer_Election_And_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Election_And_Product_Type__c</fullName>
    <description>Field to Store the Agreement line item Customer Election value and Product type values.</description>
    <label>Open Offer Election And Product Type</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Open_Offer_Product_and_Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Product_and_Line_Type__c</fullName>
    <description>Field to Store the Open Offer agreement line items line type and Product&apos;s material class values.</description>
    <label>Open Offer Product and Line Type</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Open_Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Status__c</fullName>
    <description>This Field is to identify the current status of the open offer agreement</description>
    <label>Open Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
                <default>true</default>
                <label>Request</label>
            </value>
            <value>
                <fullName>Eligibility Approval</fullName>
            </value>
            <value>
                <fullName>Affiliate Confirmation</fullName>
            </value>
            <value>
                <fullName>Election Template</fullName>
            </value>
            <value>
                <fullName>Signatures</fullName>
            </value>
            <value>
                <fullName>In Effect</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Field to store Sales Org</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Material_Class__c.field-meta.xml
<CustomField>
    <fullName>Material_Class__c</fullName>
    <description>Requested by : user story DCP – 2073
Why : To be able to classify the products
Value source : Information would flow in from SAP</description>
    <label>Material Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informatics Software</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Document Training</fullName>
            </value>
            <value>
                <fullName>Tools</fullName>
            </value>
            <value>
                <fullName>Service Part</fullName>
                <isActive>false</isActive>
                <label>Service Part</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>AT01</fullName>
    </customValue>
    <customValue>
        <fullName>AU01</fullName>
    </customValue>
    <customValue>
        <fullName>BE01</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
    </customValue>
    <customValue>
        <fullName>CN01</fullName>
    </customValue>
    <customValue>
        <fullName>CN02</fullName>
    </customValue>
    <customValue>
        <fullName>CN03</fullName>
    </customValue>
    <customValue>
        <fullName>DE01</fullName>
    </customValue>
    <customValue>
        <fullName>CO01</fullName>
    </customValue>
    <customValue>
        <fullName>DK01</fullName>
    </customValue>
    <customValue>
        <fullName>ES01</fullName>
    </customValue>
    <customValue>
        <fullName>FI01</fullName>
    </customValue>
    <customValue>
        <fullName>FR01</fullName>
    </customValue>
    <customValue>
        <fullName>FR02</fullName>
    </customValue>
    <customValue>
        <fullName>FR90</fullName>
    </customValue>
    <customValue>
        <fullName>GB01</fullName>
    </customValue>
    <customValue>
        <fullName>GB02</fullName>
    </customValue>
    <customValue>
        <fullName>GB03</fullName>
    </customValue>
    <customValue>
        <fullName>GB90</fullName>
    </customValue>
    <customValue>
        <fullName>HK01</fullName>
    </customValue>
	<customValue>
        <fullName>IE01</fullName>
    </customValue> 
	<customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IS01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>JP01</fullName>
    </customValue>
    <customValue>
        <fullName>KR01</fullName>
    </customValue>
    <customValue>
        <fullName>NL01</fullName>
    </customValue>
    <masterLabel>Sales Org</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ApttusAgreementsHelper.cls
/**
 *    @author Bharath Varma
 *    @date   29-Jun-2021
 *    @description :   Agreement Helper class to maintain common methods used for both Agreement and Agreement Line Items
*    Test Class 90% Coverage : TestApttusAgreements
 *   Test Class 75% Coverage :TestAgrLinesFindDuplicatesController , TestOpenOfferAgreements.
 *    Modification Log:
 *   ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 *       Developer                        Date               Description
 *     Bharath Varma                   29-Jun-2021          Initial Version
 *     Bharath Varma                   07-Apr-2022          Removed future method as it was replaced by a Queueable (AutoUpdateFieldsOnAgreementQueueable.cls)  
 *     Saddam                          25-Aug-2022          Modified getMapIdToAgreement() and updateAgrFromLineItems() and created 2 new methods setAgreementValuesForRegularAgreements(),setAgreementValuesForOpenOfferAgreements() methods.
 *     Saddam                          25-Aug-2022          Modified  updateAgrFromLineItems Created 2 new methods to set agreement Open offer customer election and Openoffer Product type value and line type mapping.
 *     Ashwin                          25-Jan-2023          INC0449613 - Correct field used in conditions.
 *    ------------------------------------------------------------------------------------------------------------------------------------
 */
public with sharing class ApttusAgreementsHelper {

    private static final String UC_MATERIAL = 'UC - Material';
    private static Map<Id, RecordTypeInfo> rtMap;
    private static Set<string> setOfOpenOfferStatus = new Set<string>{'Election Template','Signatures','In Effect','Amended','Cancelled'};
    private static final String STRCOLON = ' : ';
    private static final String STRCOMMA = ',';
    public static Boolean boolIsAgreementLineDeleted = false;


    /*
    @Author : Bharath Varma
    @Story : DCP-47006
    @Description : Method to get record type map.
    @Test Class : TestApttusAgreements.testUCMaterialRollUp
    */
    public static Map<Id, RecordTypeInfo> getRecordTypeMap()
    {
        if (rtMap == null) { rtMap = Apttus__APTS_Agreement__c.sObjectType.getDescribe().getRecordTypeInfosById(); }
        return rtMap;
    }
  
    
    /*
    @Author : Bharath Varma
    @Story : DCP-47006
    @Description : Method to get Id to Agreement Map.
    @Parameters : List of Agreements
    @Test Class : TestApttusAgreements.testUCMaterialRollUp
    @Modified  : Added a condition to check Open Offer agreement. DCP-54810 
    @MODIFIED AUTHOR : SADDAM 
    */
    public static Map<Id, Apttus__APTS_Agreement__c> getMapIdToAgreement(List<Apttus__APTS_Agreement__c> lstAgreements) {
        String rtName;
        Map<Id, RecordTypeInfo> idToRecordTypeInfo = getRecordTypeMap();
        Map<Id, Apttus__APTS_Agreement__c> mapIdToAgreement = new Map<Id, Apttus__APTS_Agreement__c>();

        for(Apttus__APTS_Agreement__c agr: lstAgreements) {
            if (agr.RecordTypeId != null) {
                rtName = idToRecordTypeInfo.get(agr.RecordTypeId).getDeveloperName(); 
            }
            if(rtName == Label.AgreementRecordTypeChannelPartner) {
                agr.ALIs_with_UC_Material_Group__c = 0;
                agr.ALIs_with_UC_Material_Discount__c = 0;
                agr.ALIs_with_UC_Material_Discount_Amount__c = 0;
                agr.ALIs_with_UC_Material_Fixed_Price__c = 0;
                mapIdToAgreement.put(agr.Id, agr);
            }
            else if(AutoUpdateFieldsOnAgreementQueueable.boolIsOpenOfferAgreement == true && rtName == Label.AgreementRecordTypeOpenOffer) {
                mapIdToAgreement.put(agr.Id, agr);
            }
        }
        ilib_LogEvent.info('mapIdToAgreement: '+mapIdToAgreement);
        return mapIdToAgreement;
    }

    /*
    @Author : Bharath Varma
    @Story : DCP-47006
    @Description : Method to Update the fields on Agreement based on the type of line items
    @Parameters : List of Agreements, Map Id to Agreement
    @Test Class : TestApttusAgreements.testUCMaterialRollUp
    @Modfied method and split the code to to 2 new methods to  check  Open offer agreements.
    @MODIFIED AUTHOR : SADDAM 
    */
    public static List<Apttus__APTS_Agreement__c> updateAgrFromLineItems(List<Apttus__AgreementLineItem__c> lstAgreementLineItems, Map<Id, Apttus__APTS_Agreement__c> mapIdToAgreement) {
      
        List<Apttus__APTS_Agreement__c> lstUpdatedAgts = new List<Apttus__APTS_Agreement__c>();
        Set<Id> setUpdatedAgreementIds = new Set<Id>();
        Map<Id, RecordTypeInfo> idToRecordTypeInfo = getRecordTypeMap();
        Map<Id,Set<String>> mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType =  new Map<Id,Set<String>>();    //DCP-56505
        Map<Id,Set<String>> mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus =  new Map<Id,Set<String>>();    //DCP-56505

        for(Apttus__AgreementLineItem__c agrLI : lstAgreementLineItems) {
            Boolean erpAndSalesOrg = mapIdToAgreement.containsKey(agrLI.Apttus__AgreementId__c) && mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).Account_ERP_Number__c == agrLI.Customer_ERP_Number__c && mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).Sales_Org__c == agrLI.Sales_Org__c;
            Boolean currencyCheck = mapIdToAgreement.containsKey(agrLI.Apttus__AgreementId__c) && agrLI.CurrencyIsoCode == mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).CurrencyIsoCode;
           
            if(!mapIdToAgreement.containsKey(agrLI.Apttus__AgreementId__c)) {continue;}
            Boolean boolIsOpenOffer =  idToRecordTypeInfo.get(mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).RecordTypeId).getDeveloperName() == System.label.AgreementRecordTypeOpenOffer;
            
            if(boolIsOpenOffer) {
                setAgreementValuesForOpenOfferAgreements(agrLI,mapIdToAgreement,mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType,mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus);
            } else {
                setAgreementValuesForRegularAgreements(erpAndSalesOrg,currencyCheck,agrLI,mapIdToAgreement);
            }


            if(mapIdToAgreement.containsKey(agrLI.Apttus__AgreementId__c) && !setUpdatedAgreementIds.contains(agrLI.Apttus__AgreementId__c)) {
                lstUpdatedAgts.add(mapIdToAgreement.get(agrLI.Apttus__AgreementId__c));
                setUpdatedAgreementIds.add(agrLI.Apttus__AgreementId__c);
            }
        }
        return lstUpdatedAgts;  

    }    
    /*
    @Author : saddam
    @Story : DCP-54532
    @Description : Method to Update the fields on Open offer status of OO Agreement based on the type of line status fo agrmnt line items.
    @Parameters : Agreement record and Map of agreement id to agreement record.
    @Test Class : tESToPENoFFERAGREEMENTS
    @Modified : DCP-54532
    */
    public static void  setAgreementValuesForOpenOfferAgreements(Apttus__AgreementLineItem__c agrLI,Map<Id, Apttus__APTS_Agreement__c> mapIdToAgreement,Map<Id,Set<String>> mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType,Map<Id,Set<String>> mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus) {

        Boolean boolLineStatusCriteriaSatisfied   = agrLI.Apttus_CMConfig__LineStatus__c == System.label.AgreementLineItemLineStatusNew || agrLI.Apttus_CMConfig__LineStatus__c == System.label.AgreementLineItemLineStatusUpdated;

        if(boolLineStatusCriteriaSatisfied && !setOfOpenOfferStatus.contains(mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).Open_Offer_Status__c) && !boolIsAgreementLineDeleted) { 
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).Open_Offer_Status__c = System.label.AgreementOpenOfferStatusElectionTemplate;
        }
         
        setAgreementOpenOfferCustomerElectionToProductTypeAndLineStatusAndLineType(agrLI, mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType);

        setAgreementOpenOfferLineTypeToProductTypeAndLineStatus(agrLI, mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus);
        
        if(mapIdToAgreement.containskey(agrLI.Apttus__AgreementId__c) && mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType.containsKey(agrLI.Apttus__AgreementId__c)) {
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).Open_Offer_Election_And_Product_Type__c = String.join(new List<String>(mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType.get(agrLI.Apttus__AgreementId__c)), ';');
        }

        if(mapIdToAgreement.containskey(agrLI.Apttus__AgreementId__c) && mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus.containsKey(agrLI.Apttus__AgreementId__c)) {
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).Open_Offer_Product_and_Line_Type__c = String.join(new List<String>(mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus.get(agrLI.Apttus__AgreementId__c)), ';');
        }
    }

     /*
    @Author : saddam
    @Story : DCP-56505
    @Description : Method to Update Open offer Customer Election.
    @Parameters : Agreement record and Map of agreement id to Set of string.
    @Test Class : 
    */
    public static void setAgreementOpenOfferCustomerElectionToProductTypeAndLineStatusAndLineType(Apttus__AgreementLineItem__c agrLI,Map<Id,Set<String>> mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType) {
        
        Set<String> setStringCustomerElectionAndProductTypeAndLineStatusAndLineType = new Set<String>();
        if(mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType.containskey(agrLI.Apttus__AgreementId__c) ) {
            mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType.get(agrLI.Apttus__AgreementId__c).add(agrLI.Customer_Election__c+STRCOLON+agrLI.Apttus__ProductId__r.Material_Class__c+STRCOMMA+agrLI.Apttus_CMConfig__LineStatus__c+STRCOMMA+agrLI.Open_Offer_Line_Type__c);
        } else if(!mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType.containskey(agrLI.Apttus__AgreementId__c)) {
            setStringCustomerElectionAndProductTypeAndLineStatusAndLineType.add(agrLI.Customer_Election__c+STRCOLON+agrLI.Apttus__ProductId__r.Material_Class__c+STRCOMMA+agrLI.Apttus_CMConfig__LineStatus__c+STRCOMMA+agrLI.Open_Offer_Line_Type__c);
            mapOfAgrIdToOpenOfferElectionToProductTypeAndLineStatusAndLineType.put(agrLI.Apttus__AgreementId__c,setStringCustomerElectionAndProductTypeAndLineStatusAndLineType);
        }
    }
     /*
    @Author : saddam
    @Story : DCP-56505
    @Description : Method to Update Open offer Customer Election.
    @Parameters : Agreement record and Map of agreement id to Set of string.
    @Test Class : 
    */
    public static void setAgreementOpenOfferLineTypeToProductTypeAndLineStatus(Apttus__AgreementLineItem__c agrLI,Map<Id,Set<String>> mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus) {
        
        Set<String> setStringProductTypeToLineTypeAndLineStatus = new Set<String>();
        if(mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus.containskey(agrLI.Apttus__AgreementId__c) ) {
            mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus.get(agrLI.Apttus__AgreementId__c).add(agrLI.Apttus__ProductId__r.Material_Class__c+STRCOLON+agrLI.Open_Offer_Line_Type__c+STRCOMMA+agrLI.Apttus_CMConfig__LineStatus__c);
        } else if(!mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus.containskey(agrLI.Apttus__AgreementId__c)) {
            setStringProductTypeToLineTypeAndLineStatus.add(agrLI.Apttus__ProductId__r.Material_Class__c+STRCOLON+agrLI.Open_Offer_Line_Type__c+STRCOMMA+agrLI.Apttus_CMConfig__LineStatus__c);
            mapOfAgrIdToOpenOfferProductTypeToLineTypeAndLineStatus.put(agrLI.Apttus__AgreementId__c,setStringProductTypeToLineTypeAndLineStatus);
        }
    }

    /*
    *  @author       : Saddam
    *  @description  : Set value of bool
    *  @param        : Boolean boolValue
    *  @return       : void
    */
    public static void setFlagForAgreementlineDeletion(Boolean boolValue) {
        boolIsAgreementLineDeleted = boolValue;
    } 

    /*
    *  @author       : Saddam
    *  @description  : get value of boolean
    *  @param        : null
    *  @return       : Boolean
    */
    public static Boolean isFlagForAgreementlineDeletionTrue() {
        return boolIsAgreementLineDeleted;
    }

    /*
    @Author : saddam
    @Story : DCP-54810
    @Description : Method to Update the fields on Non Open offer Agreement.
    @Parameters : Agreement record and Map of agreement id to agreement record,Boolean ,Agreement record.
    @Test Class : 
    */
    public static void  setAgreementValuesForRegularAgreements(Boolean erpAndSalesOrg,Boolean currencyCheck, Apttus__AgreementLineItem__c agrLI, Map<Id, Apttus__APTS_Agreement__c> mapIdToAgreement) {
           
        if(erpAndSalesOrg &&  agrLI.Line_Type__c == 'UC - Material Group 1') {
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).ALIs_with_UC_Material_Group__c += 1;
        } else if(erpAndSalesOrg &&  agrLI.Line_Type__c == UC_MATERIAL && agrLI.Discount_Type__c == '% Discount') {                         //INC0449613
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).ALIs_with_UC_Material_Discount__c += 1;
        } else if(erpAndSalesOrg &&  agrLI.Line_Type__c == UC_MATERIAL && agrLI.Discount_Type__c == 'Discount Amount' && currencyCheck) {   //INC0449613
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).ALIs_with_UC_Material_Discount_Amount__c += 1;
        } else if(erpAndSalesOrg &&  agrLI.Line_Type__c == UC_MATERIAL &&  agrLI.Discount_Type__c == 'Fixed Amount' && currencyCheck) {     //INC0449613
            mapIdToAgreement.get(agrLI.Apttus__AgreementId__c).ALIs_with_UC_Material_Fixed_Price__c += 1;
        }  
    }

}