force-app/main/default/objects/Apttus__AgreementLineItem__c/Apttus__AgreementLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus__AgreementId__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AgreementId__c</fullName>
    <description>ID of the associated agreement</description>
    <label>Agreement</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Agreement Line Items</relationshipLabel>
    <relationshipName>AgreementLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <description>Approval status of the agreement line item</description>
    <inlineHelpText>Approval status of the agreement line item</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Agreement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_End_Date__c</fullName>
    <description>Field to store the Agreement's end date</description>
    <formula>IF (
NOT(ISBLANK( Apttus__Contract_End_Date__c )),
( CASE ( MONTH ( Apttus__Contract_End_Date__c ) ,
1, $Label.MonthJan,
2, $Label.MonthFeb,
3, $Label.MonthMar,
4, $Label.MonthApr,
5, $Label.MonthMay,
6, $Label.MonthJun,
7, $Label.MonthJul,
8, $Label.MonthAug,
9, $Label.MonthSep,
10, $Label.MonthOct,
11, $Label.MonthNov,
$Label.MonthDec)) +&apos; &apos;+Text ( DAY( Apttus__Contract_End_Date__c ) )+&apos; &apos;+Text (YEAR ( Apttus__Contract_End_Date__c ) ),Null)</formula>
    <label>Agreement End Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Account__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The link to the account record to identify the external party to this agreement</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N50000001Xl0UEAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Activated_Date__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Activated_Date__c</fullName>
    <description>The date the agreement was activated in the system</description>
    <label>Activated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Status__c</fullName>
    <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
    <inlineHelpText>This field states the current sub process of within the lifecycle of the Agreement.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Apttus__Status_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
                <default>true</default>
                <label>Request</label>
            </value>
            <value>
                <fullName>Request Approval</fullName>
            </value>
            <value>
                <fullName>Submitted Request</fullName>
            </value>
            <value>
                <fullName>Approved Request</fullName>
            </value>
            <value>
                <fullName>Cancelled Request</fullName>
            </value>
            <value>
                <fullName>In Amendment</fullName>
            </value>
            <value>
                <fullName>Author Contract</fullName>
            </value>
            <value>
                <fullName>Language Approval</fullName>
            </value>
            <value>
                <fullName>Language Approved</fullName>
            </value>
            <value>
                <fullName>Internal Signatures</fullName>
            </value>
            <value>
                <fullName>Other Party Signatures</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Being Amended</fullName>
            </value>
            <value>
                <fullName>Being Renewed</fullName>
            </value>
            <value>
                <fullName>In Renewal</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Being Terminated</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>In Reconciliation</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
            <value>
                <fullName>Other Party Review</fullName>
            </value>
            <value>
                <fullName>Signature Declined</fullName>
            </value>
            <value>
                <fullName>Ready for Signatures</fullName>
            </value>
            <value>
                <fullName>Fully Signed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Status_Category__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Status_Category__c</fullName>
    <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
    <inlineHelpText>This fields states the current lifecycle of the Agreement.</inlineHelpText>
    <label>Status Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
                <default>true</default>
                <label>Request</label>
            </value>
            <value>
                <fullName>In Authoring</fullName>
            </value>
            <value>
                <fullName>In Signatures</fullName>
            </value>
            <value>
                <fullName>In Filing</fullName>
            </value>
            <value>
                <fullName>In Effect</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Subtype__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Subtype__c</fullName>
    <description>The subtype of the agreement for a given agreement type</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Non-Standard</fullName>
            </value>
            <value>
                <fullName>Lead Gen</fullName>
            </value>
            <value>
                <fullName>Customized Agreement</fullName>
            </value>
            <value>
                <fullName>Pricing Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Terms</fullName>
            </value>
            <value>
                <fullName>Termed</fullName>
            </value>
            <value>
                <fullName>One Time Sale</fullName>
            </value>
            <value>
                <fullName>One Time Sale &amp; Termed</fullName>
            </value>
            <value>
                <fullName>IHPP</fullName>
            </value>
            <value>
                <fullName>Reagent Rental</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <inlineHelpText>This field states the current approval status of the Agreement.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Field to store Created Date</description>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Number_Of_Agreement_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Agreement_Line_Items__c</fullName>
    <description>Roll up to store the number of line items</description>
    <label>Number Of Agreement Line Items</label>
    <summaryForeignKey>Apttus__AgreementLineItem__c.Apttus__AgreementId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>this field will populate the agreement record type name</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Related_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Related_Agreement__c</fullName>
    <businessOwnerUser>gpikes@illumina.com</businessOwnerUser>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to  an already existing agreement between Illumina and Customer.</description>
    <label>Related Agreement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Apttus__APTS_Agreement__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tender</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Agreements (Related Agreement)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateAgreementsCreatedPriorToDG.cls
/*@ author       : Vinay S Reddy
* @ date         : 26-06-2024
* @ Description  : Batch class to Data remediation - Discount Guidance for the Agreements created prior to DG Launch
 * 100% Code Coverage: 
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                   Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Vinay S Reddy             26-06-2024             Initial version
 * Pradeep L                 04-07-2024             Refactoring
*/

public class BatchToUpdateAgreementsCreatedPriorToDG implements Database.Batchable < sObject >, Database.Stateful {

    //private list < String > companyNameList = new list < String > {'a2gWH0000005i21YAA'};
    //private final static String APPREQ = 'Approval Required';
    private final static String PENDAPP = 'Pending Approval';
    Set<Id> agreementIds = new Set<Id>();
	
    List < Apttus__AgreementLineItem__c > agreementLineItemList = new List < Apttus__AgreementLineItem__c > ();
    Id idofAgreementsToRecallToRequest,idofAgreementsToCanelApprovals,idofAgreementsForApproval;

        private List<String> errors = new List<String>();
     public List < Database.SaveResult > saveResults = new List < Database.SaveResult > ();
    
    private static final String LOG_TITLE = 'BatchToUpdateAgreementsCreatedPriorToDG';
	set<Id> agmntIdtoprocessLargeLines = new set<Id>();
    /**
     *  @author Pradeep L
     *  @description Constructor
     **/
    public BatchToUpdateAgreementsCreatedPriorToDG(Set<Id> agreementIdSet) {
        this.agreementIds = agreementIdSet; 
    }

    /**
     *  @author Pradeep L
     *  @description Constructor default
     **/
    public BatchToUpdateAgreementsCreatedPriorToDG() {
     // setting workstream
     ilib_LogEvent.setWorkstream(ilib_LogEvent.SALES);  
    }
    
    @TestVisible
    private static Boolean useOldFrameworkWhileTesting = true;
    /**
     * @author:Vinay S Reddy
     * @date: 26-08-2024
     * @description: Required start method for batch
     * @param: bc - batch context 
     * @return: query
     */
  
        
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String strSoql = 'Select Id, Name,Number_Of_Agreement_Line_Items__c,Apttus__Account__c,Apttus__Status_Category__c,Apttus__Status__c,Apttus_Approval__Approval_Status__c,Created_Date__c,Agreement_End_Date__c,Apttus__Activated_Date__c,Related_Agreement__c,Record_Type__c,Apttus__Subtype__c From Apttus__APTS_Agreement__c Where ' +
            ' Apttus__Status_Category__c  IN (\'Request\', \'In Authoring\', \'In Signatures\', \'In Filing\') and Apttus_Approval__Approval_Status__c IN (\'Approval Required\', \'Pending Approval\', \'Rejected\', \'Cancelled\') And Number_Of_Agreement_Line_Items__c > 0 AND ( Record_Type__c !=\'Open Offer Agreement\' AND (Record_Type__c !=\'Special Programs\' AND Apttus__Subtype__c != \'Reagent Rentals\')) dynamicAgreementIds';
            if(agreementIds?.size()>0){
                strSoql = strSoql.replace('dynamicAgreementIds', ' AND Id IN : agreementIds');
            }else{
                strSoql = strSoql.replace('dynamicAgreementIds', '');
            }
            return Database.getQueryLocator(strSoql);   
        }

    /**
     * @author: Vinay S Reddy
     * @date: 26-08-2024
     * @description: Required execute method for batch
     * @param: bc - batch context
     * @return: void
     */    

    /*Execute method of Batch Class*/    
    public void execute(Database.BatchableContext bc, list < Apttus__APTS_Agreement__c > scope) {
        agreementLineItemList = new List < Apttus__AgreementLineItem__c > ();
        List < Database.SaveResult > saveResults = new List < Database.SaveResult > ();
	
        Set < string > statusCatSet = new Set < string > {
            'Request',
            'In Authoring',
            'In Signatures',
            'In Filing'
        };
        Set < Id > agreementSet = new Set < Id > {scope[0].Id};
            System.Debug('Current Agreement Record to be processed 1'+scope);
        
        for(Apttus__AgreementLineItem__c  ali : new ApttusAgreementLineItemSelectors().selectAgreementLineItemNew(agreementSet)){
            agreementLineItemList.addAll(new List<Apttus__AgreementLineItem__c>{ali});
        }

        if (statusCatSet.contains(scope[0].Apttus__Status_Category__c)) {
            idofAgreementsForApproval = scope[0].Id;
            if (scope[0].Apttus_Approval__Approval_Status__c == PENDAPP) {
                idofAgreementsToRecallToRequest = scope[0].Id;
                idofAgreementsToCanelApprovals = scope[0].Id;
            } else if (scope[0].Apttus_Approval__Approval_Status__c == 'Rejected' || scope[0].Apttus_Approval__Approval_Status__c == 'Cancelled') {
                idofAgreementsToRecallToRequest = scope[0].Id;
            }
        }
        /*if (scope[0].Apttus__Status_Category__c == 'Request' || scope[0].Apttus__Status_Category__c == 'In Authoring' || scope[0].Apttus__Status_Category__c == 'In Signatures' || scope[0].Apttus__Status_Category__c == 'In Filing') {
            if (scope[0].Apttus_Approval__Approval_Status__c == PENDAPP) {
                        agreementLineItemList1.addAll(scope[0].Apttus__AgreementLineItems__r);
                idofAgreementsToRecallToRequest = scope[0].Id;
                        idofAgreementsToCanelApprovals = scope[0].Id;
                        idofAgreementsForApproval = scope[0].Id;
                    } 
                    if (scope[0].Apttus_Approval__Approval_Status__c == 'Rejected' || scope[0].Apttus_Approval__Approval_Status__c == 'Cancelled') {
                        agreementLineItemList1.addAll(scopE[0].Apttus__AgreementLineItems__r);
                idofAgreementsToRecallToRequest = scope[0].Id;
                        idofAgreementsForApproval = scope[0].Id;
                    }                     
            if (scope[0].Apttus_Approval__Approval_Status__c == APPREQ) {
                        agreementLineItemList1.addAll(scope[0].Apttus__AgreementLineItems__r);
                        idofAgreementsForApproval = scope[0].Id;
                    }
        }*/
            

            // Cancelling Approvals

        if (idofAgreementsToCanelApprovals != null) {
            Boolean status = Apttus_Approval.ApprovalsWebService.cancelApprovals('Apttus__APTS_Agreement__c', idofAgreementsToCanelApprovals);
            System.debug('Status  ' + status);
            }
		
            
            // Status Category of Agreements to 'Request' and Status to 'Request'               
        if (idofAgreementsToRecallToRequest != null)
                AgreementRevertToRequest.agreementRevertToRequest(idofAgreementsToRecallToRequest);
                             
                //DG Fields Update
                
        if(agreementLineItemList != null && !agreementLineItemList.isEmpty() && agreementLineItemList.size() < 200){
                    DiscountGuidancePopulatorForCLM populator = new DiscountGuidancePopulatorForCLM();
        populator.deriveFieldValuesForDiscountGuidance(agreementLineItemList, null);
        //approveAgreements(scope, agreementLineItemList);
        if (!agreementLineItemList.isEmpty()) {
            saveResults.addAll(Database.update(agreementLineItemList, false));
            handleSaveResults(saveResults, 'Agreement Line Items after Approval Selection', errors);
            ApexExceptions.emitSaveErrors(saveResults, LOG_TITLE );
        }  
        } else if(agreementLineItemList != null && !agreementLineItemList.isEmpty()) {
           // agmntIdtoprocessLargeLines.clear();
            agmntIdtoprocessLargeLines.add(scope[0].Id);
        }
        

        
        }

        // Method to handle save results and errors
    private void handleSaveResults(List < Database.SaveResult > saveResults, String objectType, List < String > errors) {
        ilib_LogEvent.push(LOG_TITLE + '.execute()');
        for (Database.SaveResult saveResult: saveResults) {
            if (!saveResult.isSuccess()) {
                for (Database.Error e: saveResult.getErrors()) {
                    errors.add(objectType + ' Error: ' + e.getStatusCode() + ' - ' + e.getMessage());
                    System.debug(objectType + ' Error: ' + e.getStatusCode() + ' - ' + e.getMessage());
                    ilib_LogEvent.info(objectType + ' Error: ' + e.getStatusCode() + ' - ' + e.getMessage());
                    System.debug(objectType + ' fields that affected this error: ' + e.getFields());
                    ilib_LogEvent.info(objectType + ' fields that affected this error: ' + e.getFields());
                    System.debug(objectType + ' record that affected this id: ' + saveResult.getId());
                    ilib_LogEvent.info(objectType + ' record that affected this id: ' + saveResult.getId());
                }
             }
            if (saveResult.isSuccess()) {
                System.debug('Success Status for Agreements/Agreement Line Items   ' + saveResult);
                ilib_LogEvent.info('Success Status for Agreements/Agreement Line Items   ' + saveResult);
             }
         }
         ilib_LogEvent.pop();
         ilib_LogEvent.emit(); 

    }

    /*   // Method for agreement approvals
    private void approveAgreements(List < Apttus__APTS_Agreement__c > agreeementList, List < Apttus__AgreementLineItem__c > agreementLineItemList ) {
        
        //Approval setup
        List < Apttus__APTS_Agreement__c > listAgreementsFromIntialize = new List < Apttus__APTS_Agreement__c > ();
        Set < Id > agreementSet = new Set < Id > ();
        //agreementSet.add(idofAgreementsForApproval);
        agreementSet.add(agreeementList[0].Id);
        listAgreementsFromIntialize = new ApttusAgreementSelectors().selectAgreements(agreementSet);
        //// DCP-50961 : NEW APPROVALS start
        

            Boolean forceOldFramework = System.Test.isRunningTest() && useOldFrameworkWhileTesting;
        if (Feature.isOn('SalesCLMApprovalsPipeline') && !forceOldFramework) {
            if (!agreementLineItemList.isEmpty()) {
                Approvals.AgreementLineInputs approvalInputs = new Approvals.AgreementLineInputs(agreementLineItemList, new Map < Id, Apttus__APTS_Agreement__c > (listAgreementsFromIntialize));
                    IApprovalsAPI approvals = ApprovalsService.init(approvalInputs);
                     approvals.processAgreementLines();
                }
             } 

       } */
    /**
     * @author: Vinay S Reddy
     * @date: 27-06-2024
     * @description: Required final method for batch
     * @param: bc - batch context
     * @return: void
     */
    public void finish(Database.BatchableContext bc) {
       // finish method logic
       // 
       // 
       if(agmntIdtoprocessLargeLines !=null && agmntIdtoprocessLargeLines.size() > 0)
        Database.executeBatch(new BatchToUpdateLargeAgmntLineItems(agmntIdtoprocessLargeLines),200);
    }    

}