force-app/main/default/objects/Customer_Readiness_Form__c/Customer_Readiness_Form__c.object-meta.xml
<CustomObject>
    <description>Stores specific information on customer location during the Instrument sales cycle so Sales team can share information with Service team. Information such BSA level, application use, data storage options, desired shipment or install timelines etc.</description>
    <label>Customer Readiness Form</label>
    <nameField>
        <displayFormat>CRF-{0000}-{MM}{DD}{YYYY}</displayFormat>
        <label>Customer Readiness Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Readiness Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Readiness_Form__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Lookup to Opportunity.</description>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Readiness Forms</relationshipLabel>
    <relationshipName>Customer_Readiness_Form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Primary_Field_Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Partner_Primary_Field_Service_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DCP-16207- To populate channel partner users value based on Distributor Account</description>
    <label>Partner Primary Field Service Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Field_Application_Scientist__c.field-meta.xml
<CustomField>
    <fullName>Primary_Field_Application_Scientist__c</fullName>
    <description>Lookup to User who is treated as  Primary Field Application Scientist	</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Field Application Scientist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchMigrateCRFShares.cls
    /*
    *  @Author: Todd Newman
    *  @Date: 
    *  @Description: Batch class to share Customer_Readiness_Form__c records
    *  @Test class for 90% coverage: TestBatchMigrateShares
    *  @Test class for 75% coverage: TestBatchMigrateShares
    *  Modification Log:
    *  ---------------------------------------------------------------------------------------------------------------------------
    *       Developer                      Date                Description         
    *       Todd Newman                                      Initial Version
    *       Nesar Mohan                 2022-03-30           CodeScan Fix 
    *    ---------------------------------------------------------------------------------------------------------------------------
    **/

global class BatchMigrateCRFShares extends ilib_ScheduleAndBatch {

    /*
    *  @Author      : Todd Newman
    *  @Description : Execute method for the batch class
    *  @Param       : SchedulableContext
    *  @Return      : Void
    */

    global override void execute(SchedulableContext sc)
    {
        Database.executeBatch(new BatchMigrateCRFShares());
    }

    /*
    *  @Author      : Todd Newman
    *  @Description : Start method for the batch class to collect Customer_Readiness_Form__c records
    *  @Param       : Database.BatchableContext
    *  @Return      : Database.QueryLocator
    */

    global override Database.QueryLocator start(Database.BatchableContext bc)
    {
        String soql = 'SELECT Id, Opportunity_Name__c ' +
            'FROM Customer_Readiness_Form__c ' +
            'WHERE Opportunity_Name__r.Primary_Field_Service_Engineer__c != null ' +
            'OR Opportunity_Name__r.Primary_Field_Application_Scientist__c != null ' +
            'OR Opportunity_Name__r.Field_Application_Manager__c != null ' +
            'OR Opportunity_Name__r.Field_Service_Manager__c != null ' +
            'OR Opportunity_Name__r.Partner_Primary_Field_App_Scientist__c != null ' +
            'OR Opportunity_Name__r.Partner_Primary_Field_Service_Engineer__c != null';

        return Database.getQueryLocator(soql);
    }

    /*
    *  @Author      : Todd Newman
    *  @Description : Execute method for the batch class to execute the business logic
    *  @Param       : Database.BatchableContext, List<SObject>
    *  @Return      : Void
    */

    global override void execute(Database.BatchableContext bc, List<SObject> records)
    {
        CustomerReadinessFormsService.shareWithFieldUsers((List<Customer_Readiness_Form__c>)records, null);
    }

    /*
    *  @Author      : Todd Newman
    *  @Description : Finish method for the batch class
    *  @Param       : Database.BatchableContext
    *  @Return      : Void
    */   
    
    global override void finish(Database.BatchableContext bc) { }

}