force-app/main/default/objects/Approval_Hierarchy__c/Approval_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>Represents the hierarchy levels, approvers for an account owner or custom hierarchy for CPQ and CLM workflows</description>
    <label>Approval Hierarchy</label>
    <nameField>
        <label>Approval Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Hierarchies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Hierarchy__c/fields/Approval_Hierarchy_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Hierarchy_Type__c</fullName>
    <description>Approval Hierarchy Type values.</description>
    <label>Approval Hierarchy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CLM_Custom_Hierarchy</fullName>
                <label>CLM Custom Hierarchy</label>
            </value>
            <value>
                <fullName>CLM_Sales_Hierarchy</fullName>
                <label>CLM Sales Hierarchy</label>
            </value>
            <value>
                <fullName>CPQ_Custom_Hierarchy</fullName>
                <label>CPQ Custom Hierarchy</label>
            </value>
            <value>
                <fullName>CPQ_Sales_Hierarchy</fullName>
                <label>CPQ Sales Hierarchy</label>
            </value>
            <value>
                <fullName>Discount</fullName>
                <isActive>false</isActive>
                <label>Discount</label>
            </value>
            <value>
                <fullName>Material_Class</fullName>
                <isActive>false</isActive>
                <label>Material Class</label>
            </value>
            <value>
                <fullName>Post_Pricing_Message</fullName>
                <label>Post Pricing Message</label>
            </value>
            <value>
                <fullName>Product</fullName>
                <isActive>false</isActive>
                <label>Product</label>
            </value>
            <value>
                <fullName>Product_Category</fullName>
                <isActive>false</isActive>
                <label>Product Category</label>
            </value>
            <value>
                <fullName>Product_Group</fullName>
                <isActive>false</isActive>
                <label>Product Group</label>
            </value>
            <value>
                <fullName>Product_Line</fullName>
                <isActive>false</isActive>
                <label>Product Line</label>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Standing_Discount</fullName>
                <isActive>false</isActive>
                <label>Standing Discount</label>
            </value>
            <value>
                <fullName>Standing_Material_Group_1</fullName>
                <isActive>false</isActive>
                <label>Standing Material Group 1</label>
            </value>
            <value>
                <fullName>Standing_Material_Number</fullName>
                <isActive>false</isActive>
                <label>Standing Material Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Hierarchy__c/fields/Approver_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level_2__c</fullName>
    <description>This field denotes level 2 approval user.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver (Level 2)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Hierarchies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Hierarchy__c/fields/Approver_Level_6__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level_6__c</fullName>
    <description>This field denotes level 6 approval user.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver (Level 6)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Hierarchies5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Backup_Approver__c/Apttus_Approval__Backup_Approver__c.object-meta.xml
<CustomObject>
    <description>Allows approvers and administrators to specify backup approvers.  There is an option to transfer all pending request from and to the approver and the backup approver upon activation or cancellation of backups.  The approvals engine automatically routes requests to backup approvers when this is in effect.</description>
    <label>Backup/Delegate Approver</label>
    <nameField>
        <displayFormat>BU-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backup/Delegate Approvers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Approval__Backup_Approver__c/fields/Apttus_Approval__Backup_User__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Backup_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The backup/delegate user for the current user.</description>
    <label>Backup/Delegate User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N700000028l1cEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Backup_Approver__c/fields/Apttus_Approval__DelegateUserIds__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__DelegateUserIds__c</fullName>
    <description>IDs of approvers who are designated as delegates of the current user.</description>
    <inlineHelpText>IDs of approvers who were designated as Delegate of Backup</inlineHelpText>
    <label>Delegate Users</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Backup_Approver__c/fields/Apttus_Approval__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Effective_Date__c</fullName>
    <description>Please enter an effective date only if you are not activating it immediately. Otherwise use the Activate button to activate the backup/delegate approver immediately.</description>
    <inlineHelpText>Please enter an effective date only if you are not activating it immediately. Otherwise use the Activate button on the next screen to Activate Backup immediately.</inlineHelpText>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Backup_Approver__c/fields/Apttus_Approval__Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Expiration_Date__c</fullName>
    <description>Please enter an expiration date only if you need the system to expire it automatically at a future date. Otherwise use the Deactivate button to cancel the backup/delegate immediately.</description>
    <inlineHelpText>Please enter an expiration date only if you need the system to expire it automatically at a future date. Otherwise use the Deactivate button on the next screen to cancel the backup immediately</inlineHelpText>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Backup_Approver__c/fields/Apttus_Approval__IsDelegate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__IsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If unchecked, requests assigned to the current user get assigned to the backup instead.  When checked, requests assigned to the current user remain assigned to them but their delegates are notified and can take action on the requests as well.</description>
    <inlineHelpText>Indicates that the this entry is for delegate user.</inlineHelpText>
    <label>Is Delegate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Approval_Matrix__c/Custom_Approval_Matrix__c.object-meta.xml
<CustomObject>
    <description>Stores the criteria for various types of approvals for CLM, CPQ and Knowledge articles workflows</description>
    <label>Custom Approval Matrix</label>
    <nameField>
        <label>Custom Approval Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Approval Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Approval_Matrix__c/fields/Approval_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Approval_Hierarchy__c</fullName>
    <description>This lookup field is used to reference Approval Hierarchy where Approval Hierarchy Type is not equal to CPQ Sales or CLM Sales.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Hierarchy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Approval_Hierarchy__c.Approval_Hierarchy_Type__c</field>
            <operation>notEqual</operation>
            <value>CPQ Sales Hierarchy</value>
        </filterItems>
        <filterItems>
            <field>Approval_Hierarchy__c.Approval_Hierarchy_Type__c</field>
            <operation>notEqual</operation>
            <value>CLM Sales Hierarchy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Approval_Hierarchy__c</referenceTo>
    <relationshipLabel>Custom Approval Matrix</relationshipLabel>
    <relationshipName>Custom_Approval_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Approval_Matrix__c/fields/Approval_Hierarchy_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Hierarchy_Type__c</fullName>
    <description>DCP-39486 : Represents the Type of Approval Hierarchy</description>
    <label>Approval Hierarchy Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record Owner</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestApttusBackupApprovers.cls
/**
*    @author Govind Dubey
*    @date   5th Oct 2018
*    @description  Test class for ApttusBackupApprovers
*    Modification Log:
*    -----------------------------------------------------------------------------------------------------------------------------------
*             Developer                      Date                Description
*    -----------------------------------------------------------------------------------------------------------------------------------
*       Govind Dubey                   5th Oct 2018             Original method 
*       Satya Swain                    20 Feb 2020              Added testCheckRecordCreationForSalesOpsUser for INC0220493
*       Roopal Verma                   03 Apr 2020              Added static strings for sonarqube fix
*       Rishab Wali                    07 July 2020             Updated methods to remove circular dependency.
*       Raja Siva Krishna              22 Sept 2020             DCP-40107 Updated data to get code coverage 
*/
@isTest(SeeAllData=false isParallel=false)
public class TestApttusBackupApprovers {
    
	public static final String PROFILE_SALES_USER = 'Sales User';                //SonarQube Fix
    public static final String PROFILE_SYS_ADMIN = 'System Administrator';
    public static final String PROFILE_COMMERCIAL_OPS_QUOTING_USER = 'Commercial Ops Quoting User';
	
    /**
    * @Author Govind Dubey
    * @description setup method for BackupApprovers
    **/
    @testSetup
    static void setupData()
    { 
        
        List<Approval_Hierarchy__c> lstApprovalHierarchy = new List<Approval_Hierarchy__c>();
        
        Approval_Hierarchy__c objDiscountApprovalHeirarchy = TestDataProposal.initApprovalHierarchy('CPQ_Custom_Hierarchy');
        lstApprovalHierarchy.add(objDiscountApprovalHeirarchy);

        Approval_Hierarchy__c objDiscountApprovalHeirarchy1 = TestDataProposal.initApprovalHierarchy('CPQ_Sales_Hierarchy');
        objDiscountApprovalHeirarchy1.Approver_Level_6__c=null;
        lstApprovalHierarchy.add(objDiscountApprovalHeirarchy1);

        insert lstApprovalHierarchy;
        
        List<Custom_Approval_Matrix__c> lstMatrix = new List<Custom_Approval_Matrix__c>();
        
        Custom_Approval_Matrix__c discountApprovalMatrix = TestDataProposal.initApprovalMatrixForDiscount('CPQ Discount', 2000, 20, '2');
        lstMatrix.add(discountApprovalMatrix);
        
        insert lstMatrix;
    }
    
    /**
    * @Author Govind Dubey
    * @description Test method for BackupApprovers
    **/
    
    @isTest
    static void testBackupApprovers(){
        User objRepUser = TestDataUser.findUserInProfile(PROFILE_SALES_USER), 
            objCurrentUser = TestDataUser.findUserInProfile(PROFILE_SYS_ADMIN,new Set<Id>{UserInfo.getUserId()}),
            objOpsUser = TestDataUser.findUserInProfile(PROFILE_COMMERCIAL_OPS_QUOTING_USER);
        objOpsUser.DelegatedApproverId = objRepUser.Id;
        objCurrentUser.DelegatedApproverId = objRepUser.Id;
        objRepUser.DelegatedApproverId = UserInfo.getUserId(); //Update to remove circular dependency.
        update new List<User>{objRepUser,objCurrentUser,objOpsUser};
            
        String strEffectiveDateError;
        String strExpirationDateError;
        
        Test.startTest();
        system.runAs(objCurrentUser){
            Apttus_Approval__Backup_Approver__c objBackupApprover2 = TestDataProposal.initBackupApprover(objRepUser,objOpsUser);
            insert objBackupApprover2;
            
            Apttus_Approval__Backup_Approver__c objBackupApprover = TestDataProposal.initBackupApprover(objRepUser,objCurrentUser);
            insert objBackupApprover;
            system.assert(objBackupApprover.Id!=null);
            
            objBackupApprover.Apttus_Approval__Backup_User__c = objOpsUser.Id;
            objBackupApprover.Apttus_Approval__Effective_Date__c = system.today()+2;
            try{
                update objBackupApprover;
            }catch(Exception e){
                strEffectiveDateError = e.getMessage();
            }
            
            objBackupApprover.Apttus_Approval__Expiration_Date__c = system.today()+4;
            try{
                update objBackupApprover;
            }catch(Exception e){
                strExpirationDateError = e.getMessage();
            }
        }
        Test.stopTest();
        //system.assert(strEffectiveDateError.contains(Label.UI_Text_Effective_Date_Modification_Error));
        //system.assert(strExpirationDateError.contains(Label.UI_Text_Expiration_Date_Modification_Error));
    }
    
    /**
    * @Author Govind Dubey
    * @description Test method for BackupApprovers
    **/
    
    @isTest
    static void testBackupApproversWrongBackup(){
        User objRepUser = TestDataUser.findUserInProfile(PROFILE_SALES_USER), 
        objAdminUser = TestDataUser.findUserInProfile(PROFILE_SYS_ADMIN,new Set<Id>{UserInfo.getUserId()}),
        objOpsUser = TestDataUser.findUserInProfile(PROFILE_COMMERCIAL_OPS_QUOTING_USER);
        
        objOpsUser.DelegatedApproverId = objRepUser.Id;
        objAdminUser.DelegatedApproverId = objRepUser.Id;
        objRepUser.DelegatedApproverId = UserInfo.getUserId(); //Update to remove circular dependency.
        update new List<User>{objRepUser,objAdminUser,objOpsUser};
            
        String strCurrentUserError;
        String strBackupApproverError;
        String strDelegationApproverError;
        User u = [Select id, name, email from User where id=: UserInfo.getUserId()];
        
        Test.startTest();
        Apttus_Approval__Backup_Approver__c objBackupApprover = TestDataProposal.initBackupApprover(objRepUser,objAdminUser);
        try{
            insert objBackupApprover;
        }catch(Exception e){
            strCurrentUserError = e.getMessage();
        }
        
        Apttus_Approval__Backup_Approver__c objBackupApprover2 = TestDataProposal.initBackupApprover(objRepUser,u);
        try{
            insert objBackupApprover2;
        }catch(Exception e){
            strBackupApproverError = Label.UI_Text_Backup_Approver_Error;
        }
        
        Apttus_Approval__Backup_Approver__c objBackupApprover3 = TestDataProposal.initBackupApprover(objRepUser,u);
        objBackupApprover3.Apttus_Approval__Backup_User__c = null;
        objBackupApprover3.Apttus_Approval__IsDelegate__c = true;
        objBackupApprover3.Apttus_Approval__DelegateUserIds__c = objRepUser.Id;
        objBackupApprover3.Apttus_Approval__DelegateUserIds__c += ','+objOpsUser.Id;
        try{
            insert objBackupApprover3;
        }catch(Exception e){
            strDelegationApproverError = Label.UI_Text_Backup_Approver_Error;
        }
        
          Approval_Hierarchy__c objAH = [SELECT Id, Approver_Level_2__c FROM Approval_Hierarchy__c WHERE Approval_Hierarchy_Type__c = 'CPQ_Custom_Hierarchy'];
          objAH.Approver_Level_2__c = objRepUser.Id;
          update objAH;
        
        Apttus_Approval__Backup_Approver__c objBackupApprover4 = TestDataProposal.initBackupApprover(objRepUser,u);
        objBackupApprover4.Apttus_Approval__Backup_User__c = null;
        objBackupApprover4.Apttus_Approval__IsDelegate__c = true;
        objBackupApprover4.Apttus_Approval__DelegateUserIds__c = objRepUser.Id;
        try{
            insert objBackupApprover4;
            system.assert(objBackupApprover4.Id!=null);
        }catch(Exception e){
            strDelegationApproverError = Label.UI_Text_Backup_Approver_Error;
        }
        Test.stopTest();
        if(String.isNotBlank(strDelegationApproverError) && strDelegationApproverError != null)
            system.assert(strDelegationApproverError.contains(Label.UI_Text_Backup_Approver_Error));
        if(String.isNotBlank(strBackupApproverError) && strBackupApproverError != null)
            system.assert(strBackupApproverError.contains(Label.UI_Text_Backup_Approver_Error));
    }
    @isTest
    static void testCheckRecordCreationForSalesOpsUser(){
        User objRepUser = TestDataUser.findUserInProfile(PROFILE_SALES_USER), 
        objAdminUser = TestDataUser.findUserInProfile(PROFILE_SYS_ADMIN,new Set<Id>{UserInfo.getUserId()}),
        objOpsUser = TestDataUser.findUserInProfile(PROFILE_COMMERCIAL_OPS_QUOTING_USER);
        String strValidationErrorMessages;
        
        objOpsUser.DelegatedApproverId = objRepUser.Id;
        objAdminUser.DelegatedApproverId = objRepUser.Id;
        objRepUser.DelegatedApproverId = UserInfo.getUserId(); //Update to remove circular dependency.
        update new List<User>{objRepUser,objAdminUser,objOpsUser};

        List<Profile> lstProfile = [Select Id from Profile];
        Profiles.Constructor obj=new Profiles.Constructor();
        obj.construct(lstProfile);

        Profiles.getAdminProfileId();
        Profiles.getAllSalesProfileIds();

        Test.startTest();
        System.runAs(objOpsUser){
            // to test that Commercial Ops Quoting User User can create backup record for any other user
            Apttus_Approval__Backup_Approver__c objBackupApprover = TestDataProposal.initBackupApprover(objRepUser,objAdminUser);
            try{
                insert objBackupApprover;
                objBackupApprover.Apttus_Approval__Backup_User__c = objOpsUser.Id;
                update objBackupApprover;
            }
            catch(Exception e){
                strValidationErrorMessages = e.getMessage();
            }
        }
        Test.stopTest();
        List<Apttus_Approval__Backup_Approver__c> lstBackupApprover2 = [Select Id from Apttus_Approval__Backup_Approver__c];
        System.assertEquals(1, lstBackupApprover2.size());
        System.assertEquals(true, String.isBlank(strValidationErrorMessages));
    }   
}