force-app/main/default/objects/Apttus__Agreement_Clause__c/Apttus__Agreement_Clause__c.object-meta.xml
<CustomObject>
    <description>Represents a clause associated with an agreement</description>
    <label>Agreement Clause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__Agreement_Clause__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Field to store the Approval status of the clause</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__Agreement_Clause__c/fields/Apttus__Action__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inserted</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Original</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__Agreement_Clause__c/fields/Apttus__Clause__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Clause__c</fullName>
    <label>Clause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__Agreement_Clause__c/fields/Apttus__PrevText__c.field-meta.xml
<CustomField>
    <fullName>Apttus__PrevText__c</fullName>
    <description>The clause previous text</description>
    <label>Previous Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus__Agreement_Clause__c/fields/Apttus__Text__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Text__c</fullName>
    <description>The clause text</description>
    <label>Text</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ApttusAgreementClauseSelectors.cls
/**
 *    @author Prabhsimran Singh
 *    @date   4-March-2020
 *    @description    Class to get the Agreement Clause records based on different conditions 
 *    Modification Log:
 *   ---------------------------------------------------------------------------------------------------------------------------
 *    Developer                      Date                Description
 *    Prabhsimran Singh             3/4/2020             Added method as part of DCP-35369
 
 *    --------------------------------------------------------------------------------------------------------------------------
 */ 
public class ApttusAgreementClauseSelectors extends ilib_SObjectSelector{ 
/**
    *  @author Prabhsimran 
    *  @description  
    *  @return SObjectType The Schema.SObjectType of the Agreement Clause
    **/
    public Schema.SObjectType getSObjectType()
    {
       return Apttus__Agreement_Clause__c.sObjectType;
    }
    /**
     *  @author Prabhsimran
     *  @description Retrieve list of fields for Agreement Clause sObject 
     *  @return sObjectFieldList list of Schema.SObjectField
     **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
		
            Apttus__Agreement_Clause__c.id,
            Apttus__Agreement_Clause__c.Apttus__Clause__c,
            Apttus__Agreement_Clause__c.Apttus__Action__c,
            Apttus__Agreement_Clause__c.Apttus__PrevText__c,
            Apttus__Agreement_Clause__c.Apttus__Text__c,
            Apttus__Agreement_Clause__c.Approval_Status__c
        };
    }    
    /**
     *  @author Prabhsimran
     *  @description fetch Agreement Clauses for the Agreement Ids passed in the argument
     *  @param idSet set of agreement ids
     *  @return list of clause records
     **/
    public List<Apttus__Agreement_Clause__c> selectByAgreementId(Set<Id> setAgreementId) 
    {
        return (List<Apttus__Agreement_Clause__c>) Database.query(
                                newQueryFactory()                                
                                .setCondition('Apttus__Agreement__c IN: setAgreementId')
                                .toSOQL()
      );
    }
}