force-app/main/default/objects/ContentVersion/fields/Document_Type_fileupload__c.field-meta.xml
<CustomField>
    <fullName>Document_Type_fileupload__c</fullName>
    <description>DCP-43185:created new field in content version</description>
    <label>Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Field to store Product Group.</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AmpliSeq Library Prep</fullName>
            </value>
            <value>
                <fullName>Archer Targeted RNA</fullName>
            </value>
            <value>
                <fullName>Array-Based Analysis</fullName>
            </value>
            <value>
                <fullName>Array Services - ILS</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2.x</fullName>
            </value>
            <value>
                <fullName>AutoLoader Accessories</fullName>
            </value>
            <value>
                <fullName>AutoLoader Service Contract</fullName>
            </value>
            <value>
                <fullName>Automation Software DX</fullName>
            </value>
            <value>
                <fullName>Automation Software RUO</fullName>
            </value>
            <value>
                <fullName>BAR Service Contract</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Storage</fullName>
            </value>
            <value>
                <fullName>Basespace Cloud Storage + Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Subscriptions</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cohort Analyzer</fullName>
            </value>
            <value>
                <fullName>BaseSpace Correlation Engine</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Accessory</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Platform</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Qualifications</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Software</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite System</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Upgrades</fullName>
            </value>
            <value>
                <fullName>BaseSpace Professional Service</fullName>
            </value>
            <value>
                <fullName>BeadXpress Service Contract</fullName>
            </value>
            <value>
                <fullName>Beadxpress System (220V)</fullName>
            </value>
            <value>
                <fullName>Billable Service</fullName>
            </value>
            <value>
                <fullName>Billable Service Sequencing</fullName>
            </value>
            <value>
                <fullName>BioRad System</fullName>
            </value>
            <value>
                <fullName>BlueGnome Accessory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Latest_Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Latest_Completion_Date_Time__c</fullName>
    <description>DCP-39890: Created to identify the latest WO completed date.</description>
    <label>Latest Completion Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product in which specialization would be required to service the work order. Calculated from installed product by OptiMax pre-calculation engine</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/SVMXC__Service_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. In ServiceMax, service orders can be used to manage the entire service delivery process, from creating estimates and quotations, to requesting and receiving parts, to recording usage/consumption, to closure and analysis.</description>
    <label>Work Detail</label>
    <nameField>
        <displayFormat>WL-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Activity_Type__c</fullName>
    <description>Indicates the type of activity performed. Usually applicable for labor line types.</description>
    <inlineHelpText>Indicates the type of activity performed. Usually applicable for labor line types.</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Work_Order_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Calibration</fullName>
            </value>
            <value>
                <fullName>Cleanup</fullName>
            </value>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Customer Readiness</fullName>
            </value>
            <value>
                <fullName>Customer Service Review</fullName>
            </value>
            <value>
                <fullName>Dedicated Onsite Activities</fullName>
            </value>
            <value>
                <fullName>De-Installation</fullName>
            </value>
            <value>
                <fullName>Depot Service</fullName>
            </value>
            <value>
                <fullName>Field Compliance Review</fullName>
            </value>
            <value>
                <fullName>Illumina Review</fullName>
            </value>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>IQ/OQ</fullName>
            </value>
            <value>
                <fullName>IT Consult</fullName>
            </value>
            <value>
                <fullName>Letter of Acceptance accepted</fullName>
            </value>
            <value>
                <fullName>OQ</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>PQ Training</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Qualification Service Review</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Remote Support</fullName>
            </value>
            <value>
                <fullName>Repair/Troubleshooting</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Sales Support Activity</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
                <default>true</default>
                <label>Service</label>
            </value>
            <value>
                <fullName>System Health Check</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Line_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Line_Status__c</fullName>
    <description>Service Order Line Status.</description>
    <inlineHelpText>Service Order Line Status.</inlineHelpText>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reversal Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting WO Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product estimated, requested or used. Is a lookup to an existing salesforce product record</description>
    <inlineHelpText>Name of the product estimated, requested or used. Is a lookup to an existing salesforce product record</inlineHelpText>
    <label>Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Service_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Order__c</fullName>
    <description>Service order number. Is a lookup to an existing service order in ServiceMax</description>
    <inlineHelpText>Service order number. Is a lookup to an existing service order in ServiceMax</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DocumentUploadController.cls
/**
*    @author Raja Siva Krishna
*    @date   2020-11-19
*    @description    DCP-43185: DocumentUploadController class
*    Modification Log:
*    ------------------------------------------------------------------------------------ 
*             Developer                      Date                Description
*             Raja Siva Krishna             19/11/2020          Initial Version
*     ------------------------------------------------------------------------------------ 
*                    
*/
public with sharing class DocumentUploadController {
    /* @author Raja Siva Krishna
    *  @description get workdetails activity and uploaded document names and have them in a wrapper
    */
    @AuraEnabled(cacheable=true)
    public static WorkDetailsFieldsWrapper getWrapperFieldDetails(Id recId) {
        try{
            //Boolean boolLatestCompletion = false;
            List<SVMXC__Service_Order_Line__c> lstWd = new WorkDetailsSelector().selectWorkDetailRecords(recId);
            // SVMXC__Service_Order__c woObj = new WorkOrdersSelector().selectWorkOrdertoKnowCompletionDate(recId);
            // if(!string.isEmpty(String.valueof(woObj.Latest_Completion_Date_Time__c))){
            //     boolLatestCompletion = true;
            // }
            WorkDetailsFieldsWrapper objWdWrapper = new WorkDetailsFieldsWrapper();

            if(!lstWd.isEmpty()){
                
                for (SVMXC__Service_Order_Line__c objWd : lstWd)
                {
                    if(objWd.SVMXC__Activity_Type__c != null && !String.isBlank(objWd.SVMXC__Activity_Type__c)  && objWd.SVMXC__Line_Status__c != 'Canceled'){
                        // if(boolLatestCompletion && objWd.CreatedDate>woObj.Latest_Completion_Date_Time__c){
                        //     objWdWrapper.setAcivityType.add(objWd.SVMXC__Activity_Type__c);
                        // }
                        // else if(!boolLatestCompletion){
                        //     objWdWrapper.setAcivityType.add(objWd.SVMXC__Activity_Type__c);
                        // }
                        objWdWrapper.setAcivityType.add(objWd.SVMXC__Activity_Type__c);
                    }
                }
            }
            Map<Id,String> uploadedDocNames = getUploadedDocDetails(recId);
            objWdWrapper.mapContentDocIdtoDocName = uploadedDocNames;
            set<String> setDocNamesContentVersion = new set<String>();
            setDocNamesContentVersion.add('Genric DOC');
            set<Id> setContentDocIds = new set<Id>();
            setContentDocIds = uploadedDocNames.keyset();
            for(Id eachId:setContentDocIds){
                if(uploadedDocNames.containskey(eachId)){
                    setDocNamesContentVersion.add(uploadedDocNames.get(eachId));
                }
            }
            string strJoinDocumentNames = String.join(new List<String>(setDocNamesContentVersion),'\',\'');
            strJoinDocumentNames='\''+strJoinDocumentNames+'\'';
            objWdWrapper.setAllDocumentNames=strJoinDocumentNames;
            objWdWrapper.lstUploadedDocNames=new List<String>(setDocNamesContentVersion);
            String strWoProductId='';
            String strWoProductGrpName='';
            List<SVMXC__Service_Order__c> lstWO = new WorkOrdersSelector().selectWorkOrders(new Set<Id>{recId});
            for(SVMXC__Service_Order__c eachRec:lstWO){
                strWoProductId = eachRec.SVMXC__Product__c;
                strWoProductGrpName = eachRec.SVMXC__Product__r.Product_Group__c;
            }
            objWdWrapper.setProductId=strWoProductId;
            objWdWrapper.setProductGroup=strWoProductGrpName;
            system.debug(objWdWrapper.setAllDocumentNames+objWdWrapper.lstUploadedDocNames+objWdWrapper.setProductId+objWdWrapper.setProductGroup);
            system.debug('Final Wrapper resul::'+objWdWrapper);
            return objWdWrapper;
        }
        catch(Exception e){
            //get exception message
            throw new AuraHandledException(e.getMessage()); 
        }
    }
 
    /**
    *  @author Raja Siva Krishna
    *  @description getting uploaded documents names as a Map 
    **/
    @AuraEnabled(cacheable=true)
    public static map<Id,String> getUploadedDocDetails(Id recId) {
        //TODO [KD comment]: this can be opimzed as for file preview we only need, unless there is some other purpose.
        try{
            List<Id> lstContentDocIds = new List<Id>();
            Map<Id,String> mapIdtoDocname = new Map<Id,String>();
            List<ContentDocumentLink> lstContentDocLinks = new ContentDocumentLinksSelector().selectByMasterDataRequestId(recId);
            for(ContentDocumentLink eachContenDocId:lstContentDocLinks){
                lstContentDocIds.add(eachContenDocId.ContentDocument.Id);
            }
            List<ContentVersion> lstContentVersions = new ContentVersionsSelector().getContentVersionIdsForDocUploadComp(lstContentDocIds);
            for(ContentVersion eachContentVersion:lstContentVersions){
                if(!mapIdtoDocname.containsKey(eachContentVersion.ContentDocumentId)){
                    mapIdtoDocname.put(eachContentVersion.ContentDocumentId, eachContentVersion.Document_Type_fileupload__c);
                }
            }
            return mapIdtoDocname;
        }
        catch(Exception e){
            //get exception message
            throw new AuraHandledException(e.getMessage()); 
        }
    }
   
    /**
    *  @author Raja Siva Krishna
    *  @description Wrapper class for List of fields values
    **/
    public class WorkDetailsFieldsWrapper {
        @AuraEnabled
        public Set<String> setAcivityType {
            get {
                if (setAcivityType == null){
                    setAcivityType = new set<String>();
                }
                return setAcivityType;
            }
            set;
        }
        @AuraEnabled
        public List<String> lstUploadedDocNames {
            get {
                if (lstUploadedDocNames == null){
                    lstUploadedDocNames = new List<String>();
                }
                return lstUploadedDocNames;
            }
            set;
        }
        @AuraEnabled
        public String setAllDocumentNames {
            get {
                if (setAllDocumentNames == null){
                    setAllDocumentNames = '';
                }
                return setAllDocumentNames;
            }
            set;
        }

        @AuraEnabled
        public String setAllDocumentIDs {
            get {
                if (setAllDocumentIDs == null){
                    setAllDocumentIDs = '';
                }
                return setAllDocumentIDs;
            }
            set;
        }
        @AuraEnabled
        public String setProductId {
            get {
                if (setProductId == null){
                    setProductId = '';
                }
                return setProductId;
            }
            set;
        }
        @AuraEnabled
        public String setProductGroup {
            get {
                if (setProductGroup == null){
                    setProductGroup = '';
                }
                return setProductGroup;
            }
            set;
        }
        @AuraEnabled
        public Map<Id,String> mapContentDocIdtoDocName{
            get {
                if (mapContentDocIdtoDocName == null){
                    mapContentDocIdtoDocName = new Map<Id,String>();
                }
                return mapContentDocIdtoDocName;
            }
            set; 
        }
    }
}