force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Lookup to Account for Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Ultimate_Consignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/View_Contract__c.field-meta.xml
<CustomField>
    <fullName>View_Contract__c</fullName>
    <description>This field determines if Sales Contract button should be visible on page layout or not. The decision is based on values from metadata record : Code_Parameter__mdt.Sales_Contract_Access</description>
    <formula>AND( 
				Contains( $CustomMetadata.Code_Parameter__mdt.Sales_Contract_Access.Values_Text__c ,  $Profile.Name ),
				Contains( $CustomMetadata.Code_Parameter__mdt.Sales_Contract_Access.PickListValue__c , Sold_To_Sales_Organization__c ),
				Contains( $CustomMetadata.Code_Parameter__mdt.Sales_Contract_Access.PickListValue__c , TEXT( Apttus_Proposal__Approval_Stage__c ) )
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>View Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <businessOwnerUser>gis@illumina.com</businessOwnerUser>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores Work Order reference used for Break-Fix Quoting</description>
    <inlineHelpText>Stores Work Order reference used for Break-Fix Quoting</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Status__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Status__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Acceptance_Forecast_in_Current_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Acceptance_Forecast_in_Current_Quarter__c</fullName>
    <description>Forecast for Current Quarter</description>
    <label>Acceptance Forecast in Current Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0% - Instrument DOA</fullName>
            </value>
            <value>
                <fullName>0% Out - Not Current Quarter</fullName>
            </value>
            <value>
                <fullName>30% Out - Longshot</fullName>
            </value>
            <value>
                <fullName>60% Out - Upside</fullName>
            </value>
            <value>
                <fullName>70% Committed - Risk</fullName>
            </value>
            <value>
                <fullName>80% Committed - Low Risk</fullName>
            </value>
            <value>
                <fullName>90% Committed - Obtaining LOA</fullName>
            </value>
            <value>
                <fullName>100% Completed - LOA Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Acceptance_Status__c.field-meta.xml
<CustomField>
    <fullName>Acceptance_Status__c</fullName>
    <description>Acceptance Status is updated by Adobe Sign integration when the LOA is signed and attached to the Work Order.</description>
    <label>Acceptance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Generate_Inventory_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Generate_Inventory_Snapshot__c</fullName>
    <description>Checkbox to check whether Inventory Snapshot should generate or not.</description>
    <defaultValue>false</defaultValue>
    <label>Generate Inventory Snapshot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/LOA_Signed_and_Attached__c.field-meta.xml
<CustomField>
    <fullName>LOA_Signed_and_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check whether Letter of Acceptance is signed and Attached to this work order.</description>
    <label>LOA Signed and Attached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Record type for Sales workstream tasks</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/Attachments.cls
/***************************************************************************************************************************************
* NAME   : Attachments
* DESCRIPTION  : Domain class for AttachmentTrigger.
*                    
* @AUTHOR : Ritika Maheshwari
* @DATE   : 06-June-2018  
* 
* MODIFICATION LOG:  
* --------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
* --------------------------------------------------------------------------------------------------------------------------------------
* Ritika               06-June-2018          Initial Version. Added logic to reparent inventory snapshot created for Location, to be associated to Work Order
* Soumya               10-Sept-2018          Added sendEmailLOA() method under after insert to send email when LOA is inserted.
* Sarath Pullanikkatt  07-Jan-2020           Removed Schema.getGlobalDescribe() to retrieve Locations and Agreements object prefixes.
* Roopal Verma         24-March-2021         DCP-45303 - Added logic to craete a task on quote when sales contract is attached on quote.
****************************************************************************************************************************************/ 
public with sharing class Attachments extends ilib_SObjectDomain { 

    public static final String STRING_ATTACHMENT_NAME = 'Letter of Acceptance - signed';
    public static final String STRING_WORK_ORDER_ACCEPTANCE_STATUS = 'Completed';
    public static final String STRING_AGREEMENT_NAME = 'Letter of Acceptance';
    public static final String STRING_AGREEMENT_STATUS_SIGNED = 'Signed';
    public static final String STRING_WORK_ORDER_ACCEPATNCE_FORECAST = '100% Completed - LOA Signed';
    public static final String LOCATION_OBJ_PREFIX = 'a2K'; //SVMXC__Site__c object Prefix
    public static final String ADOBE_AGREEMENT_OBJ_PREFIX = 'a8P'; //echosign_dev1__SIGN_Agreement__c object Prefix
	public static final String PARTS_ORDER_LINE_OBJ_PREFIX = 'a10'; //Parts Order Line object Prefix
    public static final String STRING_MOBILE_LOANER_NAME = 'Sign_Service_Loaner_Agreement__Mobile';//Loaner mobile document name
    public static final String QUOTATION_OBJ_PREFIX = 'a3s'; //Quotation object prefix
    public static final String STRING_TASK_SUBJECT = 'Sales Contract Generated';
    public static final String STRING_TASK_STATUS_OPEN = 'Open';
    public static final String STRING_TASK_PRIORITY_NORMAL = 'Normal';
    public static final String STRING_TASK_TYPE_OTHER = 'Other';
    
   /*
    * Constructor
    */
    public Attachments(List<Attachment> sObjectList)
    {
        super(sObjectList);
    }

    /*
    * Boilerplate which is required for base class instantiation logic
    */
    public class Constructor implements ilib_SObjectDomain.IConstructable
    {
	    /*Param - sobjectList */
        public ilib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Attachments(sObjectList);
        }
    }

    /**
    *  @author Ritika Maheshwari
    *  @description - To be executed, when the attachment is inserted. 
    *               1. Checks if attachment is created for Location. If yes, then fetch its work order and associate the attachment with Work Order
    **/
    public override void onbeforeInsert()
    {
        Map<Id, List<Attachment>> mapParentLocationIdToAttachments = new Map<Id, List<Attachment>>();
        Map<Id, List<Attachment>> mapParentQuotationIdToAttachments = new Map<Id, List<Attachment>>();
        Set<Id> setQuoteIds = new Set<Id>();
        List<Apttus_Proposal__Proposal__c> lstQuoteRecords = new List<Apttus_Proposal__Proposal__c>();

        for(Attachment objAttachment : (List<Attachment>)records){
            if(objAttachment.ParentId != null && String.valueOf(objAttachment.ParentId).startsWith(LOCATION_OBJ_PREFIX)){
                if(!mapParentLocationIdToAttachments.containsKey(objAttachment.ParentId)){
                    mapParentLocationIdToAttachments.put(objAttachment.ParentId, new List<Attachment>());
                }
                mapParentLocationIdToAttachments.get(objAttachment.ParentId).add(objAttachment);
            }

            if(objAttachment.ParentId != null && String.valueOf(objAttachment.ParentId).startsWith(QUOTATION_OBJ_PREFIX)){
                if(!mapParentQuotationIdToAttachments.containsKey(objAttachment.ParentId)){
                    mapParentQuotationIdToAttachments.put(objAttachment.ParentId, new List<Attachment>());
                }
                mapParentQuotationIdToAttachments.get(objAttachment.ParentId).add(objAttachment);
            }
        }
        if(mapParentLocationIdToAttachments.size() > 0 ){
            updateAttachmentParentIdToWorkOrder(mapParentLocationIdToAttachments);
        }

        setQuoteIds = mapParentQuotationIdToAttachments.keySet();
        if(!setQuoteIds.isEmpty()){
            lstQuoteRecords = new ApttusProposalsSelector().selectByQuoteId(setQuoteIds);
        }

        if(!lstQuoteRecords.isEmpty()){
        createTaskForSalesContract(lstQuoteRecords);
        }
    }

    /**
    *  @author Ritika M
    *  @description - This method reparents attachments to Work Order
    *  @parameters : mapParentLocationIdToAttachments - map of Location Ids versus its correspoding attachments which have been inserted
    *  @return : void
    **/
    private static void updateAttachmentParentIdToWorkOrder( Map<Id, List<Attachment>> mapParentLocationIdToAttachments){
        List<SVMXC__Service_Order__c> lstWorkOrderUpdate = new List<SVMXC__Service_Order__c>();
        for(SVMXC__Service_Order__c objWorkOrder : new WorkOrdersSelector().selectCycleCountWorkOrderforSpanshot(mapParentLocationIdToAttachments.keyset() ))
        {           
            for(Attachment objAttachment : mapParentLocationIdToAttachments.get(objWorkOrder.SVMXC__Site__c))    
            {
                objAttachment.ParentId = objWorkOrder.Id;
            }
            objWorkOrder.Generate_Inventory_Snapshot__c = false;
            lstWorkOrderUpdate.add(objWorkOrder);
        }
        
        update lstWorkOrderUpdate;
    }

    /**
    *  @author Roopal Verma
    *  @description - Create task on quote for sales contracts
    *  @parameters : List of quote records
    *  @return : void
    **/
    private static void createTaskForSalesContract(List<Apttus_Proposal__Proposal__c> lstQuoteRecords){
        List<Task> lstTask = new List<Task>();
        for(Apttus_Proposal__Proposal__c objQuote : lstQuoteRecords){
            if(objQuote.View_Contract__c){
                Task objtsk = new Task();
                objtsk.Subject = STRING_TASK_SUBJECT;
                objtsk.Status = STRING_TASK_STATUS_OPEN;
                objtsk.Priority = STRING_TASK_PRIORITY_NORMAL;
                objtsk.WhatId = objQuote.Id;
                objtsk.OwnerId = objQuote.Ultimate_Consignee__r.OwnerId;
                objtsk.Type = STRING_TASK_TYPE_OTHER;
                lstTask.add(objtsk);
            }
        }

        if(lstTask!=null && !lstTask.isEmpty()){
            insert lstTask;
        }
    }
    
    /**
    *  @author Soumya
    *  @description - To be executed, when the Attachment is inserted. 
    *  @parameters : null
    *  @return : void              
    **/
    public override void onAfterInsert()
    {
        Map<id,id> agreementIdToAttachmentIds = new Map<id,id>();
		//DCP-43150
		Attachment mobileloanerattch =new Attachment();
        //Check whether attachment is Letter of Acceptance
        for(Attachment objAttachment : (List<Attachment>)records){
            if(objAttachment.ParentId != null  
                && objAttachment.Name.contains(STRING_ATTACHMENT_NAME) 
                && String.valueOf(objAttachment.ParentId).startsWith(ADOBE_AGREEMENT_OBJ_PREFIX) ){
                agreementIdToAttachmentIds.put(objAttachment.ParentId,objAttachment.id);
            }
			 if(objAttachment.ParentId != null  
                && objAttachment.Name.contains(STRING_MOBILE_LOANER_NAME) 
                && String.valueOf(objAttachment.ParentId).startsWith(PARTS_ORDER_LINE_OBJ_PREFIX) ){
                  //  attachmentIdToPOLIds.put(objAttachment.id,objAttachment.ParentId);
                  if(mobileloanerattch.id == null)
            {
            mobileloanerattch= objAttachment;
            }
                    
        }
        sendEmailWhenLOASigned(agreementIdToAttachmentIds);
		if(mobileloanerattch.id != null)
        {
            ServiceUtilityCollection.createFilesFromAttachment(mobileloanerattch);
        }
       
      }
    }
    /**
    *  @author Soumya
    *  @description - To be executed, when the LOA is signed and attched through Adobe E-Sign (Smart Docs).This sends an email making the LOA as attachment.
    *  @parameters : Null
    *  @return : void             
    **/
    public void sendEmailWhenLOASigned(Map<id,id> agreementIdToAttachmentIds){
        
        if(agreementIdToAttachmentIds.size()>0){
            Map<id,id> workOrderIdToAgreementIds= new Map<id,id>();
            //Stores the agreement corresponding to the Work Orders
            for(echosign_dev1__SIGN_Agreement__c objAgreement :new AgreementsSelector().selectAgreements(agreementIdToAttachmentIds.keyset())){
                //To Check whether agreement is Letter of Acceptance and it is signed
                if(objAgreement.Name.contains(STRING_AGREEMENT_NAME) 
                    && objAgreement.echosign_dev1__Status__c==STRING_AGREEMENT_STATUS_SIGNED){
                    workOrderIdToAgreementIds.put(objAgreement.Work_Order__c,objAgreement.id);
                }

            }
            List<SVMXC__Service_Order__c> lstWorkOrders = new List<SVMXC__Service_Order__c>();
            //To store the work orders that are to be updated
            map<id,List<id>> workOrderIdToAttachmentIds= new map<id,List<id>>();
            //To store the work order record corresponding to the attachment
            for(SVMXC__Service_Order__c objWorkOrder : new WorkOrdersSelector().selectWorkOrdersFromIds(workOrderIdToAgreementIds.keyset())){
                
                workOrderIdToAttachmentIds.put(objWorkOrder.id,new List<id>());
                if(workOrderIdToAgreementIds.containsKey(objWorkOrder.id) && agreementIdToAttachmentIds.containsKey(workOrderIdToAgreementIds.get(objWorkOrder.id))){
                    workOrderIdToAttachmentIds.get(objWorkOrder.id).add(agreementIdToAttachmentIds.get(workOrderIdToAgreementIds.get(objWorkOrder.id)));
                }
                //update fields on work orders
                objWorkOrder.Acceptance_Status__c=STRING_WORK_ORDER_ACCEPTANCE_STATUS;
                objWorkOrder.LOA_Signed_and_Attached__c=true;
                objWorkOrder.Acceptance_Forecast_in_Current_Quarter__c=STRING_WORK_ORDER_ACCEPATNCE_FORECAST;
                lstWorkOrders.add(objWorkOrder);
            }
            try{
                update lstWorkOrders;
            }
            catch(Exception e){
                system.debug('Error:'+e.getMessage());
            }
            //Passing data to send emails
            SendEmailNotification.sendEmailWithAttachments('Letter_of_Acceptance',lstWorkOrders,workOrderIdToAttachmentIds,null,null);
        }
    }
}