force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
    <description>The proposal approval stage</description>
    <inlineHelpText>Current stage of Quote; also reflected in the lifecycle chevrons.</inlineHelpText>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/cs_Apex_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls apex behavior globally or by user/profile</description>
    <label>Apex Settings</label>
</CustomObject>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_All_Validations__c.field-meta.xml
<CustomField>
    <fullName>Bypass_All_Validations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>WARNING: this does what it says it does (for most validation rules, not all). Proceed with caution!</description>
    <inlineHelpText>WARNING: this does what it says it does (for most validation rules, not all). Proceed with caution!</inlineHelpText>
    <label>Bypass All Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchUpdateApprovalReqQuoteToDraftStage.cls
/**
 *  @author Pradeep Landge  
 *  @date  24-June-2024
 *  @description  [DCP-522] | [CPQ]: Data remediation - For In Progress Quotes
 *  Modification Log:
 *  ------------------------------------------------------------------------------------
 *       Developer           Date            Description  
 *       Pradeep Landge      24-June-2024    Initial Version
 *  ------------------------------------------------------------------------------------
 **/
public with sharing class BatchUpdateApprovalReqQuoteToDraftStage implements Database.Batchable < sObject > , Database.Stateful {
    public static String strQuoteStageDraft = 'Draft';
    set < Id > processedQuotes = new set < Id > ();
    private static final String LOG_TITLE = 'BatchUpdateApprovalReqQuoteToDraftStage';
    cs_Apex_Settings__c cs = cs_Apex_Settings__c.getInstance(userInfo.getUserId());


    /**
     *  @author Pradeep Landge
     *  @description Batch start method
     **/
    public Database.QueryLocator start(Database.BatchableContext bc) {

        cs.Bypass_All_Validations__c = true;
        upsert cs cs_Apex_Settings__c.Id;

        String strSoql = 'select id, Apttus_Proposal__Approval_Stage__c from  Apttus_Proposal__Proposal__c where Apttus_Proposal__Approval_Stage__c = \'Approval Required\'';
        return Database.getQueryLocator(strSOQL);
    }

    /**
     *  @author Pradeep Landge
     *  @description Execute method - Update Quote Stage
     **/
    public void execute(Database.BatchableContext bc, list < SObject > scope) {
        ilib_LogEvent.push(LOG_TITLE + '.execute()');
        List < Apttus_Proposal__Proposal__c > lstProposal = new List < Apttus_Proposal__Proposal__c > ();

        for (Apttus_Proposal__Proposal__c objProposal: (List < Apttus_Proposal__Proposal__c > ) scope) {

            objProposal.Apttus_Proposal__Approval_Stage__c = strQuoteStageDraft;
            lstProposal.add(objProposal);
            ilib_LogEvent.info('lstProposal > '+lstProposal);
        }
        if (!lstProposal.isEmpty()) {
            List < Database.SaveResult > srList = Database.update(lstProposal, false);
            ApexExceptions.emitSaveErrors(srList, LOG_TITLE + ' updateQuoteStageDraft ');
            // Iterate through each returned result
            for (Database.SaveResult sr: srList) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    processedQuotes.add(sr.getId());
                }
            }
        }

        ilib_LogEvent.pop();
    }


    /**
     *  @author Pradeep Landge
     *  @description Batch Finish method
     **/
    public void finish(Database.BatchableContext bc) {
        ilib_LogEvent.push(LOG_TITLE + '.finish()');
        cs.Bypass_All_Validations__c = false;
        upsert cs cs_Apex_Settings__c.Id;
        // Call line batch and pass processedQuotes;        
        ilib_LogEvent.info('processedQuotes > '+processedQuotes);
        BatchUpdateToRecalculate updateLines = new BatchUpdateToRecalculate(processedQuotes);
        Database.executeBatch(updateLines, 1);
        ilib_LogEvent.pop();
    }

}