force-app/main/default/objects/Consortium__c/Consortium__c.object-meta.xml
<CustomObject>
    <description>Stores category, species, product, stage, related custom and/or tiered pricing etc. for the Illumina&apos;s consortium</description>
    <label>Consortium</label>
    <nameField>
        <label>Consortium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consortia</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consortium_Account__c/Consortium_Account__c.object-meta.xml
<CustomObject>
    <description>Represents the association between Consortium(s) and Account(s). ILMN Specific Info: This is a junction Object between Consortium and Accounts</description>
    <label>Consortium Account</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Consortium Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consortia Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consortium_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Purpose: Links account record to the Consortia Account
Team Responsible: Product Marketing</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consortia Accounts</relationshipLabel>
    <relationshipName>Consortia_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Consortium_Account__c/fields/Consortia__c.field-meta.xml
<CustomField>
    <fullName>Consortia__c</fullName>
    <description>Purpose: Links consortium record to the Consortia Account
Team Responsible: Product Marketing</description>
    <label>Consortia</label>
    <referenceTo>Consortium__c</referenceTo>
    <relationshipLabel>Consortia Accounts</relationshipLabel>
    <relationshipName>Consortia_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Consortium_Account__c/fields/Is_InActive__c.field-meta.xml
<CustomField>
    <fullName>Is_InActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Purpose: Provide ability for Consortium manager to inactivate an Consortium Account
Team Responsible: Product Marketing</description>
    <label>Is InActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestDataConsortiumAccount.cls
/**
* Consortium Account and associated records
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*    ------------------------------------------------------------------------------------
**/
@isTest

public with sharing class TestDataConsortiumAccount{

    /**
    * 
    *
    * @desc initConsrtuimAccount
    */
    public static Consortium_Account__c initConsortiumAccount(Consortium__c c, Account a, boolean booIsInactive){

        Consortium_Account__c consortiumAcc = new Consortium_Account__c(
            Consortia__c = c.id,
            Account__c = a.id,
            Is_InActive__c = booIsInactive
            );

        return consortiumAcc;
    }
}