force-app/main/default/objects/Account_to_Field_Support__c/Account_to_Field_Support__c.object-meta.xml
<CustomObject>
    <description>Storing Account Roles Like Primary FSE, Secondary FSE and FSM</description>
    <label>Account to Field Support</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account to Field Support</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_to_Field_Support__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>Technician Linked to Customer Solutions record</description>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SVMXC__Service_Group_Members__c.SVMXC__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipLabel>Account to Field Support</relationshipLabel>
    <relationshipName>Account_Users</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/SVMXC__Service_Group_Members__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group.</description>
    <label>Technician/Equipment</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technician/Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an existing salesforce User.</description>
    <inlineHelpText>Lookup to an existing salesforce User.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Field_Support_Salesforce_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Field_Support_Salesforce_User_Id__c</fullName>
    <description>Salesforce Id of the user associated with Field Support Technician.</description>
    <formula>SVMXC__Group_Member__r.SVMXC__Salesforce_User__c</formula>
    <label>Field Support Salesforce User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Initiate_Quoting__c.field-meta.xml
<CustomField>
    <fullName>Initiate_Quoting__c</fullName>
    <businessOwnerUser>gis@illumina.com</businessOwnerUser>
    <description>Auto Populated back end field to used to store the value of initiate Quoting for automation process on work order</description>
    <inlineHelpText>Field used to store the value of initiate Quoting for automation process on work order</inlineHelpText>
    <label>Initiate Quoting</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Blanket Purchase Order Quote</fullName>
            </value>
            <value>
                <fullName>Itemized Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Partner_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Partner_Work_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is checked if WO was created by a CP User / WO is assigned to a CP User / WO was owned by a CP User any time / WO Account associated to VAD territory.</description>
    <label>Partner Work Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Group_Member__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Group_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</description>
    <inlineHelpText>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</inlineHelpText>
    <label>Technician</label>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteValidaton_WOHelper.cls
/**
* @author Shivani Jain
* @date 7th May 2022
*
* @description DCP-54018 Helper Class for Work Order Trigger to run logic related to Quote creation from the Work Order. 
*/ 
public with sharing class QuoteValidaton_WOHelper {

    /*
    *  @AUTHOR: Digvijay Singh
    *  @DESCRIPTION: Work Order Assignment for Quote Creation
    *  @PARAM : List of Sobject
    *  @RETURN:  void
    */
    public static void workOrderAssignmentForQuoteCreation(Map<Id, SObject> oldRecords, List<sObject> records, Id idEstimatesRecordTypeId) {
 
        for(SVMXC__Service_Order__c objWorkOrder : (List<SVMXC__Service_Order__c>)records) {
            
            SVMXC__Service_Order__c objOldWorkOrder = (SVMXC__Service_Order__c)(oldRecords.get(objWorkOrder.Id)); 
            // DCP- 46318
            validateUserForAutomatedQuoteCreation(objWorkOrder,objOldWorkOrder, idEstimatesRecordTypeId);
            // Removed logic to update WO owner to estimate Queue //DCP-45874
        }
    }

    /**
    *   DCP- 46318
    *   @author Adyasha Satapathy
    *   @param Map<Id, SObject> idToOldWorkOrder
    *   @return void
    **/
    public static void validateUserForAutomatedQuoteCreation(SVMXC__Service_Order__c objWorkOrder, SVMXC__Service_Order__c objOldWorkOrder, Id idEstimatesRecordTypeId) {
        ilib_LogEvent.push(WorkOrders.LOG_TITLE + '.validateUserForAutomatedQuoteCreation()');
        Id currentUserId = UserInfo.getUserId();
            
        if(objWorkOrder.RecordTypeId != idEstimatesRecordTypeId || currentUserId == objWorkOrder.OwnerId || Profiles.getAllAdminProfileIds().contains(Userinfo.getProfileId())
            || objWorkOrder.Initiate_Quoting__c == objOldWorkOrder.Initiate_Quoting__c || String.isBlank(objWorkOrder.Initiate_Quoting__c)) {
            ilib_LogEvent.pop();
            return;
        }

        Boolean boolLoggedInUserIsFieldSupport = String.isNotBlank(objWorkOrder.SVMXC__Group_Member__c) && currentUserId.to15().equals(objWorkOrder.Field_Support_Salesforce_User_Id__c);
        ilib_LogEvent.message('boolLoggedInUserIsFieldSupport: '+boolLoggedInUserIsFieldSupport);

        Boolean boolCriteriaPassedForBypass = false;
        Boolean boolLoggedInUserIsAccToFieldSupport = false;
        
        if(objWorkOrder.Partner_Work_Order__c) {
            boolLoggedInUserIsAccToFieldSupport = checkUserSatisfiesCriteria(currentUserId, WorkOrders.mapaccountIdToPFSERoles.get(objWorkOrder.SVMXC__Company__c),new Set<String>{WorkOrders.STRING_LABEL_PRIMARY_FSE, WorkOrders.STRING_LABEL_SECONDARY_FSE, WorkOrders.STRING_LABEL_PRIMARY_FAS, WorkOrders.STRING_LABEL_FSM, WorkOrders.STRING_LABEL_SECONDARY_FAS});
            ilib_LogEvent.message('boolLoggedInUserIsAccToFieldSupport for partner wo: '+boolLoggedInUserIsAccToFieldSupport);
            boolCriteriaPassedForBypass = boolLoggedInUserIsAccToFieldSupport;
        } else {
            boolLoggedInUserIsAccToFieldSupport = checkUserSatisfiesCriteria(currentUserId,WorkOrders.mapaccountIdToPFSERoles.get(objWorkOrder.SVMXC__Company__c),new Set<String>{WorkOrders.STRING_LABEL_FSM});
            ilib_LogEvent.message('boolLoggedInUserIsAccToFieldSupport for non partner wo: '+boolLoggedInUserIsAccToFieldSupport);
            boolCriteriaPassedForBypass = boolLoggedInUserIsFieldSupport || boolLoggedInUserIsAccToFieldSupport;
        }
        if(!boolCriteriaPassedForBypass) {
            objWorkOrder.addError(Label.WorkOrderPreventQuotingValidationErrorMessage);
        }    
        ilib_LogEvent.pop();
    }

    /**
    *   DCP- 46318
    *   @author Adyasha Satapathy
    *   @param Id userId, Map<String,Account_to_Field_Support__c> mapAccToFieldSupport, Set<String> setRoles
    *   @return Boolean
    **/
    public static Boolean checkUserSatisfiesCriteria(Id userId, Map<String,Account_to_Field_Support__c> mapAccToFieldSupport, Set<String> setRoles) {
        Boolean boolLoggedInUserSatisfiesCriteria = false;
        for(String strRole : setRoles) {
            if(mapAccToFieldSupport != NULL && !mapAccToFieldSupport.isEmpty() && mapAccToFieldSupport.get(strRole) != null) {
                Id accountToFieldSupportUserId = String.isNotBlank(mapAccToFieldSupport.get(strRole).User__c) ? mapAccToFieldSupport.get(strRole).User__r.SVMXC__Salesforce_User__c : NULL;
                boolLoggedInUserSatisfiesCriteria = userId == accountToFieldSupportUserId;                
            }
            if(boolLoggedInUserSatisfiesCriteria) break;
        }
        return boolLoggedInUserSatisfiesCriteria;
    }

}