force-app/main/default/objects/Competitive_Complementary_Technology__c/Competitive_Complementary_Technology__c.object-meta.xml
<CustomObject>
    <description>Stores Competitive and Complementary data for an Account</description>
    <label>Competitive &amp; Complementary Technology</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive &amp; Complementary Technologies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitive &amp; Complementary Technology</relationshipLabel>
    <relationshipName>Competitor_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Competitive_Positioning__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Positioning__c</fullName>
    <description>Indicates the Competitive Positioning for this Competitor within this Opportunity. Jira Story #CMCM-4485</description>
    <inlineHelpText>Select the Competitive Positioning for this Opportunity.</inlineHelpText>
    <label>Competitive Positioning</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competitor Slightly Favored</fullName>
            </value>
            <value>
                <fullName>Competitor Strongly Favored</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Illumina Slightly Favored</fullName>
            </value>
            <value>
                <fullName>Illumina Strongly Favored</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/CompetitorName__c.field-meta.xml
<CustomField>
    <fullName>CompetitorName__c</fullName>
    <description>Competitor Name from picklist of CCT_ProductName__mdt CMCM-5648</description>
    <inlineHelpText>Enter Competitor Name</inlineHelpText>
    <label>Competitor Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Dollar_Per_Gb__c.field-meta.xml
<CustomField>
    <fullName>Dollar_Per_Gb__c</fullName>
    <description>This is the cost per Gigabase, typically used for WGS systems, as panels have different sizes.</description>
    <inlineHelpText>Enter cost per Gigabase here (if known).</inlineHelpText>
    <label>$ / Gb</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Is_In_Use__c.field-meta.xml
<CustomField>
    <fullName>Is_In_Use__c</fullName>
    <description>Flag to check is in use</description>
    <inlineHelpText>* Currently in Use: To indicate this technology is currently in use at the customer site
* Future Consideration: To indicate if they are considering future purchase of competitive technology. For what reason(s)? Future use should consider next 1-2 years
* No Longer in Use: To indicate when this technology was previously in use at the customer site.
* Unknown: To catch all for any other scenario we would like to track for awareness that doesn&apos;t fit into any of the other options</inlineHelpText>
    <label>Usage Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Currently in Use</fullName>
            </value>
            <value>
                <fullName>Future Consideration</fullName>
            </value>
            <value>
                <fullName>No longer in Use</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Number_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Units__c</fullName>
    <description>field to store number of units</description>
    <inlineHelpText>Optional: # of operational instruments observed.</inlineHelpText>
    <label>Number Of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the name of the related Opportunity to this CCT record. Jira Story #CMCM-4485</description>
    <inlineHelpText>Select the Opportunity for this Competitor record.</inlineHelpText>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitive &amp; Complementary Technology</relationshipLabel>
    <relationshipName>Competitive_Complementary_Technologies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Primary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Competitor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this Competitor record is the primary competitor for this Opportunity. Jira Story #CMCM-4485</description>
    <inlineHelpText>Checking this checkbox indicates that this Competitor is the primary competitor for this Opportunity.</inlineHelpText>
    <label>Primary Competitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Indicates the Product Category of the Competitor&apos;s product. Controlling field is &apos;Competitor name&apos;. This field control &apos;Product Name&apos;. Managed through LWC. Jira Story # CMCM-4468</description>
    <inlineHelpText>Select the Product Category for this Competitor; Product Category and Competitor Name selected determine the Product Names displayed, when applicable.</inlineHelpText>
    <label>Product Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitive_Complementary_Technology__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>Product Name from picklist of CCT_ProductName__mdt CMCM-5648</description>
    <inlineHelpText>Enter Product Name</inlineHelpText>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataCompetitiveCompTech.cls
/**
*    @author: Kushagra Desai
*    @date:   03-Sept-2019
*    @description:  Data creation class for Competitive_Complementary_Technology__c
*    Modification Log:
*    -----------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Vivek R                       06-Oct-22           Codescan fixes: added comments
*             Gerardo Garcia                30-Jan-24           Add initForOpportunity method CMCM-4485
*             Gerardo Garcia                28-Feb-24           Replace fields to new fields CompetitorName__c and ProductName__c due CCT phase 1
*    ------------------------------------------------------------------------------------ 
*                    
*/
@isTest
 public with sharing class TestDataCompetitiveCompTech {

    /**
     *  @author      : Kushagra Desai
     *  @description : Method to create Data Order through the Id of the account record
     *  @param       : Account
     *  @return      : Competitive_Complementary_Technology__c
    */
    public static Competitive_Complementary_Technology__c getNewCompetitiveCompTech(Account a) {
        Competitive_Complementary_Technology__c cct  = initCompetitiveCompTech(a.Id);
        insert cct;
        return cct;
    }
    /**
     *  @author      : Kushagra Desai
     *  @description : Method to create Data Order through the Id of the account record
     *  @param       : Id
     *  @return      : Competitive_Complementary_Technology__c
    */
	 public static Competitive_Complementary_Technology__c initCompetitiveCompTech(String accId){
        Competitive_Complementary_Technology__c cct =  new Competitive_Complementary_Technology__c();
        cct.Account__c = accId;
        cct.CompetitorName__c = 'GenapSys';
        cct.Product_Category__c = 'Instrument';
        cct.ProductName__c = 'Genius (Benchtop Sequencer)';
        cct.Number_Of_Units__c = 1;
        cct.Is_In_Use__c = 'Unknown';
        cct.RecordTypeId = CompetitiveTechnologySelector.getAccountTypeId();
        return cct;
    }

    /**
     *  @author      : Gerardo Garcia
     *  @description : Creates CCT for opportunity
     *  @param       : opportunityId id for Opportunity_Name__c
     *  @param       : isPrimary Is_Primary_Competitor__c
     *  @return      : Competitive_Complementary_Technology__c
    */
	 public static Competitive_Complementary_Technology__c initForOpportunity(Id opportunityId, Boolean isPrimary){
        Competitive_Complementary_Technology__c cct =  new Competitive_Complementary_Technology__c();
        cct.Opportunity_Name__c = opportunityId;
        cct.CompetitorName__c = 'GenapSys';
        cct.Product_Category__c = 'Instrument';
        cct.ProductName__c = 'Genius (Benchtop Sequencer)';
        cct.Competitive_Positioning__c = 'Competitor Slightly Favored';
        cct.Primary_Competitor__c = isPrimary;
        cct.Dollar_Per_Gb__c = 10;
        cct.RecordTypeId = CompetitiveTechnologySelector.getOpportunityTypeId();
        return cct;
    }
}