force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>Generic object to store comments related to different objects</description>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>DCP-1049
To capture user comments
Manually entered by user</description>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DCP-1049
To associate the comment with work order
Manually selected</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TAPS_Comments.cls
/***************************************************************************************************************************************
* NAME   : TAPS_Comments 
* --------------------------------------------------------------------------------------------------------------------------------------
*/
public without sharing class TAPS_Comments extends TAPS_ComposedBase implements TAPS_IObjectsCustom {

    /*
    * @description: return Object API Name
    * @return: SObjectType 
    */
    public override SObjectType getObjectType()
    {
        return Comment__c.sObjectType;
    }

	/*
    * @description: used to fetch data related to Account 
    * @return: Map<Id, Set<Id>> 
    */	
    public override Map<Id, Set<Id>> mapRecordToAccountsCustom(Set<Id> recordIds)
    {
        List<Comment__c> recordDetails = [SELECT Id, Work_Order__c, Work_Order__r.SVMXC__Company__c FROM Comment__c WHERE Id IN :recordIds];
        return UtilsCollection.getMapOfIdToIds(recordDetails, 'Id', 'Work_Order__r.SVMXC__Company__c');
    }

	/*
    * @description: returns Id related to comment Object
    * @return: Set<Id>
    */
    public override Set<Id> getRecordIdsFromAccountIdsCustom(Set<Id> accountIds)
    {
        List<Comment__c> commentDetails = [SELECT Id FROM Comment__c WHERE Work_Order__r.SVMXC__Company__c IN :accountIds];
        return UtilsCollection.getSetOfIds(commentDetails, 'Id');
    }

	/*
    * @description: used to fetch data related to Account 
    * @return: Map<Id, Set<Id>> 
    */
    public override Set<Id> getRecordIdsFromModifiedRecordIdsCustom(Set<Id> modifiedRecordIds)
    {
        if (modifiedRecordIds.size() == 0) return modifiedRecordIds;

        // modified record IDs could be Work Orders
        if (UtilsCollection.getFirstIdFromSet(modifiedRecordIds).getSobjectType() == SVMXC__Service_Order__c.SObjectType)
        {
            List<Comment__c> recordDetails = [SELECT Id FROM Comment__c WHERE Work_Order__c IN :modifiedRecordIds];
            return UtilsCollection.getSetOfIds(recordDetails, 'Id');
        }

        return modifiedRecordIds;
    }

	/*
    * @description:Returns Object API Name
    * @return: SObjectType
    */
    public override SObjectType getShareObjectType()
    {
        return Comment__Share.sObjectType;
    }

	/*
    * @description:Returns Field API Name 
    * @return: String
    */	
    public override String getShareParentFieldName()
    {
        return 'ParentId';
    }

	/*
    * @description:Create Sharing Record
    * @return: SObject
    */	
    public override SObject createSharingRecord(Id recordId, Id userId)
    {
        Comment__Share share = new Comment__Share(
            UserOrGroupId = userId,
            AccessLevel = 'Read',
            RowCause = Schema.Comment__Share.RowCause.Manual
        );
        share.put(getShareParentFieldName(), recordId);
        return share;
    }

	/*
    * @description: Used to filter territory based on user Id
    * @return: Map<Id, Set<Id>>
    */	
    public override Map<Id, Set<Id>> filterTerritoryIdToUserIds(Map<Id, Set<Id>> territoryIdToUserIds, Map<Id, Set<Id>> accountIdToTerritoryIds, Map<Id, Set<Id>> recordIdToAccountIds)
    {
        // filter by role in territory to only include certain sales roles
        return filterSalesUsersByRoleInTerritory(territoryIdToUserIds);
    }

}