force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>Generic object to store comments related to different objects</description>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>DCP-1049
To capture user comments
Manually entered by user</description>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Perform_Actions_as_Admin__c.field-meta.xml
<CustomField>
    <fullName>Perform_Actions_as_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-49914 This field is used to perform actions by Admin User on Creation of We Chat Comment</description>
    <label>Perform Actions as Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PerformAdminActions_CommentManager.cls
/**
* @author Shivani Jain
* @date 8th April 2022
*
* @description DCP-49914 Class to update Post Chatter field to trigger notifiction for we chat comments
*/
public with sharing class PerformAdminActions_CommentManager implements ilib_AdminOperationLogicInterface {

    private static final String LOG_TITLE = 'PostChatterWeChatCase_CommentManager';

    /*******************************************************************************************************
    * @description DCP-49914 Interface method
    * @param lstCommentIds List<Id>
    */
    public static void doBusinessLogic(List<Id> lstCommentIds) {
        triggerChatterPostOnComment(lstCommentIds);
    }

    /*******************************************************************************************************
    * @description DCP-49914 Logic to update Post Chatter field on Comment
    * @param lstCommentIds list of comment Ids
    */
    private static void triggerChatterPostOnComment(List<Id> lstCommentIds){
        List<Comment__c> lstCommentsToUpdate = new List<Comment__c>();

        for(Id commentId : lstCommentIds){
            Comment__c comment = new Comment__c(Id = commentId);
            comment.Perform_Actions_as_Admin__c = true;
            lstCommentsToUpdate.add(comment);
        }
        if(!lstCommentsToUpdate.isEmpty()) {
            List<Database.SaveResult> srListComments = Database.update(lstCommentsToUpdate, false);
            ApexExceptions.emitSaveErrors(srListComments, LOG_TITLE);
        }
    }
}