force-app/main/default/objects/Apttus_Config2__PriceList__c/Apttus_Config2__PriceList__c.object-meta.xml
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
    <description>The proposal approval stage</description>
    <inlineHelpText>Current stage of Quote; also reflected in the lifecycle chevrons.</inlineHelpText>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related opportunity</description>
    <inlineHelpText>Related parent opportunity under which this Quote is created.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>R00N70000001yUfDEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_QPApprov__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPApprov__Approval_Status__c</fullName>
    <description>The quote approval status</description>
    <inlineHelpText>Approval status of quote submitted for approval.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_Presence__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Presence__c</fullName>
    <description>Indicates if the opportunity has at least a competitor, no competition, or an unknown competitor.  Jira story # CMCM-5875</description>
    <inlineHelpText>If &apos;yes&apos; a C&amp;CT record should be added (use the Competitive Info tab). If there is no competitor or the competitor is unknown, please select the appropriate option.</inlineHelpText>
    <label>Competitor Context Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No Competitor</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestOpportunityQuoteRecall.cls
/**
*    @author Vinay S Reddy
*    @date   2023-12-10
*    @description    CMCM-1036   
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Descriptions
*             Vinay S Reddy                12 Oct 2023           Test class for Quote recall when opportunity stage changes to closed lost or closed abandoned
   ----------------------------------------------------------------------------------- 
*                    
*/
@isTest
public with sharing class TestOpportunityQuoteRecall {

    @isTest
    static void testOppQuote()
    {
       //Opportunity creation
        Account acc = TestDataAccount.getAccount('Test 1');
        String recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.AccountRecordTypeIndirectPartner).getRecordTypeId();
        acc.RecordTypeId = recordtypeid;
        insert acc;

        Opportunity opp = TestDataOpportunity.initOpportunity(acc);
        insert opp;

        Apttus_Config2__PriceList__c priceList = TestDataProposal.initPriceList('AMR-USD-US-01');
        insert priceList;
        String strDraft = 'Draft';
        String strNone = 'None';
        Apttus_Proposal__Proposal__c proposal = TestDataProposal.initProposal(acc.id, opp.id, 'Test Proposal', priceList.id, true, strDraft, strNone);
        insert proposal;
        proposal.Apttus_Proposal__Approval_Stage__c='In Review';
        proposal.Apttus_QPApprov__Approval_Status__c='Pending Approval';
        update proposal;


        Test.startTest();
        Opportunity opp1=[Select Id,StageName,Account.Name from  Opportunity where Account.Name='Test 1'];
        opp1.StageName = 'Closed Lost';
        opp1.Competitor_Presence__c = 'No Competitor'; //Added by SB
        update opp1; 
        system.debug('Opportunity record is '+opp1);
        Test.stopTest();

        Apttus_Proposal__Proposal__c prop=[Select ID,Apttus_Proposal__Approval_Stage__c,Apttus_QPApprov__Approval_Status__c From Apttus_Proposal__Proposal__c Where Apttus_Proposal__Opportunity__c = :opp1.Id]; 
	     System.assertEquals('Cancelled',prop.Apttus_QPApprov__Approval_Status__c,'Proposal is not recalled'); 
        System.assertEquals('Draft',prop.Apttus_Proposal__Approval_Stage__c,'Proposal is not recalled');

}
    @isTest static void testOppQuote1(){
        boolean check=PEQuoteOpportunityTriggerHandler.methodToCheckQuotetoRecall('Pending',true);
        system.assertEquals(false,check,'Else block not executed');
}
}