force-app/main/default/objects/Apttus_Config2__PriceList__c/Apttus_Config2__PriceList__c.object-meta.xml
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related opportunity</description>
    <inlineHelpText>Related parent opportunity under which this Quote is created.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>R00N70000001yUfDEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_QPConfig__PriceListId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__PriceListId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated price list</description>
    <inlineHelpText>The Illumina price list applicable to this transaction.</inlineHelpText>
    <label>Price List</label>
    <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
    <relationshipLabel>Quotes/Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Direct_Sale_to_Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sale_to_Ultimate_Consignee__c</fullName>
    <description>Formula field to populate "Direct sales to ultimate consignee"</description>
    <inlineHelpText>Field is applicable to Indirect transactions</inlineHelpText>
    <formula>Apttus_Proposal__Opportunity__r.Direct_Sale_to_Ultimate_Consignee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Direct Sale to Ultimate Consignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <description>Opportunity Record Type name</description>
    <formula>Apttus_Proposal__Opportunity__r.RecordType.Name</formula>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/SAP_Quote__c.field-meta.xml
<CustomField>
    <fullName>SAP_Quote__c</fullName>
    <description>DCP-1058 - Represents SAP Quote Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SAP quote number that is associated with the APTTUS quote; used for order conversion.</inlineHelpText>
    <label>SAP Quote #</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Sold_To_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Account_Name__c</fullName>
    <description>Sold to Account Name</description>
    <formula>Apttus_Proposal__Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sold To Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/Apttus_Proposal__Proposal_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with a quote/proposal</description>
    <label>Proposal Line Item</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Apttus_QPConfig__PriceListId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__PriceListId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the price list associated with the product or service</description>
    <label>Price List</label>
    <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
    <relationshipLabel>Proposal Line Items</relationshipLabel>
    <relationshipName>ProposalLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Apttus_QPConfig__Quantity2__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__Quantity2__c</fullName>
    <description>The product or service quantity</description>
    <label>Quantity (2)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Customer_Historical_Discount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Historical_Discount__c</fullName>
    <businessOwnerGroup>Sales_Schema_Owners</businessOwnerGroup>
    <description>Customer Historical Discount provided by the Discount Recommendation grid</description>
    <inlineHelpText>Customer Historical Discount provided by the Discount Recommendation grid</inlineHelpText>
    <label>Customer Historical Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Customer_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Customer_Net_Price__c</fullName>
    <description>Stores Customer Net Price value for the line item</description>
    <label>Customer Net Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Derived_From_Name__c.field-meta.xml
<CustomField>
    <fullName>Derived_From_Name__c</fullName>
    <description>Displays the line item name from which the proposal line item is derived</description>
    <formula>Apttus_QPConfig__DerivedFromId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Derived From Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Distributor_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Rebate__c</fullName>
    <description>Created to calculate the Distributor Rebate as a part of the Story 13308</description>
    <inlineHelpText>Customer Net Price - Distributor Net Price</inlineHelpText>
    <label>Distributor Commission</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Distributor_Specific_Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Specific_Discount_Percentage__c</fullName>
    <description>Distributor based discount value in terms of percentage</description>
    <label>Distributor Specific Discount %</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>Stores the list price of the line item</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Material_Class__c.field-meta.xml
<CustomField>
    <fullName>Material_Class__c</fullName>
    <description>Stores the material class value of the line item from which proposal line item is derived</description>
    <formula>if(Apttus_QPConfig__OptionId__c!=null,TEXT( Apttus_QPConfig__OptionId__r.Material_Class__c ),TEXT(Apttus_Proposal__Product__r.Material_Class__c))</formula>
    <label>Material Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>Stores the material number value of the product in the line item</description>
    <formula>Apttus_Proposal__Product__r.ProductCode</formula>
    <label>Material Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Term_Months__c</fullName>
    <description>Stores term value in months and used in output template</description>
    <formula>Apttus_QPConfig__DerivedFromId__r.Term_Months__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term(Months)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Total_Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Percentage__c</fullName>
    <description>Stores total discount percentage value for the given line item</description>
    <label>Total Discount %</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Historical_Discount__c/Customer_Historical_Discount__c.object-meta.xml
<CustomObject>
    <description>Stores historical discount for an account per SKU / MG1. Weighted average at the NGN level.</description>
    <label>Customer Historical Discount</label>
    <nameField>
        <displayFormat>CHD-{0000000}</displayFormat>
        <label>Customer Historical Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Historical Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Historical_Discount__c/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

force-app/main/default/classes/ViewSalesMarginDataController.cls
/**
 * @author Pradeep Landge
 * @date   26-Sept-2024
 * @description    DGP-497 : This class will be used for getting the Sales Margin Data.
 * Test class for 75%+ coverage : TestViewSalesMarginDataController [85%]
 * Modification Log:
 *  ------------------------------------------------------------------------------------
 *   Developer                Date              Description
 *   Sai P                 06-Nov-2024          DGP-502 Q1'25: Phase 2 - Ability to view Margin Analysis screen in sandbox
 *  -----------------------------------------------------------------------------------
 */
public with sharing class ViewSalesMarginDataController extends ilib_RestReceiver {
    private static final String LOG_TITLE = 'ViewSalesMarginDataController';
    private static final String SL_VIEW_MARGINDATA = 'SL_View_MarginData';
    private static final String NET_MARGIN = 'Net Margin';
    private static final String MARGIN_LIST_PRICE = 'Margin List Price';
    private static final String PROPOSED_PRICE = 'Proposed Price';
    private static final String GETCOGS = 'GetCOGS';
    private static final String ERROR = 'Error-';
    private static final String SUCCESS = 'Success';
    private static final String FALSE_VAL = 'FALSE';
    private static final Integer HTTP_POST_SUCCESS_CODE = 201;
    private static final Integer HTTP_SUCCESS_CODE = 200;
    private static final String SAPSUCCESS = 'S';

    /*
    *  @author       : Pradeep Landge
    *  @description  : Checks if the current user has both edit access to a specific Quote record and 
                        the custom permission 'SL_View_MarginData'.
    *  @param        : Id quoteId
    *  @return       : Boolean True if the user has both edit access and 
                        the required custom permission, false otherwise.
    */
    @AuraEnabled
    public static Map<String, Boolean> hasUserPermissionAndAccess(Id quoteId) {
        //DGP-502 added changes
        Map<String, Boolean> accessCheck = new Map<String, Boolean>();
        accessCheck.put('hasAccess', false);
        accessCheck.put('hasPermission', false);
        accessCheck.put('isSandbox', false);
        accessCheck.put('isSubstituteUser', false);
        accessCheck.put('hasGroupAccess', false);
        try {
            UserRecordAccess useraccess = [
                SELECT RecordId, HasReadAccess
                FROM UserRecordAccess
                WHERE UserId = :UserInfo.getUserId() AND RecordId = :quoteId
                LIMIT 1
            ];

            // Check if the user has access to the Quote record & 'SL_View_MarginData' custom permission
            accessCheck.put('hasAccess', useraccess.HasReadAccess);
            accessCheck.put('hasPermission', FeatureManagement.checkPermission(SL_VIEW_MARGINDATA));
            Organization org = [SELECT Id, isSandbox FROM Organization LIMIT 1];
            List<AuthSession> authSession = [
                SELECT Id
                FROM AuthSession
                WHERE UsersId = :UserInfo.getUserId() AND SessionType = 'SubstituteUser'
            ];
            Boolean hasLoggedInUser = !authSession.isEmpty();
            accessCheck.put('isSandbox', org.IsSandbox);
            accessCheck.put('isSubstituteUser', hasLoggedInUser);
            if (org.IsSandbox) {
                List<GroupMember> checkMarginDataGroup = [
                    SELECT UserOrGroupId
                    FROM GroupMember
                    WHERE Group.DeveloperName = 'View_Margin_Data_in_Sandbox' AND UserOrGroupId = :UserInfo.getUserId()
                ];
                if (!checkMarginDataGroup.isEmpty()) {
                    accessCheck.put('hasGroupAccess', true);
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return accessCheck;
    }

    /*
    *  @author       : Pradeep Landge
    *  @description  : Retrieves margin analysis data for a specific Quote, 
                        including Quote details and its related line items.
    *  @param        : Id  quoteId
    *  @return       : MarginAnalysisData details
    */
    @AuraEnabled
    public static MarginAnalysisData getMarginAnalysis(Id quoteId) {
        try {
            List<Apttus_Proposal__Proposal_Line_Item__c> items = new ApttusProposalLineItemsSelector()
                .selectByQuoteId(new Set<Id>{ quoteId });
            if (items != null && !items.isEmpty()) {
                ResponseWrapper responseFromTM1 = new TargetMarginCalculationService().getTargetMarginFromSnap(items);
                ResponseWrapper responseFromSAP = new ViewSalesMarginDataController().getCOGSForQuote(items);
                new ViewSalesMarginDataController()
                    .finalizeLogs(responseFromTM1.log, responseFromTM1.integrationStatus, responseFromTM1.message, quoteId);
                new ViewSalesMarginDataController()
                    .finalizeLogs(responseFromSAP.log, responseFromSAP.integrationStatus, responseFromSAP.message, quoteId);
                return new MarginAnalysisData(items, responseFromTM1.resultMap, responseFromSAP.resultMap);
            } else {
                return null;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /*
     *  @author       : Akash Kumar
     *  @description  : Since two callouts are involved this method takes care of inserting the logs together after 
                        both the callouts to avoid uncommitted work pending error.
     *  @param        : Interface log, Http response from API, Quote Id
     *  @return       : void
     */
    private void finalizeLogs(ilib_LogInterface.LogDetails log, String integrationStatus, String message, String quoteId) {
        if (integrationStatus == SUCCESS)
            ilib_LogInterface.finalizeLog(log, ilib_LogInterface.RESULT_SUCCESS, message, quoteId);
        else
            ilib_LogInterface.finalizeLog(log, ilib_LogInterface.RESULT_FAIL, message, quoteId);
    }

    /*
     *  @author       : Akash Kumar
     *  @description  : Performs the lineLevel analysis for the given Quote.
     *  @param        : List<QuoteLineItemData> lineItems
     *  @return       : LineAnalysisData details
     */
    public static List<LineLevelWrapper> lineLevelAnalysis(List<QuoteLineItemData> lineItems) {
        List<LineLevelWrapper> productLines = new List<LineLevelWrapper>();
        Map<String, List<Double>> lineToMargins = new Map<String, List<Double>>();
        if (lineItems != null && !lineItems.isEmpty()) {
            for (QuoteLineItemData item : lineItems) {
                if (!lineToMargins.containsKey(item.productLine)) {
                    lineToMargins.put(
                        item.productLine,
                        new List<Double>{
                            item.marginAtQuotePrice != null ? item.marginAtQuotePrice : 0,
                            item.quoteExtendedPrice != null ? item.quoteExtendedPrice : 0,
                            item.standardMarginTarget
                        }
                    );
                } else {
                    lineToMargins.put(
                        item.productLine,
                        new List<Double>{
                            lineToMargins.get(item.productLine)[0] + (item.marginAtQuotePrice != null ? item.marginAtQuotePrice : 0),
                            lineToMargins.get(item.productLine)[1] + (item.quoteExtendedPrice != null ? item.quoteExtendedPrice : 0),
                            lineToMargins.get(item.productLine)[2]
                        }
                    );
                }
            }
        }

        for (String line : lineToMargins?.keySet()) {
            productLines.add(
                new LineLevelWrapper(
                    line,
                    lineToMargins.get(line)[1] == 0
                        ? null
                        : (lineToMargins.get(line)[0] / lineToMargins.get(line)[1]) != 0
                              ? lineToMargins.get(line)[0] / lineToMargins.get(line)[1]
                              : null,
                    lineToMargins.get(line)[2]
                )
            );
        }
        return productLines;
    }

    /*
     *  @author       : Akash Kumar
     *  @description  : Wrapper class to handle line item details dynamically
     */
    public class LineLevelWrapper {
        @AuraEnabled
        public String productLine;
        @AuraEnabled
        public Double marginAtProposedPrice;
        @AuraEnabled
        public Double standardMarginTarget;
        @AuraEnabled
        public Double productLineSortBy;

        /*
         * Description : Constructor to Wrapper Class for LineLevel details.
         */
        public LineLevelWrapper(string productLine, Double marginAtProposedPrice, Double standardMarginTarget) {
            this.productLine = productLine;
            this.marginAtProposedPrice = marginAtProposedPrice;
            this.productLineSortBy = marginAtProposedPrice != null ? marginAtProposedPrice : 0;
            this.standardMarginTarget = standardMarginTarget;
        }
    }

    /*
     *  @author       : Pradeep Landge
     *  @description  : Finds and returns the quote type based on its properties.
     *  @param        : q The Quote object to evaluate.
     *  @return       : String The type of the Quote (e.g., Indirect, Direct).
     */
    private string findQuoteType(Apttus_Proposal__Proposal_Line_Item__c line) {
        if (line.Apttus_Proposal__Proposal__r.Direct_Sale_to_Ultimate_Consignee__c) {
            return (System.Label.Indirect_Direct_UC_Quote);
        } else if (line.Apttus_Proposal__Proposal__r.Quote_Type__c.startsWith(System.Label.DistributionChannelDirect)) {
            return (System.Label.Direct_Quote);
        } else if (line.Apttus_Proposal__Proposal__r.Quote_Type__c.startsWith(System.Label.DistributionChannelIndirect)) {
            return (System.Label.Indirect_Quote);
        }
        return null;
    }

    /**
     * Method to fetch Currency Type records for all Currency ISO Codes.
     **/
    private List<CurrencyType> fetchCurrencyTypeIsoCode(string currencyIsoCode) {
        CurrencyCodesSelector selector = new CurrencyCodesSelector();
        return selector.getCurrencyTypeRecordsFromIsoCodes(new Set<string>{ currencyIsoCode });
    }

    /**
     * Method to calcualion of quote header values
     **/
    private Map<string, Decimal> calcQuoteHeaderDetails(List<QuoteLineItemData> lineItems) {
        ilib_LogEvent.push('calcQuoteHeaderDetails');
        Map<string, Decimal> headerDetailsMap = new Map<string, Decimal>();
        Double standardMarginAtListPriceTotal = 0;
        Double extendedListPriceTotal = 0;
        Double standardMarginAtQuoteProposedPriceTotal = 0;
        Double proposedExtendedListPriceTotal = 0;

        ilib_LogEvent.message('@@@ Parameterts for Calculation @@@');
        if (lineItems != null && !lineItems.isEmpty()) {
            for (QuoteLineItemData item : lineItems) {
                ilib_LogEvent.message('Line Number : ' + item.line.name);
                ilib_LogEvent.message('Line productName : ' + item.productName);
                ilib_LogEvent.message('Line standardCogs : ' + item.standardCogs);

                if (item.standardCogs != null) {
                    ilib_LogEvent.message(item.line.name + ': standardMarginAtListPrice : ' + item.standardMarginAtListPrice);
                    ilib_LogEvent.message(
                        item.line.name + ': standardMarginAtListPrice >> Calculated from "calculateStandardMarginAtListPrice"'
                    );
                    standardMarginAtListPriceTotal += item.standardMarginAtListPrice;

                    ilib_LogEvent.message(item.line.name + ': extendedListPrice :' + item.extendedListPrice);
                    ilib_LogEvent.message(item.line.name + ': extendedListPrice >> Calculated from "calculateExtendedListPrice"');

                    extendedListPriceTotal += item.extendedListPrice;

                    ilib_LogEvent.message(item.line.name + ': marginAtQuotePrice : ' + item.marginAtQuotePrice);
                    ilib_LogEvent.message(
                        item.line.name + ': marginAtQuotePrice >> Calculated from "calculateStandardMarginAtQuoteProposedPrice"'
                    );

                    StandardMarginAtQuoteProposedPriceTotal += item.marginAtQuotePrice != null ? item.marginAtQuotePrice : 0;

                    ilib_LogEvent.message(item.line.name + ': quoteExtendedPrice : ' + item.quoteExtendedPrice);
                    ilib_LogEvent.message(item.line.name + ': quoteExtendedPrice >> Calculated from "Calculate quoteExtendedPrice"');

                    proposedExtendedListPriceTotal += item.quoteExtendedPrice != null ? item.quoteExtendedPrice : 0;
                }
            }
        }

        ilib_LogEvent.message('@@@ Total values @@@');
        ilib_LogEvent.message('standardMarginAtListPriceTotal               : ' + standardMarginAtListPriceTotal);
        ilib_LogEvent.message('extendedListPriceTotal                       : ' + extendedListPriceTotal);
        ilib_LogEvent.message('standardMarginAtQuoteProposedPriceTotal      : ' + standardMarginAtQuoteProposedPriceTotal);
        ilib_LogEvent.message('proposedExtendedListPriceTotal               : ' + proposedExtendedListPriceTotal);

        headerDetailsMap.put(NET_MARGIN, StandardMarginAtQuoteProposedPriceTotal);
        ilib_LogEvent.message('@@@ Formula for NET_MARGIN => SUM(marginAtQuotePrice) => ' + StandardMarginAtQuoteProposedPriceTotal);

        headerDetailsMap.put(
            MARGIN_LIST_PRICE,
            extendedListPriceTotal != 0 ? standardMarginAtListPriceTotal / extendedListPriceTotal : null
        );
        ilib_LogEvent.message(
            '@@@ Formula for MARGIN_LIST_PRICE => standardMarginAtListPriceTotal / extendedListPriceTotal => ' +
            headerDetailsMap.get(MARGIN_LIST_PRICE)
        );

        headerDetailsMap.put(
            PROPOSED_PRICE,
            proposedExtendedListPriceTotal != 0 ? StandardMarginAtQuoteProposedPriceTotal / proposedExtendedListPriceTotal : null
        );
        ilib_LogEvent.message(
            '@@@ Formula for PROPOSED_PRICE => StandardMarginAtQuoteProposedPriceTotal / proposedExtendedListPriceTotal => ' +
            headerDetailsMap.get(PROPOSED_PRICE)
        );

        ilib_LogEvent.message('headerDetailsMap ' + headerDetailsMap);
        ilib_LogEvent.pop();
        return headerDetailsMap;
    }

    /*
     * @Author: Pradeep Landge
     * @date: 17-Oct-2024
     * @Description : Method to get COGS data for Quote
     * @param : Quote Id
     * @return: MAP< String, Double >
     */
    public ResponseWrapper getCOGSForQuote(List<Apttus_Proposal__Proposal_Line_Item__c> items) {
        ilib_LogEvent.push('getCOGSForQuote');
        ilib_LogEvent.rootTitle = LOG_TITLE;
        ilib_LogEvent.push(LOG_TITLE + '.getCOGSForQuote()');
        ilib_LogEvent.message('quoteRecordId: ' + items[0].Apttus_Proposal__Proposal__c);

        Map<String, Double> cogsValues = new Map<String, Double>();
        ResponseWrapper responsewrapper;
        HttpResponse response;
        try {
            ViewSalesMarginDataController instantiated = new ViewSalesMarginDataController();
            ilib_RestInterface.InterfaceDetails interfaceDetails = instantiated.interfaceDetails;
            string strRequstQuotJSON = createCoGsReqJSON(items[0]);
            ilib_LogInterface.LogDetails log = ilib_LogInterface.initiateLog(interfaceDetails, strRequstQuotJSON);
            String message;
            response = ApttusSAPConnector.getCOGS(strRequstQuotJSON);
            ilib_LogEvent.message('COGS Response : ' + response.getBody());
            if (response.getStatusCode() == HTTP_SUCCESS_CODE || response.getStatusCode() == HTTP_POST_SUCCESS_CODE) {
                // Parse the response JSON
                COGS_ResponseWrapper cogsResWrap = COGS_ResponseWrapper.parse(response.getBody());
                ilib_LogEvent.message('COGS Serialized Response : ' + JSON.serializePretty(cogsResWrap));
                if (cogsResWrap.d.navhdrtoret?.results[0].type == SAPSUCCESS) {
                    if (cogsResWrap.d.navhdrtoitemcond != null) {
                        for (COGS_ResponseWrapper.cls_results item : cogsResWrap.d.navhdrtoitemcond.results) {
                            cogsValues.put(item.ZzapPosnr, Double.valueOf(item.Krate.replace(',', '')));
                        }
                    }
                    message = JSON.serializePretty(cogsResWrap.d.navhdrtoret.results[0]);
                    responsewrapper = new ResponseWrapper(cogsValues, log, SUCCESS, message, items[0].Apttus_Proposal__Proposal__c);
                } else {
                    message = JSON.serializePretty(cogsResWrap.d.navhdrtoret.results[0]);
                    responsewrapper = new ResponseWrapper(cogsValues, log, ERROR, message, items[0].Apttus_Proposal__Proposal__c);
                }
            } else {
                cogsValues.put(ERROR, 0.0);
                responseWrapper = new ResponseWrapper(cogsValues, log, ERROR, response.getBody(), items[0].Apttus_Proposal__Proposal__c);
            }
        } catch (Exception e) {
            ilib_LogEvent.error('Error at line         					: ' + e.getLineNumber());
            ilib_LogEvent.error('The following exception has occurred   : ' + e.getMessage());
            ilib_LogEvent.error('Exception type caught 					: ' + e.getTypeName());
            ilib_LogEvent.error('Cause                 					: ' + e.getCause());
            ilib_LogEvent.error('Stack trace           					: ' + e.getStackTraceString());
            cogsValues.put(ERROR, 0.0);
            ApexExceptions.emit('ViewSalesMarginDataController', items[0].Apttus_Proposal__Proposal__c, e);
        }
        ilib_LogEvent.pop();
        return responsewrapper;
    }

    /*
     * @Author: Pradeep Landge
     * @date: 17-Oct-2024
     * @Description :static method for create Quote JSON
     * @param : Object Apttus_Proposal__Proposal_Line_Item__c
     * @return: JSON
     */

    public static String createCoGsReqJSON(Apttus_Proposal__Proposal_Line_Item__c line) {
        ilib_LogEvent.push('createCoGsReqJSON');
        CreateCoGsReqJSONWrapper wrrRequest = new CreateCoGsReqJSONWrapper();
        wrrRequest.ZzapQuot = (String) line.Apttus_Proposal__Proposal__r.Name;
        wrrRequest.Zzoppid = (String) line.Apttus_Proposal__Proposal__r.Apttus_Proposal__Opportunity__c;
        wrrRequest.Zstatus = GETCOGS;
        wrrRequest.Vbeln = line.Apttus_Proposal__Proposal__r.SAP_Quote__c != null
            ? (String) line.Apttus_Proposal__Proposal__r.SAP_Quote__c
            : '';
        ilib_LogEvent.message('Quote : ' + line.Apttus_Proposal__Proposal__c);
        String quotJSON = JSON.serializePretty(wrrRequest);
        ilib_LogEvent.pop();
        return quotJSON;
    }

    /* 
    COGS wrapper Class for JSON
    */
    public class CreateCoGsReqJSONWrapper {
        public string ZzapQuot;
        public String Zzoppid;
        public String Zstatus;
        public String Vbeln;
        public List<Object> NAVHDRTORET = new List<Object>();
        public List<Object> NAVHDRTOITEMCOND = new List<Object>();
    }

    /*
     * @author : Pradeep Landge
     * Description : Wrapper Class for Quote related details.
     *               This class is used to encapsulate the details of a quote,
     *               including its number, type, currency, financial metrics like
     *               net margin, and line items. It also provides a breakdown of margin
     *               analysis by product line.
     */
    public class MarginAnalysisData {
        @AuraEnabled
        public String quoteNumber;
        @AuraEnabled
        public String quoteType;
        @AuraEnabled
        public String currencyIsoCode;
        @AuraEnabled
        public Decimal budgetFXRate;
        @AuraEnabled
        public Decimal netMargin;
        @AuraEnabled
        public Decimal standardMarginListPrice;
        @AuraEnabled
        public Decimal standardMarginProposedPrice;
        @AuraEnabled
        public String soldToAccount;
        @AuraEnabled
        public Boolean boolShowTargetMarginError = false;
        @AuraEnabled
        public Boolean boolShowCogsError = false;
        @AuraEnabled
        public List<QuoteLineItemData> lineItems;
        @AuraEnabled
        public List<LineLevelWrapper> productLines;

        /*
         * Description : Constructor to Wrapper Class for Quote related details.
         */
        public MarginAnalysisData(
            List<Apttus_Proposal__Proposal_Line_Item__c> items,
            Map<String, Double> materialNumberToTargerMargin,
            Map<String, Double> lineNumberToCogs
        ) {
            ViewSalesMarginDataController vsm = new ViewSalesMarginDataController();
            this.quoteNumber = items[0].Apttus_Proposal__Proposal__r.Name;
            this.quoteType = vsm.findQuoteType(items[0]);
            this.currencyIsoCode = items[0].Apttus_Proposal__Proposal__r.Apttus_QPConfig__PriceListId__r?.currencyIsoCode != null
                ? items[0].Apttus_Proposal__Proposal__r.Apttus_QPConfig__PriceListId__r.currencyIsoCode
                : items[0].Apttus_Proposal__Proposal__r.currencyIsoCode; //q.Budget_FX_Rate__c;
            this.soldToAccount = items[0].Apttus_Proposal__Proposal__r.Sold_To_Account_Name__c;
            this.boolShowTargetMarginError = materialNumberToTargerMargin.containsKey(ERROR) ? true : false;
            this.boolShowCogsError = lineNumberToCogs.containsKey(ERROR) ? true : false;
            this.lineItems = new List<QuoteLineItemData>();
            for (Apttus_Proposal__Proposal_Line_Item__c item : items) {
                this.lineItems.add(new QuoteLineItemData(item, materialNumberToTargerMargin, lineNumberToCogs));
            }
            if (this.lineItems != null && !this.lineItems.isEmpty())
                this.productLines = lineLevelAnalysis(this.lineItems);

            Map<string, Decimal> headerDetailsMap = vsm.calcQuoteHeaderDetails(this.lineItems);
            this.budgetFXRate = vsm.fetchCurrencyTypeIsoCode(currencyIsoCode)[0].ConversionRate;
            this.netMargin = headerDetailsMap.get(NET_MARGIN);
            this.standardMarginListPrice = headerDetailsMap.get(MARGIN_LIST_PRICE);
            this.standardMarginProposedPrice = headerDetailsMap.get(PROPOSED_PRICE);
        }
    }

    /**
     * @author       : Pradeep Landge
     * Description   : Wrapper class for Quote Line Item details and margin calculations.
     */
    public class QuoteLineItemData {
        public Double priceForCalculation = 0;
        public Double distributorSpecificDiscount = 0;
        @AuraEnabled
        public Double extendedListPrice = 0;
        @AuraEnabled
        public Double marginAtQuotePrice;
        @AuraEnabled
        public Double standardMarginAtListPrice = 0;
        public Boolean isNonSubscriptionLineItem, isSubscriptionLineItem = false;
        public String quoteType;
        @AuraEnabled
        public String productName;
        @AuraEnabled
        public Apttus_Proposal__Proposal_Line_Item__c line;
        @AuraEnabled
        public String currencyIsoCode;
        @AuraEnabled
        public String productLine;
        @AuraEnabled
        public String materialNumber;
        @AuraEnabled
        public Double quantity;
        @AuraEnabled
        public Double listPrice;
        @AuraEnabled
        public String materialClass;
        @AuraEnabled
        public Double priceOverride;
        @AuraEnabled
        public Double termMonths;
        @AuraEnabled
        public Double channelPartnerPrice;
        @AuraEnabled
        public Double distributorCommission;
        @AuraEnabled
        public Double historicalDiscount;
        @AuraEnabled
        public Double quoteProposedPrice;
        @AuraEnabled
        public Double quoteExtendedPrice;
        @AuraEnabled
        public Double marginAtListPrice;
        @AuraEnabled
        public Double marginAtHistoricalDiscount;
        @AuraEnabled
        public Double marginAtProposedPrice;
        @AuraEnabled
        public Double standardMarginTarget;
        @AuraEnabled
        public Double netprice;
        @AuraEnabled
        public Double standardCogs;
        @AuraEnabled
        public Double standardCogsSort;

        /*
         * Description   : Constructor to Wrapper class for Quote Line Item details and margin calculations.
         */
        public QuoteLineItemData(
            Apttus_Proposal__Proposal_Line_Item__c item,
            Map<String, Double> materialNumberToTargerMargin,
            Map<String, Double> lineNumberToCogs
        ) {
            SalesMarginDataCalculationService salesMarginObj = new SalesMarginDataCalculationService();
            this.line = item;
            ilib_LogEvent.message('Calculate QLI' + line.Name);
            if ((!lineNumberToCogs?.containsKey(ERROR) && lineNumberToCogs.get(item.Derived_From_Name__c) != null) || Test.isRunningTest())
                this.standardCogs = Test.isRunningTest() ? (Math.random() * 10) : lineNumberToCogs.get(item.Derived_From_Name__c);
            this.standardCogsSort = standardCogs != null ? standardCogs : 0;
            this.productName = item.Apttus_Proposal__Product__r.Name;
            this.productLine = item.Apttus_Proposal__Product__r.Product_Line_ilmn__c;
            this.materialNumber = item.Apttus_Proposal__Product__r.Material_Number__c;
            this.quantity = item.Apttus_QPConfig__Quantity2__c;
            this.listPrice = item.List_Price__c;
            this.materialClass = item.Material_Class__c;
            this.priceOverride = item.Price_Override__c;
            this.currencyIsoCode = item.Apttus_QPConfig__PriceListId__r?.currencyIsoCode != null
                ? item.Apttus_QPConfig__PriceListId__r.currencyIsoCode
                : item.currencyIsoCode;
            this.termMonths = item.Term_Months__c;
            this.quoteProposedPrice = item.Apttus_QPConfig__NetUnitPrice__c;
            ilib_LogEvent.message('Calculate quoteProposedPrice for QLI' + this.quoteProposedPrice);
            this.netprice = item.Customer_Net_Price__c;
            this.distributorCommission = item.Distributor_Rebate__c;
            this.priceForCalculation = item.Price_Override__c != null ? item.Price_Override__c : item.List_Price__c;
            this.quoteType = new ViewSalesMarginDataController().findQuoteType(item);
            if (this.quoteType == Label.Indirect_Quote) {
                this.distributorSpecificDiscount = item.Distributor_Specific_Discount_Percentage__c != null
                    ? item.Distributor_Specific_Discount_Percentage__c
                    : 0;
                this.channelPartnerPrice = (1 - distributorSpecificDiscount / 100) * this.priceForCalculation;
            }
            this.isNonSubscriptionLineItem = isNonSubscriptionLineItem(item);
            this.isSubscriptionLineItem = isSubscriptionLineItem(item);
            this.extendedListPrice = salesMarginObj.calculateExtendedListPrice(
                item,
                this.priceForCalculation,
                this.isSubscriptionLineItem,
                this.isNonSubscriptionLineItem,
                this.quoteType
            );
            Double totalDiscountPercentage = item.Total_Discount_Percentage__c != null ? item.Total_Discount_Percentage__c : 0;
            ilib_LogEvent.message('Calculate quoteExtendedPrice for QLI' + line.Name);
            ilib_LogEvent.message('totalDiscountPercentage : ' + totalDiscountPercentage);
            ilib_LogEvent.message('extendedListPrice : ' + extendedListPrice);
            ilib_LogEvent.message('extendedListPrice Calculated from calculateExtendedListPrice');
            Double extendedListPriceSpecific = salesMarginObj.calculateExtendedListPrice(
                                                    item,
                                                    this.priceForCalculation,
                                                    this.isSubscriptionLineItem,
                                                    this.isNonSubscriptionLineItem
                                                );
            this.quoteExtendedPrice = (1 - totalDiscountPercentage / 100) * extendedListPriceSpecific;
            //this.quoteExtendedPrice = item.Apttus_QPConfig__NetPrice__c;
            ilib_LogEvent.message('quoteExtendedPrice : (1-totalDiscountPercentage/100)*this.extendedListPrice : ' + quoteExtendedPrice);
            this.marginAtQuotePrice = (standardCogs != null && (this.isNonSubscriptionLineItem || this.isSubscriptionLineItem))
                ? salesMarginObj.calculateStandardMarginAtQuoteProposedPrice(   
                      item,
                      this.priceForCalculation,
                      this.isSubscriptionLineItem,
                      this.isNonSubscriptionLineItem,
                      this.quoteType,
                      standardCogs
                  )
                : null;
            this.standardMarginAtListPrice = standardCogs != null
                ? salesMarginObj.calculateStandardMarginAtListPrice(
                      item,
                      this.priceForCalculation,
                      this.isSubscriptionLineItem,
                      this.isNonSubscriptionLineItem,
                      this.quoteType,
                      standardCogs
                  )
                : null;
            Double customerHistoricDiscount = item.Customer_Historical_Discount__c != null ? item.Customer_Historical_Discount__c : 0;
            this.historicalDiscount =  (1 - customerHistoricDiscount / 100) * this.priceForCalculation;
            if (standardCogs != null && (this.isNonSubscriptionLineItem || this.isSubscriptionLineItem)) {
                this.marginAtListPrice = SalesMarginDataCalculationService.calculateStandardMarginAtListPricePercentage(
                    item,
                    this.priceForCalculation,
                    this.isSubscriptionLineItem,
                    this.isNonSubscriptionLineItem,
                    this.quoteType,
                    standardCogs
                );
                this.marginAtHistoricalDiscount = SalesMarginDataCalculationService.calculateStandardMarginAtHistoricDiscountPercent(
                    item,
                    this.priceForCalculation,
                    this.isSubscriptionLineItem,
                    this.isNonSubscriptionLineItem,
                    this.quoteType,
                    standardCogs
                );
                this.marginAtProposedPrice = SalesMarginDataCalculationService.calculateStandardMarginAtQuoteProposedPricePercent(
                    item,
                    this.priceForCalculation,
                    this.isSubscriptionLineItem,
                    this.isNonSubscriptionLineItem,
                    this.quoteType,
                    standardCogs
                );
            }
            if (
                (!materialNumberToTargerMargin.containsKey(ERROR) &&
                materialNumberToTargerMargin.get(item.Apttus_Proposal__Product__r.Material_Number__c) != null) || Test.isRunningTest()
            )
                this.standardMarginTarget = Test.isRunningTest()
                    ? (Math.random() * 100)
                    : materialNumberToTargerMargin.get(item.Apttus_Proposal__Product__r.Material_Number__c) != 0 ?
                    materialNumberToTargerMargin.get(item.Apttus_Proposal__Product__r.Material_Number__c) / 100 
                    : null;
                    
        }
        private Boolean isNonSubscriptionLineItem(Apttus_Proposal__Proposal_Line_Item__c objQli) {
            return objQli.List_Price__c != null &&
                !objQli.Apttus_Proposal__Product__r.Custom_Product__c &&
                (objQli.Term_Months__c == null ||
                objQli.Term_Months__c <= 0);
        }

        private Boolean isSubscriptionLineItem(Apttus_Proposal__Proposal_Line_Item__c objQli) {
            return objQli.List_Price__c != null &&
                !objQli.Apttus_Proposal__Product__r.Custom_Product__c &&
                (objQli.Term_Months__c != null &&
                objQli.Term_Months__c > 0);
        }
    }

    /*
     *  @author       : Akash Kumar
     *  @description  : Generic Response Wrapper to store log info and values from api
     */

    public class ResponseWrapper {
        public Map<String, Double> resultMap = new Map<String, Double>();
        public ilib_LogInterface.LogDetails log;
        public String integrationStatus;
        public String message;
        public String quoteId;
        /*
         * Description : Constructor to fill the response wrapper with required info
         */
        public ResponseWrapper(
            Map<String, Double> resultMap,
            ilib_LogInterface.LogDetails log,
            String integrationStatus,
            String message,
            String quoteId
        ) {
            this.resultMap = resultMap;
            this.log = log;
            this.integrationStatus = integrationStatus;
            this.message = message;
            this.quoteId = quoteId;
        }
    }
}