force-app/main/default/objects/Customer_Agreement__c/Customer_Agreement__c.object-meta.xml
<CustomObject>
    <description>Deprecated Object: This object was used to store the customer agreements before CLM go live. All the active Customer Agreements are migrated to Apttus OOB Agreements Object as on CLM go live date.</description>
    <label>Customer Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Agreements - DEPRECATED</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Agreement__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <description>Agreement Number</description>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Agreement__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Agreement Type</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Certificate Of Authorization</fullName>
            </value>
            <value>
                <fullName>Channel Partner Agreement</fullName>
            </value>
            <value>
                <fullName>Due Diligence Questionnaire</fullName>
            </value>
            <value>
                <fullName>Standing Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Agreement__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Agreement__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type</description>
    <label>Product Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Consumable</fullName>
            </value>
            <value>
                <fullName>FastTrack Services</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Service Contract</fullName>
            </value>
            <value>
                <fullName>TG Consumables</fullName>
            </value>
            <value>
                <fullName>TruSight Content Sets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Agreement__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Agreement_Account_Link__c/Customer_Agreement_Account_Link__c.object-meta.xml
<CustomObject>
    <label>Customer Agreement Account Link</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Customer Agreement Account Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Agreement Account Links</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Agreement_Account_Link__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Field to store Account Id</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Group__c</field>
            <operation>notEqual</operation>
            <value>Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Agreement Account Links</relationshipLabel>
    <relationshipName>Customer_Agreement_Account_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Agreement_Account_Link__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Field to store Agreement type</description>
    <formula>TEXT ( Customer_Agreement__r.Agreement_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Agreement_Account_Link__c/fields/Customer_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Customer_Agreement__c</fullName>
    <description>Field to store Customer Agreement</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Agreement</label>
    <referenceTo>Customer_Agreement__c</referenceTo>
    <relationshipLabel>Customer Agreement Account Links</relationshipLabel>
    <relationshipName>Customer_Agreement_Account_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Agreement_Account_Link__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Field to store End date</description>
    <formula>TEXT ( Customer_Agreement__r.End_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Agreement_Account_Link__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Field to store start date</description>
    <formula>TEXT ( Customer_Agreement__r.Start_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataContract.cls
/**
 * Created by tnewman on 11/20/18.
 */
@isTest
public with sharing class TestDataContract {

    /*public static Customer_Agreement__c getNewAgreement()
    {
        Customer_Agreement__c rec = initAgreement();
        insert rec;
        return rec;
    }
    public static Customer_Agreement__c initAgreement()
    {
        Customer_Agreement__c rec = new Customer_Agreement__c(
                Name = TestData.getRandom(),
                Agreement_Number__c = TestData.getRandomNumeric(),
                Agreement_Type__c = 'Standing Agreement',
                Product_Type__c = 'Instrument',
                Start_Date__c = Date.today() - 2,
                End_Date__c = Date.today() + 20
        );
        return rec;
    }
    public static Customer_Agreement_Account_Link__c getNewAgreementLink(Id accountId, Id agreementId)
    {
        Customer_Agreement_Account_Link__c rec = initAgreementLink(accountId, agreementId);
        insert rec;
        return rec;
    }
    public static Customer_Agreement_Account_Link__c initAgreementLink(Id accountId, Id agreementId)
    {
        Customer_Agreement_Account_Link__c rec = new Customer_Agreement_Account_Link__c(
                Account__c = accountId,
                Customer_Agreement__c = agreementId
        );
        return rec;
    }*/

}