force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
    <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N70000001hzZ0EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing location record</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>R00N70000001hzcqEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Identifier</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3730xl</fullName>
            </value>
            <value>
                <fullName>454</fullName>
            </value>
            <value>
                <fullName>7900</fullName>
            </value>
            <value>
                <fullName>Additional Datastore/Facility</fullName>
            </value>
            <value>
                <fullName>API Package</fullName>
            </value>
            <value>
                <fullName>API Script</fullName>
            </value>
            <value>
                <fullName>Bartender Integration</fullName>
            </value>
            <value>
                <fullName>Client Licenses</fullName>
            </value>
            <value>
                <fullName>Configuration Slice</fullName>
            </value>
            <value>
                <fullName>Custom AI Integration</fullName>
            </value>
            <value>
                <fullName>Custom JBOSS settings</fullName>
            </value>
            <value>
                <fullName>Custom Product</fullName>
            </value>
            <value>
                <fullName>Custom Reports</fullName>
            </value>
            <value>
                <fullName>Database Customization</fullName>
            </value>
            <value>
                <fullName>Data Model Package</fullName>
            </value>
            <value>
                <fullName>GeneChip</fullName>
            </value>
            <value>
                <fullName>HiScan</fullName>
            </value>
            <value>
                <fullName>HiSeq 2000/2500</fullName>
            </value>
            <value>
                <fullName>HiSeq 3000</fullName>
            </value>
            <value>
                <fullName>HiSeq 4000</fullName>
            </value>
            <value>
                <fullName>HiSeq Integration</fullName>
            </value>
            <value>
                <fullName>HiSeqX</fullName>
            </value>
            <value>
                <fullName>Infinium Integration</fullName>
            </value>
            <value>
                <fullName>Ion PGM</fullName>
            </value>
            <value>
                <fullName>Ion Proton</fullName>
            </value>
            <value>
                <fullName>Ion Torrent</fullName>
            </value>
            <value>
                <fullName>iScan</fullName>
            </value>
            <value>
                <fullName>Lab Instrument Toolkit</fullName>
            </value>
            <value>
                <fullName>LabLink Branding</fullName>
            </value>
            <value>
                <fullName>LabLink Customised Sample Import Sheets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Account__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your account.</description>
    <inlineHelpText>The company to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your company</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>To capture the type of location</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trunk</fullName>
            </value>
            <value>
                <fullName>Locker</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
            <value>
                <fullName>Partner Stock</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Importer Of Record</fullName>
            </value>
            <value>
                <fullName>Customer Hierarchy</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
                <isActive>false</isActive>
                <label>Temporary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestTAPS_Locations.cls
/**
*    @author Todd Newman
*    Created Date 2018-12-11
*    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------
*         Developer                      Date                Description
*         Ashwin Kumar                   31-Mar-2021         DCP-52339 Remove TestTAPS.setupDeferredObjectData
*    ---------------------------------------------------------------------------------------------------------------------------
**/	

@isTest
private class TestTAPS_Locations {

    // NOTE: TestTAPS covers scenarios like new user, new territory, territory move 
    // this is just to make sure we have coverage of the specific object trigger

    @testSetup static void setupEtmData()
    {
        setupTerritoryData();    
    }
    static void setupTerritoryData()
    {
        User objUser = TestDataUser.findUserInProfile(TestDataUser.PROFILE_ADMIN,new Set<Id>{UserInfo.getUserId()});
        System.runAs(objUser){
            TestTAPS.setupTerritoryDataWithPartners();
        }
    }

    // these methods do most of the object-specific work, modify all of them

    private static TAPS_ComposedBase mshareClass;
    private static TAPS_ComposedBase getShareClass()
    {
        if (mshareClass == null) mshareClass = new TAPS_Locations();
        return mshareClass;
    }

    private static void reparentRecord(Id recordId, Id newParentId)
    {
        update new SVMXC__Site__c(Id = recordId, SVMXC__Account__c = newParentId);
    }

    private static List<SVMXC__Site__Share> getShareRecords(Id parentId)
    {
        return [SELECT Id
        FROM SVMXC__Site__Share
        WHERE ParentId = :parentId
        AND RowCause = :Schema.SVMXC__Site__Share.RowCause.Manual];
    }

    private static List<SVMXC__Site__Share> getShareRecords(Id parentId, Set<Id> userIds)
    {
        return [SELECT Id
        FROM SVMXC__Site__Share
        WHERE ParentId = :parentId
        AND RowCause = :Schema.SVMXC__Site__Share.RowCause.Manual
        AND UserOrGroupId IN :userIds];
    }

    private static void createShareRecords(Id recordId, Id userId)
    {
        TAPS_ComposedBase shareClass = getShareClass();
        insert (SVMXC__Site__Share)shareClass.createSharingRecord(recordId, userId);
    }

    // these methods are the tests, only the object creation need to be altered by class

    // inserting a record to an account associated to TERRITORY1 should add shares to the 2 associated users
    @isTest static void customAdd()
    {
        User otherAdmin = TestDataUser.findUserInProfile(TestDataUser.PROFILE_ADMIN, new Set<Id> { UserInfo.getUserId() });

        Territory2 territory1 = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1 LIMIT 1];
        Territory2 territory1cp = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1_CP LIMIT 1];
        UserTerritory2Association associatedUser1 = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory1.Id];
        UserTerritory2Association associatedUser1cp = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory1cp.Id];

        Account a1;
        SVMXC__Site__c rec1;
        System.runAs(otherAdmin)
        {
            a1 = TestDataAccount.getNewAccount();
            a1.Account_Group__c = 'Sold To';
            update a1;

            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1);
            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1cp);
        }

        Test.startTest();
        {
            rec1 = TestDataFieldService.getNewLocation(a1.Id);
            // Added by Satya as part of PRB0042764 
            TestTAPS.objectBeingTested = getShareClass().getObjectType();
            Test.getEventBus().deliver();
        }
        Test.stopTest();

        // validate shares were added by batch
        List<SObject> shareRecordsAfter = getShareRecords(rec1.Id, new Set<Id> { associatedUser1.Id });
        System.assertEquals(0, shareRecordsAfter.size());

        List<SObject> shareRecordsAfterCp = getShareRecords(rec1.Id, new Set<Id> { associatedUser1cp.UserId });
        System.assertEquals(1, shareRecordsAfterCp.size());
    }

    // inserting a record to an account associated to TERRITORY1 should add shares to the 2 associated users
    @isTest static void customAddWithoutAccount()
    {
        User otherAdmin = TestDataUser.findUserInProfile(TestDataUser.PROFILE_ADMIN, new Set<Id> { UserInfo.getUserId() });

        Territory2 territory1 = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1 LIMIT 1];
        Territory2 territory1cp = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1_CP LIMIT 1];
        UserTerritory2Association associatedUser1 = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory1.Id];
        UserTerritory2Association associatedUser1cp = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory1cp.Id];

        Account a1;
        SVMXC__Site__c rec1;
        System.runAs(otherAdmin)
        {
            a1 = TestDataAccount.getNewAccount();
            a1.Account_Group__c = 'Sold To';
            update a1;

            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1);
            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1cp);
        }

        Test.startTest();
        {
            rec1 = TestDataFieldService.initLocation(a1.Id);
            rec1.SVMXC__Account__c = null;
            rec1.Type__c = 'Partner Stock';
            insert rec1;

            Product2 prod = TestDataMaster.getNewProduct('Test Product','Instrument');
            SVMXC__Installed_Product__c ipRec = TestDataFieldService.createInstalledProduct(prod.Id);
            ipRec.SVMXC__Company__c = a1.Id;
            ipRec.SVMXC__Site__c = rec1.Id;
            insert ipRec; 

            // Added by Satya as part of PRB0042764 
            TestTAPS.objectBeingTested = getShareClass().getObjectType();
            Test.getEventBus().deliver();
        }
        Test.stopTest();

        // validate shares were added by batch
        List<SObject> shareRecordsAfter = getShareRecords(rec1.Id, new Set<Id> { associatedUser1.Id });
        System.assertEquals(0, shareRecordsAfter.size());

        List<SObject> shareRecordsAfterCp = getShareRecords(rec1.Id, new Set<Id> { associatedUser1cp.UserId });
        System.assertEquals(1, shareRecordsAfterCp.size());
    }
    
    // move a record from one account to another (and therefore from one territory to another)
    // the old shares should go away and new shares created
    @isTest static void customReparent()
    {
        User otherAdmin = TestDataUser.findUserInProfile(TestDataUser.PROFILE_ADMIN, new Set<Id> { UserInfo.getUserId() });

        Territory2 territory1 = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1 LIMIT 1];
        Territory2 territory2 = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY2 LIMIT 1];
        Territory2 territory1cp = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1_CP LIMIT 1];
        Territory2 territory2cp = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY2_CP LIMIT 1];
        UserTerritory2Association associatedUser1 = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory1.Id];
        //UserTerritory2Association associatedUser2 = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory2.Id];
        UserTerritory2Association associatedUser1cp = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory1cp.Id];
        UserTerritory2Association associatedUser2cp = [SELECT UserId FROM UserTerritory2Association WHERE Territory2Id = :territory2cp.Id];

        Account a1;
        Account a2;
        SVMXC__Site__c rec1;
        System.runAs(otherAdmin)
        {
            a1 = TestDataAccount.initAccount();
            a1.Account_Group__c = 'Sold To';
            a2 = TestDataAccount.initAccount();
            a2.Account_Group__c = 'Sold To';
            insert new List<Account> { a1, a2 };

            rec1 = TestDataFieldService.getNewLocation(a1.Id);

            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1);
            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1cp);
            TestDataTerritory.getNewAccountTerritoryLink(a2, territory2);
            TestDataTerritory.getNewAccountTerritoryLink(a2, territory2cp);
        }

        // manually create initial shares since since the trigger won't run the batch
        createShareRecords(rec1.Id, associatedUser1cp.UserId);

        // validate we start with shares on channel users for a1
        List<SObject> shareRecordsBefore1 = getShareRecords(rec1.Id, new Set<Id> { associatedUser1cp.UserId });
        System.assertEquals(1, shareRecordsBefore1.size());
        List<SObject> shareRecordsBefore2 = getShareRecords(rec1.Id, new Set<Id> { associatedUser2cp.UserId, associatedUser1.UserId });
        System.assertEquals(0, shareRecordsBefore2.size());

        Test.startTest();
        {
            reparentRecord(rec1.Id, a2.Id);
            // Added by Satya as part of PRB0042764 
            TestTAPS.objectBeingTested = getShareClass().getObjectType();
            Test.getEventBus().deliver();
        }
        Test.stopTest();

        // validate shares now belong to channel users on a2
        List<SObject> shareRecordsAfter1 = getShareRecords(rec1.Id, new Set<Id> { associatedUser1cp.UserId });
        System.assertEquals(0, shareRecordsAfter1.size());
        List<SObject> shareRecordsAfter2 = getShareRecords(rec1.Id, new Set<Id> { associatedUser2cp.UserId });
        System.assertEquals(1, shareRecordsAfter2.size());
    }

    // inserting a record with no account, shouldn't bomb
    @isTest static void orphanRecord()
    {
        User otherAdmin = TestDataUser.findUserInProfile(TestDataUser.PROFILE_ADMIN, new Set<Id> { UserInfo.getUserId() });

        Territory2 territory1 = [SELECT Id FROM Territory2 WHERE Name = :TestTAPS.TERRITORY1_CP LIMIT 1];

        Account a1;
        SVMXC__Site__c rec1;
        System.runAs(otherAdmin)
        {
            a1 = TestDataAccount.getNewAccount();
            a1.Account_Group__c = 'Sold To';
            update a1;

            TestDataTerritory.getNewAccountTerritoryLink(a1, territory1);
        }

        Test.startTest();
        {
            rec1 = TestDataFieldService.initLocation(a1.Id);
            rec1.SVMXC__Account__c = null;
            insert rec1;
            // Added by Satya as part of PRB0042764 
            TestTAPS.objectBeingTested = getShareClass().getObjectType();
            Test.getEventBus().deliver();
        }
        Test.stopTest();

        // validate nothing bad happens with orphan record
        List<SObject> shareRecordsAfter = getShareRecords(rec1.Id);
        System.assertEquals(0, shareRecordsAfter.size());
    }

}