force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan__c/SVMXC__PM_Plan__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Preventive Maintenance Plans for various customer contracts and automatically initiating execution of such maintenance plans using work orders.</description>
    <label>Preventive Maintenance Plan</label>
    <nameField>
        <label>PM Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preventive Maintenance Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__PM_Plan__c/fields/SVMXC__End_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__End_Date__c</fullName>
    <description>End Date for the preventive maintenance plan</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan__c/fields/SVMXC__Frequency__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Frequency__c</fullName>
    <description>Frequency to run the preventive maintenance plan if based on dates</description>
    <label>Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan__c/fields/SVMXC__Frequency_Unit__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Frequency_Unit__c</fullName>
    <description>Unit of measure for frequency</description>
    <label>Frequency Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
                <default>true</default>
                <label>Days</label>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan__c/fields/SVMXC__PM_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__PM_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM Plan Template</label>
    <referenceTo>SVMXC__PM_Plan_Template__c</referenceTo>
    <relationshipLabel>Preventive Maintenance Plans</relationshipLabel>
    <relationshipName>Preventive_Maintenance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service/Maintenance Contract</description>
    <label>Service/Maintenance Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipName>PM_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan__c/fields/SVMXC__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Start_Date__c</fullName>
    <description>Start date for the preventive maintenance plan</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan_Template__c/SVMXC__PM_Plan_Template__c.object-meta.xml
<CustomObject>
    <description>This is a template for creating preventive maintenance plan, it has definitions for products, schedules and tasks that are needs to be performed as part of Preventive Maintenance.</description>
    <label>PM Plan Template</label>
    <nameField>
        <label>PM Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Plan Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__PM_Schedule_Definition__c/SVMXC__PM_Schedule_Definition__c.object-meta.xml
<CustomObject>
    <description>Time based schedules for PM Plan are defined here.</description>
    <label>PM Schedule Definition</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Schedule Definition</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__PM_Schedule_Definition__c/fields/SVMXC__Frequency__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Frequency__c</fullName>
    <label>Frequency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Schedule_Definition__c/fields/SVMXC__PM_Plan__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__PM_Plan__c</fullName>
    <label>PM Plan</label>
    <referenceTo>SVMXC__PM_Plan__c</referenceTo>
    <relationshipLabel>PM Schedule Definition</relationshipLabel>
    <relationshipName>PM_Schedule_Definition</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/SVMXC__Service_Contract__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/OQ_Required__c.field-meta.xml
<CustomField>
    <fullName>OQ_Required__c</fullName>
    <description>To show OQ Required field from Service Plan</description>
    <formula>SVMXC__Service_Plan__r.OQ_Required__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OQ Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__Active__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if this contract is currently active or not. This flag is checked automatically when you activate a contract</description>
    <inlineHelpText>Flag indicating if this contract is currently active or not. This flag is checked automatically when you activate a contract</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__End_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__End_Date__c</fullName>
    <description>End date of the service contract</description>
    <inlineHelpText>End date of the service contract</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Plan</label>
    <referenceTo>SVMXC__Service_Plan__c</referenceTo>
    <relationshipLabel>Service/Maintenance Contracts</relationshipLabel>
    <relationshipName>Service_Maintenance_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Start_Date__c</fullName>
    <description>Start date of the service contract</description>
    <inlineHelpText>Start date of the service contract</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Plan__c/SVMXC__Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Service Plan is a template for creating service contract, it has all coverage information along with detail pricing terms.</description>
    <label>Service Plan</label>
    <nameField>
        <label>Service Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Plan__c/fields/OQ_Required__c.field-meta.xml
<CustomField>
    <fullName>OQ_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify if OQ is required on entitlement.</description>
    <label>OQ Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Plan__c/fields/SVMXC__Active__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Conveys whether the catalog is active or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPMScheduleDefinitionSelector.cls
/*@ author       : Prashanth
* @ date         : 20-08-2019
* @ Description  : Test class for PMScheduleDefinitionSelector class
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                              Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Prashanth                20-08-2019                        Initial version
*/
@isTest
public class TestPMScheduleDefinitionSelector{
    static testMethod void selectSchDefsForPMPlansTest(){
        Account acc = TestDataAccount.getAccount('Test Acc', 'USD');
        acc.Account_Group__c='Distributor';
        acc.ERP_Customer_Id__c = 'Test1';
        insert acc;
        System.assert(acc.Id != null);
        //pm template
        SVMXC__PM_Plan_Template__c pmTemplate = new SVMXC__PM_Plan_Template__c();
		pmTemplate.Name='Test PM Template';
		pmTemplate.CurrencyIsoCode='USD';
		insert pmTemplate;
		
		//Service Plan
		SVMXC__Service_Plan__c testServicePlan = new SVMXC__Service_Plan__c();
		testServicePlan.Name = 'Test Service Plan';
		testServicePlan.SVMXC__Active__c = true;
		testServicePlan.OQ_Required__c = true;
		insert testServicePlan;
		
        //service contract
        SVMXC__Service_Contract__c testServCont = TestDataFieldService.createServiceContract(acc.Id);
        testServCont.SVMXC__Service_Plan__c = testServicePlan.id;
        testServCont.SVMXC__Start_Date__c = system.today();
        testServCont.SVMXC__End_Date__c = system.today().addYears(1);
        insert testServCont;

        //SVMXC__PM_Plan__c
        SVMXC__PM_Plan__c pmPlan = new SVMXC__PM_Plan__c();
        pmPlan.Name='BYANNUAL Plan';
        pmPlan.CurrencyIsoCode='USD';
        pmPlan.SVMXC__PM_Plan_Template__c=pmTemplate.Id;
        pmPlan.SVMXC__Service_Contract__c= testServCont.Id;
        insert pmPlan;

        //schedule definitions
        SVMXC__PM_Schedule_Definition__c schDef = new SVMXC__PM_Schedule_Definition__c();
        schDef.SVMXC__PM_Plan__c = pmPlan.Id;
        schDef.SVMXC__Frequency__c = 26;
        schDef.SVMXC__Frequency_Unit__c = 'Weeks';
        insert schDef;
        Test.startTest();
        List<SVMXC__PM_Schedule_Definition__c> lstSchDefs = new PMScheduleDefinitionSelector().selectSchDefsForPMPlans(new Set<Id>{pmPlan.Id});
		System.assertEquals(1,lstSchDefs.size());
        Test.stopTest();
    }
}