force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <description>Flag to determine active account</description>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact.FirstName +&apos; &apos; + Contact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
    <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Cases Reported From This Site</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <description>Field to track Active ServiceMax</description>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/SVMXC__RMA_Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Parts Order is an object to handle parts logistics. With record type RMA, it is a document that authorizes products or parts to be returned to the manufacturer/repair center/warehouse. With record type Shipment,  it is an internal document that authorizes products or parts to be shipped to a customer or field inventory location. ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both.</description>
    <label>Parts Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>Enter name of lab or department. Defaulted from Work Order.</description>
    <label>Contact Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone__c</fullName>
    <description>Enter name of contact the shipment should be addressed to. Defaulted from Work Order.</description>
    <label>Contact Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/ERP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Sales_Order_Number__c</fullName>
    <description>To be populated from SAP</description>
    <externalId>true</externalId>
    <label>ERP Sales Order #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Order_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Status__c</fullName>
    <description>Current status of the RMA/Shipment order</description>
    <inlineHelpText>Current status of the RMA/Shipment order</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Integration Error</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Service_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Order related to this RMA/shipment order. Is a lookup to an existing service order record in ServiceMax</description>
    <inlineHelpText>Service Order related to this RMA/shipment order. Is a lookup to an existing service order record in ServiceMax</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipName>RMA_Shipment_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>Automatically populate Contact First Name and Last name associated with the Work Order.</description>
    <formula>SVMXC__Contact__r.FirstName + &apos; &apos; +  SVMXC__Contact__r.LastName</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Is_Auto_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_Auto_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check whether Work Order is created from automation.</description>
    <label>Is Auto Created?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Status__c</fullName>
    <description>Current status of the service order</description>
    <inlineHelpText>Current status of the service order</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
                <default>true</default>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assignment Accepted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Technician Onsite</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Revisit Required</fullName>
            </value>
            <value>
                <fullName>Estimate Approved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Technician Acknowledged</fullName>
            </value>
            <value>
                <fullName>Technician Enroute</fullName>
            </value>
            <value>
                <fullName>Work Complete</fullName>
            </value>
            <value>
                <fullName>Requires Revisit</fullName>
            </value>
            <value>
                <fullName>Reopen Requested</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Closed-Duplicate</fullName>
            </value>
            <value>
                <fullName>Awaiting Parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/recordTypes/Remote.recordType-meta.xml
<RecordType>
    <fullName>Remote</fullName>
    <active>true</active>
    <label>Remote</label>
</RecordType>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/ERP_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_ID__c</fullName>
     <description>Unique ERP Customer ID populated based on Account linked to location.</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ERP Customer ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Account__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your account.</description>
    <inlineHelpText>The company to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your company</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Stocking_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Stocking_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</description>
    <inlineHelpText>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</inlineHelpText>
    <label>Stocking Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>To capture the type of location</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trunk</fullName>
            </value>
            <value>
                <fullName>Locker</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
            <value>
                <fullName>Partner Stock</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Importer Of Record</fullName>
            </value>
            <value>
                <fullName>Customer Hierarchy</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
                <isActive>false</isActive>
                <label>Temporary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestServiceUtility.cls
/**
* @author Shivani Jain
* @date 5th Sep 2022
*
* @description DCP-43629 Test class for ServiceUtility 
*/ 
@IsTest
private class TestServiceUtility {
    /*******************************************************************************************************
    * @description test data setup
    */ 
    @TestSetup
    static void createSetupData() {
        //Creating Account
        

        Account acc = TestDataAccount.getAccount('Test Parent', 'USD');
        acc.Account_Group__c='Sold To';
        acc.ERP_Customer_Id__c = '4000026704';
        insert acc;

        Account acc1 = TestDataAccount.getAccount('Test Child', 'USD');
        acc1.Account_Group__c='Distributor';
        acc1.ParentId = acc.id;
        insert acc1;
        
        //Creating Contact
        Contact con = TestDataContact.getNewContact(acc); 

        //Creating Case      
        Case objectCase = TestDataCase.initServiceRequestCase(con);
        insert objectCase;

        //Creating Work Order
        SVMXC__Service_Order__c workOrder = TestDataFieldService.createWorkOrder('Remote Support', objectCase.Id, 'Initiated');
        workOrder.SVMXC__Order_Status__c = 'Assigned';
        workOrder.Is_Auto_Created__c = true;
        insert workOrder;

        //Insert Location
        SVMXC__Site__c location = TestDataFieldService.createLocation('ServiceLoc', 'Stringing street New York', 'Sri Lanka', '43527', 'USD');
        location.SVMXC__Account__c = acc.Id;
        SVMXC__Site__c shippingLocation = new SVMXC__Site__c(
                Name = 'testStockingLocation',
                CurrencyIsoCode = 'USD',
                SVMXC__Stocking_Location__c = true,
                SVMX_PS_Active__c = true,
                Type__c = 'Trunk');
        List<SVMXC__Site__c> locList = new list < SVMXC__Site__c > ();
            locList.add(location);
            locList.add(shippingLocation);
        insert locList;

    }

    /*******************************************************************************************************
    * @description test method for updateSoldToOnPO
    */ 
    static testmethod void testSoldToOnHierarchy() {
        Case objectCase = [SELECT id FROM Case LIMIT 1][0];
        List<Account> accList = [SELECT id FROM Account WHERE Name =: 'Test Child' LIMIT 1];
        SVMXC__Service_Order__c workOrder = [SELECT id FROM SVMXC__Service_Order__c LIMIT 1][0];
        List<SVMXC__Site__c> locList = [SELECT id FROM SVMXC__Site__c LIMIT 2];

        Test.startTest();
        //Creating Part Order
        SVMXC__RMA_Shipment_Order__c partOrder = TestDataFieldService.createPartOrder('RMA', objectCase.Id, 'Open');
        partOrder.ERP_Sales_Order_Number__c = '1234';
        partOrder.SVMXC__Service_Order__c = workOrder.id;
        partOrder.Contact_Name__c = 'Test';
        partOrder.Contact_Phone__c = 'Test';
        partOrder.SVMXC__Order_Type__c = 'Shipment';
        partOrder.SVMXC__Destination_Location__c = locList[0].Id;
        partOrder.Shipping_Location__c = locList[1].Id;
        partOrder.SVMXC__Company__c = accList[0].Id;
        partOrder.Sold_To__c = accList[0].Id;
        insert partOrder;
        Test.stopTest();

        List<SVMXC__RMA_Shipment_Order__c> updatedPartsOrder = [SELECT id, Sold_To__r.Name FROM SVMXC__RMA_Shipment_Order__c LIMIT 1];
        System.assertEquals('Test Parent', updatedPartsOrder[0].Sold_To__r.Name, 'Sold To Population logic from Metadata failed');

    }

}