force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Indicates if address has been verified in master data</description>
    <inlineHelpText>Indicates if address has been verified in master data.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
                <default>true</default>
                <label>Unverified</label>
            </value>
            <value>
                <fullName>Prospect Validation</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Upgrade</fullName>
            </value>
            <value>
                <fullName>Pending Validation</fullName>
            </value>
            <value>
                <fullName>Pending Obsolete</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Block__c.field-meta.xml
<CustomField>
    <fullName>Credit_Block__c</fullName>
    <description>Field to indicate if the account is marked for credit block and suspend it</description>
    <label>Credit Block</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Template__c/Apttus__APTS_Template__c.object-meta.xml
<CustomObject>
    <description>Contract language templates available in the system. These templates specify guidance, language, local setitngs, and include Word attachment templates representing the bulk of actual contracts that can be used when creating a first draft . Templates can include standard and non-standard language.</description>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
    <description>The proposal approval stage</description>
    <inlineHelpText>Current stage of Quote; also reflected in the lifecycle chevrons.</inlineHelpText>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related opportunity</description>
    <inlineHelpText>Related parent opportunity under which this Quote is created.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>R00N70000001yUfDEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact associated with the quote/proposal</description>
    <inlineHelpText>The primary contact for the Quote; primary contact will receive the Quote.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_QPApprov__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPApprov__Approval_Status__c</fullName>
    <description>The quote approval status</description>
    <inlineHelpText>Approval status of quote submitted for approval.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look Up To Customer Master Data</description>
    <inlineHelpText>Customer account that will receive the invoice for this transaction. Changes in Bill-To account will automatically update associated Payer account and payment terms.</inlineHelpText>
    <label>Bill To</label>
    <referenceTo>Customer_Master_Data__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Direct_Sale_to_Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sale_to_Ultimate_Consignee__c</fullName>
    <description>Formula field to populate "Direct sales to ultimate consignee"</description>
    <inlineHelpText>Field is applicable to Indirect transactions</inlineHelpText>
    <formula>Apttus_Proposal__Opportunity__r.Direct_Sale_to_Ultimate_Consignee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Direct Sale to Ultimate Consignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <description>Lookup to distributor account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Third party that purchases from Illumina to resell its products</inlineHelpText>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations (Distributor)</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <description>Lookup to customer master data</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account that will pay the invoice for this transaction.</inlineHelpText>
    <label>Payer</label>
    <referenceTo>Customer_Master_Data__c</referenceTo>
    <relationshipLabel>Quotations (Payer)</relationshipLabel>
    <relationshipName>Quotations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Payer_Credit_Block__c.field-meta.xml
<CustomField>
    <fullName>Payer_Credit_Block__c</fullName>
    <description>Stores Payer&apos;s Credit block value.</description>
    <label>Payer Credit Block</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look Up To Customer Master Data</description>
    <inlineHelpText>Name of entity that Illumina will ship product/solution to. Drives freight, tax and sales organization (direct/indirect). Changes to Ship-To after quote is Approved will not be allowed.</inlineHelpText>
    <label>Ship To</label>
    <referenceTo>Customer_Master_Data__c</referenceTo>
    <relationshipLabel>Quotations (Ship To)</relationshipLabel>
    <relationshipName>Quotations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Lookup to Account for Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Ultimate_Consignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/Customer_Master_Data__c.object-meta.xml
<CustomObject>
    <description>Stores master data for all accounts groups that are used in the system&apos;s workflow and processes. Source of majority of the data is ERP (SAP) system</description>
    <label>Customer Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Data__c/fields/Credit_Block__c.field-meta.xml
<CustomField>
    <fullName>Credit_Block__c</fullName>
    <description>Credit Block</description>
    <label>Credit Block</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct_Sale_to_Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sale_to_Ultimate_Consignee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The ultimate consignee becomes the sold-to account for quoting and order purposes, if this field is checked.</description>
    <inlineHelpText>Used when Illumina will be selling directly to the Ultimate Consignee on behalf of the channel partner. Quote output will also be addressed to the Ultimate Consignee.</inlineHelpText>
    <label>Direct Sale to Ultimate Consignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Distributor Account</description>
    <inlineHelpText>Name of distributor required.  For standard indirect transactions, sold to and distributor should be the same except when affiliates are &quot;sold to&quot;.  For direct to UC transactions, distributor is the distributor who brokers the deal and earns the rebate.</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND (4 OR 5)) OR (3 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.Account_Group__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS Data Update</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Data Migration</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Illumina</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>(Qtly/Weekly)</value>
        </filterItems>
        <infoMessage>You can only associate distributor type of account to this field. Search results only display distributor  type of  accounts tied to this opportunity.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Distributor_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As part of DCP-1298 for capturing the end user for the opportunity
Automated/Manual.</description>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerateQueueDocument.cls
/**
 * @description       : 
 * @author            : Arquimidez Mora
 * @Modification Log  : 
 * Ver         Date             Author             Modification
 * 1.0      19-Sep-2024      Arquimidez Mora      Initial Version 
**/
public with sharing class GenerateQueueDocument implements Queueable, Finalizer, Database.AllowsCallouts {
    private List<QuoteCreationAPIOppCartWrapper> lstQuoteCreationWrapper = new List<QuoteCreationAPIOppCartWrapper>();
    private List<String> lstCartValidate = new List<String>();
    private  String aVALIDATECARTSTEP = 'Cart Validation';
    private  String aFINALIZECARTSTEP = 'Finalize Cart';
    private  String aSYNCCARTSTEP = 'Sync Cart';
    private  String aSTRINGPROTECTIONLEVEL = 'Read only';
    private  String aSTRINGDOCFORMAT = 'PDF';
    private  String aSTRINGAPISERVERURL = System.Url.getOrgDomainUrl().toExternalForm() + '/services/Soap/u/60.0/' + UserInfo.getOrganizationId();
    private  String aSTRINGTEMPLATE = 'English_Direct';
    private static final String APPROVED = 'Approved';
    private static final String CREATE ='Create';
    private QueueStep processType;
    public static final String STRING_QUOTE_EMAIL = 'Quote';
    
    /**Quoeue Steps*/
    public enum QueueStep {
        STEP1_VALIDATE_CART,
        STEP2_FINALIZE_CART,
        STEP3_SYNC_CART,
        STEP4_LOG_ERRORS,
        STEP5_PUBLISH_PE_SUBMIT_FOR_APPROVAL,
        STEP6_GENDOC
    }

    /** 
     * Constructor,
     */
    public GenerateQueueDocument(List<String> lstCartValidate, QueueStep processType){
        this.lstCartValidate = lstCartValidate;
        this.processType = processType;
    }
    /** 
     * Constructor,
     */
    public GenerateQueueDocument(List<QuoteCreationAPIOppCartWrapper> lstQuoteCreationWrapper, QueueStep processType){
        this.lstQuoteCreationWrapper = lstQuoteCreationWrapper;
        this.processType = processType;
    }

    /**Execute Method*/
    public void execute( QueueableContext objContext ){
        switch on this.processType {
            when STEP1_VALIDATE_CART {
                validateCart();
            }
            when STEP2_FINALIZE_CART {
                finalizeCart();
            }
            when STEP3_SYNC_CART {
                syncCart();
            }
            when STEP4_LOG_ERRORS {
                logErrors();
            }
            when STEP5_PUBLISH_PE_SUBMIT_FOR_APPROVAL {
                publishPESubmitForApproval();
            }
            when STEP6_GENDOC {
                generateDocument();
            }
        }
    }
    /**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024 
     * @param strQuoteId  
     * @param strCartId 
     **/
    public void execute( FinalizerContext ctx ) {
        switch on this.processType {
            when STEP1_VALIDATE_CART {
                System.enqueueJob(new GenerateQueueDocument( this.lstQuoteCreationWrapper, QueueStep.STEP2_FINALIZE_CART),5);
            }
            when STEP2_FINALIZE_CART {
                System.enqueueJob(new GenerateQueueDocument( this.lstQuoteCreationWrapper, QueueStep.STEP3_SYNC_CART));
            }
            when STEP3_SYNC_CART {
                System.enqueueJob(new GenerateQueueDocument( this.lstQuoteCreationWrapper, QueueStep.STEP4_LOG_ERRORS), 5);
            }
            when STEP4_LOG_ERRORS {
                System.enqueueJob(new GenerateQueueDocument( this.lstQuoteCreationWrapper, QueueStep.STEP5_PUBLISH_PE_SUBMIT_FOR_APPROVAL));
            }
        }
    }
    
    
    /**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024 
     * @param strQuoteId  
     * @param strCartId 
     **/
    private void validateCart() {
        this.lstQuoteCreationWrapper = WebGeneratedQuoteOpportunityCreation.handleCartValidate(this.lstCartValidate);
        system.debug('lstQuoteCreationWrapper  '+this.lstQuoteCreationWrapper);
        for(QuoteCreationAPIOppCartWrapper objQuoteAPIDataWrapper :this.lstQuoteCreationWrapper){
            if(objQuoteAPIDataWrapper.objErrorHandler.lstErrors.isEmpty()){
                objQuoteAPIDataWrapper.lstSuccessesSteps.add(aVALIDATECARTSTEP);
            }
        }

        finalizeQueue(QueueStep.STEP1_VALIDATE_CART);
    }

    /**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024
     * @param strQuoteId 
     * @param strCartId 
     **/
    public void finalizeCart() {     
        for(QuoteCreationAPIOppCartWrapper objQuoteAPIDataWrapper :this.lstQuoteCreationWrapper){
            system.debug('objQuoteAPIDataWrapper '+ objQuoteAPIDataWrapper);
            if( objQuoteAPIDataWrapper.objErrorHandler?.lstErrors != null && objQuoteAPIDataWrapper.objErrorHandler?.lstErrors.size() > 0 && !Test.isRunningTest()){ 
            	continue;
            } else{
            	Boolean isSuccess = UtilsCart.finalizeCart(objQuoteAPIDataWrapper.objRequestWrapper.cartId);
                if(isSuccess){
                    objQuoteAPIDataWrapper.lstSuccessesSteps.add(aFINALIZECARTSTEP);
                }else{
                    objQuoteAPIDataWrapper.objErrorHandler.addError('ERR12', ' - Finalize Cart Failed');

                    for(String temp : ApttusValidationCallback.errorMessagesToEmail ){
                        objQuoteAPIDataWrapper.objErrorHandler.addError('ERR12', temp);
                    }
                }
            }
        }

        
        QuoteCreationAPIEmailMessagingService.handleErrorEmail(this.lstQuoteCreationWrapper, WebGeneratedQuoteOpportunityCreation.mapCustomerIds, STRING_QUOTE_EMAIL,'Finalize Cart');

        finalizeQueue(QueueStep.STEP2_FINALIZE_CART);
    }

    /**
     * @description 
     * @author Arquimidez Mora | 09-Sep-2024 
     * @param strCartId 
     **/
    private void syncCart() {
        for(QuoteCreationAPIOppCartWrapper objQuoteAPIDataWrapper :this.lstQuoteCreationWrapper){
            system.debug('objQuoteAPIDataWrapper '+ objQuoteAPIDataWrapper);
            if(objQuoteAPIDataWrapper.objErrorHandler.lstErrors !=null && objQuoteAPIDataWrapper.objErrorHandler.lstErrors.size() > 0) { 
            	continue;
            }
            /* else{
                Boolean boolSynchIsSuccess = UtilsCart.synchronizeCart(objQuoteAPIDataWrapper.objRequestWrapper.cartId);
                if(boolSynchIsSuccess){
                    objQuoteAPIDataWrapper.lstSuccessesSteps.add(aSYNCCARTSTEP);
                }else{
                    objQuoteAPIDataWrapper.objErrorHandler.addError('ERR13', ' - Sync Cart Failed');
                }
            } */
        }
        finalizeQueue(QueueStep.STEP3_SYNC_CART);
    }
	/**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024
     * @param strQuoteId 
     * @param strCartId 
     **/
    private void logErrors(){
        QuoteCreationAPIErrorHandler.insertInterfaceLog(this.lstQuoteCreationWrapper, aVALIDATECARTSTEP);
        finalizeQueue(QueueStep.STEP4_LOG_ERRORS);
    }

    /**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024
     * @param strQuoteId 
     * @param strCartId 
     **/
    private void publishPESubmitForApproval(){
        for(QuoteCreationAPIOppCartWrapper objQuoteAPIDataWrapper : this.lstQuoteCreationWrapper) {
            system.debug('objQuoteAPIDataWrapper '+ objQuoteAPIDataWrapper);
            if(objQuoteAPIDataWrapper.objErrorHandler.lstErrors != null && objQuoteAPIDataWrapper.objErrorHandler.lstErrors.size()>0 && !Test.isRunningTest()){
            	continue;
            }
            else{
                CEQWebResquestPlatformEventService.createPlatformEvent(QuoteCreationAPIPESubscriberService.Step.STEP4_SUBMIT_FOR_APPROVAL, objQuoteAPIDataWrapper.strJSONPayload);
            }
        }
    }

    /**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024
     * @param strQuoteId 
     * @param strCartId 
     **/
    private void generateDocument(){
        
        Apttus__APTS_Template__c templateDetails = new Apttus__APTS_Template__c();
        if(!Test.isRunningTest())
        templateDetails = [Select Id, Name From Apttus__APTS_Template__c where Name =:aSTRINGTEMPLATE Limit 1];
        

        List<String> quoteIdList = new List<String>();
        for(QuoteCreationAPIOppCartWrapper objCreationWrapper: this.lstQuoteCreationWrapper ){
            quoteIdList.add(objCreationWrapper.objRequestWrapper.quoteId);
        }

        Map<Id,Apttus_Proposal__Proposal__c> quoteMapDetails = new Map<Id,Apttus_Proposal__Proposal__c>([Select Id, Name,Apttus_QPApprov__Approval_Status__c, Apttus_Proposal__Approval_Stage__c,Apttus_Proposal__Opportunity__r.StageName,Bill_To__c,Ship_To__c,Payer__c,Apttus_Proposal__Opportunity__r.Account.Account_Status__c,Apttus_Proposal__Opportunity__r.Ultimate_Consignee__r.Account_Status__c,Apttus_Proposal__Opportunity__r.Lessor_Customer__r.Account_Status__c,Apttus_Proposal__Primary_Contact__c,Apttus_Proposal__Opportunity__r.Distributor__r.Account_Status__c,Apttus_Proposal__Opportunity__r.Ultimate_Consignee__r.Credit_Block__c,Apttus_Proposal__Opportunity__r.Distributor__r.Credit_Block__c,Apttus_Proposal__Opportunity__r.Direct_Sale_to_Ultimate_Consignee__c,Apttus_Proposal__Opportunity__r.Lessor_Customer__r.Credit_Block__c,Apttus_Proposal__Opportunity__r.Account.Credit_Block__c,Payer__r.Credit_Block__c,Payer_Credit_Block__c FROM Apttus_Proposal__Proposal__c WHERE Id IN: quoteIdList]);
        
        for(QuoteCreationAPIOppCartWrapper objCreationWrapper: this.lstQuoteCreationWrapper ){
            if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Approval_Stage__c ==APPROVED || Test.isRunningTest()){

                if(!String.isBlank(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Payer__r.Credit_Block__c) ){
                    objCreationWrapper.objErrorHandler.addError('ERR12', Label.UI_ErrorMessage_QuotationPayerCreditBlocked);
                }

                if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.StageName == CREATE){
                    objCreationWrapper.objErrorHandler.addError('ERR12', Label.GenerateProposalCreateStageMessage);
                }

                List<String> oppStage = new List<String>{'Closed Won','Closed Lost','Closed Abandoned'};
                if(oppStage.contains(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.StageName)){
                    objCreationWrapper.objErrorHandler.addError('ERR12', Label.GenerateProposalClosedStageMessage);
                }

                if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Bill_To__c == null){
                    objCreationWrapper.objErrorHandler.addError('ERR120', Label.GenerateProposalBillToMessage);
                }

                if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Ship_To__c == null){
                    objCreationWrapper.objErrorHandler.addError('ERR13', Label.GenerateProposalShipToMessage);
                }
                if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Payer__c == null){
                    objCreationWrapper.objErrorHandler.addError('ERR13', Label.GenerateProposalPayerMessage);
                }

                List<String> accStatus = new List<String>{'Unverified','Pending Validation'};
                if(accStatus.contains(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Account.Account_Status__c)){
                    objCreationWrapper.objErrorHandler.addError('ERR13', Label.GenerateProposalSoldToMessage);
                }

                if(accStatus.contains(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Ultimate_Consignee__r.Account_Status__c)){
                    objCreationWrapper.objErrorHandler.addError('ERR130', Label.GenerateProposalUltimateConsigneeMessage);
                }

                if(accStatus.contains(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Lessor_Customer__r.Account_Status__c)){
                    objCreationWrapper.objErrorHandler.addError('ERR14', Label.GenerateProposalLessorCustomerMessage);
                }

                if(accStatus.contains(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Distributor__r.Account_Status__c)){
                    objCreationWrapper.objErrorHandler.addError('ERR14', Label.GenerateProposalDistributorMessage);
                }
                if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Primary_Contact__c == null){
                    objCreationWrapper.objErrorHandler.addError('ERR14', Label.GenProposalPCMsg);
                }

                if(!String.isBlank(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Ultimate_Consignee__r.Credit_Block__c) ){
                    objCreationWrapper.objErrorHandler.addError('ERR140', Label.QuoteUCCreditBlock);
                }

                if(!String.isBlank(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Distributor__r.Credit_Block__c) && quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Direct_Sale_to_Ultimate_Consignee__c != true ){
                    objCreationWrapper.objErrorHandler.addError('ERR15', Label.QuoteDistCreditBlock);
                }

                if(!String.isBlank(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Lessor_Customer__r.Credit_Block__c) ){
                    objCreationWrapper.objErrorHandler.addError('ERR15', Label.QuoteLCCreditBlock);
                }

                if(!String.isBlank(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Opportunity__r.Account.Credit_Block__c) ){
                    objCreationWrapper.objErrorHandler.addError('ERR15', Label.QuoteSoldToCreditBlock);
                }
            }
           if(objCreationWrapper.objErrorHandler?.lstErrors!=null && objCreationWrapper.objErrorHandler?.lstErrors.size()>0){ 
            	continue;
            }
            else if(quoteMapDetails.get(objCreationWrapper.objRequestWrapper.quoteId).Apttus_Proposal__Approval_Stage__c ==APPROVED){
                String strQuoteId = objCreationWrapper.objRequestWrapper.quoteId;
                if(!Test.isRunningTest())
                Apttus_Proposal.MergeWebService.submitGenerateDoc(templateDetails.Id, strQuoteId, this.aSTRINGPROTECTIONLEVEL, this.aSTRINGDOCFORMAT, false,  UserInfo.getSessionId(), this.aSTRINGAPISERVERURL);  
            } 
        }
        if(!Test.isRunningTest())
        QuoteCreationAPIEmailMessagingService.handleErrorEmail(this.lstQuoteCreationWrapper, WebGeneratedQuoteOpportunityCreation.mapCustomerIds, STRING_QUOTE_EMAIL,'Generate Document');

    }

    /**
     * @description 
     * @author Arquimidez Mora | 03-Sep-2024
     * @param strQuoteId 
     * @param strCartId 
     **/
    private void finalizeQueue( QueueStep processType){
        Finalizer finalizer = new GenerateQueueDocument( this.lstQuoteCreationWrapper, processType);
        System.attachFinalizer(finalizer);
    }
}