force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Associated_Product__c/Associated_Product__c.object-meta.xml
<CustomObject>
    <description>Associated Product can link to Case and/or Work Order</description>
    <label>Associated Product</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Associated Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the Account based on the Installed Product added to the Associated product</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the Case the Associated Product is related to</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Product__c/fields/Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>Installed_Product__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Installed product</description>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Product__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <defaultValue>false</defaultValue>
    <description>If set to true, shows the product on the Associated Product is the main product for a Case.</description>
    <inlineHelpText>Check this box if this product is the main product for a Case. For Business Issue Cases, this designated the Suspected Root Cause Product.</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Associated_Product__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Work order</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <description>Case evaluation.</description>
    <inlineHelpText>Document the process taken to verify the customer problem statement, steps taken to evaluate/assess the issue and details on how cause was identified</inlineHelpText>
    <label>Evaluation</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Verification_Result__c.field-meta.xml
<CustomField>
    <fullName>Verification_Result__c</fullName>
    <description>Manual entry, Technician&apos;s verification result after the case completion.</description>
    <inlineHelpText>Specify how Illumina confirmed the issue has been resolved</inlineHelpText>
    <label>Verification Result</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the work order for elevation case</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Elevation Case</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/cs_Apex_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls apex behavior globally or by user/profile</description>
    <label>Apex Settings</label>
</CustomObject>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_Triggers_By_Object_1__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers_By_Object_1__c</fullName>
    <description>A comma-delimited list of objects for which triggers will be bypassed. Use the name that would come from describe, don&apos;t misspell it!  (ex: Opportunity,Apttus_Proposal__Proposal__c)</description>
    <label>Bypass Triggers By Object 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_Triggers_By_Object_2__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers_By_Object_2__c</fullName>
    <description>A comma-delimited list of objects for which triggers will be bypassed. Use the name that would come from describe, don&apos;t misspell it!  (ex: Opportunity,Apttus_Proposal__Proposal__c)</description>
    <label>Bypass Triggers By Object 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_Triggers_By_Object_3__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers_By_Object_3__c</fullName>
    <description>A comma-delimited list of objects for which triggers will be bypassed. Use the name that would come from describe, don&apos;t misspell it!  (ex: Opportunity,Apttus_Proposal__Proposal__c)</description>
    <label>Bypass Triggers By Object 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_Triggers_By_Object_4__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers_By_Object_4__c</fullName>
    <description>A comma-delimited list of objects for which triggers will be bypassed. Use the name that would come from describe, don&apos;t misspell it!  (ex: Opportunity,Apttus_Proposal__Proposal__c)</description>
    <label>Bypass Triggers By Object 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
    <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N70000001hzZ0EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Contact__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the primary contact for this installed product at the customer’s location. Lookup to an existing salesforce contact record</description>
    <inlineHelpText>Name of the primary contact for this installed product at the customer’s location. Lookup to an existing salesforce contact record</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N70000001hzcJEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <description>Captures the Evaluation done by Service users to complete a Work Order. Manually updated by users.</description>
    <inlineHelpText>Document the process taken to verify the customer problem statement, steps taken to evaluate/assess the issue and details on how cause was identified</inlineHelpText>
    <label>Evaluation</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Record_Created_from_SFM__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_from_SFM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-256
To check whether the record is created from SFM.
It is checked through SFM transaction when ever a record is created through SFM Button</description>
    <label>Record Created from SFM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
    <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Contact__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</description>
    <inlineHelpText>Name of the contact person from the customer account for this service order. Is a lookup to an existing salesforce contact record</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Work_Performed__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Work_Performed__c</fullName>
    <description>Details of work performed to address/resolve the service order</description>
    <inlineHelpText>Specify work done to directly address/resolve the issue</inlineHelpText>
    <label>Work Performed</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Verification_Result__c.field-meta.xml
<CustomField>
    <fullName>Verification_Result__c</fullName>
    <description>US: DCP-672
Manual entry, Technician&apos;s verification result after the Work Order completion.</description>
    <inlineHelpText>Specify how Illumina  confirmed the issue has been resolved</inlineHelpText>
    <label>Verification Result</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestHandleAPLinkwithCaseWO_WOHelper.cls
//TestHandleAPLinkwithCaseWO_WOHelper 
/*
* @ author       : Siddartha Reddy Kalam
* @ date         : 20-March-2024
* @ Description  : Test class for HandleAPLinkwithCaseWO_WOHelper class
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                              Date                               Description
* Siddartha Reddy Kalam                  20-March-2024                        Initial version - CMCM-5782
* ---------------------------------------------------------------------------------------------------------------------------------------
*/
@isTest
public class TestHandleAPLinkwithCaseWO_WOHelper {
	
    public static final String STRING_WO_RECORDTYPE = 'Field Service';
    public static final string STRING_INSTALLED_PRODUCT_NAME = 'Test IP VM';
    public static final string STRING_CURRENCY = 'USD';
    public static final string STRING_INSTALLED_PRODUCT_STATUS = 'New';
    
    /**
    * method : initializeTestData
    * Description: method is to create test data.
    * params: NA
    * return: void
    * author: Siddartha Reddy Kalam
    **/
    @testSetup
    public static void initializeTestData() {
        Feature.setMockFeatureFlag('ServiceAssociatedProducts', true);
        cs_Apex_Settings__c setting = cs_Apex_Settings__c.getInstance(UserInfo.getUserId());
        setting.Bypass_Triggers_By_Object_1__c = 'Associated_Product__c';
        setting.Bypass_Triggers_By_Object_2__c = 'Account';
        setting.Bypass_Triggers_By_Object_3__c = 'SVMXC__Installed_Product__c';
        setting.Bypass_Triggers_By_Object_4__c = 'Contact';
        upsert setting;
        //insert Account
        Account acc = TestDataAccount.getAccount('Test Acc', 'USD');
        acc.Account_Group__c = 'Distributor';
        acc.ERP_Customer_Id__c = 'Test1';
        insert acc;
        System.assert(acc.Id != null,'Account got created');

        //insert Contact
        Contact con = TestDataPerson.getNewContact(acc.Id);
        System.assert(con.id != null, 'Contact got created');
            
        //insert Case
        Case cs = TestDataCase.initServiceRequestCase(con);
        cs.Status = 'Initiated';
        insert cs;
        System.assert(cs.Id != null, 'Case got created');
        
        SVMXC__Installed_Product__c objInstalledProduct = TestDataFieldService.createInstalledProduct(STRING_INSTALLED_PRODUCT_NAME, STRING_CURRENCY, STRING_INSTALLED_PRODUCT_STATUS);
        objInstalledProduct.SVMXC__Company__c = acc.Id;
        insert objInstalledProduct; 
        
        SVMXC__Service_Order__c wo = TestDataFieldService.createWorkOrder(STRING_WO_RECORDTYPE, null, 'Initiated');
        wo.Evaluation__c = 'Test';
        wo.SVMXC__Work_Performed__c = 'Test';
        wo.Verification_Result__c = 'Test';
        wo.SVMXC__Contact__c = con.id;
        wo.Record_Created_from_SFM__c = true;
        AssociatedProduct.isTestRunning = TRUE; // added by dhairya shah
        insert wo;

        List<Associated_Product__c> assocProducts = new List<Associated_Product__c>{
            new Associated_Product__c(Case__c = cs.Id, Installed_Product__c = objInstalledProduct.Id, Account__c = acc.id),
            new Associated_Product__c(Is_Primary__c=true,Work_Order__c = wo.Id, Installed_Product__c = objInstalledProduct.Id, Account__c = acc.id),
            new Associated_Product__c(Work_Order__c = wo.Id, Installed_Product__c = objInstalledProduct.Id, Account__c = acc.id)
        };
       insert assocProducts; 
    }
    
    /**
    * method : initializeTestData
    * Description: method is to insert WO with case to link associated products related to case with WO.
    * params: NA
    * return: void
    * author: Siddartha Reddy Kalam
    **/
    @IsTest
    public static void testupdateAPsfromCaseonWO(){
        Test.startTest();
        Case cs1 = [select id from case where Status ='Initiated' Limit 1];
        System.assert(cs1.Id != null, 'fetched Case id');
        List<Associated_Product__c> insertedassocProducts = [SELECT Id FROM Associated_Product__c WHERE Case__c =: cs1.Id Limit 3];
        SVMXC__Service_Order__c wo = TestDataFieldService.createWorkOrder(STRING_WO_RECORDTYPE, null, 'Initiated');
        wo.Evaluation__c='Test';
        wo.SVMXC__Work_Performed__c = 'Test';
        wo.Verification_Result__c = 'Test';
        wo.SVMXC__Case__c = cs1.Id;
        wo.Record_Created_from_SFM__c=true;
        try{
            AssociatedProduct.isTestRunning = TRUE;
            insert wo;
        }catch (Exception e) {
            System.assert(e.getMessage().contains(System.Label.AssociatedProduct_AccountContactRelation_Error),'Error');
        }
        SVMXC__Service_Order__c wo1 = [select id from SVMXC__Service_Order__c where id=:wo.id Limit 1];
        System.assert(wo1.Id != null, 'Work order got created');
        List<Associated_Product__c> updatedProducts = [SELECT Id FROM Associated_Product__c WHERE Work_Order__c =: wo1.Id Limit 3];
        System.assertEquals(updatedProducts.size(), insertedassocProducts.size(), 'All records that are inserted on case updated successfully');
	    Test.stopTest();         
    }

    /**
    * method : initializeTestData
    * Description: method is to update WO with case if case and WO both has associated products with primary record then throw error.
    * params: NA
    * return: void
    * author: Siddartha Reddy Kalam
    **/
    @IsTest
    public static void testcheckAPhasIsPrimary(){

        Case cs1 = [select id from case where Status ='Initiated' Limit 1];
        System.assert(cs1.Id != null, 'fetched Case id');
        SVMXC__Service_Order__c insertedwo = [select id from SVMXC__Service_Order__c Limit 1];
        System.assert(insertedwo.Id != null, 'fetched WO id');

        insertedwo.SVMXC__Case__c = cs1.Id;
        try{
            Test.startTest();
            update insertedwo;
            Test.stopTest(); 
        }catch (Exception e) {
            System.assert(e.getMessage().contains(System.Label.CheckAPofCaseWOHasIsprimary),'Error');
        }
    }

    /**
    * method : initializeTestData
    * Description: method is to update WO with case to link associated products related to case with WO and WO's ap records with case.
    * params: NA
    * return: void
    * author: Siddartha Reddy Kalam
    **/
    @IsTest
    public static void testverifyCaseIsChanged(){
        Case cs1 = [select id from case where Status ='Initiated' Limit 1];
        System.assert(cs1.Id != null, 'fetched Case id');

        List<Associated_Product__c> listupdateassocProducts = new List<Associated_Product__c>();
        List<Associated_Product__c> insertedassocProducts = [SELECT Id FROM Associated_Product__c WHERE Is_Primary__c = true Limit 1];
        for(Associated_Product__c objAP: insertedassocProducts){
            objAP.Is_Primary__c = false;
            listupdateassocProducts.add(objAP);
        }
        update listupdateassocProducts;
        SVMXC__Service_Order__c insertedwo = [select id from SVMXC__Service_Order__c Limit 1];
        System.assert(insertedwo.Id != null, 'fetched WO id');
        insertedwo.SVMXC__Case__c = cs1.Id;
        Test.startTest();
        AssociatedProduct.isTestRunning = TRUE; // added by dhairya shah
        update insertedwo;
        Test.stopTest(); 
        SVMXC__Service_Order__c wo1 = [select id from SVMXC__Service_Order__c where id =: insertedwo.Id Limit 1];
        System.assert(wo1.Id != null, 'Work order got created');
        List<Associated_Product__c> updatedProducts = [SELECT Id FROM Associated_Product__c WHERE Work_Order__c =: wo1.Id and Case__c =:cs1.Id Limit 1];
        System.assertEquals(updatedProducts.size(), listupdateassocProducts.size(), 'All records that are inserted on case/WO updated successfully');
    }
    
}