force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Indicates if address has been verified in master data</description>
    <inlineHelpText>Indicates if address has been verified in master data.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
                <default>true</default>
                <label>Unverified</label>
            </value>
            <value>
                <fullName>Prospect Validation</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Upgrade</fullName>
            </value>
            <value>
                <fullName>Pending Validation</fullName>
            </value>
            <value>
                <fullName>Pending Obsolete</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Clinical_Oncology_Screening_Dx_Testing__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Oncology_Screening_Dx_Testing__c</fullName>
    <description>Check if the customer perform screening/diagnostic tests in clinical oncology</description>
    <inlineHelpText>Does the company (or account) use or will in the near future use Illumina sequencing products to perform screening or diagnostic tests in clinical oncology (on human samples), or manufacture kits for such screening/testing?</inlineHelpText>
    <label>Clinical Oncology Screening/Dx Testing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categorical_Value</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>When applicable, indicates nature of entity and work within the clinical space, used for segmentation</description>
    <inlineHelpText>Indicates the account's work within the clinical space; values are region specific and used for segmentation.  Terms and regional use:  "Clinical" (All); "Non Clinical" (All); "Healthcare Prime" (AMR); "IVD Partner" (GC); "Platform Distributor" (GC).</inlineHelpText>
    <label>Clinical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clinical_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sub_Type__c</fullName>
    <description>Field to indicate customer subtype based on the customer type</description>
    <label>Customer Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Customer_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Defines nature of entity and enterprise, utilized for segmentation</description>
    <inlineHelpText>Defines nature of entity&apos;s enterprise; utilized for segmentation.</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Eligible_To_Estimate_Consumable_Spend__c.field-meta.xml
<CustomField>
    <fullName>Eligible_To_Estimate_Consumable_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Customer is eligible to estimate their Sequencing Consumable Spend for their first Contract Year under the Open Offer Supply Agreement</description>
    <inlineHelpText>Indicates that Customer is eligible to estimate their Sequencing Consumable Spend for their first Contract Year under the Open Offer Supply Agreement</inlineHelpText>
    <label>Eligible To Estimate Consumable Spend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/For_Profit_Company__c.field-meta.xml
<CustomField>
    <fullName>For_Profit_Company__c</fullName>
    <description>Is the Company Profit Company(excludes governments, government agencies, hospitals, research institutes, academic institutions, non-profit)</description>
    <inlineHelpText>Is the company (or account) a for-profit laboratory (excluding government, government agencies, hospitals, research institutes, academic institutes, and non-profits), or kit manufacturer?</inlineHelpText>
    <label>For-Profit Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categorical_Value</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>back end field.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Oncology_Lab_Manufacturer_Comparison__c.field-meta.xml
<CustomField>
        <fullName>Oncology_Lab_Manufacturer_Comparison__c</fullName>
        <description>Field will be driven by inputs from "For Profit Company" and "Clinical Oncology Screening/DX Testing" fields. Drives MFN Approval.</description>
        <inlineHelpText>Auto-populated field indicating a MFN comparison customer for use within MFN eligible countries. This field does not need to be selected manually.</inlineHelpText>
        <label>Oncology Lab/Manufacturer Comparison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Categorical_Value</valueSetName>
        </valueSet>
   </CustomField>

force-app/main/default/objects/Account/fields/Open_Offer_Comparison_Customer__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Comparison_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Offer Comparison Customer</description>
	<inlineHelpText>Customers whose discounting is relevant for internal comparison versus universal grid.</inlineHelpText>
    <label>Open Offer Comparison Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Population_Genomics__c.field-meta.xml
<CustomField>
    <fullName>Population_Genomics__c</fullName>
    <description>Boolean field to indicate if account is marked for population genomics</description>
    <label>Population Genomics</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Population_Genomics</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purchases_Products_Shipping_to_U_S__c.field-meta.xml
<CustomField>
    <fullName>Purchases_Products_Shipping_to_U_S__c</fullName>
    <description>Check if Account provide Shipping to US</description>
    <inlineHelpText>Does the company (or account) purchase or receive products shipped within OR to the US?</inlineHelpText>
    <label>Purchases Products Shipping to U.S.</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categorical_Value</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sequencing_Liquid_Bx_Cancer_Screening__c.field-meta.xml
<CustomField>
    <fullName>Sequencing_Liquid_Bx_Cancer_Screening__c</fullName>
    <description>If Clinical Oncology Screening/Dx Testing is “Yes,” then, within clinical oncology, does the company perform liquid biopsy cancer screening or diagnostics test (on human samples received form, and delivered to, unaffiliated health care professions, health care organizations or other labs) on Illumina Instruments, or manufacture kits for such screening/testing?</description>
    <inlineHelpText>If Clinical Oncology Screening/Dx Testing is “Yes,” then, within clinical oncology, does the company perform liquid biopsy cancer screening or diagnostics test (on human samples received form, and delivered to, unaffiliated health care professions, health care organizations or other labs) on Illumina Instruments, or manufacture kits for such screening/testing?</inlineHelpText>
    <label>Sequencing: Liquid Bx Cancer Screening</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Clinical_Oncology_Screening_Dx_Testing__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Signed_Open_Offer__c.field-meta.xml
<CustomField>
    <fullName>Signed_Open_Offer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customers who have signed Grail open offer.</description>
	<inlineHelpText>Customers who have signed the open offer.</inlineHelpText>
    <label>Signed Open Offer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record type is maintained by Master Data for accounts that are upgraded to Sold To or Ultimate Consignee</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Market_Segment__c/Market_Segment__c.object-meta.xml
<CustomObject>
    <description>Stores information on account&apos;s market segment, sub-segment and allocated percent if more than one is assigned</description>
    <label>Market Segment</label>
    <nameField>
        <displayFormat>MS-{000000}{MMDDYYYY}</displayFormat>
        <label>Market Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Segments</relationshipLabel>
    <relationshipName>Market_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Segment__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>Stores information of account's market segment</description>
    <label>Market Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segment__c/fields/Market_Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Sub_Segment__c</fullName>
    <description>Stores information of account's sub-segment</description>
    <label>Market Sub Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Market_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Market_Sub_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segment__c/fields/Percent_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Percent_Allocation__c</fullName>
    <description>Stores information of market segment, sub-segment and allocated percent if more than one is assigned</description>
    <label>Percent Allocation</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Categorical_Value.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Categorical Value</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clinical_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Non Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Prime</fullName>
    </customValue>
    <customValue>
        <fullName>IVD Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Distributor</fullName>
    </customValue>
    <description>As part of DCP-1298 for Clinical Type information.</description>
    <masterLabel>Clinical Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academic Medical Center</fullName>
    </customValue>
    <customValue>
        <fullName>Applied Technology Company</fullName>
    </customValue>
    <customValue>
        <fullName>Biopharma</fullName>
    </customValue>
    <customValue>
        <fullName>Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Testing Lab</fullName>
        <isActive>false</isActive>
        <label>Clinical Testing Lab</label>
    </customValue>
    <customValue>
        <fullName>Clinical Testing Lab - Service/Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Testing Lab - Specialty</fullName>
    </customValue>
    <customValue>
        <fullName>Core Research Lab</fullName>
    </customValue>
    <customValue>
        <fullName>CRO</fullName>
    </customValue>
    <customValue>
        <fullName>Department Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Genome Center</fullName>
    </customValue>
    <customValue>
        <fullName>Health System</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Clinical Testing Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Population Initiative - Funding Body</fullName>
    </customValue>
    <customValue>
        <fullName>Research Institute</fullName>
    </customValue>
    <customValue>
        <fullName>Service Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Testing Lab</fullName>
    </customValue>
    <masterLabel>Customer Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Customer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academic</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma/Biotech</fullName>
        <isActive>false</isActive>
        <label>Pharma/Biotech</label>
    </customValue>
    <customValue>
        <fullName>New Customer Sub Type</fullName>
        <isActive>false</isActive>
        <label>New Customer Sub Type</label>
    </customValue>
    <customValue>
        <fullName>Non-Profit</fullName>
        <isActive>false</isActive>
        <label>Non-Profit</label>
    </customValue>
    <customValue>
        <fullName>Indirect</fullName>
        <isActive>false</isActive>
        <label>Indirect</label>
    </customValue>
    <customValue>
        <fullName>Hospital</fullName>
        <isActive>false</isActive>
        <label>Hospital</label>
    </customValue>
    <customValue>
        <fullName>BioBank</fullName>
        <isActive>false</isActive>
        <label>BioBank</label>
    </customValue>
    <customValue>
        <fullName>Private  Institution or Company</fullName>
        <isActive>false</isActive>
        <label>Private  Institution or Company</label>
    </customValue>
    <masterLabel>Customer Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agrigenomics</fullName>
    </customValue>
    <customValue>
        <fullName>Cancer Research</fullName>
    </customValue>
    <customValue>
        <fullName>Cell and Molecular Biology Research</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Forensics</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Research</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Infectious Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Reproductive Health</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Training/Education</fullName>
    </customValue>
    <customValue>
        <fullName>Transplant genomics</fullName>
        <isActive>false</isActive>
        <label>Transplant Genomics</label>
    </customValue>
    <customValue>
        <fullName>Preconception and Fertility</fullName>
        <isActive>false</isActive>
        <label>Preconception and Fertility</label>
    </customValue>
    <customValue>
        <fullName>Public Health Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology/Virology Research</fullName>
        <isActive>false</isActive>
        <label>Microbiology/Virology Research</label>
    </customValue>
    <customValue>
        <fullName>Genetic &amp; Complex Disease Research</fullName>
        <isActive>false</isActive>
        <label>Genetic &amp; Complex Disease Research</label>
    </customValue>
    <customValue>
        <fullName>Clinical Oncology</fullName>
        <isActive>false</isActive>
        <label>Clinical Oncology</label>
    </customValue>
    <customValue>
        <fullName>Cellular and Molecular Research</fullName>
        <isActive>false</isActive>
        <label>Cellular and Molecular Research</label>
    </customValue>
    <customValue>
        <fullName>Agricultural Genomics</fullName>
        <isActive>false</isActive>
        <label>Agricultural Genomics</label>
    </customValue>
    <customValue>
        <fullName>Pregnancy</fullName>
        <isActive>false</isActive>
        <label>Pregnancy</label>
    </customValue>
    <description>As part of DCP-1298 for the possible values of Primary Segments of the market.</description>
    <masterLabel>Market Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market_Sub_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academic Research</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture Research</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Applied Microbiology</fullName>
    </customValue>
    <customValue>
        <fullName>Autoimmune Research</fullName>
    </customValue>
    <customValue>
        <fullName>Autoimmune Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiovascular Research</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiovascular Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Carrier Testing</fullName>
    </customValue>
    <customValue>
        <fullName>IVF Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolic Disease Research</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolic Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Neurological Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Neuroscience Research</fullName>
    </customValue>
    <customValue>
        <fullName>NIPT</fullName>
    </customValue>
    <customValue>
        <fullName>Plant Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Public Health</fullName>
    </customValue>
    <customValue>
        <fullName>Rare And Inherited Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Transplant Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <isActive>false</isActive>
        <label>NA</label>
    </customValue>
    <masterLabel>Market Sub Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Population_Genomics.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
        <default>true</default>
        <label>No</label>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <masterLabel>Population Genomics</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SegmentationSelectionController.cls
/**
 * @author Akshay Mohan 
 * @date   12-Oct-2018
 * @description    Controller class for custom component which let's user select Segmentation fields
 * Test Class Coverage For 75% coverage: TestSegmentationSelectionController
 * Test Class Coverage For 90% coverage: TestSegmentationSelectionController
 * Modification Log:
*  ------------------------------------------------------------------------------------------------------------------------------------------------------------ 
*   Developer                Date                Description                                                 
*   Akshay Mohan             12-Oct-2018         Original
*   Kushagra Desai           27-Aug-2019         DCP-28584 : Updating Account plan
*   Kushagra Desai           20-Nov-2019         INC0240834 : Update all Account Plan related to Account only if records are updated
*   Vignesh S                12-Feb-2019         DCP-31443 : Adding logic - Variable for Segmentation Validation Bypass.
*   Rahul Bishnoi            04-Feb-2021         INC0306304
*   Aman Tyagi               30-Mar-2022         CodeScan Fixes
*   Nesar Mohan              18-May-2022         DCP-53342: Added checks for ISR inclusion
*   Satya Swain              19-May-2022         DCP-53342: Refactored the methods
*   Adyasha                  01-Jun-2022         DCP-53375: Splitting of DML Transactions as added Validation in Market Segment Trigger
*   Iram Malik               14-Jul-2022         Codescan Fixes
*   Himanshu                 24-Aug-2022         DCP-56003 Added field Eligible To Estimate Consumable
*  -----------------------------------------------------------------------------------          
*   Satya Swain              30-Aug-2022         INC0420918 : Modified scenarios in checkIfReadOnlyForOpenOfferFields, getTerritoryRestrictionsForOpenOffer
*   Adyasha                  15-Sep-2022         DCP-56397: Added field Sequencing_Liquid_Bx_Cancer_Screening__c
*   Gopinath Reddy           21-Mar-2023         DCP-58180 : Added the logic on loadPage method to check country to poplulate the segmention label
 -------------------------------------------------------------------------------------------------------------------------------------------------------------          
*/
public with sharing class SegmentationSelectionController {

    // DCP-28584
    public static Boolean hasUpdate = false;
    private static final String LOG_TITLE = 'SegmentationSelectionController';
    public static final String MARKET_SEGMENT_OBJECT_NAME = 'Market_Segment__c';
    public static final String ACCOUNT_OBJECT_NAME = 'Account'; //DCP-50649
	public static final String ACCOUNT_BILLING_COUNTRY_US = 'US'; //DCP-58180
    public static final String MARKET_SEGMENT_PICKLIST_NAME = 'Market_Segment__c';
    public static final String MARKET_SUB_SEGMENT_PICKLIST_NAME = 'Market_Sub_Segment__c';
    public static final String CLINICAL_TYPE_PICKLIST_NAME = 'Clinical_Type__c';
    public static final String CUSTOMER_TYPE_PICKLIST_NAME = 'Customer_Type__c';
    public static final String CUSTOMER_SUB_TYPE_PICKLIST_NAME = 'Customer_Sub_Type__c';
    public static final String FOR_PROFIT_COMPANY_PICKLIST_NAME = 'For_Profit_Company__c'; //DCP-50649
    public static final String PURCHASESPRODUCTSSHIPPINGTOUS = 'Purchases_Products_Shipping_to_U_S__c'; //DCP-50649
    public static final String CLINICAL_ONCOLOGY_SCREENING_DX_TESTING_PICKLIST_NAME = 'Clinical_Oncology_Screening_Dx_Testing__c'; //DCP-50649
    public static final String ONCOLOGY_LAB_MANUFACTURER_COMPARISON = 'Oncology_Lab_Manufacturer_Comparison__c'; //DCP-51002
    public static final String SEQUENCING_LIQUID_BX_CANCER_SCREENING = 'Sequencing_Liquid_Bx_Cancer_Screening__c'; //DCP-56397
    public static final Set<String> SET_PROFILES_ALLOWED_TO_SUBMIT_ERP = new Set<String>{Label.SalesRepProfileName,Label.Profile_Marketing_Lead_Qualification};
    public static final Set<String> SET_SUPER_USER_PROFILES = new Set<String>{Label.ProfileSystemAdmin,Label.ProfileDataSteward,Label.Profile_Release_Manager};
    
    /* Enum to track type of Transaction as part of DCP-53375*/
    public Enum DML_TRANSACTION { IS_INSERT, IS_UPDATE, IS_DELETE, IS_DELETE_INSERT, IS_DELETE_UPDATE, IS_INSERT_UPDATE, IS_DELETE_INSERT_UPDATE }
    
    
    /*
    * Author : Akshay Mohan 
    * @Description : Wrapper class to store market segment details
    * @param: NA
    * @return: NA
    */
    public class MarketSegmentWrapper {
        String strRecordId;
        String strMarketSegment;
        List<String> lstSubSegments = new List<String>();
        Decimal decAllocation;
        Boolean booDelete=false;
        /*
        * @Author: Akshay Mohan 
        * @Description : constructor of MarketSegmentWrapper class
        * @param: NA
        * @return:NA
        */
        public MarketSegmentWrapper() { }

        /*
        * @Description : parameterized constructor of MarketSegmentWrapper class
        * @param: Market_Segment__c obj  
        */
        public MarketSegmentWrapper(Market_Segment__c obj) {
            strRecordId = obj.Id;
            strMarketSegment = obj.Market_Segment__c;
            decAllocation = obj.Percent_Allocation__c;

            if (String.isNotBlank(obj.Market_Sub_Segment__c)) {
                lstSubSegments.addAll(obj.Market_Sub_Segment__c.split(';'));                
            }
        }

        /*
        * @Description : method to get the sObject based on id
        * @param: Id idAccount
        * @return: Market_Segment__c
        */
        public Market_Segment__c getSObject(Id idAccount) {
            Market_Segment__c objSeg = getSObject();
            objSeg.Account__c = idAccount;
            return objSeg;
        }

        /*
        * @Description : method to get the sObject
        * @param: none
        * @return: Market_Segment__c
        */
        public Market_Segment__c getSObject() {
            Market_Segment__c objSeg = new Market_Segment__c(Id=strRecordId, Market_Segment__c = strMarketSegment,
                                                            Percent_Allocation__c = decAllocation);
            objSeg.Market_Sub_Segment__c ='';
            for (String strVal : lstSubSegments) {
                objSeg.Market_Sub_Segment__c+=strVal+';';
            }
            return objSeg;
        }
    }

    /*
    *  @author       : Akshay Mohan
    *  @description  : To Initialize the component
    *  @param        : String strAccountId
    *  @return       : String JSON
    */
    @AuraEnabled
    public static String loadPage(String strAccountId) {   
        ilib_LogEvent.setTitle(LOG_TITLE + '.loadPage()');
                    
        try {
            ilib_LogEvent.push(LOG_TITLE + 'reloadRecords()');
            ilib_LogEvent.message('strAccountId ::: '+strAccountId);                 
            List<MarketSegmentWrapper> lstMarketSegments = loadMarketSegments(strAccountId);            
            Map<String,Object> mapStringToPicklistValues = getMapOfStringToPicklistValues();
                    
            //load labels
            Map<String,String> labelToValue = getMapOfLabels();        
        
            Boolean booObjectHasEditPermission = Schema.sObjectType.Market_Segment__c.isUpdateable();                        
            ilib_LogEvent.message('booObjectHasEditPermission--> '+ booObjectHasEditPermission);
            

            //Only users with permission set can edit this field
            Boolean booHasEditPermission = Schema.sObjectType.Account.fields.Population_Genomics__c.isUpdateable();
            Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1][0].IsSandbox;
            String submitRequestLabel=Label.Submit_Segmentation_Request;
			String submitSegReqLabel = Label.Submit_Segment_Request; //DCP-58180
            Account objAccount = new AccountsSelector().selectLoggedInAccountForUser(strAccountId)[0];
            Boolean booDisplaySubmitButton = String.isBlank(objAccount.ERP_Customer_Id__c) ? false : true;
            if(isSandbox) {
                submitRequestLabel=Label.Submit_Segmentation_Request_Sandbox;
            }
			if(objAccount.BillingCountryCode == ACCOUNT_BILLING_COUNTRY_US){ //DCP-58180
                submitSegReqLabel = Label.Submit_Segment_Request_US;
            }
            
            Map<String,Boolean> mapAccessbilityBooleanOptions = new Map<String,Boolean>();
            
            setAccessibilityRulesForOpenOfferSection(objAccount, mapAccessbilityBooleanOptions);
        
            labelToValue.put('SegmentSubmitURL',submitRequestLabel);
            labelToValue.put('Submit',submitSegReqLabel);    //DCP-58180
			
            ilib_LogEvent.pop();

        return '{"lstMarketSegments" : '+JSON.serialize(lstMarketSegments)
            + ',"lstMarketSegmentPicklistValues" : '+JSON.serialize(mapStringToPicklistValues.get('lstMarketSegmentPicklistValues'))
            + ',"marketSegmentToSubSegment" : '+JSON.serialize(mapStringToPicklistValues.get('marketSegmentToSubSegment'))
            + ',"lstClinicalTypePicklistValues" : '+JSON.serialize(mapStringToPicklistValues.get('lstClinicalTypePicklistValues'))
            + ',"lstCustomerTypePicklistValues" : '+JSON.serialize(mapStringToPicklistValues.get('lstCustomerTypePicklistValues'))
            + ',"customerTypeToSubType" : '+JSON.serialize(mapStringToPicklistValues.get('customerTypeToSubType'))
            + ',"dummyMarketSegment" : '+JSON.serialize(new MarketSegmentWrapper())
            + ',"booHasEditPermission" : '+booHasEditPermission
            + ',"booObjectHasEditPermission" : '+booObjectHasEditPermission
            + ',"mapLabels" : '+JSON.serialize(labelToValue)
            + ',"lstPurchasesProductsShippingToUS" :'+JSON.serialize(mapStringToPicklistValues.get('lstPurchasesProductsShippingToUS'))
            + ',"lstForProfitCompany" :'+JSON.serialize(mapStringToPicklistValues.get('lstForProfitCompany'))
            + ',"lstClinicalOncologyScreeningDxTesting" :'+JSON.serialize(mapStringToPicklistValues.get('lstClinicalOncologyScreeningDxTesting'))
            + ',"lstSequencingLiquidBxCancerScreening" :'+JSON.serialize(mapStringToPicklistValues.get('lstSequencingLiquidBxCancerScreening'))//DCP-56397
            + ',"mapClinicalOncologyToSequencingLiquidBx" :'+JSON.serialize(mapStringToPicklistValues.get('mapClinicalOncologyToSequencingLiquidBx'))//DCP-56397
            + ',"lstOncologyLabManufacturerComparison" :'+JSON.serialize(mapStringToPicklistValues.get('lstOncologyLabManufacturerComparison'))
            + ',"CustomerERPID": '+objAccount.ERP_Customer_Id__c 
            + ',"objAccount": '+JSON.serialize(objAccount) 
            + ',"DisplaySubmitButton": '+booDisplaySubmitButton            
            + ',"boolComparisonCustomerFieldsFLS": '+mapAccessbilityBooleanOptions.get('boolComparisonCustomerFieldsFLS')
            + ',"conditionalReadOnlyAccessForOO": '+mapAccessbilityBooleanOptions.get('conditionalReadOnlyAccessForOO')
            + '}';

        } catch(Exception e) {
            ApexExceptions.emit(LOG_TITLE +'.loadPage()', strAccountId, e);
            throw new AuraHandledException(e.getMessage()); 
        } finally {
            ilib_LogEvent.emit();
        }
    }

    /*
    *  @author       : Akshay Mohan
    *  @description  : To reload existing records
    *  @param        : String strAccountId
    *  @return       : String JSON
    */    
    public static String reloadRecords(String strAccountId) {
        ilib_LogEvent.push(LOG_TITLE + 'reloadRecords()');
        ilib_LogEvent.message('strAccountId ::: '+strAccountId);
        
        List<MarketSegmentWrapper> lstMarketSegments = loadMarketSegments(strAccountId);

        ilib_LogEvent.pop();
        return '{"lstMarketSegments" : ' + JSON.serialize(lstMarketSegments)+'}';
    }

    /*
    *  @author       : Akshay Mohan
    *  @description  : To load Market Segments for an account
    *  @param        : String strAccountId
    *  @return       : List<MarketSegmentWrapper> wrapper records of market segments
    */
    private static List<MarketSegmentWrapper> loadMarketSegments(Id idAccount) {
        ilib_LogEvent.setTitle(LOG_TITLE + '.loadMarketSegments()');
        ilib_LogEvent.push(LOG_TITLE + 'loadMarketSegments()');
        List<MarketSegmentWrapper> lstMarketSegments = new List<MarketSegmentWrapper>();
        for (Market_Segment__c objSeg : new MarketSegmentSelector().selectByAccountId(idAccount)) {
            lstMarketSegments.add(new MarketSegmentWrapper(objSeg));
        }        

        ilib_LogEvent.message('lstMarketSegments ::: '+lstMarketSegments);    
        
        ilib_LogEvent.pop();
        ilib_LogEvent.emit();
        
        return lstMarketSegments;
    }

    /*
    *  @author       : Akshay Mohan
    *  @description  : To save Market Segments for an account
    *  @param        : strAccount Id of the Account
    *  @param        : String strJSON
    *  @return       : List<MarketSegmentWrapper> wrapper records of market segments
    */
    @AuraEnabled
    public static String saveMarketSegments(String strAccount,String strJSON) {
        ilib_LogEvent.setTitle(LOG_TITLE + '.saveMarketSegments()');
        ilib_LogEvent.push(LOG_TITLE + '.saveMarketSegments()');
        
        ilib_LogEvent.message('strAccount ::: '+strAccount);
        ilib_LogEvent.message('strJSON: '+strJSON);
        DML_TRANSACTION objTransaction = null;
        try {
            List<MarketSegmentWrapper> lstMarketSegments = (List<MarketSegmentWrapper>)JSON.deserialize(strJSON,List<MarketSegmentWrapper>.class);
            ilib_LogEvent.message('lstMarketSegments: '+lstMarketSegments);

            List<Market_Segment__c> lstMarketSegmentsToUpdate = new List<Market_Segment__c>();
            List<Market_Segment__c> lstMarketSegmentsToInsert = new List<Market_Segment__c>();
            List<Market_Segment__c> lstMarketSegmentsToDelete = new List<Market_Segment__c>();

            for (MarketSegmentWrapper wrapSeg : lstMarketSegments) {
                if (String.isBlank(wrapSeg.strRecordId)) {                                       
                    lstMarketSegmentsToInsert.add(wrapSeg.getSObject(strAccount));
                } else if (wrapSeg.booDelete) {
                    lstMarketSegmentsToDelete.add(wrapSeg.getSObject());
                } else {
                    lstMarketSegmentsToUpdate.add(wrapSeg.getSObject());
                }
            }

            objTransaction = prepareTransactionEnum(lstMarketSegmentsToInsert,lstMarketSegmentsToUpdate,lstMarketSegmentsToDelete,objTransaction);         
            performDMLForMarketSegments(lstMarketSegmentsToInsert,lstMarketSegmentsToUpdate,lstMarketSegmentsToDelete,objTransaction);

            // DCP-28584 : Update all Account Plan related to Account only if records are updated
            hasUpdate = true;
            
            ilib_LogEvent.pop();

            return reloadRecords(strAccount);   

        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage()); 
        } finally {
            ilib_LogEvent.emit();
        }
    }
    /*
    *  @author       : Adyasha
    *  @description  : prepare DML_TRANSACTION enum based on type of DML eligibility
    *  @param        : List<Market_Segment__c> lstMarketSegmentsToInsert,List<Market_Segment__c> lstMarketSegmentsToUpdate
    *  @param        : List<Market_Segment__c> lstMarketSegmentsToDelete,DML_TRANSACTION objTransaction
    *  @return       : DML_TRANSACTION
    */
    private static DML_TRANSACTION prepareTransactionEnum(List<Market_Segment__c> lstMarketSegmentsToInsert,List<Market_Segment__c> lstMarketSegmentsToUpdate, List<Market_Segment__c> lstMarketSegmentsToDelete,DML_TRANSACTION objDMLTransaction) {
        Boolean boolDeletionListEmpty = lstMarketSegmentsToDelete.isEmpty();
        Boolean boolUpdationListEmpty = lstMarketSegmentsToUpdate.isEmpty();
        Boolean boolInsertionListEmpty = lstMarketSegmentsToInsert.isEmpty();
        DML_TRANSACTION objTransaction = objDMLTransaction; 

        if(boolDeletionListEmpty) {
            if(!boolInsertionListEmpty && boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_INSERT; }
            else if(boolInsertionListEmpty && !boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_UPDATE; }
            else if(!boolInsertionListEmpty && !boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_INSERT_UPDATE; }
        } else {
            if(!boolInsertionListEmpty && !boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_DELETE_INSERT_UPDATE; }
            else if(!boolInsertionListEmpty && boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_DELETE_INSERT; }
            else if(boolInsertionListEmpty && !boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_DELETE_UPDATE; }
            else if(boolInsertionListEmpty && boolUpdationListEmpty) { objTransaction = DML_TRANSACTION.IS_DELETE; }
        }
        return objTransaction;
    }

    /*
    *  @author       : Adyasha
    *  @description  : perform DMLs for Market Segment based on Enum Values
    *  @param        : List<Market_Segment__c> lstMarketSegmentsToInsert,List<Market_Segment__c> lstMarketSegmentsToUpdate
    *  @param        : List<Market_Segment__c> lstMarketSegmentsToDelete,DML_TRANSACTION objTransaction
    *  @return       : void
    */
    private static void performDMLForMarketSegments(List<Market_Segment__c> lstMarketSegmentsToInsert,List<Market_Segment__c> lstMarketSegmentsToUpdate, List<Market_Segment__c> lstMarketSegmentsToDelete,DML_TRANSACTION objTransaction) {
        switch on objTransaction {
            when IS_DELETE_INSERT_UPDATE {
                ilib_LogEvent.message('delete, update and insert ::: ');
                MarketSegments.setFlagForAllocationEvaluation(false);
                delete lstMarketSegmentsToDelete;
                insert lstMarketSegmentsToInsert;
                MarketSegments.setFlagForAllocationEvaluation(true);
                update lstMarketSegmentsToUpdate;
            }
            when IS_DELETE_INSERT {
                ilib_LogEvent.message('delete, insert ::: ');
                MarketSegments.setFlagForAllocationEvaluation(false);
                delete lstMarketSegmentsToDelete;
                MarketSegments.setFlagForAllocationEvaluation(true);
                insert lstMarketSegmentsToInsert;
            }
            when IS_DELETE_UPDATE {
                ilib_LogEvent.message('delete, update ::: ');
                MarketSegments.setFlagForAllocationEvaluation(false);
                delete lstMarketSegmentsToDelete;
                MarketSegments.setFlagForAllocationEvaluation(true);
                update lstMarketSegmentsToUpdate;
            }
            when IS_INSERT {
                ilib_LogEvent.message('simple insert ::: ');
                MarketSegments.setFlagForAllocationEvaluation(true);
                insert lstMarketSegmentsToInsert;
            }
            when IS_UPDATE {
                ilib_LogEvent.message('simple update ::: ');
                MarketSegments.setFlagForAllocationEvaluation(true);
                update lstMarketSegmentsToUpdate;
            }
            when IS_DELETE {
                ilib_LogEvent.message('simple delete ::: ');
                MarketSegments.setFlagForAllocationEvaluation(true);
                delete lstMarketSegmentsToDelete;
            }
            when IS_INSERT_UPDATE {
                ilib_LogEvent.message('insert and update ::: ');
                MarketSegments.setFlagForAllocationEvaluation(false);
                insert lstMarketSegmentsToInsert;
                MarketSegments.setFlagForAllocationEvaluation(true);
                update lstMarketSegmentsToUpdate;
            }                
        }
        MarketSegments.setFlagForAllocationEvaluation(false);
    }
    /*
    *  @author       : Satya Swain
    *  @description  : get picklist values list for Account Picklist fields
    *  @param        : none
    *  @return       : Map<String,Object> mapStringToPicklistValues
    */
    private static Map<String,Object> getMapOfStringToPicklistValues() {
        Map<String,Object> mapStringToPicklistValues = new Map<String,Object>();
        Map<String, SObjectField> mapFields = UtilsObject.getSObjectFields(MARKET_SEGMENT_OBJECT_NAME);
        //get market segment picklist
        List<PickListValueWrapper> lstMarketSegmentPicklistValues = 
            UtilsObject.getPicklistValuesWrapper(mapFields,MARKET_SEGMENT_PICKLIST_NAME,Label.UI_Label_Segmentation_Selection_Select_Market_Segment);
        //get sub segment picklist
        Map<String, List<PickListValueWrapper>> marketSegmentToSubSegment = 
            UtilsObject.getDependentPicklistValues(mapFields,MARKET_SEGMENT_PICKLIST_NAME,MARKET_SUB_SEGMENT_PICKLIST_NAME,Label.UI_Label_Segmentation_Selection_Select_Market_Sub_Segment);

        // DCP-50649 Developer: Dushyant Srivastava
        mapFields = UtilsObject.getSObjectFields(ACCOUNT_OBJECT_NAME);
       //get clinical type
        List<PickListValueWrapper> lstClinicalTypePicklistValues = 
            UtilsObject.getPicklistValuesWrapper(mapFields,CLINICAL_TYPE_PICKLIST_NAME,Label.UI_Label_Segmentation_Selection_Select_Clinical_Type);
        //get customer Type
        List<PickListValueWrapper> lstCustomerTypePicklistValues = 
            UtilsObject.getPicklistValuesWrapper(mapFields,CUSTOMER_TYPE_PICKLIST_NAME,Label.UI_Label_Segmentation_Selection_Select_Customer_Type);
        //get customer sub Type
        Map<String, List<PickListValueWrapper>> customerTypeToSubType = 
            UtilsObject.getDependentPicklistValues(mapFields,CUSTOMER_TYPE_PICKLIST_NAME,CUSTOMER_SUB_TYPE_PICKLIST_NAME,Label.UI_Label_Segmentation_Selection_Select_Customer_Sub_Type);
        //get Purchases Products Shipping to U.S.
        List<PickListValueWrapper> lstPurchasesProductsShippingToUS = 
            UtilsObject.getPicklistValuesWrapper(mapFields,PURCHASESPRODUCTSSHIPPINGTOUS,Label.UI_Label_Comparison_Customer_Information);
        //get For-Profit Company
        List<PickListValueWrapper> lstForProfitCompany = 
            UtilsObject.getPicklistValuesWrapper(mapFields,FOR_PROFIT_COMPANY_PICKLIST_NAME,Label.UI_Label_Comparison_Customer_Information);
        //get Clinical Oncology Screening/Dx Testing
        List<PickListValueWrapper> lstClinicalOncologyScreeningDxTesting = 
            UtilsObject.getPicklistValuesWrapper(mapFields,CLINICAL_ONCOLOGY_SCREENING_DX_TESTING_PICKLIST_NAME,Label.UI_Label_Comparison_Customer_Information);
        //get Oncology Lab/Manufacturer Comparison	
        List<PickListValueWrapper> lstOncologyLabManufacturerComparison = 
            UtilsObject.getPicklistValuesWrapper(mapFields,ONCOLOGY_LAB_MANUFACTURER_COMPARISON,Label.UI_Label_Comparison_Customer_Information); 
        //get Sequencing Liquid Bx Cancer Screening --> DCP-56397
        List<PickListValueWrapper> lstSequencingLiquidBxCancerScreening = 
            UtilsObject.getPicklistValuesWrapper(mapFields,SEQUENCING_LIQUID_BX_CANCER_SCREENING,Label.UI_Label_Comparison_Customer_Information); 
        Map<String, List<PickListValueWrapper>> mapClinicalOncologyToSequencingLiquidBx = 
        UtilsObject.getDependentPicklistValues(mapFields,CLINICAL_ONCOLOGY_SCREENING_DX_TESTING_PICKLIST_NAME,SEQUENCING_LIQUID_BX_CANCER_SCREENING,Label.UI_Label_Comparison_Customer_Information);

    
        mapStringToPicklistValues.put('lstMarketSegmentPicklistValues',lstMarketSegmentPicklistValues);
        mapStringToPicklistValues.put('marketSegmentToSubSegment',marketSegmentToSubSegment);
        mapStringToPicklistValues.put('lstClinicalTypePicklistValues',lstClinicalTypePicklistValues);
        mapStringToPicklistValues.put('lstCustomerTypePicklistValues',lstCustomerTypePicklistValues);
        mapStringToPicklistValues.put('customerTypeToSubType',customerTypeToSubType);
        mapStringToPicklistValues.put('lstPurchasesProductsShippingToUS',lstPurchasesProductsShippingToUS);
        mapStringToPicklistValues.put('lstForProfitCompany',lstForProfitCompany);
        mapStringToPicklistValues.put('lstClinicalOncologyScreeningDxTesting',lstClinicalOncologyScreeningDxTesting);
        mapStringToPicklistValues.put('lstOncologyLabManufacturerComparison',lstOncologyLabManufacturerComparison);
        //DCP-56397
        mapStringToPicklistValues.put('lstSequencingLiquidBxCancerScreening',lstSequencingLiquidBxCancerScreening);
        mapStringToPicklistValues.put('mapClinicalOncologyToSequencingLiquidBx',mapClinicalOncologyToSequencingLiquidBx);
        // End of DCP-56397

        return mapStringToPicklistValues;
    }
    
    /*
    *  @author       : Satya Swain
    *  @description  : get map of all labels to be used in LWC
    *  @param        : none
    *  @return       : Map<String,String>
    */
    private static Map<String,String> getMapOfLabels() {
        Map<String,String> labelToValue = new Map<String,String>();
        labelToValue.put('UI_Label_Segmentation_Selection_Heading',Label.UI_Label_Segmentation_Selection_Heading);
        labelToValue.put('UI_Label_Segmentation_Selection_Field_Market_Segment',Label.UI_Label_Segmentation_Selection_Field_Market_Segment);
        labelToValue.put('UI_Label_Segmentation_Selection_Field_Market_Sub_Segment',Label.UI_Label_Segmentation_Selection_Field_Market_Sub_Segment);
        labelToValue.put('UI_Label_Segmentation_Selection_Field_Allocation',Label.UI_Label_Segmentation_Selection_Field_Allocation);
        labelToValue.put('UI_Label_Segmentation_Selection_Field_Clinical_Type',Label.UI_Label_Segmentation_Selection_Field_Clinical_Type);
        labelToValue.put('UI_Label_Segmentation_Selection_Field_Customer_Type',Label.UI_Label_Segmentation_Selection_Field_Customer_Type);
        labelToValue.put('UI_Label_Segmentation_Selection_Field_Customer_Sub_Type',Label.UI_Label_Segmentation_Selection_Field_Customer_Sub_Type);
        labelToValue.put('UI_Label_Segmentation_Selection_Market_Segment_Disclaimer',Label.UI_Label_Segmentation_Selection_Market_Segment_Disclaimer);
        labelToValue.put('Cancel',Label.Cancel);
        labelToValue.put('Save',Label.Save);
        labelToValue.put('UI_Error_Message_Segmentation_Selection_Allocation_Total',Label.UI_Error_Message_Segmentation_Selection_Allocation_Total);
        labelToValue.put('UI_Label_Segmentation_Selection_Additional_Heading',Label.UI_Label_Segmentation_Selection_Additional_Heading);
        labelToValue.put('UI_Button_Segmentation_Selection_Even_Split',Label.UI_Button_Segmentation_Selection_Even_Split);
        labelToValue.put('UI_Error_Message_Segmentation_Selection_Complete_Required_fields',Label.UI_Error_Message_Segmentation_Selection_Complete_Required_fields);
        labelToValue.put('UI_Error_Message_Segmentation_Selection_Submit_Error',Label.UI_Error_Message_Segmentation_Selection_Submit_Error);
        labelToValue.put('UI_Error_Message_Segmentation_Selection_Account_Locked',Label.UI_Error_Message_Segmentation_Selection_Account_Locked);
        labelToValue.put('UI_Error_Message_Segmentation_Selection_Market_Segment_Locked',Label.UI_Error_Message_Segmentation_Selection_Market_Segment_Locked);
        labelToValue.put('UI_Error_Message_ERP_Submit_Error',Label.UI_Error_Message_ERP_Submit_Error); //DCP-50649
        labelToValue.put('UI_Label_Purchases_Products_Shipping_to_U_S',Label.UI_Label_Purchases_Products_Shipping_to_U_S);
        labelToValue.put('UI_Label_Comparison_Customer_Information_US_Accounts_Only',Label.UI_Label_Comparison_Customer_Information_US_Accounts_Only);
        labelToValue.put('UI_Label_For_Profit_Company',Label.UI_Label_For_Profit_Company);
        labelToValue.put('UI_Label_Clinical_Oncology_Screening_Dx_Testing',Label.UI_Label_Clinical_Oncology_Screening_Dx_Testing);
        labelToValue.put('UI_Label_Oncology_Lab_Manufacturer_Comparison',Label.UI_Label_Oncology_Lab_Manufacturer_Comparison);
        labelToValue.put('Help_Text_Purchases_Products_Shipping_to_U_S',Account.Purchases_Products_Shipping_to_U_S__c.getDescribe().getInlineHelpText());
        labelToValue.put('Help_Text_For_Profit_Company',Account.For_Profit_Company__c.getDescribe().getInlineHelpText());
        labelToValue.put('Help_Text_Clinical_Oncology_Screening_Dx_Testing',Account.Clinical_Oncology_Screening_Dx_Testing__c.getDescribe().getInlineHelpText());
        labelToValue.put('Help_Text_Oncology_Lab_Manufacturer_Comparison',Account.Oncology_Lab_Manufacturer_Comparison__c.getDescribe().getInlineHelpText());
        labelToValue.put('UI_Error_Message_Comparison_Customer_Information_Field_Access_Error',Label.UI_Error_Message_Comparison_Customer_Information_Field_Access_Error);
        labelToValue.put('US',Label.US);
        labelToValue.put('UI_Label_Segmentation_Selection_Select_Clinical_Type',Label.UI_Label_Segmentation_Selection_Select_Clinical_Type);
        labelToValue.put('UI_Label_Segmentation_Selection_Select_Customer_Type',Label.UI_Label_Segmentation_Selection_Select_Customer_Type);
        labelToValue.put('UI_Label_Segmentation_Selection_Select_Customer_Sub_Type',Label.UI_Label_Segmentation_Selection_Select_Customer_Sub_Type);
        labelToValue.put('UI_Label_Comparison_Customer_Information',Label.UI_Label_Comparison_Customer_Information);
        labelToValue.put('AccountProspect',Label.AccountProspect);
        labelToValue.put('AccountRecordTypeDeveloperNameChannelPartnerProspect',Label.AccountRecordTypeDeveloperNameChannelPartnerProspect);
        labelToValue.put('Help_Signed_Open_Offer',Account.Signed_Open_Offer__c.getDescribe().getInlineHelpText());
        labelToValue.put('Help_Open_Offer_Comparison_Customer',Account.Open_Offer_Comparison_Customer__c.getDescribe().getInlineHelpText());
        labelToValue.put('Help_Oncology_Lab_Manufacturer_Comparison',Account.Oncology_Lab_Manufacturer_Comparison__c.getDescribe().getInlineHelpText());
        labelToValue.put('UI_Label_Open_Offer_Comparison_Customer',Label.UI_Label_Open_Offer_Comparison_Customer);
        labelToValue.put('UI_Label_Signed_Open_Offer',Label.UI_Label_Signed_Open_Offer);
        labelToValue.put('UI_Message_Segmentation_Change_Guidance',Label.UI_Message_Segmentation_Change_Guidance);
		labelToValue.put('UI_Message_Segmentation_Change_Guidance_US',Label.UI_Message_Segmentation_Change_Guidance_US);
        labelToValue.put('UI_Label_Segmentation_Add_Row',Label.UI_Label_Segmentation_Add_Row);
        labelToValue.put('UI_Label_Segmentation_Delete_Row',Label.UI_Label_Segmentation_Delete_Row);
        labelToValue.put('Help_Eligible_To_Estimate_Consumable_Spend',Account.Eligible_To_Estimate_Consumable_Spend__c.getDescribe().getInlineHelpText());
        labelToValue.put('UI_Label_Eligible_To_Estimate_Consumable_Spend',Label.UI_Label_Eligible_To_Estimate_Consumable_Spend);
        labelToValue.put('UI_Label_Segmentation_Selection_Insufficient_Access_Error',Label.UI_Label_Segmentation_Selection_Insufficient_Access_Error);
        labelToValue.put('UI_Label_Yes',Label.UI_Label_Yes); //DCP-56397
        labelToValue.put('UI_Label_Sequencing_Liquid_Bx_Cancer_Screening',Label.UI_Label_Sequencing_Liquid_Bx_Cancer_Screening); //DCP-56397
        labelToValue.put('Help_Sequencing_Liquid_Bx_Cancer_Screening',Account.Sequencing_Liquid_Bx_Cancer_Screening__c.getDescribe().getInlineHelpText()); //DCP-56397
        labelToValue.put('UI_Error_Message_Sequencing_Liquid_Bx_Cancer_Screening_Required',Label.UI_Error_Message_Sequencing_Liquid_Bx_Cancer_Screening_Required); //DCP-56397
        return labelToValue;
    }
    /*
    *  @author       : Satya Swain
    *  @description  : calculate accessibility logic for Open Offer section 
    *  @param        : none
    *  @return       : void
    */
    private static void setAccessibilityRulesForOpenOfferSection(Account objAccount, Map<String,Boolean> mapAccessbilityBooleanOptions) {
        Boolean boolComparisonCustomerFieldsFLS = false;
        Boolean conditionalReadOnlyAccessForOO = true;        
        
        List<String> accountComparisonCustomerFields = Label.Account_Comparison_Customer_Information_Fields.split(',');
        Map<String,Schema.SObjectField> mapAccountSchema = Schema.SObjectType.Account.fields.getMap();
        for (String fieldToCheck : accountComparisonCustomerFields) {
            if (!mapAccountSchema.get(fieldToCheck).getDescribe().isCreateable() && !mapAccountSchema.get(fieldToCheck).getDescribe().isUpdateable()) {
                boolComparisonCustomerFieldsFLS = true;
            }
        }

        Profile objCurrentUserProfile = new ProfilesSelector().getProfilesById(new Set<Id>{UserInfo.getProfileId()})[0];
        
        conditionalReadOnlyAccessForOO = !SET_SUPER_USER_PROFILES.contains(objCurrentUserProfile.Name);
        
        if(conditionalReadOnlyAccessForOO) {
            boolComparisonCustomerFieldsFLS = getTerritoryRestrictionsForOpenOffer(objAccount,objCurrentUserProfile, boolComparisonCustomerFieldsFLS);   
        }
                         
        mapAccessbilityBooleanOptions.put('boolComparisonCustomerFieldsFLS',boolComparisonCustomerFieldsFLS);
        mapAccessbilityBooleanOptions.put('conditionalReadOnlyAccessForOO',conditionalReadOnlyAccessForOO);       
    }

    /*
    *  @author       : Satya Swain
    *  @description  : calculate accessibility logic for Open Offer section 
    *  @param        : Account objAccount, Boolean boolComparisonCustomerFieldsFLS
    *  @return       : Boolean
    */
    public static Boolean getTerritoryRestrictionsForOpenOffer(Account objAccount, Profile objUserProfile, Boolean boolComparisonCustomerFieldsFLS) {
        
        ilib_LogEvent.setTitle(LOG_TITLE + '.getTerritoryRestrictionsForOpenOffer()');
        ilib_LogEvent.push(LOG_TITLE + '.getTerritoryRestrictionsForOpenOffer()');
        
        Map<String, Boolean> mapStringToOpenOfferFieldChecks = new Map<String, Boolean>();
        List<UserTerritory2Association> lstUTAForAllAccountHierarchyTerritories = new List<UserTerritory2Association>();
        Set<Id> setISRUserIds = new Set<Id>();
        Set<Id> setTerritoryUserIds = new Set<Id>();        
        
        Boolean boolHasRecordEditAccess = new UserRecordAccessSelector().selectUserRecordAccessByUserAndRecordId(UserInfo.getUserId(),objAccount.Id)[0]?.HasEditAccess;
        List<ObjectTerritory2Association> lstObjectTerritory2Association = new ObjectTerritory2AssociationsSelector().selectByAccountIds(new Set<Id>{objAccount.Id});
        Set<Id> setTerritoryIds = UtilsCollection.getSetOfIds(lstObjectTerritory2Association,'Territory2Id');
        
        Set<Id> setTerritoryIncludingParents = new TerritoriesSelector().getTerritoryIdsIncludingParents(setTerritoryIds);
        
        if(setTerritoryIncludingParents != null && !setTerritoryIncludingParents.isEmpty()) {
            lstUTAForAllAccountHierarchyTerritories = new UserTerritory2AssociationSelector().selectByTerritoryId(setTerritoryIncludingParents);
        }

        if(lstUTAForAllAccountHierarchyTerritories != null && !lstUTAForAllAccountHierarchyTerritories.isEmpty()) {            
            for(UserTerritory2Association objUserTerritory2Association : lstUTAForAllAccountHierarchyTerritories) {
                setTerritoryUserIds.add(objUserTerritory2Association.UserId);            
                if(String.isNotBlank(objUserTerritory2Association.RoleInTerritory2) && Label.ISRRolesETM.contains(objUserTerritory2Association.RoleInTerritory2)) {
                    setISRUserIds.add(objUserTerritory2Association.UserId);
                }
            }
        }

        Boolean boolLoggedInUserIsNotOwner = objAccount.OwnerId != UserInfo.getUserId();
        Boolean boolAccountIsProspectValidation = checkIfAccountIsVerified(objAccount);
        Boolean boolUserInCurrentTerritory = !setTerritoryUserIds.isEmpty() && setTerritoryUserIds.contains(UserInfo.getUserId()) ? true : false;
        Boolean boolUserIsISR = !setISRUserIds.isEmpty() && setISRUserIds.contains(UserInfo.getUserId()) ? true : false;               
        Boolean boolUserProfileEligibleForEdits = SET_PROFILES_ALLOWED_TO_SUBMIT_ERP.contains(objUserProfile.Name);
        Boolean boolTerritoryAssigned = lstObjectTerritory2Association != null && !lstObjectTerritory2Association.isEmpty();
        
        mapStringToOpenOfferFieldChecks.put('boolUserInCurrentTerritory',boolUserInCurrentTerritory);
        mapStringToOpenOfferFieldChecks.put('boolLoggedInUserIsNotOwner',boolLoggedInUserIsNotOwner);
        mapStringToOpenOfferFieldChecks.put('boolUserIsISR',boolUserIsISR);
        mapStringToOpenOfferFieldChecks.put('boolAccountIsProspectValidation',boolAccountIsProspectValidation);
        mapStringToOpenOfferFieldChecks.put('boolCCFieldsFLS',boolComparisonCustomerFieldsFLS);
        mapStringToOpenOfferFieldChecks.put('boolHasRecordEditAccess',boolHasRecordEditAccess);
        mapStringToOpenOfferFieldChecks.put('boolUserProfileEligibleForEdits',boolUserProfileEligibleForEdits);
        mapStringToOpenOfferFieldChecks.put('boolTerritoryAssigned',boolTerritoryAssigned);
        
        ilib_LogEvent.message('mapStringToOpenOfferFieldChecks ::: '+mapStringToOpenOfferFieldChecks);
        
        ilib_LogEvent.pop();
        ilib_LogEvent.emit();

        return checkIfReadOnlyForOpenOfferFields(mapStringToOpenOfferFieldChecks);
    }

    /*
    *  @author       : Satya Swain
    *  @description  : check if account is verified 
    *  @param        : Account objAccount
    *  @return       : Boolean
    */
    private static Boolean checkIfAccountIsVerified(Account objAccount) {
        return objAccount.Account_Status__c == Label.Account_Account_Status_Prospect_Validation || String.isNotBlank(objAccount.ERP_Customer_Id__c);
    }   

    /*
    *  @author       : Satya Swain
    *  @description  : calculate accessibility logic for Open Offer section fields 
    *  @param        : Map<String, Boolean> mapStringToOpenOfferFieldChecks
    *  @return       : Boolean
    */
    private static Boolean checkIfReadOnlyForOpenOfferFields(Map<String, Boolean> mapStringToOpenOfferFieldChecks) {
        ilib_LogEvent.push(LOG_TITLE + '.checkIfReadOnlyForOpenOfferFields()');        
        Boolean boolUserInCurrentTerritory = mapStringToOpenOfferFieldChecks.get('boolUserInCurrentTerritory');
        Boolean boolLoggedInUserIsNotOwner = mapStringToOpenOfferFieldChecks.get('boolLoggedInUserIsNotOwner');
        Boolean boolUserIsISR = mapStringToOpenOfferFieldChecks.get('boolUserIsISR');
        Boolean boolAccountIsProspectValidation = mapStringToOpenOfferFieldChecks.get('boolAccountIsProspectValidation');
        Boolean boolComparisonCustomerFieldsFLS = mapStringToOpenOfferFieldChecks.get('boolCCFieldsFLS');
        Boolean boolHasRecordEditAccess = mapStringToOpenOfferFieldChecks.get('boolHasRecordEditAccess');
        Boolean boolUserProfileEligibleForEdits = mapStringToOpenOfferFieldChecks.get('boolUserProfileEligibleForEdits');
        Boolean boolTerritoryAssigned = mapStringToOpenOfferFieldChecks.get('boolTerritoryAssigned');
        Boolean boolUserIsSameTerritoryISR = boolLoggedInUserIsNotOwner && boolUserInCurrentTerritory && boolUserIsISR;

        ilib_LogEvent.info('boolUserInCurrentTerritory ::: '+boolUserInCurrentTerritory);
        ilib_LogEvent.info('boolLoggedInUserIsNotOwner ::: '+boolLoggedInUserIsNotOwner);
        ilib_LogEvent.info('boolUserIsISR ::: '+boolUserIsISR);
        ilib_LogEvent.info('boolAccountIsProspectValidation ::: '+boolAccountIsProspectValidation);
        ilib_LogEvent.info('boolHasRecordEditAccess ::: '+boolHasRecordEditAccess);
        ilib_LogEvent.info('boolUserProfileEligibleForEdits ::: '+boolUserProfileEligibleForEdits);
        ilib_LogEvent.info('boolUserIsSameTerritoryISR ::: '+boolUserIsSameTerritoryISR);
        
        
        if(!boolHasRecordEditAccess) {
            boolComparisonCustomerFieldsFLS = true;
        }

        if(boolTerritoryAssigned) {
            if(boolLoggedInUserIsNotOwner && !boolUserInCurrentTerritory) {
                boolComparisonCustomerFieldsFLS = true;
            } else if(boolLoggedInUserIsNotOwner && boolUserInCurrentTerritory && (boolUserIsISR || boolUserProfileEligibleForEdits)) {
                boolComparisonCustomerFieldsFLS = false;
            } else if(!boolLoggedInUserIsNotOwner && (boolUserIsISR || boolUserProfileEligibleForEdits)) {
                boolComparisonCustomerFieldsFLS = false;
            }
        } else {
            if(!boolLoggedInUserIsNotOwner && boolUserProfileEligibleForEdits) {
                boolComparisonCustomerFieldsFLS = false;
            } else if(boolLoggedInUserIsNotOwner) {
                boolComparisonCustomerFieldsFLS = true;
            }
        }

        if(boolAccountIsProspectValidation) {
            boolComparisonCustomerFieldsFLS = true;
        }
        
        ilib_LogEvent.info('exiting checkIfReadOnlyForOpenOfferFields boolComparisonCustomerFieldsFLS ::: '+boolComparisonCustomerFieldsFLS);
        ilib_LogEvent.pop();
        return boolComparisonCustomerFieldsFLS;
    }
}