force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/Account_Sales_Area__c.object-meta.xml
<CustomObject>
    <description>Stores the ERP (SAP) system specific information such as Sales Organization, Distribution Channel, Division and Company Code for the related account. Contains inco terms, pricegroup, pricelist type and terms of payment assigned to the given account</description>
    <label>Account Sales Area</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Account Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Area</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Sales_Area__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to Account.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <description>Field to store Contract Number.</description>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Customer_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master_Data__c</fullName>
    <description>Lookup to Customer Master Data.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master Data</label>
    <referenceTo>Customer_Master_Data__c</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Field to store Price Group.</description>
    <label>Price Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>As part of DCP 10312 to store the price list.</description>
    <label>Price List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_List_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type__c</fullName>
    <description>Field to store Price List Type.</description>
    <label>Price List Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/Apttus__AgreementLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to Account(Sold To)</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreement Line Items (Account)</relationshipLabel>
    <relationshipName>Agreement_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__ItemSequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__ItemSequence__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The sequence of items belonging to a line</description>
    <label>Item Sequence</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__LineNumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__LineNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The line number</description>
    <label>Line Number</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount applied to Line Item</description>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount applied like % Discount, Fixed Price etc.</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <description>Specifies type of line added. Ex: Material Group 1</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Material Group 1</fullName>
            </value>
            <value>
                <fullName>Price Group - Material</fullName>
            </value>
            <value>
                <fullName>Price Group - Material Group 1</fullName>
            </value>
            <value>
                <fullName>Quota</fullName>
            </value>
            <value>
                <fullName>UC - Material</fullName>
            </value>
            <value>
                <fullName>UC - Material Group 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Represents Price Group of Line Item</description>
    <label>Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Button to view Price Group</description>
    <label>Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/CLM_ProfileValidation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CLM_ProfileValidation</label>
</CustomObject>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Channel_Partner_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Agreement__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Channel Partner Agreement.</description>
    <defaultValue>false</defaultValue>
    <label>Channel Partner Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Master_Customer_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Agreement__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Master Customer Agreement.</description>
    <defaultValue>false</defaultValue>
    <label>Master Customer Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Master_Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Service_Agreement__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Master Service Agreement.</description>
    <defaultValue>false</defaultValue>
    <label>Master Service Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Negotiated_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Negotiated_Terms_and_Conditions__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Negotiated Terms and Conditions</description>
    <defaultValue>false</defaultValue>
    <label>Negotiated Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Standing_Quote__c.field-meta.xml
<CustomField>
    <fullName>Standing_Quote__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Standing Quote.</description>
    <defaultValue>false</defaultValue>
    <label>Standing Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Tender__c.field-meta.xml
<CustomField>
    <fullName>Tender__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Tender.</description>
    <defaultValue>false</defaultValue>
    <label>Tender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/Customer_Master_Data__c.object-meta.xml
<CustomObject>
    <description>Stores master data for all accounts groups that are used in the system&apos;s workflow and processes. Source of majority of the data is ERP (SAP) system</description>
    <label>Customer Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Field to store Account Id</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Master Data</relationshipLabel>
    <relationshipName>Customer_Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Field to store Account Group</description>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Locker</fullName>
            </value>
            <value>
                <fullName>Trunk</fullName>
            </value>
            <value>
                <fullName>Importer Of Record</fullName>
            </value>
            <value>
                <fullName>Customer Hierarchy</fullName>
            </value>
            <value>
                <fullName>Partner Stock</fullName>
            </value>
            <value>
                <fullName>Parts Locker</fullName>
                <isActive>false</isActive>
                <label>Parts Locker</label>
            </value>
            <value>
                <fullName>Trunk Stock</fullName>
                <isActive>false</isActive>
                <label>Trunk Stock</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Field to store Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country code of the country. Used for backed calculations like sales area.</description>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>Field to store ERP Customer Id</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ERP Customer Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestApttusAgreementLineItemViewerCntl.cls
/**
 *    @author Rahul Bishnoi
 *    @date   10-July-2020
 *    @description  Test class for ApttusAgreementLineItemViewerController
 *    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------------
*    Developer                      Date                Description
*    Rahul Bishnoi                 10-July-2020         Initial Version
*    Prem Ranjan                   04 May 2022          CodeScan Fix (APEX) Unused Local Variable 
*	 Maruthi						27-June-2022		Updated testgetRecords
*    Vishal Reddy                  30-Sep-2022          Created testExceptions to increase code coverage
*    Arif,Dalali                   28-Nov-2022          POL-57: Update APJ and EMEA References to AMEA and Europe respectively
*    ------------------------------------------------------------------------------------------------------------------------------------------------

 *
 */
@isTest
public with sharing class TestApttusAgreementLineItemViewerCntl {
    public static final string STRLINETYPEMATERIALGROUP = 'Material Group 1';
    public static final string STRDISCOUNTTYPE = '% Discount';
    public static final string STRPAGEREFERENCE = 'Page.PreviewSubmitApprovals';
    public static final string STRAPPROVER = 'Test Approver';

    @testSetup
    static void setupData() {
        Account acc = TestDataAccount.initAccount();
        acc.ERP_Customer_Id__c = '234567';
        acc.Account_Group__c = 'Distributor';
        
        Account acc2 = TestDataAccount.initAccount();
        acc2.ERP_Customer_Id__c = '183456';
        insert new List<Account> { acc, acc2 };

        Customer_Master_Data__c objCMD1 = new Customer_Master_Data__c(Name='CMD1',Country__c='Hong Kong',Country_Code__c='HK'),
                                objCMD2 = new Customer_Master_Data__c(Name='CMD2',Country__c='Hong Kong',Country_Code__c='HK');
        objCMD1.ERP_Customer_Id__c = '234567';
        objCMD2.ERP_Customer_Id__c = '183456';
        insert new List<Customer_Master_Data__c> {objCMD1, objCMD2};

        Account_Sales_Area__c acc1SalesArea = TestDataAccountSalesArea.getAccountSalesArea('HK01', '01', '178', '00', false);
        acc1SalesArea.Account__c = acc.Id;
        acc1SalesArea.Price_List_Type__c = '06';
        acc1SalesArea.CurrencyIsoCode = 'USD';
        acc1SalesArea.Price_List__c = '01-AMEA-USD'; //POL-57
        acc1SalesArea.Contract_Number__c = '123456_HK010100';
        acc1SalesArea.Price_Group__c = 'TXDR';
        
        Account_Sales_Area__c acc2SalesArea = TestDataAccountSalesArea.getAccountSalesArea('HK01', '02', '179', '00', false);
        acc2SalesArea.Account__c = acc2.Id;
        acc2SalesArea.Price_List_Type__c = '06';
        acc2SalesArea.CurrencyIsoCode = 'USD';
        acc2SalesArea.Price_List__c = '01-AMEA-USD'; //POL-57
        acc2SalesArea.Contract_Number__c ='567890_US010100';
        insert new List<Account_Sales_Area__c>{ acc1SalesArea, acc2SalesArea };
        
        Contact con = TestDataPerson.initContact(acc.Id);
        Contact con2 = TestDataPerson.initContact(acc.Id);
        insert new List<Contact> { con, con2 };

        CLM_ProfileValidation__c profilevalidation = new CLM_ProfileValidation__c(SetupOwnerId=userinfo.getProfileId(),Channel_Partner_Agreement__c=true,Master_Customer_Agreement__c=true,Master_Service_Agreement__c=true,Negotiated_Terms_and_Conditions__c=true,Standing_Quote__c=true,Tender__c=true);
        insert profilevalidation;
        
        Id recTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Channel Partner Agreement').getRecordTypeId();
        Apttus__APTS_Agreement__c oAgreement1 = TestDataAgreement.initAgreements('Test Agreement - Price Group', acc.id);
        //oAgreement1.Customer_Discount_Level__c = 'Price Group';
        oAgreement1.recordTypeId=recTypeId;
        insert oAgreement1;
        
        
        Apttus__AgreementLineItem__c oAgreementLI1 = TestDataAgreement.initAgreementsLineItem(oAgreement1.id);
        oAgreementLI1.Line_Type__c = STRLINETYPEMATERIALGROUP;
        oAgreementLI1.Apttus_CMConfig__LineNumber__c = 4;
        oAgreementLI1.Apttus_CMConfig__ItemSequence__c = 4;
        oAgreementLI1.Discount_Type__c = STRDISCOUNTTYPE;
        oAgreementLI1.Discount__c=12.23;
        oAgreementLI1.Apttus_CMConfig__StartDate__c = system.today()+5;
        oAgreementLI1.Apttus_CMConfig__EndDate__c = system.today()+28;
        oAgreementLI1.Material_Group_1__c='AIM';
        oAgreementLI1.CurrencyIsoCode = 'USD';
        oAgreementLI1.Distribution_Channel__c = '02';
        oAgreementLI1.Customer_ERP_Number__c = '234567';
        oAgreementLI1.Sales_Org__c = 'US01';
        insert oAgreementLI1;
            
        
    }
    /*
    *@author: Rahul Bishnoi
    *@Desc: Test method to check getRecords
    */
    @isTest
    static void testgetRecords() {
        Apttus__APTS_Agreement__c objAgreement = [select id,Apttus__FF_Agreement_Number__c from Apttus__APTS_Agreement__c where Name = 'Test Agreement - Price Group'];
        Test.starttest();        
        try{
            ApttusAgreementLineItemViewerController.getFilterRecords(objAgreement.id,'test',Integer.valueof(Label.LabelViewLinesLimit));
            String jsonObj = ApttusAgreementLineItemViewerController.getRecords(objAgreement.id,Integer.valueof(Label.LabelViewLinesLimit));
            AgreementLineWrapper listTemp = new AgreementLineWrapper();
            listTemp = (AgreementLineWrapper) System.JSON.deserialize(jsonObj, AgreementLineWrapper.class);		
            System.assert(!(listTemp.listAgreementLineItems.isEmpty()),'Agreement Lines Are Fetched');
        }catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }
        Test.stoptest();
    }

    /*
    *@author: Maruthi B
    *@Desc: Wrapper calss to get records for getRecords method for assert.
    */
    public class AgreementLineWrapper
    {
        public List<ApttusAgreementLineItemViewerController.agreementLineWrapper> listAgreementLineItems;
        String hasMoreLines;
    }
    /*
    *@author: Rahul Bishnoi
    *@Desc: Test method to check getAgreement
    */

    @isTest
    static void testgetAgreement() {
        Apttus__APTS_Agreement__c objAgreement = [select id,Apttus__FF_Agreement_Number__c from Apttus__APTS_Agreement__c where Name = 'Test Agreement - Price Group'];
        Test.starttest();
        ApttusAgreementLineItemViewerController.checkSessionCache(objAgreement.id);
        Apttus__APTS_Agreement__c agrmt = ApttusAgreementLineItemViewerController.getAgreement();
        System.assertEquals(agrmt.id, objAgreement.id);
        Test.stoptest();
    }
    /*
    *@author: Rahul Bishnoi
    *@Desc: Test method to check getAgreementAura
    */

    @isTest
    static void testgetAgreementAura() {
        Apttus__APTS_Agreement__c objAgreement = [select id,Apttus__FF_Agreement_Number__c from Apttus__APTS_Agreement__c where Name = 'Test Agreement - Price Group'];
        Test.starttest();
        Apttus__APTS_Agreement__c agrmt = ApttusAgreementLineItemViewerController.getAgreementAura(objAgreement.id);
        System.assertEquals(agrmt.id, objAgreement.id);
        Test.stoptest();
    }
    /*
    *@author: Vishal Reddy
    *@Desc: Test method to create exceptions
    */

    @isTest
    static void testExceptions() {
        Apttus__APTS_Agreement__c objAgreement = [select id,Apttus__FF_Agreement_Number__c from Apttus__APTS_Agreement__c where Name = 'Test Agreement - Price Group'];
        Test.starttest();
        try{
            ApttusAgreementLineItemViewerController.catchExceptionGetFilterRecords = true;
            ApttusAgreementLineItemViewerController.getFilterRecords(objAgreement.id,'test',Integer.valueof(Label.LabelViewLinesLimit));		
            System.assert(!ApttusAgreementLineItemViewerController.catchExceptionGetFilterRecords, 'catchExceptionFilterRecords is still true');
        }
        catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }

        try{
            ApttusAgreementLineItemViewerController.catchExceptionFilterLogic = true;      
            ApttusAgreementLineItemViewerController.getFilterRecords(objAgreement.id,'test',Integer.valueof(Label.LabelViewLinesLimit));		
            //System.assert(!(listTemp.listAgreementLineItems.isEmpty()),'Agreement Lines Are Fetched'); no need for system.assert as this method raises exceptions
        }
        catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }
        
        try{
            ApttusAgreementLineItemViewerController.catchExceptiongetRecords = true;
            ApttusAgreementLineItemViewerController.getRecords(objAgreement.id,Integer.valueof(Label.LabelViewLinesLimit));
        }
        catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }

        try{
            ApttusAgreementLineItemViewerController.catchExceptionCheckSessionCache = true;
            ApttusAgreementLineItemViewerController.checkSessionCache(objAgreement.id);
        }
        catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }

        try{
            ApttusAgreementLineItemViewerController.catchExceptionGetAgreement = true;
            ApttusAgreementLineItemViewerController.getAgreement();
        }
        catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }
        
        try{
            ApttusAgreementLineItemViewerController.catchExceptionGetAgreementAura = true;
            ApttusAgreementLineItemViewerController.getAgreementAura(objAgreement.id);
        }
        catch(Exception e){
            System.debug('error message is : '+e.getMessage());
        }

        Test.stoptest();
    }

}