force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <description>Flag to determine active account</description>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact.FirstName +&apos; &apos; + Contact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
    <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Cases Reported From This Site</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <description>Field to track Active ServiceMax</description>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <description>Context information from transactions where unhandled errors occurred, used to aid troubleshooting</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Exception Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>From a checked exception</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/SVMXC__RMA_Shipment_Line__c.object-meta.xml
<CustomObject>
    <description>ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both. Parts Order Line lists parts returned or shipped.</description>
    <label>Parts Order Line</label>
    <nameField>
        <displayFormat>LN-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <description>To capture the requested delivery date of part order line</description>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/SVMXC__RMA_Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__RMA_Shipment_Order__c</fullName>
    <description>RMA/Shipment number. Is a lookup to an existing RMA/Shipment record in ServiceMax</description>
    <inlineHelpText>RMA/Shipment number. Is a lookup to an existing RMA/Shipment record in ServiceMax</inlineHelpText>
    <label>Parts Order</label>
    <referenceTo>SVMXC__RMA_Shipment_Order__c</referenceTo>
    <relationshipName>RMA_Shipment_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/SVMXC__Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the service engineer associated with this RMA/shipment order. Is a lookup to an existing salesforce user record</description>
    <inlineHelpText>Name of the service engineer associated with this RMA/shipment order. Is a lookup to an existing salesforce user record</inlineHelpText>
    <label>Service Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RMA_Shipment_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/SVMXC__RMA_Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Parts Order is an object to handle parts logistics. With record type RMA, it is a document that authorizes products or parts to be returned to the manufacturer/repair center/warehouse. With record type Shipment,  it is an internal document that authorizes products or parts to be shipped to a customer or field inventory location. ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both.</description>
    <label>Parts Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>Enter name of lab or department. Defaulted from Work Order.</description>
    <label>Contact Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone__c</fullName>
    <description>Enter name of contact the shipment should be addressed to. Defaulted from Work Order.</description>
    <label>Contact Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/ERP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Sales_Order_Number__c</fullName>
    <description>To be populated from SAP</description>
    <externalId>true</externalId>
    <label>ERP Sales Order #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture the requester (User) of the parts</description>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Parts_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <description>To capture the requested delivery date of part order line.</description>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Shipping_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To Populate the Shipping Location.</description>
    <label>Shipping Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SVMXC__Site__c.Type__c</field>
            <operation>notEqual</operation>
            <value>Bill To, Payer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Parts Orders (Shipping Location)</relationshipLabel>
    <relationshipName>Parts_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account from/to which this RMA/shipment is made. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Company from/to which this RMA/shipment is made. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parts Orders (Account)</relationshipLabel>
    <relationshipName>RMA_Shipment_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the internal/customer site to which the products are shipped. Is a lookup to an existing site record in ServiceMax</description>
    <inlineHelpText>Name of the internal/customer site to which the products are shipped. Is a lookup to an existing site record in ServiceMax. Choose an existing site OR enter address details.</inlineHelpText>
    <label>To Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Parts Orders (Destination Location)</relationshipLabel>
    <relationshipName>RMA_Shipment_Order_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Order_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Type__c</fullName>
    <description>Order Type</description>
    <inlineHelpText>Choose the Order type</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Advance Exchange</fullName>
            </value>
            <value>
                <fullName>Replenishment</fullName>
            </value>
            <value>
                <fullName>Customer Owned</fullName>
            </value>
            <value>
                <fullName>Loaner</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>Stock Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the service engineer associated with this RMA/shipment order. Is a lookup to an existing salesforce user record</description>
    <inlineHelpText>Name of the service engineer associated with this RMA/shipment order. Is a lookup to an existing salesforce user record</inlineHelpText>
    <label>Service Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RMA_Shipment_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Service Engineer associated with the site.</description>
    <inlineHelpText>Name of the Service Engineer associated with the site.</inlineHelpText>
    <label>Service Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Stocking_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Stocking_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</description>
    <inlineHelpText>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</inlineHelpText>
    <label>Stocking Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>To capture the type of location</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trunk</fullName>
            </value>
            <value>
                <fullName>Locker</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
            <value>
                <fullName>Partner Stock</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Importer Of Record</fullName>
            </value>
            <value>
                <fullName>Customer Hierarchy</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
                <isActive>false</isActive>
                <label>Temporary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPartsOrderApproval.cls
/***************************************************************************************************************************************
* @Author:  Nidhi Hegde
* @Date:    05-Oct-2023 
* @Name :   TestPartsOrderApproval
* @Description: For Covering Parts_Order_Notify_Primary_Secondary_FSE_for_review_and_Approval_of_Parts_Order Flow
* ----------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
* ---------------------------------------------------------------------------------------------------------------------------------------
* Nidhi Hegde             05-Oct-2023        Initial Version (CMCM-3826)
******************************************************************************************************************************************************************/

@IsTest(SeeAllData=true)
public class TestPartsOrderApproval {
    public static final string STRING_PARTS_ORDER_LINE_NON_BILLABLE_REASON = 'Goodwill';
    public static final string STRING_PARTS_ORDER_LINE_STATUS = 'Open';
    public static final string STRING_PRODUCT_CODE = 'Test 123';
    public static final string STRING_PRODUCT_CODE1 = 'Test 1234';
    public static final string STRING_PRODUCT_INSTRUMENT_CLASS = 'Instrument';
    public static final string STRING_PRODUCT_NAME = 'Test Product VM';
	public static final string STRING_PRODUCT_MATERIAL_CLASS = 'Consumable';
   
   /**
    *  @author Nidhi Hegde
   * This test method is responsible for testing the order approval workflow.
  */    
    @isTest
    public static void testOrderApproval() {
        Account objAccount = TestDataAccount.getNewAccount();
        objAccount.Account_Group__c = 'Sold To';
        update objAccount;
        
        Contact objContact = TestDataContact.getNewContact(objAccount);
        
        Case objCase = TestDataCase.initServiceRequestCase(objContact);
        insert objCase;
        
        Profile proId = [SELECT Id FROM Profile WHERE Name = 'Channel Partner Service' LIMIT 1];
        User u = TestDataUser.initPartnerUser(proId.id,objContact.Id);
        insert u;
        
        User manager1 = TestDataFieldService.createUser('Field Service', true);
        User manager2 = TestDataFieldService.createUser('Field Service', false);
        manager2.ManagerId = manager1.id;
        manager2.UserName = 'Second'+ manager2.UserName;
        insert manager2;
        User sapUsr = TestDataFieldService.createUser('Integration SAP Service', false);
        sapUsr.ManagerId = manager2.Id;
        insert sapUsr;
        
        SVMXC__Site__c location = TestDataFieldService.createLocation('ServiceLoc1', 'Stringing street New York', 'USA', '43527', 'USD');
             
        SVMXC__Site__c shippingLocation = new SVMXC__Site__c(
            Name = 'testStockingLocation',
            CurrencyIsoCode = 'USD',
            SVMXC__Stocking_Location__c = true,
            SVMX_PS_Active__c = true,
            SVMXC__Service_Engineer__c=sapUsr.id,
            Type__c = 'Trunk'
        );
        list < SVMXC__Site__c > locList = new list < SVMXC__Site__c > ();
        locList.add(location);
        locList.add(shippingLocation);
        insert locList;
        
        SVMXC__RMA_Shipment_Order__c partOrder = TestDataFieldService.createPartOrder('RMA', objCase.Id, 'Open');
        partOrder.ERP_Sales_Order_Number__c = '1765';
        partOrder.SVMXC__Company__c = objAccount.id;
        partOrder.Contact_Name__c = 'Test';
        partOrder.Contact_Phone__c = 'Test';
        partOrder.SVMXC__Order_Type__c = 'Shipment';
        partOrder.SVMXC__Destination_Location__c = locList[0].Id;
        partOrder.Shipping_Location__c = locList[1].Id;
        partOrder.Requested_Delivery_Date__c = date.today() + 2;
        partOrder.Requested_By__c = u.Id;
        insert partOrder;
        
        List<Product2> lstProducts = new List<Product2>();
        Product2 objProduct = TestDataMaster.initProduct(STRING_PRODUCT_CODE);
        objProduct.Service_Product_Type__c = 'Spare';
        lstProducts.add(objProduct);
        Product2 objProduct1 = TestDataMaster.initProduct(STRING_PRODUCT_CODE1);
        objProduct1.Service_Product_Type__c = STRING_PRODUCT_MATERIAL_CLASS;
        lstProducts.add(objProduct1);
        
        insert lstProducts;
        SVMXC__Site__c objLocationRec = new SVMXC__Site__c(Name = 'test');
        insert objLocationRec;
        list <SVMXC__RMA_Shipment_Line__c > objPartsOrderLineList = new list <SVMXC__RMA_Shipment_Line__c > ();
		Id shipmentRecordTypeId = Schema.SObjectType.SVMXC__RMA_Shipment_Line__c.getRecordTypeInfosByName().get('Shipment').getRecordTypeId();        
        SVMXC__RMA_Shipment_Line__c objPartsOrderLine1 = new SVMXC__RMA_Shipment_Line__c();
        objPartsOrderLine1.SVMXC__RMA_Shipment_Order__c = partOrder.Id;
        objPartsOrderLine1.SVMXC__Product__c = lstProducts[0].Id;
        objPartsOrderLine1.From_Location__c = objLocationRec.id;
        objPartsOrderLine1.RecordTypeId = shipmentRecordTypeId; 
        objPartsOrderLine1.Requested_Delivery_Date__c = system.today();
        objPartsOrderLine1.SVMXC__Line_Status__c = 'Open';
        objPartsOrderLineList.add(objPartsOrderLine1);
        SVMXC__RMA_Shipment_Line__c objPartsOrderLine = TestDataFieldService.createPartsOrderLines(partOrder.Id);
        objPartsOrderLine.SVMXC__Product__c = lstProducts[1].Id;
        objPartsOrderLine.RecordTypeId = shipmentRecordTypeId; 
        objPartsOrderLine.Reason__c = STRING_PARTS_ORDER_LINE_NON_BILLABLE_REASON;
        objPartsOrderLine.SVMXC__Line_Status__c = 'Open';
        objPartsOrderLine.Requested_Delivery_Date__c = system.today();
        objPartsOrderLineList.add(objPartsOrderLine);
        
        insert objPartsOrderLineList;
        Test.startTest();
        Map<String, Object> inputs = new Map<String, Object>();
        inputs.put('PartsOrderID',partOrder.Id);    
        Flow.Interview flw = new Flow.Interview.Parts_Order_Notify_Primary_Secondary_FSE_for_review_and_Approval_of_Parts_Order(inputs);
        flw.start();
        SVMXC__RMA_Shipment_Order__c partsOrderList = (SVMXC__RMA_Shipment_Order__c)flw.getVariableValue('ObjPartsOrder');  
        User usrList = (User)flw.getVariableValue('PartsOrderUser');
        String contactId = (String)flw.getVariableValue('varContactId');
        String partnerEmail = (String)flw.getVariableValue('ListPartnerUserEmails');
        Assert.isTrue (partsOrderList != null);
        Assert.isTrue (usrList != null);
        Assert.isTrue (ContactId != null);
        Assert.isTrue (partnerEmail != null);
        Test.stopTest();
        Integer emailCount = Limits.getLimitEmailInvocations();
        Assert.isTrue(emailCount != null, 'email not sent');
    }
    /**
    *  @author Nidhi Hegde
    * This test method is responsible for testing the handling of exceptions during the parts order workflow. 
   */
    @isTest
    public static void testPartsOrderException() {
        Profile proId = [SELECT Id FROM Profile WHERE Name = 'Channel Partner Service' LIMIT 1];
        Map<String, Object> inputs = new Map<String, Object>();
        inputs.put('PartsOrderID',proId.Id);    
        Flow.Interview flw = new Flow.Interview.Parts_Order_Notify_Primary_Secondary_FSE_for_review_and_Approval_of_Parts_Order(inputs);
        Test.startTest();
        flw.start();
        Test.stopTest();
        List<Exception_Log__c> logList = [SELECT Id, Name, Message__c, Related_Record__c, Source__c, Type__c, Workstream__c, Line_Number__c FROM Exception_Log__c LIMIT 1];
        Assert.isTrue(!logList.isEmpty());
    }
}