force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <description>Case evaluation.</description>
    <inlineHelpText>Document the process taken to verify the customer problem statement, steps taken to evaluate/assess the issue and details on how cause was identified</inlineHelpText>
    <label>Evaluation</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Verification_Result__c.field-meta.xml
<CustomField>
    <fullName>Verification_Result__c</fullName>
    <description>Manual entry, Technician&apos;s verification result after the case completion.</description>
    <inlineHelpText>Specify how Illumina confirmed the issue has been resolved</inlineHelpText>
    <label>Verification Result</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <description>Captures the Evaluation done by Service users to complete a Work Order. Manually updated by users.</description>
    <inlineHelpText>Document the process taken to verify the customer problem statement, steps taken to evaluate/assess the issue and details on how cause was identified</inlineHelpText>
    <label>Evaluation</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Is_Service_Report_Generated__c.field-meta.xml
<CustomField>
    <fullName>Is_Service_Report_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify whether the service report is generated for the work order or not</description>
    <label>Is Service Report Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/No_Calibrated_Tools_Used__c.field-meta.xml
<CustomField>
    <fullName>No_Calibrated_Tools_Used__c</fullName>
    <description>Updated manually by users at the time of Work Order debrief/completion to indicate that no calibrated tools were used for the Work Order.</description>
    <defaultValue>false</defaultValue>
    <label>No Calibrated Tools Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>US: DCP-672
Manual entry, Purchase Order Number to uniquely identify the purchase order from external systems.</description>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Record_Created_from_SFM__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_from_SFM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-256
To check whether the record is created from SFM.
It is checked through SFM transaction when ever a record is created through SFM Button</description>
    <label>Record Created from SFM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Status__c</fullName>
    <description>Current status of the service order</description>
    <inlineHelpText>Current status of the service order</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
                <default>true</default>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assignment Accepted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Technician Onsite</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Revisit Required</fullName>
            </value>
            <value>
                <fullName>Estimate Approved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Technician Acknowledged</fullName>
            </value>
            <value>
                <fullName>Technician Enroute</fullName>
            </value>
            <value>
                <fullName>Work Complete</fullName>
            </value>
            <value>
                <fullName>Requires Revisit</fullName>
            </value>
            <value>
                <fullName>Reopen Requested</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Closed-Duplicate</fullName>
            </value>
            <value>
                <fullName>Awaiting Parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Type__c</fullName>
    <description>Type of service order: Field Service, Depot repair etc.</description>
    <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Depot Repair</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
                <default>true</default>
                <label>Field Service</label>
            </value>
            <value>
                <fullName>Propel</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Service Activities</fullName>
            </value>
            <value>
                <fullName>Remote Support</fullName>
            </value>
            <value>
                <fullName>Depot Service</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Dedicated Onsite Activities</fullName>
            </value>
            <value>
                <fullName>Sales Support Activity</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Cycle Count</fullName>
            </value>
            <value>
                <fullName>Clarity LIMS</fullName>
            </value>
            <value>
                <fullName>Channel Partner Replenishment</fullName>
            </value>
            <value>
                <fullName>Return Scrap Decommission</fullName>
            </value>
            <value>
                <fullName>Billable Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Work_Performed__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Work_Performed__c</fullName>
    <description>Details of work performed to address/resolve the service order</description>
    <inlineHelpText>Specify work done to directly address/resolve the issue</inlineHelpText>
    <label>Work Performed</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Verification_Result__c.field-meta.xml
<CustomField>
    <fullName>Verification_Result__c</fullName>
    <description>US: DCP-672
Manual entry, Technician&apos;s verification result after the Work Order completion.</description>
    <inlineHelpText>Specify how Illumina  confirmed the issue has been resolved</inlineHelpText>
    <label>Verification Result</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestAutoCloseWOHelper.cls
/**
*    @author Ritika
*    @date  
*    @description    Test class for AutoCloseWOHelper
*    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------
*         Developer               Date                Description
*    ---------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public with sharing class TestAutoCloseWOHelper {
    public static final String STRING_WO_RECORDTYPE = 'Field Service';
    public static final String STRING_WO_ORDER_TYPE = 'Service Activities';
    /**
    *   @author Ritika  
    **/
    @isTest
    public static void testWOClosure(){
        Account acc = TestDataAccount.getAccount('Test Acc', 'USD');
        acc.Account_Group__c='Distributor';
        insert acc;
        
        //insert contact
        Contact con = TestDataPerson.getNewContact(acc.Id);
                
        //insert case        
        Case cs = TestDataCase.initServiceRequestCase(con);
        insert cs;

        SVMXC__Service_Order__c workOrder = TestDataFieldService.createWorkOrder(STRING_WO_RECORDTYPE, cs.Id, 'Initiated');
        workOrder.SVMXC__Order_Type__c=STRING_WO_ORDER_TYPE;
        workOrder.Is_Service_Report_Generated__c=true;
        workOrder.Record_Created_from_SFM__c=true;
        workOrder.Evaluation__c='Test';
        workOrder.SVMXC__Work_Performed__c='Test';
        workOrder.Verification_Result__c='Test'; 
        insert workOrder;
        
        Test.startTest();
        workOrder.PO_Number__c='12';
        workOrder.SVMXC__Order_Status__c = 'Completed';
        workOrder.No_Calibrated_Tools_Used__c = true;
        update workOrder;
        Test.getEventBus().deliver();
        Test.stopTest();
        SVMXC__Service_Order__c resultWorkOrder = [Select id,SVMXC__Order_Status__c from SVMXC__Service_Order__c where Id = :workOrder.Id];
        System.assertEquals(resultWorkOrder.SVMXC__Order_Status__c, 'Closed');
    }
}