force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Awareness_Date_Difference_Reason__c.field-meta.xml
<CustomField>
    <fullName>Awareness_Date_Difference_Reason__c</fullName>
    <description>Reason for Awareness Date Difference is needed when Date of Awareness and Case Created Date has difference.</description>
    <inlineHelpText>Filled in when the Date of Issue Awareness Date doesn’t match the Case Creation Date.</inlineHelpText>
    <label>Awareness Date Difference Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Updated information presented by customer</fullName>
            </value>
            <value>
                <fullName>Logistical delay</fullName>
            </value>
            <value>
                <fullName>Automatic case creation during off hours</fullName>
            </value>
            <value>
                <fullName>Other: See Description and Evaluation</fullName>
                <label>Other: See Case Description Field and Work Order Notes Field</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Date_of_Issue_Awareness__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_Awareness__c</fullName>
    <description>Date of issue awareness</description>
    <inlineHelpText>Date Illumina became aware of a Business Issue</inlineHelpText>
    <label>Date of Issue Awareness</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Elevation_Category__c.field-meta.xml
<CustomField>
    <fullName>Elevation_Category__c</fullName>
    <description>The dependent field from work order type for elevation case</description>
    <label>Elevation Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Work_Order_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Management Elevation</fullName>
            </value>
            <value>
                <fullName>Hot Site Elevation</fullName>
            </value>
            <value>
                <fullName>Standard Technical Elevation Regional</fullName>
            </value>
            <value>
                <fullName>Non Standard Technical Elevation Global/HQ</fullName>
            </value>
            <value>
                <fullName>Project Elevation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Elevation_Manager__c.field-meta.xml
<CustomField>
    <fullName>Elevation_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select a user as an elevation manager</description>
<!--QACM-40-->
    <label>Elevation Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Business_Issue.recordType-meta.xml
<RecordType>
    <fullName>Business_Issue</fullName>
    <active>true</active>
    <businessProcess>Business Issue</businessProcess>
    <description>A written, electronic, or oral communication that alleges deficiencies related to the identity, quality, durability, reliability, safety, effectiveness, or performance of a device after it is released for distribution.</description>
    <label>Business Issue</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Elevation.recordType-meta.xml
<RecordType>
    <fullName>Elevation</fullName>
    <active>true</active>
    <businessProcess>Elevation</businessProcess>
    <label>Elevation</label>
</RecordType>

force-app/main/default/objects/Elevations__c/Elevations__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture all information and track account and technical elevation related to work order.</description>
    <label>Elevation</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Elevation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elevation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Elevations__c/fields/Elevation_Category__c.field-meta.xml
<CustomField>
    <fullName>Elevation_Category__c</fullName>
    <description>Category of the account elevation. Filled by the creator</description>
    <label>Elevation Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Maintenance</fullName>
                <default>true</default>
                <label>Account Maintenance</label>
            </value>
            <value>
                <fullName>Hot Site</fullName>
            </value>
            <value>
                <fullName>Standard Technical</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Non Standard Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Elevations__c/fields/Elevation_Manager__c.field-meta.xml
<CustomField>
    <fullName>Elevation_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select a user as an elevation manager.Filled by creator </description>
    <label>Elevation Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Elevation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Elevations__c/fields/Elevation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Elevation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of the elevation. Filled by creator.</description>
    <label>Elevation Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Elevation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Elevations__c/fields/Elevation_Status__c.field-meta.xml
<CustomField>
    <fullName>Elevation_Status__c</fullName>
    <description>Status of the account elevation. Has to be updated at creation &amp; closure.</description>
    <label>Elevation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Actions Complete</fullName>
            </value>
            <value>
                <fullName>Closed - Actions Could Not Be Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>US: DCP-672
To Populate the Record type of the associated case.
Automatically Populated if Case is associated to the Work Order.</description>
    <formula>SVMXC__Case__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Onsite_Response_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Response_Due_Date__c</fullName>
    <description>Capture the Onsite Response Due Date based on SLA Terms and the time zone of Field Support user.
Populated from trigger if SLA Terms and Field Support are associated to the Work Order.</description>
    <label>Onsite Response Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
    <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Group_Member__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Group_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</description>
    <inlineHelpText>Name of the group member working on the service order. This does not imply that this member has the ownership of service order record</inlineHelpText>
    <label>Technician</label>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Status__c</fullName>
    <description>Current status of the service order</description>
    <inlineHelpText>Current status of the service order</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
                <default>true</default>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assignment Accepted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Technician Onsite</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Revisit Required</fullName>
            </value>
            <value>
                <fullName>Estimate Approved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Technician Acknowledged</fullName>
            </value>
            <value>
                <fullName>Technician Enroute</fullName>
            </value>
            <value>
                <fullName>Work Complete</fullName>
            </value>
            <value>
                <fullName>Requires Revisit</fullName>
            </value>
            <value>
                <fullName>Reopen Requested</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Closed-Duplicate</fullName>
            </value>
            <value>
                <fullName>Awaiting Parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Type__c</fullName>
    <description>Type of service order: Field Service, Depot repair etc.</description>
    <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Depot Repair</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
                <default>true</default>
                <label>Field Service</label>
            </value>
            <value>
                <fullName>Propel</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Service Activities</fullName>
            </value>
            <value>
                <fullName>Remote Support</fullName>
            </value>
            <value>
                <fullName>Depot Service</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Dedicated Onsite Activities</fullName>
            </value>
            <value>
                <fullName>Sales Support Activity</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Cycle Count</fullName>
            </value>
            <value>
                <fullName>Clarity LIMS</fullName>
            </value>
            <value>
                <fullName>Channel Partner Replenishment</fullName>
            </value>
            <value>
                <fullName>Return Scrap Decommission</fullName>
            </value>
            <value>
                <fullName>Billable Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__SM_SLA_Onsite_Response__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__SM_SLA_Onsite_Response__c</fullName>
    <description>Number of minutes Configured in the SLA Rule for Onsite Response.</description>
    <inlineHelpText>Number of minutes Configured in the SLA Rule for Onsite Response.</inlineHelpText>
    <label>SLA Onsite Response</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/recordTypes/Field_Service.recordType-meta.xml
<RecordType>
    <fullName>Field_Service</fullName>
    <active>true</active>
    <label>Field Service</label>
</RecordType>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPlanOfAction_ElevationHelper.cls
/**
* @author Shivani Jain
* @date 28 Feb 2022
*
* @description DCP-49675 Test class for PlanOfAction_ElevationHelper
*/ 
@IsTest(SeeAllData=false)
private class TestPlanOfAction_ElevationHelper {

    static final String BUSINESS_ISSUE = 'Business Issue';
    static final String CASE_STATUS_INITIATED = 'Initiated';

    /*******************************************************************************************************
    * @description test validateIfLoanergreementIsGenerated method throwing error
    */
    static testmethod void testSendNotifications() {
        Account acc = TestDataAccount.getAccount('Test Account', 'USD');
        acc.Account_Group__c = Accounts.GROUP_ULTIMATE_CONSIGNEE;
        insert acc;
        System.assert(acc.id != null, 'Account not inserted successfully');

        Contact con = TestDataPerson.getNewContact(acc.Id);
        System.assert(con.id != null, 'Contact not inserted successfully');

        Case objCase = TestDataCase.initNewCase(BUSINESS_ISSUE, CASE_STATUS_INITIATED, con.Id);
        objCase.Subject = 'test';
        objCase.Description= 'test';
        objCase.Origin = 'Phone-CP';
        objCase.Date_of_Issue_Awareness__c=System.today() -2;
        objCase.Awareness_Date_Difference_Reason__c = 'Logistical delay';
        insert objCase;
        System.assert(objCase.id != null, 'Case not inserted successfully');

        SVMXC__Service_Order__c workOrder = [select id,Onsite_Response_Due_Date__c,SVMXC__SM_SLA_Onsite_Response__c,
                                                SVMXC__Order_Type__c,Case_Record_Type__c,OwnerId,SVMXC__Group_Member__c,
                                             SVMXC__Order_Status__c from 
                                             SVMXC__Service_Order__c where SVMXC__Case__c =: objCase.Id Limit 1];
        System.assert(workOrder.id != null, 'Automatic Work Order creation from Case trigger failed');

        List<User> lstUsers = [SELECT Id FROM User WHERE Profile.Name =: System.label.Field_Service LIMIT 1];

        Id technicalElevationRecordType = Schema.SObjectType.Elevations__c.getRecordTypeInfosByName().get('Technical Elevation').getRecordTypeId();
          
        Elevations__c techElev = new Elevations__c();
        techElev.RecordTypeId = technicalElevationRecordType;
        techElev.Elevation_Category__c = 'Standard Technical';
        techElev.Elevation_Status__c = 'Open';
        techElev.Elevation_Owner__c = lstUsers[0].Id;
        techElev.Elevation_Manager__c = lstUsers[0].Id;
        techElev.Plan_of_Action__c = 'test';
        techElev.Work_Order__c = workOrder.Id;
        insert techElev;
        System.assert(techElev.id != null, 'Technical Elevation not inserted successfully');

        workOrder.Technical_Elevation__c = techElev.Id;
        update workOrder;

        Test.startTest();
        PlanOfAction_ElevationHelper.sendNotifications(new List<Elevations__c>{techElev});
        
        List<Comment__c> commentLst = [SELECT id FROM Comment__c WHERE Work_Order__c =: workOrder.Id];
        System.assert(commentLst != NULL && commentLst.size() == 1, 'Comment Insertion failed');
        Test.stopTest();
    }
}