force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Field to capture external Id</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Associated_Product__c/Associated_Product__c.object-meta.xml
<CustomObject>
    <description>Associated Product can link to Case and/or Work Order</description>
    <label>Associated Product</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Associated Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Product__c/fields/Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>Installed_Product__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Installed product</description>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Field to hold PS External ID.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component SN</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Case1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Field to store External ID</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FRU_List__c/FRU_List__c.object-meta.xml
<CustomObject>
    <label>FRU List</label>
    <nameField>
        <displayFormat>FRU-{0000}</displayFormat>
        <label>FRU List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRU Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FRU_List__c/fields/ERP_Product__c.field-meta.xml
<CustomField>
    <fullName>ERP_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated by SAP via integration. Used to check the part being added on a parts order line to ensure part is compatible for the installed product (Product on the parts order line is comapred with the ERP Product field).</description>
    <label>ERP Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>FRU Lists (Product)</relationshipLabel>
    <relationshipName>FRU_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FRU_List__c/fields/Service_Bill_Of_Materials__c.field-meta.xml
<CustomField>
    <fullName>Service_Bill_Of_Materials__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service BOM.
To be populated from SAP.</description>
    <label>Service Bill Of Materials</label>
    <referenceTo>Service_Bill_Of_Materials__c</referenceTo>
    <relationshipLabel>FRU Lists</relationshipLabel>
    <relationshipName>FRU_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FRU_List__c/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Product_Type__c</fullName>
    <description>Field to specifytype of service product.</description>
    <label>Service Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved Tool</fullName>
                <isActive>false</isActive>
                <label>Approved Tool</label>
            </value>
            <value>
                <fullName>Approved Tool- Calibrated</fullName>
            </value>
            <value>
                <fullName>Approved Tool- Non-Calibrated</fullName>
            </value>
            <value>
                <fullName>Approved Tool- Reference</fullName>
            </value>
            <value>
                <fullName>Consumable</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>NONFRU</fullName>
            </value>
            <value>
                <fullName>Spare</fullName>
            </value>
            <value>
                <fullName>Standard Tool</fullName>
            </value>
            <value>
                <fullName>Tool</fullName>
                <isActive>false</isActive>
                <label>Tool</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Unique field to store external id.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Bill_Of_Materials__c/Service_Bill_Of_Materials__c.object-meta.xml
<CustomObject>
    <description>Service BOM to store the compatible FRU products.</description>
    <label>Service Bill Of Materials</label>
    <nameField>
        <label>Service Bill Of Materials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Bill Of Materials</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Bill_Of_Materials__c/fields/ERP_Service_BoM_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Service_BoM_Number__c</fullName>
    <description>Unique Service BoM Number of SAP. 
To be populated from SAP.</description>
    <externalId>true</externalId>
    <label>ERP Service BoM Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Service_Bill_Of_Materials__c.field-meta.xml
<CustomField>
    <fullName>Service_Bill_Of_Materials__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Service BOM. 
To be populated from SAP.</description>
    <label>Service Bill Of Materials</label>
    <referenceTo>Service_Bill_Of_Materials__c</referenceTo>
    <relationshipLabel>Installed Products</relationshipLabel>
    <relationshipName>Installed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Service_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Product_Type__c</fullName>
    <description>Formula field that Indicates whether the Installed Product is Instrument, Spare, Core or Consumable. Used in various business logic and automations.</description>
    <formula>TEXT(SVMXC__Product__r.Service_Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
    <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N70000001hzZ0EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Is_Auto_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_Auto_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check whether Work Order is created from automation.</description>
    <label>Is Auto Created?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Component</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Order_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Order_Type__c</fullName>
    <description>Type of service order: Field Service, Depot repair etc.</description>
    <inlineHelpText>Type of service order: Field Service, Depot repair etc.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Depot Repair</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
                <default>true</default>
                <label>Field Service</label>
            </value>
            <value>
                <fullName>Propel</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Service Activities</fullName>
            </value>
            <value>
                <fullName>Remote Support</fullName>
            </value>
            <value>
                <fullName>Depot Service</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Dedicated Onsite Activities</fullName>
            </value>
            <value>
                <fullName>Sales Support Activity</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Cycle Count</fullName>
            </value>
            <value>
                <fullName>Clarity LIMS</fullName>
            </value>
            <value>
                <fullName>Channel Partner Replenishment</fullName>
            </value>
            <value>
                <fullName>Return Scrap Decommission</fullName>
            </value>
            <value>
                <fullName>Billable Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/recordTypes/Installation.recordType-meta.xml
<RecordType>
    <fullName>Installation</fullName>
    <active>false</active>
    <label>Installation</label>
</RecordType>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestServiceBomController.cls
/**
*    @author: Sandeep 
*    @date:   20-Jan-2021
*    @description:  Test Class for  ServiceBomController  class.
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*    ------------------------------------------------------------------------------------ 
*             Sandeep                   20-Jan-2021           Initial Development 
              Priya                     19-Dec-2023           test method for saveAssociatedProducts
                                
*/
@IsTest
public class TestServiceBomController {
    
    public static final string STRING_INSTALLED_PRODUCT_NAME = 'Test IP VM';
    public static final string STRING_CURRENCY = 'USD';
    public static final string STRING_INSTALLED_PRODUCT_STATUS = 'New';
    public static final string STRING_PRODUCT_NAME = 'Test Product VM';
    
    static testMethod void getDetails(){
        Account objAccount = TestDataAccount.getNewAccount();
        Account objAccupdate=[select id,Account_Group__c from Account where id=:objAccount.id];
        objAccupdate.Account_Group__c='Distributor';
        update objAccupdate;
        Product2 objProduct2 = new Product2(Name = STRING_PRODUCT_NAME+'2',Service_Product_Type__c = 'Spare');
        insert objProduct2;
        Service_Bill_Of_Materials__c serviceBOM = new Service_Bill_Of_Materials__c(Name = 'Test Service BOM', ERP_Service_BoM_Number__c = '100291');
        insert serviceBOM;
        FRU_List__c fruList = new FRU_List__c(SVMX_PS_External_ID__c = '1091');
        fruList.Service_Bill_Of_Materials__c=serviceBOM.Id;
        fruList.ERP_Product__c=objProduct2.id;
        insert fruList;
        SVMXC__Installed_Product__c objInstalledProduct = TestDataFieldService.createInstalledProduct(STRING_INSTALLED_PRODUCT_NAME, STRING_CURRENCY, STRING_INSTALLED_PRODUCT_STATUS);
        objInstalledProduct.SVMXC__Company__c = objAccount.Id;
        objInstalledProduct.Service_Bill_Of_Materials__c=serviceBOM.Id;
        insert objInstalledProduct;
        Contact objContact = TestDataContact.getNewContact(objAccount);
        Case objCase = TestDataCase.initServiceRequestCase(objContact);
        objCase.SVMXC__Component__c = objInstalledProduct.Id;
        insert objCase;
        Test.startTest();
        SVMXC__Service_Order__c workOrder = TestDataFieldService.createWorkOrder('Field Service', objCase.Id, 'Initiated');
        workOrder.SVMXC__Company__c = objAccount.id;
        workOrder.SVMXC__Component__c = objInstalledProduct.Id;
        workOrder.SVMXC__Order_Type__c='Installation';
        workOrder.Is_Auto_Created__c=true;
        insert workOrder;
        ServiceBomController.ProductReturnedWrapper prw= new ServiceBomController.ProductReturnedWrapper();
        prw = ServiceBomController.getIpDetails(STRING_INSTALLED_PRODUCT_NAME);
        System.assert(prw!=null,'prw is null');
        List<SVMXC__Service_Order__c> lstWo= ServiceBomController.getWODetails(workOrder.Id+'');
        System.assert(!lstWo.isEmpty(),'lstWo is empty');
        List<Case> lstCase=ServiceBomController.getCaseDetails(objCase.Id+'');
        System.assert(!lstCase.isEmpty(),'lstCase is empty');
        ServiceBomController.getPODetails(workOrder.Id+'');
        List<ServiceBomController.ServiceBomWrapper> lstSBW = new List<ServiceBomController.ServiceBomWrapper>();
        lstSBW = ServiceBomController.getFruList(serviceBOM.Id,'Test');
        System.assert(!lstSBW.isEmpty(),'lstSBW is empty');
        List<ServiceBomController.ProductReturnedWrapper> lstPRW = new List<ServiceBomController.ProductReturnedWrapper>();
        lstPRW= ServiceBomController.getProductReturned(objInstalledProduct.Id);
        System.assert(!lstPRW.isEmpty(),'lstPRW is empty');
        Test.StopTest();
    }
    /**
    *  @author: Priya 
    *  @description :test method for saveAssociatedProducts (CMCM-3200)
    **/ 
    static testMethod void testSaveAssociatedProducts() {
        Boolean featureFlag;
        Feature.setMockFeatureFlag('ServiceAssociatedProducts', true);
        List<Map<String, Object>> isPrimaryAssociatedProduct = new List<Map<String, Object>>();
        Map<String, Object> dataMap = new Map<String, Object>();
        
        cs_Apex_Settings__c apexSettings = new cs_Apex_Settings__c(
            Bypass_Triggers_By_Object_1__c = 'Case',
            Bypass_Triggers_By_Object_2__c = 'SVMXC__Installed_Product__c',
            Bypass_Triggers_By_Object_3__c = 'Associated_Product__c'
        );
        insert apexSettings;
        Account objAccount = TestDataAccount.getNewAccount();
        SVMXC__Installed_Product__c objInstalledProduct = TestDataFieldService.createInstalledProduct(STRING_INSTALLED_PRODUCT_NAME, STRING_CURRENCY, STRING_INSTALLED_PRODUCT_STATUS);
        objInstalledProduct.SVMXC__Company__c = objAccount.Id;
        insert objInstalledProduct;
        Product2 objProduct2 = new Product2(Name = STRING_PRODUCT_NAME+'2',Service_Product_Type__c = 'Spare');
        objProduct2.Source_System__c = 'SAP';
        insert objProduct2;
        Contact objContact = TestDataContact.getNewContact(objAccount);
        Case objCase = TestDataCase.initServiceRequestCase(objContact);
        objCase.SVMXC__Component__c = objInstalledProduct.Id;
        insert objCase;
        Test.startTest();
        Associated_product__c associatedProd = new Associated_product__c();
        associatedProd.Case__c = objCase.Id;
        associatedProd.Installed_Product_Upgrade_Type__c = 'IVD';
        associatedProd.Is_Primary__c = true;
        associatedProd.Product_Serial_Number__c = 'test';
        associatedProd.Product_Lot_Number__c = 'test';
        associatedProd.Expired_Date__c = date.today();
        associatedProd.Is_Expired__c = False;
        //associatedProd.Installed_Product__c = objInstalledProduct.id;
        insert associatedProd;
        // Add data to the map
        dataMap.put('serialnumber', 'Test 123');
        dataMap.put('lotNumber', 'Test 123');
        dataMap.put('ExpiredDate', Date.today());
        dataMap.put('isExpire', false);
        dataMap.put('isPrimary', false);
        dataMap.put('recId', objProduct2.Id);
        dataMap.put('id', associatedProd.Id);
        isPrimaryAssociatedProduct.add(dataMap);
        String jsonString = JSON.serialize(isPrimaryAssociatedProduct);
        try{
        String serviceResult = ServiceBomController.saveAssociatedProducts(jsonString, objCase.Id);
        Assert.areEqual('Success',serviceResult);
        Associated_product__c insertedRecord = [SELECT Id, Name, Product_Serial_Number__c FROM Associated_product__c WHERE Product_Serial_Number__c='Test 123' AND Is_Primary__c = false LIMIT 1];
        System.assertEquals('Test 123', insertedRecord.Product_Serial_Number__c,'Product serial number is not same');
        }
        catch(Exception e) {
            //throw new AuraHandledException('133 Test Class Exception: ' + e.getMessage());
            ApexExceptions.emit('ServiceBomController',e);
            ilib_LogEvent.emit();
            system.debug('TestServiceBomController debug--'+ e.getMessage());
        }
        Test.StopTest();
    }
    /**
    *  @author: Priya 
    *  @description :test method for saveAssociatedProducts (CMCM-3200)
    **/ 
    static testMethod void testgetAssociatedProduct() {
        Feature.setMockFeatureFlag('ServiceAssociatedProducts', true);
        Account objAccount = TestDataAccount.getNewAccount();
        SVMXC__Installed_Product__c objInstalledProduct = TestDataFieldService.createInstalledProduct(STRING_INSTALLED_PRODUCT_NAME, STRING_CURRENCY, STRING_INSTALLED_PRODUCT_STATUS);
        objInstalledProduct.SVMXC__Company__c = objAccount.Id;
        insert objInstalledProduct;
        Product2 objProduct2 = new Product2(Name = STRING_PRODUCT_NAME+'2',Service_Product_Type__c = 'Spare');
        insert objProduct2;
        Contact objContact = TestDataContact.getNewContact(objAccount);
        Case objCase = TestDataCase.initServiceRequestCase(objContact);
        objCase.SVMXC__Component__c = objInstalledProduct.Id;
        insert objCase;
        Test.startTest();
        Associated_product__c associatedProd = new Associated_product__c();
        associatedProd.Case__c = objCase.Id;
        associatedProd.Installed_Product_Upgrade_Type__c = 'IVD';
        associatedProd.Is_Primary__c = true;
        associatedProd.Product_Serial_Number__c = 'test';
        associatedProd.Product_Lot_Number__c = 'test';
        associatedProd.Expired_Date__c = date.today();
        associatedProd.Is_Expired__c = False;
        associatedProd.Installed_Product__c = objInstalledProduct.id;
        insert associatedProd;
        List<Associated_Product__c> apList = ServiceBomController.getAssociatedProduct(objCase.Id);
        Assert.isTrue(apList!= null);
        Test.StopTest();
    }
}