force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__Parts_Request__c/SVMXC__Parts_Request__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>This object is used to capture part requests made from field engineers to other field engineers/warehouses/suppliers, and from warehouses to suppliers. Parts requests do not have the context of a service event.</description>
    <label>Parts Request</label>
    <nameField>
        <displayFormat>PRQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Parts_Request__c/fields/SVMXC__Requested_From__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Requested_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location from where stock is requested. This is a lookup to an existing site record.</description>
    <inlineHelpText>Location from where stock is requested. This is a lookup to an existing site record.</inlineHelpText>
    <label>Requested From</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>Parts_Request_From</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Parts_Request__c/fields/SVMXC__Required_At_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Required_At_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location where stock is required. This is a lookup to an existing site record.</description>
    <inlineHelpText>Location where stock is required. This is a lookup to an existing site record.</inlineHelpText>
    <label>Required At Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>Parts_Request_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Parts_Request_Line__c/SVMXC__Parts_Request_Line__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>This object is used to capture parts and quantities in a parts request. Parts requests do not have the context of a service event.</description>
    <label>Parts Request Line</label>
    <nameField>
        <displayFormat>PRQL-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Parts_Request_Line__c/fields/Inventory_Authority_Source__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Authority_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate the inventory authority of requested location.
Flows from process builder.</description>
    <label>Inventory Authority Source</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Parts_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Parts_Request_Line__c/fields/SVMXC__Parts_Request__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Parts_Request__c</fullName>
    <description>Parent Parts request for this request line. Reference to an existing Parts Request in ServiceMax</description>
    <label>Parts Request</label>
    <referenceTo>SVMXC__Parts_Request__c</referenceTo>
    <relationshipLabel>Parts Request Lines</relationshipLabel>
    <relationshipName>Parts_Request_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Parts_Request_Line__c/fields/SVMXC__Posted_To_Inventory__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Posted_To_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating if this receipt has been posted to product inventory.</description>
    <inlineHelpText>Flag indicating if this receipt has been posted to product inventory.</inlineHelpText>
    <label>Posted To Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/SVMXC__Service_Group__c.object-meta.xml
<CustomObject>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group. Service orders are assigned to a service group and optionally to group members. At the time of assignment, all the above parameters can be considered by the support center engineer(s) to choose the most suitable group that can address the customer problem.</description>
    <label>Service Team</label>
    <nameField>
        <label>Service Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/SVMXC__Service_Group_Members__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group.</description>
    <label>Technician/Equipment</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technician/Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an existing salesforce User.</description>
    <inlineHelpText>Lookup to an existing salesforce User.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Service_Group__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Group__c</fullName>
    <description>Name of the service group. Is a lookup to an existing service group in ServiceMax</description>
    <inlineHelpText>Name of the service group. Is a lookup to an existing service group in ServiceMax</inlineHelpText>
    <label>Service Team</label>
    <referenceTo>SVMXC__Service_Group__c</referenceTo>
    <relationshipLabel>Technician/Equipment</relationshipLabel>
    <relationshipName>Service_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/ERP_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_ID__c</fullName>
     <description>Unique ERP Customer ID populated based on Account linked to location.</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ERP Customer ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMX_PS_Preferred_Technician__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Preferred_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Technician</label>
    <referenceTo>SVMXC__Service_Group_Members__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Account__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your account.</description>
    <inlineHelpText>The company to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your company</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Service Engineer associated with the site.</description>
    <inlineHelpText>Name of the Service Engineer associated with the site.</inlineHelpText>
    <label>Service Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Stocking_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Stocking_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</description>
    <inlineHelpText>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</inlineHelpText>
    <label>Stocking Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPartsRequestLines.cls
/***************************************************************************************************************************************
 * NAME   : TestPartsRequestLines
 * DESCRIPTION  : TestClass for  PartsRequestLines.cls -> notifyInventoryAuthority
 *    
 * @AUTHOR : Nitin
 * @DATE   : 12th Sept 2024 
 *
 * MODIFICATION LOG:   
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nitin             12th Sept 2024           Initial Version
***************************************************************************************************************************************
*/ 
@IsTest
public class TestPartsRequestLines {

  @IsTest
  private static void testnotifyInventoryAuthority() { 
      List < SVMXC__Site__c > locationList = new List < SVMXC__Site__c > ();
      Account testAccount = TestDataAccount.getAccount('Test ACC', 'USD');
      testAccount.Account_Group__c='Distributor';
      testAccount.ERP_Customer_Id__c = 'Test1';
      INSERT testAccount;

      User serviceEngineer = TestDataFieldService.createUser('Field Service Logistics',false);
      INSERT serviceEngineer;

      SVMXC__Site__c sourceLocation = new SVMXC__Site__c();
      sourceLocation.Name = 'source location';
      sourceLocation.SVMXC__Account__c = testAccount.Id;
      sourceLocation.SVMXC__Stocking_Location__c = true;
      sourceLocation.SVMXC__Service_Engineer__c = serviceEngineer.Id;
      INSERT sourceLocation;

      system.assertNotEquals(null,sourceLocation.Id); 

      //Create Destination Location
      SVMXC__Site__c destinationLocation = new SVMXC__Site__c();
      destinationLocation.Name = 'destination Location';
      destinationLocation.SVMXC__Account__c = testAccount.Id;
      destinationLocation.SVMXC__Stocking_Location__c = true;
      locationList.add(destinationLocation);
      INSERT destinationLocation;
      system.assertNotEquals(null,destinationLocation.Id); 

      //Create Parts Request
      SVMXC__Parts_Request__c partsRequest = new SVMXC__Parts_Request__c();
      partsRequest.SVMXC__Requested_From__c = sourceLocation.Id;
      partsRequest.SVMXC__Required_At_Location__c = destinationLocation.Id;
      INSERT partsRequest;

      system.assertNotEquals(null,partsRequest.SVMXC__Requested_From__c); 

      SVMXC__Parts_Request_Line__c partsRequestLine = new SVMXC__Parts_Request_Line__c();
      partsRequestLine.SVMXC__Parts_Request__c = partsRequest.Id;
      INSERT partsRequestLine;

      //Updates Parts Request Line
      SVMXC__Parts_Request_Line__c toUpdatepartsRequestLine = [SELECT Id, SVMXC__Posted_To_Inventory__c FROM SVMXC__Parts_Request_Line__c WHERE Id =: partsRequestLine.Id];
      toUpdatepartsRequestLine.SVMXC__Posted_To_Inventory__c = TRUE;
      UPDATE toUpdatepartsRequestLine;

      SVMXC__Parts_Request_Line__c ip= [select id,Inventory_Authority_Source__c from SVMXC__Parts_Request_Line__c where id=:partsRequestLine.id];
      System.assertEquals(ip.Inventory_Authority_Source__c, serviceEngineer.Id);
  }


  @IsTest
  private static void testnotifyInventoryAuthorityPreferredLocation() { 
      List < SVMXC__Site__c > locationList = new List < SVMXC__Site__c > ();
      Account testAccount = TestDataAccount.getAccount('Test ACC', 'USD');
      testAccount.Account_Group__c='Distributor';
      testAccount.ERP_Customer_Id__c = 'Test1';
      INSERT testAccount;

      User serviceEngineer = TestDataFieldService.createUser('Field Service Logistics',false);
      INSERT serviceEngineer;

      SVMXC__Service_Group__c serviceTeam = TestDataFieldService.createServiceTeam('TestTeam','US');
      INSERT serviceTeam;

      SVMXC__Service_Group_Members__c fieldSupport = TestDataFieldService.getNewFieldSupport(serviceEngineer.Id,'PreferedTechnician',serviceTeam.Id);
      SVMXC__Site__c sourceLocation = new SVMXC__Site__c();
      sourceLocation.Name = 'source location';
      sourceLocation.SVMXC__Account__c = testAccount.Id;
      sourceLocation.SVMXC__Stocking_Location__c = true;
      sourceLocation.SVMX_PS_Preferred_Technician__c = fieldSupport.Id;
      INSERT sourceLocation;

      system.assertNotEquals(null,sourceLocation.Id); 

      //Create Destination Location
      SVMXC__Site__c destinationLocation = new SVMXC__Site__c();
      destinationLocation.Name = 'destination Location';
      destinationLocation.SVMXC__Account__c = testAccount.Id;
      destinationLocation.SVMXC__Stocking_Location__c = true;
      locationList.add(destinationLocation);
      INSERT destinationLocation;
      system.assertNotEquals(null,destinationLocation.Id); 

      //Create Parts Request
      SVMXC__Parts_Request__c partsRequest = new SVMXC__Parts_Request__c();
      partsRequest.SVMXC__Requested_From__c = sourceLocation.Id;
      partsRequest.SVMXC__Required_At_Location__c = destinationLocation.Id;
      INSERT partsRequest;

      system.assertNotEquals(null,partsRequest.SVMXC__Requested_From__c); 

      SVMXC__Parts_Request_Line__c partsRequestLine = new SVMXC__Parts_Request_Line__c();
      partsRequestLine.SVMXC__Parts_Request__c = partsRequest.Id;
      INSERT partsRequestLine;

      //Updates Parts Request Line
      SVMXC__Parts_Request_Line__c toUpdatepartsRequestLine = [SELECT Id, SVMXC__Posted_To_Inventory__c FROM SVMXC__Parts_Request_Line__c WHERE Id =: partsRequestLine.Id];
      toUpdatepartsRequestLine.SVMXC__Posted_To_Inventory__c = TRUE;
      UPDATE toUpdatepartsRequestLine;

      SVMXC__Parts_Request_Line__c ip= [select id,Inventory_Authority_Source__c from SVMXC__Parts_Request_Line__c where id=:partsRequestLine.id];
      SVMXC__Site__c fromLoc= [select id,SVMX_PS_Preferred_Technician__r.SVMXC__Salesforce_User__c from SVMXC__Site__c where id=:sourceLocation.id];

      System.assertEquals(ip.Inventory_Authority_Source__c , fromLoc.SVMX_PS_Preferred_Technician__r.SVMXC__Salesforce_User__c);     
  }

}