force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/Apttus_Config2__LineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected product or service</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Shipping_In_1Q_After_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_1Q_After_Close_Quarter__c</fullName>
    <description>This field populate shipping close quarter.</description>
    <label>Shipping In 1Q After Close Quarter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Shipping_In_2Q_After_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_2Q_After_Close_Quarter__c</fullName>
    <description>This field populate shipping close quarter.</description>
    <label>Shipping In 2Q After Close Quarter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Shipping_In_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_Close_Quarter__c</fullName>
    <description>This field populate shipping close quarter.</description>
    <label>Shipping In Close Quarter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/Apttus_Config2__ProductConfiguration__c.object-meta.xml
<CustomObject>
    <description>Represents a product configuration</description>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/fields/Apttus_QPConfig__Proposald__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__Proposald__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the quote/proposal associated with the configuration</description>
    <label>Quote/Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Configurations</relationshipLabel>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related opportunity</description>
    <inlineHelpText>Related parent opportunity under which this Quote is created.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>R00N70000001yUfDEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Direct_Sale_to_Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sale_to_Ultimate_Consignee__c</fullName>
    <description>Formula field to populate "Direct sales to ultimate consignee"</description>
    <inlineHelpText>Field is applicable to Indirect transactions</inlineHelpText>
    <formula>Apttus_Proposal__Opportunity__r.Direct_Sale_to_Ultimate_Consignee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Direct Sale to Ultimate Consignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <description>Lookup to distributor account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Third party that purchases from Illumina to resell its products</inlineHelpText>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations (Distributor)</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Lookup to Account for Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Ultimate_Consignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/Apttus_Proposal__Proposal_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with a quote/proposal</description>
    <label>Proposal Line Item</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Shipping_In_1Q_After_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_1Q_After_Close_Quarter__c</fullName>
    <description>Stores the percentage or amount of discretionary discount applied by the sales rep on the line item</description>
    <label>Shipping In 1Q After Close Quarter</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Shipping_In_2Q_After_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_2Q_After_Close_Quarter__c</fullName>
    <description>Indicates the shipping value after Close Quarters in 2nd quarter</description>
    <label>Shipping In 2Q After Close Quarter</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Shipping_In_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_Close_Quarter__c</fullName>
    <description>Stores the shipping value in close quarters for the line item</description>
    <label>Shipping In Close Quarter</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct_Sale_to_Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sale_to_Ultimate_Consignee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The ultimate consignee becomes the sold-to account for quoting and order purposes, if this field is checked.</description>
    <inlineHelpText>Used when Illumina will be selling directly to the Ultimate Consignee on behalf of the channel partner. Quote output will also be addressed to the Ultimate Consignee.</inlineHelpText>
    <label>Direct Sale to Ultimate Consignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Distributor Account</description>
    <inlineHelpText>Name of distributor required.  For standard indirect transactions, sold to and distributor should be the same except when affiliates are &quot;sold to&quot;.  For direct to UC transactions, distributor is the distributor who brokers the deal and earns the rebate.</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND (4 OR 5)) OR (3 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.Account_Group__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS Data Update</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Data Migration</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Illumina</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>(Qtly/Weekly)</value>
        </filterItems>
        <infoMessage>You can only associate distributor type of account to this field. Search results only display distributor  type of  accounts tied to this opportunity.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Distributor_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>As part of DCP-8330 for the capturing the values of Price List.</description>
    <label>Price List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As part of DCP-1298 for capturing the end user for the opportunity
Automated/Manual.</description>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Indirect_Standard.recordType-meta.xml
<RecordType>
    <fullName>Indirect_Standard</fullName>
    <active>true</active>
    <businessProcess>Standard Direct and Indirect Sales Process</businessProcess>
    <description>Select for all Indirect High-Touch sales opportunities   (Instruments, Software, Consumables, Service Contracts, Bundles, Tenders, Rentals, etc.)</description>
    <label>Indirect Standard</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Shipping_In_1Q_After_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_1Q_After_Close_Quarter__c</fullName>
    <description>Line item level quantity estimated to ship in first quarter after fiscal quarter in which opportunity is projected to close.</description>
    <label>Shipping In 1Q After Close Quarter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shipping_In_2Q_After_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_2Q_After_Close_Quarter__c</fullName>
    <description>Line item level quantity estimated to ship in second quarter after fiscal quarter in which opportunity is projected to close.</description>
    <label>Shipping In 2Q After Close Quarter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shipping_In_Close_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Shipping_In_Close_Quarter__c</fullName>
    <description>Line item level quantity estimated to ship in fiscal quarter in which opportunity is projected to close</description>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Line item level quantity estimated to ship in fiscal quarter in which opportunity is projected to close.</inlineHelpText>
    <label>Shipping In Close Quarter</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunitySyncToQuote__e/OpportunitySyncToQuote__e.object-meta.xml
<CustomObject>
    <label>Opportunity SyncTo Quote</label>
    <pluralLabel>Opportunity Sync To Quotes</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpportunitySyncToQuote__e/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <description>Field to store Quote Id</description>
    <label>QuoteId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestOpportunitySyncToQuotes.cls
/**
*  @author Milan Savaliya
*  @date 2018-10-26
*  @description  
*  Modification Log:
*  ------------------------------------------------------------------------------------
*      Developer          Date        Description
*      Milan            2018-10-26
*      Joshith K        2020-04-27     added asserts for cart line item fields and updated testmethod. 
*	   Joshith K        2020-09-11 	   Apttus_Config2__IncentiveCode__c added in configLineItemCustomField.
*  ------------------------------------------------------------------------------------
**/
@isTest(SeeAllData=false isParallel=false)
private class TestOpportunitySyncToQuotes {

    /**
    *  @author Milan Savaliya
    *  @description Test Data Setup for Sync  Attachment tO oPP
    **/
    @testSetup
    static voId setupData()
    {
        Apttus_Config2__ConfigLineItemCustomFields__c configLineItemCustomField = new Apttus_Config2__ConfigLineItemCustomFields__c();
        configLineItemCustomField.Name = 'System Properties';
        configLineItemCustomField.Apttus_Config2__CustomFieldNames2__c = 'Apttus_Config2__HasIncentives__c,Apttus_Config2__IncentiveCode__c';
        insert configLineItemCustomField;

        Apttus_Config2__PriceList__c obPriceList = TestDataProposal.initPriceList('AMR-USD-US-01');
        insert obPriceList;
    
        Product2 product = TestDataMaster.initProduct('Brownie', 'Services');
        Product2 productTwo = TestDataMaster.initProduct('Cookie', 'Services');
        Product2 productThree = TestDataMaster.initProduct('Cake', 'Services');
        insert new List<Product2> {product, productTwo, productThree};

        Apttus_Config2__PriceListItem__c priceListItem = TestDataProposal.initPriceListItem(product, obPriceList);
        Apttus_Config2__PriceListItem__c priceListItemTwo = TestDataProposal.initPriceListItem(productTwo, obPriceList);
        Apttus_Config2__PriceListItem__c priceListItemThree = TestDataProposal.initPriceListItem(productThree, obPriceList);
        insert new List<Apttus_Config2__PriceListItem__c> {priceListItem, priceListItemTwo, priceListItemThree};

        Account objAccount = TestDataAccount.initAccount();
        objAccount.Account_Group__c = 'Distributor';
        insert objAccount;

        List<Opportunity> lstOpp= new List<Opportunity>();
        Opportunity objOpportunity = TestDataOpportunity.initOpportunity(objAccount, 'Indirect_Standard');
        objOpportunity.Distributor__c = objAccount.Id;
        objOpportunity.Ultimate_Consignee__c = objAccount.Id;
        objOpportunity.Direct_Sale_to_Ultimate_Consignee__c = false;
        objOpportunity.Price_List__c = obPriceList.Name;
        lstOpp.add(objOpportunity);
        
         //create opp without line items
        Opportunity objOpportunityNew = TestDataOpportunity.initOpportunity(objAccount, 'Indirect_Standard');
        objOpportunityNew.Name='Opp Without Lines';
        objOpportunityNew.Distributor__c = objAccount.Id;
        objOpportunityNew.Ultimate_Consignee__c = objAccount.Id;
        objOpportunityNew.Direct_Sale_to_Ultimate_Consignee__c = false;
        objOpportunityNew.Price_List__c = obPriceList.Name;
        lstOpp.add(objOpportunityNew);

        insert lstOpp;
        System.debug('####BatchToCloneOppLineToCart objOpportunity:' + objOpportunity);

        List<OpportunityLineItem> lstOpportunityLineItems = new List<OpportunityLineItem>();
        Integer counter = 2;
        for(Product2 objProduct : [SELECT Id FROM Product2 LIMIT 3])
        {
            PricebookEntry objPricebookEntry = TestDataMaster.getNewStandardPrice(objProduct.Id, 200);
            OpportunityLineItem oli = TestDataOpportunity.initOpportunityLineItem(lstOpp.get(0).Id, objPricebookEntry.Id, 14, 11);
            oli.Quantity = counter * 5;
            oli.Shipping_In_Close_Quarter__c = counter + 2;
            oli.Shipping_In_1Q_After_Close_Quarter__c = counter + 1;
            oli.Shipping_In_2Q_After_Close_Quarter__c = counter;
            lstOpportunityLineItems.add(oli);

            counter = counter + 1;
        }
        insert lstOpportunityLineItems;
        List<Apttus_Proposal__Proposal__c> listQuotes = new List<Apttus_Proposal__Proposal__c>();
        Apttus_Proposal__Proposal__c objQuote = TestDataProposal.initProposal(
            lstOpp.get(0).AccountId, lstOpp.get(0).Id, 'Test Proposal',
            obPriceList.Id, true,
            ApttusProposals.APPROVAL_STAGE_DRAFT, ApttusProposals.APPROVAL_STATUS_NONE
        );
        listQuotes.add(objQuote);
        Apttus_Proposal__Proposal__c objQuoteNew = TestDataProposal.initProposal(
            lstOpp.get(1).AccountId, lstOpp.get(1).Id, ' Proposal To Opp Without Lines',
            obPriceList.Id, true,
            ApttusProposals.APPROVAL_STAGE_DRAFT, ApttusProposals.APPROVAL_STATUS_NONE
        );
        listQuotes.add(objQuoteNew);
        insert listQuotes;
        Apttus_Config2__ProductConfiguration__c testCart = TestDataProposal.getNewCart(objQuote);
        Apttus_Proposal__Proposal_Line_Item__c proposalLineItem = TestDataProposal.initProposalLineItem(objQuote, product);
		proposalLineItem.Apttus_QPConfig__HasIncentives__c = false;
		proposalLineItem.Apttus_QPConfig__ConfigurationId__c = testCart.id;
		Apttus_Proposal__Proposal_Line_Item__c proposalLineItem2 = TestDataProposal.initProposalLineItem(objQuote, productTwo);
		proposalLineItem2.Apttus_QPConfig__HasIncentives__c = false;
		proposalLineItem2.Apttus_QPConfig__ConfigurationId__c = testCart.id;
		insert new List<Apttus_Proposal__Proposal_Line_Item__c> {proposalLineItem, proposalLineItem2};
    }

    @isTest
    private static voId testAfterUpdate()
    {
        List<Apttus_Config2__ProductConfiguration__c> listCart;
        List<OpportunityLineItem> opptLineItems;
        List<Apttus_Config2__LineItem__c> cartLineItems;
        
        Test.startTest();
        {   
            Apttus_Proposal__Proposal__c objProposal = [Select Id, Apttus_Proposal__Opportunity__c FROM Apttus_Proposal__Proposal__c where Apttus_Proposal__Opportunity__r.Name != 'Opp Without Lines' LIMIT 1];
        
            List<Apttus_Config2__ConfigCustomClasses__c> listConfigCustomClasses = [SELECT Id FROM Apttus_Config2__ConfigCustomClasses__c];
            if (!listConfigCustomClasses.isEmpty())
            {
                delete listConfigCustomClasses;
            }

            List<OpportunitySyncToQuote__e> listPlatformEvent = new List<OpportunitySyncToQuote__e>();
            for(Apttus_Proposal__Proposal__c objQuoteProposal:[Select Id, Apttus_Proposal__Opportunity__c FROM Apttus_Proposal__Proposal__c])
            { 
                OpportunitySyncToQuote__e oppprtunitySyncToQuote = new OpportunitySyncToQuote__e(QuoteId__c = objQuoteProposal.Id);
                listPlatformEvent.add(oppprtunitySyncToQuote);
            }

            List<Apttus_Proposal__Proposal_Line_Item__c> objProposalLineItems = new ApttusProposalLineItemsSelector().selectByQuoteId(new Set<Id>{objProposal.id});
            new UtilsCart.LineItemWrapper(objProposalLineItems[0]);
            //multiple records in same instance     
            EventBus.publish(listPlatformEvent);
            Test.getEventBus().deliver();
            //Adding temporary coverage for ApttusUpdatePriceForCart
            ApttusUpdatePriceForCart.runTestBoolIsPricePending = true;
            List<Apttus_Config2__ProductConfiguration__c> prodConfig = new ApttusProductConfigurationsSelector().selectProductConfigurationByQuotIds(new Set<ID> {objProposal.id});
            UtilsCart.doReprice(prodConfig[0].id);
            new ApttusUpdatePriceForCart(prodConfig[0].id).updateRepriceFlagOnQuote(prodConfig[0].id);

            listCart = [SELECT Id
            FROM Apttus_Config2__ProductConfiguration__c
            WHERE Apttus_QPConfig__Proposald__c = :objProposal.Id];

            opptLineItems = 
            [SELECT Id, Quantity, Shipping_In_Close_Quarter__c, Shipping_In_1Q_After_Close_Quarter__c, Shipping_In_2Q_After_Close_Quarter__c, Product2.ProductCode
            FROM OpportunityLineItem];

            cartLineItems =
                [SELECT Id, Apttus_Config2__Quantity__c, Shipping_In_Close_Quarter__c, Shipping_In_1Q_After_Close_Quarter__c, Shipping_In_2Q_After_Close_Quarter__c, Apttus_Config2__ProductId__r.ProductCode
                FROM Apttus_Config2__LineItem__c];

            }
        Test.stopTest();

        Assert.isFalse(listCart.isEmpty(), 'Cart Was not created for Opp Line Item Sync');

        Map<String,Apttus_Config2__LineItem__c> mapCartLines = new Map <String,Apttus_Config2__LineItem__c>();
        for(Apttus_Config2__LineItem__c objCartLine:cartLineItems){
            mapCartLines.put(objCartLine.Apttus_Config2__ProductId__r.ProductCode,objCartLine);
        }
        for (Integer i = 0; i < opptLineItems.size(); i++)
        {
            System.debug('TTN n ' + opptLineItems.get(i).Product2.ProductCode + ' vs ' + cartLineItems.get(i).Apttus_Config2__ProductId__r.ProductCode);
            System.debug('TTN q ' + opptLineItems.get(i).Quantity + ' vs ' + cartLineItems.get(i).Apttus_Config2__Quantity__c);
            System.debug('TTN ' + opptLineItems.get(i).Shipping_In_Close_Quarter__c + ' vs ' + cartLineItems.get(i).Shipping_In_Close_Quarter__c);
            System.debug('TTN ' + opptLineItems.get(i).Shipping_In_1Q_After_Close_Quarter__c + ' vs ' + cartLineItems.get(i).Shipping_In_1Q_After_Close_Quarter__c);
            System.debug('TTN ' + opptLineItems.get(i).Shipping_In_2Q_After_Close_Quarter__c + ' vs ' + cartLineItems.get(i).Shipping_In_2Q_After_Close_Quarter__c);
            Assert.areEqual(opptLineItems.get(i).Quantity, mapCartLines.get(opptLineItems.get(i).Product2.ProductCode).Apttus_Config2__Quantity__c);
            Assert.areEqual(opptLineItems.get(i).Shipping_In_Close_Quarter__c, mapCartLines.get(opptLineItems.get(i).Product2.ProductCode).Shipping_In_Close_Quarter__c);
            Assert.areEqual(opptLineItems.get(i).Shipping_In_1Q_After_Close_Quarter__c, mapCartLines.get(opptLineItems.get(i).Product2.ProductCode).Shipping_In_1Q_After_Close_Quarter__c);
            Assert.areEqual(opptLineItems.get(i).Shipping_In_2Q_After_Close_Quarter__c, mapCartLines.get(opptLineItems.get(i).Product2.ProductCode).Shipping_In_2Q_After_Close_Quarter__c);
            
        }
    }

}