force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component SN</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Case1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
    <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Cases Reported From This Site</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/cs_Apex_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls apex behavior globally or by user/profile</description>
    <label>Apex Settings</label>
</CustomObject>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_Triggers_By_Object_1__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers_By_Object_1__c</fullName>
    <description>A comma-delimited list of objects for which triggers will be bypassed. Use the name that would come from describe, don&apos;t misspell it!  (ex: Opportunity,Apttus_Proposal__Proposal__c)</description>
    <label>Bypass Triggers By Object 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SVMXC__Enable_Serialized_Tracking__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Enable_Serialized_Tracking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if stock information for this product is tracked at the serial number level. If this flag is checked, serial number information will be captured in all ServiceMax inventory transactions.</description>
    <inlineHelpText>Flag indicates if stock information for this product is tracked at the serial number level. If this flag is checked, serial number information will be captured in all ServiceMax inventory transactions.</inlineHelpText>
    <label>Enable Serialized Tracking of Stock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SVMXC__Stockable__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Stockable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if this product is stockable. ServiceMax does not maintain inventory of non-stockable products.</description>
    <inlineHelpText>Flag indicates if this product is stockable. ServiceMax does not maintain inventory of non-stockable products.</inlineHelpText>
    <label>Stockable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SVMXC__Tracking__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Tracking__c</fullName>
    <description>If and how this product is tracked when sold to customers. Serialized products are tracked by unique serial numbers. Lot/Batch tracked items are identified by the batch or lot numbers. Non-tracked items do not have a lot or serial number.</description>
    <inlineHelpText>If and how this product is tracked when sold to customers. Serialized products are tracked by unique serial numbers. Lot/Batch tracked items are identified by the batch or lot numbers. Non-tracked items do not have a lot or serial number.</inlineHelpText>
    <label>Tracking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Serialized</fullName>
            </value>
            <value>
                <fullName>Lot/Batch Tracked</fullName>
            </value>
            <value>
                <fullName>Non-Tracked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
    <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N70000001hzZ0EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing location record</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>R00N70000001hzcqEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/SVMXC__RMA_Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Parts Order is an object to handle parts logistics. With record type RMA, it is a document that authorizes products or parts to be returned to the manufacturer/repair center/warehouse. With record type Shipment,  it is an internal document that authorizes products or parts to be shipped to a customer or field inventory location. ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both.</description>
    <label>Parts Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account from/to which this RMA/shipment is made. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Company from/to which this RMA/shipment is made. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parts Orders (Account)</relationshipLabel>
    <relationshipName>RMA_Shipment_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/SVMXC__Service_Group_Members__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group.</description>
    <label>Technician/Equipment</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technician/Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Service_Group__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Group__c</fullName>
    <description>Name of the service group. Is a lookup to an existing service group in ServiceMax</description>
    <inlineHelpText>Name of the service group. Is a lookup to an existing service group in ServiceMax</inlineHelpText>
    <label>Service Team</label>
    <referenceTo>SVMXC__Service_Group__c</referenceTo>
    <relationshipLabel>Technician/Equipment</relationshipLabel>
    <relationshipName>Service_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Site__c/SVMXC__Service_Group_Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group.</description>
    <label>Location Covered</label>
    <nameField>
        <displayFormat>SGSI-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations Covered</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Site__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location covered by the service team. Not used</description>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Locations Covered</relationshipLabel>
    <relationshipName>Service_Group_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Component</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/recordTypes/Installation.recordType-meta.xml
<RecordType>
    <fullName>Installation</fullName>
    <active>false</active>
    <label>Installation</label>
</RecordType>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Account__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your account.</description>
    <inlineHelpText>The company to which this site belongs to. Note that you can maintain your own organization’s locations in which case you will create an Account record for your company</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Stocking_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Stocking_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</description>
    <inlineHelpText>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</inlineHelpText>
    <label>Stocking Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestLocation_POLHelper.cls
/**
* @author Shivani Jain
* @date 5 Jan 2022
*
* @description DCP-42926 Test class for Location_POLHelper
*/ 
@IsTest(SeeAllData=True)
private class TestLocation_POLHelper {

    static Account objAccountTest;
    static Product2 nonSerializedProdTest;
    static SVMXC__Site__c location1Test;
    static SVMXC__Site__c objLocationRecTest;
    static SVMXC__Installed_Product__c objInstalledProductTest;
    static Case objCaseTest;
    static final String STRING_PARTS_ORDER_LINE_IS_NULL = 'objPartsOrderLine is null';
    static final String STRING_WORK_ORDER_TYPE_INSTALLATION = 'Installation';
    static final string STRING_PARTS_ORDER_TYPE_RETURN = 'Return';
    static final String STRING_WORK_ORDER_STATUS_INITIATED ='Initiated';

    /*******************************************************************************************************
    * @description test data setup
    */
    public static void testDataCreation() {
        objAccountTest = TestDataAccount.getNewAccount(); //create account
        objAccountTest.Account_Group__c = 'Distributor';
        update objAccountTest;

        Contact objContact = TestDataContact.getNewContact(objAccountTest); //create contact.
        
        nonSerializedProdTest = new Product2();
        nonSerializedProdTest.Name = 'Test Non Serialized Product';
        nonSerializedProdTest.IsActive = true;
        nonSerializedProdTest.SVMXC__Tracking__c = 'Non-Tracked';
        nonSerializedProdTest.SVMXC__Stockable__c = true;
        nonSerializedProdTest.SVMXC__Enable_Serialized_Tracking__c = false;
        insert nonSerializedProdTest;
        System.assertNotEquals(null, nonSerializedProdTest.Id, 'Non serialized product not inserted');
        
        List<SVMXC__Site__c> lstSites = new LIst<SVMXC__Site__c>();
        location1Test = new SVMXC__Site__c();
        location1Test.Name = 'Test Location 1';
        location1Test.SVMXC__Account__c = objAccountTest.Id;
        location1Test.SVMXC__Stocking_Location__c = true;
        lstSites.add(location1Test);

        objLocationRecTest = new SVMXC__Site__c(Name = 'test');
        lstSites.add(objLocationRecTest);

        insert lstSites;
        System.assertNotEquals(null, location1Test.Id, 'Location not inserted successfully');
        System.assertNotEquals(null, objLocationRecTest.Id, 'Location not inserted successfully');
        
        objInstalledProductTest = TestDataFieldService.createInstalledProduct('Test IP VM', 'USD', 'New');
        objInstalledProductTest.SVMXC__Company__c = objAccountTest.Id;
        insert objInstalledProductTest;
        System.assertNotEquals(null, objInstalledProductTest.Id, 'Installed Product not inserted successfully');

        objCaseTest = TestDataCase.initServiceRequestCase(objContact);
        objCaseTest.SVMXC__Component__c = objInstalledProductTest.Id;
        insert objCaseTest;
        System.assertNotEquals(null, objCaseTest.Id, 'Service Request Case not inserted successfully');
        
    }

    /*******************************************************************************************************
    * @description test method to test Trunk Locker error
    */
    static testMethod void trunkLockerErrorTest() {  
        cs_Apex_Settings__c cs=cs_Apex_Settings__c.getInstance(UserInfo.getUserId());             
        cs.Bypass_Triggers_By_Object_1__c = 'Associated_Product__c';
        upsert cs cs_Apex_Settings__c.Id; 
        Boolean expectedExceptionThrown;
        testDataCreation();

        SVMXC__Service_Group__c objGroup = TestDataFieldService.createServiceTeam('TestServiceTeam','Antarctica');
        insert objGroup;
        System.assertNotEquals(null, objGroup.Id, 'Service Group not inserted successfully');

        SVMXC__Service_Group_Members__c objGroupMember = TestDataFieldService.createTechnician(UserInfo.getUserId(), 'Test', objGroup.id);
        objGroupMember.SVMXC__Inventory_Location__c = location1Test.Id;
        insert objGroupMember;
        System.assertNotEquals(null, objGroupMember.Id, 'Service Group Member not inserted successfully');

        SVMXC__Service_Group_Site__c objLocationCovered = TestDataFieldService.createLocationCovered(objGroupMember.id, location1Test.id, objGroup.id);
        insert objLocationCovered;
        System.assertNotEquals(null, objLocationCovered.Id, 'Service Group Site not inserted successfully');
        
        SVMXC__Service_Order__c wOrder = TestDataFieldService.createWorkOrder('Field Service', objCaseTest.Id, STRING_WORK_ORDER_STATUS_INITIATED);
        wOrder.SVMXC__Company__c = objAccountTest.id;
        wOrder.SVMXC__Component__c = objInstalledProductTest.Id;
        wOrder.SVMXC__Order_Type__c = STRING_WORK_ORDER_TYPE_INSTALLATION;
        wOrder.SVMXC__Group_Member__c = objGroupMember.Id;
        wOrder.Is_Auto_Created__c = true;
        insert wOrder; 
        System.assertNotEquals(null, wOrder.Id, 'Work Order not inserted successfully');  
        
        SVMXC__RMA_Shipment_Order__c objPartsOrder = TestDataFieldService.createPartsOrderRecord(STRING_PARTS_ORDER_TYPE_RETURN,
                'Open', '188', 'Test', 'Test', null);
        objPartsOrder.SVMXC__Source_Location__c = objLocationRecTest.id;
        objPartsOrder.SVMXC__Service_Order__c = wOrder.Id;
        
        Test.startTest();
        insert objPartsOrder;
        System.assertNotEquals(null, objPartsOrder.Id, 'Parts Order not inserted successfully');
        
        Id shipmentRecordTypeId = Schema.SObjectType.SVMXC__RMA_Shipment_Line__c.getRecordTypeInfosByName().get('Shipment').getRecordTypeId();
        
        SVMXC__RMA_Shipment_Line__c objPol = TestDataFieldService.createPartsOrderLineRecord(objPartsOrder.Id, 
                    objLocationRecTest.Id, shipmentRecordTypeId, 'Open', objInstalledProductTest.id, nonSerializedProdTest.Id);
        objPol.Requested_Delivery_Date__c = Date.today();
        objPol.To_Location__c = location1Test.id;
        objPol.Batch_Number__c = '123456';
        objPol.SVMXC__Actual_Quantity2__c = 2;
        objPol.Consumed_QTY__c = 0;

        try {
            insert objPol;
        } catch(Exception ex){
            expectedExceptionThrown = ex.getMessage().contains(Label.Trunk_Locker_Error) ? true : false;
        }
        System.assert(expectedExceptionThrown, 'Location_POLHelper failed');
        
        Test.stoptest();
    }   
}