force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <description>Case evaluation.</description>
    <inlineHelpText>Document the process taken to verify the customer problem statement, steps taken to evaluate/assess the issue and details on how cause was identified</inlineHelpText>
    <label>Evaluation</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Installed_Product_Upgrade_Type__c.field-meta.xml
<CustomField>
    <fullName>Installed_Product_Upgrade_Type__c</fullName>
    <description>Stores the Upgrade type of the Associated Installed Product .</description>
    <label>Installed Product Upgrade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>NONE</label>
            </value>
            <value>
                <fullName>IVD</fullName>
            </value>
            <value>
                <fullName>RUO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Verification_Result__c.field-meta.xml
<CustomField>
    <fullName>Verification_Result__c</fullName>
    <description>Manual entry, Technician&apos;s verification result after the case completion.</description>
    <inlineHelpText>Specify how Illumina confirmed the issue has been resolved</inlineHelpText>
    <label>Verification Result</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the work order for elevation case</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Elevation Case</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <label>Notes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notes__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
	<description>OpenQ Notes</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proactive_Run_Detail__c/Proactive_Run_Detail__c.object-meta.xml
<CustomObject>
    <label>Proactive Run Detail</label>
    <nameField>
        <displayFormat>PRD-{000000}</displayFormat>
        <label>Proactive Run Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proactive Run Details</pluralLabel>
    <sharingModel>Read</sharingModel> 
</CustomObject>

force-app/main/default/objects/Proactive_Run_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to a case record</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Proactive Run Details</relationshipLabel>
    <relationshipName>ProactiveRunDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proactive_Run_Detail__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>This field is created to hold the notes for each run&apos;s metrics to be entered by user on Proactive tab and also on the proactive run detail record</description>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proactive_Run_Detail__c/fields/Run_ID__c.field-meta.xml
<CustomField>
    <fullName>Run_ID__c</fullName>
    <description>This field is used to populate the runId value from Proactive</description>
    <label>Run ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proactive_Run_Detail__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the parent work order</description>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipLabel>Proactive Run Details</relationshipLabel>
    <relationshipName>ProactiveRun_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Case_Line__c/SVMXC__Case_Line__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Case Line</description>
    <label>Case Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Case_Line__c/fields/Proactive_Run_Detail__c.field-meta.xml
<CustomField>
    <fullName>Proactive_Run_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field used to populate the parent Proactive record</description>
    <label>Proactive Run Detail</label>
    <referenceTo>Proactive_Run_Detail__c</referenceTo>
    <relationshipLabel>Case Lines</relationshipLabel>
    <relationshipName>Case_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Case_Line__c/fields/Show_On_Case__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check box to mark the additional product information on case</description>
    <label>Show On Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Case_Line__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Lines</relationshipLabel>
    <relationshipName>Case_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Case_Line__c/fields/SVMXC__Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to an existing installed product record</description>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Case Lines</relationshipLabel>
    <relationshipName>Case_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Installed_Product_Upgrade_Type__c.field-meta.xml
<CustomField>
    <fullName>Installed_Product_Upgrade_Type__c</fullName>
    <description>Picklist field to choose Installed Product Upgrade Type.</description>
    <label>Installed Product Upgrade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <default>true</default>
                <label>NONE</label>
            </value>
            <value>
                <fullName>IVD</fullName>
            </value>
            <value>
                <fullName>RUO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <description>Captures the Evaluation done by Service users to complete a Work Order. Manually updated by users.</description>
    <inlineHelpText>Document the process taken to verify the customer problem statement, steps taken to evaluate/assess the issue and details on how cause was identified</inlineHelpText>
    <label>Evaluation</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>US: DCP-672
Manual entry, To capture the additional notes if applicable.</description>
    <inlineHelpText>Document status updates and activities with customer.</inlineHelpText>
    <label>Notes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Case__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</description>
    <inlineHelpText>Support Case from which this service order originated. Is a lookup to an existing salesforce case record</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Work_Performed__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Work_Performed__c</fullName>
    <description>Details of work performed to address/resolve the service order</description>
    <inlineHelpText>Specify work done to directly address/resolve the issue</inlineHelpText>
    <label>Work Performed</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Verification_Result__c.field-meta.xml
<CustomField>
    <fullName>Verification_Result__c</fullName>
    <description>US: DCP-672
Manual entry, Technician&apos;s verification result after the Work Order completion.</description>
    <inlineHelpText>Specify how Illumina  confirmed the issue has been resolved</inlineHelpText>
    <label>Verification Result</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestCaseLinesSelector.cls
//TestCaseLinesSelector 
/*
* @ author       : Romi
* @ date         : 30-Aug-2021
* @ Description  : Test class for CaseLinesSelector class
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                              Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Romi                  30-Aug-2021                        Initial version
*Preetha                14-Mar-2022                        Added checkShowOnCaseOnAP method
*/
@isTest
public class TestCaseLinesSelector {
    public static final String STRING_WO_RECORDTYPE='Field Service';
    /**
     * @author: Romi
     * @description: test selectCaseLinesFromId method.
     */
    public testMethod static void selectCaseLinesFromIdTest(){
        //insert Account
        Account acc = TestDataAccount.getAccount('Test Acc', 'USD');
        acc.Account_Group__c='Distributor';
        acc.ERP_Customer_Id__c = 'Test1';
        insert acc;
        System.assert(acc.Id != null);
        
        //insert Contact
        Contact con = TestDataPerson.getNewContact(acc.Id);
        System.assert(con.id != null);
        
        //insert Case
        Case cs = TestDataCase.initServiceRequestCase(con);
        cs.Status = 'Initiated';
        insert cs;
        System.assert(cs.Id != null);
        
        SVMXC__Installed_Product__c objInstalledProduct = TestDataInstalledProduct.initInstalledProduct(acc.Id);
        insert objInstalledProduct;
        
		// DCP-51097  - Start
        SVMXC__Service_Order__c wo = TestDataFieldService.createWorkOrder(STRING_WO_RECORDTYPE, null, 'Initiated');
        wo.Evaluation__c='Test';
        wo.SVMXC__Work_Performed__c='Test';
        wo.Verification_Result__c='Test'; 
        Test.startTest();
        insert wo;
        Test.stopTest();
        System.assert(wo.Id != null);
        

        Proactive_Run_Detail__c prRec = new Proactive_Run_Detail__c();
        prRec.Work_Order__c=wo.Id;
        prRec.Case__c=cs.Id;
        prRec.Notes__c='TestNotes';
        prRec.Run_ID__c='12345';
        Insert prRec;
        Set<Id> prdSetIds = new Set<Id>();
        prdSetIds.add(prRec.Id);
		
		// DCP-51097  - End
        
        //insert Case Line
        SVMXC__Case_Line__c objCaseLine = new SVMXC__Case_Line__c();
        objCaseLine.SVMXC__Case__c = cs.Id;
        objCaseLine.Installed_Product_Upgrade_Type__c = 'IVD';
        objCaseLine.Show_On_Case__c = TRUE;//QACM-18
        objCaseLine.SVMXC__Installed_Product__c=objInstalledProduct.id;
        objCaseLine.Proactive_Run_Detail__c=prRec.Id;
        insert objCaseLine;
        System.assert(objCaseLine.Id!=null);
        
        Set<Id> setobjCaseLine = new Set<Id>();
        setobjCaseLine.add(objCaseLine.Id);
        
        
        Set<Id> csSet = new Set<Id>();
        csSet.add(cs.id);
        
        Set<Id> setobjInstalledProduct = new Set<Id>();
        setobjInstalledProduct.add(objInstalledProduct.Id);
        
        
        CaseLinesSelector selector = new CaseLinesSelector();
        List<SVMXC__Case_Line__c> lstCLIP =  selector.selectCaseLinesRelatedtoIP(setobjInstalledProduct);
        System.assert(lstCLIP.size()>0);
        List<SVMXC__Case_Line__c> lstCase =  selector.selectCaseLinesOnCases(csSet);
        System.assert(lstCase.size()>0);
        List<SVMXC__Case_Line__c> lstCaseLine =  selector.selectCaseLinesFromId(setobjCaseLine);
        System.assert(lstCaseLine.size()>0);
        List<SVMXC__Case_Line__c> lstCaseLineforPrd =  selector.fetchCaseLinesForPrd(prdSetIds);
        System.assert(!lstCaseLineforPrd.isEmpty());// DCP-51097
        //QACM-18
        List<SVMXC__Case_Line__c> lstShowOnCaseLine =  selector.selectShowOnCaseLines(csSet);
        System.assert(!lstShowOnCaseLine.isEmpty(),'List has value');
        
    }

   
    
}