force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Mark_For_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Mark_For_Deletion__c</fullName>
    <description>Field to indicate if the account is marked for deletion and make it obsolete</description>
    <defaultValue>false</defaultValue>
    <label>Mark For Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>Stores the ERP (SAP) specific information between an account and related account under a given Account Sales Area. Source of majority of the data is ERP (SAP) system</description>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>ERP_PF{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This field maintain the account.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Partner_Functions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Area__c</fullName>
    <description>This field stores account sales area related to Account which is synced through SAP.</description>
    <label>Account Sales Area</label>
    <referenceTo>Account_Sales_Area__c</referenceTo>
    <relationshipLabel>Account Relationships</relationshipLabel>
    <relationshipName>Partner_Functions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Default_Partner__c.field-meta.xml
<CustomField>
    <fullName>Default_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-28541 - To default the bill to/ ship to</description>
    <label>Default Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/ERP_Account_Relationship_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Account_Relationship_Id__c</fullName>
    <description>This field stores ERP (SAP) external relationship id.</description>
    <externalId>true</externalId>
    <label>ERP Account Relationship Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>Account&apos;s ERP Id</description>
    <externalId>true</externalId>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/IsInactive__c.field-meta.xml
<CustomField>
    <fullName>IsInactive__c</fullName>
    <description>This field is used to identify whether Account Relationship is active or not.</description>
    <defaultValue>false</defaultValue>
    <label>IsInactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Related_ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_ERP_Customer_Id__c</fullName>
    <description>Customer Master Data Record&apos;s ERP Id</description>
    <label>Related ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <description>This picklist field is used to identify relationship with Account.</description>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Code Desc Missing</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/Account_Sales_Area__c.object-meta.xml
<CustomObject>
    <description>Stores the ERP (SAP) system specific information such as Sales Organization, Distribution Channel, Division and Company Code for the related account. Contains inco terms, pricegroup, pricelist type and terms of payment assigned to the given account</description>
    <label>Account Sales Area</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Account Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Area</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Sales_Area__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to Account.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Customer_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master_Data__c</fullName>
    <description>Lookup to Customer Master Data.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master Data</label>
    <referenceTo>Customer_Master_Data__c</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/ERP_Account_Sales_Area_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Account_Sales_Area_Id__c</fullName>
    <description>Unique External Field to store ERP Account Sales Area Id.</description>
    <externalId>true</externalId>
    <label>ERP Account Sales Area Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Inco_Term_1__c.field-meta.xml
<CustomField>
    <fullName>Inco_Term_1__c</fullName>
    <description>Incoterm 1 for standard shipments.</description>
    <label>Inco Term 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Inco_Term_1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/IsInactive__c.field-meta.xml
<CustomField>
    <fullName>IsInactive__c</fullName>
    <description>Field to check if record Is Inactive or not.</description>
    <defaultValue>false</defaultValue>
    <label>IsInactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Term_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Term_Of_Payment__c</fullName>
    <description>Field to store Term Of Payment.</description>
    <label>Term Of Payment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/Customer_Master_Data__c.object-meta.xml
<CustomObject>
    <description>Stores master data for all accounts groups that are used in the system&apos;s workflow and processes. Source of majority of the data is ERP (SAP) system</description>
    <label>Customer Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Field to store Account Id</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Master Data</relationshipLabel>
    <relationshipName>Customer_Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Field to store Account Group</description>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Locker</fullName>
            </value>
            <value>
                <fullName>Trunk</fullName>
            </value>
            <value>
                <fullName>Importer Of Record</fullName>
            </value>
            <value>
                <fullName>Customer Hierarchy</fullName>
            </value>
            <value>
                <fullName>Partner Stock</fullName>
            </value>
            <value>
                <fullName>Parts Locker</fullName>
                <isActive>false</isActive>
                <label>Parts Locker</label>
            </value>
            <value>
                <fullName>Trunk Stock</fullName>
                <isActive>false</isActive>
                <label>Trunk Stock</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>Field to store ERP Customer Id</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ERP Customer Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Mark_For_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Mark_For_Deletion__c</fullName>
    <description>Checkbox to store if CMD is marked for deletion</description>
    <defaultValue>false</defaultValue>
    <label>Mark For Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Inco_Term_1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFR: Costs and freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIF: Costs, Insurance and Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIP: Carriage and Insurance Paid To</fullName>
    </customValue>
    <customValue>
        <fullName>CPT: Carriage Paid To</fullName>
    </customValue>
    <customValue>
        <fullName>DAF: Delivered At Frontier</fullName>
    </customValue>
    <customValue>
        <fullName>DAP: Delivered At Place</fullName>
    </customValue>
    <customValue>
        <fullName>DAT: Delivery At Terminal</fullName>
    </customValue>
    <customValue>
        <fullName>DDP: Delivered Duty Paid</fullName>
    </customValue>
    <customValue>
        <fullName>DDU: Delivered Duty Unpaid</fullName>
    </customValue>
    <customValue>
        <fullName>DEQ: Delivered Ex Quay (Duty Paid)</fullName>
    </customValue>
    <customValue>
        <fullName>DES: Delivered Ex Ship</fullName>
    </customValue>
    <customValue>
        <fullName>EXW: Ex Works</fullName>
    </customValue>
    <customValue>
        <fullName>FAS: Free Alongside Ship</fullName>
    </customValue>
    <customValue>
        <fullName>FCA: Free Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>FH: Free House</fullName>
    </customValue>
    <customValue>
        <fullName>FOB: Free On Board</fullName>
    </customValue>
    <customValue>
        <fullName>UN: Not Free</fullName>
    </customValue>
    <customValue>
        <fullName>DPU: Delivered at Place Unloaded</fullName>
    </customValue>
    <masterLabel>Inco Term 1</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountRelationshipsSelector.cls
/**
* @author Akshay Mohan
* @date   30-Aug-2018
* @description  Selector class for Account_Relationship__c
* Modification Log:
*  ------------------------------------------------------------------------------------
*   Developer                Date                Description
*   Akshay Mohan             30-Aug-2018         Original
*   Rahul Sharma             29-Nov-2018         selectByAccountIdRelationship - Added select field for incoterm1
*	Roopal Verma             04-Apr-2019         selectByAccERPAndASAERP, Added Mark_For_Deletion__c and IsInactive__c in all methods
*   Roopal Verma             11-11-2019          DCP-28541 Added Default_Partner__c
*  -----------------------------------------------------------------------------------
*/
public class AccountRelationshipsSelector extends ilib_SObjectSelector {

    /*
    *   @author Akshay Mohan
    *   @date   30-Aug-2018
    *   @description  Describe the object
    *
    */
    public Schema.SObjectType getSObjectType()
    {
      return Account_Relationship__c.sObjectType;
   }

    /*
    *   @author Akshay Mohan
    *   @date   30-Aug-2018
    *   @description  Set Select fields
    *
    */
    public List<Schema.SObjectField> getSObjectFieldList()
    {
       return new List<Schema.SObjectField> {
          Account_Relationship__c.Id,
          Account_Relationship__c.Name,
          Account_Relationship__c.Relationship__c,
          Account_Relationship__c.Related_ERP_Customer_Id__c,
          Account_Relationship__c.ERP_Customer_Id__c,
          Account_Relationship__c.IsInactive__c,
          Account_Relationship__c.ERP_Account_Relationship_Id__c,
		  Account_Relationship__c.Default_Partner__c                                              //DCP-28541 Added Default
       };
    }

    /**
     *  @author Akshay Mohan
     *  @date   30-Aug-2018
     *  @description Fetch the Account Relationships for an Account Id & Relationship
     *  @param Set<String> setAccountIdWithERP
     *  @param lstRelationship of relationships
     *  @return Account_Relationship__c List with related CustomerMasterData
     *
    **/
    public List<Account_Relationship__c> selectByAccountIdRelationship(Set<String> setAccountERP,List<String> lstRelationship)
    {
        if (setAccountERP.isEmpty())
            return new List<Account_Relationship__c>();

        ilib_QueryFactory query = newQueryFactory();

        query.setCondition(' Relationship__c IN :lstRelationship AND Account_Sales_Area__r.IsInactive__c = false '
                            +' AND Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c = false'
                            +' AND Account_Sales_Area__r.Account__r.Account_Group__c != \'Legacy\' '
                            +' AND Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c != \'Legacy\' '
                            +' AND IsInactive__c = false AND ERP_Customer_Id__c IN :setAccountERP');

        //get relationship fields from Customer_Master_Data__c
        CustomerMasterDataSelector selectorCMD = new CustomerMasterDataSelector();
        selectorCMD.configureQueryFactoryFields(query,'Account_Sales_Area__r.Customer_Master_Data__r');

        //select sales area name
        String strQuery = query.selectField('Account_Sales_Area__r.Name')
                                .selectField('Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c')
                                .selectField('Account_Sales_Area__r.Term_Of_Payment__c')
                                .selectField('Account_Sales_Area__r.Account__r.Id')
                                .selectField('Account_Sales_Area__r.Account__r.ERP_Customer_Id__c')
                                .selectField('Account_Sales_Area__r.Inco_Term_1__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c')
            					.selectField('Account_Sales_Area__r.Account__r.Account_Group__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c')
                                .toSOQL();
        return (List<Account_Relationship__c>) Database.query( strQuery );
    }

    /**
     *  @author Akshay Mohan
     *  @date   26-Sep-2018
     *  @description Fetch the Account Relationships for an Account ERP, Account Sales Area & Relationship
     *  @param Set<String> setAccountERP
     *  @param Set<String> setASAERP
     *  @param lstRelationship of relationships
     *  @return Account_Relationship__c List with related CustomerMasterData
     *
    **/
    public List<Account_Relationship__c> selectByAccountERPSARelationship(Set<String> setAccountERP, Set<String> setASAERP, List<String> lstRelationship)
    {
        if (setAccountERP.isEmpty())
            return new List<Account_Relationship__c>();

        ilib_QueryFactory query = newQueryFactory();

        query.setCondition(' Relationship__c IN :lstRelationship AND Account_Sales_Area__r.IsInactive__c = false '
                            +' AND IsInactive__c = false AND ERP_Customer_Id__c IN :setAccountERP '
                            +' AND Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c = false'
                           	+' AND Account_Sales_Area__r.Account__r.Account_Group__c != \'Legacy\''
                            +' AND Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c != \'Legacy\' '
                            +' AND Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c IN :setASAERP ');

        //get relationship fields from Customer_Master_Data__c
        CustomerMasterDataSelector selectorCMD = new CustomerMasterDataSelector();
        selectorCMD.configureQueryFactoryFields(query,'Account_Sales_Area__r.Customer_Master_Data__r');

        //select sales area name
        String strQuery = query.selectField('Account_Sales_Area__r.Name')
                                .selectField('Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c')
                                .selectField('Account_Sales_Area__r.Account__r.Id')
                                .selectField('Account_Sales_Area__r.Term_Of_Payment__c')
                                .selectField('Account_Sales_Area__r.Account__r.ERP_Customer_Id__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c')
            					.selectField('Account_Sales_Area__r.Account__r.Account_Group__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c')
                                .toSOQL();
        return (List<Account_Relationship__c>) Database.query( strQuery );
    }

    /**
     *  @author Akshay Mohan
     *  @date   30-Aug-2018

     *  @param Set<String> setASAERP
     *  @param String strRelationship
     *  @return Account_Relationship__c List with related CustomerMasterData
     *
    **/
    public List<Account_Relationship__c> selectByASAERPWithRelationship(Set<String> setASAERP, String strRelationship)
    {
        if (setASAERP == null)
            return new List<Account_Relationship__c>();

        // INC0214022 : sometimes a set with only null was passed in
        setASAERP.remove(null);

        if (setASAERP.isEmpty())
            return new List<Account_Relationship__c>();

        // INC0214022 : use IN clase instead of != to eliminate non-selective query
        Set<String> setNotLegacyAccountGroups = Accounts.ACCOUNT_GROUP_VALUES;
        setNotLegacyAccountGroups.remove(Accounts.ACCOUNTGROUP_LEGACY);
        Set<String> setNotLegacyCmdGroups = CustomerMasterDatas.ACCOUNT_GROUP_VALUES;
        setNotLegacyCmdGroups.remove(Accounts.ACCOUNTGROUP_LEGACY);

        ilib_QueryFactory query = newQueryFactory();

        query.setCondition(' Relationship__c = :strRelationship'
                            + ' AND Account_Sales_Area__r.IsInactive__c = false '
                            + ' AND Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c = false'
                           	+ ' AND Account_Sales_Area__r.Account__r.Account_Group__c != \'Legacy\''
                            + ' AND Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c != \'Legacy\' '
                            + ' AND IsInactive__c = false'
                            + ' AND Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c IN :setASAERP');

        // replacing the != to these broke TestAutomateBillToShipToService, not sure why
        // turns out the problem was the set with null in it
        // I had left these in because it seems better but now removing because of the test issue
        //                  + ' AND Account_Sales_Area__r.Account__r.Account_Group__c IN :setNotLegacyAccountGroups'
        //                  + ' AND Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c IN :setNotLegacyCmdGroups'

        //get relationship fields from Customer_Master_Data__c
        CustomerMasterDataSelector selectorCMD = new CustomerMasterDataSelector();
        selectorCMD.configureQueryFactoryFields(query,'Account_Sales_Area__r.Customer_Master_Data__r');

        //select sales area name
        String strQuery = query.selectField('Account_Sales_Area__r.Term_Of_Payment__c')
                                .selectField('Account_Sales_Area__r.Customer_Master_Data__c')
                                .selectField('Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c')
            					.selectField('Account_Sales_Area__r.Account__r.Account_Group__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c')
                                .toSOQL();
        System.debug('setASAERP: ' + setASAERP);
        return (List<Account_Relationship__c>) Database.query( strQuery );
    }

    /**
     *  @author Akshay Mohan
     *  @date   26-Sep-2018
     *  @description Fetch the Account Relationships for a CMD ERP Id
     *  @param Set<String> setCMDERP
     *  @param String strASA
     *  @return Account_Relationship__c List with related CustomerMasterData
     *
    **/
    public List<Account_Relationship__c> selectByCMDERPWithASA(Set<String> setCMDERP,String strASA)
    {
        if(setCMDERP.isEmpty())
            return new List<Account_Relationship__c>();

        strASA='%_'+strASA;
        ilib_QueryFactory query = newQueryFactory();
        query.setCondition('Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c LIKE :strASA '
                            +' AND Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c = false'
                            +' AND Account_Sales_Area__r.Account__r.Account_Group__c != \'Legacy\''
                            +' AND Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c != \'Legacy\' '
                            +' AND IsInactive__c = false AND Account_Sales_Area__r.IsInactive__c = false '
                            +' AND ERP_Customer_Id__c IN :setCMDERP ');

        //select sales area name
        String strQuery = query.selectField('Account_Sales_Area__r.Term_Of_Payment__c')
                                .selectField('Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c')
             					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c')
            					.selectField('Account_Sales_Area__r.Account__r.Account_Group__c')
            					.selectField('Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c')
                                .toSOQL();
        return (List<Account_Relationship__c>) Database.query( strQuery );
    }

    /*
    * @author Roopal Verma
    * @date   03-28-2019
    * @description Fetch Account Relationships based on Account ERP Id and ASA ERP Id
    *
    */
    public List<Account_Relationship__c> selectByAccERPAndASAERP(set<String> accERPId)
    {
        return (List<Account_Relationship__c>) Database.query(
        newQueryFactory().selectField('Account_Sales_Area__r.ERP_Account_Sales_Area_Id__c')
            			 .selectField('Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c')
            			 .selectField('Account_Sales_Area__r.Account__c')
            			 .selectField('Account_Sales_Area__r.Account__r.Account_Group__c')
            			 .selectField('Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c')
            			 .setCondition('ERP_Customer_Id__c IN :accERPId'
                         +' AND Account_Sales_Area__r.Account__r.Account_Group__c != \'Legacy\''
                         +' AND Account_Sales_Area__r.Customer_Master_Data__r.Account_Group__c != \'Legacy\' '
                   		 +' AND IsInactive__c = false'
            			 +' AND Account_Sales_Area__r.Customer_Master_Data__r.Mark_For_Deletion__c = false')
            			 .toSOQL());
    }

}