force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <description>Auto-update from SAP</description>
    <inlineHelpText>Designation that indicates business relationship of entity with Illumina; determines role account will play in transactions and customer account type in master data.</inlineHelpText>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Type__c</fullName>
    <description>This field should flow from CMD to Sales Order</description>
    <inlineHelpText>Indicates nature of partner&apos;s business; drives account segmentation for Indirect Partners</inlineHelpText>
    <label>Channel Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel_Partner_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/Apttus_Config2__Order__c.object-meta.xml
<CustomObject>
    <description>Represents an order associated with an account</description>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__OrderReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__OrderReferenceNumber__c</fullName>
    <description>Order reference number assigned to this order.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order reference number assigned to this order.</inlineHelpText>
    <label>Order Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__RelatedOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__RelatedOpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the related opportunity</description>
    <inlineHelpText>ID of the related opportunity</inlineHelpText>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__SoldToAccountId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__SoldToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the sold to account</description>
    <inlineHelpText>ID of the sold to account</inlineHelpText>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>OrdersSoldTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Status__c</fullName>
    <description>The order status</description>
    <inlineHelpText>The order status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__Type__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Type__c</fullName>
    <description>The type of order</description>
    <inlineHelpText>The type of order</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bill Only Service</fullName>
            </value>
            <value>
                <fullName>Credit Memo Request</fullName>
            </value>
            <value>
                <fullName>Custom Order</fullName>
            </value>
            <value>
                <fullName>Debit Memo Request</fullName>
            </value>
            <value>
                <fullName>Spare Debit Memo Req</fullName>
            </value>
            <value>
                <fullName>Free of Charge</fullName>
            </value>
            <value>
                <fullName>Internal Order</fullName>
            </value>
            <value>
                <fullName>Standard Order</fullName>
            </value>
            <value>
                <fullName>Illumina Returns</fullName>
            </value>
            <value>
                <fullName>Rush Order</fullName>
            </value>
            <value>
                <fullName>Spare &amp; Labor Order</fullName>
            </value>
            <value>
                <fullName>Spares Returns</fullName>
            </value>
            <value>
                <fullName>BaseSpValue Contract</fullName>
            </value>
            <value>
                <fullName>Value Contract</fullName>
            </value>
            <value>
                <fullName>Illmna Base Warranty</fullName>
            </value>
            <value>
                <fullName>Illmn Extnded Wrrnty</fullName>
            </value>
            <value>
                <fullName>Illmn Prof Svcs</fullName>
            </value>
            <value>
                <fullName>Illmn Rental Contrct</fullName>
            </value>
            <value>
                <fullName>Illmn S/W Contract</fullName>
            </value>
            <value>
                <fullName>Illmn Servc Contract</fullName>
            </value>
            <value>
                <fullName>Service Contract</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/ASOP_Number__c.field-meta.xml
<CustomField>
    <fullName>ASOP_Number__c</fullName>
    <description>Field to store ASOP number</description>
    <externalId>true</externalId>
    <label>ASOP Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/ASOP_Number_Link__c.field-meta.xml
<CustomField>
    <fullName>ASOP_Number_Link__c</fullName>
    <description>ASOP number link</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASOP Number Link</label>
    <referenceTo>Apttus_Config2__Order__c</referenceTo>
    <relationshipLabel>Orders (ASOP Number Link)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>Field to populate contact email id</description>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <description>Distributor Account Id</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Distributor)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Order_Line_Not_Activated__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Not_Activated__c</fullName>
    <description>Checking Order line item not activated under Order</description>
    <label>Order Line Not Activated</label>
    <summaryFilterItems>
        <field>Apttus_Config2__OrderLineItem__c.Apttus_Config2__Status__c</field>
        <operation>notEqual</operation>
        <value>Activated</value>
    </summaryFilterItems>
    <summaryForeignKey>Apttus_Config2__OrderLineItem__c.Apttus_Config2__OrderId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Field store order Status</description>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Sales_Order_Number_Unique__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Number_Unique__c</fullName>
    <description>This is a shadow field for Sales Order Number</description>
    <externalId>true</externalId>
    <label>Sales Order Number Unique</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Field to store Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <description>Lookup to distributor account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Third party that purchases from Illumina to resell its products</inlineHelpText>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations (Distributor)</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Lookup to Account for Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Ultimate_Consignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Distributor Account</description>
    <inlineHelpText>Name of distributor required.  For standard indirect transactions, sold to and distributor should be the same except when affiliates are &quot;sold to&quot;.  For direct to UC transactions, distributor is the distributor who brokers the deal and earns the rebate.</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND (4 OR 5)) OR (3 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.Account_Group__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS Data Update</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Data Migration</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Illumina</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>(Qtly/Weekly)</value>
        </filterItems>
        <infoMessage>You can only associate distributor type of account to this field. Search results only display distributor  type of  accounts tied to this opportunity.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Distributor_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As part of DCP-1298 for capturing the end user for the opportunity
Automated/Manual.</description>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
        <default>true</default>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Sold To</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultimate Consignee</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect (Default)</fullName>
        <isActive>false</isActive>
        <label>Prospect (Default)</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Channel_Partner_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregator</fullName>
    </customValue>
    <customValue>
        <fullName>CoDevelopment</fullName>
    </customValue>
    <customValue>
        <fullName>CoMarketing</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor/Dealer</fullName>
    </customValue>
    <customValue>
        <fullName>Divestiture</fullName>
    </customValue>
    <customValue>
        <fullName>In Country Caretaker</fullName>
    </customValue>
    <customValue>
        <fullName>In Licensing/Out Licensing Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Generation</fullName>
    </customValue>
    <customValue>
        <fullName>Original Equipment Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>Service Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Value Added Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <masterLabel>Channel Partner Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApttusOrdersSelector.cls
/**
 *    @author Shashank Singhal
 *    @date   2018-08-24
 *    @description  DCP-844: Apttus Order Selector 
 *    Modification Log:
 *    ------------------------------------------------------------------------------------ 
 *    Developer                      Date                Description
 *    Shashank                        2018-08-24         Initial Version
 *    Rahul Sharma                    2019-07-03         DCP-25384 Added selectOrdersBySoldToAndUC 
 *    Shivani Jain                    2022-02-08         DCP-51266 - Relocation Order should not trigger 
 *                                                                   Install WO Creation
 *    Shivani Jain                    2022-04-25         DCP-51484 No CP WOs should have Associated SR case
 *    Sudarshan                       05-Dec-2023        CMCM-1354  EOL WO Changes
 *    Arquimidez Mora                 10-Aug-2024        CMCM-9645 Added a new method fetchOrderByRelatedOpportunity
 *    ------------------------------------------------------------------------------------ 
 *                    
 */
public with sharing class ApttusOrdersSelector extends ilib_SObjectSelector{
	/**
    *  @author Shashank Singhal 
    *  @description  
    *  @return SObjectType The Schema.SObjectType of the Order
    **/
   public Schema.SObjectType getSObjectType()
   {
        return Apttus_Config2__Order__c.sObjectType;
   }
    
    /**
     *  @author  Shashank Singhal
     *  @description Retrieve list of fields for Order sObject 
     *  @return sObjectFieldList list of Schema.SObjectField
     **/
    public List<Schema.SObjectField> getSObjectFieldList(){
    	return new List<Schema.SObjectField> {
        	Apttus_Config2__Order__c.id, 
                Apttus_Config2__Order__c.Apttus_Config2__OrderReferenceNumber__c, 
                Apttus_Config2__Order__c.Apttus_QPConfig__ProposalId__c,
                Apttus_Config2__Order__c.ASOP_Number__c,
                Apttus_Config2__Order__c.Apttus_Config2__Status__c,
                Apttus_Config2__Order__c.Order_Status__c,
                Apttus_Config2__Order__c.Order_Line_Not_Activated__c
        };
    }
    
    /**
     *  @author Shashank Singhal 
     *  @description Fetch Orders for related quotes
     *  @param quoteIds Set of quote Ids
     *  @return orderList List
     **/
    /*public List<Apttus_Config2__Order__c> selectOrdersForQuotes(Set<Id> setQuoteIds) 
    {
        return (List<Apttus_Config2__Order__c>) Database.query(
            newQueryFactory().setCondition('Apttus_QPConfig__ProposalId__c IN :setQuoteIds').toSOQL()
        );
    }*/
 
    /*
     * @Author : Sravan Panchangam
     * @Decription : DCP-13048
     * @Param ASOP Number
     * @return  Order with ASOP Number
     */
    public List<Apttus_Config2__Order__c> fetchOrdersbySalesOrderUnique(Set<String> salesorderNumbers){
        return (List<Apttus_Config2__Order__c>) Database.query(
            newQueryFactory().setCondition('Sales_Order_Number_Unique__c IN :salesorderNumbers').toSOQL());
    }

    /*
     * @Author : Ritika M
     * @Decription : Fetch Order records by thier ids
     * @Param Set Apprus Order Ids
     * @return  List of Apptus Orders
     */
    public List<Apttus_Config2__Order__c> selectOrdersByIds(Set<Id> setOrderIdsIds){
        return (List<Apttus_Config2__Order__c>)  Database.query(
            newQueryFactory().selectField('Apttus_Config2__RelatedOpportunityId__c')
            				.selectField('Ultimate_Consignee__c')
                            .selectField('Name') //DCP - 47704
                            .selectField('Contact_Email__c')
                            .selectField('ASOP_Number_Link__c')
							.selectField('Apttus_Config2__SoldToAccountId__c')
            				.selectField('Apttus_Config2__SoldToAccountId__r.RecordTypeId')
            				.selectField('Apttus_Config2__SoldToAccountId__r.Channel_Partner_Type__c')
                            .selectField('Apttus_Config2__Type__c')//PM-122
                            .selectField('Apttus_Config2__SoldToAccountId__r.Account_Group__c')//PM-122
                            .selectField('Apttus_Config2__SoldToAccountId__r.BillingCountryCode')//CMCM-698
                            .selectField('Distributor__c')//PM-122
                            .selectField('Apttus_QPConfig__ProposalId__c') //CMCM-1354
                            .selectField('Distributor__r.Account_Group__c')//PM-122
                            .selectField('Apttus_Config2__RelatedOpportunityId__r.Product_Interest__c') //DCP-51266
                            .selectField('Ultimate_Consignee__r.VAD_Channel_Partner_Territory__c') //DCP-51484
            				.selectField('Distributor__r.BillingCountry') //CMCM-2266
                            .selectField('Distributor__r.BillingCountryCode') //CMCM-2266
                            .selectField('Apttus_Config2__SoldToAccountId__r.BillingCountry')//CMCM-2266
            				.setCondition('ID IN :setOrderIdsIds').toSOQL());
    }
	/*
     * @Author : Sravan Panchangam
     * @Decription : DCP-9865
     * @Param ASOP Number
     * @return  Order with ASOP Number
     */
    public Apttus_Config2__Order__c fetchRecordForSalesOrderNumber(String salesOrderNumber){
        return (Apttus_Config2__Order__c)  Database.query(
            newQueryFactory().setCondition('Sales_Order_Number_Unique__c = :salesOrderNumber').toSOQL());
    }
    
    /*
     * @Author : Sravan Panchangam
     * @Decription : DCP-13048 latest change
     * @Param ASOP Number
     * @return  Order with ASOP Number
     */
    public List<Apttus_Config2__Order__c> fetchRecordForASOPLink(Set<String> asopNumber){
        return (List<Apttus_Config2__Order__c>)  Database.query(
            newQueryFactory().setCondition('Sales_Order_Number_Unique__c = :asopNumber').toSOQL());
    }

    /*
     * @Author : Rahul Sharma
     * @Decription : DCP-25384 To fetch orders by Sold To and UC
     * @Param Set of Account Ids
     * @return  Order List
     */
    public List<Apttus_Config2__Order__c> selectOrdersBySoldToAndUC(Set<id> setAccountIds){
        return (List<Apttus_Config2__Order__c>)  Database.query(
            newQueryFactory().setCondition('Apttus_Config2__SoldToAccountId__c IN :setAccountIds OR Ultimate_Consignee__c IN :setAccountIds').toSOQL());
    }

    /*
     * @Author : Arquimidez Mora
     * @Decription : Fetch Orders by Opportunity
     * @return  Order List
     */
    public List<Apttus_Config2__Order__c> fetchOrderByRelatedOpportunity(Set<Id> setOpportunityIds)
    {
        List<Apttus_Config2__Order__c> res = (List<Apttus_Config2__Order__c>) Database.query(
            newQueryFactory()
            .selectField('Id')
            .setCondition('Apttus_Config2__RelatedOpportunityId__c IN :setOpportunityIds')
            .toSOQL()
        );

        return res;
    }
}