force-app/main/default/objects/Account/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>When applicable, indicates nature of entity and work within the clinical space, used for segmentation</description>
    <inlineHelpText>Indicates the account's work within the clinical space; values are region specific and used for segmentation.  Terms and regional use:  "Clinical" (All); "Non Clinical" (All); "Healthcare Prime" (AMR); "IVD Partner" (GC); "Platform Distributor" (GC).</inlineHelpText>
    <label>Clinical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clinical_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>back end field.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>DCP-17970 changes</description>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>Legacy field</description>
    <inlineHelpText>When applicable, indicates the nature of entity's work within the clinical space; used for segmentation.  Terms and regional use:  "Clinical" (All); "Non Clinical" (All); "Healthcare Prime" (AMR); "IVD Partner" (GC); "Platform Distributor" (GC).</inlineHelpText>
    <label>Clinical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clinical_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>Field to map market segment of Contact</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Pain__c.field-meta.xml
<CustomField>
    <fullName>Pain__c</fullName>
    <description>Legacy field
CMCM-3574 - Field label updated from &apos;Pain&apos; to &apos;Critical Business Issue&apos;</description>
    <label>Critical Business Issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pain</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <description>Multi-select picklist to select Product Interests</description>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Projected_Budget_Range__c.field-meta.xml
<CustomField>
    <fullName>Projected_Budget_Range__c</fullName>
    <description>Field to track Projected Budget Range</description>
    <label>Projected Budget Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Projected_Budget_Range</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Purchase_Timeline__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Timeline__c</fullName>
    <description>Timeline for Purchase</description>
    <label>Purchase Timeline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Purchase_Timeline</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Readiness_Form__c/Customer_Readiness_Form__c.object-meta.xml
<CustomObject>
    <description>Stores specific information on customer location during the Instrument sales cycle so Sales team can share information with Service team. Information such BSA level, application use, data storage options, desired shipment or install timelines etc.</description>
    <label>Customer Readiness Form</label>
    <nameField>
        <displayFormat>CRF-{0000}-{MM}{DD}{YYYY}</displayFormat>
        <label>Customer Readiness Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Readiness Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Readiness_Form__c/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>Formula Field to store Clinical Type of ultimate consignee.</description>
    <formula>TEXT(Opportunity_Name__r.Ultimate_Consignee__r.Clinical_Type__c)</formula>
    <label>Clinical Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Readiness_Form__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>Formula Field to store Market Segment of the ultimate consignee.</description>
    <formula>TEXT( Opportunity_Name__r.Ultimate_Consignee__r.Market_Segment__c )</formula>
    <label>Market Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Readiness_Form__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Formula field to store ultimate consignee from opportunity.</description>
    <formula>Opportunity_Name__r.Ultimate_Consignee__r.Name</formula>
    <label>Ultimate Consignee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Segment__c/Market_Segment__c.object-meta.xml
<CustomObject>
    <description>Stores information on account&apos;s market segment, sub-segment and allocated percent if more than one is assigned</description>
    <label>Market Segment</label>
    <nameField>
        <displayFormat>MS-{000000}{MMDDYYYY}</displayFormat>
        <label>Market Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segment__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>Stores information of account's market segment</description>
    <label>Market Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Abandoned_Reason_Details__c.field-meta.xml
<CustomField>
    <fullName>Abandoned_Reason_Details__c</fullName>
    <description>Closed Lost/Abandoned Reason Details</description>
    <label>Closure Details</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>As part of 1298 for Budget information.</description>
    <inlineHelpText>Source and status of customer&apos;s budget associated with this opportunity. </inlineHelpText>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>As part of DCP-1298 for Clinical Type Information.</description>
    <inlineHelpText>When applicable, indicates nature of entity's work within the clinical space; value defaulted from Ultimate Consignee, but can be opportunity-specific and adjusted if needed. Required throughout opportunity lifecycle.  Terms and regional use:  "Clinical" (All); "Non Clinical" (All); "Healthcare Prime" (AMR); "IVD Partner" (GC); "Platform Distributor" (GC).</inlineHelpText>
    <label>Clinical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clinical_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <description>As part of US 1298 for user to select possible Competitor</description>
    <inlineHelpText>Primary competitor associated with opportunity.</inlineHelpText>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitor_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_Presence__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Presence__c</fullName>
    <description>Indicates if the opportunity has at least a competitor, no competition, or an unknown competitor.  Jira story # CMCM-5875</description>
    <inlineHelpText>If &apos;yes&apos; a C&amp;CT record should be added (use the Competitive Info tab). If there is no competitor or the competitor is unknown, please select the appropriate option.</inlineHelpText>
    <label>Competitor Context Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No Competitor</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct_Sale_to_Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sale_to_Ultimate_Consignee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The ultimate consignee becomes the sold-to account for quoting and order purposes, if this field is checked.</description>
    <inlineHelpText>Used when Illumina will be selling directly to the Ultimate Consignee on behalf of the channel partner. Quote output will also be addressed to the Ultimate Consignee.</inlineHelpText>
    <label>Direct Sale to Ultimate Consignee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>As part of DCP-1298 for the possible values of Segments of the market.</description>
    <inlineHelpText>Primary scientific application area(s) in which entity is focused; value defaulted from Ultimate Consignee, but can be opportunity-specific and adjusted, if needed. Required throughout opportunity lifecycle; drives commissions.</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pain__c.field-meta.xml
<CustomField>
    <fullName>Pain__c</fullName>
    <description>User manually enters the value. Was previously labeled &apos;Pain&apos; in the UI and replaced it with &apos;Critical Business Issue&apos; but we will not update the API</description>
    <inlineHelpText>The critical problem the customer is seeking to solve.</inlineHelpText>
    <label>Critical Business Issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pain</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <description>Value Source : User manually Enters the value. High level product class representative of best solution to meet customer&apos;s needs. Multi-select and is required throughout the opportunity lifecycle.</description>
    <inlineHelpText>High level product class representative of best solution to meet customer&apos;s needs. Multi-select and is required throughout the opportunity lifecycle.</inlineHelpText>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Budget_Range__c.field-meta.xml
<CustomField>
    <fullName>Projected_Budget_Range__c</fullName>
    <description>As part of DCP-1298 for the possible values for Projected Budget Range.
Manual</description>
    <inlineHelpText>Customer&apos;s estimated budget range for solving the stated Pain and customer need. Required in order to move to Qualify stage.</inlineHelpText>
    <label>Projected Budget Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Projected_Budget_Range</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_Timeline__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Timeline__c</fullName>
    <description>To display Timeline information.</description>
    <inlineHelpText>Customer&apos;s estimated buying cycle timeline for solving the stated Pain and customer need. Required in order to move to Qualify stage.</inlineHelpText>
    <label>Purchase Timeline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Purchase_Timeline</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rev_Rec_Terms__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Terms__c</fullName>
    <description>As part of DCP-1298 for the possible values for Rev Rec Terms.
Manual.</description>
    <inlineHelpText>Applicable revenue recognition terms associated with customer purchase resulting from successful closure of opportunity.</inlineHelpText>
    <label>Rev Rec Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rev_Rec_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As part of DCP-1298 for capturing the end user for the opportunity
Automated/Manual.</description>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <businessProcess>Standard Direct and Indirect Sales Process</businessProcess>
    <description>Select for all Direct High-Touch sales opportunities   (Instruments, Software, Consumables, Service Contracts, Bundles, Tenders, Rentals, etc.)</description>
    <label>Direct Standard</label>
</RecordType>

force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Government: Application in Process</fullName>
    </customValue>
    <customValue>
        <fullName>Government: Available Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Grant: Application in Process</fullName>
    </customValue>
    <customValue>
        <fullName>Grant: Available Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Budget: In Place</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Budget: In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Not Yet Determined</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clinical_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Non Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Prime</fullName>
    </customValue>
    <customValue>
        <fullName>IVD Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Distributor</fullName>
    </customValue>
    <description>As part of DCP-1298 for Clinical Type information.</description>
    <masterLabel>Clinical Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Competitor_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10X Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Agena (Sequenom)</fullName>
    </customValue>
    <customValue>
        <fullName>Agilent</fullName>
    </customValue>
    <customValue>
        <fullName>Apton</fullName>
    </customValue>
    <customValue>
        <fullName>BGI</fullName>
    </customValue>   
    <customValue>
        <fullName>Competitor Unknown / Not Shared</fullName>
    </customValue> 
    <customValue>
        <fullName>Complete Genomics/MGI</fullName>
    </customValue>
    <customValue>
        <fullName>Danaher (IDT)</fullName>
    </customValue>
    <customValue>
        <fullName>DIY INF</fullName>
    </customValue>
    <customValue>
        <fullName>DNANexus</fullName>
    </customValue>
    <customValue>
        <fullName>Element Biosciences</fullName>
    </customValue>
    <customValue>
        <fullName>Fabric Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>GenapSys</fullName>
    </customValue>
    <customValue>
        <fullName>Genemind</fullName>
    </customValue>
    <customValue>
        <fullName>Invitae</fullName>
    </customValue>
    <customValue>
        <fullName>Lexogen</fullName>
    </customValue>
    <customValue>
        <fullName>MatriDx</fullName>
    </customValue>
    <customValue>
        <fullName>NanoString</fullName>
    </customValue>
    <customValue>
        <fullName>Natera</fullName>
    </customValue>
    <customValue>
        <fullName>New England Biolabs (NEB)</fullName>
    </customValue>
    <customValue>
        <fullName>NIPD Genetics</fullName>
    </customValue>
    <customValue>
        <fullName>No Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>NVIDIA (Parabricks)</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Oxford Nanopore Technologies (ONT)</fullName>
    </customValue>
    <customValue>
        <fullName>PacBio</fullName>
    </customValue>
    <customValue>
        <fullName>Qiagen</fullName>
    </customValue>
    <customValue>
        <fullName>Roche / Kapa / Nimblegen</fullName>
    </customValue>
    <customValue>
        <fullName>Send out</fullName>
    </customValue>
    <description>As part of DCP-1298 for Competitor Information.</description>
    <masterLabel>Competitor Name</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agrigenomics</fullName>
    </customValue>
    <customValue>
        <fullName>Cancer Research</fullName>
    </customValue>
    <customValue>
        <fullName>Cell and Molecular Biology Research</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Forensics</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Research</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Infectious Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Reproductive Health</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Training/Education</fullName>
    </customValue>
    <customValue>
        <fullName>Transplant genomics</fullName>
        <isActive>false</isActive>
        <label>Transplant Genomics</label>
    </customValue>
    <customValue>
        <fullName>Preconception and Fertility</fullName>
        <isActive>false</isActive>
        <label>Preconception and Fertility</label>
    </customValue>
    <customValue>
        <fullName>Public Health Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology/Virology Research</fullName>
        <isActive>false</isActive>
        <label>Microbiology/Virology Research</label>
    </customValue>
    <customValue>
        <fullName>Genetic &amp; Complex Disease Research</fullName>
        <isActive>false</isActive>
        <label>Genetic &amp; Complex Disease Research</label>
    </customValue>
    <customValue>
        <fullName>Clinical Oncology</fullName>
        <isActive>false</isActive>
        <label>Clinical Oncology</label>
    </customValue>
    <customValue>
        <fullName>Cellular and Molecular Research</fullName>
        <isActive>false</isActive>
        <label>Cellular and Molecular Research</label>
    </customValue>
    <customValue>
        <fullName>Agricultural Genomics</fullName>
        <isActive>false</isActive>
        <label>Agricultural Genomics</label>
    </customValue>
    <customValue>
        <fullName>Pregnancy</fullName>
        <isActive>false</isActive>
        <label>Pregnancy</label>
    </customValue>
    <description>As part of DCP-1298 for the possible values of Primary Segments of the market.</description>
    <masterLabel>Market Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Pain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>High System Downtime</fullName>
    </customValue>
    <customValue>
        <fullName>High Turnaround Time</fullName>
    </customValue>
    <customValue>
        <fullName>Increasing Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Lack of Competitiveness</fullName>
    </customValue>
    <customValue>
        <fullName>Lack of Expertise</fullName>
    </customValue>
    <customValue>
        <fullName>Low Capacity (Throughput)</fullName>
    </customValue>
    <customValue>
        <fullName>Poor Data Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>Poor Data Quality</fullName>
    </customValue>
    <customValue>
        <fullName>Poor Reputation</fullName>
    </customValue>
    <customValue>
        <fullName>Third Party Dependency</fullName>
    </customValue>
    <masterLabel>Pain</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consumables</fullName>
    </customValue>
    <customValue>
        <fullName>Instrument</fullName>
    </customValue>
    <customValue>
        <fullName>Service Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Software</fullName>
    </customValue>
    <customValue>
        <fullName>Relocation</fullName>
    </customValue>
    <customValue>
        <fullName>Break Fix</fullName>
    </customValue>
	<customValue>
        <fullName>NIPT</fullName>
    </customValue>
    <customValue>
        <fullName>Arrays</fullName>
    </customValue>
    <customValue>
        <fullName>Sequencing</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Other Services (Including Professional Services)</fullName>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Projected_Budget_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0 - $10,000</fullName>
    </customValue>
    <customValue>
        <fullName>$10,000 - $25,000</fullName>
    </customValue>
    <customValue>
        <fullName>$25,000 - $50,000</fullName>
    </customValue>
    <customValue>
        <fullName>$50,000 - $100,000</fullName>
    </customValue>
    <customValue>
        <fullName>$100,000 - $250,000</fullName>
    </customValue>
    <customValue>
        <fullName>$250,000 - $500,000</fullName>
    </customValue>
    <customValue>
        <fullName>$500,000 - $1,000,000</fullName>
    </customValue>
    <customValue>
        <fullName>over $1,000,000</fullName>
    </customValue>
    <masterLabel>Projected Budget Range</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Purchase_Timeline.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0-3 Months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 Months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 Months</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;12 Months</fullName>
    </customValue>
    <masterLabel>Purchase Timeline</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rev_Rec_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACD: Acceptance Upon Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>ACI: Acceptance Upon Installation</fullName>
    </customValue>
    <customValue>
        <fullName>ACP: Acceptance Upon Performance</fullName>
    </customValue>
    <customValue>
        <fullName>DEL: Proof Of Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>MIL: Milestone Billing</fullName>
    </customValue>
    <customValue>
        <fullName>SHI: Shipment</fullName>
    </customValue>
    <customValue>
        <fullName>SPD: Shipment with Partial Deferral</fullName>
    </customValue>
    <description>As part of DCP-1298 for the possible values for  Rev Rec Terms</description>
    <masterLabel>Rev Rec Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataOpportunity.cls
/**
* Opportunity and associated records
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Govind Dubey                26 May 2018            getNewOpportunitywithRole(account)
*                                                                initOpportunityContRole()
*                                                                getContactRecord()
*                                                                getAccountRecord()
*                                                                getOpportunityContactRoleRecord()
*                                         13 July 2018           getNewIndReOrderOpportunity()
*                                                                initIndReOrderOpportunity()
*             Roopal Verma                26 July 2018           Removed Method__c from initOpportunity()
*             Rahul Sharma                26 sep 2018            Added initOpportunity(Account a,String strDeveloperName)
*             Pradeep Patil               19 Oct 2018            Removed Lab Type from initOpportunity method call
*			  Saurabh Brahmankar		  27 Feb 2024			 Added 'Competitor Presence' field 
*    ------------------------------------------------------------------------------------
**/
public with sharing class TestDataOpportunity {

    /**
    * 
    *
    * @desc getNewOpportunity [CodeScan Fix]
    */
    public static Opportunity getNewOpportunity(Account a)
    {
        Opportunity o = initOpportunity(a);
        insert o;
        return o;
    }

    /**
    * 
    *
    * @desc initOpportunity [CodeScan Fix]
    */
    public static Opportunity initOpportunity(Account a)
    {
        return initOpportunity(a, Opportunities.RT_STANDARD_DIRECT);
    }

    /**
    * 
    *
    * @desc initOpportunity [CodeScan Fix]
    */
    public static Opportunity initOpportunity(Account a,String strDeveloperName)
    {
        return initOpportunity(a,Opportunities.RECORD_TYPE_MAP.get(strDeveloperName).getRecordTypeId(),'Create','Standard Sale','Consumables');
    }

    /**
    * 
    *
    * @desc initOpportunity [CodeScan Fix]
    */
    public static Opportunity initOpportunity(Account a,ID idRecordTypeId,String strStage,String strType,String strProductInterest)
    {
        return initOpportunity(a,strStage,Date.today() + 30,10000,idRecordTypeId,10,'Clinical','Description Test','Applied Lab','Forensics',strProductInterest,strType,'$10,000 - $25,000','Internal Budget: In Process','Poor Data Quality','0-3 Months',true);
    }

    /**
    * 
    *
    * @desc initOpportunity [CodeScan Fix]
    */
    public static Opportunity initOpportunity(Account a,string strStage,Date dtCloseDate,Integer intAmount,Id idRecordType,Integer intProbability,String strClinicalType, String strDescription, String strLabType,String strPrimaryMarket,String strProductInterest,String strType,String strBudgetRange, String strBudget, String strPain,String strPurchaseTimeline, Boolean booDirectSaletoUltimateConsignee)
    {
        String rand = TestData.getRandom();

        Opportunity o = new Opportunity(
            Name = rand,
            StageName = strStage,
            CloseDate = dtCloseDate,
            AccountId = a.Id,
            Ultimate_Consignee__c = a.Id,
            Amount = intAmount,
            RecordTypeId = idRecordType,
            Probability = intProbability,
            Clinical_Type__c = strClinicalType,
            Description = strDescription,
            Market_Segment__c = strPrimaryMarket,
            Product_Interest__c = strProductInterest,
            Type = strType,
            Projected_Budget_Range__c = strBudgetRange,
            Budget__c = strBudget,
            Pain__c = strPain,
            Purchase_Timeline__c = strPurchaseTimeline,
            Direct_Sale_to_Ultimate_Consignee__c = booDirectSaletoUltimateConsignee,
            Rev_Rec_Terms__c = 'SHI: Shipment ',
            Abandoned_Reason_Details__c = 'Error',
            Competitor_Presence__c = 'No Competitor' //Competitor_Name__c = 'No Competitor' Added by SB
        );

        return o;
    }

    /**
    * 
    *
    * @desc getNewOpportunity2 [CodeScan Fix]
    */
    public static Opportunity getNewOpportunity2(Id accountId)
    {
        Opportunity rec = initOpportunity2(accountId);
        insert rec;
        return rec;
    }
    /**
    * 
    *
    * @desc initOpportunity2 [CodeScan Fix]
    */
    public static Opportunity initOpportunity2(Id accountId)
    {
        String rand = TestData.getRandom();
        Id idRecordType = Opportunities.RECORD_TYPE_MAP.get(Opportunities.RT_STANDARD_DIRECT).getRecordTypeId();
        return new Opportunity(
                Name = rand,
                StageName = 'Create',
                CloseDate = Date.today() + 30,
                AccountId = accountId,
                Ultimate_Consignee__c = accountId,
                Amount = Decimal.valueOf(TestData.getRandomNumeric()),
                RecordTypeId = idRecordType,
                Probability = 50,
                Clinical_Type__c = 'Clinical',
                Description = TestData.getRandom(),
                Market_Segment__c = 'Forensics',
                Product_Interest__c = 'Services',
                Type = 'Standard Sale',
                Projected_Budget_Range__c = '$10,000 - $25,000',
                Budget__c = 'Internal Budget: In Process',
                Pain__c = 'Poor Data Quality',
                Purchase_Timeline__c = '0-3 Months',
                Direct_Sale_to_Ultimate_Consignee__c = true,
                Rev_Rec_Terms__c='SHI: Shipment ',
                Competitor_Presence__c = 'No Competitor' //Competitor_Name__c = 'No Competitor' Added by SB
        );
    }

    /**
    * 
    *
    * @desc initOpportunity [CodeScan Fix]
    */
    public static Opportunity initOpportunity(Account a,string strStage,Date dtCloseDate,Integer intAmount,String strDeveloperName,Integer intProbability,String strClinicalType, String strDescription, String strLabType,String strPrimaryMarket,String strProductInterest,String strType,String strBudgetRange, String strBudget, String strPain,String strPurchaseTimeline, Boolean booDirectSaletoUltimateConsignee)
    {
        String rand = TestData.getRandom();
        Id idRecordType = Opportunities.RECORD_TYPE_MAP.get(strDeveloperName).getRecordTypeId();
        Opportunity o = new Opportunity(
            Name = rand,
            StageName = strStage,
            CloseDate = dtCloseDate,
            AccountId = a.Id,
            Ultimate_Consignee__c = a.Id,
            Amount = intAmount,
            RecordTypeId = idRecordType,
            Probability = intProbability,
            Clinical_Type__c = strClinicalType,
            Description = strDescription,
            Market_Segment__c = strPrimaryMarket,
            Product_Interest__c = strProductInterest,
            Type = strType,
            Projected_Budget_Range__c = strBudgetRange,
            Budget__c = strBudget,
            Pain__c = strPain,
            Purchase_Timeline__c = strPurchaseTimeline,
            Direct_Sale_to_Ultimate_Consignee__c = booDirectSaletoUltimateConsignee,
            Rev_Rec_Terms__c='SHI: Shipment ',
            Competitor_Presence__c = 'No Competitor' //Competitor_Name__c = 'No Competitor' Added by SB
        );
        return o;
    }

    /**
    * 
    *
    * @desc getNewOpportunityLineItem [CodeScan Fix]
    */
    public static OpportunityLineItem getNewOpportunityLineItem(Id oppId, Id pbeId, Double quantity, Double price)
    {
        OpportunityLineItem oli = initOpportunityLineItem(oppId, pbeId, quantity, price);
        insert oli;
        return oli;
    }

    /**
    * 
    *
    * @desc initOpportunityLineItem [CodeScan Fix]
    */
    public static OpportunityLineItem initOpportunityLineItem(Id oppId, Id pbeId, Double quantity, Double price)
    {
        OpportunityLineItem oli = new OpportunityLineItem(
            PricebookEntryId = pbeId,
            Quantity = quantity,
            OpportunityId = oppId,
            Shipping_In_Close_Quarter__c = 1,
            UnitPrice = price
        );

        return oli;
    }

    /**
    *  @author  Indra Ganesan
    *  @description to Set Opportunity Primary Contact Role
    **/
   public static OpportunityContactRole getNewOpportunityPrimaryContactRole(String role, Id contactId, Id opportunityId, boolean val)
   {
       OpportunityContactRole ocr = new OpportunityContactRole(
           Role = role,
           ContactId = contactId,
           OpportunityId = opportunityId,
           isPrimary = true
       );
       return ocr;
   }

    /**
     *  @author  Govind Dubey
     *  @description to Set Opportunity Contact Role
     **/
    public static OpportunityContactRole getNewOpportunityContactRole(String role, Id contactId, Id opportunityId)
    {
        OpportunityContactRole ocr = new OpportunityContactRole(
            Role = role,
            ContactId = contactId,
            OpportunityId = opportunityId
        );
       return ocr;
    }

    /**
    * 
    *
    * @desc getNewCrf [CodeScan Fix]
    */
    public static Customer_Readiness_Form__c getNewCrf(Id accountId, Id opportunityId)
    {
        Customer_Readiness_Form__c rec = initCrf(accountId, opportunityId);
        insert rec;
        return rec;
    }
    /**
    * 
    *
    * @desc initCrf [CodeScan Fix]
    */
    public static Customer_Readiness_Form__c initCrf(Id accountId, Id opportunityId)
    {
        Customer_Readiness_Form__c rec = new Customer_Readiness_Form__c(
                SFT_Account__c = accountId,
                Opportunity_Name__c = opportunityId
        );
        return rec;
    }

    /**
     *  @author Rohan Chandarana
     *  @description Get the standard price book
     *  @return Pricebook2
     **/
    public static Pricebook2 getStandardPriceBook()
    {
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPricebook;
        return standardPricebook;
    }

}