force-app/main/default/objects/Account/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>When applicable, indicates nature of entity and work within the clinical space, used for segmentation</description>
    <inlineHelpText>Indicates the account's work within the clinical space; values are region specific and used for segmentation.  Terms and regional use:  "Clinical" (All); "Non Clinical" (All); "Healthcare Prime" (AMR); "IVD Partner" (GC); "Platform Distributor" (GC).</inlineHelpText>
    <label>Clinical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clinical_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Updated_By_System__c.field-meta.xml
<CustomField>
    <fullName>Is_Updated_By_System__c</fullName>
    <defaultValue>false</defaultValue>
    <description>system managed flag to allow bypassing of validation rules</description>
    <label>Is Updated By System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>back end field.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Hierarchy__c/Approval_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>Represents the hierarchy levels, approvers for an account owner or custom hierarchy for CPQ and CLM workflows</description>
    <label>Approval Hierarchy</label>
    <nameField>
        <label>Approval Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Hierarchies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Hierarchy__c/fields/Approval_Hierarchy_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Hierarchy_Type__c</fullName>
    <description>Approval Hierarchy Type values.</description>
    <label>Approval Hierarchy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CLM_Custom_Hierarchy</fullName>
                <label>CLM Custom Hierarchy</label>
            </value>
            <value>
                <fullName>CLM_Sales_Hierarchy</fullName>
                <label>CLM Sales Hierarchy</label>
            </value>
            <value>
                <fullName>CPQ_Custom_Hierarchy</fullName>
                <label>CPQ Custom Hierarchy</label>
            </value>
            <value>
                <fullName>CPQ_Sales_Hierarchy</fullName>
                <label>CPQ Sales Hierarchy</label>
            </value>
            <value>
                <fullName>Discount</fullName>
                <isActive>false</isActive>
                <label>Discount</label>
            </value>
            <value>
                <fullName>Material_Class</fullName>
                <isActive>false</isActive>
                <label>Material Class</label>
            </value>
            <value>
                <fullName>Post_Pricing_Message</fullName>
                <label>Post Pricing Message</label>
            </value>
            <value>
                <fullName>Product</fullName>
                <isActive>false</isActive>
                <label>Product</label>
            </value>
            <value>
                <fullName>Product_Category</fullName>
                <isActive>false</isActive>
                <label>Product Category</label>
            </value>
            <value>
                <fullName>Product_Group</fullName>
                <isActive>false</isActive>
                <label>Product Group</label>
            </value>
            <value>
                <fullName>Product_Line</fullName>
                <isActive>false</isActive>
                <label>Product Line</label>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Standing_Discount</fullName>
                <isActive>false</isActive>
                <label>Standing Discount</label>
            </value>
            <value>
                <fullName>Standing_Material_Group_1</fullName>
                <isActive>false</isActive>
                <label>Standing Material Group 1</label>
            </value>
            <value>
                <fullName>Standing_Material_Number</fullName>
                <isActive>false</isActive>
                <label>Standing Material Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Hierarchy__c/fields/Approver_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level_1__c</fullName>
    <description>This field denotes level 1 approval user.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver (Level 1)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Hierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related opportunity</description>
    <inlineHelpText>Related parent opportunity under which this Quote is created.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>R00N70000001yUfDEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <description>Lookup to distributor account</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Third party that purchases from Illumina to resell its products</inlineHelpText>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations (Distributor)</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Indirect_Transregion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Transregion_Flag__c</fullName>
    <description>Flag to check Indirect transregion </description>
    <formula>If (
    AND ( 
        OR (
            Apttus_Proposal__Opportunity__r.RecordType.DeveloperName = $Label.IndirectFieldServices,
            Apttus_Proposal__Opportunity__r.RecordType.DeveloperName = $Label.IndirectReOrder,
            Apttus_Proposal__Opportunity__r.RecordType.DeveloperName = $Label.OpportunityRTIndirectStandard
        ), 
         Distributor__r.Territory_Region__c != null,
         Ultimate_Consignee__r.Territory_Region__c != null,
         Distributor__r.Territory_Region__c != Ultimate_Consignee__r.Territory_Region__c 
    ),
   true,
   false )</formula>
    <label>Indirect Transregion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Is_Updated_By_System__c.field-meta.xml
<CustomField>
    <fullName>Is_Updated_By_System__c</fullName>
    <description>Flag to check is updated by system</description>
    <defaultValue>false</defaultValue>
    <label>Is Updated By System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Transborder_Flag__c.field-meta.xml
<CustomField>
    <fullName>Transborder_Flag__c</fullName>
    <description>Flag to check opportunity Transborder Flag</description>
    <formula>Apttus_Proposal__Opportunity__r.Transborder_Flag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transborder Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Lookup to Account for Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Ultimate_Consignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Segment__c/Market_Segment__c.object-meta.xml
<CustomObject>
    <description>Stores information on account&apos;s market segment, sub-segment and allocated percent if more than one is assigned</description>
    <label>Market Segment</label>
    <nameField>
        <displayFormat>MS-{000000}{MMDDYYYY}</displayFormat>
        <label>Market Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segment__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>Stores information of account's market segment</description>
    <label>Market Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Clinical_Type__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Type__c</fullName>
    <description>As part of DCP-1298 for Clinical Type Information.</description>
    <inlineHelpText>When applicable, indicates nature of entity's work within the clinical space; value defaulted from Ultimate Consignee, but can be opportunity-specific and adjusted if needed. Required throughout opportunity lifecycle.  Terms and regional use:  "Clinical" (All); "Non Clinical" (All); "Healthcare Prime" (AMR); "IVD Partner" (GC); "Platform Distributor" (GC).</inlineHelpText>
    <label>Clinical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clinical_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Distributor Account</description>
    <inlineHelpText>Name of distributor required.  For standard indirect transactions, sold to and distributor should be the same except when affiliates are &quot;sold to&quot;.  For direct to UC transactions, distributor is the distributor who brokers the deal and earns the rebate.</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND (4 OR 5)) OR (3 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.Account_Group__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS</value>
        </filterItems>
        <filterItems>
            <field>$User.FirstName</field>
            <operation>equals</operation>
            <value>GIS Data Update</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Data Migration</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>Illumina</value>
        </filterItems>
        <filterItems>
            <field>$User.LastName</field>
            <operation>equals</operation>
            <value>(Qtly/Weekly)</value>
        </filterItems>
        <infoMessage>You can only associate distributor type of account to this field. Search results only display distributor  type of  accounts tied to this opportunity.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Distributor_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Updated_By_System__c.field-meta.xml
<CustomField>
    <fullName>Is_Updated_By_System__c</fullName>
    <description>Checkbox field to check if the record is updated by system</description>
    <defaultValue>false</defaultValue>
    <label>Is Updated By System</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>As part of DCP-1298 for the possible values of Segments of the market.</description>
    <inlineHelpText>Primary scientific application area(s) in which entity is focused; value defaulted from Ultimate Consignee, but can be opportunity-specific and adjusted, if needed. Required throughout opportunity lifecycle; drives commissions.</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transborder_Flag__c.field-meta.xml
<CustomField>
    <fullName>Transborder_Flag__c</fullName>
    <description>Checkbox for Transborder Flag</description>
    <defaultValue>false</defaultValue>
    <label>Transborder Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As part of DCP-1298 for capturing the end user for the opportunity
Automated/Manual.</description>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Clinical_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Non Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Prime</fullName>
    </customValue>
    <customValue>
        <fullName>IVD Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Distributor</fullName>
    </customValue>
    <description>As part of DCP-1298 for Clinical Type information.</description>
    <masterLabel>Clinical Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agrigenomics</fullName>
    </customValue>
    <customValue>
        <fullName>Cancer Research</fullName>
    </customValue>
    <customValue>
        <fullName>Cell and Molecular Biology Research</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Forensics</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Research</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Infectious Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Reproductive Health</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Training/Education</fullName>
    </customValue>
    <customValue>
        <fullName>Transplant genomics</fullName>
        <isActive>false</isActive>
        <label>Transplant Genomics</label>
    </customValue>
    <customValue>
        <fullName>Preconception and Fertility</fullName>
        <isActive>false</isActive>
        <label>Preconception and Fertility</label>
    </customValue>
    <customValue>
        <fullName>Public Health Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology/Virology Research</fullName>
        <isActive>false</isActive>
        <label>Microbiology/Virology Research</label>
    </customValue>
    <customValue>
        <fullName>Genetic &amp; Complex Disease Research</fullName>
        <isActive>false</isActive>
        <label>Genetic &amp; Complex Disease Research</label>
    </customValue>
    <customValue>
        <fullName>Clinical Oncology</fullName>
        <isActive>false</isActive>
        <label>Clinical Oncology</label>
    </customValue>
    <customValue>
        <fullName>Cellular and Molecular Research</fullName>
        <isActive>false</isActive>
        <label>Cellular and Molecular Research</label>
    </customValue>
    <customValue>
        <fullName>Agricultural Genomics</fullName>
        <isActive>false</isActive>
        <label>Agricultural Genomics</label>
    </customValue>
    <customValue>
        <fullName>Pregnancy</fullName>
        <isActive>false</isActive>
        <label>Pregnancy</label>
    </customValue>
    <description>As part of DCP-1298 for the possible values of Primary Segments of the market.</description>
    <masterLabel>Market Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/OpportunitiesHelper.cls
/**
*    Author        Rishab
*    Date          2021-04-05
*    Description   Opportunity Helper class
*    Test Class     TestOpportunities
*    Modification Log:
*    ------------------------------------------------------------------------------------------------------------------------------------------------
*     Developer                      Date                Description
*     Rishab Wali                    05-Apr-2021         Initial Version 
*     Khushbu                        04-Sept-2022        DCP-56658- get accounthierarchy data to populate approval hierarchy owner
*     Rajbabu Boopalan               04-Nov-2023         CMCM-4516 CPU Timeout error on submit for approval
*     Raja Babu                      26-June-2024        PRB0048852 Method Name: updateCloseDateToToday:- Duplicate Renewal Opportunity for Informatic opportunity
*    ------------------------------------------------------------------------------------------------------------------------------------------------
*/
public with sharing class OpportunitiesHelper {

    private static Map<Id, Schema.RecordTypeInfo> idToRecordType;
    public static final Set<String> DIRECT_RECORD_TYPES = new Set<String> { Label.OpportunityRTDirectFieldServices, Label.OpportunityRTDirectReOrder, Label.OpportunityRTDirectStandard };
    public static final Set<String> INDIRECT_RECORD_TYPES = new Set<String> { Label.OpportunityRTIndirectStandard, Label.IndirectReOrder, Label.IndirectFieldServices };
    public static Map<Id, Id> mapOwnerIdApprovalHierarchy = new Map<Id, Id>();

    /* Method to get recordId map*/ 
    public static Map<Id, Schema.RecordTypeInfo> getIdToRecordType()
    {
        if (idToRecordType == null) { idToRecordType = Opportunity.sObjectType.getDescribe().getRecordTypeInfosById(); }
        return idToRecordType;
    }

    /*Method to Update Market Segment and Clinical Type */
    public static void updateMarketSegmentClinicalType(List<Opportunity> oppList , Map<Id,Opportunity> oldOpportunityMap)
    {
        Set<Id> ucIdSet = new Set<Id>();
        Set<Id> oppUpdateIdSet = new Set<Id>(); 

        for(Opportunity opp : oppList)
        {
            if(opp.Ultimate_Consignee__c != null  && opp.Ultimate_Consignee__c != oldOpportunityMap.get(opp.Id).Ultimate_Consignee__c)
            {
                ucIdSet.add(opp.Ultimate_Consignee__c);
                oppUpdateIdSet.add(opp.Id);
            }
        }

        if(!ucIdSet.isEmpty())
        {
            Map<Id,Account> accIdToAccountMap = new Map<Id,Account>(new AccountsSelector().selectAccounts(ucIdSet));
            for(Opportunity oppty : oppList)
            {
                if(accIdToAccountMap.containsKey(oppty.Ultimate_Consignee__c))
                { 
                    updateOppClinicalType(oppty, accIdToAccountMap);
                    if(accIdToAccountMap.get(oppty.Ultimate_Consignee__c).Market_Segment__c == Opportunities.UCMARKETSEGMENTMULTIPLE)
                    {
                        oppty.Is_Updated_By_System__c = true;
                        oppty.Market_Segment__c = null; 
                    }
                    else
                    {
                        oppty.Market_Segment__c = accIdToAccountMap.get(oppty.Ultimate_Consignee__c).Market_Segment__c;
                    } 
                }
            }
        }
    }

    /*Method to Update Opportunity Fields from Ultimate Consignee */
    public static void updateOpportunityFromUltimateConsignee(List<Opportunity> lstOpportunity)
    {
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> opportunityIdWithUCBlankSet = new Set<Id>();
        Set<Id> opportunityIdWithoutUCBlankSet = new Set<Id>();
        Set<Id> opportunityIdWithMarketSegmentBlankSet = new Set<Id>();
        for(Opportunity opp : lstOpportunity)
        {
            if(opp.AccountId != null && opp.Ultimate_Consignee__c == null 
              && (getIdToRecordType().get(opp.RecordTypeId).getDeveloperName() == System.Label.FieldServices
              || getIdToRecordType().get(opp.RecordTypeId).getDeveloperName() == System.Label.OpportunityRTDirectReOrder
              || getIdToRecordType().get(opp.RecordTypeId).getDeveloperName() == System.Label.OpportunityRTDirectStandard) 
              )
              {
                  opp.Ultimate_Consignee__c = opp.AccountId;
                  accountIdSet.add(opp.AccountId);
                  opportunityIdWithUCBlankSet.add(opp.Id);
              }
              if(opp.Ultimate_Consignee__c != null && String.isBlank(opp.Clinical_Type__c))
              {
                accountIdSet.add(opp.Ultimate_Consignee__c);
                opportunityIdWithoutUCBlankSet.add(opp.Id);
              }
              if(opp.Ultimate_Consignee__c != null && String.isBlank(opp.Market_Segment__c))
              {
                accountIdSet.add(opp.Ultimate_Consignee__c);
                opportunityIdWithMarketSegmentBlankSet.add(opp.Id);
              }
        }

        if(!accountIdSet.isEmpty())
        {
            Map<Id,Account> accIdToAccountMap = new Map<Id,Account>(new AccountsSelector().selectAccounts(accountIdSet));
            for(Opportunity oppty : lstOpportunity)
            {
                updateOpprtunityFields(oppty, accIdToAccountMap, opportunityIdWithUCBlankSet, opportunityIdWithoutUCBlankSet, opportunityIdWithMarketSegmentBlankSet);
            }
        }
    }

    /* method to update Opportunity fields*/
    private static void updateOpprtunityFields(Opportunity oppty, Map<Id,Account> accIdToAccountMap, 
                                    Set<Id> opportunityIdWithUCBlankSet, Set<Id> opportunityIdWithoutUCBlankSet,
                                    Set<Id> opportunityIdWithMarketSegmentBlankSet) {
        

        if(opportunityIdWithUCBlankSet.contains(oppty.Id) && accIdToAccountMap.containsKey(oppty.AccountId))
        {
            oppty.Clinical_Type__c = accIdToAccountMap.get(oppty.AccountId).Clinical_Type__c;
        }
        if(opportunityIdWithoutUCBlankSet.contains(oppty.Id) && accIdToAccountMap.containsKey(oppty.Ultimate_Consignee__c))
        {
            oppty.Clinical_Type__c = accIdToAccountMap.get(oppty.Ultimate_Consignee__c).Clinical_Type__c;
        }
        if(opportunityIdWithMarketSegmentBlankSet.contains(oppty.Id) && accIdToAccountMap.containsKey(oppty.Ultimate_Consignee__c))
        {
            Account objOppUC = accIdToAccountMap.get(oppty.Ultimate_Consignee__c);
            if(objOppUC.Market_Segment__c != Opportunities.UCMARKETSEGMENTMULTIPLE && String.isNotBlank(objOppUC.Market_Segment__c))
            {
                oppty.Market_Segment__c = objOppUC.Market_Segment__c;
            }
        }
    }

    /*Method to update Opp Clinical Type*/
    private static void updateOppClinicalType(Opportunity oppty, Map<Id,Account> accIdToAccountMap) 
    {
        if(oppty.Clinical_Type__c != accIdToAccountMap.get(oppty.Ultimate_Consignee__c).Clinical_Type__c)
        {
            oppty.Clinical_Type__c = accIdToAccountMap.get(oppty.Ultimate_Consignee__c).Clinical_Type__c;
        }
    }

    /**
     *  @author Khushbu Vasani
     *  @description  Method to return approval hierarchy record id DCP-56658
     *  @parameter Opp and Quote/Proposal
     *  @return  owner id of account
     **/
    public static Id getAccountHierarchy(Id accountOwnerID)
    { 
        getApprovalHierarchyData();
        
        if(mapOwnerIdApprovalHierarchy.containsKey(accountOwnerID))
        {
            return mapOwnerIdApprovalHierarchy.get(accountOwnerID);
        }
        return null;
    }

     /**
     *  @author Khushbu Vasani
     *  @description  Method to return account owner DCP-56658
     *  @parameter Opp and Quote/Proposal
     *  @return  owner id of account
     **/
    public static Id getAccountOwnerId(Opportunity objOpp, Apttus_Proposal__Proposal__c objProposal)
    {
        boolean booIndirectDeal = INDIRECT_RECORD_TYPES.contains(objOpp.RecordType.DeveloperName);
        
        Id accountOwnerID;
        if(objOpp.Transborder_Flag__c || objProposal.Indirect_Transregion_Flag__c)
        {
            if (booIndirectDeal)
            {
                accountOwnerID = objOpp.Distributor__r.Owner.Id;
            }
            else
            {
                accountOwnerID = objOpp.Ultimate_Consignee__r.Owner.Id;
            }
        }
        else
        {
            if (booIndirectDeal) 
            {
                accountOwnerID = objOpp.Ultimate_Consignee__r.Owner.Id;
            }
            else
            {
                accountOwnerID = objOpp.Account.Owner.Id;
            }
        }

        return accountOwnerID;
    }

     /**
     *  @author Khushbu Vasani
     *  @description  Method to return account owner DCP-56658
     *  @parameter Opp and Quote/Proposal
     *  @return  owner id of account
     **/
    public static Account getAccountIdBasedOnProposal(Apttus_Proposal__Proposal__c objProposal)
    {
        boolean booIndirectDeal = INDIRECT_RECORD_TYPES.contains(objProposal.Apttus_Proposal__Opportunity__r.RecordType.DeveloperName);
       
        Account accountId;
        if(objProposal.Apttus_Proposal__Opportunity__r.Transborder_Flag__c || objProposal.Indirect_Transregion_Flag__c)
        {
            if (booIndirectDeal)
            {
                accountId = objProposal.Apttus_Proposal__Opportunity__r.Distributor__r;
            }
            else
            {
                accountId = objProposal.Apttus_Proposal__Opportunity__r.Ultimate_Consignee__r;
            }
        }
        else
        {
            if (booIndirectDeal) 
            {
                accountId = objProposal.Apttus_Proposal__Opportunity__r.Ultimate_Consignee__r;
            }
            else
            {
                accountId = objProposal.Apttus_Proposal__Opportunity__r.Account;
            }
        }

        return accountId;
    }

    private static void getApprovalHierarchyData()
    {       
        if (mapOwnerIdApprovalHierarchy.isEmpty())
        {
            //CMCM-4516
            List<Approval_Hierarchy__c> lstApprovalHierarchy = new ApprovalHierarchiesSelector().selectAllRecords();
            //List<Approval_Hierarchy__c> lstApprovalHierarchy = selectAllRecords();
           
            for(Approval_Hierarchy__c objApprovalHierarchy : lstApprovalHierarchy)
            {
                if(!mapOwnerIdApprovalHierarchy.containsKey(objApprovalHierarchy.Approver_Level_1__c))
                {
                    if(Label.CPQ_Sales_Hierarchy.equals(objApprovalHierarchy.Approval_Hierarchy_Type__c)){
                        mapOwnerIdApprovalHierarchy.put(objApprovalHierarchy.Approver_Level_1__c, objApprovalHierarchy.Id);
                    }
                }
            }
        }
    }

    /**
     *  @author Raja Babu
     *  @description  convert workflow Opportunity: Update Close Date For Closed Opportunity
     *  @parameter NewOppList and mapOfOldOpp
     *  @return  CloseDate
     **/
    public static void updateCloseDateToToday(List<Opportunity> lstOpps, Map<Id,Opportunity> idToOldOpps){
        for(Opportunity opp:lstOpps){
            if(opp.stageName != idToOldOpps.get(opp.Id).stageName && Opportunities.OPPTY_CLOSED_STAGES.contains(opp.StageName)){
                opp.closeDate = date.today();
            }
        }
    }

    //CMCM-4516
    /*private static List<Approval_Hierarchy__c> selectAllRecords() {
        return [
            SELECT 
            id,
            Approver_Level_1__c,
            Approver_Level_2__c, 
            Approver_Level_3__c, 
            Approver_Level_4__c, 
            Approver_Level_5__c, 
            Approver_Level_6__c,
            Approval_Hierarchy_Type__c
            FROM Approval_Hierarchy__c
        ];
    }*/
}