force-app/main/default/objects/Account/fields/Clinical_Oncology_Screening_Dx_Testing__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Oncology_Screening_Dx_Testing__c</fullName>
    <description>Check if the customer perform screening/diagnostic tests in clinical oncology</description>
    <inlineHelpText>Does the company (or account) use or will in the near future use Illumina sequencing products to perform screening or diagnostic tests in clinical oncology (on human samples), or manufacture kits for such screening/testing?</inlineHelpText>
    <label>Clinical Oncology Screening/Dx Testing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categorical_Value</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/For_Profit_Company__c.field-meta.xml
<CustomField>
    <fullName>For_Profit_Company__c</fullName>
    <description>Is the Company Profit Company(excludes governments, government agencies, hospitals, research institutes, academic institutions, non-profit)</description>
    <inlineHelpText>Is the company (or account) a for-profit laboratory (excluding government, government agencies, hospitals, research institutes, academic institutes, and non-profits), or kit manufacturer?</inlineHelpText>
    <label>For-Profit Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categorical_Value</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/Apttus__AgreementLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Approval_Category__c.field-meta.xml
<CustomField>
    <fullName>Approval_Category__c</fullName>
    <description>Sets the Approval Category that needs to be fired for the Line Item</description>
    <label>Approval Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Material_Group</fullName>
                <label>Material Group</label>
            </value>
            <value>
                <fullName>Material_Number</fullName>
                <label>Material Number</label>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Material_Group_Custom</fullName>
                <label>Material Group Custom</label>
            </value>
            <value>
                <fullName>Material_Number_Custom</fullName>
                <label>Material Number Custom</label>
            </value>
            <value>
                <fullName>Discount_Custom</fullName>
                <label>Discount Custom</label>
            </value>
            <value>
                <fullName>MFN_Approvals</fullName>
                <label>MFN Approvals</label>
            </value>
            <value>
                <fullName>Standing_Discount</fullName>
                <isActive>false</isActive>
                <label>Standing_Discount</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__EndDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__EndDate__c</fullName>
    <description>The end date for products and services</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__ItemSequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__ItemSequence__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The sequence of items belonging to a line</description>
    <label>Item Sequence</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__LineNumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__LineNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The line number</description>
    <label>Line Number</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_CMConfig__StartDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMConfig__StartDate__c</fullName>
    <description>The start date for products and services</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Customer_ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_ERP_Number__c</fullName>
    <description>Field to store ERP Number of Customer Account</description>
    <label>Customer ERP Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Discontinued__c.field-meta.xml
<CustomField>
    <fullName>Discontinued__c</fullName>
    <description>Picklist field to indicate whether a line item is Discontinued</description>
    <label>Discontinued?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount applied to Line Item</description>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <description>Type of Discount applied like % Discount, Fixed Price etc.</description>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Field to populate Distribution Channel : 01/02</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <description>Specifies type of line added. Ex: Material Group 1</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Material Group 1</fullName>
            </value>
            <value>
                <fullName>Price Group - Material</fullName>
            </value>
            <value>
                <fullName>Price Group - Material Group 1</fullName>
            </value>
            <value>
                <fullName>Quota</fullName>
            </value>
            <value>
                <fullName>UC - Material</fullName>
            </value>
            <value>
                <fullName>UC - Material Group 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Material_Group_1__c.field-meta.xml
<CustomField>
    <fullName>Material_Group_1__c</fullName>
    <description>Field to store Material Group of product</description>
    <label>Material Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Group_1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>Field to store Material Number of product</description>
    <label>Material Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Field to store Sales Org</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Field to store Distribution Channel</description>
    <formula>IF(
OR( 
ISPICKVAL(Apttus__Account__r.Account_Group__c,&quot;Distributor&quot;),
AND(ISPICKVAL(Apttus__Account__r.Account_Group__c,&quot;Prospect&quot;),  NOT(ISBLANK(TEXT(Apttus__Account__r.Channel_Partner_Type__c))))
),
&apos;02&apos;,&apos;01&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distribution Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Field to store Sales Org</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Submit_For_Approval__c.field-meta.xml
<CustomField>
    <fullName>Submit_For_Approval__c</fullName>
    <description>Button to submit Agreement for approval</description>
    <formula>IF(
AND (
OR(
ISPICKVAL( Apttus_Approval__Approval_Status__c , &apos;Approval Required&apos;),
ISPICKVAL(Apttus_Approval__Approval_Status__c , &apos;Not Submitted&apos;)
),
Approval_Matrix_Not_Found__c&lt;&gt; True,
Approval_Hierarchy_Not_Found__c &lt;&gt; True,
Is_Agreement_under_Approvals_submission__c &lt;&gt; True
),
IF(
AND(

RecordType.DeveloperName == $Label.AgreementRecordTypeDevNameOpenOffer,
Apttus__Account__r.Open_Offer_Comparison_Customer__c &lt;&gt; true
),
$Label.ErrorMessageForOpenOfferAgreement,
IF(Number_Of_Agreement_Line_Items__c &gt; 0,
IF(
OR(
AND(
RecordType.DeveloperName == $Label.RecordTypeChannelPartnerAgreement,
OR($Permission.SL_Allow_CP_Agreement_Submission,$Profile.Name ==$Label.Profile_System_Administrator)
),
RecordType.DeveloperName != $Label.RecordTypeChannelPartnerAgreement
), HYPERLINK(&quot;/apex/Apttus_Approval__PreviewSubmitApprovals?Id=&quot;&amp;Id, IMAGE(&quot;/resource/Apttus_Proposal__Button_SubmitForApproval&quot;, &quot;Submit For Approval&quot;),&quot;_self&quot;),NULL
),

IF(
AND(
OR(
AND(
RecordType.DeveloperName == $Label.RecordTypeChannelPartnerAgreement,
OR($Permission.SL_Allow_CP_Agreement_Submission,$Profile.Name ==$Label.Profile_System_Administrator)
),
RecordType.DeveloperName != $Label.RecordTypeChannelPartnerAgreement
),
ISPICKVAL(Line_Items_Required_Optional__c,&apos;Optional&apos;)
), HYPERLINK(&quot;/apex/Apttus_Approval__PreviewSubmitApprovals?Id=&quot;&amp;Id, IMAGE(&quot;/resource/Apttus_Proposal__Button_SubmitForApproval&quot;, &quot;Submit For Approval&quot;),&quot;_self&quot;),
IF(
AND(
AND(
RecordType.DeveloperName == $Label.RecordTypeChannelPartnerAgreement,
AND(NOT($Permission.SL_Allow_CP_Agreement_Submission),$Profile.Name &lt;&gt;$Label.Profile_System_Administrator)
),
ISPICKVAL(Line_Items_Required_Optional__c,&apos;Optional&apos;)
)
,null,
$Label.UI_Error_Message_To_Upload_Agreement_Line_Items_For_Approval)

)

)
),
IF(
AND(
ISPICKVAL( Apttus_Approval__Approval_Status__c , &apos;Approved&apos;),
Approval_Matrix_Not_Found__c &lt;&gt; True,
Approval_Hierarchy_Not_Found__c &lt;&gt; True,
RecordType.DeveloperName &lt;&gt; $Label.AgreementRecordTypeDevNameOpenOffer

),
$Label.NoApprovalRequiredIfApproved,
IF(
AND(
Approval_Hierarchy_Not_Found__c == True,
Approval_Matrix_Not_Found__c&lt;&gt; True,
RecordType.DeveloperName &lt;&gt; $Label.AgreementRecordTypeDevNameOpenOffer

),
$Label.UI_ErrorMessageAgreementApprovalHierarchyNotFound,
IF(
AND(    
Approval_Matrix_Not_Found__c== True,
RecordType.DeveloperName &lt;&gt; $Label.AgreementRecordTypeDevNameOpenOffer
),
$Label.UI_ErrorMessageAgreementApprovalMatrixNotFound,
null
)
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Submit For Approval</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Material_Group_1__c.field-meta.xml
<CustomField>
    <fullName>Material_Group_1__c</fullName>
    <description>Field to store Material Group.</description>
    <label>Material Group 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>US-439
Product’s material number
Populated from SAP</description>
    <externalId>true</externalId>
    <label>Material Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Categorical_Value.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>Categorical Value</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material_Group_1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AIM</fullName>
    </customValue>
    <customValue>
        <fullName>AIP</fullName>
    </customValue>
    <customValue>
        <fullName>AIR</fullName>
    </customValue>
    <customValue>
        <fullName>AIS</fullName>
    </customValue>
    <customValue>
        <fullName>ASQ</fullName>
    </customValue>
    <customValue>
        <fullName>BG1</fullName>
    </customValue>
    <customValue>
        <fullName>BGS</fullName>
    </customValue>
    <customValue>
        <fullName>BSC</fullName>
    </customValue>
    <customValue>
        <fullName>CGA</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <customValue>
        <fullName>CRT</fullName>
    </customValue>
    <customValue>
        <fullName>CSP</fullName>
    </customValue>
    <customValue>
        <fullName>CU1</fullName>
    </customValue>
    <customValue>
        <fullName>DLP</fullName>
    </customValue>
    <customValue>
        <fullName>ELP</fullName>
    </customValue>
    <customValue>
        <fullName>EP1</fullName>
    </customValue>
    <customValue>
        <fullName>FTS</fullName>
    </customValue>
    <customValue>
        <fullName>GEX</fullName>
    </customValue>
    <customValue>
        <fullName>GGA</fullName>
    </customValue>
    <customValue>
        <fullName>GGG</fullName>
    </customValue>
    <customValue>
        <fullName>GLS</fullName>
    </customValue>
    <customValue>
        <fullName>GNS</fullName>
    </customValue>
    <customValue>
        <fullName>GSC</fullName>
    </customValue>
    <customValue>
        <fullName>HLS</fullName>
    </customValue>
    <customValue>
        <fullName>HWA</fullName>
    </customValue>
    <customValue>
        <fullName>HX1</fullName>
    </customValue>
    <customValue>
        <fullName>ICP</fullName>
    </customValue>
    <customValue>
        <fullName>IMQ</fullName>
    </customValue>
    <customValue>
        <fullName>IMS</fullName>
    </customValue>
    <customValue>
        <fullName>INF</fullName>
    </customValue>
    <masterLabel>Material Group 1</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>AT01</fullName>
    </customValue>
    <customValue>
        <fullName>AU01</fullName>
    </customValue>
    <customValue>
        <fullName>BE01</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
    </customValue>
    <customValue>
        <fullName>CN01</fullName>
    </customValue>
    <customValue>
        <fullName>CN02</fullName>
    </customValue>
    <customValue>
        <fullName>CN03</fullName>
    </customValue>
    <customValue>
        <fullName>DE01</fullName>
    </customValue>
    <customValue>
        <fullName>CO01</fullName>
    </customValue>
    <customValue>
        <fullName>DK01</fullName>
    </customValue>
    <customValue>
        <fullName>ES01</fullName>
    </customValue>
    <customValue>
        <fullName>FI01</fullName>
    </customValue>
    <customValue>
        <fullName>FR01</fullName>
    </customValue>
    <customValue>
        <fullName>FR02</fullName>
    </customValue>
    <customValue>
        <fullName>FR90</fullName>
    </customValue>
    <customValue>
        <fullName>GB01</fullName>
    </customValue>
    <customValue>
        <fullName>GB02</fullName>
    </customValue>
    <customValue>
        <fullName>GB03</fullName>
    </customValue>
    <customValue>
        <fullName>GB90</fullName>
    </customValue>
    <customValue>
        <fullName>HK01</fullName>
    </customValue>
	<customValue>
        <fullName>IE01</fullName>
    </customValue> 
	<customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IS01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>JP01</fullName>
    </customValue>
    <customValue>
        <fullName>KR01</fullName>
    </customValue>
    <customValue>
        <fullName>NL01</fullName>
    </customValue>
    <masterLabel>Sales Org</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TestApprovalsAgreementLineMFN.cls
/**
*    @author Bharath Varma
*    @date   2021-12-07
*    @description    DCP-50961: Test class for ApprovalsAgreementLineMFN
*    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------
*         Developer                      Date                Description         
*         Bharath Varma                2021-12-07           Initial Version
*    ---------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public with sharing class TestApprovalsAgreementLineMFN {

    public static FINAL string PERDISCOUNT = '% Discount';
    public static FINAL string MATGRPAIP = 'AIP';

    @testSetup
    static void setupData() {
        TestDataApprovals.getSupportDataForAgreementApprovals();
    }


    private static List<Product2> getProducts()
    {
        Product2 objProduct2 = TestDataMaster.createProduct(false);
        objProduct2.Material_Group_1__c = TestDataApprovals.MATERIAL_GROUP_AIP;
        objProduct2.Material_Number__c = '20028871'; 

        Product2 objProduct3 = TestDataMaster.createProduct(false);
        objProduct3.Material_Group_1__c = TestDataApprovals.MATERIAL_GROUP_AIP;
        objProduct3.Material_Number__c = '20028318'; 
        
        Product2 objProduct4 = TestDataMaster.createProduct(false);
        objProduct4.Material_Group_1__c = TestDataApprovals.MATERIAL_GROUP_AIP; 
        objProduct4.Material_Number__c = '20024913'; 

        return new List<Product2>{objProduct2,objProduct3,objProduct4};
    }

     @isTest
    static void testMFNApprovals()
    { 
        ApttusAgreementLineItems.useOldFrameworkWhileTesting = false;
        Feature.setMockFeatureFlag('SalesCLMApprovalsPipeline', true);

        Account acc = [Select Id, Clinical_Oncology_Screening_Dx_Testing__c, For_Profit_Company__c, BillingCountry, BillingState From Account Where ERP_Customer_Id__c = '234567'];
        acc.Clinical_Oncology_Screening_Dx_Testing__c = 'Yes';
        acc.For_Profit_Company__c = 'Yes';
        acc.BillingCountry = 'USA';
        acc.BillingState = 'Texas';

        update acc;
        system.debug('%& acc'+acc); 

        List<Product2> products = getProducts();
        insert products;

        Apttus__APTS_Agreement__c objAgreement = [Select Id,Submit_For_Approval__c FROM Apttus__APTS_Agreement__c WHERE Name = 'Test Agreement - Price Group' ];

        List<Apttus__AgreementLineItem__c> agreementLines = new List<Apttus__AgreementLineItem__c>();

        for(Product2 product : products)
        {
            Apttus__AgreementLineItem__c objAgreementLineItem2 = TestDataAgreement.initAgreementsLineItem(objAgreement.Id);
            objAgreementLineItem2.Material_Number__c = product.Material_Number__c;
            objAgreementLineItem2.Material_Group_1__c = MATGRPAIP;
            objAgreementLineItem2.Line_Type__c = 'Material';
            objAgreementLineItem2.Apttus_CMConfig__LineNumber__c = 1;
            objAgreementLineItem2.Apttus_CMConfig__ItemSequence__c = 1;
            objAgreementLineItem2.Discount_Type__c = PERDISCOUNT ;
            objAgreementLineItem2.Customer_ERP_Number__c = '123456';
            objAgreementLineItem2.Sales_Org__c = 'HK01';
            objAgreementLineItem2.Distribution_Channel__c = '01';
            objAgreementLineItem2.CurrencyIsoCode= 'USD';
            objAgreementLineItem2.Discount__c = 45;
            objAgreementLineItem2.Discontinued__c = 'No';
            objAgreementLineItem2.Apttus_CMConfig__StartDate__c=system.today()+1;
            objAgreementLineItem2.Apttus_CMConfig__EndDate__c=system.today()+2;

            agreementLines.add(objAgreementLineItem2);
        }

        Test.startTest();
        insert agreementLines;

        acc.BillingCountry = 'Germany';
        update acc;

        for(Apttus__AgreementLineItem__c agreementLine : agreementLines)
        {
            agreementLine.Discount__c = 47;
        }

        update agreementLines;
        
        Test.stopTest();
        Apttus__AgreementLineItem__c objAgrUpd = [Select Id, Approval_Category__c from Apttus__AgreementLineItem__c where Apttus__AgreementId__c = :objAgreement.Id LIMIT 1];
        system.assert(objAgrUpd.Approval_Category__c != null, 'Approvals did not fire');
    }

   
}