force-app/main/default/objects/Account/fields/Country_Local__c.field-meta.xml
<CustomField>
    <fullName>Country_Local__c</fullName>
    <description>Local Address Country Information as part of DCP-760</description>
    <inlineHelpText>Address country in local language.</inlineHelpText>
    <label>Country (Local)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Field to indicate District of Territory associated to Account</description>
    <inlineHelpText>Indicates territory rollup.</inlineHelpText>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>Field to store Primary language in which entity transacts</description>
    <inlineHelpText>Primary language in which entity transacts; determines language output for quoting.</inlineHelpText>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Field to display internal Illumina Territory Region</description>
    <inlineHelpText>Internal Illumina territory region.</inlineHelpText>
    <label>Territory Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Id__c</fullName>
    <description>Field that gets the id of the highest level parent in the current account hierarchy using the standard Parent Account Lookup</description>
    <formula>IF ( 
NOT ( 
ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.ParentId)
), 
Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.ParentId, 
IF ( 
NOT ( 
ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.ParentId)
), 
Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.ParentId, 
IF ( 
NOT (
ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.ParentId) 
), 
Parent.Parent.Parent.Parent.Parent.Parent.Parent.ParentId, 
IF ( 
NOT (
ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.ParentId) 
), 
Parent.Parent.Parent.Parent.Parent.Parent.ParentId, 
IF ( 
NOT (
ISBLANK(Parent.Parent.Parent.Parent.Parent.ParentId) 
), 
Parent.Parent.Parent.Parent.Parent.ParentId, 
IF ( 
NOT (
ISBLANK(Parent.Parent.Parent.Parent.ParentId) 
), 
Parent.Parent.Parent.Parent.ParentId, 
IF ( 
NOT ( 
ISBLANK(Parent.Parent.Parent.ParentId) 
), 
Parent.Parent.Parent.ParentId, 
IF ( 
NOT ( 
ISBLANK(Parent.Parent.ParentId) 
), 
Parent.Parent.ParentId, 
IF ( 
NOT ( 
ISBLANK(Parent.ParentId) 
), 
Parent.ParentId, 
IF ( 
NOT ( 
ISBLANK(ParentId) 
), 
ParentId, 
Id
) 
) 
) 
) 
) 
) 
) 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ultimate Parent Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record type is maintained by Master Data for accounts that are upgraded to Sold To or Ultimate Consignee</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Auto filled from Territory district on the account via process builder but manual override is allowed.</description>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Africa District</fullName>
            </value>
            <value>
                <fullName>AMEA No Sync</fullName>
            </value>
            <value>
                <fullName>AMR Broad</fullName>
            </value>            
            <value>
                <fullName>AMR Caris/Veracyte</fullName>
            </value>
            <value>
                <fullName>AMR Distributors</fullName>
            </value>
            <value>
                <fullName>AMR FedGov</fullName>
            </value>
            <value>
                <fullName>AMR Florida Carolinas</fullName>
            </value>
            <value>
                <fullName>AMR FMI/GeneDx</fullName>
            </value>
            <value>
                <fullName>AMR Grail District</fullName>
            </value>
            <value>
                <fullName>AMR Greater Boston</fullName>
            </value>
            <value>
                <fullName>AMR Great Lakes</fullName>
            </value>
            <value>
                <fullName>AMR Guardant/Personalis</fullName>
            </value>
            <value>
                <fullName>AMR Invitae/Adaptive</fullName>
            </value>
            <value>
                <fullName>AMR ISAM Central</fullName>
            </value>
            <value>
                <fullName>AMR ISAM NE</fullName>
            </value>
            <value>
                <fullName>AMR ISAM Pacific</fullName>
            </value>
            <value>
                <fullName>AMR ISAM South</fullName>
            </value>
            <value>
                <fullName>AMR LabCorp/BRL</fullName>
            </value>
            <value>
                <fullName>AMR SoCal HI</fullName>
            </value>
            <value>
                <fullName>AMR Mid Atlantic</fullName>
            </value>
            <value>
                <fullName>AMR Mid South</fullName>
            </value>
            <value>
                <fullName>AMR Mountain Plains</fullName>
            </value>            
            <value>
                <fullName>AMR Myriad/IMH</fullName>
            </value>
            <value>
                <fullName>AMR Natera/TTAM</fullName>
            </value>
            <value>
                <fullName>AMR New York/New England</fullName>
            </value>
            <value>
                <fullName>AMR No Sync</fullName>
            </value>
            <value>
                <fullName>AMR ADNA/Quest</fullName>
            </value>            
            <value>
                <fullName>AMR Ambry/NeoGenomics/BMG</fullName>
            </value>
            <value>
                <fullName>AMR PA NJ DE</fullName>
            </value>
            <value>
                <fullName>AMR SF and East Bay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>To capture the language code from Contact.</description>
    <formula>IF(TEXT(Contact.Preferred_Language__c) = &apos;English&apos;, &apos;en_US&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;Chinese&apos;, &apos;zh_CN&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;French&apos;, &apos;fr&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;German&apos;, &apos;de&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;Italian&apos;, &apos;it&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;Japanese&apos;, &apos;ja&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;Korean&apos;, &apos;ko&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;Portuguese&apos;, &apos;pt_BR&apos;, IF(TEXT(Contact.Preferred_Language__c) = &apos;Spanish&apos;, &apos;es&apos;, &apos;&apos;) ) ) ) ) ) ) ) )</formula>
    <label>Preferred Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Attribution__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Attribution__c</fullName>
    <description>DCP-16865</description>
    <label>Campaign Attribution</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Local__c.field-meta.xml
<CustomField>
    <fullName>Country_Local__c</fullName>
    <description>Created as part of DCP-3000.
Value Source: Value will be entered manually by the user.</description>
    <inlineHelpText>Contact address country in local language.</inlineHelpText>
    <label>Country (Local)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>DCP-857 Indicate the contact is active or not.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Form_Submission_URL__c.field-meta.xml
<CustomField>
    <fullName>Last_Form_Submission_URL__c</fullName>
    <description>Field that captures the website page URL a contact was last on when submitting a Pardot form</description>
    <label>Last Form Submission URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Responded_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Last_Responded_Campaign__c</fullName>
    <description>Field that captures the last campaign a contact is associated to</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Responded Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contacts (Last Responded Campaign)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Responded_Campaign_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Responded_Campaign_Date__c</fullName>
    <description>Field that captures the member date of the last campaign a contact is associated to</description>
    <label>Last Responded Campaign Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Partner_Portal_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Status__c</fullName>
    <description>To capture status of partner portal</description>
    <label>Partner Portal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PGUID__c.field-meta.xml
<CustomField>
    <fullName>PGUID__c</fullName>
    <description>Field that captures Platform users unique identifier</description>
    <externalId>true</externalId>
    <label>PGUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_User_Role__c.field-meta.xml
<CustomField>
   <fullName>Portal_User_Role__c</fullName>
        <description>This field stores the Portal User&apos;s Role associated with the current contact. It gets populated by a process builder when a Portal User is created/modified.</description>
        <label>Portal User Role</label>
        <length>255</length>
        <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>Preferred Language of Contact (Default: English)</description>
    <inlineHelpText>Contact&apos;s preferred language for all Illumina communications.</inlineHelpText>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_And_Contact_Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <description>Multi-select picklist to select Product Interests</description>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Questions_For_Rep__c.field-meta.xml
<CustomField>
    <fullName>Questions_For_Rep__c</fullName>
    <description>Long Text Area field to store Questions for Rep </description>
    <label>Questions For Rep</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Territory Region from Account to Contact</description>
    <formula>Account.Territory_Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Waterfall_Closed_Won_Date__c.field-meta.xml
<CustomField>
    <fullName>Waterfall_Closed_Won_Date__c</fullName>
    <description>Field that captures waterfall stage closed won date for Hive9</description>
    <label>Waterfall Closed Won Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Waterfall_Engaged_Date__c.field-meta.xml
<CustomField>
    <fullName>Waterfall_Engaged_Date__c</fullName>
    <description>Field that captures waterfall stage engaged date for Hive9</description>
    <label>Waterfall Engaged Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Waterfall_Opportunity_Date__c.field-meta.xml
<CustomField>
    <fullName>Waterfall_Opportunity_Date__c</fullName>
    <description>Field that captures waterfall stage when contact is associated to opportunity date for Hive9</description>
    <label>Waterfall Opportunity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Waterfall_Qualified_Date__c.field-meta.xml
<CustomField>
    <fullName>Waterfall_Qualified_Date__c</fullName>
    <description>Field that captures waterfall stage qualfied date for Hive9</description>
    <label>Waterfall Qualified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Software_Download__c/Software_Download__c.object-meta.xml
<CustomObject>
    <description>Software Download object to store data from Software Download Audit records</description>
    <label>Software Download</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Software Downloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Download__c/fields/Contact_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Full_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship To Contact</description>
    <label>Contact Full Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Software Downloads</relationshipLabel>
    <relationshipName>Software_Downloads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Marketing.recordType-meta.xml
<RecordType>
    <fullName>Marketing</fullName>
    <active>true</active>
    <description>Record type for Marketing workstream tasks</description>
    <label>Marketing</label>
</RecordType>

force-app/main/default/globalValueSets/Lead_And_Contact_Preferred_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <description>Created as part of story DCP-13306 . This picklist is to be added on contact and lead object</description>
    <masterLabel>Lead And Contact Preferred Language</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Preferred_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese trad.</fullName>
    </customValue>
    <customValue>
        <fullName>Code Desc Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Croatian</fullName>
    </customValue>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Hebrew</fullName>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
    </customValue>
    <customValue>
        <fullName>Icelandic</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Malay</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consumables</fullName>
    </customValue>
    <customValue>
        <fullName>Instrument</fullName>
    </customValue>
    <customValue>
        <fullName>Service Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Software</fullName>
    </customValue>
    <customValue>
        <fullName>Relocation</fullName>
    </customValue>
    <customValue>
        <fullName>Break Fix</fullName>
    </customValue>
	<customValue>
        <fullName>NIPT</fullName>
    </customValue>
    <customValue>
        <fullName>Arrays</fullName>
    </customValue>
    <customValue>
        <fullName>Sequencing</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Other Services (Including Professional Services)</fullName>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactsSelector.cls
/**
*    @author Roopal Verma
*    @date   2018-09-29
*    @description    DCP-11367: Contact Selector class
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Rahul Bishnoi                 1/7/2019            Fetch the Leads based on PGUID - DCP - 31268
*             Arnab Modak                   20/11/2019          DCP-30953 : Ordered query by "Last Modified" - selectContactsFromAccount()
*             Gopinath Reddy                8/1/2020            DCP-30474 Logic
*             Deep Diwakar                 16-April-2021        DCP-45348: Added customer community contact selector method
*             Deep Diwakar                 July 14 2021         DCP-47095: Adding SOQL instrumentation for all selector queries with
*                                                                 feature flag implementation.
              Saddam Hussain               Aug 23 2021          CMCP-33 Added New Field to Soql to selectLoggedInAccountContacts methodtest
*             Deep Diwakar                 Jan-02-2024          CMCM-4697: Added selector method to query contact with AOW
*             Deep Diwakar                 June-26-2024         CMCM-6457: Added selector method for contacts with waterfall fields
*             Deep Diwakar                 Jul-29-2024          CMCM-7519: Added selector method for querying contacts using task whoid field
*             Deep Diwakar                 Aug-08-2024          CMCM-9421: Added selector method for querying contact fields to move to campaign member
*    ------------------------------------------------------------------------------------
*
*/
public with sharing class ContactsSelector extends ilib_SObjectSelector{

    private final String LOG_TITLE = 'ContactsSelector';
    private static final String MARKETING_QUERY_LOGS = 'MarketingQueryLogs';
    private static final String FIELDS_ACCOUNDID = 'AccountId';
    private static final String EMAIL = 'Email';

    /**Method - get sObjectType */
    public Schema.SObjectType getSObjectType()
    {
        return Contact.sObjectType;
    }

    /**
    *  @author  Roopal Verma
    *  @description Retrieve list of fields for Contact Object
    *  @return sObjectFieldList list of Schema.SObjectField
    **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Contact.id,
            Contact.Email,
            Contact.name,
            Contact.Phone,
			Contact.Is_Active__c,
			Contact.AccountId,
            Contact.Country_Local__c,
            //DCP-30953
           Contact.LastModifiedDate,
           Contact.AccountId,
           Contact.Is_Active__c,
           Contact.Country_Local__c,
           //DCP-30474
           Contact.PGUID__c

        };
    }

    private Boolean removeDefaultOrderBy=false;
    /**
    *  @author Joshith K
    *  @description Override Default name Ordering
    *
    *  @return String for Ordering
    **/
    public override String getOrderBy() {
        if(removeDefaultOrderBy){
            return 'LastModifiedDate DESC';
        }else{
            return super.getOrderBy();
        }

    }

    /**
    *  @author Roopal Verma
    *  @description Fetch the Contact
    *  @param Set of Account Ids
    *  @return List of Contacts
    **/
    public List<Contact> selectContactsFromAccount(Set<Id> setAccountId)
    {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactsFromAccount',UtilsCollection.serializeIds(setAccountId));
        }

        List<Contact> res = (List<Contact>) Database.query(
                                    newQueryFactory().setCondition('Contact.AccountId IN :setAccountId').toSOQL()
        );

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
        }

    /**
    *  @author Roopal Verma
    *  @description Fetch the Contact
    *  @param Set of Account Ids
    *  @return List of Contacts
    **/
    public List<Contact> selectContacts(Set<Id> setContactId)
    {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContacts',UtilsCollection.serializeIds(setContactId));
        }

        List<Contact> res = (List<Contact>) Database.query(
                                    newQueryFactory()
                                    .selectField('Id')
                                    .selectField('Is_Active__c')
                                    .selectField(FIELDS_ACCOUNDID)
                                    .selectField('email')
                                    .selectField('Account.Territory_Region__c')
                                    .selectField('Account.District__c')
                                    //Refactor PB:: Work_Order_Update_Contact_Preferred_Language
                                    .selectField('Preferred_Language__c')
                                    .selectField('FirstName')
                                    .selectField('LastName')
                                    .selectField('MailingCountry')
                                    .selectField('Country_Local__c')
                                    .setCondition('Id IN :setContactId').toSOQL()
        );

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
    }

    /*
    * @author Shaik Moulali
    * @date   10-08-2018
    * @description Fetch list of contacts for logged in Account and based partner portal status
    * @param Pass the Logged In user's Id
    *
    */
    public List<Contact> selectLoggedInAccountContacts(Id accountId, String partnerPortalStatus)
    {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            Set<Id> acctIdSet = new Set<Id>();
            logger = new ilib_LogQuery(LOG_TITLE + '.selectLoggedInAccountContacts',UtilsCollection.serializeIds(acctIdSet));
        }

        ilib_QueryFactory query = newQueryFactory();
        query.setCondition('AccountId = :accountId AND Partner_Portal_Status__c = :partnerPortalStatus');
        String strQuery = query.selectField('id')
            .selectField('Name')
            .selectField('FirstName')
            .selectField('LastName')
            .selectField('Title')
            .selectField('Email')
            .selectField('Partner_Portal_Status__c')
            .selectField(FIELDS_ACCOUNDID)
            .selectField('CreatedDate')
            .selectField('LastModifiedDate')
            .selectField('Portal_User_Role__c')         //cmcp-33 added new role field
        .toSOQL();
        List<Contact> res = Database.query(strQuery);

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
    }

    /*
    * @author Ritika M
    * @date
    * @description Fetch list of contacts for corresponding email addressed
    * @param Set of email addresses
    *
    */
    public List<Contact> selectContactsByEmail(Set<String> setContactEmails)
    {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactsByEmail',UtilsCollection.serializeIds(setContactEmails));
        }

        List<Contact> res = (List<Contact>) Database.query(
                                    newQueryFactory().setCondition('Email IN : setContactEmails').toSOQL()
        );

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
    }


	 /*
    * @author Prakhar K
    * @date 05-Dec-2019
    * @description Fetch contact fields based on web email of Case
    * @param Set of WebEmail addresses on Case object
    *
    */
    public List<Contact> contactsByEmailID(Set<String> setEmails)
    {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.ContactsByEmailID',UtilsCollection.serializeIds(setEmails));
        }

        List<Contact> res = (List<Contact>) Database.query(
                                    newQueryFactory().setCondition('Is_Active__c = true AND Email IN : setEmails').toSOQL()
        );

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
    }


     /*
    * @author Joshith K
    * @date 16-Aug-2019
    * @description Fetch list of contacts and Child Software Downloads for corresponding  email addressed
    * @param Set of email addresses
    *
    */
    public List<Contact> selectContactsWithSftwDwnldByEmail(Set<String> setContactEmails)
    {

        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactsWithSftwDwnldByEmail',UtilsCollection.serializeIds(setContactEmails));
        }

        removeDefaultOrderBy=TRUE;
         ilib_QueryFactory contactQuery = newQueryFactory();
         contactQuery.selectField('FirstName');
         contactQuery.selectField('LastName');
         contactQuery.selectField('MailingCountry');
         contactQuery.selectField('Country_Local__c');
        ilib_QueryFactory softwareQueryFactory = new SoftwareDownloadsSelector().
        addQueryFactorySubselect(contactQuery,'Software_Downloads__r');
        List<Contact> res = (List<Contact>) Database.query(
            contactQuery.setCondition('Email in :setContactEmails').toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
    }

    /**
    *  @author Gopinath
    *  @description Fetch COntact ids to replace pguid ids.
    *  @return List of Contact Ids
    **/
   public List<Contact> selectContactIdsforPGUIDId(set<String> setSapPGUIDIds)
   {
       ilib_LogQuery logger;

       if (Feature.isOn(MARKETING_QUERY_LOGS)){
           logger = new ilib_LogQuery(LOG_TITLE + '.selectContactIdsforPGUIDId',UtilsCollection.serializeIds(setSapPGUIDIds));
       }

       List<Contact> res = (List<Contact>) Database.query(
           newQueryFactory().setCondition('PGUID__c IN : setSapPGUIDIds').toSOQL()
       );

       if (Feature.isOn(MARKETING_QUERY_LOGS)){
           logger.stop(res.size());
       }

       return res;
   }
  /* @author     : Prashanth
	 * @param      : contact Ids
	 * @return     : List of contact Records
	 * @Description: Method that returns list of contacts with AccountcontactRelations assigned to those contacts.
	 **/
    public List<Contact> returnContactWithACRDetails(Set<Id> setContactIds){
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.returnContactWithACRDetails',UtilsCollection.serializeIds(setContactIds));
        }

        ilib_QueryFactory contactQuery = newQueryFactory();
        contactQuery.selectField('Account.Ultimate_Parent_Id__c');
        ilib_QueryFactory acrSubQuery = new AccountContactRelationsSelector().addQueryFactorySubselect(contactQuery,'AccountContactRelations');
        acrSubQuery.selectField('IsDirect');
        List<Contact> res = (List<Contact>)Database.query(contactQuery.setCondition('Id in:setContactIds').toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;
    }
   /* @author     : Monika
     * @param      : contact Ids
     * @return     : Contact Record
     * @Description: Method that returns list of contacts with Account Billing Country.
     **/
    public  Contact returnAccountBillingCountry(Id contactId)
    {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            Set<Id>contactIdSet = new Set<Id>();
            contactIdSet.add(contactId);
            logger = new ilib_LogQuery(LOG_TITLE + '.returnAccountBillingCountry',UtilsCollection.serializeIds(contactIdSet));
        }

        ilib_QueryFactory contactQuery = newQueryFactory();
        contactQuery.selectField('Account.BillingCountry');
    contactQuery.selectField('FirstNameLocal');
        contactQuery.selectField('LastNameLocal');
        Contact res = (Contact)Database.query(contactQuery.setCondition('Id = :contactId').toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop();
        }

        return res;
    }

    /**
     * @author     : Deep Diwakar
     * @param      : Set of email ids
     * @return     : Contact Record
     * @Description: Method that returns list of contacts for customer community specific fields using
                     email id as filter criteria.
    **/
    public List<Contact> selectCustomerCommunityContactsByEmail(Set<String> emailSet) {
        ilib_LogQuery logger;

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger = new ilib_LogQuery(LOG_TITLE + '.selectCustomerCommunityContactsByEmail',UtilsCollection.serializeIds(emailSet));
        }

        List<Contact> res = (List<Contact>) Database.query(newQueryFactory(false)
                                .selectField('Id')
                                .selectField('FirstName')
                                .selectField('LastName')
                                .selectField(EMAIL)
                                .selectField(FIELDS_ACCOUNDID)
                                .selectField('PGUID__c')
                                .selectField('Partner_Portal_Status__c')
                                .setCondition('Email IN : emailSet').setLimit(1000).toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)){
            logger.stop(res.size());
        }

        return res;

    }

    /**
     * @author     : Deep Diwakar
     * @param      : Set of account ids
     * @return     : List of Contact Record
     * @Description: retuns list of contacts with AOW values. It only queries fields specified in the method, doesn't
     *               query default fields. 
    **/
    public List<Contact> selectContactWithAow(Set<Id> setAccountId) {
        ilib_LogQuery logger = new ilib_LogQuery();

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactWithAow',UtilsCollection.serializeIds(setAccountId));
        }

        List<Contact> res = (List<Contact>) Database.query(newQueryFactory(false)
                                .selectField('Id')
                                .selectField(FIELDS_ACCOUNDID)
                                .selectField('Area_Of_Work__c')
                                .setCondition('Contact.AccountId IN : setAccountId').setLimit(1000).toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger.stop(res.size());
        }

        return res;

    }

    /**
     * @author     : Deep Diwakar
     * @param      : Set of contact ids
     * @return     : List of Contact Record
     * @Description: retuns list of contacts with waterfall field values. It only queries fields specified in the method, doesn't
     *               query default fields. 
    **/
    public List<Contact> selectContactsWithWaterfall(Set<Id> setContactIds) {
        ilib_LogQuery logger = new ilib_LogQuery();

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactsWithWaterfall',UtilsCollection.serializeIds(setContactIds));
        }

        List<Contact> res = (List<Contact>) Database.query(newQueryFactory(false)
                                .selectField('Id')
                                .selectField('Waterfall_Stage__c')
                                .selectField('Waterfall_Engaged_Date__c')
                                .selectField('Waterfall_Qualified_Date__c')
                                .selectField('Waterfall_Sales_Accepted_Date__c')
                                .selectField('Waterfall_Opportunity_Date__c')
                                .selectField('Waterfall_Closed_Won_Date__c')
                                .selectField('Last_Responded_Campaign_Date__c')
                                .selectField('Last_Responded_Campaign__c')
                                .setCondition('Id IN : setContactIds').toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger.stop(res.size());
        }

        return res;

    }

    /**
     * @author     : Deep Diwakar
     * @param      : Set of contact ids
     * @return     : List of contact records
     * @Description: retuns list of contacts with field values needed for Marketing task updates. It only queries
     *               fields specified in the method, doesn't query default fields.  
    **/
    public List<Contact> selectContactFieldsForTask(Set<Id> setContactIds) {
        ilib_LogQuery logger = new ilib_LogQuery();

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactFieldsForTask',UtilsCollection.serializeIds(setContactIds));
        }

        List<Contact> res = (List<Contact>) Database.query(newQueryFactory(false)
                                .selectField('Id')
                                .selectField('Product_Interest__c')
                                .selectField('Form_Type__c')
                                .selectField('Last_Form_Submission_URL__c')
                                .selectField('Questions_For_Rep__c')
                                .setCondition('Id IN : setContactIds').toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger.stop(res.size());
        }

        return res;

    }

    /**
     * @author     : Deep Diwakar
     * @param      : Set of contact ids
     * @return     : List of contact records
     * @Description: retuns list of contacts with field values needed for moving to corresponding campaign members. 
     *               It only queries fields specified in the method, doesn't query default fields.  
    **/
    public List<Contact> selectContactsForCampMemberFields(Set<Id> setContactIds) {
        ilib_LogQuery logger = new ilib_LogQuery();

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger = new ilib_LogQuery(LOG_TITLE + '.selectContactsForCampMemberFields',UtilsCollection.serializeIds(setContactIds));
        }

        List<Contact> res = (List<Contact>) Database.query(newQueryFactory(false)
                                .selectField('Id')
                                .selectField(EMAIL)
                                .selectField('Form_Type__c')
                                .selectField('Campaign_Attribution__c')
                                .selectField('Media_Code__c')
                                .setCondition('Id IN : setContactIds').toSOQL());

        if (Feature.isOn(MARKETING_QUERY_LOGS)) {
            logger.stop(res.size());
        }

        return res;

    }

}