force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Field to display internal Illumina Territory Region</description>
    <inlineHelpText>Internal Illumina territory region.</inlineHelpText>
    <label>Territory Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record type is maintained by Master Data for accounts that are upgraded to Sold To or Ultimate Consignee</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account_Sales_Area__c/Account_Sales_Area__c.object-meta.xml
<CustomObject>
    <description>Stores the ERP (SAP) system specific information such as Sales Organization, Distribution Channel, Division and Company Code for the related account. Contains inco terms, pricegroup, pricelist type and terms of payment assigned to the given account</description>
    <label>Account Sales Area</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Account Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Area</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Sales_Area__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to Account.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <description>Field to store Contract Number.</description>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Customer_Master_Data__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master_Data__c</fullName>
    <description>Lookup to Customer Master Data.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master Data</label>
    <referenceTo>Customer_Master_Data__c</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Field to store Price Group.</description>
    <label>Price Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>As part of DCP 10312 to store the price list.</description>
    <label>Price List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_List_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type__c</fullName>
    <description>Field to store Price List Type.</description>
    <label>Price List Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/Apttus__AgreementLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to Account(Sold To)</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreement Line Items (Account)</relationshipLabel>
    <relationshipName>Agreement_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <description>Approval status of the agreement line item</description>
    <inlineHelpText>Approval status of the agreement line item</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>Field to store Material Number of product</description>
    <label>Material Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__AgreementLineItem__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Represents Price Group of Line Item</description>
    <label>Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Button to view Price Group</description>
    <label>Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Territory/Region for Quality/Parternship Agreements.</description>
    <inlineHelpText>Select all the apply of where products or services are intended to be sold or distributed</inlineHelpText>
    <label>Territory/Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEA - Asia-Pacific, Middle East, Africa</fullName>
            </value>
            <value>
                <fullName>APJ - Asia and the Pacific Group</fullName>
                <isActive>False</isActive>
                <label>APJ - Asia and the Pacific Group</label>
            </value>
            <value>
                <fullName>GC - Greater China</fullName>
            </value>
            <value>
                <fullName>AMR - Americas</fullName>
            </value>
            <value>
                <fullName>EUR - Europe</fullName>
            </value>
            <value>
                <fullName>EMEA - Europe, Middle East, and Africa</fullName>
                <isActive>False</isActive>
                <label>EMEA - Europe, Middle East, and Africa</label>
            </value>
            <value>
                <fullName>Global - All Regions</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Field to store Validation status</description>
    <inlineHelpText>This field states the current status of integrations with SAP(Validate, Activate).</inlineHelpText>
    <label>Validation Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/CLM_ProfileValidation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CLM_ProfileValidation</label>
</CustomObject>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Channel_Partner_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Agreement__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Channel Partner Agreement.</description>
    <defaultValue>false</defaultValue>
    <label>Channel Partner Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Master_Customer_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Agreement__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Master Customer Agreement.</description>
    <defaultValue>false</defaultValue>
    <label>Master Customer Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Master_Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Service_Agreement__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Master Service Agreement.</description>
    <defaultValue>false</defaultValue>
    <label>Master Service Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Negotiated_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Negotiated_Terms_and_Conditions__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Negotiated Terms and Conditions</description>
    <defaultValue>false</defaultValue>
    <label>Negotiated Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Standing_Quote__c.field-meta.xml
<CustomField>
    <fullName>Standing_Quote__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Standing Quote.</description>
    <defaultValue>false</defaultValue>
    <label>Standing Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLM_ProfileValidation__c/fields/Tender__c.field-meta.xml
<CustomField>
    <fullName>Tender__c</fullName>
    <description>This checkbox field is used to validate if user is able to create Tender.</description>
    <defaultValue>false</defaultValue>
    <label>Tender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Territory Region from Account to Contact</description>
    <formula>Account.Territory_Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/Customer_Master_Data__c.object-meta.xml
<CustomObject>
    <description>Stores master data for all accounts groups that are used in the system&apos;s workflow and processes. Source of majority of the data is ERP (SAP) system</description>
    <label>Customer Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Master Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Master_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Field to store Account Id</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Master Data</relationshipLabel>
    <relationshipName>Customer_Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Field to store Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country code of the country. Used for backed calculations like sales area.</description>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master_Data__c/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>Field to store ERP Customer Id</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ERP Customer Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>US-439
Product’s material number
Populated from SAP</description>
    <externalId>true</externalId>
    <label>Material Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestAgreementOutputParametersForm.cls
/**
*    @author: Vignesh S
*    @date:   23-Jan-2020
*    @description:  Test class for AgreementOutputParametersForm Controller
*    Modification Log:
*    -----------------------------------------------------------------------------------
*             Developer                      Date                Description
              Vignesh S                   23-Jan-2020            Initial Version
              KD                           10-Feb-2020          SAP integration 
              KD                          3-March-2020          Generate Enhancement
              Arif,Dalali                 28-Nov-2022           POL-57: Update APJ and EMEA References to AMEA and Europe respectively
*    ------------------------------------------------------------------------------------ 
*                    
*/
@isTest
public with sharing class TestAgreementOutputParametersForm {
    
    @testSetup 
    static void setupData(){
        Account acc = TestDataAccount.initAccount();
        acc.ERP_Customer_Id__c = '123456';
        acc.Territory_Region__c = 'AMR';    
        Account acc2 = TestDataAccount.initAccount();
        insert new List<Account> { acc, acc2 };
            
        Contact con = TestDataPerson.initContact(acc.Id);
        Contact con2 = TestDataPerson.initContact(acc.Id);
        insert new List<Contact> { con, con2 };
            
        Customer_Master_Data__c objCMD1 = new Customer_Master_Data__c(Name='CMD1',Country__c='Hong Kong',Country_Code__c='HK'),
                                objCMD2 = new Customer_Master_Data__c(Name='CMD2',Country__c='Hong Kong',Country_Code__c='HK');
        objCMD1.ERP_Customer_Id__c = '123456';
        objCMD2.ERP_Customer_Id__c = '234567';
        insert new List<Customer_Master_Data__c> {objCMD1, objCMD2};
        Product2 product = TestDataMaster.createProduct(false);
        product.Material_Number__c = 'VC0013519-OPA';
        insert product;
        
        CLM_ProfileValidation__c profilevalidation = new CLM_ProfileValidation__c(SetupOwnerId=userinfo.getProfileId(),Channel_Partner_Agreement__c=true,Master_Customer_Agreement__c=true,Master_Service_Agreement__c=true,Negotiated_Terms_and_Conditions__c=true,Standing_Quote__c=true,Tender__c=true);
        insert profilevalidation;
        
        Account_Sales_Area__c acc1SalesArea = TestDataAccountSalesArea.getAccountSalesArea('HK01', '01', '178', '00', false);
        acc1SalesArea.Account__c = acc.Id;
        acc1SalesArea.Price_List_Type__c = '06';
        acc1SalesArea.CurrencyIsoCode = 'USD';
        acc1SalesArea.Price_List__c = '01-AMEA-USD';  //POL-57
        acc1SalesArea.Contract_Number__c = '123456_HK010100';
        acc1SalesArea.Price_Group__c = 'TXDR';
        
        Account_Sales_Area__c acc2SalesArea = TestDataAccountSalesArea.getAccountSalesArea('HK01', '02', '179', '00', false);
        acc2SalesArea.Account__c = acc2.Id;
        acc2SalesArea.Price_List_Type__c = '06';
        acc2SalesArea.CurrencyIsoCode = 'USD';
        acc2SalesArea.Price_List__c = '01-AMEA-USD'; //POL-57
        acc2SalesArea.Contract_Number__c ='567890_US010100';
        insert new List<Account_Sales_Area__c>{ acc1SalesArea, acc2SalesArea };

        Id recTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Master Customer Agreement').getRecordTypeId();
        Apttus__APTS_Agreement__c oAgreement1 = TestDataAgreement.initAgreements('Test Agreement - Price Group', acc.id);
        oAgreement1.RecordTypeId = recTypeId;
        oAgreement1.Validation_Status__c = 'Validate In Progress';
        oAgreement1.Apttus_Approval__Approval_Status__c = Label.AgreementApprovalStatusNotSubmitted;
        insert new List<Apttus__APTS_Agreement__c>{oAgreement1};
        
        
        Apttus__AgreementLineItem__c oAgreementLineItem = TestDataAgreement.initAgreementsLineItem(oAgreement1.id);
        oAgreementLineItem.Material_Number__c = 'VC0013519-OPA';
        oAgreementLineItem.Line_Type__c = 'Material';
        oAgreementLineItem.Apttus_CMConfig__LineNumber__c = 1;
        oAgreementLineItem.Apttus_CMConfig__ItemSequence__c = 1;
        oAgreementLineItem.Discount_Type__c = '% Discount';
        oAgreementLineItem.Discount__c = 12;
        oAgreementLineItem.CurrencyIsoCode = 'USD';
        oAgreementLineItem.Distribution_Channel__c = '01';
        oAgreementLineItem.Customer_ERP_Number__c = '123456';
        oAgreementLineItem.Sales_Org__c = 'US01';
        insert oAgreementLineItem;

        oAgreement1.Apttus_Approval__Approval_Status__c = Label.AgreementApprovalStatusApproved;
       update oAgreement1;
            
        
    }
    
    /**
     *  @Author Vignesh S
     *  @Description : Method that passes agreement Id and gets agreement and selected Material group.
     **/
    @isTest
    static void testAgreementRecords(){
        AgreementOutputParametersForm.AgreementWrapper aggWarp = null;
        list<Apttus__APTS_Agreement__c> lstAgreement = [select Id from Apttus__APTS_Agreement__c LIMIT 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ApttusCLMMockHTTP('Success',null,null));
        if(!lstAgreement.isEmpty()){
            aggWarp= AgreementOutputParametersForm.getAgreementWrapper(lstAgreement[0].Id);
        }
        System.debug('Agreement JSON-->>'+aggWarp.objAgreement.Name);
        System.assertEquals('Test Agreement - Price Group',aggWarp.objAgreement.Name,'Fetch Agreement is not correct');
        Test.stopTest();
    }
    /**
     *  @Author KD
     *  @Description : Test class for upload file
     **/
    @isTest
    static void testUploadCSV(){
        Test.startTest();
        ContentVersion objCV;
        objCV = TestDataFieldService.createDocVersion('TestDoc', 'test.csv', 'Excluded Item,Included Item\r\n123,abc\r\n456,def', true);
        insert objCV;
        ContentVersion contentVersion2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :objCV.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        String strRetCSV = AgreementOutputParametersForm.readCSVFile(contentVersion2.ContentDocumentId);
        Test.stopTest();
        System.assertEquals(documents[0].Id, contentVersion2.ContentDocumentId);
        System.assertEquals('{"excludeValue": ["123","456"],"includeValue": ["abc","def"]}',strRetCSV,'Return String is not correct');

    }
    /**
     *  @Author KD
     *  @Description : Test class for Generate success
     **/
    @isTest
    static void testAgreementGenerateSuccess(){
        list<Apttus__APTS_Agreement__c> lstAgreement = [select Id,Apttus__FF_Agreement_Number__c from Apttus__APTS_Agreement__c LIMIT 1];
        String strInputJSON = '{"IncludeAllMaterial":true,"includeAdditionalMaterials":"include","excludeAdditionalMaterials":"exclude","includeMaterialFile":"[\\"abc\\",\\"def\\"]","excludeMaterialFile":"[\\"123\\",\\"456\\"]","selectedMaterialGroup":"[{\\"Description\\":\\"TG MiSeq Consumables\\",\\"isSelected\\":false,\\"materialGroup\\":\\"AIM\\"},{\\"Description\\":\\"TG Misc Consumables\\",\\"isSelected\\":false,\\"materialGroup\\":\\"AIR\\"},{\\"Description\\":\\"AmpliSeq Consumables\\",\\"isSelected\\":false,\\"materialGroup\\":\\"ASQ\\"}]","pricingDate":"2021-02-13","language":"English","hideListPrice":true,"customerName":"10X Genomics;6000022795","customerERPNumber":"6000022795","salesOrg":"BE01","curr":"AUD"}';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ApttusCLMMockHTTP('Success',lstAgreement[0].Apttus__FF_Agreement_Number__c,''));
        System.assertequals(Label.UI_Agreement_Generate_Success,AgreementOutputParametersForm.sendGenerateRequest(strInputJSON,lstAgreement[0].id));
        Test.stopTest();
    }
     /**
     *  @Author KD
     *  @Description : Test class for Generate failure
     **/
    @isTest
    static void testAgreementGenerateFailure(){
        list<Apttus__APTS_Agreement__c> lstAgreement = [select Id,Apttus__FF_Agreement_Number__c from Apttus__APTS_Agreement__c LIMIT 1];
        String strInputJSON = '{"IncludeAllMaterial":true,"includeAdditionalMaterials":"include","excludeAdditionalMaterials":"exclude","includeMaterialFile":"[\\"abc\\",\\"def\\"]","excludeMaterialFile":"[\\"123\\",\\"456\\"]","selectedMaterialGroup":"[{\\"Description\\":\\"TG MiSeq Consumables\\",\\"isSelected\\":false,\\"materialGroup\\":\\"AIM\\"},{\\"Description\\":\\"TG Misc Consumables\\",\\"isSelected\\":false,\\"materialGroup\\":\\"AIR\\"},{\\"Description\\":\\"AmpliSeq Consumables\\",\\"isSelected\\":false,\\"materialGroup\\":\\"ASQ\\"}]","pricingDate":"2021-02-13","language":"English","hideListPrice":true,"customerName":"10X Genomics;6000022795","customerERPNumber":"6000022795","salesOrg":"BE01","curr":"AUD"}';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ApttusCLMMockHTTP('Fail',lstAgreement[0].Apttus__FF_Agreement_Number__c,''));
        String strReturn = AgreementOutputParametersForm.sendGenerateRequest(strInputJSON,lstAgreement[0].id);
        System.assertequals(true,strReturn.contains(Label.UI_Agreement_Generate_Failed),'Generate Error');
        Test.stopTest();
    }
}