force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/National_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>National_Group_Number__c</fullName>
    <description>As part of 7729, to capture national group number.</description>
    <label>National Group Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Open_Offer_Comparison_Customer__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Comparison_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Offer Comparison Customer</description>
	<inlineHelpText>Customers whose discounting is relevant for internal comparison versus universal grid.</inlineHelpText>
    <label>Open Offer Comparison Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Signed_Open_Offer__c.field-meta.xml
<CustomField>
    <fullName>Signed_Open_Offer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customers who have signed Grail open offer.</description>
	<inlineHelpText>Customers who have signed the open offer.</inlineHelpText>
    <label>Signed Open Offer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/Apttus_Config2__LineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Applied_Discount_Details__c.field-meta.xml
<CustomField>
    <fullName>Applied_Discount_Details__c</fullName>
    <description>This field states the details for discount given.</description>
    <label>Applied Discount Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Applied_Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Applied_Discount_Percentage__c</fullName>
    <description>This field states the discount percentage for a product.</description>
    <label>Applied Discount Percentage</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__ConfigurationId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ConfigurationId__c</fullName>
    <description>ID of the associated configuration</description>
    <label>Configuration</label>
    <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected product or service</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Open_Offer_Max__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Max__c</fullName>
    <description>Discount Ceiling for this product for this customer based on Open Offer and account analysis.</description>
    <inlineHelpText>Discount % allowance as per universal grid. This field does not show grandfather pricing.</inlineHelpText>
    <label>Open Offer Max %</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Open_Offer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Product_Category__c</fullName>
    <businessOwnerGroup>Sales_Schema_Owners</businessOwnerGroup>
    <description>Open Offer Product Category of Product (in case of Product/Service Line Type) or Option (in case of Option Line Type).</description>
    <formula>IF(ISPICKVAL(Apttus_Config2__LineType__c, &apos;Product/Service&apos;) , TEXT(Apttus_Config2__ProductId__r.Open_Offer_Product_Category__c),TEXT(Apttus_Config2__OptionId__r.Open_Offer_Product_Category__c))</formula>
    <label>Open Offer Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/Apttus_Config2__ProductConfiguration__c.object-meta.xml
<CustomObject>
    <description>Represents a product configuration</description>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/fields/Apttus_QPConfig__Proposald__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__Proposald__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the quote/proposal associated with the configuration</description>
    <label>Quote/Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Configurations</relationshipLabel>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Account__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prospect Account</description>
    <inlineHelpText>Customer account to which Illumina is selling in this transaction; drives currency and discount(s) applicable to the transaction.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SFDC_520_Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/National_Group_Number__c.field-meta.xml
<CustomField>
        <fullName>National_Group_Number__c</fullName>
        <description>DCP-51343-Fetch NGN from Account</description>
        <inlineHelpText>As part of 7729, to capture national group number.</inlineHelpText>
        <formula>Ultimate_Consignee__r.National_Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>National Group Number</label>
        <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Open_Offer_Discount_Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Discount_Violation_Type__c</fullName>
    <description>Picklist field to indicate whether Applied Discount % &gt; Open Offer Max %, and also if Applied Discount % &gt; Open Offer Max % + 15</description>
    <inlineHelpText>choose if  Applied Discount % &gt; Open Offer Max % (or Open Offer Max%+15)</inlineHelpText>
    <label>Open Offer Discount Violation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Exceeded</fullName>
            </value>
            <value>
                <fullName>Discount Exceeded By 15 Percent</fullName>
            </value>
            <value>
                <fullName>No Open Offer Discount Due To Different Ngn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Open_Offer_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Product_Type__c</fullName>
    <description>System generated field reflecting high level product class based on items added to Conga cart when product added is an open offer product.</description>
    <inlineHelpText>System generated field reflecting high level product class based on items added to Conga cart when product added is an open offer product.</inlineHelpText>
    <label>Open Offer Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Quote_Has_Open_Offer_Product__c.field-meta.xml
<CustomField>
    <fullName>Quote_Has_Open_Offer_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will be true when Quote has Open offer Product.</description>
    <inlineHelpText>This field will be indicator that the Quote has any Open Offer Product or not.</inlineHelpText>
    <label>Quote Has Open Offer Product?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <description>Opportunity Record Type name</description>
    <formula>Apttus_Proposal__Opportunity__r.RecordType.Name</formula>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Ultimate_Consignee__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Consignee__c</fullName>
    <description>Lookup to Account for Ultimate Consignee</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of entity using product/solution;  specific to location where solution/will be installed or relocated. Required through opportunity lifecycle; drives pricebook (direct channel). Changes to UC after Quote Approved invalidates Quote and changes stage to Denied.</inlineHelpText>
    <label>Ultimate Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals (Ultimate Consignee)</relationshipLabel>
    <relationshipName>Ultimate_Consignee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Code_Parameter__mdt/Code_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>Values used by Apex or Lightning code</description>
    <label>Code Parameter</label>
    <pluralLabel>Code Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Code_Parameter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Usually will be name/value pairs. Each pair on a line and separated by a colon</description>
    <inlineHelpText>Usually will be name/value pairs. Each pair on a line and separated by a colon</inlineHelpText>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Material_Class__c.field-meta.xml
<CustomField>
    <fullName>Material_Class__c</fullName>
    <description>Requested by : user story DCP – 2073
Why : To be able to classify the products
Value source : Information would flow in from SAP</description>
    <label>Material Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informatics Software</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Document Training</fullName>
            </value>
            <value>
                <fullName>Tools</fullName>
            </value>
            <value>
                <fullName>Service Part</fullName>
                <isActive>false</isActive>
                <label>Service Part</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Open_Offer_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Open_Offer_Product_Category__c</fullName>
    <description>Open Offer Product Category</description>
    <inlineHelpText>Products in the Open Offer</inlineHelpText>
    <label>Open Offer Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Open_Offer_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Open_Offer_Product_Category.globalValueSet-meta.xml
<GlobalValueSet>
	<customValue>
        <fullName>DEDICATED ON-SITES</fullName>
    </customValue>
    <customValue>
        <fullName>NEXTSEQ 1000/2000</fullName>
    </customValue>
    <customValue>
        <fullName>NEXTSEQ 500/550/550DX/1000/2000</fullName>
    </customValue>
    <customValue>
        <fullName>NEXTSEQ 550</fullName>
    </customValue>
    <customValue>
        <fullName>NEXTSEQ 500/550/550DX/1000/2000 SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>NEXTSEQ 550 (TG)</fullName>
    </customValue>
    <customValue>
        <fullName>NEXTSEQ 550DX</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ 6000</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ 6000DX</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ 6000DX V1.5</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ 6000 SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ 6KDX</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ V1.5</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ X</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ X 25B</fullName>
    </customValue>
    <customValue>
        <fullName>NOVASEQ X B3</fullName>
    </customValue>
    <customValue>
        <fullName>NVQ X</fullName>
    </customValue>
    <customValue>
        <fullName>SERVICES</fullName>
    </customValue>
    <masterLabel>Open Offer Product Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/OpenOfferQuotationUpdatesHelper.cls
/**
*    @author Nesar Mohan
*    @date   2022-06-02
*    @description    DCP-53938: Helper class to evalute the logic of open offer criteria and update the fields on quote record
*    Test class for 90%+ coverage : TestApttusProposalLineItemsOpenOffer
*    Test class for 75%+ coverage : TestApttusProposalLineItemsOpenOffer
*    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------------------
*         Developer                      Date                Description         
*        Nesar Mohan                  2022-06-02           Initial Version
*        Himanshu                     2022-06-21           To get Material Class for DCP-53205
*        Satya Swain                  2022-06-23           TASK0799027 : Replace ApttusProposalLineItemsHelper with this class to make it 
                                                           specific to Open offer calculations
*        Khushbu Vasani               2022-09-01           DCP-56658 changes
*    ---------------------------------------------------------------------------------------------------------------------------
**/
public with sharing class OpenOfferQuotationUpdatesHelper {
    public static final String OODISCOUNTEXCEPTIONREQUEST = 'Open_Offer_Discount_Exception_Request';
    private static final String LOG_TITLE = 'OpenOfferQuotationUpdatesHelper';
    
    /*
    *  @AUTHOR:         Nesar Mohan
    *  @DESCRIPTION:    Method to evaluate open offer logic
    *  @PARAM :         Map<Id,Id>
    *  @RETURN:         void
    */
    public void evaluateOpenOfferLogic(Map<Id,Id> mapLineItemIdtoQuoteId) {

        ilib_LogEvent.push(LOG_TITLE + '.evaluateOpenOfferLogic()');

        Map<Id,Apttus_Proposal__Proposal__c> mapIdToProposalForUpdate = new Map<Id,Apttus_Proposal__Proposal__c>();
        Set<Id> setCartLineItemIds =  mapLineItemIdtoQuoteId.keyset();
        Map<Id,Boolean> mapQuoteIdToOpenOfferValue = new Map<Id,Boolean>();
        Map<Id,Set<String>> mapQuoteIdToOpenOfferProductMaterialClass =  new Map<Id,Set<String>>();//DCP-53205
        List<Apttus_Config2__LineItem__c> lstCartLineItemsWithOOProduct = new List<Apttus_Config2__LineItem__c>();
        
        List<Apttus_Config2__LineItem__c> lstCartLineItems = new ApttusLineItemsSelector().selectById(setCartLineItemIds);

        for(Apttus_Config2__LineItem__c objCartLineItem : lstCartLineItems) {
            Set<String> setStringMaterialClass = new Set<String>();
            if (objCartLineItem.Apttus_Config2__ProductId__r.Open_Offer_Product_Category__c!=null) {
                mapQuoteIdToOpenOfferValue.put(mapLineItemIdtoQuoteId.get(objCartLineItem.Id),true);
                lstCartLineItemsWithOOProduct.add(objCartLineItem);
                populateMapOfOpenOfferProductClassTypes(mapQuoteIdToOpenOfferProductMaterialClass,objCartLineItem,setStringMaterialClass,mapLineItemIdtoQuoteId);//DCP-53205
            } else if (!mapQuoteIdToOpenOfferValue.containsKey(mapLineItemIdtoQuoteId.get(objCartLineItem.Id))) {
                mapQuoteIdToOpenOfferValue.put(mapLineItemIdtoQuoteId.get(objCartLineItem.Id),false);
                mapQuoteIdToOpenOfferProductMaterialClass.put(mapLineItemIdtoQuoteId.get(objCartLineItem.Id),setStringMaterialClass);//DCP-53205
            }
        }

        List<Apttus_Proposal__Proposal__c> lstProposal = new ApttusProposalsSelector().selectById(mapQuoteIdToOpenOfferValue.keyset());
        
        for(Apttus_Proposal__Proposal__c objQuoteRecord : lstProposal) {
            objQuoteRecord.Quote_Has_Open_Offer_Product__c = mapQuoteIdToOpenOfferValue.get(objQuoteRecord.id);
            objQuoteRecord.Open_Offer_Discount_Violation_Type__c = '';
            objQuoteRecord.Open_Offer_Product_Type__c = String.join(new List<String>(mapQuoteIdToOpenOfferProductMaterialClass.get(objQuoteRecord.id)), ';');
            mapIdToProposalForUpdate.put(objQuoteRecord.id,objQuoteRecord);
        }

        if(!lstCartLineItemsWithOOProduct.isEmpty()) {
            evaluateDiscountCheck(lstCartLineItemsWithOOProduct,mapLineItemIdtoQuoteId,mapIdToProposalForUpdate);
        }
        
        if(!mapIdToProposalForUpdate.isEmpty()) {
            try {
                Database.update(mapIdToProposalForUpdate.values());
            } catch(Exception e) {
                ApexExceptions.emit(LOG_TITLE, e);
            }
        }
        ilib_LogEvent.pop();
    }

    /*
    *  @AUTHOR:         Nesar Mohan
    *  @DESCRIPTION:    Method to evaluate account Discount check logic
    *  @PARAM :         List<Apttus_Config2__LineItem__c>, Map<Id,Id>, Map<Id,Apttus_Proposal__Proposal__c>
    *  @RETURN:         void
    */
    public void evaluateDiscountCheck(List<Apttus_Config2__LineItem__c> lstCartLineItems, Map<Id,Id> mapLineItemIdtoQuoteId,Map<Id,Apttus_Proposal__Proposal__c> mapIdToProposalForUpdate) {
        
        ilib_LogEvent.push(LOG_TITLE + '.evaluateDiscountCheck()');
        
        Code_Parameter__mdt objOOViolationType = Code_Parameter__mdt.getInstance(OODISCOUNTEXCEPTIONREQUEST);

        Map<Id,String> mapQuoteIdToDiscountExceededType = new Map<Id,String>();
        calculateDiscountViolationTypeCriteria(lstCartLineItems,mapQuoteIdToDiscountExceededType,mapLineItemIdtoQuoteId,objOOViolationType);

        List<Apttus_Proposal__Proposal__c> lstProposalsEligibleForDiscountViolation = new ApttusProposalsSelector().selectById(mapQuoteIdToDiscountExceededType.keySet());

        for(Apttus_Proposal__Proposal__c objQuoteRecord : lstProposalsEligibleForDiscountViolation) {
            Boolean booIsDirectQuote = objQuoteRecord.Quote_Type__c.startsWith(System.Label.DistributionChannelDirect);
            Boolean booHasQuoteId = mapIdToProposalForUpdate.containsKey(objQuoteRecord.Id);
            String strvalueToPopulate = mapQuoteIdToDiscountExceededType.get(objQuoteRecord.Id);

            if(booHasQuoteId && booIsDirectQuote) {
                mapIdToProposalForUpdate.get(objQuoteRecord.Id).Open_Offer_Discount_Violation_Type__c = strvalueToPopulate;
            } else if(!booHasQuoteId && booIsDirectQuote) {
                objQuoteRecord.Open_Offer_Discount_Violation_Type__c = strvalueToPopulate;
                mapIdToProposalForUpdate.put(objQuoteRecord.id,objQuoteRecord);
            }
        }
        ilib_LogEvent.pop();
    }

    /*
    *  @AUTHOR:         Himanshu Malik
    *  @DESCRIPTION:    Method to get Material Class for DCP-53205
    *  @PARAM :         Map<Id,Set<String>> mapQuoteIdToOpenOfferProductMaterialClass,Apttus_Config2__LineItem__c objCartLineItem,Set<String> setStringMaterialClass,Map<Id,Id> mapLineItemIdtoQuoteId
    *  @RETURN:         void
    */
    public void populateMapOfOpenOfferProductClassTypes(Map<Id,Set<String>> mapQuoteIdToOpenOfferProductMaterialClass,Apttus_Config2__LineItem__c objCartLineItem,Set<String> setStringMaterialClass,Map<Id,Id> mapLineItemIdtoQuoteId) {
       
        ilib_LogEvent.push(LOG_TITLE + '.populateMapOfOpenOfferProductClassTypes()');
        Decimal decimalAppliedDiscountPercentage = objCartLineItem.Applied_Discount_Percentage__c == NULL ? 0 : objCartLineItem.Applied_Discount_Percentage__c;
        Decimal decimalOpenOfferMaxPercentage = objCartLineItem.Open_Offer_Max__c == NULL ? 0 : objCartLineItem.Open_Offer_Max__c;
        Boolean boolAppliedPercentGreaterThanOOMax = decimalAppliedDiscountPercentage > decimalOpenOfferMaxPercentage;
        if(mapQuoteIdToOpenOfferProductMaterialClass.containskey(mapLineItemIdtoQuoteId.get(objCartLineItem.Id)) && boolAppliedPercentGreaterThanOOMax ) {
            mapQuoteIdToOpenOfferProductMaterialClass.get(mapLineItemIdtoQuoteId.get(objCartLineItem.Id)).add(objCartLineItem.Apttus_Config2__ProductId__r.Material_Class__c);
        } else if (!mapQuoteIdToOpenOfferProductMaterialClass.containskey(mapLineItemIdtoQuoteId.get(objCartLineItem.Id)) && boolAppliedPercentGreaterThanOOMax) {
            setStringMaterialClass.add(objCartLineItem.Apttus_Config2__ProductId__r.Material_Class__c);
            mapQuoteIdToOpenOfferProductMaterialClass.put(mapLineItemIdtoQuoteId.get(objCartLineItem.Id),setStringMaterialClass);
        }
        ilib_LogEvent.pop();
    }        

    /*
    *  @AUTHOR:         Nesar Mohan
    *  @DESCRIPTION:    Method to calculate Discount Violation Type
    *  @PARAM :         List<Apttus_Config2__LineItem__c> lstCartLineItems, Map<Id,String> mapQuoteIdToDiscountExceededType,Map<Id,Id> mapLineItemIdtoQuoteId, Code_Parameter__mdt objOOViolationType
    *  @RETURN:         void
    */
    public void calculateDiscountViolationTypeCriteria(List<Apttus_Config2__LineItem__c> lstCartLineItems, Map<Id,String> mapQuoteIdToDiscountExceededType,Map<Id,Id> mapLineItemIdtoQuoteId, Code_Parameter__mdt objOOViolationType) {
        
        ilib_LogEvent.push(LOG_TITLE + '.calculateDiscountViolationTypeCriteria()');   
        for(Apttus_Config2__LineItem__c objLineItem : lstCartLineItems) {

            Boolean boolUcIsOocc = objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Ultimate_Consignee__r.Open_Offer_Comparison_Customer__c || objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Ultimate_Consignee__r.Signed_Open_Offer__c;
            Boolean boolSoldToIsOoocc = objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_Proposal__Account__r.Open_Offer_Comparison_Customer__c || objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_Proposal__Account__r.Signed_Open_Offer__c;
           
            Boolean boolQuoteIdKeyFoundInMap = mapQuoteIdToDiscountExceededType.containsKey(mapLineItemIdtoQuoteId.get(objLineItem.Id));
            String strValueFromMap = mapQuoteIdToDiscountExceededType.get(mapLineItemIdtoQuoteId.get(objLineItem.Id));
            Boolean boolMapContainsNGNValue = boolQuoteIdKeyFoundInMap && strValueFromMap == System.Label.NoOpenOfferDiscountDueToDifferentNgn;
            Boolean boolMapContainsExceededByFifteen = boolQuoteIdKeyFoundInMap && strValueFromMap == System.Label.DiscountExceededByFifteen;
            
            Decimal decAppliedDiscountPercentage = objLineItem.Applied_Discount_Percentage__c == NULL ? 0 : objLineItem.Applied_Discount_Percentage__c;
            Decimal decOpenOfferMaxPercentage = objLineItem.Open_Offer_Max__c == NULL ? 0 : objLineItem.Open_Offer_Max__c;
            Decimal decPercentageDifference = decAppliedDiscountPercentage - decOpenOfferMaxPercentage;
            Boolean boolAppliedPercentGreaterThanOOMax = decAppliedDiscountPercentage > decOpenOfferMaxPercentage;
            Boolean boolDiscountTypeIsDiscretionary = !String.isBlank(objLineItem.Applied_Discount_Details__c) && objLineItem.Applied_Discount_Details__c.contains(System.Label.ApprovalStepNameSalesDiscretionary);
           
            //DCP-56658 changes
            Account objUltimateConsignee = objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Ultimate_Consignee__r;
            Account objSoldTo = objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_Proposal__Account__r;

            string strUcErpNgnNumber = string.isBlank(objUltimateConsignee.National_Group_Number__c) ? objUltimateConsignee.erp_customer_id__C : objUltimateConsignee.National_Group_Number__c;
            string strSoldToErpNgnNumber = string.isBlank(objSoldTo.National_Group_Number__c) ? objSoldTo.erp_customer_id__C : objSoldTo.National_Group_Number__c;
            boolean boolDiffNgn = strUcErpNgnNumber != strSoldToErpNgnNumber;


            //Boolean boolNgnEmptyForSoldToAndUC = string.isEmpty(objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Ultimate_Consignee__r.National_Group_Number__c) && string.isEmpty(objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_Proposal__Account__r.National_Group_Number__c);
            // Boolean boolErpDifferentForSoldToAndUC = false;
            // if(boolUcIsOocc && boolSoldToIsOoocc && boolDiffNgn)
            // {
            //     boolErpDifferentForSoldToAndUC = objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Ultimate_Consignee__r.ERP_Customer_Id__c != objLineItem.Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.Apttus_Proposal__Account__r.ERP_Customer_Id__c;
            // }
            Boolean boolNoAdtData = false;
            if((boolUcIsOocc || boolSoldToIsOoocc) && objLineItem.Open_Offer_Max__c == null)
            {
                boolNoAdtData = true;
            }

            if((boolUcIsOocc && boolSoldToIsOoocc && boolDiffNgn) || boolNoAdtData) {
                mapQuoteIdToDiscountExceededType.put(mapLineItemIdtoQuoteId.get(objLineItem.Id),System.Label.NoOpenOfferDiscountDueToDifferentNgn);
            } else if(boolDiscountTypeIsDiscretionary && boolAppliedPercentGreaterThanOOMax && decPercentageDifference > Decimal.valueOf(objOOViolationType.Value__c) && !boolMapContainsNGNValue) {
                mapQuoteIdToDiscountExceededType.put(mapLineItemIdtoQuoteId.get(objLineItem.Id),System.Label.DiscountExceededByFifteen);
            } else if(boolDiscountTypeIsDiscretionary && boolAppliedPercentGreaterThanOOMax && decPercentageDifference <= Decimal.valueOf(objOOViolationType.Value__c) && !boolMapContainsNGNValue && !boolMapContainsExceededByFifteen) {
                mapQuoteIdToDiscountExceededType.put(mapLineItemIdtoQuoteId.get(objLineItem.Id),System.Label.DiscountExceeded);
            } else if(!boolQuoteIdKeyFoundInMap) {
                mapQuoteIdToDiscountExceededType.put(mapLineItemIdtoQuoteId.get(objLineItem.Id),'');
            }
        }
        ilib_LogEvent.pop();
    }
}