force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Product group values from Product to be used instead of product family</description>
    <label>Product Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AmpliSeq Library Prep</fullName>
            </value>
            <value>
                <fullName>Archer Targeted RNA</fullName>
            </value>
            <value>
                <fullName>Array-Based Analysis</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2.x</fullName>
            </value>
            <value>
                <fullName>AutoLoader Accessories</fullName>
            </value>
            <value>
                <fullName>AutoLoader Service Contract</fullName>
            </value>
            <value>
                <fullName>BAR Service Contract</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Storage</fullName>
            </value>
            <value>
                <fullName>Basespace Cloud Storage + Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Subscriptions</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cohort Analyzer</fullName>
            </value>
            <value>
                <fullName>BaseSpace Correlation Engine</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Accessory</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Qualifications</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Software</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite System</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Upgrades</fullName>
            </value>
            <value>
                <fullName>BaseSpace Professional Service</fullName>
            </value>
            <value>
                <fullName>BeadXpress Service Contract</fullName>
            </value>
            <value>
                <fullName>Beadxpress System (220V)</fullName>
            </value>
            <value>
                <fullName>Billable Service</fullName>
            </value>
            <value>
                <fullName>Billable Service Sequencing</fullName>
            </value>
            <value>
                <fullName>BioRad System</fullName>
            </value>
            <value>
                <fullName>BlueGnome Accessory</fullName>
            </value>
            <value>
                <fullName>cBot Qualification</fullName>
            </value>
            <value>
                <fullName>cBot Service Contract</fullName>
            </value>
            <value>
                <fullName>cBot System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Data to be inserted/updated using batch job-BatchContactCountryRegionMapping.</description>
    <label>Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Picklist field to specify Category of the product.</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BaseSpace Suite</fullName>
            </value>
            <value>
                <fullName>CytoGenomics</fullName>
            </value>
            <value>
                <fullName>Epigenetics</fullName>
            </value>
            <value>
                <fullName>EPI Molecular Biology</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>Gene Expression</fullName>
            </value>
            <value>
                <fullName>Genotyping</fullName>
            </value>
            <value>
                <fullName>HiSeq</fullName>
            </value>
            <value>
                <fullName>HiSeq HD</fullName>
            </value>
            <value>
                <fullName>HiSeq X</fullName>
            </value>
            <value>
                <fullName>iSeq</fullName>
            </value>
            <value>
                <fullName>Library Prep</fullName>
            </value>
            <value>
                <fullName>MA Automation</fullName>
            </value>
            <value>
                <fullName>MA Miscellaneous</fullName>
            </value>
            <value>
                <fullName>MA Scanners</fullName>
            </value>
            <value>
                <fullName>MA Services</fullName>
            </value>
            <value>
                <fullName>MA Software</fullName>
            </value>
            <value>
                <fullName>MiniSeq</fullName>
            </value>
            <value>
                <fullName>MiSeq</fullName>
            </value>
            <value>
                <fullName>NextSeq</fullName>
            </value>
            <value>
                <fullName>NextSeq 1000/2000</fullName>
            </value>
            <value>
                <fullName>NextSeq 500/550</fullName>
            </value>
            <value>
                <fullName>NovaSeq</fullName>
            </value>
            <value>
                <fullName>NovaSeq X Series</fullName>
            </value>
            <value>
                <fullName>Other MA Systems</fullName>
            </value>
            <value>
                <fullName>SQ Misc</fullName>
            </value>
            <value>
                <fullName>SQ Services</fullName>
            </value>
            <value>
                <fullName>SQ Software/Server</fullName>
            </value>
            <value>
                <fullName>SQ Supporting Systems</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Field to store Product Group.</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AmpliSeq Library Prep</fullName>
            </value>
            <value>
                <fullName>Archer Targeted RNA</fullName>
            </value>
            <value>
                <fullName>Array-Based Analysis</fullName>
            </value>
            <value>
                <fullName>Array Services - ILS</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2.x</fullName>
            </value>
            <value>
                <fullName>AutoLoader Accessories</fullName>
            </value>
            <value>
                <fullName>AutoLoader Service Contract</fullName>
            </value>
            <value>
                <fullName>Automation Software DX</fullName>
            </value>
            <value>
                <fullName>Automation Software RUO</fullName>
            </value>
            <value>
                <fullName>BAR Service Contract</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Storage</fullName>
            </value>
            <value>
                <fullName>Basespace Cloud Storage + Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Subscriptions</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cohort Analyzer</fullName>
            </value>
            <value>
                <fullName>BaseSpace Correlation Engine</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Accessory</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Platform</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Qualifications</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Software</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite System</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Upgrades</fullName>
            </value>
            <value>
                <fullName>BaseSpace Professional Service</fullName>
            </value>
            <value>
                <fullName>BeadXpress Service Contract</fullName>
            </value>
            <value>
                <fullName>Beadxpress System (220V)</fullName>
            </value>
            <value>
                <fullName>Billable Service</fullName>
            </value>
            <value>
                <fullName>Billable Service Sequencing</fullName>
            </value>
            <value>
                <fullName>BioRad System</fullName>
            </value>
            <value>
                <fullName>BlueGnome Accessory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <formula>SVMXC__Company__r.BillingCity</formula>
    <label>Account Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Automatically populate value from Product Category field on Product associated with Installed Product.</description>
    <formula>TEXT(SVMXC__Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT(SVMXC__Product__r.Product_Group__c)</formula>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Product_Regulatory_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Regulatory_Type__c</fullName>
    <formula>SVMXC__Product__r.Regulatory_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Regulatory Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>To capture region of account associated with installed product
Generated automatically from formula field</description>
    <formula>SVMXC__Company__r.Territory_Region__c</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Sent_to_Qualtrics__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Qualtrics__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <defaultValue>false</defaultValue>
    <description>Qualtrics Surveys: This checkbox will be checked whenever an Installed Product record
triggers a Qualtrics Survey</description>
    <label>Sent to Qualtrics</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
    <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N70000001hzZ0EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
    <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>R00N70000001hzchEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Serial_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Serial_Lot_Number__c</fullName>
    <description>Unique identification of this product. This information is Required if the product’s tracking is Serialized or Lot/Batch Tracked in the product record</description>
    <inlineHelpText>Unique identification of this product. This information is Required if the product’s tracking is Serialized or Lot/Batch Tracked in the product record</inlineHelpText>
    <label>Serial/Lot Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InstalledProductOutboundMessageHandler.cls
/**
 *    @author Vishal
 *    @date   19-Nov-2024
 *    @description  Class to send outbound messages for qualtrics survey
 *    @Test Class - TestIPOutboundMessageHandler
 * */
public with sharing class InstalledProductOutboundMessageHandler {
    
    public static final String INTERFACE_NAME_POST = 'Qualtrics_Survey_Direct';
    public static final String INTERFACE_NAME_POST_CP = 'Qualtrics_Survey_CP';
    /**
    hold http actions
    */ 
    public enum HttpMethod {HEAD, POST}
    public static final Integer SUCCESS = 200;
    public static final Integer ACCEPTED = 202;

     /**
     *  @author  Vishal
     *  @description This method is invoke by Installed Product Self Install Survey: Qualtrics Flow
     *  @return Void
     */
    @InvocableMethod(label='Send Data Through Outbound Message' description='Sends the outbound message' category='SVMXC__Installed_Product__c')
    public static void sendMessage(List<CheckPartner> installProductIdList) {
        if (installProductIdList == null || installProductIdList.isEmpty()) {
            return; // No IDs to process
        }
        sendOutboundMessages(installProductIdList[0].recordId, installProductIdList[0].isCP);
    }
     /**
     *  @author  Vishal
     *  @description This method is used to send outbound message to qualtrics
     *  @return Void
     */
    @future(callout=true)
    public static void sendOutboundMessages(Id recordId, Boolean isCP) {
        if (recordId == null) {
            return; // No records to process
        }
        
        try             
        {
            String interfaceName;
            if(isCP){
                 interfaceName = INTERFACE_NAME_POST_CP;
            }else{
                 interfaceName = INTERFACE_NAME_POST;
            }
            List<SVMXC__Installed_Product__c> updatedProducts = new List<SVMXC__Installed_Product__c>();
            
            SVMXC__Installed_Product__c installedProductRecord = new InstalledProductsSelector().getIP(recordId);
                try {
                    Map<String, Object> payload = createPayload(installedProductRecord);
                    String jsonPayload = JSON.serialize(payload);
                    
                    HttpRequest request = UtilsRest.createHttpRequestIP(interfaceName, HttpMethod.POST.name(), jsonPayload);
                    
                    HttpResponse response = UtilsRest.send(request);
                    
                    if (response.getStatusCode() == SUCCESS || response.getStatusCode() == ACCEPTED) {
                        installedProductRecord.Sent_to_Qualtrics__c = true;
                        updatedProducts.add(installedProductRecord);
                    }
                    System.debug('Response for Record ' + installedProductRecord.Id + ': Status=' + response.getStatusCode() + ', Body=' + response.getBody());
                } catch (Exception e) {
                    System.debug('HTTP Callout Error for Record ' + installedProductRecord.Id + ': ' + e.getMessage());
                }
            
            // Update only the products successfully sent
            if (!updatedProducts.isEmpty()) {
                update updatedProducts;
            }
        } catch (Exception e) {
            System.debug('Error in sendOutboundMessages: ' + e.getMessage());
        }
    }
     /**
     *  @author  Vishal
     *  @description Create payload for outbound message
     *  @return Map<String, Object> createPayload
     */
    private static Map<String, Object> createPayload(SVMXC__Installed_Product__c ipRecord) {
        return new Map<String, Object>{
            'InstalledProductId' => ipRecord.Id,
            'SVMXC__Serial_Lot_Number__c' => ipRecord.SVMXC__Serial_Lot_Number__c,
            'Account_Country__c' => ipRecord.Account_Country__c,
            'ProductId' => ipRecord.SVMXC__Product__r.Id,
            'ProductName' => ipRecord.SVMXC__Product__r.Name,
            'Product_Category__c' => ipRecord.Product_Category__c,
            'Product_Group__c' => ipRecord.Product_Group__c,
            'Product_Regulatory_Type__c' => ipRecord.Product_Regulatory_Type__c,
            'Region__c' => ipRecord.Region__c,
            'SVMXC__Company__c' => ipRecord.SVMXC__Company__r.Name,
            'ERP_Customer_Id__c' => ipRecord.SVMXC__Company__r.ERP_Customer_Id__c,
            'ContactRecordId' => ipRecord.SVMXC__Contact__c,
            'ContactEmail' => ipRecord.SVMXC__Contact__r.Email,
            'ContactFirstName' => ipRecord.SVMXC__Contact__r.FirstName,
            'ContactLastName' => ipRecord.SVMXC__Contact__r.LastName,
            'ContactFullName' => ipRecord.SVMXC__Contact__r.Name,
            'ContactPreferredLanguage' => ipRecord.SVMXC__Contact__r.Preferred_Language__c, 
            'SVMXC__Date_Shipped__c' => ipRecord.SVMXC__Date_Shipped__c
        };
    }
    /**
     *  @author  Vishal
     *  @description Invocable variables
     *  @return Void
     */
    public class CheckPartner {
        @InvocableVariable(required=true)
        public boolean isCP;
        @InvocableVariable(required=true)
        public Id recordId;
    }

}