force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/Account_Sales_Area__c.object-meta.xml
<CustomObject>
    <description>Stores the ERP (SAP) system specific information such as Sales Organization, Distribution Channel, Division and Company Code for the related account. Contains inco terms, pricegroup, pricelist type and terms of payment assigned to the given account</description>
    <label>Account Sales Area</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Account Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Area</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Sales_Area__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <description>Field to store Contract Number.</description>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Field to store Distribution Channel.</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Field to store Division.</description>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <description>Field to store Sales Organization.</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/Apttus_Config2__PriceList__c.object-meta.xml
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Apttus_Config2__Active__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the price list is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Apttus_Config2__ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ContractNumber__c</fullName>
    <description>The contract number associated with the price list.</description>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Apttus_Config2__EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__EffectiveDate__c</fullName>
    <description>The price list effective date. The price list becomes effective on this date and time.</description>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceList__c/fields/Apttus_Config2__ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ExpirationDate__c</fullName>
    <description>The price list expiration date. The price list becomes ineffective after this date and time.</description>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/Apttus_Config2__PriceListItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__Active__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the price list item is active. Inactive price list items are ignored.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ContractNumber__c</fullName>
    <description>The contract number associated with the price item</description>
    <formula>Apttus_Config2__PriceListId__r.Apttus_Config2__ContractNumber__c</formula>
    <inlineHelpText>The contract number associated with the price item</inlineHelpText>
    <label>Contract Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__EffectiveDate__c</fullName>
    <description>The price effective date. The price becomes effective on this date and time.</description>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ExpirationDate__c</fullName>
    <description>The price expiration date. The price becomes ineffective after this date and time.</description>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ListPrice__c</fullName>
    <description>The list price for the product</description>
    <label>List Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__PriceType__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PriceType__c</fullName>
    <description>The price type</description>
    <label>Price Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
                <default>true</default>
                <label>One Time</label>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
            <value>
                <fullName>Included Usage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the product associated with the price list</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>PriceLists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Customer_Specific_Price__c.field-meta.xml
<CustomField>
    <fullName>Customer_Specific_Price__c</fullName>
    <description>This field specify customer specific pricing for a given item.</description>
    <label>Customer Specific Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/PLI_Key__c.field-meta.xml
<CustomField>
    <fullName>PLI_Key__c</fullName>
    <description>This field store PLI key.</description>
    <formula>Apttus_Config2__PriceListId__r.Apttus_Config2__ContractNumber__c + &apos;_&apos; + Apttus_Config2__ProductId__r.Material_Number__c + &apos;_&apos; + TEXT(CurrencyIsoCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLI Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/Apttus_PLI_Staging__c.object-meta.xml
<CustomObject>
    <description>Obsolete object - will delete in 2021</description>
    <label>PLI Staging</label>
    <nameField>
        <label>PLI Staging</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PLI Staging</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <description>Customer # + Sales Area</description>
    <formula>CustomerId__c + &apos;_&apos; + SalesOrganization__c + DistributionChannel__c + Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>Field to store the customer id</description>
    <label>CustomerId</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/CustomerPrice__c.field-meta.xml
<CustomField>
    <fullName>CustomerPrice__c</fullName>
    <description>Field to store the customer price</description>
    <label>CustomerPrice</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel__c</fullName>
    <description>Field to store the distribution channel</description>
    <label>DistributionChannel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Field to store Division</description>
    <label>Division</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <description>Field to store the list price</description>
    <label>ListPrice</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/MaterialId__c.field-meta.xml
<CustomField>
    <fullName>MaterialId__c</fullName>
    <description>Field to store the material id</description>
    <label>MaterialId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/PLI_Key__c.field-meta.xml
<CustomField>
    <fullName>PLI_Key__c</fullName>
    <description>Field to store the pli_key</description>
    <formula>Contract_Number__c + &apos;_&apos; + MaterialId__c + &apos;_&apos; + TEXT(CurrencyIsoCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLI Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/PriceListType__c.field-meta.xml
<CustomField>
    <fullName>PriceListType__c</fullName>
    <description>Field to store the price list type</description>
    <label>PriceListType</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>Processed_Date__c</fullName>
    <description>Field to store the processed date</description>
    <label>Processed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Field to store Quantity</description>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganization__c</fullName>
    <description>Field to store the sales organization</description>
    <label>SalesOrganization</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Field to store UOM</description>
    <label>UOM</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Field to store the valid from</description>
    <label>ValidFrom</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_PLI_Staging__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Field to store the valid to</description>
    <label>ValidTo</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Area__c/Product_Sales_Area__c.object-meta.xml
<CustomObject>
    <label>Product Sales Area</label>
    <nameField>
        <label>Product Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Areas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Sales_Area__c/fields/Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Category_Group__c</fullName>
    <description>Prodcut category group</description>
    <label>Category Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Area__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Field to store distribution channel</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sales_Area__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBatchStagedPLItems.cls
@isTest
private class TestBatchStagedPLItems {

//    private static Date pastDate = Date.today() - 10;
//    private static Date futureDate = Date.today() + 10;
//
//    @isTest static void renewableField()
//    {
//        // product setup
//        Product2 p1 = TestDataMaster.getNewProduct('Cookie');
//        Product2 p2 = TestDataMaster.getNewProduct('Cookie_Service');
//        Product_Sales_Area__c psa1 = TestDataMaster.initProductSalesArea(p1.Id);
//        Product_Sales_Area__c psa2 = TestDataMaster.initProductSalesArea(p2.Id);
//        Product_Sales_Area__c psa3 = TestDataMaster.initProductSalesArea(p2.Id);
//        psa2.Category_Group__c = Products.CATEGORY_GROUP_SAP_RENEWABLE_CODE;
//        psa3.Category_Group__c = Products.CATEGORY_GROUP_SAP_RENEWABLE_CODE;
//        insert new List<Product_Sales_Area__c> {psa1, psa2, psa3};
//
//        // account setup
//        Account a = TestDataAccount.getNewAccount();
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        String expectedContract = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//
//        // staging data setup
//        TestDataMaster.getNewPliStaging(a, asa, p1, pastDate, futureDate);
//        TestDataMaster.getNewPliStaging(a, asa, p2, pastDate, futureDate);
//
//        Test.startTest();
//        Database.executeBatch(new BatchStagedPLItems());
//        Test.stopTest();
//
//        // assert PL data
//        List<Apttus_Config2__PriceList__c> pls = [SELECT Id, Apttus_Config2__ContractNumber__c FROM Apttus_Config2__PriceList__c];
//        System.assertEquals(1, pls.size());
//        Apttus_Config2__PriceList__c pl = pls.get(0);
//        System.assertEquals(expectedContract, pl.Apttus_Config2__ContractNumber__c);
//
//        // assert PLI data inserted
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__ProductId__c, Apttus_Config2__PriceType__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(2, plis.size());
//
//        // assert price types are correct
//        Apttus_Config2__PriceListItem__c pli1;
//        Apttus_Config2__PriceListItem__c pli2;
//        if (plis.get(0).Apttus_Config2__ProductId__c == p1.Id)
//        {
//            pli1 = plis.get(0);
//            pli2 = plis.get(1);
//        }
//        else
//        {
//            pli2 = plis.get(0);
//            pli1 = plis.get(1);
//        }
//        System.assertEquals(PriceListItems.PRICE_TYPE_ONE_TIME, pli1.Apttus_Config2__PriceType__c);
//        System.assertEquals(PriceListItems.PRICE_TYPE_RECURRING, pli2.Apttus_Config2__PriceType__c);
//
//        // assert processing is complete
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id, Processed_Date__c FROM Apttus_PLI_Staging__c];
//        System.assertEquals(2, stagingAfter.size());
//        System.assertEquals(Date.today(), stagingAfter.get(0).Processed_Date__c);
//    }
//
//    @isTest static void oneStagingRecordToOnePLI()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p = TestDataMaster.getNewProduct('Cookie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        // NOTE: could be a domain function
//        String expectedContract = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//
//        Test.startTest();
//        {
//            Database.executeBatch(new BatchStagedPLItems());
//        }
//        Test.stopTest();
//
//        // assert PL data
//        List<Apttus_Config2__PriceList__c> pls = [SELECT Id, Apttus_Config2__ContractNumber__c FROM Apttus_Config2__PriceList__c];
//        System.assertEquals(1, pls.size());
//        Apttus_Config2__PriceList__c pl = pls.get(0);
//        System.assertEquals(expectedContract, pl.Apttus_Config2__ContractNumber__c);
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(1, plis.size());
//        Apttus_Config2__PriceListItem__c pli = plis.get(0);
//        System.assertEquals(p.Id, pli.Apttus_Config2__ProductId__c);
//        System.assertEquals(staging.ListPrice__c, pli.Apttus_Config2__ListPrice__c);
//        System.assertEquals(staging.CustomerPrice__c, pli.Customer_Specific_Price__c);
//        System.assertEquals(pastDate, pli.Apttus_Config2__EffectiveDate__c.date());
//        System.assertEquals(futureDate, pli.Apttus_Config2__ExpirationDate__c.date());
//
//        // assert processing is complete
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id, Processed_Date__c FROM Apttus_PLI_Staging__c];
//        System.assertEquals(1, stagingAfter.size());
//        System.assertEquals(Date.today(), stagingAfter.get(0).Processed_Date__c);
//    }
//
//    @isTest static void oneStagingRecordToOnePLIExtantPL()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p = TestDataMaster.getNewProduct('Cookie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        String contractNumber = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//        Apttus_Config2__PriceList__c priceList = TestDataMaster.getNewPriceList(contractNumber);
//
//        Test.startTest();
//        {
//            Database.executeBatch(new BatchStagedPLItems());
//        }
//        Test.stopTest();
//
//        // assert no new PL data
//        List<Apttus_Config2__PriceList__c> pls = [SELECT Id FROM Apttus_Config2__PriceList__c];
//        System.assertEquals(1, pls.size());
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(1, plis.size());
//        Apttus_Config2__PriceListItem__c pli = plis.get(0);
//        System.assertEquals(p.Id, pli.Apttus_Config2__ProductId__c);
//        System.assertEquals(staging.ListPrice__c, pli.Apttus_Config2__ListPrice__c);
//        System.assertEquals(staging.CustomerPrice__c, pli.Customer_Specific_Price__c);
//        System.assertEquals(pastDate, pli.Apttus_Config2__EffectiveDate__c.date());
//        System.assertEquals(futureDate, pli.Apttus_Config2__ExpirationDate__c.date());
//
//        // assert processing is complete
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id, Processed_Date__c FROM Apttus_PLI_Staging__c];
//        System.assertEquals(1, stagingAfter.size());
//        System.assertEquals(Date.today(), stagingAfter.get(0).Processed_Date__c);
//    }
//
//    @isTest static void oneStagingToMatchingPlis()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p = TestDataMaster.getNewProduct('Cookie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        String contractNumber = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//        Apttus_Config2__PriceList__c priceList = TestDataMaster.getNewPriceList(contractNumber);
//        Apttus_Config2__PriceListItem__c pliOverlapped = TestDataMaster.getNewPriceListItem(priceList.Id, p.Id, pastDate + 2, futureDate - 2, 'USD');
//        Apttus_Config2__PriceListItem__c pliFuture = TestDataMaster.getNewPriceListItem(priceList.Id, p.Id, futureDate + 20, futureDate + 50, 'USD');
//
//        Test.startTest();
//        {
//            Database.executeBatch(new BatchStagedPLItems());
//        }
//        Test.stopTest();
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__Active__c, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(3, plis.size());
//        for (Apttus_Config2__PriceListItem__c pli : plis)
//        {
//            if (pli.Id == pliOverlapped.Id)
//            {
//                System.assert(pli.Apttus_Config2__Active__c == false);
//            }
//            else if (pli.Id == pliFuture.Id)
//            {
//                System.assert(pli.Apttus_Config2__Active__c == true);
//            }
//            else // newly-created row
//            {
//                System.assertEquals(p.Id, pli.Apttus_Config2__ProductId__c);
//                System.assertEquals(staging.ListPrice__c, pli.Apttus_Config2__ListPrice__c);
//                System.assertEquals(staging.CustomerPrice__c, pli.Customer_Specific_Price__c);
//                System.assertEquals(pastDate, pli.Apttus_Config2__EffectiveDate__c.date());
//                System.assertEquals(futureDate, pli.Apttus_Config2__ExpirationDate__c.date());
//            }
//        }
//    }
//
//    @isTest static void batchGetsFirstFindsMany()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p = TestDataMaster.getNewProduct('Cookie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging1 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging2 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging3 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Test.setCreatedDate(staging1.Id, DateTime.now() - .3);
//        Test.setCreatedDate(staging2.Id, DateTime.now() - .2);
//        Test.setCreatedDate(staging3.Id, DateTime.now() - .1);
//        String contractNumber = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//        Apttus_Config2__PriceList__c priceList = TestDataMaster.getNewPriceList(contractNumber);
//        Apttus_Config2__PriceListItem__c pliExtant = TestDataMaster.getNewPriceListItem(priceList.Id, p.Id, pastDate, futureDate, 'USD');
//
//        Test.startTest();
//        {
//            // requery to get formula and system values
//            List<Apttus_PLI_Staging__c> batchRows =
//                [SELECT Id, CreatedDate, Contract_Number__c, CurrencyIsoCode, PLI_Key__c, CustomerId__c, SalesOrganization__c, DistributionChannel__c, Division__c, MaterialId__c, PriceListType__c, ListPrice__c, CustomerPrice__c, Quantity__c, UOM__c, ValidFrom__c, ValidTo__c, Processed_Date__c
//                 FROM Apttus_PLI_Staging__c
//                 WHERE Id = :staging1.Id];
//
//            BatchStagedPLItems batch = new BatchStagedPLItems();
//            batch.initCounts();
//            batch.execute(null, batchRows);
//        }
//        Test.stopTest();
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__Active__c, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(2, plis.size());
//        Apttus_Config2__PriceListItem__c activePli;
//        for (Apttus_Config2__PriceListItem__c pli : plis)
//        {
//            if (pli.Apttus_Config2__Active__c) activePli = pli;
//        }
//        // staging 3 is the most recent
//        System.assertEquals(p.Id, activePli.Apttus_Config2__ProductId__c);
//
//        System.assertEquals(staging3.ListPrice__c, activePli.Apttus_Config2__ListPrice__c);
//        System.assertEquals(staging3.CustomerPrice__c, activePli.Customer_Specific_Price__c);
//        System.assertEquals(pastDate, activePli.Apttus_Config2__EffectiveDate__c.date());
//        System.assertEquals(futureDate, activePli.Apttus_Config2__ExpirationDate__c.date());
//
//        // assert processing is complete
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id FROM Apttus_PLI_Staging__c WHERE Processed_Date__c != null];
//        System.assertEquals(3, stagingAfter.size());
//    }
//
//    @isTest static void batchGetsSecondFindsMany()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p = TestDataMaster.getNewProduct('Cookie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging1 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging2 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging3 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Test.setCreatedDate(staging1.Id, DateTime.now() - .3);
//        Test.setCreatedDate(staging2.Id, DateTime.now() - .2);
//        Test.setCreatedDate(staging3.Id, DateTime.now() - .1);
//        String contractNumber = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//        Apttus_Config2__PriceList__c priceList = TestDataMaster.getNewPriceList(contractNumber);
//        Apttus_Config2__PriceListItem__c pliExtant = TestDataMaster.getNewPriceListItem(priceList.Id, p.Id, pastDate, futureDate, 'USD');
//
//        Test.startTest();
//        {
//            // requery to get formula and system values
//            List<Apttus_PLI_Staging__c> batchRows =
//            [SELECT Id, CreatedDate, Contract_Number__c, CurrencyIsoCode, PLI_Key__c, CustomerId__c, SalesOrganization__c, DistributionChannel__c, Division__c, MaterialId__c, PriceListType__c, ListPrice__c, CustomerPrice__c, Quantity__c, UOM__c, ValidFrom__c, ValidTo__c, Processed_Date__c
//            FROM Apttus_PLI_Staging__c
//            WHERE Id = :staging2.Id];
//
//            BatchStagedPLItems batch = new BatchStagedPLItems();
//            batch.initCounts();
//            batch.execute(null, batchRows);
//        }
//        Test.stopTest();
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__Active__c, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(2, plis.size());
//        Apttus_Config2__PriceListItem__c activePli;
//        for (Apttus_Config2__PriceListItem__c pli : plis)
//        {
//            if (pli.Apttus_Config2__Active__c) activePli = pli;
//        }
//        // staging 3 is the most recent
//        System.assertEquals(p.Id, activePli.Apttus_Config2__ProductId__c);
//
//        System.assertEquals(staging3.ListPrice__c, activePli.Apttus_Config2__ListPrice__c);
//        System.assertEquals(staging3.CustomerPrice__c, activePli.Customer_Specific_Price__c);
//        System.assertEquals(pastDate, activePli.Apttus_Config2__EffectiveDate__c.date());
//        System.assertEquals(futureDate, activePli.Apttus_Config2__ExpirationDate__c.date());
//
//        // assert processing is complete
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id FROM Apttus_PLI_Staging__c WHERE Processed_Date__c != null];
//        System.assertEquals(3, stagingAfter.size());
//    }
//
//    @isTest static void batchGetsThirdFindsMany()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p = TestDataMaster.getNewProduct('Cookie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging1 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging2 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging3 = TestDataMaster.getNewPliStaging(a, asa, p, pastDate, futureDate);
//        Test.setCreatedDate(staging1.Id, DateTime.now() - .3);
//        Test.setCreatedDate(staging2.Id, DateTime.now() - .2);
//        Test.setCreatedDate(staging3.Id, DateTime.now() - .1);
//        String contractNumber = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//        Apttus_Config2__PriceList__c priceList = TestDataMaster.getNewPriceList(contractNumber);
//        Apttus_Config2__PriceListItem__c pliExtant = TestDataMaster.getNewPriceListItem(priceList.Id, p.Id, pastDate, futureDate, 'USD');
//
//        Test.startTest();
//        {
//            // requery to get formula and system values
//            List<Apttus_PLI_Staging__c> batchRows =
//            [SELECT Id, CreatedDate, Contract_Number__c, CurrencyIsoCode, PLI_Key__c, CustomerId__c, SalesOrganization__c, DistributionChannel__c, Division__c, MaterialId__c, PriceListType__c, ListPrice__c, CustomerPrice__c, Quantity__c, UOM__c, ValidFrom__c, ValidTo__c, Processed_Date__c
//            FROM Apttus_PLI_Staging__c
//            WHERE Id = :staging3.Id];
//
//            BatchStagedPLItems batch = new BatchStagedPLItems();
//            batch.initCounts();
//            batch.execute(null, batchRows);
//        }
//        Test.stopTest();
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__Active__c, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(2, plis.size());
//        Apttus_Config2__PriceListItem__c activePli;
//        for (Apttus_Config2__PriceListItem__c pli : plis)
//        {
//            if (pli.Apttus_Config2__Active__c) activePli = pli;
//        }
//        // staging 3 is the most recent
//        System.assertEquals(p.Id, activePli.Apttus_Config2__ProductId__c);
//
//        System.assertEquals(staging3.ListPrice__c, activePli.Apttus_Config2__ListPrice__c);
//        System.assertEquals(staging3.CustomerPrice__c, activePli.Customer_Specific_Price__c);
//        System.assertEquals(pastDate, activePli.Apttus_Config2__EffectiveDate__c.date());
//        System.assertEquals(futureDate, activePli.Apttus_Config2__ExpirationDate__c.date());
//
//        // assert processing is complete
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id FROM Apttus_PLI_Staging__c WHERE Processed_Date__c != null];
//        System.assertEquals(3, stagingAfter.size());
//    }
//
//    @isTest static void batchGetsOneFindsSome()
//    {
//        Account a = TestDataAccount.getNewAccount();
//        Product2 p1 = TestDataMaster.getNewProduct('Cookie');
//        Product2 p2 = TestDataMaster.getNewProduct('Brownie');
//        Account_Sales_Area__c asa = TestDataAccountSalesArea.getNewAccountSalesArea(a.ERP_Customer_Id__c);
//        Apttus_PLI_Staging__c staging1 = TestDataMaster.getNewPliStaging(a, asa, p1, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging2 = TestDataMaster.getNewPliStaging(a, asa, p1, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging3 = TestDataMaster.getNewPliStaging(a, asa, p2, pastDate, futureDate);
//        Apttus_PLI_Staging__c staging4 = TestDataMaster.getNewPliStaging(a, asa, p2, pastDate, futureDate);
//        Test.setCreatedDate(staging1.Id, DateTime.now() - .3);
//        Test.setCreatedDate(staging2.Id, DateTime.now() - .2);
//        Test.setCreatedDate(staging3.Id, DateTime.now() - .3);
//        Test.setCreatedDate(staging4.Id, DateTime.now() - .2);
//        String contractNumber = a.ERP_Customer_Id__c + '_' + asa.Sales_Organization__c + asa.Distribution_Channel__c + asa.Division__c;
//        Apttus_Config2__PriceList__c priceList = TestDataMaster.getNewPriceList(contractNumber);
//        Apttus_Config2__PriceListItem__c pliExtant1 = TestDataMaster.getNewPriceListItem(priceList.Id, p1.Id, pastDate, futureDate, 'USD');
//        Apttus_Config2__PriceListItem__c pliExtant2 = TestDataMaster.getNewPriceListItem(priceList.Id, p2.Id, pastDate, futureDate, 'USD');
//
//        Test.startTest();
//        {
//            // requery to get formula and system values
//            List<Apttus_PLI_Staging__c> batchRows =
//            [SELECT Id, CreatedDate, Contract_Number__c, CurrencyIsoCode, PLI_Key__c, CustomerId__c, SalesOrganization__c, DistributionChannel__c, Division__c, MaterialId__c, PriceListType__c, ListPrice__c, CustomerPrice__c, Quantity__c, UOM__c, ValidFrom__c, ValidTo__c, Processed_Date__c
//            FROM Apttus_PLI_Staging__c
//            WHERE Id = :staging2.Id];
//
//            BatchStagedPLItems batch = new BatchStagedPLItems();
//            batch.initCounts();
//            batch.execute(null, batchRows);
//        }
//        Test.stopTest();
//
//        // assert PLI data
//        List<Apttus_Config2__PriceListItem__c> plis =
//            [SELECT Id, Apttus_Config2__Active__c, Apttus_Config2__ProductId__c, Apttus_Config2__ListPrice__c, Customer_Specific_Price__c, Apttus_Config2__EffectiveDate__c, Apttus_Config2__ExpirationDate__c
//             FROM Apttus_Config2__PriceListItem__c];
//        System.assertEquals(3, plis.size());
//
//        // assert processing is complete for product p1
//        List<Apttus_PLI_Staging__c> stagingAfter = [SELECT Id FROM Apttus_PLI_Staging__c WHERE Processed_Date__c = null];
//        System.assertEquals(2, stagingAfter.size());
//    }

}