force-app/main/default/objects/Account/fields/ERP_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Customer_Id__c</fullName>
    <description>External ID mapped from SAP</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique SAP Customer #</inlineHelpText>
    <label>ERP Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/Account_Sales_Area__c.object-meta.xml
<CustomObject>
    <description>Stores the ERP (SAP) system specific information such as Sales Organization, Distribution Channel, Division and Company Code for the related account. Contains inco terms, pricegroup, pricelist type and terms of payment assigned to the given account</description>
    <label>Account Sales Area</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Account Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Area</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Sales_Area__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup to Account.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sales Area</relationshipLabel>
    <relationshipName>Account_Sales_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <description>Field to store Contract Number.</description>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Field to store Distribution Channel.</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Field to store Price Group.</description>
    <label>Price Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_Group_Description__c.field-meta.xml
<CustomField>
    <fullName>Price_Group_Description__c</fullName>
    <description>Field to store the Price Group Description.</description>
    <label>Price Group Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>As part of DCP 10312 to store the price list.</description>
    <label>Price List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Price_List_Type__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Type__c</fullName>
    <description>Field to store Price List Type.</description>
    <label>Price List Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Sales_Area__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <description>Field to store Sales Organization.</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Subtype__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Subtype__c</fullName>
    <description>The subtype of the agreement for a given agreement type</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Non-Standard</fullName>
            </value>
            <value>
                <fullName>Lead Gen</fullName>
            </value>
            <value>
                <fullName>Customized Agreement</fullName>
            </value>
            <value>
                <fullName>Pricing Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Terms</fullName>
            </value>
            <value>
                <fullName>Termed</fullName>
            </value>
            <value>
                <fullName>One Time Sale</fullName>
            </value>
            <value>
                <fullName>One Time Sale &amp; Termed</fullName>
            </value>
            <value>
                <fullName>IHPP</fullName>
            </value>
            <value>
                <fullName>Reagent Rental</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Date_awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_awarded__c</fullName>
    <businessOwnerUser>gpikes@illumina.com</businessOwnerUser>
    <description>Date Illumina was awarded the Tender</description>
    <label>Date Awarded</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>Field to store Distribution Channel</description>
    <formula>IF(
OR( 
ISPICKVAL(Apttus__Account__r.Account_Group__c,&quot;Distributor&quot;),
AND(ISPICKVAL(Apttus__Account__r.Account_Group__c,&quot;Prospect&quot;),  NOT(ISBLANK(TEXT(Apttus__Account__r.Channel_Partner_Type__c))))
),
&apos;02&apos;,&apos;01&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distribution Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Freight_Charge__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charge__c</fullName>
    <businessOwnerGroup>Sales_Schema_Owners</businessOwnerGroup>
    <description>Indicate what kind of freight  charge was negotiated</description>
    <label>Freight Charge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Non-standard</fullName>
            </value>
            <value>
                <fullName>Do Not Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Fully_Signed_Contract_Attached__c.field-meta.xml
<CustomField>
    <fullName>Fully_Signed_Contract_Attached__c</fullName>
    <businessOwnerUser>gpikes@illumina.com</businessOwnerUser>
    <description>A copy of the fully executed contract/tender needs to be included in the record.  Please indicate yes or no it if has been attached.</description>
    <label>Fully Signed Contract Attached?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <description>Button to view Price Group</description>
    <label>Price Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Price_Group_Description__c.field-meta.xml
<CustomField>
    <fullName>Price_Group_Description__c</fullName>
    <description>Field to store description for Price Group</description>
    <label>Price Group Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Reason_for_Non_Compliance__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Non_Compliance__c</fullName>
    <businessOwnerUser>gpikes@illumina.com</businessOwnerUser>
    <description>Provide reason why required fields are not completed</description>
    <label>Reason for Non-Compliance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>this field will populate the agreement record type name</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Field to store Sales Org</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Tenders_Status__c.field-meta.xml
<CustomField>
    <fullName>Tenders_Status__c</fullName>
    <description>Field to store Tender status</description>
    <label>Tenders Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Pending TAM decision</fullName>
            </value>
            <value>
                <fullName>Contracts Decline to Pursue/ TAM Declines to Pursue</fullName>
            </value>
            <value>
                <fullName>Pre-submission</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pre-Award</fullName>
            </value>
            <value>
                <fullName>Won Pending PO/Contract</fullName>
            </value>
            <value>
                <fullName>In Effect/Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed Abandoned</fullName>
            </value>
            <value>
                <fullName>TAM Declines to Pursue</fullName>
            </value>
            <value>
                <fullName>Contracts Decline to Pursue</fullName>
            </value>
            <value>
                <fullName>Pre Submission</fullName>
            </value>
            <value>
                <fullName>Post Submission</fullName>
            </value>
            <value>
                <fullName>Post Award Won – Pending PO/Contract</fullName>
            </value>
            <value>
                <fullName>Post Award Won – Received PO/Signed Contract</fullName>
            </value>
            <value>
                <fullName>Post Award Lost</fullName>
            </value>
            <value>
                <fullName>Tender Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Total_contract_length_with_extension__c.field-meta.xml
<CustomField>
    <fullName>Total_contract_length_with_extension__c</fullName>
    <businessOwnerUser>gpikes@illumina.com</businessOwnerUser>
    <description>Length of contract including extension in months</description>
    <inlineHelpText>Length of contract including extension in months</inlineHelpText>
    <label>Total Contract Length With Extension</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/recordTypes/Tender.recordType-meta.xml
<RecordType>
    <fullName>Tender</fullName>
    <active>true</active>
    <label>Tender</label>
</RecordType>

force-app/main/default/globalValueSets/Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>AT01</fullName>
    </customValue>
    <customValue>
        <fullName>AU01</fullName>
    </customValue>
    <customValue>
        <fullName>BE01</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
    </customValue>
    <customValue>
        <fullName>CN01</fullName>
    </customValue>
    <customValue>
        <fullName>CN02</fullName>
    </customValue>
    <customValue>
        <fullName>CN03</fullName>
    </customValue>
    <customValue>
        <fullName>DE01</fullName>
    </customValue>
    <customValue>
        <fullName>CO01</fullName>
    </customValue>
    <customValue>
        <fullName>DK01</fullName>
    </customValue>
    <customValue>
        <fullName>ES01</fullName>
    </customValue>
    <customValue>
        <fullName>FI01</fullName>
    </customValue>
    <customValue>
        <fullName>FR01</fullName>
    </customValue>
    <customValue>
        <fullName>FR02</fullName>
    </customValue>
    <customValue>
        <fullName>FR90</fullName>
    </customValue>
    <customValue>
        <fullName>GB01</fullName>
    </customValue>
    <customValue>
        <fullName>GB02</fullName>
    </customValue>
    <customValue>
        <fullName>GB03</fullName>
    </customValue>
    <customValue>
        <fullName>GB90</fullName>
    </customValue>
    <customValue>
        <fullName>HK01</fullName>
    </customValue>
	<customValue>
        <fullName>IE01</fullName>
    </customValue> 
	<customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IS01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>JP01</fullName>
    </customValue>
    <customValue>
        <fullName>KR01</fullName>
    </customValue>
    <customValue>
        <fullName>NL01</fullName>
    </customValue>
    <masterLabel>Sales Org</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TestBatchUpdateNonCompliantAgreements.cls
/***
*    Name - TestBatchUpdateNonCompliantAgreements.
*    DESCRIPTION  : TestClass for BatchUpdateAgreementConLength & BatchUpdateAgreementAwardDt classes.
*    Modification Log:
*   ------------------------------------------------------------------------------------------------
*    Developer                      Date              		Description
*    Amogh Ghodke             27th November 2023              CMCM-2709
*   ------------------------------------------------------------------------------------------------
*/
@isTest(isparallel=false)
public class TestBatchUpdateNonCompliantAgreements {
    
     static testMethod void testBatch(){
	    Id recTypeTender = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Tender').getRecordTypeId();
        Account acc = TestDataAccount.initAccount();
        acc.ERP_Customer_Id__c = '345678';
        acc.BIllingCountryCode='HK' ;
        insert acc;
       
        List<PermissionSetAssignment> lstAgrManager = [SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name = 'SL_Apttus_Agreement_Manager'];
        Set<Id> setUserId = UtilsCollection.getSetOfIds(lstAgrManager,'AssigneeId');
        List<User> lstUser = [Select Id From User where Id =: setUserId AND IsActive = true AND Profile.Name = 'Sales User'];
        User agrManager = lstUser[0];
       
		
		Account_Sales_Area__c accSalesArea = TestDataAccountSalesArea.getAccountSalesArea('HK01', '01', '181', '00', false);
        accSalesArea.Account__c = acc.Id;
        accSalesArea.Price_List_Type__c = '06';
        accSalesArea.CurrencyIsoCode = 'USD';
        accSalesArea.Price_List__c = '01-AMEA-USD';
        accSalesArea.Contract_Number__c = '123456_HK010300';
        accSalesArea.Price_Group__c = 'Test';
        accSalesArea.Sales_Organization__c='HK01';
        accSalesArea.Price_Group_Description__c='Test';
        accSalesArea.Distribution_Channel__c='01';
		insert accSalesArea;
		
        System.runAs(agrManager){
        TestDataAgreement.addHierarchyPermission();
        List<Apttus__APTS_Agreement__c> agreementList = new List<Apttus__APTS_Agreement__c>();
        Apttus__APTS_Agreement__c oAgreement = TestDataAgreement.initAgreements('Test Agreement - Total contract length blank', acc.id);
        oAgreement.Sales_Org__c = 'HK01';
        oAgreement.Total_contract_length_with_extension__c = null;
        oAgreement.Apttus__Subtype__c = 'One Time Sale & Termed';
        oAgreement.Fully_Signed_Contract_Attached__c = 'Yes';
        oAgreement.RecordTypeId = recTypeTender;
        oAgreement.Freight_Charge__c = 'Standard';
        agreementList.add(oAgreement);
        
        Apttus__APTS_Agreement__c oAgreement1 = TestDataAgreement.initAgreements('Test Agreement - Award date not specified', acc.id);
        oAgreement1.Date_awarded__c = null;
        oAgreement1.Fully_Signed_Contract_Attached__c = 'Yes';
        oAgreement1.Tenders_Status__c = 'In Effect/Won';
        oAgreement1.RecordTypeId = recTypeTender;
        oAgreement1.Freight_Charge__c = 'Standard';
        agreementList.add(oAgreement1);
        insert agreementList;    
        
        Test.startTest();
        BatchUpdateAgreementConLength obj =new BatchUpdateAgreementConLength();
        Database.executeBatch(obj);
        BatchUpdateAgreementAwardDt objVar =new BatchUpdateAgreementAwardDt();
        Database.executeBatch(objVar);
        Test.stopTest();
        List<Apttus__APTS_Agreement__c> oAgreementList = [SELECT Id, Name, Date_awarded__c, Tenders_Status__c, Sales_Org__c, Total_contract_length_with_extension__c, Apttus__Subtype__c, Reason_for_Non_Compliance__c FROM Apttus__APTS_Agreement__c WHERE Record_Type__c = 'Tender'];
	     for(Apttus__APTS_Agreement__c nonCompliantVar : oAgreementList) {
           if(nonCompliantVar.Name == 'Test Agreement - Total contract length blank' && nonCompliantVar.Total_contract_length_with_extension__c == null)
              System.assert(String.isNotBlank(nonCompliantVar.Reason_for_Non_Compliance__c), 'Total contract length blank');
            else if(nonCompliantVar.Name == 'Test Agreement - Award date not specified' && nonCompliantVar.Date_awarded__c == null && nonCompliantVar.Tenders_Status__c == 'In Effect/Won')
              System.assert(String.isNotBlank(nonCompliantVar.Reason_for_Non_Compliance__c), 'Award date not specified');}
        }
    }
}