force-app/main/default/objects/Account/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>back end field.</description>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Segment__c/Market_Segment__c.object-meta.xml
<CustomObject>
    <description>Stores information on account&apos;s market segment, sub-segment and allocated percent if more than one is assigned</description>
    <label>Market Segment</label>
    <nameField>
        <displayFormat>MS-{000000}{MMDDYYYY}</displayFormat>
        <label>Market Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Segment__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <description>Stores information of account's market segment</description>
    <label>Market Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/SVMXC__Service_Group__c.object-meta.xml
<CustomObject>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group. Service orders are assigned to a service group and optionally to group members. At the time of assignment, all the above parameters can be considered by the support center engineer(s) to choose the most suitable group that can address the customer problem.</description>
    <label>Service Team</label>
    <nameField>
        <label>Service Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__Active__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag indicates if this member is active and available for service order assignments. This flag does not drive any functionality in ServiceMax and is for informational purposes only</description>
    <inlineHelpText>Flag indicates if this member is active and available for service order assignments. This flag does not drive any functionality in ServiceMax and is for informational purposes only</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__City__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__City__c</fullName>
    <description>“City” part of the service team&apos;s address</description>
    <inlineHelpText>“City” part of the service team&apos;s address</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__Country__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Country__c</fullName>
    <description>“Country” part of the Service Team&apos;s address</description>
    <inlineHelpText>“Country” part of the Service Team&apos;s address</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua And</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Ayerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__Email__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Email__c</fullName>
    <description>Email address for the service team</description>
    <inlineHelpText>Email address for the service team</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__Group_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Group_Type__c</fullName>
    <description>Indicates if this is a group Internal to your organization, a Partner company providing the services on your behalf, or a combination of Both.</description>
    <inlineHelpText>Indicates if this is a group Internal to your organization, a Partner company providing the services on your behalf, or a combination of Both.</inlineHelpText>
    <label>Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__Phone__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Phone__c</fullName>
    <description>Telephone Number of the service team</description>
    <inlineHelpText>Telephone Number of the service team</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__State__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__State__c</fullName>
    <description>“State&apos; part of the service team&apos;s address</description>
    <inlineHelpText>“State&apos; part of the service team&apos;s address</inlineHelpText>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group__c/fields/SVMXC__Street__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Street__c</fullName>
    <description>“Street” part of the service team&apos;s address</description>
    <inlineHelpText>“Street” part of the service team&apos;s address</inlineHelpText>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/SVMXC__Service_Group_Members__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Group enables definition of your entire service organization. Service group definition includes details of group members, products in which the group specializes in, the skills available in the group, typical service delivery costs as well as geographies covered by the group.</description>
    <label>Technician/Equipment</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technician/Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Active__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag indicates if this member is active and available for service order assignments. This flag does not drive any functionality in ServiceMax and is for informational purposes only</description>
    <inlineHelpText>Flag indicates if this member is active and available for service order assignments. This flag does not drive any functionality in ServiceMax and is for informational purposes only</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__City__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__City__c</fullName>
    <description>“City” part of the technician&apos;s address</description>
    <inlineHelpText>“City” part of the technician&apos;s address</inlineHelpText>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Country__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Country__c</fullName>
    <description>“Country” part of the technician&apos;s address</description>
    <inlineHelpText>“Country” part of the technician&apos;s address</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua And</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Ayerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Email__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Email__c</fullName>
    <description>Email of the technician</description>
    <inlineHelpText>Email of the technician</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Phone__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Phone__c</fullName>
    <description>Telephone number of the technician</description>
    <inlineHelpText>Telephone number of the technician</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Service_Group__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Group__c</fullName>
    <description>Name of the service group. Is a lookup to an existing service group in ServiceMax</description>
    <inlineHelpText>Name of the service group. Is a lookup to an existing service group in ServiceMax</inlineHelpText>
    <label>Service Team</label>
    <referenceTo>SVMXC__Service_Group__c</referenceTo>
    <relationshipLabel>Technician/Equipment</relationshipLabel>
    <relationshipName>Service_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__State__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__State__c</fullName>
    <description>“State” part of the technician&apos;s address</description>
    <inlineHelpText>“State” part of the technician&apos;s address</inlineHelpText>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Group_Members__c/fields/SVMXC__Street__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Street__c</fullName>
    <description>“Street” part of the technician&apos;s address</description>
    <inlineHelpText>“Street” part of the technician&apos;s address</inlineHelpText>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Market_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agrigenomics</fullName>
    </customValue>
    <customValue>
        <fullName>Cancer Research</fullName>
    </customValue>
    <customValue>
        <fullName>Cell and Molecular Biology Research</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Forensics</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Research</fullName>
    </customValue>
    <customValue>
        <fullName>Genetic Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Infectious Disease Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Reproductive Health</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Training/Education</fullName>
    </customValue>
    <customValue>
        <fullName>Transplant genomics</fullName>
        <isActive>false</isActive>
        <label>Transplant Genomics</label>
    </customValue>
    <customValue>
        <fullName>Preconception and Fertility</fullName>
        <isActive>false</isActive>
        <label>Preconception and Fertility</label>
    </customValue>
    <customValue>
        <fullName>Public Health Surveillance</fullName>
    </customValue>
    <customValue>
        <fullName>Microbiology/Virology Research</fullName>
        <isActive>false</isActive>
        <label>Microbiology/Virology Research</label>
    </customValue>
    <customValue>
        <fullName>Genetic &amp; Complex Disease Research</fullName>
        <isActive>false</isActive>
        <label>Genetic &amp; Complex Disease Research</label>
    </customValue>
    <customValue>
        <fullName>Clinical Oncology</fullName>
        <isActive>false</isActive>
        <label>Clinical Oncology</label>
    </customValue>
    <customValue>
        <fullName>Cellular and Molecular Research</fullName>
        <isActive>false</isActive>
        <label>Cellular and Molecular Research</label>
    </customValue>
    <customValue>
        <fullName>Agricultural Genomics</fullName>
        <isActive>false</isActive>
        <label>Agricultural Genomics</label>
    </customValue>
    <customValue>
        <fullName>Pregnancy</fullName>
        <isActive>false</isActive>
        <label>Pregnancy</label>
    </customValue>
    <description>As part of DCP-1298 for the possible values of Primary Segments of the market.</description>
    <masterLabel>Market Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TestBatchToUpdateAccountPFASandPFSE.cls
/**
 * @author Saurabh Brahmankar
 * @description Test BatchToUpdateAccountFieldsPFASandPFSE
 * Modification Log:
 *   ---------------------------------------------------------------------------------------------------------------------------
 *    Developer                     Date(YY-MM-DD)                  Description
 *    Saurabh Brahmankar			2024-03-07						Initial Version CMCM-5763
 *   ---------------------------------------------------------------------------------------------------------------------------
 */

@IsTest
private class TestBatchToUpdateAccountPFASandPFSE {
  

    @IsTest //@TestSetup
    static void makeData(){
        
        //Create Account
        Account objAccount = TestDataAccount.getCustomerAccount();
        objAccount.Market_Segment__c = null;
        insert objAccount;
        
        SVMXC__Service_Group__c accST1 = New SVMXC__Service_Group__c();
        accST1.Name = 'Service Team 1';
        accST1.SVMXC__Active__c = true;
        accST1.SVMXC__Group_Type__c = 'Both';
        accST1.SVMXC__Phone__c = '(098) 765-4782';
        accST1.SVMXC__Email__c = 'qw@illumina.com';
        accST1.SVMXC__Street__c = 'mangalore';
        accST1.SVMXC__City__c = 'mangalore';
        accST1.SVMXC__State__c = 'Alabama';
        accST1.SVMXC__Country__c = 'United States';
        insert accST1;
        
        SVMXC__Service_Group_Members__c accFS1 = new SVMXC__Service_Group_Members__c();
        accFS1.Name ='Test User 1';
        accFS1.SVMXC__Active__c = true;
        accFS1.Preferred_Service_Report_Language__c = 'English';
        accFS1.SVMXC__Service_Group__c = accST1.Id;  
        insert accFS1; 
            
        Account_to_Field_Support__c accATFS1 = new Account_to_Field_Support__c();
        accATFS1.Account__c = objAccount.ID; 
        accATFS1.User_Role__c='Primary Field Application Scientist'; 
        accATFS1.user__c=accFS1.ID;
        insert accATFS1;
       
        SVMXC__Service_Group__c accST2 = New SVMXC__Service_Group__c();
        accST2.Name = 'Service Team 2';
        accST2.SVMXC__Active__c = true;
        accST2.SVMXC__Group_Type__c = 'Both';
        accST2.SVMXC__Phone__c = '(098) 765-4783';
        accST2.SVMXC__Email__c = 'qw2@illumina.com';
        accST2.SVMXC__Street__c = 'mangalore2';
        accST2.SVMXC__City__c = 'mangalore2';
        accST2.SVMXC__State__c = 'Alabama';
        accST2.SVMXC__Country__c = 'United States';
        insert accST2;        
        
        SVMXC__Service_Group_Members__c accFS2 =new SVMXC__Service_Group_Members__c();
        accFS2.Name ='Test User 2';
        accFS2.SVMXC__Active__c = true;
        accFS2.Preferred_Service_Report_Language__c = 'English';    
        accFS2.SVMXC__Service_Group__c = accST2.Id;     
        insert accFS2; 
            
        Account_to_Field_Support__c accATFS2=new Account_to_Field_Support__c();
        accATFS2.Account__c = objAccount.ID; 
        accATFS2.User_Role__c='Primary Field Service Engineer'; 
        accATFS2.user__c=accFS2.ID;
        insert accATFS2;
           
        // Start the batch
        Test.startTest();
        BatchToUpdateAccountFieldsPFASandPFSE batchClassInstance = new BatchToUpdateAccountFieldsPFASandPFSE();
        Database.executeBatch(batchClassInstance);
        Test.stopTest();

        // Verify the results
        objAccount = [SELECT Id, Primary_Field_Application_Scientist__c, Primary_Field_Service_Engineer__c FROM Account WHERE Id = :objAccount.Id];
        system.debug('objAccount is =>'+objAccount);
        System.assertEquals(accFS1.Name, objAccount.Primary_Field_Application_Scientist__c);
        System.assertEquals(accFS2.Name, objAccount.Primary_Field_Service_Engineer__c);
    }        
        
}