force-app/main/default/objects/Account/fields/R_Q_Contact_Eligible__c.field-meta.xml
<CustomField>
    <fullName>R_Q_Contact_Eligible__c</fullName>    
    <defaultValue>false</defaultValue>
    <description>Direct UC Accounts and Distributor Accounts with applicable Order Types are the only Accounts that need to maintain R/Q Contacts and this field will be marked as True for those Accounts. Any other Accounts will have this field marked as FALSE.</description>
    <label>R/Q Contact Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Order__c/Apttus_Config2__Order__c.object-meta.xml
<CustomObject>
    <description>Represents an order associated with an account</description>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Code_Parameter__mdt/Code_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>Values used by Apex or Lightning code</description>
    <label>Code Parameter</label>
    <pluralLabel>Code Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Code_Parameter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Usually will be name/value pairs. Each pair on a line and separated by a colon</description>
    <inlineHelpText>Usually will be name/value pairs. Each pair on a line and separated by a colon</inlineHelpText>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RQContactEligibleQueueable.cls
/*@ author       : Maruthi
* @ date         : 09-Feb-2022
* @ Description  : PM-122: R/Q Contact Eligible Queueable
*/
public with sharing class RQContactEligibleQueueable implements Queueable {
    Set<Id> setOrderIds;
    public static final String CODEPARAMETERORDERTYPE = 'Order_Types_For_Contact_Eligibility';
    public static final String DISTRIBUTOR = 'Distributor';
    public static final String SOLDTO ='Sold To';
    private static final String LOG_TITLE = 'RQContactEligibleQueueable';
    public static final String RQCONTACTELIGIBLE ='R_Q_Contact_Eligible__c';

    /*@ author       : Maruthi
    * @ date         : 09-Feb-2022
    * @ Description  : This is the Constructor for RQContactEligibleQueueable
    */
    public RQContactEligibleQueueable(Set<Id> setOrderIds) {
        this.setOrderIds = setOrderIds;         
    }

    /*
    *  @AUTHOR:  Maruthi B
    *  @DESCRIPTION: This Method to invoke  
    */
    public void execute(QueueableContext context) {  
        ilib_LogEvent.push(LOG_TITLE +'.updateRQContactEligible');  
        try {
            ilib_LogEvent.message('setOrderIds--'+setOrderIds);
            Set<Id> setAccountIds = new Set<Id>();        
            List<Code_Parameter__mdt> codeParameter =new CodeParametersSelector().selectCodeParameterByDeveloperName(new set<String>{CODEPARAMETERORDERTYPE});               
            List<String> orderTypeList = codeParameter[0].Value__c.split(',');  
            List<Apttus_Config2__Order__c> listOrder = new ApttusOrdersSelector().selectOrdersByIds(setOrderIds);            
            setAccountIds = RQContactEligibleHelper.getRQAccountId(listOrder,orderTypeList); //CMCM-698
            List<Account> updateListAccount = getUpdateList(setAccountIds); 
            ilib_LogEvent.message('updateListAccount--'+updateListAccount);
            if(!updateListAccount.isEmpty()) {                
                Update updateListAccount;
            }
            ilib_LogEvent.pop();
        } catch(Exception e) {
            ApexExceptions.emit(LOG_TITLE+'.updateRQContactEligible',e);
            throw e;
        }  		
    }

    /*
    *  @AUTHOR:  Maruthi B
    *  @DESCRIPTION: TASK0754014-This Method to get update list 
    */
    private List<Account> getUpdateList(Set<Id> setAccountIds) { 
        
        List<Account> lstAccount = new AccountsSelector().selectRQAccounts(setAccountIds);  
		//added as part of TASK0754014
        List<AccountHistory> lstAccountHistory = new AccountHistorySelector().selectObjectHistory(setAccountIds,RQCONTACTELIGIBLE);
        Set<Id> setAccId = new Set<Id>();
        for(AccountHistory accHis : lstAccountHistory) {
            if(accHis.OldValue == True && accHis.NewValue == False) {
                setAccId.add(accHis.AccountId);    
            }             
        }                  
        List<Account> updateListAccount = new List<Account>();
        for(Account objAcc : lstAccount) {   
            if(setAccId.isEmpty() || !setAccId.isEmpty() && !setAccId.contains(objAcc.Id)) {
                objAcc.R_Q_Contact_Eligible__c = true;
                updateListAccount.add(objAcc);  
            }             
        }
        
        return updateListAccount;
    }
}