force-app/main/default/objects/Account/fields/Regulatory_Type__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Type__c</fullName>
    <description>Field to store regulatory codes</description>
    <label>Regulatory Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>DX_COMP</fullName>
            </value>
            <value>
                <fullName>DX_LOT_TRACKER</fullName>
            </value>
            <value>
                <fullName>DX_QC</fullName>
            </value>
            <value>
                <fullName>IUO</fullName>
            </value>
            <value>
                <fullName>IUO_COMP</fullName>
            </value>
            <value>
                <fullName>QC_COMP</fullName>
            </value>
            <value>
                <fullName>RUO</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>SA_COMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Product__c/Associated_Product__c.object-meta.xml
<CustomObject>
    <description>Associated Product can link to Case and/or Work Order</description>
    <label>Associated Product</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Associated Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Product__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <businessOwnerGroup>Service_Schema_Owners</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field links/relates the associated product record with Service/Maintenance Contract object having ERP Contract Type = Software (ZWS), ZCQ or Software Contract</description>
    <label>Subscription</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_of_Issue_Awareness__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Issue_Awareness__c</fullName>
    <description>Date of issue awareness</description>
    <inlineHelpText>Date Illumina became aware of a Business Issue</inlineHelpText>
    <label>Date of Issue Awareness</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PAE_PFA_Evaluation_Required__c.field-meta.xml
<CustomField>
    <fullName>PAE_PFA_Evaluation_Required__c</fullName>
    <defaultValue>$Label.CasePAEStatusPending</defaultValue>
    <description>Picklist to determine the pAE/pFA Evaluation Required value. Auto updated from pAE/pFA values in other fields.</description>
    <label>pAE/pFA Evaluation Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field links/related the Case record with  Service/Maintenance Contract object having ERP Contract Type = Software (ZWS), ZCQ or Software Contract and Account same as this Case</description>
    <label>Subscription</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 3 OR 4) AND 2) OR 5</booleanFilter>
        <errorMessage>The Contact on this case is unrelated to the account on the Subscription. Either 1) Select a Subscription that is related to the account OR 2) Select a different Contact and Account that matches the Subscription.</errorMessage>
        <filterItems>
            <field>SVMXC__Service_Contract__c.ERP_Contract_Type__c</field>
            <operation>equals</operation>
            <value>Software (ZWS)</value>
        </filterItems>
        <filterItems>
            <field>SVMXC__Service_Contract__c.SVMXC__Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>SVMXC__Service_Contract__c.ERP_Contract_Type__c</field>
            <operation>equals</operation>
            <value>Software Contract</value>
        </filterItems>
        <filterItems>
            <field>SVMXC__Service_Contract__c.ERP_Contract_Type__c</field>
            <operation>equals</operation>
            <value>Quantity Contract (ZCQ)</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipLabel>Cases (Subscription)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component SN</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Case1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product for which customer is seeking support. Reference to Product2 object.</description>
    <inlineHelpText>Choose or enter the Product name for which the customer is seeking support.</inlineHelpText>
    <label>Component Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</description>
    <inlineHelpText>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</inlineHelpText>
    <label>Service/Maintenance Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
    <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Cases Reported From This Site</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Inquiry.recordType-meta.xml
<RecordType>
    <fullName>Inquiry</fullName>
    <active>true</active>
    <businessProcess>Inquiry</businessProcess>
    <description>A communication that concerns procedural matters that can be resolved through training or guidance, requests information related to product after it has been released for distribution or seeks information regarding services offered by Illumina.</description>
    <label>Inquiry</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Regulatory_Type__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Type__c</fullName>
    <description>Field to store Regulatory Type.</description>
    <label>Regulatory Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Product_Type__c</fullName>
    <description>Field to specifytype of service product.</description>
    <label>Service Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved Tool</fullName>
                <isActive>false</isActive>
                <label>Approved Tool</label>
            </value>
            <value>
                <fullName>Approved Tool- Calibrated</fullName>
            </value>
            <value>
                <fullName>Approved Tool- Non-Calibrated</fullName>
            </value>
            <value>
                <fullName>Approved Tool- Reference</fullName>
            </value>
            <value>
                <fullName>Consumable</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>NONFRU</fullName>
            </value>
            <value>
                <fullName>Spare</fullName>
            </value>
            <value>
                <fullName>Standard Tool</fullName>
            </value>
            <value>
                <fullName>Tool</fullName>
                <isActive>false</isActive>
                <label>Tool</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Identify the source system that is creating the case in Salesforce</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
                <default>true</default>
                <label>SFDC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Regulatory_Type__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Type__c</fullName>
    <description>This field has been created as part of DCP-3090</description>
    <label>Regulatory Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>RUO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Service_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Product_Type__c</fullName>
    <description>Formula field that Indicates whether the Installed Product is Instrument, Spare, Core or Consumable. Used in various business logic and automations.</description>
    <formula>TEXT(SVMXC__Product__r.Service_Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
    <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>R00N70000001hzchEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used by Reverse Logistics Module. Reference to the latest service contract for this installed product. Derived automatically upon creating/updating service contract</description>
    <label>Service Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipName>Installed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing location record</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>R00N70000001hzcqEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/SVMXC__Service_Contract__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/ERP_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>ERP_Contract_Type__c</fullName>
    <description>Type of contract
Details to come in from SAP</description>
    <label>ERP Contract Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestUpdateAPwithIPProductSub_CaseHelper.cls
/***************************************************************************************************************************************
 * NAME   : TestUpdateAPwithIPProductSub_CaseHelper
 * DESCRIPTION  : Test Class for UpdateAPwithIPProductSub_CaseHelper (Code Coverage-91%)
 * @AUTHOR : Abhishek Yadav
 * @DATE   : 02-Nov-2024 
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Abhishek Yadav          16-Nov-2023             Initial Version
 ****************************************************************************************************************************************/ 
@isTest
public with sharing class TestUpdateAPwithIPProductSub_CaseHelper { 
    public static final String STRING_WO_RECORDTYPE = 'Field Service';
     public static final string STRING_INSTALLED_PRODUCT_NAME = 'Test IP';
     public static final string STRING_CURRENCY = 'USD';
     public static final string STRING_INSTALLED_PRODUCT_STATUS = 'New';
     public static final string STRING_CASE_INQ_RECORDTYPE = 'Inquiry';
     public static final string STRING_CASE_SR_RECORDTYPE = 'Service Request';
     public static final string STRING_CASE_BI_RECORDTYPE = 'Business Issue';
     public static final string STRING_CASE_STATUS = 'Initiated';
     public static final string STRING_CASE_ORIGIN = 'Phone - CS';
     public static final string STRING_LOCATION = 'Test Location';
     public static final string STRING_STREET = 'Test Street';
     public static final string STRING_PRODUCT_MATERIAL_CLASS = 'Consumable';
     public static final string STRING_PRODUCT_CODE = 'Test 1234';
     public static final string STRING_EVALUATION_ANSWER_PENDING = 'Pending';
    /**
    *  CMCM-263
    *  @author : Abhishek Yadav
    *  @description - insert Associated Product on Case Creation
    **/
    @isTest
    static void testAPInstallProduct() {

        // Create Account
        Account objAccount = TestDataAccount.getNewAccount();
        // Create Contact
        Contact con = new Contact();
        con.FirstName = 'testfirstname'; 
        con.LastName = 'testlastname'; 
        con.AccountId = objAccount.Id;
        con.Phone = '1234567890';
        con.email = 'abc@test.com.invalid';
        insert con;
        // insert Subscription
        SVMXC__Service_Contract__c objServiceContract = TestDataFieldService.createServiceContract(objAccount.Id);
        objServiceContract.ERP_Contract_Type__c = 'Software (ZWS)';
        insert objServiceContract;
        // insert Installed Product
        SVMXC__Installed_Product__c objInstalledProduct = TestDataFieldService.createInstalledProduct(STRING_INSTALLED_PRODUCT_NAME, STRING_CURRENCY, STRING_INSTALLED_PRODUCT_STATUS);
        insert objInstalledProduct;
        // insert Location
        SVMXC__Site__c objLocation = TestDataFieldService.createLocation(STRING_LOCATION,STRING_STREET,'Ireland','123456','USD');
         insert objLocation;
         // insert product 
         Product2 objProduct = TestDataMaster.initProduct(STRING_PRODUCT_CODE);
         objProduct.Service_Product_Type__c = STRING_PRODUCT_MATERIAL_CLASS;
         objProduct.Regulatory_Type__c = 'DX';
         objProduct.Source_System__c = 'SAP';
         insert objProduct;
       // insert Case
       Case objCase = TestDataCase.initNewCase(STRING_CASE_INQ_RECORDTYPE, STRING_CASE_STATUS, STRING_CASE_ORIGIN);
       objCase.PAE_PFA_Evaluation_Required__c = STRING_EVALUATION_ANSWER_PENDING; 
       objCase.Date_of_Issue_Awareness__c = Date.Today();      
       insert objCase;
       Test.startTest();
       objCase.SVMXC__Component__c = objInstalledProduct.Id; 
       objCase.SVMXC__Product__c = objProduct.Id; 
       objCase.RecordTypeId = UpdateAPwithIPProductSub_CaseHelper.BUSINESS_ISSUE_CASE_RECORDTYPE;    
       update objCase;
       List<Associated_Product__c> associatedList = [SELECT Id FROM associated_product__c LIMIT 1];
       Assert.isTrue(!associatedList.isEmpty(), 'associatedList should not blank');
       Test.stopTest();
   }
   /*  CMCM-263
   *  @author : Abhishek Yadav
   *  @description - insert Associated Product on Case Creation
   **/
   @isTest
   static void testAPProductNSubscription() {

        // Create Account
        Account objAccount = TestDataAccount.getCustomerAccount();
        insert objAccount;
        // Create Contact
        Contact con = new Contact();
        con.FirstName = 'testfirstname'; 
        con.LastName = 'testlastname'; 
        con.AccountId = objAccount.Id;
        con.Phone = '1234567890';
        con.email = 'abc@test.com.invalid';
        insert con;
        // insert Subscription
        SVMXC__Service_Contract__c objServiceContract = TestDataFieldService.createServiceContract(objAccount.Id);
        objServiceContract.ERP_Contract_Type__c = 'Software (ZWS)';
        insert objServiceContract;
        // insert Location
        SVMXC__Site__c objLocation = TestDataFieldService.createLocation(STRING_LOCATION,STRING_STREET,'Ireland','123456','USD');
        insert objLocation;
        // insert product 
        Product2 objProduct = TestDataMaster.initProduct(STRING_PRODUCT_CODE);
        objProduct.Service_Product_Type__c = STRING_PRODUCT_MATERIAL_CLASS;
        objProduct.Regulatory_Type__c = 'DX';
        objProduct.Source_System__c = 'SAP';
        insert objProduct;
        // insert Case
        Case objCase = TestDataCase.initNewCase(STRING_CASE_SR_RECORDTYPE, STRING_CASE_STATUS, STRING_CASE_ORIGIN);
        objCase.PAE_PFA_Evaluation_Required__c = STRING_EVALUATION_ANSWER_PENDING; 
        objCase.Date_of_Issue_Awareness__c = Date.Today();
        objCase.ContactId = con.id;
        insert objCase;
        Test.startTest();
        objCase.SVMXC__Product__c = objProduct.Id;
        objCase.Subscription__c = objServiceContract.id; 
        objCase.RecordTypeId = UpdateAPwithIPProductSub_CaseHelper.BUSINESS_ISSUE_CASE_RECORDTYPE;    
        update objCase;
        List<Associated_Product__c> associatedList = [SELECT Id FROM associated_product__c LIMIT 1];
        Assert.isTrue(!associatedList.isEmpty(), 'associatedList should not blank');
        Test.stopTest();
   }
   /*  CMCM-263
   *  @author : Abhishek Yadav
   *  @description - insert Associated Product on Case Creation
   **/
   @isTest
   static void testAPProduct() {

        // Create Account
        Account objAccount = TestDataAccount.getCustomerAccount();
        insert objAccount;
        // Create Contact
        Contact con = new Contact();
        con.FirstName = 'testfirstname'; 
        con.LastName = 'testlastname'; 
        con.AccountId = objAccount.Id;
        con.Phone = '1234567890';
        con.email = 'abc@test.com.invalid';
        insert con;
        // insert Location
        SVMXC__Site__c objLocation = TestDataFieldService.createLocation(STRING_LOCATION,STRING_STREET,'Ireland','123456','USD');
        insert objLocation;
        // insert product 
        Product2 objProduct = TestDataMaster.initProduct(STRING_PRODUCT_CODE);
        objProduct.Service_Product_Type__c = STRING_PRODUCT_MATERIAL_CLASS;
        objProduct.Regulatory_Type__c = 'DX';
        objProduct.Source_System__c = 'SAP';
        insert objProduct;
    // insert Case
        Case objCase = TestDataCase.initNewCase(STRING_CASE_SR_RECORDTYPE, STRING_CASE_STATUS, STRING_CASE_ORIGIN);
        objCase.PAE_PFA_Evaluation_Required__c = STRING_EVALUATION_ANSWER_PENDING; 
        objCase.Date_of_Issue_Awareness__c = Date.Today();
        objCase.ContactId = con.id;
        insert objCase;
        Test.startTest();
        objCase.SVMXC__Product__c = objProduct.Id;
        objCase.RecordTypeId = UpdateAPwithIPProductSub_CaseHelper.BUSINESS_ISSUE_CASE_RECORDTYPE;    
        update objCase;
        List<Associated_Product__c> associatedList = [SELECT Id FROM associated_product__c LIMIT 1];
        Assert.isTrue(!associatedList.isEmpty(), 'associatedList should not blank');
        Test.stopTest();
   }
   /*  CMCM-263
   *  @author : Abhishek Yadav
   *  @description - insert Associated Product on Case Creation
   **/
    @isTest
    static void testAPSubscription() {

        // Create Account
        Account objAccount = TestDataAccount.getCustomerAccount();
        insert objAccount;
        // Create Contact
        Contact con = new Contact();
        con.FirstName = 'testfirstname'; 
        con.LastName = 'testlastname'; 
        con.AccountId = objAccount.Id;
        con.Phone = '1234567890';
        con.email = 'abc@test.com.invalid';
        insert con;
        // insert Subscription
        SVMXC__Service_Contract__c objServiceContract = TestDataFieldService.createServiceContract(objAccount.Id);
        objServiceContract.ERP_Contract_Type__c = 'Software (ZWS)';
        insert objServiceContract;
        // insert Location
        SVMXC__Site__c objLocation = TestDataFieldService.createLocation(STRING_LOCATION,STRING_STREET,'Ireland','123456','USD');
            insert objLocation;
        // insert Case
        Case objCase = TestDataCase.initNewCase(STRING_CASE_SR_RECORDTYPE, STRING_CASE_STATUS, STRING_CASE_ORIGIN);
        objCase.PAE_PFA_Evaluation_Required__c = STRING_EVALUATION_ANSWER_PENDING; 
        objCase.Date_of_Issue_Awareness__c = Date.Today();
        objCase.ContactId = con.id;
        insert objCase;
        Test.startTest();
        objCase.Subscription__c = objServiceContract.id; 
        objCase.RecordTypeId = UpdateAPwithIPProductSub_CaseHelper.BUSINESS_ISSUE_CASE_RECORDTYPE;    
        update objCase;
        List<Associated_Product__c> associatedList = [SELECT Id FROM associated_product__c LIMIT 1];
        Assert.isTrue(!associatedList.isEmpty(), 'associatedList should not blank');
        Test.stopTest();
   }
}