force-app/main/default/objects/Account/fields/Regulatory_Type__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Type__c</fullName>
    <description>Field to store regulatory codes</description>
    <label>Regulatory Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>DX_COMP</fullName>
            </value>
            <value>
                <fullName>DX_LOT_TRACKER</fullName>
            </value>
            <value>
                <fullName>DX_QC</fullName>
            </value>
            <value>
                <fullName>IUO</fullName>
            </value>
            <value>
                <fullName>IUO_COMP</fullName>
            </value>
            <value>
                <fullName>QC_COMP</fullName>
            </value>
            <value>
                <fullName>RUO</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>SA_COMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <description>Flag to determine active account</description>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Field to capture external Id</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>Material Number of the affected part/product</description>
    <label>Material Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Field to hold PS External ID.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product for which customer is seeking support. Reference to Product2 object.</description>
    <inlineHelpText>Choose or enter the Product name for which the customer is seeking support.</inlineHelpText>
    <label>Component Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer location where the contact is reporting the problem or the location of the installed product.</description>
    <inlineHelpText>The customer location where the contact is reporting the problem or the location of the installed product.</inlineHelpText>
    <label>Site</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Cases Reported From This Site</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <description>Field to track Active ServiceMax</description>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Field to store External ID</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Auto_Create_Installation_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Installation_Workflow__c</fullName>
    <inlineHelpText>Field for Installation Case or Work Order creation requirement</inlineHelpText>
    <label>Auto Create Installation Workflow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto Create Install Work Order Only</fullName>
            </value>
            <value>
                <fullName>Auto Create Install Work Order and Service Request Case</fullName>
            </value>
            <value>
                <fullName>Auto Create Service Request Case Only</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <description>US-439
Product’s material number
Populated from SAP</description>
    <externalId>true</externalId>
    <label>Material Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Regulatory_Type__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Type__c</fullName>
    <description>Field to store Regulatory Type.</description>
    <label>Regulatory Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <description>Field to store Service Level.</description>
    <label>Service Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Product_Type__c</fullName>
    <description>Field to specifytype of service product.</description>
    <label>Service Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved Tool</fullName>
                <isActive>false</isActive>
                <label>Approved Tool</label>
            </value>
            <value>
                <fullName>Approved Tool- Calibrated</fullName>
            </value>
            <value>
                <fullName>Approved Tool- Non-Calibrated</fullName>
            </value>
            <value>
                <fullName>Approved Tool- Reference</fullName>
            </value>
            <value>
                <fullName>Consumable</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>NONFRU</fullName>
            </value>
            <value>
                <fullName>Spare</fullName>
            </value>
            <value>
                <fullName>Standard Tool</fullName>
            </value>
            <value>
                <fullName>Tool</fullName>
                <isActive>false</isActive>
                <label>Tool</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Unique field to store external id.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/SVMXC__Product_Stock__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Product stock is used to store inventory information for a product in a given location and status along with reorder information.</description>
    <label>Product Stock</label>
    <nameField>
        <displayFormat>STK-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMX_PS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_External_ID__c</fullName>
    <description>Product Stock External ID</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__IsPartnerRecord__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__IsPartnerRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if transaction is for/ by a Partner or not.</description>
    <inlineHelpText>Flag indicates if transaction is for/ by a Partner or not.</inlineHelpText>
    <label>IsPartnerRecord</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing site record.</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record.</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>Product_Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
    <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__Quantity2__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Quantity2__c</fullName>
    <description>Quantity of product in the provided location.</description>
    <inlineHelpText>Quantity of product in the provided location.</inlineHelpText>
    <label>Qty</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMX_PS_Active__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__IsPartnerRecord__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__IsPartnerRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates that Location belongs to a Partner.</description>
    <inlineHelpText>Flag indicates that Location belongs to a Partner.</inlineHelpText>
    <label>Is Partner Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Stocking_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Stocking_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</description>
    <inlineHelpText>Flag indicates if this is a stocking location or not. ServiceMax does not perform inventory updates on non-stocking locations.</inlineHelpText>
    <label>Stocking Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>To capture the type of location</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trunk</fullName>
            </value>
            <value>
                <fullName>Locker</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Ultimate Consignee</fullName>
            </value>
            <value>
                <fullName>Partner Stock</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Bill To</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Importer Of Record</fullName>
            </value>
            <value>
                <fullName>Customer Hierarchy</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
                <isActive>false</isActive>
                <label>Temporary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestProductStockSelector.cls
//TestProductStockSelector
/*@ author       : Prashanth
* @ date         : 20-08-2019
* @ Description  : Test class for ProductStockSelector class
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                              Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Prashanth                20-08-2019                        Initial version
*/
@isTest(SeeAllData=false)
public with sharing class TestProductStockSelector
{
    /**
    *  @author Bharath Kumar
    *  @description - test setupData
    **/
    @testSetup
    static void setupData()
    {
        TestDataMaster.createProduct(true);
 
    }

    /**
    *  @author Bharath Kumar
    *  @description - increasing test coverage
    **/
    static testMethod void testProductStockSelectorMethod(){

    	// Account objAccount = TestDataAccount.getNewAccount();
        Test.startTest();
        // Contact con = new Contact(FirstName = 'testfirstname', LastName = 'testlastname');
        Product2 prod = new Product2(Name='TestProd',
                                     Auto_Create_Installation_Workflow__c='Auto Create Install Work Order and Service Request Case',
                                     Service_Product_Type__c='Instrument',
                                     Regulatory_Type__c='DX',
                                     IsActive=true,
                                     ProductCode='43535',
                                     Material_Number__c = '1111',
                                     Service_Level__c = 'GOLD'
                                    );        
        insert prod;
        //SVMXC__Site__c location =TestDataFieldService.createLocation('ServiceLoc1','Stringing street New York','USA','43527','USD');
        SVMXC__Site__c shippingLocation = new SVMXC__Site__c(
        Name = 'testStockingLocation',
        CurrencyIsoCode = 'USD',
        SVMXC__Stocking_Location__c = true,
        SVMX_PS_Active__c = true,
        Type__c = 'Ship To');
        //list<SVMXC__Site__c> locList= new list<SVMXC__Site__c>();
        //locList.add(location);
        //locList.add(shippingLocation);
        insert shippingLocation;
        
        SVMXC__Site__c location =TestDataFieldService.createLocation('ServiceLoc1','Stringing street New York','USA','43527','USD');
        Location.SVMX_PS_External_ID__c = 'EXTLOC11223344';
        insert location;
        
        SVMXC__Product_Stock__c productStock = new SVMXC__Product_Stock__c();
		productStock.CurrencyIsoCode = 'USD';
		productStock.SVMXC__IsPartnerRecord__c = false;
		productStock.SVMXC__Location__c = location.Id;	
		productStock.SVMXC__Product__c = prod.Id;
		productStock.SVMXC__Quantity2__c = 1.0;
        productStock.SVMX_PS_External_ID__c = '1223';
		productStock.SVMXC__Status__c = 'Available';
		insert productStock;
        
        Set<Id> setproductStock = new Set<Id>{productStock.Id};
        Set<String> setExternalId = new Set<String>{productStock.SVMX_PS_External_ID__c};

		ProductStockSelector pse= new ProductStockSelector ();
		//pse.selectProductStockByLocationExtId(new set<string>{productStock.SVMX_PS_External_ID__c});
        system.assertNotEquals(null,location.SVMX_PS_External_ID__c);
        pse.selectProductStockByLocationAndProduct(new set<id>{location.Id},new set<id>{prod.Id});
        pse.selectProductStockByToFromLocationAndProduct(new set<id>{shippingLocation.Id},new set<id>{location.Id},new list<id>{prod.id},new Set<String>{productStock.SVMXC__Status__c}); 
        pse.selectProductStocksByIds(setproductStock);
        pse.selectProductStocksByExternalId(setExternalId);
            
		List<SVMXC__Product_Stock__c> lstProductStock = new List<SVMXC__Product_Stock__c>();
        lstProductStock = pse.selectProductStockByLocationExtId(new set<string>{location.SVMX_PS_External_ID__c});
        System.assertEquals(1, lstProductStock.size());
        
    }    

}