force-app/main/default/objects/Account/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Field to display internal Illumina Territory Region</description>
    <inlineHelpText>Internal Illumina territory region.</inlineHelpText>
    <label>Territory Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ClassificationName__c/Apttus_Config2__ClassificationName__c.object-meta.xml
<CustomObject>
    <description>Represents a category</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceList__c/Apttus_Config2__PriceList__c.object-meta.xml
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/Apttus_Config2__ProductConfiguration__c.object-meta.xml
<CustomObject>
    <description>Represents a product configuration</description>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/fields/GT_Check_Pending_Count__c.field-meta.xml
<CustomField>
    <fullName>GT_Check_Pending_Count__c</fullName>
    <description>Roll up summary to count GT Check Pending</description>
    <label>GT Check Pending Count</label>
    <summaryFilterItems>
        <field>Apttus_Config2__LineItem__c.Global_Trade_Block__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Apttus_Config2__LineItem__c.Apttus_Config2__ConfigurationId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ProductConfiguration__c/fields/Quote_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sub_Type__c</fullName>
    <description>Field to store Quote sub type</description>
    <formula>Apttus_QPConfig__Proposald__r.Quote_Sub_Type__c</formula>
    <label>Quote Sub Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Quote_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sub_Type__c</fullName>
    <description>Opportunity Type</description>
    <formula>TEXT(Apttus_Proposal__Opportunity__r.Type)</formula>
    <label>Quote Sub Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Sold_To_Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Distribution_Channel__c</fullName>
    <description>Text field to sold to distribution channel</description>
    <label>Sold To Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Stamped through the territory region of Sold to Account of Opportunity.</description>
    <formula>Apttus_Proposal__Opportunity__r.Account.Territory_Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Transborder_Flag__c.field-meta.xml
<CustomField>
    <fullName>Transborder_Flag__c</fullName>
    <description>Flag to check opportunity Transborder Flag</description>
    <formula>Apttus_Proposal__Opportunity__r.Transborder_Flag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transborder Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>As part of DCP-8330 for the capturing the values of Price List.</description>
    <label>Price List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <description>As part of DCP-814, this field captures the value of record type name of current opportunity which can then be used in validation rule</description>
    <label>RecordTypeName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sold_to_Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sold_to_Distribution_Channel__c</fullName>
    <description>Distribution Channel of Sold To Account</description>
    <label>Sold to Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <description>Territory Region of Account</description>
    <formula>Account.Territory_Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transborder_Flag__c.field-meta.xml
<CustomField>
    <fullName>Transborder_Flag__c</fullName>
    <description>Checkbox for Transborder Flag</description>
    <defaultValue>false</defaultValue>
    <label>Transborder Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestApttusDisplayActionCallbackCatalyst.cls
/*@ author       : Rahul Sharma
* @ date         : 20 April 2019
* @ Description  : Display action callback Catalyst test class
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                        Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* Rahul Sharma         20 Apr 2019                     Initial version
* Nishan Shetty        05-Jan-2023                     CodeScan Fix for Unused Local Variable.
*/
@isTest(isParallel=false)
private class TestApttusDisplayActionCallbackCatalyst {

    
    private static final String SUGGESTED_SALES = 'Apply_Remove';
    private static final String PRICELIST = '01-AMR-USD';
    private static final String AMR = 'AMR';
    private static final String USD = 'USD';
    private static final String OPPORTUNITYRTDIRECT = 'Direct';
    
    @testSetup
    static void setupData()
    {
        Apttus_Config2__PriceList__c objPriceList = TestDataProposal.initPriceList(PRICELIST);
        insert objPriceList;

        Account objAccount = TestDataAccount.getNewAccount();
        objAccount.Territory_Region__c =AMR;
        objAccount.CurrencyIsoCode=USD;
        Update objAccount;
        
        Opportunity objOpportunity = TestDataOpportunity.getNewOpportunity(objAccount);
        
        objOpportunity.RecordTypeName__c = OPPORTUNITYRTDIRECT;
        objOpportunity.Sold_to_Distribution_Channel__c = OPPORTUNITYRTDIRECT;
        objOpportunity.Transborder_Flag__c = true;
        objOpportunity.Price_List__c = objPriceList.Name;
        update objOpportunity;
                
        
        Apttus_Proposal__Proposal__c objProposal = TestDataProposal.initProposal(objAccount.id, objOpportunity.id, 'Test Proposal', objPriceList.id, true, 'Draft', 'None');
        insert objProposal;
        
        TestDataMaster.createProduct(true);//CodeScan Fix For Unused Local Variable.

        Apttus_Config2__ProductConfiguration__c newCart = TestDataProposal.getNewCart(objProposal);
                
        List<Apttus_Config2__ClassificationName__c> lstCategory = new List<Apttus_Config2__ClassificationName__c>();
          

        Apttus_Config2__ClassificationName__c objCategory = TestDataProposal.initCategory('Test Category');
        lstCategory.add(objCategory);
        insert lstCategory;
    
        List<Apttus_Config2__ConfigCustomDisplayActions__c> lstConfigDisplayActions = new List<Apttus_Config2__ConfigCustomDisplayActions__c>();
        
        Apttus_Config2__ConfigCustomDisplayActions__c objCustomSetting = new Apttus_Config2__ConfigCustomDisplayActions__c();
        objCustomSetting.Apttus_Config2__ActionLabelName__c = SUGGESTED_SALES;
        objCustomSetting.Apttus_Config2__ActionName__c = SUGGESTED_SALES;
        objCustomSetting.Apttus_Config2__Sequence__c = 1;
        objCustomSetting.Apttus_Config2__IsEnabled__c = false;
        objCustomSetting.Name = 'Test' + objCustomSetting.Apttus_Config2__Sequence__c + '' + System.now().millisecond();
        objCustomSetting.Apttus_Config2__DisplayType__c = 'Cart Line Item';
        lstConfigDisplayActions.add(objCustomSetting);

        insert lstConfigDisplayActions;  
    }

    /**
    *  @author Rahul  Sharma
    *  @description Test method for display action callback Catalyst
    **/
   
    
    @isTest
    static void testCallbackCatalyst()
    {   
        new PermissionSetAssignmentsSelector().selectPermissionSetAssigmentByName('Test');
        PermissionSet ps = new PermissionSet();
        ps.Name = 'Test_DisplayAction_Catalyst';
        ps.Label = 'Test_DisplayAction_Catalyst';
        insert ps;

        SetupEntityAccess sea = new SetupEntityAccess();
        sea.ParentId = ps.Id;
        sea.SetupEntityId = [select Id from CustomPermission where DeveloperName = 'Check_Catalyst_Discount'][0].Id;
        insert sea;

        
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = UserInfo.getUserId();
        psa.PermissionSetId = ps.Id;
        insert psa; 

        String strSysAdmin = 'System Administrator';
        Set<Id> setUserId = UtilsCollection.getSetOfIds([SELECT AssigneeId FROM PermissionSetAssignment 
                                                         WHERE Assignee.Profile.Name= :strSysAdmin
                                                            AND PermissionSet.Name='Test_DisplayAction_Catalyst']
                                                        ,'AssigneeId');
        
        User objUser = TestDataUser.findUserInProfile(strSysAdmin,setUserId,true);

        //System.runAs(new User(Id = UserInfo.getUserId())){  
        System.runAs(objUser){
        Apttus_Proposal__Proposal__c proposal = [Select Id from Apttus_Proposal__Proposal__c limit 1];
        Product2 thisProduct = [Select Id from product2 limit 1];

        Apttus_CPQApi.CPQ.CreateCartRequestDO createCartRequest = new Apttus_CPQApi.CPQ.CreateCartRequestDO();
        createCartRequest.QuoteId = proposal.Id;

        Apttus_Config2__ProductConfiguration__c objProductConfig = [SELECT Id,Quote_Sub_Type__c,GT_Check_Pending_Count__c from Apttus_Config2__ProductConfiguration__c LIMIT 1];  

        Apttus_CPQApi.CPQ.AddMultiProductRequestDO addProductRequest = new Apttus_CPQApi.CPQ.AddMultiProductRequestDO();
        addProductRequest.CartId = objProductConfig.Id;
        
        Apttus_CPQApi.CPQ.SelectedProductDO selectedProduct = new Apttus_CPQApi.CPQ.SelectedProductDO();
        selectedProduct.ProductId = thisProduct.Id;
        selectedProduct.Quantity = 1;
        selectedProduct.SellingTerm = 12;
        addProductRequest.SelectedProducts.add(selectedProduct);

        Apttus_CPQApi.CPQWebService.addMultiProducts(addProductRequest);

        List<Apttus_Config2__ConfigCustomDisplayActions__c> lstConfigDisplayActions = [SELECT Id, Name, Apttus_Config2__ActionName__c, Apttus_Config2__ActionLabelName__c, Apttus_Config2__DisplayType__c, Apttus_Config2__ActionPage__c, Apttus_Config2__IsEnabled__c, Apttus_Config2__Sequence__c FROM Apttus_Config2__ConfigCustomDisplayActions__c ];
        List<Apttus_Config2.DisplayActionInfo> lstDisplayActions = new List<Apttus_Config2.DisplayActionInfo>();

        Apttus_Config2.DisplayActionInfo oDisplayActionInfo;

        for( Apttus_Config2__ConfigCustomDisplayActions__c oTempCustomSetting : lstConfigDisplayActions){
            oDisplayActionInfo = new Apttus_Config2.DisplayActionInfo(oTempCustomSetting);
            oDisplayActionInfo.IsEnabled = false;
            lstDisplayActions.add(oDisplayActionInfo);
        }

        Test.startTest();
        ApttusDisplayActionCallback objDisplayActionCallback = new ApttusDisplayActionCallback();
        try{
            objDisplayActionCallback.start(null, lstDisplayActions);
        } catch(Exception e){
            System.debug('Exception : '+ e);
        }
        Apttus_Config2.ProductConfiguration objCart;
        objDisplayActionCallback.objProductConfig = objProductConfig;
        objDisplayActionCallback.start(objCart,lstDisplayActions);
        objDisplayActionCallback.setActionProperties(null);
        Test.stopTest();
        System.assertEquals(1, [SELECT COUNT() FROM Apttus_Config2__ConfigCustomDisplayActions__c WHERE Apttus_Config2__IsEnabled__c = false]);
    }
}
    
}