force-app/main/default/objects/Apttus_Config2__Incentive__c/Apttus_Config2__Incentive__c.object-meta.xml
<CustomObject>
    <description>Represents an incentive associated with one or more products</description>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41005: create new field to store Approval Required details.</description>
    <label>Approval Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DCP-41005: create new field to store Approver details.</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Incentives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Apttus_Config2__Active__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the incentive is active</description>
    <inlineHelpText>Indicates whether the incentive is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Apttus_Config2__Description__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__Description__c</fullName>
    <description>The incentive description</description>
    <inlineHelpText>The incentive description</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Apttus_Config2__ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ExpirationDate__c</fullName>
    <defaultValue>DATE(2099,12,31)</defaultValue>
    <description>The incentive expiration date. The incentive becomes ineffective after this date.</description>
    <inlineHelpText>The incentive expiration date. The incentive becomes ineffective after this date.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Apttus_Config2__IncentiveCode__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__IncentiveCode__c</fullName>
    <description>The incentive code available to customers to identify the incentive</description>
    <inlineHelpText>The incentive code available to customers to identify the incentive</inlineHelpText>
    <label>Incentive Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Change_History__c.field-meta.xml
<CustomField>
    <fullName>Change_History__c</fullName>
    <description>DCP-41005: create new field to store Change History.</description>
    <label>Change History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>DCP-41005: create new field to store Country.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <description>DCP-41005: create new field to store customer description.</description>
    <label>Customer Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>DCP-41005: create new field to store Distribution Channel.</description>
    <label>Distribution Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Distribution_Channel_Description__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel_Description__c</fullName>
    <description>DCP-41005: create new field to store Distribution Channel Description.</description>
    <label>Distribution Channel Description</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Limit_View__c.field-meta.xml
<CustomField>
    <fullName>Limit_View__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41005: create new field to store Limit View.</description>
    <label>Limit View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Master_Promotions__c.field-meta.xml
<CustomField>
    <fullName>Master_Promotions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Promotions</label>
    <referenceTo>Promotions__c</referenceTo>
    <relationshipLabel>Incentives</relationshipLabel>
    <relationshipName>Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <description>DCP-41005: create new field to store Primary Product Line details.</description>
    <label>Primary Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Promo_Channel__c.field-meta.xml
<CustomField>
    <fullName>Promo_Channel__c</fullName>
    <description>DCP-41005:Modifed field from text to multipicklist.</description>
    <label>Promo Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>OL</fullName>
            </value>
            <value>
                <fullName>O1</fullName>
            </value>
            <value>
                <fullName>O2</fullName>
            </value>
            <value>
                <fullName>O3</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>F1</fullName>
            </value>
            <value>
                <fullName>F2</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Promotion_Channel_Description__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Channel_Description__c</fullName>
    <description>DCP-41005: create new field to store Promotion Channel Description.</description>
    <label>Promotion  Channel Description</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online/Quoting</fullName>
            </value>
            <value>
                <fullName>Online Only</fullName>
            </value>
            <value>
                <fullName>Online Only – One Use Per UC</fullName>
            </value>
            <value>
                <fullName>Online Only – Two Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Online Only – Three Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Quoting Only</fullName>
            </value>
            <value>
                <fullName>Quoting Only – One Use Per UC</fullName>
            </value>
            <value>
                <fullName>Quoting Only – Two Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Quoting Only – Three Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Online/Quoting – One User Per UC</fullName>
            </value>
            <value>
                <fullName>Online/Quoting – Two Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Online/Quoting – Three Uses Per UC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Promotion_Details__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Details__c</fullName>
    <description>DCP-41005: create new field to store Promotion Details.</description>
    <label>Promotion Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Promotion_Owner__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DCP-41005: create new field to store promotion owner.</description>
    <label>Promotion Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Promotion_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Terms_and_Conditions__c</fullName>
    <label>Promotion Terms and Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Regions__c.field-meta.xml
<CustomField>
    <fullName>Regions__c</fullName>
    <description>DCP-41005: create new field to store Regions.</description>
    <label>Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMR</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <isActive>false</isActive>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>AMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
                <isActive>false</isActive>
                <label>APAC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <description>DCP-41005: create new field to store sales description.</description>
    <label>Sales Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>DCP-41005: create new field to store Sales Org.</description>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Stackable__c.field-meta.xml
<CustomField>
    <fullName>Stackable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41005: create new field to store Stackable.</description>
    <label>Stackable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>AT01</fullName>
    </customValue>
    <customValue>
        <fullName>AU01</fullName>
    </customValue>
    <customValue>
        <fullName>BE01</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
    </customValue>
    <customValue>
        <fullName>CN01</fullName>
    </customValue>
    <customValue>
        <fullName>CN02</fullName>
    </customValue>
    <customValue>
        <fullName>CN03</fullName>
    </customValue>
    <customValue>
        <fullName>DE01</fullName>
    </customValue>
    <customValue>
        <fullName>CO01</fullName>
    </customValue>
    <customValue>
        <fullName>DK01</fullName>
    </customValue>
    <customValue>
        <fullName>ES01</fullName>
    </customValue>
    <customValue>
        <fullName>FI01</fullName>
    </customValue>
    <customValue>
        <fullName>FR01</fullName>
    </customValue>
    <customValue>
        <fullName>FR02</fullName>
    </customValue>
    <customValue>
        <fullName>FR90</fullName>
    </customValue>
    <customValue>
        <fullName>GB01</fullName>
    </customValue>
    <customValue>
        <fullName>GB02</fullName>
    </customValue>
    <customValue>
        <fullName>GB03</fullName>
    </customValue>
    <customValue>
        <fullName>GB90</fullName>
    </customValue>
    <customValue>
        <fullName>HK01</fullName>
    </customValue>
	<customValue>
        <fullName>IE01</fullName>
    </customValue> 
	<customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IS01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>JP01</fullName>
    </customValue>
    <customValue>
        <fullName>KR01</fullName>
    </customValue>
    <customValue>
        <fullName>NL01</fullName>
    </customValue>
    <masterLabel>Sales Org</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/IncentiveSelector.cls
/**
*    @author: Pankaj Singla
*    @date:   08-Sept-2020
*    @description:  Selector Class for Apttus_Config2__Incentive__c
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Pankaj Singla              08 Sept 2020           Initial Build
              
*    ------------------------------------------------------------------------------------ 
*                    
*/
public with sharing class IncentiveSelector extends ilib_SObjectSelector{
	/**
    *  @author Pankaj Singla
    *  @description  
    *  @return SObjectType The Schema.SObjectType of the proposal
    **/	
     public Schema.SObjectType getSObjectType(){
        return Apttus_Config2__Incentive__c.sObjectType;
     }
     
    /**
     *  @author  Pankaj Singla
     *  @description Retrieve list of fields for Apttus_Config2__Incentive__c
     *  @return sObjectFieldList list of Schema.SObjectField
     **/
      public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
            Apttus_Config2__Incentive__c.Id,
            Apttus_Config2__Incentive__c.Apttus_Config2__Active__c,
            Apttus_Config2__Incentive__c.Approval_Required__c,
            Apttus_Config2__Incentive__c.Approver__c,
            Apttus_Config2__Incentive__c.Change_History__c,
            Apttus_Config2__Incentive__c.Country__c,
            Apttus_Config2__Incentive__c.Customer_Description__c,
            Apttus_Config2__Incentive__c.Distribution_Channel__c,
            Apttus_Config2__Incentive__c.Distribution_Channel_Description__c,
            Apttus_Config2__Incentive__c.Distribution_Channel_Description__c,
            Apttus_Config2__Incentive__c.Apttus_Config2__ExpirationDate__c,
            Apttus_Config2__Incentive__c.Limit_View__c,
            Apttus_Config2__Incentive__c.Apttus_Config2__Description__c,
            Apttus_Config2__Incentive__c.Primary_Product_Line__c,
            Apttus_Config2__Incentive__c.Promotion_Channel_Description__c,
            Apttus_Config2__Incentive__c.Promo_Channel__c,
            Apttus_Config2__Incentive__c.Apttus_Config2__IncentiveCode__c,
            Apttus_Config2__Incentive__c.Name,
            Apttus_Config2__Incentive__c.Promotion_Details__c,
            Apttus_Config2__Incentive__c.Promotion_Owner__c,
            Apttus_Config2__Incentive__c.Regions__c,
            Apttus_Config2__Incentive__c.Sales_Org__c,
            Apttus_Config2__Incentive__c.Sales_Description__c,
            Apttus_Config2__Incentive__c.Stackable__c,
            Apttus_Config2__Incentive__c.Promotion_Terms_and_Conditions__c,
            Apttus_Config2__Incentive__c.Master_Promotions__c
        
        };
      }
     /**
     *  @author Pankaj Singla
     *  @description Fetch the Incentive Records
     *  @param setPromotionIds- Set of promotion Ids
     *  @return List of Incentive Records
     **/ 
      public List<Apttus_Config2__Incentive__c> selectIncentiveList(Set<Id> setPromotionIds) {
            return (List<Apttus_Config2__Incentive__c>) Database.query(
                newQueryFactory().setCondition('Master_Promotions__c IN :setPromotionIds').toSOQL()
                
            );
      }

}