force-app/main/default/objects/Apttus_Config2__Incentive__c/Apttus_Config2__Incentive__c.object-meta.xml
<CustomObject>
    <description>Represents an incentive associated with one or more products</description>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41005: create new field to store Approval Required details.</description>
    <label>Approval Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Change_History__c.field-meta.xml
<CustomField>
    <fullName>Change_History__c</fullName>
    <description>DCP-41005: create new field to store Change History.</description>
    <label>Change History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>DCP-41005: create new field to store Country.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__Incentive__c/fields/Master_Promotions__c.field-meta.xml
<CustomField>
    <fullName>Master_Promotions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Promotions</label>
    <referenceTo>Promotions__c</referenceTo>
    <relationshipLabel>Incentives</relationshipLabel>
    <relationshipName>Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotions__c/Promotions__c.object-meta.xml
<CustomObject>
    <description>Represents a promotion associated with one or more products. Source of majority of the data is ERP (SAP) system</description>
    <label>Promotions</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotions__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <description>This checkbox indicates if approval is required or not for given promotion.</description>
    <defaultValue>false</defaultValue>
    <label>Approval Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Change_History__c.field-meta.xml
<CustomField>
    <fullName>Change_History__c</fullName>
    <description>This field denotes change history for given promotion.</description>
    <label>Change History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This text field stores country for promotion.</description>
    <inlineHelpText>What countries this promotion targets, if any</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Code__c</fullName>
    <description>This field is used to store promo external id which is synced from SAP.</description>
    <externalId>true</externalId>
    <label>Promotion Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPromotions.cls
@isTest
/**
*    @author: Pankaj Singla
*    @date:   09-Sept-2020
*    @description:  Test Class for Promotions
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Pankaj Singla              09 Sept 2020           Initial Build
              
*    ------------------------------------------------------------------------------------ 
*                    
*/
public with sharing class TestPromotions {
     
    /**
     * @author Pankaj Singla
     * @date   2020-09-09
     * @description  Test the insert and update of Promotion Record
     * 
     **/
    static testmethod void testpromotionTrigger(){
        Promotions__c objPromotion=new Promotions__c(Approval_Required__c=true,Change_History__c='test',
         Country__c='India',Name='test',Promotion_Code__c='123');
        insert objPromotion;
        Apttus_Config2__Incentive__c objincentive=[select id,name from Apttus_Config2__Incentive__c 
                                                   where Master_Promotions__c=:objPromotion.Id];
        system.assertEquals(objincentive.Name, objPromotion.Promotion_Code__c);
        objPromotion.Promotion_Code__c='345';
    	update objPromotion;
        
    }
    
    
}