force-app/main/default/objects/Channel_Partner_Quota__c/Channel_Partner_Quota__c.object-meta.xml
<CustomObject>
    <description>Stores channel partners&apos; quota information. The data is used by internal users (such as CP owner, GCP) for tracking and reporting</description>
    <label>Channel Partner Quota</label>
    <nameField>
        <label>Quota Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Quotas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner_Quota__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Lookup field to Account</description>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Channel Partner Quotas</relationshipLabel>
    <relationshipName>Channel_Partner_Quotas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TAPS_ChannelPartnerQuotas.cls
/***************************************************************************************************************************************
* NAME   : TAPS_ChannelPartnerQuotas 
* DESCRIPTION: Created for TASK0748834
*
* Modification Log:
* Developer     Date            Description
* Koustubh M    22-May-2022     TASK0748834 Added Channel_Partner_Quota__c
* --------------------------------------------------------------------------------------------------------------------------------------
*/
public without sharing class TAPS_ChannelPartnerQuotas extends TAPS_ComposedBase implements TAPS_IObjectsDirect {

    /* 
    * @description: To return Object API Name
    * @return: SObjectType
    */
    public override SObjectType getObjectType() {
        return Channel_Partner_Quota__c.sObjectType;
    }

	/* 
    * @description: To return Field API Name
    * @return: SObjectType
    */
    public override String getLookupFieldName() {
        return 'Account_Name__c';
    }

	/* 
    * @description: To return Object API Name
    * @return: SObjectType
    */
    public override SObjectType getShareObjectType() {
        return Channel_Partner_Quota__Share.sObjectType;
    }

	/* 
    * @description: To return Field API Name
    * @return: SObjectType
    */	
    public override String getShareParentFieldName() {
        return 'ParentId';
    }

	/* 
    * @description: Create Sharing Record
    * @Param: Id, Id
    * @return: SObject
    */
    public override SObject createSharingRecord(Id recordId, Id userId) {
        return new Channel_Partner_Quota__Share(
                UserOrGroupId = userId,
                ParentId = recordId,
                AccessLevel = 'Edit',
                RowCause = Schema.Channel_Partner_Quota__Share.RowCause.Manual
        );
    }

}