force-app/main/default/objects/Missing_Product__c/Missing_Product__c.object-meta.xml
<CustomObject>
    <description>It is used to store ProductCodes for SAP shipped parts (in PartsOrderDataReceiver - for example Substitutions) that are missing in SFDC.</description>
    <label>Missing Product</label>
    <nameField>
        <label>Missing Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missing Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Missing_Product__c/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <description>This field will map to the missing product material number.</description>
    <externalId>true</externalId>
    <label>Product External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Missing_Products__c/Missing_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>It is used to store ProductCodes(in csv) for SAP shipped parts(in PartsOrderDataReceiver) missing products in SFDC.</description>
    <label>Missing Products</label>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Product_Code1__c.field-meta.xml
<CustomField>
    <fullName>Product_Code1__c</fullName>
    <description>This field is used to store Product Code value from Installed Product rest interface.</description>
    <externalId>true</externalId>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
    <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>R00N70000001hzchEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/SVMXC__RMA_Shipment_Line__c.object-meta.xml
<CustomObject>
    <description>ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both. Parts Order Line lists parts returned or shipped.</description>
    <label>Parts Order Line</label>
    <nameField>
        <displayFormat>LN-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/Product_Code1__c.field-meta.xml
<CustomField>
    <fullName>Product_Code1__c</fullName>
    <description>This field is used only in SFM Transactions as a display field in read-only mode. Also used in PartsOrderDataReceiver to store ProductCodes of shipped Parts</description>
    <externalId>true</externalId>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Line__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product to be shipped/received. Is a lookup to an existing salesforce product record</description>
    <inlineHelpText>Name of the product to be shipped/received. Is a lookup to an existing salesforce product record</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>RMA_Shipment_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateProductOnPOLsIPs.cls
/***************************************************************************************************************************************
* NAME   : UpdateProductOnPOLsIPs
* DESCRIPTION  : Logic for updating POLs/IPs product when product synced to SFDC
*                    
* @AUTHOR : Tapas
* @DATE   : 16-Jul-2021  
* 
* MODIFICATION LOG: 
* -----------------------------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
* ------------------------------------------------------------------------------------------------------------------------------------------------------------
* Tapas             	   16-Jul-2021          Initial Version. 
* Shivani Jain             22-Aug-2022          DCP-50068 Add a new field for handling more products for Missing products Functionality
* Priya Mukherjee          30-Apr-2024          CMCM-2846 Modify implementation related to Missing product functionality
******************************************************************************************************************************************************************/
public with sharing class UpdateProductOnPOLsIPs implements ilib_AdminOperationLogicInterface{
    private static final String LOG_TITLE = 'UpdateProductOnPOLsIPs';

    /*******************************************************************************************************
    * @description Run Business Logic for updating Installed products, Missing products & POLs
    * @param lstProductIds List<Id>
    * @return void
    * Modified - CMCM-2846 - added logic to replace custom settings Missing_Products__c with custom object Missing_Product__c
    */
    public static void doBusinessLogic(List<Id> lstProductIds){
        system.debug('Inside doBusinessLogic');
        ilib_LogEvent.rootTitle = LOG_TITLE;  
        ilib_LogEvent.push(LOG_TITLE + '.doBusinessLogic()');
        
        try{
            Set<Id> setProdIds = new Set<Id>(lstProductIds);
            List<Product2> lstProds = new ProductsSelector().selectProducts(setProdIds);
            Map<String,Product2> prodCodeToProd = (Map<String,Product2>)UtilsCollection.getMapOfStringToSObject(lstProds,'ProductCode',Map<String, Product2>.class);
            
            List<SVMXC__RMA_Shipment_Line__c> lstPOLs = new PartsOrderLineSelector().selectPOLsFromProductExtIds(prodCodeToProd.keySet());
            List<SVMXC__Installed_Product__c> lstIPs = new InstalledProductsSelector().selectIPsFromProductExtIds(prodCodeToProd.keySet());

            system.debug('lstPOLs=='+ lstPOLs);
            system.debug('prodCodeToProd=='+ prodCodeToProd);
            system.debug('lstIPs=='+ lstIPs);
            updateRelatedRecords(lstPOLs, prodCodeToProd);
            updateRelatedRecords(lstIPs, prodCodeToProd);

            // Query and delete Matching Missing_Product__c records
            List<Missing_Product__c> missingProducts = [SELECT Id, Product_External_Id__c FROM Missing_Product__c WHERE Product_External_Id__c IN :prodCodeToProd.keySet()];
            system.debug('missingProducts=='+ missingProducts);
            delete missingProducts;

            ilib_LogEvent.message('Processed POLs and IPs updates. Missing products deleted: ' + missingProducts.size());

        } catch (Exception ee) {
            ApexExceptions.emit(LOG_TITLE, lstProductIds.get(0), ee);
        }
        
        ilib_LogEvent.pop();
        ilib_LogEvent.emit();
    }

    private static void updateRelatedRecords(List<SObject> records, Map<String, Product2> prodCodeToProd) {
        system.debug('Inside updateRelatedRecords');
        for (SObject record : records) {
            String productCode = (String) record.get('Product_Code1__c');
            if (record.get('SVMXC__Product__c') == null && productCode != null && prodCodeToProd.containsKey(productCode)) {
                system.debug('Inside updateRelatedRecords iF statement');
                record.put('SVMXC__Product__c', prodCodeToProd.get(productCode).Id);
            }
        }
        system.debug('records=='+ records);
        if (!records.isEmpty()) {
            update records;
        }
    }
}