force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>This is to capture feedback related to knowledge.</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB-{000000}</displayFormat>
        <label>Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Feedback_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Disposition__c</fullName>
    <description>To capture feedback state</description>
    <label>Feedback Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Feedback_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Reason__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Reason__c</fullName>
    <description>To capture feedback reason for the given feedback</description>
    <label>Feedback Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wrong Information</fullName>
            </value>
            <value>
                <fullName>Typo</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Missing Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Status__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Status__c</fullName>
    <description>To capture if status is open or closed</description>
    <label>Feedback Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Knowledge_Article_Link__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture Knowledge article for which feedback given.</description>
    <label>Knowledge Article Link</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Article_Body__c.field-meta.xml
<CustomField>
    <fullName>Article_Body__c</fullName>
    <description>Rich text editor to capture Knowledge Article content.</description>
    <label>Article Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Article_Version_Author__c.field-meta.xml
<CustomField>
    <fullName>Article_Version_Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person who has written the article and can be contacted for the content of that article.</description>
    <inlineHelpText>Please enter your name here if you are writing this article version. For questions on this content please add a post and @mention the Article Version Author.</inlineHelpText>
    <label>Article Version Author</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Primary_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Primary_Workflow__c</fullName>
    <description>Workflow for approval process. Manually filled. The picklist values in both primary and secondary workflow fields need to be in sync</description>
    <label>Primary Workflow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bioinformatics</fullName>
            </value>
            <value>
                <fullName>Bulletins</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>External Content</fullName>
            </value>
            <value>
                <fullName>Instrumentation</fullName>
            </value>
            <value>
                <fullName>Library Preparation</fullName>
            </value>
            <value>
                <fullName>Mega Guide</fullName>
            </value>
            <value>
                <fullName>Microarray</fullName>
            </value>
            <value>
                <fullName>Process Guidelines</fullName>
            </value>
            <value>
                <fullName>Product Support</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Secondary_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Workflow__c</fullName>
    <description>Workflow for approval process. Manually filled. The picklist values in both primary and secondary workflow fields need to be in sync.</description>
    <label>Secondary Workflow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bioinformatics</fullName>
            </value>
            <value>
                <fullName>Bulletins</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>External Content</fullName>
            </value>
            <value>
                <fullName>Instrumentation</fullName>
            </value>
            <value>
                <fullName>Library Preparation</fullName>
            </value>
            <value>
                <fullName>Mega Guide</fullName>
            </value>
            <value>
                <fullName>Microarray</fullName>
            </value>
            <value>
                <fullName>Process Guidelines</fullName>
            </value>
            <value>
                <fullName>Product Support</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/FAQ.recordType-meta.xml
<RecordType>
    <fullName>FAQ</fullName>
    <active>true</active>
    <description>Concise answers to Frequently Asked Questions</description>
    <label>FAQ</label>
</RecordType>

force-app/main/default/classes/TestFeedItem.cls
/**
 *    @author Anisha Bharti
 *    @date   19-Nov-2020
 *    @description  Test class of FeedItem
 *    Modification Log:
 *    ---------------------------------------------------------------------------------------------------------------------------------
 *     Developer                      Date                Description
 *  
 *    ------------------------------------------------------------------------------------------------------------------------------------------------
 */
@isTest
public with sharing class TestFeedItem {
    
    public static final String VALIDATIONSTATUS_PENDINGREVIEW = 'Pending Review';
    public static final String REVIEWSTATUS_PENDINGREVIEW = 'Pending Review - Review Not Started';
    public static final Id FAQ_RECORD_TYPE_ID = Schema.SObjectType.Knowledge__Kav.getRecordTypeInfosByName().get('FAQ').getRecordTypeId();
    public static final String REVIEWSTATUS_REVIEWCOMPLETE = 'Review Completed';
    
    /*
    *@author: Anisha Bharti
    *@Desc: Test method 
    */
    @testSetup 
    static void setupData(){
        Knowledge__kav know = new Knowledge__kav();
        know.Article_Body__c = 'I am the Article body';
        know.Title = 'New "Article"';
        know.Summary = 'Test Article Summary';
        know.UrlName = 'New--Article';
        know.Primary_Workflow__c = 'Instrumentation';
		know.Secondary_Workflow__c = 'Instrumentation';
        know.Article_Version_Author__c = userinfo.getuserid();
        Know.RecordtypeId = FAQ_RECORD_TYPE_ID;
        insert know;
        
        Feedback__c feed = new Feedback__c();
        feed.Knowledge_Article_Link__c = know.id;
        feed.Feedback_Status__c = 'Open';
        feed.Feedback_Disposition__c = 'New';
        feed.Feedback_Reason__c = 'Sequencing';
        insert feed;        
    }
    
    /**
    *    @author Anisha Bharti
    *    @date   20-Nov-2020
    *    @test Method onafterinsert of FeedItem
    */
    @isTest
    static void testonafterinsert(){
        Feedback__c feed = [select id, name, ownerid from feedback__c LIMIT 100];
       
        Test.startTest();
            user newOwner = [Select id, name, email, isactive, profile.name, userrole.name, usertype from user where Profile.name = 'System Administrator' AND id != :userinfo.getUserId() AND IsActive = TRUE LIMIT 1];
                  
            Feedback__c objFB = new Feedback__c();   
            objFB.Id = feed.Id;
            objFB.OwnerId = newOwner.Id;
            update objFB;

            FeedItem fItem = new FeedItem();
            fItem.ParentId = feed.Id;
            fItem.Body = 'Tests';
            insert fItem;

            system.assertEquals(1, Limits.getEmailInvocations());
        Test.stopTest();
    }
    
    static String getRandomString() {
        String strHashString = '1000' + String.valueOf(Datetime.now().formatGMT('yyyy-MM-dd HH:mm:ss.SSS'));
        Blob bbHash = Crypto.generateDigest('MD5', Blob.valueOf(strHashString));
        String strHexDigest = EncodingUtil.convertToHex(bbHash);
        return strHexDigest;
    }

}