force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>This is to capture feedback related to knowledge.</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB-{000000}</displayFormat>
        <label>Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Feedback_Owner__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Owner__c</fullName>
    <description>To capture feedback owner</description>
    <formula>IF(Owner:Queue.QueueName = &quot;&quot;,
        HYPERLINK(&apos;/&apos; + OwnerId , Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName),
        HYPERLINK(&apos;/p/own/Queue/d?id=&apos; + OwnerId , Owner:Queue.QueueName )
        )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Feedback Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FeedbackSelector.cls
/**
 *    @author Anisha Bharti
 *    @date   19-Nov-2020
 *    @description : Feedback Selector class
 *    Modification Log:
 *    ------------------------------------------------------------------------------------ 
 *    Developer                      Date                  Description
 *  
 *    ------------------------------------------------------------------------------------ 
 *                    
 */
public with sharing class FeedbackSelector extends ilib_SObjectSelector{
    /**
    *  @author Anisha
    *  @description Method to fetch Feedback fields
    *  @param none
    *  @return List
    **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {   
        return new List<Schema.SObjectField> {
            
            Feedback__c.id,
            Feedback__c.Name,
            Feedback__c.ownerid,
            Feedback__c.Feedback_Owner__c,
            Feedback__c.createdById
        };
    }

     /**
    *  @author Anisha
    *  @description Method to fetch sobjecttyhpe of feedback
    *  @param none
    *  @return SObjectType The Schema.SObjectType of Feedback
    **/
    public Schema.SObjectType getSObjectType()
    { 
        return Feedback__c.sObjectType;
    }
    
    /**
    *  @author Anisha
    *  @param Set<Id>
    *  @return List
    **/
    public List<Feedback__c> getFeedbackByIds(Set<ID> setIds)
    {
        return (List<Feedback__c>)Database.query(newQueryFactory().setCondition('ID IN :setIds').toSOQL());
    }
}