force-app/main/default/objects/SVMXC__Product_Serial__c/SVMXC__Product_Serial__c.object-meta.xml
<CustomObject>
    <description>This object is used to track serial numbers in a product&apos;s inventory at a given location.</description>
    <label>Stocked Serial/Batch Detail</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocked Serial/Batch Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <description>To store the value of Batch Number coming from SAP.</description>
    <label>Batch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>To fetch the product code of the associated product.</description>
    <formula>SVMXC__Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/Product_Stock_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Stock_Status__c</fullName>
    <description>To capture the value of product stock associated with the stock serial.</description>
    <formula>TEXT(SVMXC__Product_Stock__r.SVMXC__Status__c)</formula>
    <label>Product Stock Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>To default the stock serial quantity to 1.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/SVMX_PS_VS_Linked_Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_VS_Linked_Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Linked_Installed_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/SVMXC__Active__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicates Serial Number record is active or not.</description>
    <inlineHelpText>Flag indicates Serial Number record is active or not.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Serial__c/fields/SVMXC__Product_Stock__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to an existing product-stock record.</description>
    <inlineHelpText>This is a lookup to an existing product-stock record.</inlineHelpText>
    <label>Product Stock</label>
    <referenceTo>SVMXC__Product_Stock__c</referenceTo>
    <relationshipName>Product_Serial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/SVMXC__Product_Stock__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Product stock is used to store inventory information for a product in a given location and status along with reorder information.</description>
    <label>Product Stock</label>
    <nameField>
        <displayFormat>STK-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>To get the product code on product stock.</description>
    <formula>SVMXC__Product__r.ProductCode</formula>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing site record.</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record.</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>Product_Stock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__Quantity2__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Quantity2__c</fullName>
    <description>Quantity of product in the provided location.</description>
    <inlineHelpText>Quantity of product in the provided location.</inlineHelpText>
    <label>Qty</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__Product_Stock__c/fields/SVMXC__Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Status__c</fullName>
    <description>Current Status of Product-Stock.</description>
    <inlineHelpText>Current Status of Product-Stock.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/SVMXC__Service_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. In ServiceMax, service orders can be used to manage the entire service delivery process, from creating estimates and quotations, to requesting and receiving parts, to recording usage/consumption, to closure and analysis.</description>
    <label>Work Detail</label>
    <nameField>
        <displayFormat>WL-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <description>Stores the Batch number which will used in Integration operations.</description>
    <label>Batch Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/Consumed_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Consumed_Part_Number__c</fullName>
    <description>To Populate the Productcode of the associated Product Stock. 
Automatically Populated if Product Stock is associated to the Work Detail.</description>
    <formula>SVMX_PS_VS_Consumed_Product_Stock__r.SVMXC__Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumed Part Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Formula field to fetch product code of part</description>
    <formula>SVMXC__Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMX_PS_VS_Consumed_Stocked_Serial__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_VS_Consumed_Stocked_Serial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The field indicates reference to Stock Serial. This will be used to find the proper Stock Serial under the consumed product stock. Either this field or &quot;Consumed Serial Number&quot; need to be populated in case if product is Serialized in order to get data.</description>
    <inlineHelpText>The field indicates reference to Stock Serial. This will be used to find the proper Stock Serial under the consumed product stock. Either this field or &quot;Consumed Serial Number&quot; need to be populated in case if product is Serialized in order to get data.</inlineHelpText>
    <label>Consumed Stock Serial</label>
    <referenceTo>SVMXC__Product_Serial__c</referenceTo>
    <relationshipLabel>Work Details (Consumed Stock Serial)</relationshipLabel>
    <relationshipName>SVMX_PS_VS_Consumed_Stocked_Serial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Actual_Quantity2__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Actual_Quantity2__c</fullName>
    <description>Number of units consumed. This is context-sensitive based on line type.</description>
    <inlineHelpText>Number of units consumed. This is context-sensitive based on line type.</inlineHelpText>
    <label>Line Qty</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Consumed_From_Location__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Consumed_From_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location from which inventory was consumed. Link to an existing site record in ServiceMax</description>
    <inlineHelpText>Location from which inventory was consumed. Link to an existing site record in ServiceMax</inlineHelpText>
    <label>Consumed From Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>Service_Order_Line_Cons_Loc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the part used. Reference to an existing installed product record in ServiceMax</description>
    <label>IB Serial Number</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdjustInventory_WorkdetailHelper.cls
/*****************************************************************************************************************
 * Class Name: AdjustInventory_WorkdetailHelper
 * Description: Adjust the inventory for serialized, batch & non tracked products.
 * Author: Prashanth
 * 
 * Date: 06-Dec-2021
 * 
 * Notification Log:
 * -------------------------------------------------------------------------------------------------------------
 * Developer                  Date                              Description
 * -------------------------------------------------------------------------------------------------------------
 * Prashanth               06-12-2021        Adjust the inventory for serialized, batch & non tracked products.
 ******************************************************************************************************************/
public with sharing class AdjustInventory_WorkdetailHelper {
    //DCP-44981
    public static final String STRING_CONSUMED_PRODUCT_STOCK = 'Consumed';
    public static final String STRING_AVAILABLE_PRODUCT_STOCK = 'Available';

    /*
    *  @DESCRIPTION: DCP-44981 - Parts Consumption Reversal Process for Serialized Work Detail
    *  @RETURN:  void
    */
    public static void adjustSerializedOrNonTrackedInventory(Map < Id, SVMXC__Service_Order_Line__c > serializedWorkDetailIdToWorkDetailMap, String serializedOrNonTracked) {

        Map < String, Id > partNumberToConsumedLocationIdMap = new Map < String, Id > ();
        Map < String, SVMXC__Service_Order_Line__c > partNumberToWorkDetailMap = new Map < String, SVMXC__Service_Order_Line__c > ();
        Map < String, List < SVMXC__Product_Stock__c >> partNumberToListProductStocks = new Map < String, List < SVMXC__Product_Stock__c >> ();
        List < SVMXC__Product_Serial__c > listReparentedStockedSerialInternal = new List < SVMXC__Product_Serial__c > ();
        List < SVMXC__Product_Stock__c > listProductStockInternal = new List < SVMXC__Product_Stock__c > ();

        for (Id workDetailId: serializedWorkDetailIdToWorkDetailMap.keyset()) {
            if (String.isNotBlank(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).Consumed_Part_Number__c)) {
                partNumberToConsumedLocationIdMap.put(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).Consumed_Part_Number__c, serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMXC__Consumed_From_Location__c);
                partNumberToWorkDetailMap.put(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).Consumed_Part_Number__c, serializedWorkDetailIdToWorkDetailMap.get(workDetailId));
            }
        }

        //get available and consumed product stocks based on part number
        Map < Id, SVMXC__Product_Stock__c > productStockIdToProductStockMap = new Map < Id, SVMXC__Product_Stock__c > ([Select Id, SVMXC__Status__c,SVMXC__Location__c, Product_Code__c, SVMXC__Quantity2__c from SVMXC__Product_Stock__c Where Product_Code__c IN :partNumberToConsumedLocationIdMap.keyset() AND SVMXC__Location__c IN :partNumberToConsumedLocationIdMap.values()]);

        //part number with list of product stocks
        for (Id productStockId: productStockIdToProductStockMap.keyset()) {
            if (partNumberToListProductStocks!=NULL && !partNumberToListProductStocks.IsEmpty() && partNumberToListProductStocks.containskey(productStockIdToProductStockMap.get(productStockId).Product_Code__c)) {
                partNumberToListProductStocks.get(productStockIdToProductStockMap.get(productStockId).Product_Code__c).add(productStockIdToProductStockMap.get(productStockId));
            } else {
                partNumberToListProductStocks.put(productStockIdToProductStockMap.get(productStockId).Product_Code__c, new List < SVMXC__Product_Stock__c > ());
                partNumberToListProductStocks.get(productStockIdToProductStockMap.get(productStockId).Product_Code__c).add(productStockIdToProductStockMap.get(productStockId));
            }
        }
        populateProductStockMap(partNumberToListProductStocks, partNumberToWorkDetailMap, listReparentedStockedSerialInternal, listProductStockInternal, serializedOrNonTracked);
        //update product stock
        if (!listProductStockInternal.isEmpty()){
            PartsConsumptionReversal_WDHelper.listProductStockFinalUpdate.addAll(listProductStockInternal);
        }

        //reparent stocked serial update
        if ( !listReparentedStockedSerialInternal.isEmpty()){
            PartsConsumptionReversal_WDHelper.listStockedSerialFinalUpdate.addAll(listReparentedStockedSerialInternal);
        }   

    }
    /*
    *  Method:populateProductStockMap
    *  @DESCRIPTION: DCP-44981 - Parts Consumption Reversal Process for Serialized Work Detail
    *  @RETURN:  void
    */
    public static void populateProductStockMap(Map < String, List < SVMXC__Product_Stock__c >> partNumberToListProductStocks, Map < String, SVMXC__Service_Order_Line__c > partNumberToWorkDetailMap,List < SVMXC__Product_Serial__c > listReparentedStockedSerialInternal, List<SVMXC__Product_Stock__c> listProductStockInternal, String serializedOrNonTracked){
        for (string partNumber: partNumberToListProductStocks.keyset()) {

            for (SVMXC__Product_Stock__c productStock: partNumberToListProductStocks.get(partNumber)) {
                if (productStock.SVMXC__Status__c == STRING_CONSUMED_PRODUCT_STOCK) {
                    productStock.SVMXC__Quantity2__c -= partNumberToWorkDetailMap.get(partNumber).SVMXC__Actual_Quantity2__c;
                } else if (productStock.SVMXC__Status__c == STRING_AVAILABLE_PRODUCT_STOCK) {
                    productStock.SVMXC__Quantity2__c += partNumberToWorkDetailMap.get(partNumber).SVMXC__Actual_Quantity2__c;

                    if (serializedOrNonTracked == Workdetails.PRODUCT_TRACKING_SERIALIZED){
                        listReparentedStockedSerialInternal.add(new SVMXC__Product_Serial__c(Id = partNumberToWorkDetailMap.get(partNumber).SVMX_PS_VS_Consumed_Stocked_Serial__c, SVMXC__Product_Stock__c = productStock.id, SVMX_PS_VS_Linked_Installed_Product__c = partNumberToWorkDetailMap.get(partNumber).SVMXC__Serial_Number__c,SVMXC__Active__c = true));
                    }

                }
                listProductStockInternal.add(productStock);
            }
        }
    }

    /*
    *  @DESCRIPTION: DCP-44981 - Parts Consumption Reversal Process for Batch Work Detail
    *  @RETURN:  void
    */
    public static void adjustBatchInventory(Map < Id, SVMXC__Service_Order_Line__c > batchWorkDetailIdToWorkDetailMap) {

        Map < String, Id > partNumberToConsumedLocationIdMap = new Map < String, Id > ();
        Map < String, SVMXC__Service_Order_Line__c > partNumberToWorkDetailMap = new Map < String, SVMXC__Service_Order_Line__c > ();
        Map < String, List < SVMXC__Product_Stock__c >> partNumberToListProductStocks = new Map < String, List < SVMXC__Product_Stock__c >> ();
        List < SVMXC__Product_Serial__c > listStockSerialInternal = new List < SVMXC__Product_Serial__c > ();
        List < SVMXC__Product_Stock__c > listProductStockInternal = new List < SVMXC__Product_Stock__c > ();

        for (Id workDetailId: batchWorkDetailIdToWorkDetailMap.keyset()) {
            if (String.isNotBlank(batchWorkDetailIdToWorkDetailMap.get(workDetailId).Consumed_Part_Number__c)) {
                partNumberToConsumedLocationIdMap.put(batchWorkDetailIdToWorkDetailMap.get(workDetailId).Consumed_Part_Number__c, batchWorkDetailIdToWorkDetailMap.get(workDetailId).SVMXC__Consumed_From_Location__c);
                partNumberToWorkDetailMap.put(batchWorkDetailIdToWorkDetailMap.get(workDetailId).Consumed_Part_Number__c, batchWorkDetailIdToWorkDetailMap.get(workDetailId));
            }
        }

        //get available and consumed product stocks based on part number
        Map < Id, SVMXC__Product_Stock__c > productStockIdToProductStockMap = new Map < Id, SVMXC__Product_Stock__c > ([Select Id, SVMXC__Status__c, Product_Code__c, SVMXC__Quantity2__c, (Select Id, Quantity__c, Batch_Number__c, Product_Stock_Status__c from SVMXC__Product_Serial__r) from SVMXC__Product_Stock__c Where Product_Code__c IN: partNumberToConsumedLocationIdMap.keyset() AND SVMXC__Location__c IN: partNumberToConsumedLocationIdMap.values()]);

        //part number with list of product stocks
        for (Id productStockId: productStockIdToProductStockMap.keyset()) {
            if (partNumberToListProductStocks!=NULL && !partNumberToListProductStocks.IsEmpty() && partNumberToListProductStocks.containskey(productStockIdToProductStockMap.get(productStockId).Product_Code__c)) {
                partNumberToListProductStocks.get(productStockIdToProductStockMap.get(productStockId).Product_Code__c).add(productStockIdToProductStockMap.get(productStockId));
            } else {
                partNumberToListProductStocks.put(productStockIdToProductStockMap.get(productStockId).Product_Code__c, new List < SVMXC__Product_Stock__c > ());
                partNumberToListProductStocks.get(productStockIdToProductStockMap.get(productStockId).Product_Code__c).add(productStockIdToProductStockMap.get(productStockId));
            }
        }

        for (string partNumber: partNumberToListProductStocks.keyset()) {
            adjustBatchQuantity(partNumberToListProductStocks, partNumberToWorkDetailMap, listStockSerialInternal, listProductStockInternal,partNumber);
        }

        //update product stock
        if ( !listProductStockInternal.isEmpty()){
            PartsConsumptionReversal_WDHelper.listProductStockFinalUpdate.addAll(listProductStockInternal);
        }

        //reparent stocked serial update
        if ( !listStockSerialInternal.isEmpty()){
            PartsConsumptionReversal_WDHelper.listStockedSerialFinalUpdate.addAll(listStockSerialInternal);
        }     

    }
     
    
    /*
    * Method:adjustBatchQuantity
    *  @DESCRIPTION: DCP-44981 - Parts Consumption Reversal Process for Serialized Work Detail, update on IP
    *  @RETURN:  void
    */
    public static void adjustBatchQuantity(Map < String, List < SVMXC__Product_Stock__c >> partNumberToListProductStocks, Map < String, SVMXC__Service_Order_Line__c > partNumberToWorkDetailMap, List < SVMXC__Product_Serial__c > listStockSerialInternal, List < SVMXC__Product_Stock__c > listProductStockInternal, String partNumber){
        //adjust the quantity
        for (SVMXC__Product_Stock__c productStock: partNumberToListProductStocks.get(partNumber)) {
            if (productStock.SVMXC__Status__c == STRING_CONSUMED_PRODUCT_STOCK) {
                productStock.SVMXC__Quantity2__c -= partNumberToWorkDetailMap.get(partNumber).SVMXC__Actual_Quantity2__c;
            } else if (productStock.SVMXC__Status__c == STRING_AVAILABLE_PRODUCT_STOCK) {
                productStock.SVMXC__Quantity2__c += partNumberToWorkDetailMap.get(partNumber).SVMXC__Actual_Quantity2__c;
            }

            for (SVMXC__Product_Serial__c stockedSerial: productStock.SVMXC__Product_Serial__r) {

                if (stockedSerial.Product_Stock_Status__c == STRING_CONSUMED_PRODUCT_STOCK && stockedSerial.Batch_Number__c == partNumberToWorkDetailMap.get(partNumber).Batch_Number__c) {
                    stockedSerial.Quantity__c -= partNumberToWorkDetailMap.get(partNumber).SVMXC__Actual_Quantity2__c;
                } else if (stockedSerial.Product_Stock_Status__c == STRING_AVAILABLE_PRODUCT_STOCK && stockedSerial.Batch_Number__c == partNumberToWorkDetailMap.get(partNumber).Batch_Number__c) {
                    stockedSerial.Quantity__c += partNumberToWorkDetailMap.get(partNumber).SVMXC__Actual_Quantity2__c;
                }

                listStockSerialInternal.add(stockedSerial);
            }
            listProductStockInternal.add(productStock);

        }
        
    }

}