force-app/main/default/objects/Business_Hours_Setting__mdt/Business_Hours_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Setting to store Business Hours for the organization.</description>
    <label>Business Hours Setting</label>
    <pluralLabel>Business Hours Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Business_Hours_Setting__mdt/fields/EndHourOfTheDay__c.field-meta.xml
<CustomField>
    <fullName>EndHourOfTheDay__c</fullName>
    <description>Time entered from 0 - 24, which would be the end of the business day.</description>
    <label>End Hour of the Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Hours_Setting__mdt/fields/Rejection_Hour_For_SLA_Next_Day__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Hour_For_SLA_Next_Day__c</fullName>
    <description>Number of hours after which the auto rejection should be fired when SLA is next day.</description>
    <label>Rejection Hour For SLA Next Day</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Hours_Setting__mdt/fields/Rejection_Hour_For_SLA_Post_Next_Day__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Hour_For_SLA_Post_Next_Day__c</fullName>
    <description>Number of hours after which auto rejection should be fired if SLA is after next day.</description>
    <label>Rejection Hour For SLA Post Next Day</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Hours_Setting__mdt/fields/StartTimeOfTheDay__c.field-meta.xml
<CustomField>
    <fullName>StartTimeOfTheDay__c</fullName>
    <description>Time entered from 0 - 24, which would be the start of the business day.</description>
    <label>Start Hour of the Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestBusinessHoursSettingMetadataSelector.cls
/***************************************************************************************************************************************
* NAME         : TestBusinessHoursSettingMetadataSelector
* DESCRIPTION  : Test class businessHoursSettingMetadataSelector
* @AUTHOR      : Venkatesh Prabhu
* @DATE        : 2nd Dec 2024
* 
* MODIFICATION LOG:  
* --------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
 * Venkatesh Prabhu      2nd Dec 2024       CMCM-12168 Too Many SOQL Queries
****************************************************************************************************************************************/
@isTest
public class TestBusinessHoursSettingMetadataSelector {


    @IsTest
    private static void testGetBusinessHoursSettingMetadata() {
        Business_Hours_Setting__mdt expectedBusinessHoursSetting = [SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, SystemModstamp, EndHourOfTheDay__c, Rejection_Hour_For_SLA_Next_Day__c, Rejection_Hour_For_SLA_Post_Next_Day__c, StartTimeOfTheDay__c FROM Business_Hours_Setting__mdt LIMIT 1];

        Business_Hours_Setting__mdt actualBusinessHoursSetting = new BusinessHoursSettingMetadataSelector().selectDefaultBusinessHourSetting(expectedBusinessHoursSetting.DeveloperName)[0];

        System.assertEquals(expectedBusinessHoursSetting.DeveloperName, actualBusinessHoursSetting.DeveloperName, 'The returned Business_Hours_Setting__mdt record should match the expected record.');
    }

}