force-app/main/default/objects/Partner_Portal_Content__c/Partner_Portal_Content__c.object-meta.xml
<CustomObject>
    <description>Stores the content for the portal banner based on the record data created for a given region</description>
    <label>Partner Portal Content</label>
    <nameField>
        <displayFormat>PPC-{0}</displayFormat>
        <label>Partner Content Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Portal Contents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox is ticked if Slide is being used.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Button_Text__c.field-meta.xml
<CustomField>
    <fullName>Button_Text__c</fullName>
    <description>Text displayed on the Button.</description>
    <label>Button Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Button_URL__c.field-meta.xml
<CustomField>
    <fullName>Button_URL__c</fullName>
    <description>Navigates to this URL when the button is clicked.</description>
    <label>Button URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Button_Visible__c.field-meta.xml
<CustomField>
    <fullName>Button_Visible__c</fullName>
    <description>Flag to determine the visibility of button on partner portal</description>
    <defaultValue>false</defaultValue>
    <label>Button Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Home_Page_Text__c.field-meta.xml
<CustomField>
    <fullName>Home_Page_Text__c</fullName>
    <description>Field to capture home page text</description>
    <label>Home Page Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <description>This field holds the Url of Image</description>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/ImageCSS__c.field-meta.xml
<CustomField>
    <fullName>ImageCSS__c</fullName>
    <description>For storing the Image url CSS.</description>
    <label>ImageCSS</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Quick_Links_Label__c.field-meta.xml
<CustomField>
    <fullName>Quick_Links_Label__c</fullName>
    <description>This field holds the quick link label on partner portal</description>
    <label>Quick Links Label</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Quick_Links_URL__c.field-meta.xml
<CustomField>
    <fullName>Quick_Links_URL__c</fullName>
    <description>URL for the Quick Link to be used on Illumina Partner Portal.</description>
    <label>Quick Links URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Name of the region to which a particular Slide will be displayed.</description>
    <label>Region</label>
`   <trackHistory>true</trackHistory>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Slide_Name__c.field-meta.xml
<CustomField>
    <fullName>Slide_Name__c</fullName>
    <description>Holds Slide name on partner portal</description>
    <label>Slide Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Slide_Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Slide_Subtitle__c</fullName>
    <description>Text below the title.</description>
    <label>Slide Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Slide_Title__c.field-meta.xml
<CustomField>
    <fullName>Slide_Title__c</fullName>
    <description>This field is to capture the title on partner portal</description>
    <label>Slide Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>This field is used to sort the order of buttons containing URL&apos;s in help page of ICPP</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Terms_of_Use_Version__c.field-meta.xml
<CustomField>
    <fullName>Terms_of_Use_Version__c</fullName>
    <description>This field is used to hold the version terms</description>
    <label>Terms of Use Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/fields/Video_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_URL__c</fullName>
    <description>Stores the URL of the Video to be shown on Partner Portal Home Page</description>
    <label>Video URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Content__c/recordTypes/help.recordType-meta.xml
<RecordType>
    <fullName>help</fullName>
    <active>true</active>
    <description>Used to manage the buttons displayed in Help page.</description>
    <label>help</label>
</RecordType>

force-app/main/default/objects/Partner_Portal_Content__c/recordTypes/Slides.recordType-meta.xml
<RecordType>
    <fullName>Slides</fullName>
    <active>true</active>
    <label>Slides</label>
</RecordType>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMR</fullName>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>APJ</fullName>
        <isActive>false</isActive>
        <label>APJ</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PartnerPortalContentSelectorHelp.cls
/**
*    @author Prakhar Kumar
*    @date   2019-08-14
*    @description    DCP-28546: Partner PortalContent Selector
*    ------------------------------------------------------------- 
* Modification Log:
* ---------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* ---------------------------------------------------------------------------------------------------
* Prakhar Kumar          22-08-2019               DCP-28546            Added RecordType.Name = Slides
* 
*                    
*/
public with sharing class PartnerPortalContentSelectorHelp extends ilib_SObjectSelector {

    /*
     * Constructor
     */
public PartnerPortalContentSelectorHelp()
{
    super(false, false, false, false);
}


/*
* @description: This method returns the objectAPIName of an SObjectType
* @return: Schema.SObjectType 
*/
public Schema.SObjectType getSObjectType()
{
    return Partner_Portal_Content__c.sObjectType;
}
 /*
* @author Prakhar Kumar
* @date   14-08-2018
* @description  Retrieve list of urls for quicklinks
* @return sObjectFieldList list of Schema.SObjectField
*/
public List<Schema.SObjectField> getSObjectFieldList()
{
    return new List<Schema.SObjectField> {
        Partner_Portal_Content__c.Active__c,
        Partner_Portal_Content__c.Button_Text__c,
        Partner_Portal_Content__c.Button_URL__c,
        Partner_Portal_Content__c.Home_Page_Text__c,
        Partner_Portal_Content__c.Image_URL__c,
        Partner_Portal_Content__c.Quick_Links_URL__c,
        Partner_Portal_Content__c.Region__c,
        Partner_Portal_Content__c.Slide_Name__c,
        Partner_Portal_Content__c.Slide_Subtitle__c,
        Partner_Portal_Content__c.Slide_Title__c,
        Partner_Portal_Content__c.Terms_of_Use_Version__c,
        Partner_Portal_Content__c.Video_URL__c,
        Partner_Portal_Content__c.ImageCSS__c,
        Partner_Portal_Content__c.Quick_Links_Label__c,
        Partner_Portal_Content__c.Button_Visible__c,
        Partner_Portal_Content__c.Sort_Order__c 
    };
}




 /**
*  @author Prakhar Kumar
*  @description Override Default name Ordering
*  
*  @return String for Ordering  
**/
private Boolean removeDefaultOrderBy=false;

    /*
    * @description: This method returns sorting field and direction based on when the default ordering is removed
    * @return: String
    */	
public override String getOrderBy() {
    if(removeDefaultOrderBy){
        return 'Sort_Order__c ASC';
    }else{
        return super.getOrderBy();
    }
    
}   



/*
* @author Vinay S Reddy
* @description Fetch hyperlinks of the Help from Partner portal Content SObject
*
*/
 
public List<Partner_Portal_Content__c> selectActiveHelpLinks() 
{   
    removeDefaultOrderBy=TRUE;     
    return (List<Partner_Portal_Content__c>) Database.query(
    newQueryFactory()
    .setCondition('Region__c = \'\' AND Active__c = true AND recordtype.Name=\'help\' AND Button_Visible__c=True AND Button_Text__c !=\'\' AND Button_URL__c != \'\' AND Sort_Order__c !=null')
    .toSOQL());
    
} 


}