force-app/main/default/objects/Apttus__QueryTemplate__c/Apttus__QueryTemplate__c.object-meta.xml
<CustomObject>
    <description>Query Template for bulding soql queries and filters</description>
    <label>Query Template</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Query Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Query Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__QueryTemplate__c/fields/Apttus__Sequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Sequence__c</fullName>
    <description>Template sequence</description>
    <inlineHelpText>Template sequence</inlineHelpText>
    <label>Sequence</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateFilter__c/Apttus__QueryTemplateFilter__c.object-meta.xml
<CustomObject>
    <description>Filter expression used in a query</description>
    <label>Query Template Filter</label>
    <nameField>
        <displayFormat>QTF-{0000000}</displayFormat>
        <label>Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Query Template Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__QueryTemplateFilter__c/fields/Apttus__CompOper__c.field-meta.xml
<CustomField>
    <fullName>Apttus__CompOper__c</fullName>
    <description>Comparison operator for a field expression in a query</description>
    <label>Comparison Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>equal to</fullName>
                <default>true</default>
                <label>equal to</label>
            </value>
            <value>
                <fullName>not equal to</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less than or equal to</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater than or equal to</fullName>
            </value>
            <value>
                <fullName>in</fullName>
            </value>
            <value>
                <fullName>not in</fullName>
            </value>
            <value>
                <fullName>like</fullName>
            </value>
            <value>
                <fullName>not like</fullName>
            </value>
            <value>
                <fullName>includes</fullName>
            </value>
            <value>
                <fullName>excludes</fullName>
            </value>
            <value>
                <fullName>starts with</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>does not contain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateFilter__c/fields/Apttus__Field__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Field__c</fullName>
    <description>The name of a field in the specified object.</description>
    <inlineHelpText>The name of a field in the specified object.</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateFilter__c/fields/Apttus__QueryTemplate__c.field-meta.xml
<CustomField>
    <fullName>Apttus__QueryTemplate__c</fullName>
    <description>The associated query template</description>
    <inlineHelpText>The associated query template</inlineHelpText>
    <label>Query Template</label>
    <referenceTo>Apttus__QueryTemplate__c</referenceTo>
    <relationshipLabel>Filters</relationshipLabel>
    <relationshipName>QueryTemplateFilters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateFilter__c/fields/Apttus__Sequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Sequence__c</fullName>
    <description>Filter sequence</description>
    <inlineHelpText>Filter sequence</inlineHelpText>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateFilter__c/fields/Apttus__Value__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Value__c</fullName>
    <description>A value used to compare with the value in field in a query</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApttusQueryTemplateFilterSelector.cls
/**
*    @author Akshay Mohan
*    @date   2021-04-27
*    @description    DCP-38809: Auto generate quote
*    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------
*         Developer               Date                Description
*         Akshay Mohan            2021-05-06          Initial Version
*    ---------------------------------------------------------------------------------------------------------------------------
**/
public with sharing class ApttusQueryTemplateFilterSelector extends ilib_SObjectSelector{
    /**
    *  @author Akshay Mohan
    *  @description  
    *  @return SObjectType The Schema.SObjectType of the object
    **/
   public Schema.SObjectType getSObjectType()
   {
        return Apttus__QueryTemplateFilter__c.sObjectType;
   }

   /**
     *  @author  Akshay Mohan 
     *  @description Retrieve list of fields for sObject 
     *  @return sObjectFieldList list of Schema.SObjectField
     **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {
       return new List<Schema.SObjectField> {
        Apttus__QueryTemplateFilter__c.id,
        Apttus__QueryTemplateFilter__c.Apttus__Sequence__c,
        Apttus__QueryTemplateFilter__c.Apttus__CompOper__c,
        Apttus__QueryTemplateFilter__c.Apttus__Field__c,
        Apttus__QueryTemplateFilter__c.Apttus__QueryTemplate__c,
        Apttus__QueryTemplateFilter__c.Apttus__Value__c
       };
    }

    /**
     *  @author Akshay Mohan
     *  @description fetch records by query template ids
     *  @param idSet set of query template ids
     *  @return list of Apttus__QueryTemplateFilter__c records
     **/
    public List<Apttus__QueryTemplateFilter__c> selectByQueryTemplateIds(Set<Id> setQueryTemplateIds){
        return (List<Apttus__QueryTemplateFilter__c>) 
            Database.query(newQueryFactory()
                .setCondition('Apttus__QueryTemplate__c IN :setQueryTemplateIds')
                .toSOQL()
            );
    }
}