force-app/main/default/objects/Apttus__QueryTemplate__c/Apttus__QueryTemplate__c.object-meta.xml
<CustomObject>
    <description>Query Template for bulding soql queries and filters</description>
    <label>Query Template</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Query Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Query Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__QueryTemplate__c/fields/Apttus__Active__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Template active indicator. Inactive templates are ignored by the template selection process</description>
    <inlineHelpText>Indicates whether the template is active. Inactive templates are ignored.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplate__c/fields/Apttus__Sequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Sequence__c</fullName>
    <description>Template sequence</description>
    <inlineHelpText>Template sequence</inlineHelpText>
    <label>Sequence</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplate__c/fields/Apttus__SObjectLabel__c.field-meta.xml
<CustomField>
    <fullName>Apttus__SObjectLabel__c</fullName>
    <description>Specifies the object to query</description>
    <inlineHelpText>The object to query</inlineHelpText>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Template</fullName>
                <default>true</default>
                <label>Agreement Template</label>
            </value>
            <value>
                <fullName>Quote/Proposal Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplate__c/fields/Apttus__SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Apttus__SObjectType__c</fullName>
    <description>Specifies the type of the object to query</description>
    <inlineHelpText>The object type to query</inlineHelpText>
    <label>SObject Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Apttus__SObjectLabel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Apttus__APTS_Template__c</fullName>
                <default>true</default>
                <label>Apttus__APTS_Template__c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateQualifier__c/Apttus__QueryTemplateQualifier__c.object-meta.xml
<CustomObject>
    <description>Filter used to select a query template</description>
    <label>Query Template Qualifier</label>
    <nameField>
        <displayFormat>QTQ-{0000000}</displayFormat>
        <label>Qualifier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Query Template Qualifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__QueryTemplateQualifier__c/fields/Apttus__QueryTemplate__c.field-meta.xml
<CustomField>
    <fullName>Apttus__QueryTemplate__c</fullName>
    <description>The associated query template</description>
    <inlineHelpText>The associated query template</inlineHelpText>
    <label>Query Template</label>
    <referenceTo>Apttus__QueryTemplate__c</referenceTo>
    <relationshipLabel>Qualifiers</relationshipLabel>
    <relationshipName>QueryTemplateQualifiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateQualifier__c/fields/Apttus__Sequence__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Sequence__c</fullName>
    <description>Qualifier sequence</description>
    <inlineHelpText>Qualifier sequence</inlineHelpText>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateQualifier__c/fields/Apttus__SObjectLabel__c.field-meta.xml
<CustomField>
    <fullName>Apttus__SObjectLabel__c</fullName>
    <description>Specifies the object to query</description>
    <inlineHelpText>The object to query</inlineHelpText>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement</fullName>
                <default>true</default>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__QueryTemplateQualifier__c/fields/Apttus__SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Apttus__SObjectType__c</fullName>
    <description>Specifies the type of the object to query.</description>
    <inlineHelpText>The object type to query</inlineHelpText>
    <label>SObject Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Apttus__SObjectLabel__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Apttus__APTS_Agreement__c</fullName>
                <default>true</default>
                <label>Apttus__APTS_Agreement__c</label>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>Apttus_Proposal__Proposal__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApttusQueryTemplateQualifierSelector.cls
/**
*    @author Akshay Mohan
*    @date   2021-04-27
*    @description    DCP-38809: Auto generate quote
*    Modification Log:
*    ---------------------------------------------------------------------------------------------------------------------------
*         Developer               Date                Description
*         Akshay Mohan            2021-05-06          Initial Version
*    ---------------------------------------------------------------------------------------------------------------------------
**/
public with sharing class ApttusQueryTemplateQualifierSelector extends ilib_SObjectSelector{

    public static final String QUOTE_OBJECT='Quote';
    public static final String TERRITORY_REGION_FIELD='Territory_Region__c';
    public static final String COMPARATOR_EQUALS='equal to';
    public static final String COMPARATOR_IN='in';
    
    /**
    *  @author Akshay Mohan
    *  @description  
    *  @return SObjectType The Schema.SObjectType of the object
    **/
   public Schema.SObjectType getSObjectType()
   {
        return Apttus__QueryTemplateQualifier__c.sObjectType;
   }

   /**
     *  @author  Akshay Mohan 
     *  @description Retrieve list of fields for sObject 
     *  @return sObjectFieldList list of Schema.SObjectField
     **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {
       return new List<Schema.SObjectField> {
        Apttus__QueryTemplateQualifier__c.id,
        Apttus__QueryTemplateQualifier__c.Apttus__CompOper__c,
        Apttus__QueryTemplateQualifier__c.Apttus__Value__c,
        Apttus__QueryTemplateQualifier__c.Apttus__Field__c,
        Apttus__QueryTemplateQualifier__c.Apttus__QueryTemplate__c,
        Apttus__QueryTemplateQualifier__c.Apttus__Sequence__c,
        Apttus__QueryTemplateQualifier__c.Apttus__SObjectType__c
       };
    }

    /**
     *  @author Akshay Mohan
     *  @description add ordering
     *  @param 
     *  @return String
     **/
    public override String getOrderBy(){
        return 'Apttus__QueryTemplate__r.Apttus__Sequence__c ASC, Apttus__QueryTemplate__c ASC';
     }

    /**
     *  @author Akshay Mohan
     *  @description fetch records by query template ids
     *  @param idSet set of query template ids
     *  @return list of Apttus__QueryTemplateQualifier__c records
     **/
    public List<Apttus__QueryTemplateQualifier__c> selectByQueryTemplateIds(Set<Id> setQueryTemplateIds){
        return (List<Apttus__QueryTemplateQualifier__c>) 
            Database.query(newQueryFactory()
                            .setCondition('Apttus__QueryTemplate__c IN :setQueryTemplateIds')
                            .toSOQL());
    }

    /**
     *  @author Akshay Mohan
     *  @description fetch records for quote by Region
     *  @param idSet set of proposal ids
     *  @return list of Apttus__QueryTemplateQualifier__c records
     **/
    public List<Apttus__QueryTemplateQualifier__c> selectQuoteTemplatesByTerritory(String strRegion){
        String strRegionLike='%'+strRegion+'%';
        return (List<Apttus__QueryTemplateQualifier__c>) 
            Database.query(newQueryFactory()
                .setCondition('Apttus__SObjectLabel__c = :QUOTE_OBJECT'
                                +' AND Apttus__QueryTemplate__r.Apttus__Active__c=true'
                                +' AND Apttus__Field__c=:TERRITORY_REGION_FIELD'
                                +' AND ((Apttus__CompOper__c=:COMPARATOR_EQUALS AND Apttus__Value__c=:strRegion)'
                                        +' OR (Apttus__CompOper__c=:COMPARATOR_IN AND Apttus__Value__c LIKE :strRegionLike))')
                .toSOQL());
    }
}