force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product in which specialization would be required to service the work order. Calculated from installed product by OptiMax pre-calculation engine</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/SVMXC__Service_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. In ServiceMax, service orders can be used to manage the entire service delivery process, from creating estimates and quotations, to requesting and receiving parts, to recording usage/consumption, to closure and analysis.</description>
    <label>Work Detail</label>
    <nameField>
        <displayFormat>WL-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMX_PS_VS_Return_Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_VS_Return_Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installed Product which is removed as a part of Part Out Process</description>
    <inlineHelpText>Installed Product which is removed as a part of Part Out Process</inlineHelpText>
    <label>Return Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Work Details (Return Installed Product)</relationshipLabel>
    <relationshipName>SVMX_PS_VS_Return_Installed_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMX_PS_VS_Return_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_VS_Return_Serial_Number__c</fullName>
    <description>This field needs to be populated in case if the &quot;Return Part&quot; is &quot;Serialized&quot;. Using info from &quot;Return Part&quot; and this Serial Number, Installed Product will be found which will be then used for Part Out Process</description>
    <inlineHelpText>This field needs to be populated in case if the &quot;Return Part&quot; is &quot;Serialized&quot;. Using info from &quot;Return Part&quot; and this Serial Number, Installed Product will be found which will be then used for Part Out Process</inlineHelpText>
    <label>Return Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Line_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Line_Status__c</fullName>
    <description>Service Order Line Status.</description>
    <inlineHelpText>Service Order Line Status.</inlineHelpText>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reversal Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting WO Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Line_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Line_Type__c</fullName>
    <description>Indicates the type of usage: Parts, Labor or Expenses</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Expenses</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Tools</fullName>
            </value>
            <value>
                <fullName>Material Consumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the product estimated, requested or used. Is a lookup to an existing salesforce product record</description>
    <inlineHelpText>Name of the product estimated, requested or used. Is a lookup to an existing salesforce product record</inlineHelpText>
    <label>Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Service_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Order__c</fullName>
    <description>Service order number. Is a lookup to an existing service order in ServiceMax</description>
    <inlineHelpText>Service order number. Is a lookup to an existing service order in ServiceMax</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckWDsInFRUs_WorkdetailHelper.cls
/*****************************************************************************************************************
 * Class Name: CheckWDsInFRUs_WorkdetailHelper
 * Description: Helper class for checking if the work details are selected in FRUs.
 * 
 * Author: Prashanth
 * 
 * Date: 07-Dec-2021
 * 
 * Notification Log:
 * -------------------------------------------------------------------------------------------------------------
 * Developer                  Date                              Description
 * -------------------------------------------------------------------------------------------------------------
 * Prashanth                  07-12-2021                       Helper class for checking if the work details are selected in FRUs
 ******************************************************************************************************************/
public with sharing class CheckWDsInFRUs_WorkdetailHelper {
    public static set < String > setTypeCheck = new set < String > ();
    public static Set < Id > setCombinedWorkOrderIds = new Set < Id > ();
    public static List < SVMXC__Service_Order_Line__c > lstCombineWOLForFRUCheck = new List < SVMXC__Service_Order_Line__c > ();
    public static Set < Id > setCombinedProductsIdsSelected = new Set < Id > ();
    public static set < Id > setToolsWorkOrderIds = new set < id > (); //Set of work orders associated with work details created for tools
    public static Set < Id > setProductsIdsSelected = new Set < Id > (); //Set of product ids which have been selected in the work detail record.
    public static set < Id > setMaterialsConsumedWorkOrderIds = new set < id > (); //Set of work orders associated with work details created for materials consumed
    public static List < SVMXC__Service_Order_Line__c > lstWOLForCompatibleToolCheck = new List < SVMXC__Service_Order_Line__c > (); //List of work details created for tools
    public static List < SVMXC__Service_Order_Line__c > lstWOLForCompatiblePartCheck = new List < SVMXC__Service_Order_Line__c > (); //List of work details created for tools
    public static List < SVMXC__Service_Order_Line__c > lstWOLForCompatibleMaterialsConsumedCheck = new List < SVMXC__Service_Order_Line__c > (); //List of work details created for materials consumed
    public static set < Id > setPartsWorkOrderIds = new set < id > (); //Set of work orders associated with work details created for parts
    public static final String STRING_WORK_DETAIL_LINE_TYPE_IS_TOOLS = 'Tool';
    /*
    *  method: checkIfSelectedInFRU
    *  @author - Prashanth
    *  @Description : check the work details if they are selected in FRU.
    * 
    */
    public static void checkIfSelectedInFRU(Map<Id, SObject> oldRecords, List<sObject> records){
        for(SVMXC__Service_Order_Line__c objWorkDetail: (List < SVMXC__Service_Order_Line__c > ) records){
            SVMXC__Service_Order_Line__c objOldWorkOrderLine = (SVMXC__Service_Order_Line__c)(oldRecords.get(objWorkDetail.Id));
            getTools(objWorkDetail, objOldWorkOrderLine);
            getMaterialsConsumed(objWorkDetail, objOldWorkOrderLine);

            // Check if the Parts selected is in FRU list
            if (objWorkDetail.SVMXC__Line_Type__c == Workdetails.STRING_WORK_DETAIL_LINE_TYPE_IS_PARTS &&
                objWorkDetail.RecordTypeId == BeforeUpdate_WorkdetailHelper.idWorkDetailUsageRecordTypeId &&
                objWorkDetail.SVMXC__Service_Order__c != null && objWorkDetail.SVMXC__Product__c != null &&
                objWorkDetail.SVMXC__Product__c != objOldWorkOrderLine.SVMXC__Product__c &&
                objWorkDetail.SVMXC__Line_Status__c != Workdetails.STRING_WORK_DETAIL_LINE_STATUS_CANCELED) {
                setPartsWorkOrderIds.add(objWorkDetail.SVMXC__Service_Order__c);
                setProductsIdsSelected.add(objWorkDetail.SVMXC__Product__c);
                setProductsIdsSelected.add(objOldWorkOrderLine.SVMXC__Product__c);

                //DCP-37747 - Bypass canceled WD's
                if (objWorkDetail.SVMXC__Line_Status__c != Workdetails.STRING_WORK_DETAIL_LINE_STATUS_CANCELED){
                    lstWOLForCompatiblePartCheck.add(objWorkDetail);
                }

            }
            if (!String.IsBlank(objWorkDetail.SVMX_PS_VS_Return_Installed_Product__c) && !Workdetails.mapIdToIP.IsEmpty() && Workdetails.mapIdToIP.containsKey(objWorkDetail.SVMX_PS_VS_Return_Installed_Product__c)) {
                objWorkDetail.SVMX_PS_VS_Return_Serial_Number__c = Workdetails.mapIdToIP.get(objWorkDetail.SVMX_PS_VS_Return_Installed_Product__c).SVMXC__Serial_Lot_Number__c;
    
            }
        }  
        //To check the Product is listed in the FRU list of Product of Work Order
        if (!setToolsWorkOrderIds.isEmpty() && !lstWOLForCompatibleToolCheck.isEmpty() && !setProductsIdsSelected.isEmpty()) {
            //DCP-33873(populate lst/Set for FRU Check)
            setCombinedWorkOrderIds.addAll(setToolsWorkOrderIds);
            lstCombineWOLForFRUCheck.addAll(lstWOLForCompatibleToolCheck);
            setCombinedProductsIdsSelected.addAll(setProductsIdsSelected);
            setTypeCheck.add('Tool');
        }
        processMaterialsConsumed();
        checkProductinRFU(oldRecords);
        
    }
    /*
    *  method: getTools
    *  @author - Prashanth
    *  @Description : check the work details if they are selected in FRU.
    * 
    */
    public static void getTools(SVMXC__Service_Order_Line__c objWorkDetail,SVMXC__Service_Order_Line__c objOldWorkOrderLine){
        // Check if the Tools selected is in FRU list
        if (objWorkDetail.SVMXC__Line_Type__c == STRING_WORK_DETAIL_LINE_TYPE_IS_TOOLS &&
            objWorkDetail.RecordTypeId == BeforeUpdate_WorkdetailHelper.idWorkDetailUsageRecordTypeId &&
            objWorkDetail.SVMXC__Service_Order__c != null && objWorkDetail.SVMXC__Product__c != null &&
            objWorkDetail.SVMXC__Product__c != objOldWorkOrderLine.SVMXC__Product__c &&
            objWorkDetail.SVMXC__Line_Status__c != Workdetails.STRING_WORK_DETAIL_LINE_STATUS_CANCELED) {
            setToolsWorkOrderIds.add(objWorkDetail.SVMXC__Service_Order__c);
            setProductsIdsSelected.add(objWorkDetail.SVMXC__Product__c);
            setProductsIdsSelected.add(objOldWorkOrderLine.SVMXC__Product__c);

            //DCP-37747 - Bypass canceled WD's
            if (objWorkDetail.SVMXC__Line_Status__c != Workdetails.STRING_WORK_DETAIL_LINE_STATUS_CANCELED){
                lstWOLForCompatibleToolCheck.add(objWorkDetail);
            }

        }
    }
    /*
    *  method: getMaterialsConsumed
    *  @author - Prashanth
    *  @Description : check the work details if they are selected in FRU.
    * 
    */
    public static void getMaterialsConsumed(SVMXC__Service_Order_Line__c objWorkDetail,SVMXC__Service_Order_Line__c objOldWorkOrderLine){
        // Check if the Materials Consumed selected is in FRU list
        if (objWorkDetail.SVMXC__Line_Type__c == Workdetails.STRING_WORK_DETAIL_LINE_TYPE_IS_MATERIALSCONSUMED &&
            objWorkDetail.RecordTypeId == BeforeUpdate_WorkdetailHelper.idWorkDetailUsageRecordTypeId &&
            objWorkDetail.SVMXC__Service_Order__c != null && objWorkDetail.SVMXC__Product__c != null &&
            objWorkDetail.SVMXC__Product__c != objOldWorkOrderLine.SVMXC__Product__c &&
            objWorkDetail.SVMXC__Line_Status__c != Workdetails.STRING_WORK_DETAIL_LINE_STATUS_CANCELED) {
            setMaterialsConsumedWorkOrderIds.add(objWorkDetail.SVMXC__Service_Order__c);
            setProductsIdsSelected.add(objWorkDetail.SVMXC__Product__c);
            setProductsIdsSelected.add(objOldWorkOrderLine.SVMXC__Product__c);

            //DCP-37747 - Bypass canceled WD's
            if (objWorkDetail.SVMXC__Line_Status__c != Workdetails.STRING_WORK_DETAIL_LINE_STATUS_CANCELED){
                lstWOLForCompatibleMaterialsConsumedCheck.add(objWorkDetail);
            }

        }
    }
    /*
    *  method: processMaterialsConsumed
    *  @author - Prashanth
    *  @Description : process materials consumed
    * 
    */
    public static void processMaterialsConsumed(){
        
        //To check the Product is listed in the FRU list of Product of Work Order
        if (!setMaterialsConsumedWorkOrderIds.isEmpty()) {
            set < id > setSpareProductIds = new set < id > ();
            List < Product2 > lstProduct = new List<Product2>();
            if (setProductsIdsSelected.size() > 0) {
                lstProduct = new ProductsSelector().selectProductsWithServiceProductType(setProductsIdsSelected, 'spare');
            }
            If(lstProduct != null && !lstProduct.isEmpty()) {
                For(Product2 objProduct: lstProduct) {
                    setSpareProductIds.add(objProduct.id);
                }
            }
            if (!setSpareProductIds.isEmpty() && !lstWOLForCompatibleMaterialsConsumedCheck.isEmpty()) {
                //DCP-33873(populate lst/Set for FRU Check)
                setCombinedWorkOrderIds.addAll(setMaterialsConsumedWorkOrderIds);
                lstCombineWOLForFRUCheck.addAll(lstWOLForCompatibleMaterialsConsumedCheck);
                setCombinedProductsIdsSelected.addAll(setSpareProductIds);
                setTypeCheck.add('Part');
            }
        }

        //To check the Product is listed in the FRU list of Product of Work Order
        if (!setPartsWorkOrderIds.isEmpty() && !lstWOLForCompatiblePartCheck.isEmpty() && !setProductsIdsSelected.isEmpty()) {
            //DCP-33873(populate lst/Set for FRU Check)
            setCombinedWorkOrderIds.addAll(setPartsWorkOrderIds);
            lstCombineWOLForFRUCheck.addAll(lstWOLForCompatiblePartCheck);
            setCombinedProductsIdsSelected.addAll(setProductsIdsSelected);
            setTypeCheck.add('Part');
        }
    }
     /*
    *  method: checkProductinRFU
    *  @author - Prashanth
    *  @Description : process materials consumed
    * 
    */
    public static void checkProductinRFU(Map<Id, sObject> oldRecords){
        //DCP-33873(call method for FRU Check)
        if (!setCombinedWorkOrderIds.isEmpty() && !lstCombineWOLForFRUCheck.isEmpty() && !setCombinedProductsIdsSelected.isEmpty()) {
            ProcessWDBeforeInsert_WorkDetailHelper.checkProductinFRUList(setCombinedWorkOrderIds, lstCombineWOLForFRUCheck, oldRecords, setCombinedProductsIdsSelected, 'Part', setTypeCheck);

        }
    }
}