force-app/main/default/objects/Apttus_Config2__OrderLineItem__c/Apttus_Config2__OrderLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with an order</description>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__OrderLineItem__c/fields/Apttus_Config2__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected product or service</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__OrderLineItem__c/fields/Custom_License_Flag__c.field-meta.xml
<CustomField>
    <fullName>Custom_License_Flag__c</fullName>
    <description>Field to store custom license flag</description>
    <defaultValue>false</defaultValue>
    <label>Custom License Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__OrderLineItem__c/fields/Dragen_Connectivity__c.field-meta.xml
<CustomField>
    <fullName>Dragen_Connectivity__c</fullName>
    <description>Field to store dragen connectivity</description>
    <label>Dragen Connectivity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__OrderLineItem__c/fields/Renewal_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Subscription__c</fullName>
    <description>Field to store renewal subscription</description>
    <formula>Apttus_QPConfig__ProposalLineItemId__r.Renewal_Subscription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/Apttus_Proposal__Proposal_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item associated with a quote/proposal</description>
    <label>Proposal Line Item</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Custom_License_Flag__c.field-meta.xml
<CustomField>
    <fullName>Custom_License_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Custom License Flag value</description>
    <label>Custom License Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Informatics_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>Informatics_SKU_Type__c</fullName>
    <description>Stores the Informatics SKU type for the product on line item</description>
    <formula>Apttus_Proposal__Product__r.Informatics_SKU_Type__c</formula>
    <label>Informatics SKU Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Is_Dragen__c.field-meta.xml
<CustomField>
    <fullName>Is_Dragen__c</fullName>
    <description>Indicates whether current material number is of Dragen type</description>
    <formula>Apttus_Proposal__Product__r.Informatics_Family__c =  $CustomMetadata.Code_Parameter__mdt.Informatics_Dragen_Family.PickListValue__c</formula>
    <label>Is Dragen?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Is_iCredit__c.field-meta.xml
<CustomField>
    <fullName>Is_iCredit__c</fullName>
    <description>Indicates whether current material number is of iCredit type</description>
    <formula>CONTAINS( Apttus_Proposal__Product__r.Informatics_SKU_Type__c, $CustomMetadata.Code_Parameter__mdt.Informatics_iCredit_Types.PickListValue__c  )</formula>
    <label>Is iCredit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Stores the Informatics family of the product in the line item</description>
    <formula>Apttus_Proposal__Product__r.Informatics_Family__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Product_Tier__c.field-meta.xml
<CustomField>
    <fullName>Product_Tier__c</fullName>
    <description>Stores the subscription tier value for the given product on line item</description>
    <formula>Apttus_Proposal__Product__r.Subscription_Tier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Stores the Informatics SKU type value for the given product on line item</description>
    <formula>Apttus_Proposal__Product__r.Informatics_SKU_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal_Line_Item__c/fields/Renewal_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Subscription__c</fullName>
    <description>ERP_Line_Number_Id__c  will only be populated for line items selected from asset lines.</description>
    <formula>AND(NOT(ISBLANK( ERP_Line_Number_Id__c)),
        NOT(CONTAINS($CustomMetadata.Product_Code_to_Subscription_Map__mdt.MicroArray_Analysis.Product_Code__c, Apttus_Proposal__Product__r.ProductCode)), 
        NOT(CONTAINS($CustomMetadata.Product_Code_to_Subscription_Map__mdt.MicroArray_Analysis_and_Report.Product_Code__c, Apttus_Proposal__Product__r.ProductCode)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Code_Parameter__mdt/Code_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>Values used by Apex or Lightning code</description>
    <label>Code Parameter</label>
    <pluralLabel>Code Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Code_Parameter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Usually will be name/value pairs. Each pair on a line and separated by a colon</description>
    <inlineHelpText>Usually will be name/value pairs. Each pair on a line and separated by a colon</inlineHelpText>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/Informatics_Product__mdt.object-meta.xml
<CustomObject>
    <description>Informatics Products</description>
    <label>Informatics Product</label>
    <pluralLabel>Informatics Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/Informatics_Product__mdt/fields/Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Line_Item__c</fullName>
    <description>Line item fields</description>
    <label>Line item</label>
    <length>355</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Product family of Informatics Products.</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>BASESPACE_SEQUENCE_HUB</fullName>
                <label>BaseSpace Sequence Hub</label>
            </value>
            <value>
                <fullName>BASESPACE_COHORT_ANALYZER</fullName>
                <label>BaseSpace Cohort Analyzer</label>
            </value>
            <value>
                <fullName>BASESPACE_CORRELATION_ENGINE</fullName>
                <label>BaseSpace Correlation Engine</label>
            </value>
            <value>
                <fullName>BASESPACE_CLARITY_LIMS</fullName>
                <label>BaseSpace Clarity LIMS</label>
            </value>
            <value>
                <fullName>DRAGEN</fullName>
            </value>
            <value>
                <fullName>TRUSIGHT_SOFTWARE_SUITE</fullName>
                <label>TruSight Software Suite</label>
            </value>
            <value>
                <fullName>INFORMATICS_ICREDITS</fullName>
                <label>Informatics iCredits</label>
            </value>
            <value>
                <fullName>IAP_BB</fullName>
                <label>IAP BB</label>
            </value>
            <value>
                <fullName>ILLUMINA_CONNECTED_INSIGHTS</fullName>
            </value>
            <value>
                <fullName>INFORMATICS_SAMPLES</fullName>
            </value>
            <value>
                <fullName>PARTEK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Picklist to select product type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUBSCRIPTION</fullName>
                <label>Subscription</label>
            </value>
            <value>
                <fullName>CONSUMPTION_ICREDITS</fullName>
                <label>Consumption iCredits</label>
            </value>
            <value>
                <fullName>ADD-ON</fullName>
                <label>Add-On</label>
            </value>
            <value>
                <fullName>PREPAID_ICREDITS</fullName>
                <label>Prepaid iCredits</label>
            </value>
            <value>
                <fullName>OPEN_PO_ICREDITS</fullName>
                <label>Open PO iCredits</label>
            </value>
            <value>
                <fullName>All Tiers</fullName>
            </value>
            <value>
                <fullName>ICREDITS</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PREPAID_SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/fields/Quote_Line_Item_Fields__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item_Fields__c</fullName>
    <description>Quote line item fields</description>
    <label>Quote Line Item Fields</label>
    <length>355</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/fields/Read_Only_Fields__c.field-meta.xml
<CustomField>
    <fullName>Read_Only_Fields__c</fullName>
    <description>List of Read only fields</description>
    <label>Read Only Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/fields/Required_Fields__c.field-meta.xml
<CustomField>
    <fullName>Required_Fields__c</fullName>
    <description>List of Required fields</description>
    <label>Required Fields</label>
    <length>355</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Informatics_Product__mdt/fields/Subscription_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Type__c</fullName>
    <description>Picklist to select subscription type</description>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
                <default>true</default>
                <label>Enterprise</label>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Free_Trial</fullName>
                <label>Free Trial</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Informatics_Family__c.field-meta.xml
<CustomField>
    <fullName>Informatics_Family__c</fullName>
    <description>Field to store Informatics Family.</description>
    <label>Informatics Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Informatics_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>Informatics_SKU_Type__c</fullName>
    <description>Field to store Informatics SKU Type.</description>
    <label>Informatics SKU Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InformaticProductsService.cls
/**
 *    @author Akshay Mohan
 *    @date   01-13-2020
 *    @description   Service class to contain all Informatics Product Identification business logic
 *    Modification Log:
 *    ------------------------------------------------------------------------------------
 *      Developer                      Date                 Description
 *      Akshay Mohan                   01-13-2020           Initial version
 *      Gopinath Reddy                 01-28-2020           DCP-32166 - Check LIMS/DRAGEN conditons
 *      Iram Malik                     14-Jul-2022          Codescan Fixes
 *      Prem Ranjan                    20-Feb-2023          CodeScan Fixes (APEX) Variable Naming Conventions
 */
public with sharing class InformaticProductsService {

    private static Map<String,Map<String,Map<String,InformaticsProductWrapper>>> mapFamilyToTypeToTier= new Map<String,Map<String,Map<String,InformaticsProductWrapper>>>();
    public static InformaticsProductWrapper iCreditConfig,dragenConfig;
    private static final String ICREDIT = 'Informatics_iCredit_Types';
    private static final String DRAGEN = 'Informatics_Dragen_Family';
    //DCP-32166
    private static final String LIMS ='Informatics_LIMS_Family';  
    private static final String SKUTYPE ='Informatics_LIMS_SKU_Type';
    private static final String ADDON_SKUTYPE ='Informatics_SKU_Type_Add_On';
    private static String strLIMSValue,strSubscription,strADDON;

    //Global constants -DCP-32166
    public static final String DRAGEN_TRIGGER1 ='DragenTrigger1';
    public static final String DRAGEN_TRIGGER2 ='DragenTrigger2';
    public static final String LIMS_TRIGGER1 ='LIMSTrigger1';
    public static final String LIMS_TRIGGER2 ='LIMSTrigger2';

    
    static {
        initialize();
    }
   
   /**
    * @author Gopinath Reddy
    * @date   01-28-2020
    * @description Checking case conditions with return string 
    */

     public static String checkCaseTriggerConditions(Apttus_Config2__OrderLineItem__c oli){
        if(oli.Renewal_Subscription__c) return null;
        if(oli.Apttus_Config2__ProductId__r.Informatics_Family__c == strLIMSValue && oli.Apttus_Config2__ProductId__r.Informatics_SKU_Type__c == strSubscription )//check LIMS Trigger 1
            return LIMS_TRIGGER1;
        else if(oli.Apttus_Config2__ProductId__r.Informatics_Family__c == strLIMSValue && oli.Apttus_Config2__ProductId__r.Informatics_SKU_Type__c == strADDON)//check LIMS Trigger 2
            return LIMS_TRIGGER2;
        else if(oli.Apttus_Config2__ProductId__r.Informatics_Family__c == dragenConfig.strFamily && oli.Custom_License_Flag__c)//check Dragen Trigger 1
            return DRAGEN_TRIGGER1;
        else if(oli.Apttus_Config2__ProductId__r.Informatics_Family__c == dragenConfig.strFamily && oli.Dragen_Connectivity__c == System.Label.Dragen_Connectivity_Offline)//check Dragen Trigger 2
            return DRAGEN_TRIGGER2;
        
        return null;       
    }

    /**
    * @author Akshay Mohan
    * @date   01-13-2020
    * @description prepare mapFamilyToTypeToTier
    */
    private static void initialize(){
        List<Informatics_Product__mdt> lstConfig = new InformaticsProductsSelector().loadAllInformaticsConfigurations();
        System.debug('lstConfig: '+ lstConfig);
        String iCreditValue;
        String dragenValue;
        
        for(Code_Parameter__mdt config : new CodeParametersSelector().selectCodeParameterByDeveloperName(new Set<String>{ICREDIT,DRAGEN,LIMS,SKUTYPE,ADDON_SKUTYPE})){
            if(ICREDIT.equals(config.DeveloperName))
                iCreditValue=config.Value__c;
            if(DRAGEN.equals(config.DeveloperName))
                dragenValue=config.Value__c;
            if(LIMS.equals(config.DeveloperName))
                strLIMSValue=config.Value__c;
            if(SKUTYPE.equals(config.DeveloperName))
                strSubscription=config.Value__c;
            if(ADDON_SKUTYPE.equals(config.DeveloperName))
                strADDON=config.Value__c;
        }

        for(Informatics_Product__mdt config: lstConfig){
            Map<String,Map<String,InformaticsProductWrapper>> mapTypeToTier = mapFamilyToTypeToTier.get(config.Product_Family__c.toUpperCase());
            if(mapTypeToTier==null){
                mapTypeToTier = new Map<String,Map<String,InformaticsProductWrapper>>();
                mapFamilyToTypeToTier.put(config.Product_Family__c.toUpperCase(),mapTypeToTier);
            }
                
            Map<String,InformaticsProductWrapper> mapTierToConfig = mapTypeToTier.get(config.Product_Type__c.toUpperCase());
            if(mapTierToConfig==null){
                mapTierToConfig = new Map<String,InformaticsProductWrapper>();
                mapTypeToTier.put(config.Product_Type__c.toUpperCase(),mapTierToConfig);
            }
                
            InformaticsProductWrapper wrapConfig = new InformaticsProductWrapper(config);
            mapTierToConfig.put(config.Subscription_Type__c.toUpperCase(),wrapConfig);
            if(config.Product_Type__c.toUpperCase() == iCreditValue.toUpperCase())
                iCreditConfig = wrapConfig;
            if(config.Product_Family__c.toUpperCase() == dragenValue.toUpperCase())
                dragenConfig = wrapConfig;
        }
        System.debug('mapFamilyToTypeToTier: '+mapFamilyToTypeToTier);
        System.debug('iCreditConfig: '+iCreditConfig);
        System.debug('dragenConfig: '+dragenConfig);
    }

    /**
    * @author Akshay Mohan
    * @date   01-13-2020
    * @description Get records based on proposal line item
    */
    public static InformaticsProductWrapper getConfig(Apttus_Proposal__Proposal_Line_Item__c pli){
        InformaticsProductWrapper wrapVal =  getConfig(pli.Product_Family__c, pli.Product_Type__c, pli.Product_Tier__c);
        if(wrapVal==null && pli.Is_iCredit__c) wrapVal = iCreditConfig;
        if(wrapVal == null && pli.Is_Dragen__c) wrapVal = dragenConfig;
        return wrapVal;
    }


    /**
    * @author Akshay Mohan
    * @date   01-13-2020
    * @description Get records based on product charecteristics
    */
    public static InformaticsProductWrapper getConfig(String strFamily,String strType,String strTier){
        strFamily= strFamily==null? null : strFamily.toUpperCase();
        strType= strType==null? null : strType.toUpperCase();
        strTier= strTier==null? null : strTier.toUpperCase();
        Map<String,Map<String,InformaticsProductWrapper>> mapTypeToTier = mapFamilyToTypeToTier.get(strFamily);
        if(mapTypeToTier == null) return null;
        Map<String,InformaticsProductWrapper> mapTierToConfig = mapTypeToTier.get(strType);
        if(mapTierToConfig == null) return null;

        return mapTierToConfig.get(strTier);
    }

    
    /**
    * @author Akshay Mohan
    * @description wrapper that has attributres for Informatics Product
    */
    
    public class InformaticsProductWrapper {
        public String strFamily,strType,strTier,strFields,strRequiredFields,strReadOnlyFields;
        public Set<String> setRequiredFields,setReadOnlyFields;
        public List<String> lstCartFields, lstQuoteFields;
        /**
        * @author Akshay Mohan
        * @description wrapper that has attributres for Informatics Product
        * @params Informatics_Product__mdt config
        * retun null
        */
        public InformaticsProductWrapper(Informatics_Product__mdt config){
            strFamily = config.Product_Family__c;
            strType = config.Product_Type__c;
            strTier = config.Subscription_Type__c;
            setRequiredFields = new Set<String>(config.Required_Fields__c.split(','));
            strRequiredFields = config.Required_Fields__c;
            lstCartFields = config.Line_Item__c.split(',');
            lstQuoteFields = config.Quote_Line_Item_Fields__c.split(',');
            strFields = config.Quote_Line_Item_Fields__c;
            strReadOnlyFields = config.Read_Only_Fields__c;
            if(String.isNotBlank(strReadOnlyFields))
                setReadOnlyFields = new Set<String>(strReadOnlyFields.split(','));
            else
                setReadOnlyFields = new Set<String>();
        }
    }
}