force-app/main/default/objects/Opportunity/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <description>As part of US 1298 for user to select possible Competitor</description>
    <inlineHelpText>Primary competitor associated with opportunity.</inlineHelpText>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitor_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_Presence__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Presence__c</fullName>
    <description>Indicates if the opportunity has at least a competitor, no competition, or an unknown competitor.  Jira story # CMCM-5875</description>
    <inlineHelpText>If &apos;yes&apos; a C&amp;CT record should be added (use the Competitive Info tab). If there is no competitor or the competitor is unknown, please select the appropriate option.</inlineHelpText>
    <label>Competitor Context Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No Competitor</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Competitor_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10X Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Agena (Sequenom)</fullName>
    </customValue>
    <customValue>
        <fullName>Agilent</fullName>
    </customValue>
    <customValue>
        <fullName>Apton</fullName>
    </customValue>
    <customValue>
        <fullName>BGI</fullName>
    </customValue>   
    <customValue>
        <fullName>Competitor Unknown / Not Shared</fullName>
    </customValue> 
    <customValue>
        <fullName>Complete Genomics/MGI</fullName>
    </customValue>
    <customValue>
        <fullName>Danaher (IDT)</fullName>
    </customValue>
    <customValue>
        <fullName>DIY INF</fullName>
    </customValue>
    <customValue>
        <fullName>DNANexus</fullName>
    </customValue>
    <customValue>
        <fullName>Element Biosciences</fullName>
    </customValue>
    <customValue>
        <fullName>Fabric Genomics</fullName>
    </customValue>
    <customValue>
        <fullName>GenapSys</fullName>
    </customValue>
    <customValue>
        <fullName>Genemind</fullName>
    </customValue>
    <customValue>
        <fullName>Invitae</fullName>
    </customValue>
    <customValue>
        <fullName>Lexogen</fullName>
    </customValue>
    <customValue>
        <fullName>MatriDx</fullName>
    </customValue>
    <customValue>
        <fullName>NanoString</fullName>
    </customValue>
    <customValue>
        <fullName>Natera</fullName>
    </customValue>
    <customValue>
        <fullName>New England Biolabs (NEB)</fullName>
    </customValue>
    <customValue>
        <fullName>NIPD Genetics</fullName>
    </customValue>
    <customValue>
        <fullName>No Competitor</fullName>
    </customValue>
    <customValue>
        <fullName>NVIDIA (Parabricks)</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Oxford Nanopore Technologies (ONT)</fullName>
    </customValue>
    <customValue>
        <fullName>PacBio</fullName>
    </customValue>
    <customValue>
        <fullName>Qiagen</fullName>
    </customValue>
    <customValue>
        <fullName>Roche / Kapa / Nimblegen</fullName>
    </customValue>
    <customValue>
        <fullName>Send out</fullName>
    </customValue>
    <description>As part of DCP-1298 for Competitor Information.</description>
    <masterLabel>Competitor Name</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEntitySubsRecordDeletionBatch.cls
/***
*    Name -TestEntitySubscriptionRecordDeletionBatch.
*    DESCRIPTION  : TestClass for EntitySubscriptionRecordDeletionBatch class.
*    Modification Log:
*   ------------------------------------------------------------------------------------------------
*    Developer                      Date                		Description
*    Priya Mukherjee              31 Aug 2023                   CMCM-790 
*   ------------------------------------------------------------------------------------------------
*/
@isTest
public class TestEntitySubsRecordDeletionBatch {
     @isTest static void testBatch() {
        // Create a closed Opportunity
        Account acc = TestDataAccount.getNewAccount();
        Opportunity testOpportunity = TestDataOpportunity.initOpportunity(acc);
        testOpportunity.StageName = 'Closed Won';
        testOpportunity.Competitor_Presence__c = 'No Competitor'; //testOpportunity.Competitor_Name__c = 'No Competitor'; Added by SB
        insert testOpportunity;

        // Create EntitySubscription records related to the closed Opportunity
        List<EntitySubscription> subscriptionsToInsert = new List<EntitySubscription>();
        subscriptionsToInsert.add(new EntitySubscription(
                ParentId = testOpportunity.Id,
                SubscriberId = UserInfo.getUserId()
            ));
        insert subscriptionsToInsert;

        Test.startTest();
        // Start the batch process
        EntitySubscriptionRecordDeletionBatch batchInstance = new EntitySubscriptionRecordDeletionBatch();
        Database.executeBatch(batchInstance);

        // Query to check if the subscriptions are deleted
        Integer deletedSubscriptionsCount = [SELECT COUNT() FROM EntitySubscription WHERE ParentId = :testOpportunity.Id];
        Test.stopTest();

        // Ensure that the subscriptions were deleted
        System.assertEquals(1, deletedSubscriptionsCount, 'EntitySubscriptions should have been deleted');
    }

}