force-app/main/default/objects/Contact/fields/AccountBillingCountryCode__c.field-meta.xml
<CustomField>
    <fullName>AccountBillingCountryCode__c</fullName>
    <description>Copies the billing country code from account</description>
    <formula>Account.BillingCountry</formula>
    <label>AccountBillingCountryCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Double_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_In__c</fullName>
    <description>Double Opt In field will be used to determine Marketable status of the Contact.</description>
    <label>Double Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Double_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Double_Opt_In_Date__c</fullName>
    <description>Double Opt In Date field holds the date depicting when Double Opt In was done.</description>
    <label>Double Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Explicit_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Explicit_Opt_In__c</fullName>
    <description>Explicit Opt In field will be used to determine Marketable status of the Contact.</description>
    <label>Explicit Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Implicit_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Implicit_Opt_In__c</fullName>
    <description>Implicit Opt In field will be used to determine Marketable status of the Contact..</description>
    <label>Implicit Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Implicit_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Implicit_Opt_In_Date__c</fullName>
    <description>Implicit Opt In Date field holds the date depicting when Implicit Opt In was done.</description>
    <label>Implicit Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketable__c.field-meta.xml
<CustomField>
    <fullName>Marketable__c</fullName>
    <description>Marketable field will be used to set the Contact as Marketable considering the Implicit, Explicit and Double Opt In flags</description>
    <label>Marketable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketable_Date__c.field-meta.xml
<CustomField>
    <fullName>Marketable_Date__c</fullName>
    <description>Last modified date for Marketable field</description>
    <label>Marketable Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Opt_in_Rule__c.field-meta.xml
<CustomField>
    <fullName>Opt_in_Rule__c</fullName>
    <description>CMCM-1177- This field depicts the Opt-in Rule for a Lead/Contact as of Privacy updates to Marketability in Jan 2024</description>
    <label>Opt-in Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Opt Out Country Single</fullName>
            </value>
            <value>
                <fullName>Opt Out Country Double</fullName>
            </value>
            <value>
                <fullName>Opt In Country Single</fullName>
            </value>
            <value>
                <fullName>Opt In Country Double</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Pardot_Opted_Out__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Opted_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should will be synced from Pardot and this value will be copied over to Email Opted Out</description>
    <label>Pardot Opted Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/cs_Apex_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls apex behavior globally or by user/profile</description>
    <label>Apex Settings</label>
</CustomObject>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_All_Flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_All_Flows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>WARNING: this does just what it says it does. Proceed with caution!</description>
    <inlineHelpText>WARNING: this does just what it says it does. Proceed with caution!</inlineHelpText>
    <label>Bypass All Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_All_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_All_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>WARNING: this does just what it says it does. Proceed with caution!</description>
    <inlineHelpText>WARNING: this does just what it says it does. Proceed with caution!</inlineHelpText>
    <label>Bypass All Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cs_Apex_Settings__c/fields/Bypass_All_Validations__c.field-meta.xml
<CustomField>
    <fullName>Bypass_All_Validations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>WARNING: this does what it says it does (for most validation rules, not all). Proceed with caution!</description>
    <inlineHelpText>WARNING: this does what it says it does (for most validation rules, not all). Proceed with caution!</inlineHelpText>
    <label>Bypass All Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchContactMarketabilityUpdates.cls
/**
*    @author: Deep Diwakar
*    @date:   Mar-19-2024
*    @description: One time batch class to update existing contacts marketability with new logic
*    @Test Class: TestBatchContactMarketabilityUpdates
*    Modification Log:
*    --------------------------------------------------------------------------------------------------
*          Developer           Date                 Description
*         Deep Diwakar       Mar-19-2024        CMCM-5552: Batch class to update existing contacts marketability with new logic
*    --------------------------------------------------------------------------------------------------
*/

public with sharing class BatchContactMarketabilityUpdates implements Database.Batchable<sObject> {

    private static final String LOG_TITLE = 'BatchContactMarketabilityUpdates';

    /**
     * @author: Deep Diwakar
     * @date: Mar-19-2024 
     * @description: Start method for batch class to collect records
     * @param: bc - batch context
     * @return: Database.QueryLocator to return contact records
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        ilib_LogEvent.setTitle(LOG_TITLE, ilib_LogEvent.MARKETING);
        ilib_LogEvent.push(LOG_TITLE + '.start()');

        String strSOQL = 'SELECT Id, MailingCountry, MailingCountryCode, Opt_in_Rule__c, Explicit_Opt_In__c, Double_Opt_In_Email_Sent_Date__c, '
                         + 'Implicit_Opt_In__c, Double_Opt_In__c, Explicit_Opt_In_Date__c, Marketable__c, Marketable_Date__c, '
                         + 'Implicit_Opt_In_Date__c, Double_Opt_In_Date__c, Pardot_Opted_Out__c, HasOptedOutOfEmail, AccountBillingCountryCode__c '
                         + 'FROM Contact';

        strSOQL=String.escapeSingleQuotes(strSOQL);

        ilib_LogEvent.info('strSOQL: ' + strSOQL);

        ilib_LogEvent.pop();
        ilib_LogEvent.emit();

        return Database.getQueryLocator(strSOQL);
    }
    
    /**
     * @author: Deep Diwakar
     * @date: Mar-19-2024 
     * @description: Execute method to run new Marketability logic
     * @param: bc - batch conext
     * @param: scope - contact records for this batch
     * @return: void
     */
    public void execute (Database.BatchableContext bc, List<Contact> scope) {
        ilib_LogEvent.setTitle(LOG_TITLE, ilib_LogEvent.MARKETING);
        ilib_LogEvent.push(LOG_TITLE + '.execute()');

        List<Contact> lstContactUpdates = new List<Contact>();

        // call marketability facade
        MarketabilityServiceFacade facade = new MarketabilityServiceFacade();
        lstContactUpdates = facade.determineMarketability(scope, 'global-v1');

        ilib_LogEvent.info('lstContactUpdates size: ' + lstContactUpdates.size());

        // Bypassing trigger run, validation and flows because this is one time mass update of existing records
        if (Schema.sObjectType.cs_Apex_Settings__c.isUpdateable() && Schema.sObjectType.cs_Apex_Settings__c.isCreateable()) {
          cs_Apex_Settings__c objApexSettings=cs_Apex_Settings__c.getInstance();

          // adding bypass for running user
          objApexSettings.Bypass_All_Validations__c=true;
          objApexSettings.Bypass_All_Triggers__c=true;
          objApexSettings.Bypass_All_Flows__c=true;
          upsert objApexSettings cs_Apex_Settings__c.Id;
          List<Database.SaveResult> results = Database.update(lstContactUpdates, false);
          // log errors, if any
          ApexExceptions.emitSaveErrors(results, LOG_TITLE);

          // revert bypass
          objApexSettings.Bypass_All_Validations__c=false;
          objApexSettings.Bypass_All_Triggers__c=false;
          objApexSettings.Bypass_All_Flows__c=false;
          upsert objApexSettings cs_Apex_Settings__c.Id;
        } else {
          ilib_LogEvent.info('User does not have create and update permission on custom setting - Apex Settings');
        }

        ilib_LogEvent.pop();
        ilib_LogEvent.emit();


    }

    /**
     * @author: Deep Diwakar
     * @date: Mar-19-2024 
     * @description: Required final method for batch
     * @param: bc - batch context
     * @return: void
     */
    public void finish(Database.BatchableContext bc) {
        ilib_LogEvent.setTitle(LOG_TITLE, ilib_LogEvent.MARKETING);
        ilib_LogEvent.push(LOG_TITLE + '.finish()');

        ilib_LogEvent.info('No work for finish method');

        ilib_LogEvent.pop();
        ilib_LogEvent.emit();
    }
}