force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Data to be inserted/updated using batch job-BatchContactCountryRegionMapping.</description>
    <label>Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Data to be inserted/updated using batch job-BatchLeadCountryRegionMapping</description>
    <label>Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/Prospect_Scoring_Log__c.object-meta.xml
<CustomObject>
    <description>DCP- 35842 - Marketing Scoring Log. This would be log for any scoring change for Lead and Contact object</description>
    <label>Marketing Scoring Log</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Marketing Scoring Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Scoring Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Action_Name__c</fullName>
    <description>DCP-35842- Marketing Scoring Log (Custom Object)</description>
    <label>Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <description>DCP-35842- Marketing Scoring Log (Custom Object)</description>
    <label>Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact Id associated with Scoring record</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Scoring Logs</relationshipLabel>
    <relationshipName>Prospect_Scoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DCP-35842- Marketing Scoring Log (Custom Object)</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Scoring Logs</relationshipLabel>
    <relationshipName>Prospect_Scoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/New_Score_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Score_Value__c</fullName>
    <description>DCP-35842- Marketing Scoring Log (Custom Object)</description>
    <label>New Score Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/Previous_Score_Value__c.field-meta.xml
<CustomField>
    <fullName>Previous_Score_Value__c</fullName>
    <description>DCP-35842- Marketing Scoring Log (Custom Object)</description>
    <label>Previous Score Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>DCP-35842- Marketing Scoring Log (Custom Object)</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospect_Scoring_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>User Lookup</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prospect_Scoring_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProspectScoringUtils.cls
/*
*    @author: Pankaj Singla
*    @date:   14-May-2020
*    @description:  Utils class for Prospect Scoring
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Pankaj Singla             14-May-2020             DCP-35843 Initial Build
*    ------------------------------------------------------------------------------------ 
*                    
*/
public with sharing class ProspectScoringUtils{
    public static Boolean boolPreventDuplicateRun=true;
    public static final String STRING_OBJECT_LEAD='Lead';
    
    /*
    *  @author Pankaj Singla
    *  @description To create a new scoring Log Record
    *  @param strActionName - Action Name
    *  @param strCampaignName - The Campaign Name
    *  @param idProspect  - Lead/Contact Id
    *  @param idUser - UserId
    *  @param strRegion - Region
    *  @param intPreviousScore - Previous Score Value
    *  @param intNewScore - New Score Value
    *  @return Prospect_Scoring_Log__c- record
    */
    public static Prospect_Scoring_Log__c createProspectScoringLogRecords(String strActionName,String strCampaignName,Id idProspect, Id idUser,String strRegion,Integer intPreviousScore, Integer intNewScore){
        //boolPreventDuplicateRun=false;
        Prospect_Scoring_Log__c objProspectLog=new Prospect_Scoring_Log__c();
        String sObjName = idProspect.getSObjectType().getDescribe().getName();
        if(sObjName.equals(STRING_OBJECT_LEAD)){
            objProspectLog.Lead__c=idProspect;
        }
        else {
            objProspectLog.Contact__c=idProspect;
        }
        objProspectLog.Action_Name__c=strActionName;
        objProspectLog.Campaign_Name__c=(String.isBlank(strCampaignName)==false?strCampaignName:'');
        objProspectLog.New_Score_Value__c=intNewScore;
        objProspectLog.Previous_Score_Value__c=(intPreviousScore==NULL?0:intPreviousScore);
        objProspectLog.Region__c=strRegion;
        objProspectLog.User__c=idUser;
        return objProspectLog;
        
    }

}