force-app/main/default/objects/innohub__Innovation_Idea__c/innohub__Innovation_Idea__c.object-meta.xml
<CustomObject>
    <label>Idea (Innohub)</label>
    <nameField>
        <label>Innovation Idea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ideas (Innohub)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/innohub__Innovation_Idea__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
	<description>Idea Category and it is controlling picklist field</description>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sequencer: Hardware/Control SW/Reagents</fullName>
            </value>
            <value>
                <fullName>Software: Non-instrument Control SW</fullName>
            </value>
            <value>
                <fullName>Library Prep</fullName>
            </value>
            <value>
                <fullName>Arrays: Scanner/Reagents/Control SW</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
				<isActive>false</isActive>
                <label>Community</label>
            </value>
			<value>
                <fullName>Idea Exchange</fullName>
				<isActive>true</isActive>
                <label>Idea Exchange</label>
            </value>
            <value>
                <fullName>Proactive</fullName>
            </value>
            <value>
                <fullName>Topics for Support Videos</fullName>
            </value>
            <value>
                <fullName>DCP Enhancements – AMR</fullName>
            </value>
            <value>
                <fullName>AMR Service &amp; Support Hub</fullName>
            </value>
            <value>
                <fullName>Internal Field Service Document Revision Request</fullName>
            </value>
            <value>
                <fullName>TS Process Excellence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/innohub__Innovation_Idea__c/fields/innohub__Category__c.field-meta.xml
<CustomField>
    <fullName>innohub__Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sequencer: Hardware/Control SW/Reagents</fullName>
            </value>
            <value>
                <fullName>Software: Non-instrument Control SW</fullName>
            </value>
            <value>
                <fullName>Library Prep</fullName>
            </value>
            <value>
                <fullName>Arrays: Scanner/Reagents/Control SW</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Proactive</fullName>
            </value>
            <value>
                <fullName>Topics for Support Videos</fullName>
            </value>
            <value>
                <fullName>DCP Enhancements – AMR</fullName>
            </value>
			<value>
                <fullName>AMR Service &amp; Support Hub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/innohub__Innovation_Idea__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
	<description>Idea Sub Category and it is dependent multi select picklist field</description>
    <label>Sub Category</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>iSeq 100</fullName>
            </value>
            <value>
                <fullName>MiniSeq</fullName>
            </value>
            <value>
                <fullName>MiSeq</fullName>
            </value>
            <value>
                <fullName>MiSeqDx</fullName>
            </value>
            <value>
                <fullName>NextSeq 500/550</fullName>
            </value>
            <value>
                <fullName>NextSeq 550Dx</fullName>
            </value>
            <value>
                <fullName>NextSeq 1000/2000</fullName>
            </value>
            <value>
                <fullName>HiSeq 1000/1500/2000/2500/3000/4000/X</fullName>
            </value>
            <value>
                <fullName>NovaSeq 6000</fullName>
            </value>
            <value>
                <fullName>NovaSeq 6000Dx</fullName>
            </value>
            <value>
                <fullName>NovaSeq X</fullName>
            </value>
            <value>
                <fullName>BaseSpace Sequence Hub (BSSH)</fullName>
            </value>
            <value>
                <fullName>BaseSpace CLI</fullName>
            </value>
            <value>
                <fullName>DRAGEN Bio-IT Platform</fullName>
            </value>
            <value>
                <fullName>BaseSpace Apps</fullName>
            </value>
            <value>
                <fullName>Illumina Connected Analytics (ICA)</fullName>
            </value>
            <value>
                <fullName>Local Run Manager (LRM)</fullName>
            </value>
            <value>
                <fullName>TruSight Software Suite (TSS)</fullName>
            </value>
            <value>
                <fullName>Internal use only tools/resources</fullName>
            </value>
            <value>
                <fullName>Emedgene (Illumina Connected Insights)</fullName>
            </value>
            <value>
                <fullName>DNA prep kits</fullName>
            </value>
            <value>
                <fullName>RNA prep kits</fullName>
            </value>
            <value>
                <fullName>AmpliSeq</fullName>
            </value>
            <value>
                <fullName>Enrichment</fullName>
            </value>
            <value>
                <fullName>Clinical, NIPT, and TSO500</fullName>
            </value>
            <value>
                <fullName>Infinium assay</fullName>
            </value>
            <value>
                <fullName>Microarray instrumentation/equipment</fullName>
            </value>
            <value>
                <fullName>Microarray analysis</fullName>
            </value>
            <value>
                <fullName>Arrays</fullName>
            </value>
            <value>
                <fullName>Library Prep</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/innohub__Innovation_Idea__c/fields/Vote_Count__c.field-meta.xml
<CustomField>
    <fullName>Vote_Count__c</fullName>
    <description>Multiply total number of votes by 10 to get points</description>
    <formula>10* innohub__Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PS_Log_Setting__mdt/PS_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Threshholds, flags, and other config for Persistable Structured (PS) Logs. Code looks for developer name = PS_Log_Settings</description>
    <label>PS Log Setting</label>
    <pluralLabel>PS Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PS_Log_Setting__mdt/fields/Disable_All_Log_Persistence__c.field-meta.xml
<CustomField>
    <fullName>Disable_All_Log_Persistence__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stops all publishing/persisting of all PS Logs, no matter the user-level configuration</description>
    <inlineHelpText>Stops all publishing/persisting of all PS Logs, no matter the user-level configuration</inlineHelpText>
    <label>Disable All Log Persistence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PS_Log_Setting__mdt/fields/Disable_Slow_Query_Publish__c.field-meta.xml
<CustomField>
    <fullName>Disable_Slow_Query_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stops all publishing/persisting of slow queries, no matter how slow</description>
    <inlineHelpText>Stops all publishing/persisting of slow queries, no matter how slow</inlineHelpText>
    <label>Disable Slow Query Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PS_Log_Setting__mdt/fields/Disable_Slow_Transaction_Publish__c.field-meta.xml
<CustomField>
    <fullName>Disable_Slow_Transaction_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stops all publishing/persisting of slow transactions, no matter how slow</description>
    <inlineHelpText>Stops all publishing/persisting of slow transactions, no matter how slow</inlineHelpText>
    <label>Disable Slow Transaction Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PS_Log_Setting__mdt/fields/Slow_Query_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Slow_Query_Threshold__c</fullName>
    <description>Queries longer than this number of seconds will be logged as performance hogs, min/max = 0.5/10</description>
    <inlineHelpText>Queries longer than this number of seconds will be logged as performance hogs, min/max = 0.5/10</inlineHelpText>
    <label>Slow Query Threshold</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PS_Log_Setting__mdt/fields/Slow_Transaction_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Slow_Transaction_Threshold__c</fullName>
    <description>Transactions longer than this number of seconds will be logged as performance hogs, min/max = 2.5/15</description>
    <inlineHelpText>Transactions longer than this number of seconds will be logged as performance hogs, min/max = 2.5/15</inlineHelpText>
    <label>Slow Transaction Threshold</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestIdeaLikeDislikeComponentController.cls
/**
*    Description - Test class for IdeaLikeDislikeComponentController 
*    Modification Log:
*   ------------------------------------------------------------------------------------------------------------
*    Developer                      Date                		Description
*    Rishab Wali                    29th Aug 2022               DCP-56319 Like Dislike Fucntionality 
*    -----------------------------------------------------------------------------------------------------------
*/
@isTest(SeeAllData=false isParallel=false)
public class TestIdeaLikeDislikeComponentController {

        
    /*
    * Test method to LikeDisLikeIdea
    */
    @isTest
    public static void checkVoteLike() {

        // config environment to enable query logs
        Feature.setMockFeatureFlag('MarketingQueryLogs', true);
        
        // setting query threshold to zero to log all queries for testing
        setThreshholdsToZero();
        
        innohub__Innovation_Idea__c objIdea = new innohub__Innovation_Idea__c(Name='Test Innovate', innohub__Category__c='Other', innohub__Description__c='Test Description');
        objIdea.Category__c = 'Idea Exchange';
		objIdea.Sub_Category__c = 'Other';
		insert objIdea;
        innohub__Innovation_Idea_Vote__c ideaVote = new innohub__Innovation_Idea_Vote__c(innohub__Innovation_Idea__c=objIdea.id, innohub__Vote_Type__c=True);
        insert ideaVote;

        Test.startTest();                
            IdeaLikeDislikeComponentController.ideaLiked(objIdea.Id);
            IdeaLikeDislikeComponentController.updateVote(false,objIdea.Id);
            IdeaLikeDislikeComponentController.updateVote(true,objIdea.Id);
        Test.stopTest();        
        innohub__Innovation_Idea__c objInnohubIdea = [SELECT Id,Vote_Count__c FROM innohub__Innovation_Idea__c WHERE Id =: objIdea.Id];
        System.assertEquals(10,objInnohubIdea.Vote_Count__c,'Vote Count not updated correctly');
    }

    /*
    * Test method to LikeDisLikeIdea
    */
    @isTest
    public static void checkVoteUnlike() {

        innohub__Innovation_Idea__c objIdea = new innohub__Innovation_Idea__c(Name='Test Innovate', innohub__Category__c='Other', innohub__Description__c='Test Description');
        objIdea.Category__c = 'Idea Exchange';
		objIdea.Sub_Category__c = 'Other';
		insert objIdea;

        Test.startTest();                
            IdeaLikeDislikeComponentController.ideaLiked(objIdea.Id);
            IdeaLikeDislikeComponentController.updateVote(false,objIdea.Id);
        Test.stopTest();        
        innohub__Innovation_Idea__c objInnohubIdea = [SELECT Id,Vote_Count__c FROM innohub__Innovation_Idea__c WHERE Id =: objIdea.Id];
        System.assertEquals(0,objInnohubIdea.Vote_Count__c,'Vote Count not updated correctly');
    }
    
     private static void setThreshholdsToZero()
     {
         PS_Log_Setting__mdt settings = new ilib_LogSettings().query();
         settings.Slow_Query_Threshold__c = 0.0;
         settings.Slow_Transaction_Threshold__c = 0.0;
         settings.Disable_All_Log_Persistence__c = false;
         settings.Disable_Slow_Query_Publish__c = false;
         settings.Disable_Slow_Transaction_Publish__c = false;

         ilib_LogSettings.unitTestSettingsRecord = settings;
     }
    
 }