force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used by Reverse Logistics Module. Reference to the latest service contract for this installed product. Derived automatically upon creating/updating service contract</description>
    <label>Service Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipName>Installed_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Offering__c/SVMXC__PM_Offering__c.object-meta.xml
<CustomObject>
    <description>This is to define Preventive Maintenance offered as part of Service Plan</description>
    <label>PM Offering</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Offerings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__PM_Offering__c/fields/SVMXC__PM_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__PM_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM Plan Template</label>
    <referenceTo>SVMXC__PM_Plan_Template__c</referenceTo>
    <relationshipLabel>PM Offerings</relationshipLabel>
    <relationshipName>PM_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Offering__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipLabel>PM Offerings</relationshipLabel>
    <relationshipName>PM_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Offering__c/fields/SVMXC__Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Plan</label>
    <referenceTo>SVMXC__Service_Plan__c</referenceTo>
    <relationshipLabel>PM Offerings</relationshipLabel>
    <relationshipName>PM_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__PM_Plan_Template__c/SVMXC__PM_Plan_Template__c.object-meta.xml
<CustomObject>
    <description>This is a template for creating preventive maintenance plan, it has definitions for products, schedules and tasks that are needs to be performed as part of Preventive Maintenance.</description>
    <label>PM Plan Template</label>
    <nameField>
        <label>PM Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Plan Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract__c/SVMXC__Service_Contract__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__End_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__End_Date__c</fullName>
    <description>End date of the service contract</description>
    <inlineHelpText>End date of the service contract</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__Service_Plan__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Plan</label>
    <referenceTo>SVMXC__Service_Plan__c</referenceTo>
    <relationshipLabel>Service/Maintenance Contracts</relationshipLabel>
    <relationshipName>Service_Maintenance_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract__c/fields/SVMXC__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Start_Date__c</fullName>
    <description>Start date of the service contract</description>
    <inlineHelpText>Start date of the service contract</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/SVMXC__Service_Contract_Products__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed products, part numbers, or groups of products entitled by this service contract.</description>
    <label>Covered Product</label>
    <nameField>
        <displayFormat>SCPN-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Covered Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/fields/SVMXC__End_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__End_Date__c</fullName>
    <description>End date of service contract/warranty at the time of entitlement</description>
    <inlineHelpText>End date of service contract/warranty at the time of entitlement</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/fields/SVMXC__Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the installed product covered by the service contract. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Name of the installed product covered by the service contract. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>R00N70000001hzdkEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/fields/SVMXC__Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Contract__c</fullName>
    <description>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</description>
    <inlineHelpText>Name of the service contract. Is a lookup to an existing service contract in ServiceMax</inlineHelpText>
    <label>Service/Maintenance Contract</label>
    <referenceTo>SVMXC__Service_Contract__c</referenceTo>
    <relationshipName>R00N70000001hzdaEAA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Contract_Products__c/fields/SVMXC__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Start_Date__c</fullName>
    <description>Start date of service contract/warranty at the time of entitlement</description>
    <inlineHelpText>Start date of service contract/warranty at the time of entitlement</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Plan__c/SVMXC__Service_Plan__c.object-meta.xml
<CustomObject>
    <description>Service Plan is a template for creating service contract, it has all coverage information along with detail pricing terms.</description>
    <label>Service Plan</label>
    <nameField>
        <label>Service Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Plan__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>This custom object represents the External ID field for SAP Material reference.</description>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBatchCreatePMPlans.cls
/**
*    @author: prashanth 
*    @date:   20-Jan-2021
*    @description:  Test Class for  BatchCreatePMPlans batch class.
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*    ------------------------------------------------------------------------------------ 
*             Prashanth                   20-Jan-2021           Initial Development            
*/
@isTest
public class TestBatchCreatePMPlans {
	/**
	* Method:pmPlanCreationTest
	* params: NA
	* return: NA
	* Description: Tests the BatchCreatePMPlans class functionality to create PM plans.
	*/
    static testMethod void pmPlanCreationTest(){
		//Account
        Account objAccount = TestDataAccount.getNewAccount();
		//Installed product
        SVMXC__Installed_Product__c ip = TestDataFieldService.createInstalledProduct('test installed product', 'USD', 'Installed');
        insert ip;
		System.assert(ip.id != null);

		SVMXC__Service_Plan__c sp1 = new SVMXC__Service_Plan__c();
        sp1.Name = 'Test1';
        sp1.Item_Number__c = '1111';
        insert sp1;
		
		SVMXC__PM_Plan_Template__c pmTemplate = new SVMXC__PM_Plan_Template__c();
		pmTemplate.Name='Test PM Template';
		pmTemplate.CurrencyIsoCode='USD';
		insert pmTemplate;
		
		SVMXC__PM_Offering__c pm = new SVMXC__PM_Offering__c();
		pm.SVMXC__Service_Plan__c=sp1.id;
		pm.SVMXC__PM_Plan_Template__c=pmTemplate.id;
        insert pm;
		System.assert(pm.id != null);

		SVMXC__Service_Contract__c testServCont = TestDataFieldService.createServiceContract(objAccount.Id);
        testServCont.SVMXC__Service_Plan__c = sp1.id;
		testServCont.SVMXC__Start_Date__c = system.today();
		testServCont.SVMXC__End_Date__c = system.today().addYears(1); 
        insert testServCont;
		
		SVMXC__Service_Contract_Products__c cp = TestDataFieldService.createCoveredProduct(ip.Id);
		cp.SVMXC__Service_Contract__c = testServCont.Id;
		insert cp;
		Test.startTest();
		//execute PM batch for creation of PM plan
		database.executebatch(new BatchCreatePMPlans());
		//test scheduler
		BatchCreatePMPlans testObj = new BatchCreatePMPlans();      
        String strCron = '0 0 23 * * ?';
        String jobId = system.schedule('Test Schedule Batch', strCron, testObj);
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
		System.assertEquals(strCron,ct.CronExpression);
		Test.stopTest(); 		
    }
}