force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Last_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_PM_Date__c</fullName>
    <description>To capture the latest Preventive Maintenance Date</description>
    <label>Last PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/Last_PM_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_PM_Date__c</fullName>
    <description>To capture the latest Preventive Maintenance Date</description>
    <formula>SVMXC__Component__r.Last_PM_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Component__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</description>
    <inlineHelpText>Serial number of the component for which the customer is seeking support. Is a lookup to an existing installed product record in ServiceMax</inlineHelpText>
    <label>Component</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Component</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/SVMXC__Service_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. In ServiceMax, service orders can be used to manage the entire service delivery process, from creating estimates and quotations, to requesting and receiving parts, to recording usage/consumption, to closure and analysis.</description>
    <label>Work Detail</label>
    <nameField>
        <displayFormat>WL-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Activity_Type__c</fullName>
    <description>Indicates the type of activity performed. Usually applicable for labor line types.</description>
    <inlineHelpText>Indicates the type of activity performed. Usually applicable for labor line types.</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Work_Order_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Calibration</fullName>
            </value>
            <value>
                <fullName>Cleanup</fullName>
            </value>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Customer Readiness</fullName>
            </value>
            <value>
                <fullName>Customer Service Review</fullName>
            </value>
            <value>
                <fullName>Dedicated Onsite Activities</fullName>
            </value>
            <value>
                <fullName>De-Installation</fullName>
            </value>
            <value>
                <fullName>Depot Service</fullName>
            </value>
            <value>
                <fullName>Field Compliance Review</fullName>
            </value>
            <value>
                <fullName>Illumina Review</fullName>
            </value>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>IQ/OQ</fullName>
            </value>
            <value>
                <fullName>IT Consult</fullName>
            </value>
            <value>
                <fullName>Letter of Acceptance accepted</fullName>
            </value>
            <value>
                <fullName>OQ</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>PQ Training</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Qualification Service Review</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Remote Support</fullName>
            </value>
            <value>
                <fullName>Repair/Troubleshooting</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Sales Support Activity</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
                <default>true</default>
                <label>Service</label>
            </value>
            <value>
                <fullName>System Health Check</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__End_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__End_Date_and_Time__c</fullName>
    <description>End date and time if the line type is Labor</description>
    <inlineHelpText>End date and time if the line type is Labor</inlineHelpText>
    <label>End Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Line_Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Line_Status__c</fullName>
    <description>Service Order Line Status.</description>
    <inlineHelpText>Service Order Line Status.</inlineHelpText>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reversal Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting WO Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the part used. Reference to an existing installed product record in ServiceMax</description>
    <label>IB Serial Number</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Service_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Order__c</fullName>
    <description>Service order number. Is a lookup to an existing service order in ServiceMax</description>
    <inlineHelpText>Service order number. Is a lookup to an existing service order in ServiceMax</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PopulateLastPMDateOnIP.cls
  /*
  @author        : Ritika M
* @ date         : 11-MAR-2022
* @ Description  : To Populate last PM date on installed product related to PM work order 
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                   Modification ID      Description
* ---------------------------------------------------------------------------------------------------------------------------------------
* 
* 
*/
public with sharing class PopulateLastPMDateOnIP implements ilib_AdminOperationLogicInterface {

     /*
     * @param      : List<Id>
     * @return     : void 
     * @Description: Method to Populate last PM date on installed product related to PM work order
     **/
    public static void doBusinessLogic(List<Id> setPMCompletedWOIds){ 
        Map<Id,SVMXC__Installed_Product__c> mapIPIdtoIPObj = new Map<Id,SVMXC__Installed_Product__c>();
        for(SVMXC__Service_Order__c objWorkOrder : [SELECT Id, SVMXC__Component__c, SVMXC__Component__r.Last_PM_Date__c, (SELECT Id, SVMXC__Activity_Type__c,SVMXC__End_Date_and_Time__c FROM SVMXC__Service_Order_Line__r WHERE SVMXC__Activity_Type__c = 'Preventative Maintenance' AND SVMXC__End_Date_and_Time__c != Null AND SVMXC__Line_Status__c != 'Canceled' ORDER BY SVMXC__End_Date_and_Time__c DESC LIMIT 1) FROM SVMXC__Service_Order__c WHERE Id IN: setPMCompletedWOIds ] ){
            if(objWorkOrder.SVMXC__Service_Order_Line__r.size() > 0){
                
                if((objWorkOrder.SVMXC__Component__r.Last_PM_Date__c  == null) || (objWorkOrder.SVMXC__Component__r.Last_PM_Date__c != null && objWorkOrder.SVMXC__Service_Order_Line__r[0].SVMXC__End_Date_and_Time__c != null && objWorkOrder.SVMXC__Service_Order_Line__r[0].SVMXC__End_Date_and_Time__c.date() > objWorkOrder.SVMXC__Component__r.Last_PM_Date__c)){
                
                SVMXC__Installed_Product__c objInstalledProduct;
                    if(mapIPIdtoIPObj.ContainsKey(objWorkOrder.SVMXC__Component__c))
                        objInstalledProduct=mapIPIdtoIPObj.get(objInstalledProduct.Id);
                    else{
                        objInstalledProduct = new  SVMXC__Installed_Product__c();
                        objInstalledProduct.Id = objWorkOrder.SVMXC__Component__c;
                    }
                    objInstalledProduct.Last_PM_Date__c = objWorkOrder.SVMXC__Service_Order_Line__r[0].SVMXC__End_Date_and_Time__c.date();
                    mapIPIdtoIPObj.put(objInstalledProduct.Id,objInstalledProduct);
                }
            }
        }
        if(!mapIPIdtoIPObj.isEmpty()){
            update mapIPIdtoIPObj.values();
        }
    }

}