force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/Deinstall_Date__c.field-meta.xml
<CustomField>
    <fullName>Deinstall_Date__c</fullName>
    <description>To populate the de-installed date based on completion of work order</description>
    <label>Deinstall Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMX_PS_VS_Cloned_From_IP__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_VS_Cloned_From_IP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents the field from which the Installed Product was cloned/created when doing Part Swap</description>
    <inlineHelpText>This field represents the field from which the Installed Product was cloned/created when doing Part Swap</inlineHelpText>
    <label>Cloned From IP</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Installed Products (Cloned From IP)</relationshipLabel>
    <relationshipName>SVMX_PS_VS_Cloned_From_IP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Date_Installed__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Date_Installed__c</fullName>
    <description>Date on which the product was installed at the customer location</description>
    <inlineHelpText>Date on which the product was installed at the customer location</inlineHelpText>
    <label>Date Installed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Parent__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial/Lot number of the parent product in the installed product hierarchy. This is a lookup to an existing installed product record.</description>
    <inlineHelpText>Serial/Lot number of the parent product in the installed product hierarchy. This is a lookup to an existing installed product record.</inlineHelpText>
    <label>Parent</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>R00N70000001hzcgEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Site__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current physical location of the product. This is a lookup to an existing location record</description>
    <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
    <label>Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipName>R00N70000001hzcqEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Status__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Status__c</fullName>
    <description>Current status of the installed product.</description>
    <inlineHelpText>Current status of the installed product.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipped</fullName>
                <default>true</default>
                <label>Shipped</label>
            </value>
            <value>
                <fullName>Returned Vendor</fullName>
            </value>
            <value>
                <fullName>Non Calibrated</fullName>
            </value>
            <value>
                <fullName>Awaiting Installation</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Scrapped</fullName>
            </value>
            <value>
                <fullName>Loaned</fullName>
            </value>
            <value>
                <fullName>De-Installed</fullName>
            </value>
            <value>
                <fullName>Calibrated</fullName>
            </value>
            <value>
                <fullName>Not Calibrated Expired</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Top_Level__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Top_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial/Lot number of the top-most product in the installed product hierarchy.</description>
    <inlineHelpText>Serial/Lot number of the top-most product in the installed product hierarchy.</inlineHelpText>
    <label>Top-Level</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>R00N70000001hzcvEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/SVMXC__Service_Order_Line__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. In ServiceMax, service orders can be used to manage the entire service delivery process, from creating estimates and quotations, to requesting and receiving parts, to recording usage/consumption, to closure and analysis.</description>
    <label>Work Detail</label>
    <nameField>
        <displayFormat>WL-{00000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMX_PS_VS_Return_Installed_Product__c.field-meta.xml
<CustomField>
    <fullName>SVMX_PS_VS_Return_Installed_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installed Product which is removed as a part of Part Out Process</description>
    <inlineHelpText>Installed Product which is removed as a part of Part Out Process</inlineHelpText>
    <label>Return Installed Product</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Work Details (Return Installed Product)</relationshipLabel>
    <relationshipName>SVMX_PS_VS_Return_Installed_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order_Line__c/fields/SVMXC__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Serial number of the part used. Reference to an existing installed product record in ServiceMax</description>
    <label>IB Serial Number</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipName>Service_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Site__c/SVMXC__Site__c.object-meta.xml
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Site is a unique location and is identified by a name and address. Site information is especially beneficial in service scenarios when accurate information about the physical location of a product is crucial to the timely delivery of service. ServiceMax also uses site to track warehouse and field inventory locations.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Site__c/fields/SVMXC__Parent__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdjustSerializedPart_WorkdetailHelper.cls
/*****************************************************************************************************************
 * Class Name: AdjustSerializedPart_WorkdetailHelper
 * Description: Adjust the inventory for serialized, batch & non tracked products.
 * Author: Prashanth
 * 
 * Date: 06-Dec-2021
 * 
 * Notification Log:
 * -------------------------------------------------------------------------------------------------------------
 * Developer                  Date                              Description
 * -------------------------------------------------------------------------------------------------------------
 * Prashanth               06-12-2021        Adjust the inventory for serialized, batch & non tracked products.
 ******************************************************************************************************************/
public with sharing class AdjustSerializedPart_WorkdetailHelper {
    /*
    *  @DESCRIPTION: DCP-44981 - Parts Consumption Reversal Process for Serialized Work Detail, update on IP
    *  @RETURN:  void
    */
    public static void adjustInstalledProductForSerializedPart(Map < Id, SVMXC__Service_Order_Line__c > serializedWorkDetailIdToWorkDetailMap, String serializedOrNonTracked) {

        Map < Id, SVMXC__Installed_Product__c > installedProductIdToUpdateIPMap = new Map < Id, SVMXC__Installed_Product__c > ();
        Map<Id, SVMXC__Service_Order_Line__c> installedProductIdToWorkDetailMap = populateIPMap(serializedWorkDetailIdToWorkDetailMap);
        if (!installedProductIdToWorkDetailMap.isEmpty()) {
            PartsConsumptionReversal_WDHelper.installedProductIdToWorkDetailFinalMap = installedProductIdToWorkDetailMap;
            Map < Id, SVMXC__Installed_Product__c > installedProductIdToIPMap = new Map < Id, SVMXC__Installed_Product__c > ([Select Id, SVMXC__Top_Level__c, SVMXC__Parent__c, SVMXC__Site__c, SVMXC__Status__c from SVMXC__Installed_Product__c where Id IN: installedProductIdToWorkDetailMap.keyset()]);
            
            for (Id installedProductId: installedProductIdToIPMap.keyset()) {

                //Return Installed product  
                if ( installedProductIdToWorkDetailMap.containsKey(installedProductId) && serializedWorkDetailIdToWorkDetailMap.get(installedProductIdToWorkDetailMap.get(installedProductId).Id).SVMX_PS_VS_Return_Installed_Product__c == installedProductId) {

                    installedProductIdToUpdateIPMap.put(installedProductId, new SVMXC__Installed_Product__c(
                        Id = installedProductId,
                        SVMXC__Top_Level__c = installedProductIdToIPMap.get(serializedWorkDetailIdToWorkDetailMap.get(installedProductIdToWorkDetailMap.get(installedProductId).Id).SVMXC__Serial_Number__c).SVMXC__Top_Level__c,
                        SVMXC__Parent__c = installedProductIdToIPMap.get(serializedWorkDetailIdToWorkDetailMap.get(installedProductIdToWorkDetailMap.get(installedProductId).Id).SVMXC__Serial_Number__c).SVMXC__Parent__c,
                        Deinstall_Date__c = null,
                        SVMX_PS_VS_Cloned_From_IP__c = null,
                        SVMXC__Status__c = 'Installed'));

                }


                //Installed product 
                if ( installedProductIdToWorkDetailMap.containsKey(installedProductId) && serializedWorkDetailIdToWorkDetailMap.get(installedProductIdToWorkDetailMap.get(installedProductId).Id).SVMXC__Serial_Number__c == installedProductId) {
                    installedProductIdToUpdateIPMap.put(installedProductId, new SVMXC__Installed_Product__c(
                        Id = installedProductId,
                        SVMXC__Top_Level__c = null,
                        SVMXC__Parent__c = null,
                        SVMX_PS_VS_Cloned_From_IP__c = null,
                        SVMXC__Date_Installed__c = null,
                        SVMXC__Status__c = 'Shipped'));
                }

            }
            
            
            system.debug('installedProductIdToUpdateIPMap ' +installedProductIdToUpdateIPMap);
            if ( !installedProductIdToUpdateIPMap.isEmpty()) {
                PartsConsumptionReversal_WDHelper.listInstalledProductFinalUpdate.addAll(installedProductIdToUpdateIPMap.values());
            }

        }

    }
    /*
    *  @DESCRIPTION: DCP-44981 - Parts Consumption Reversal Process for Serialized Work Detail, update on IP
    *  @RETURN:  void
    */
    public static Map < Id, SVMXC__Service_Order_Line__c > populateIPMap(Map < Id, SVMXC__Service_Order_Line__c > serializedWorkDetailIdToWorkDetailMap){
        Map < Id, SVMXC__Service_Order_Line__c > installedProductIdToWorkDetailMap = new Map < Id, SVMXC__Service_Order_Line__c >();
        for (Id workDetailId: serializedWorkDetailIdToWorkDetailMap.keyset()) {
            //if installed product and return installed product is not null, adjust the values.
            if (String.isNotBlank(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMXC__Serial_Number__c) && String.isNotBlank(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMX_PS_VS_Return_Installed_Product__c)
                || String.isNotBlank(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMXC__Serial_Number__c) && String.isBlank(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMX_PS_VS_Return_Installed_Product__c)
            ) {
                //Return Installed Product
                if(String.isNotBlank(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMX_PS_VS_Return_Installed_Product__c)){
                installedProductIdToWorkDetailMap.put(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMX_PS_VS_Return_Installed_Product__c, serializedWorkDetailIdToWorkDetailMap.get(workDetailId));    
                }
                
                //Installed Product
                installedProductIdToWorkDetailMap.put(serializedWorkDetailIdToWorkDetailMap.get(workDetailId).SVMXC__Serial_Number__c, serializedWorkDetailIdToWorkDetailMap.get(workDetailId));
            
            }
        }
        return installedProductIdToWorkDetailMap;
    }
}