force-app/main/default/objects/SVMXC__Installed_Product__c/SVMXC__Installed_Product__c.object-meta.xml
<CustomObject>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Installed_Product__c/fields/SVMXC__Serial_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Serial_Lot_Number__c</fullName>
    <description>Unique identification of this product. This information is Required if the product’s tracking is Serialized or Lot/Batch Tracked in the product record</description>
    <inlineHelpText>Unique identification of this product. This information is Required if the product’s tracking is Serialized or Lot/Batch Tracked in the product record</inlineHelpText>
    <label>Serial/Lot Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProactiveDynamicComponentController.cls
/*
*    @author Sagar Madkaikar 
*    @date   2021-09-27
*    @description  Controller class for ProactiveDynamicComponent component.
*    90% Code Coverage: TestProactiveDynamicComponentController
*    75% Code Coverage: TestProactiveDynamicComponentController
*    Modification Log:
*    -------------------------------------------------------------------------------------------------------
*             Developer               Date                Description
*            Sagar Madkaikar       27 Sep 2021           CMCP-81:Initial Version  
*            Sibin P Kuriakose     31 Aug 2022           [CMSI-219]: Instrumentation of the Class      		
*    --------------------------------------------------------------------------------------------------------
*                    
*/
public without sharing class ProactiveDynamicComponentController {
    private static final String LOG_TITLE = 'ProactiveDynamicComponentController';
    private static final String OBJ_INSTALLED_PRODUCT = 'Installed Products';
    /*
     *  @author Sagar Madkaikar
     *  @description Get current record ID details from recordID and Object Name passed.
     *  @param - recordId Id of current record.
     *  @param objectName - Object Name of current record.
     *  @return String - field value depending on the object name. This value will be used to form iFrame URL
     */
    @AuraEnabled
    public static String getCurrentRecordDetails(Id recordId,String objectName)
    {
        ilib_LogEvent.setTitle(LOG_TITLE, ilib_LogEvent.SERVICE); //CMSI-219
        ilib_LogEvent.push(LOG_TITLE + '.getCurrentRecordDetails');
        String returnValue;
        
        try {
            ilib_LogEvent.info('recordId'+recordId); //CMSI-219
            ilib_LogEvent.info('objectName'+objectName); //CMSI-219      
            if(objectName==OBJ_INSTALLED_PRODUCT) {
                InstalledProductsSelector ipSelector = new InstalledProductsSelector();
                List<SVMXC__Installed_Product__c> ipList = ipSelector.selectRelatedInstalledProducts(new Set<Id>{recordId});
                //return SVMXC__Serial_Lot_Number__c for IP object to form iFrame URL
                if(!ipList.isEmpty()){
                    returnValue = ipList[0].SVMXC__Serial_Lot_Number__c; 
                }
            }
        } catch (Exception e) {
            ApexExceptions.emit(LOG_TITLE,recordId,e,ilib_LogEvent.SERVICE);
            ilib_LogEvent.pop(); //CMSI-219
            ilib_LogEvent.emit(); //CMSI-219
            throw  new AuraHandledException('getCurrentRecordDetails'+ e.getMessage()) ;
        }
        ilib_LogEvent.info('Value of Field' + returnvalue); //CMSI-219
        ilib_LogEvent.pop(); //CMSI-219
        ilib_LogEvent.emit(); //CMSI-219
        return returnValue;
    }
}