force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Represents Territory and Overlay plan created by Inside Sales and Channel Partner users</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date indicates when the planned execution of the Territory plan will be completed and is defaulted to the last day of the selected calendar year.</description>
    <inlineHelpText>End Date indicates when the planned execution of the Territory plan will be completed and is defaulted to the last day of the selected calendar year.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date indicates when the execution of a Territory Plan begins and is defaulted to the first day of the selected calendar year.</description>
    <inlineHelpText>Start Date indicates when the execution of a Territory Plan begins and is defaulted to the first day of the selected calendar year.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Plan Status indicates the current status of the Territory plan. The status can be defined as Draft, Active, or Closed.</description>
    <inlineHelpText>The Plan Status indicates the current status of the Territory plan. The status can be defined as Draft, Active, or Closed. Draft means the plan is in work, and not yet being acted upon(Active). Closed means the plan has been replaced or completed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Territory_Id__c</fullName>
    <description>Territory ID of the user in ETM hierarchy, who created the Plan is auto populated at the time of plan creation</description>
    <inlineHelpText>Territory ID of the user in ETM hierarchy, who created the Plan is auto populated at the time of plan creation</inlineHelpText>
    <label>Territory Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataPlan.cls
/*@ author       : KD
* @ date         : 28-July-2020
* @ Description  : CreatePlan in system
*
* Modification Log:
* --------------------------------------------------------------------------------------------------------------------------------------
*   Developer                  Date                       Description
*    KD                      12-Aug-2020                  Added getOverlayPlan method
   Anisha Bharti             07-Sept-2020                DCP-40497 : updated plan recordtype API name
* ---------------------------------------------------------------------------------------------------------------------------------------

* 
*/
@isTest
public with sharing class TestDataPlan {
    public static Id idOverlayRecordType = Schema.SObjectType.Plan__c.getRecordTypeInfosByDeveloperName().get(Label.PlanOverlay).getRecordTypeId();
    public static Id idDirectRecordType = Schema.SObjectType.Plan__c.getRecordTypeInfosByDeveloperName().get(Label.Plan_Direct).getRecordTypeId();
    /*
    *  @AUTHOR:  KD
    *  @DESCRIPTION:This method creates Plan
    *  @PARAM :  String TerritoryId
    *  @RETURN:  
    */
    
    public static Plan__c getPlan(String strTerritoryId){
        return new Plan__c(Name = 'Test_Plan', 
                            Territory_Id__c = strTerritoryId,
                            Start_Date__c = Date.Today(),
                            End_Date__c = Date.Today()+120,
                            Status__c = 'Draft',
                            recordTypeId =idDirectRecordType);
    }
    /*
    *  @AUTHOR:  KD
    *  @DESCRIPTION:This method creates Plan
    *  @PARAM :  String TerritoryId
    *  @RETURN:  
    */
    
    public static Plan__c getOverlayPlan(String strTerritoryId){
        return new Plan__c(Name = 'Test_Plan', 
                            Territory_Id__c = strTerritoryId,
                            Start_Date__c = Date.Today(),
                            End_Date__c = Date.Today()+120,
                            Status__c = 'Draft',
                            recordTypeId =idOverlayRecordType);
    }

}