force-app/main/default/objects/SVMXC__SM_IB_Attributes_Template_Instance__c/SVMXC__SM_IB_Attributes_Template_Instance__c.object-meta.xml
<CustomObject>
    <description>Object to manage templates and installed product reference</description>
    <label>IB Attributes Template Instance</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>IB Attributes Template Instance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IB Attributes Template Instances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__SM_IB_Attributes_Template_Instance__c/fields/SVMXC__SM_Attr_Payload__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__SM_Attr_Payload__c</fullName>
    <description>Attributes as JSON with data generated in the structure defined as part of associated IB’s product template</description>
    <label>Attr Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SVMXC__SM_IB_Attributes_Template_Instance__c/fields/SVMXC__SM_Installed_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__SM_Installed_Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to installed product id/name</description>
    <label>Installed Product Id</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>IB Attributes Template Instances</relationshipLabel>
    <relationshipName>IB_Attributes_Template_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__SM_IB_Attributes_Template_Instance__c/fields/SVMXC__SM_Instance_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__SM_Instance_Template_Id__c</fullName>
    <description>Unique Record Id, Managed by ServiceMax App</description>
    <label>Instance Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMAttributesTemplateInstanceSelector.cls
/**
 *    @author Sagar Madkaikar
 *    @date   21-07-2022
 *    @description :DCP-54367 : Selector class for SVMXC__SM_IB_Attributes_Template_Instance__c object
 *    Modification Log:
 *    -------------------------------------------------------------------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      Sagar                         21-Jul-2022         Initial Version
 *    -------------------------------------------------------------------------------------------------------------------------------------------------
 */
public with sharing class SMAttributesTemplateInstanceSelector extends ilib_SObjectSelector{

    private static final String LOG_TITLE = 'SMAttributesTemplateInstanceSelector';
    private static final  string SERVICE_QUERY_LOGS = 'ServiceQueryLogs';
    
    /**
     *  @author Sagar
     *  @description
     *  @return SObjectType The Schema.SObjectType of the SVMXC__SM_IB_Attributes_Template_Instance__c.
     */
    public Schema.SObjectType getSObjectType(){
        return SVMXC__SM_IB_Attributes_Template_Instance__c.sObjectType;
    }

    /**
     *  @author  Sagar
     *  @description Retrieve list of fields for SVMXC__SM_IB_Attributes_Template_Instance__c sObject
     *  @return sObjectFieldList list of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            SVMXC__SM_IB_Attributes_Template_Instance__c.Id,
            SVMXC__SM_IB_Attributes_Template_Instance__c.SVMXC__SM_Installed_Product_Id__c,
            SVMXC__SM_IB_Attributes_Template_Instance__c.SVMXC__SM_Attr_Payload__c,
            SVMXC__SM_IB_Attributes_Template_Instance__c.SVMXC__SM_Instance_Template_Id__c
        };
    }

}