force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/SVMXC__RMA_Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Parts Order is an object to handle parts logistics. With record type RMA, it is a document that authorizes products or parts to be returned to the manufacturer/repair center/warehouse. With record type Shipment,  it is an internal document that authorizes products or parts to be shipped to a customer or field inventory location. ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both.</description>
    <label>Parts Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Shipping_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To Populate the Shipping Location.</description>
    <label>Shipping Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SVMXC__Site__c.Type__c</field>
            <operation>notEqual</operation>
            <value>Bill To, Payer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Parts Orders (Shipping Location)</relationshipLabel>
    <relationshipName>Parts_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Shipping_Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Location_Address__c</fullName>
    <description>Formula field to populate the full shipping location address.Source-Automation</description>
    <formula>IF(ISBLANK(Shipping_Location__r.SVMXC__Street__c), NULL, Shipping_Location__r.SVMXC__Street__c &amp; &quot;,&quot;) &amp;
IF(ISBLANK(Shipping_Location__r.Street_2__c), NULL, Shipping_Location__r.Street_2__c &amp; &quot;,&quot;) &amp;
IF(ISBLANK(Shipping_Location__r.SVMXC__City__c), NULL, Shipping_Location__r.SVMXC__City__c &amp; &quot;,&quot;) &amp;
IF(ISBLANK(Shipping_Location__r.SVMXC__State__c), NULL, Shipping_Location__r.SVMXC__State__c &amp; &quot;,&quot;) &amp;
IF(ISBLANK(Shipping_Location__r.SVMXC__Zip__c), NULL, Shipping_Location__r.SVMXC__Zip__c &amp; &quot;,&quot;) &amp;
IF(ISBLANK(TEXT(Shipping_Location__r.SVMXC__Country__c)), NULL, TEXT(Shipping_Location__r.SVMXC__Country__c) &amp; &quot;,&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Location Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/Shipping_Location_Details__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Location_Details__c</fullName>
        <description>Field to store Shipping Location Details on SFM screen to autofill the complete address of shipping location</description>
        <label>Shipping Location Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ShippingLocationDetails_POHelper.cls
/**
*    @author Romi Taskar
*    @date 30 August 2022
*
*    @description DCP-52923 Helper Class for Parts Order Handler for populating Shipping Location Details
*    Modification Log:
*    ------------------------------------------------------------------------------------------------------
*    Developer                      Date                Description
*    Romi Taskar                1-Sep-2022              DCP-52923: Helper Class for Parts Order Handler for populating Shipping Location Details
*    ------------------------------------------------------------------------------------------------------
*/ 
public with sharing class ShippingLocationDetails_POHelper {

    private static final String LOG_TITLE = 'ShippingLocationDetails_POHelper';
    
   /*******************************************************************************************************
    * @description : DCP - 52923 -Parts Order Management: Display Shipping Location Address
    * @param newRecord : new Parts Order
    * @param oldRecord : old Parts Order
    * @return : void
    */

    public static void populateShippingLocDetails(SVMXC__RMA_Shipment_Order__c newRecord, SVMXC__RMA_Shipment_Order__c oldRecord) {

        ilib_LogEvent.push(LOG_TITLE + '.populateShippingLocDetails()');
        ilib_LogEvent.info('New Record-->: '+newRecord.id);
        if(oldRecord == NULL || (oldRecord != NULL && oldRecord.Shipping_Location__c != newRecord.Shipping_Location__c)) {

            if(newRecord.Shipping_Location__c != NULL && PartsOrders.mapSites.containsKey(newRecord.Shipping_Location__c)) {
                newRecord.Shipping_Location_Details__c = PartsOrders.mapSites.get(newRecord.Shipping_Location__c).Shipping_Location_Address__c;

            } else {
                newRecord.Shipping_Location_Details__c = '';
            }
        }

        ilib_LogEvent.pop();
    }
}