force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/SVMXC__RMA_Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Parts Order is an object to handle parts logistics. With record type RMA, it is a document that authorizes products or parts to be returned to the manufacturer/repair center/warehouse. With record type Shipment,  it is an internal document that authorizes products or parts to be shipped to a customer or field inventory location. ServiceMax uses a common tab Parts Orders as a home for RMA and Shipment orders both.</description>
    <label>Parts Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account from/to which this RMA/shipment is made. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Company from/to which this RMA/shipment is made. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parts Orders (Account)</relationshipLabel>
    <relationshipName>RMA_Shipment_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__RMA_Shipment_Order__c/fields/SVMXC__Service_Order__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Order related to this RMA/shipment order. Is a lookup to an existing service order record in ServiceMax</description>
    <inlineHelpText>Service Order related to this RMA/shipment order. Is a lookup to an existing service order record in ServiceMax</inlineHelpText>
    <label>Work Order</label>
    <referenceTo>SVMXC__Service_Order__c</referenceTo>
    <relationshipName>RMA_Shipment_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SVMXC__Service_Order__c/SVMXC__Service_Order__c.object-meta.xml
<CustomObject>
    <description>Service Order is used to plan, execute and manage Service events for Field and Depot Service activities. Depending upon the service scenario, the order creation can be triggered by many events: When creating a Support Case, when one or more installed products require periodic service or calibration, when troubleshooting a customer problem on the field, if the field service engineer learns that the product requires specialized conditions of a factory/depot to resolve the problem, or when a new/repair shipment to customer requires specialized installation activity.</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SVMXC__Service_Order__c/fields/SVMXC__Company__c.field-meta.xml
<CustomField>
    <fullName>SVMXC__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Account initiating this service order. Is a lookup to an existing salesforce account record</description>
    <inlineHelpText>Customer Company initiating this service order. Is a lookup to an existing salesforce account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Service_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TAPS_SmaxPartsOrders.cls
/***************************************************************************************************************************************
* NAME   : TAPS_SmaxPartsOrders 
* --------------------------------------------------------------------------------------------------------------------------------------
*/
public without sharing class TAPS_SmaxPartsOrders extends TAPS_ComposedBase implements TAPS_IObjectsCustom {

    /* 
    * @description: To return Object API Name
    * @return: SObjectType
    */	
    public override SObjectType getObjectType()
    {
        return SVMXC__RMA_Shipment_Order__c.sObjectType;
    }

    /* 
    * @description: to fetch ACcount record based on Parts Order
    * @Param:Set<Id>
    * @return: Map<Id, Set<Id>>
    */
    public override Map<Id, Set<Id>> mapRecordToAccountsCustom(Set<Id> recordIds)
    {
        List<SVMXC__RMA_Shipment_Order__c> recordDetails = [SELECT Id, SVMXC__Service_Order__r.SVMXC__Company__c FROM SVMXC__RMA_Shipment_Order__c WHERE Id IN :recordIds];
        return UtilsCollection.getMapOfIdToIds(recordDetails, 'Id', 'SVMXC__Service_Order__r.SVMXC__Company__c');
    }
 
    /* 
    * @description:Fetch record Id based on related account Id of PO
    * @Param:Set<Id>
    * @return: Set<Id>
    */	
    public override Set<Id> getRecordIdsFromAccountIdsCustom(Set<Id> accountIds)
    {
        List<SVMXC__RMA_Shipment_Order__c> recordDetails = [SELECT Id FROM SVMXC__RMA_Shipment_Order__c WHERE SVMXC__Service_Order__r.SVMXC__Company__c IN :accountIds];
        return UtilsCollection.getSetOfIds(recordDetails, 'Id');
    }

    /* 
    * @description: to fetch modified records
    * @Param:Set<Id>
    * @return: Set<Id>
    */	
    public override Set<Id> getRecordIdsFromModifiedRecordIdsCustom(Set<Id> modifiedRecordIds)
    {
        if (modifiedRecordIds.size() == 0) return modifiedRecordIds;

        // modified record IDs might be Work Orders
        if (UtilsCollection.getFirstIdFromSet(modifiedRecordIds).getSobjectType() == SVMXC__Service_Order__c.SObjectType)
        {
            List<SVMXC__RMA_Shipment_Order__c> recordDetails = [SELECT Id FROM SVMXC__RMA_Shipment_Order__c WHERE SVMXC__Service_Order__c IN :modifiedRecordIds];
            return UtilsCollection.getSetOfIds(recordDetails, 'Id');
        }

        return modifiedRecordIds;
    }

    /* 
    * @description: To return Object API Name
    * @return: SObjectType
    */
    public override SObjectType getShareObjectType()
    {
        return SVMXC__RMA_Shipment_Order__Share.sObjectType;
    }

    /* 
    * @description: To return Field API Name
    * @return: String
    */
    public override String getShareParentFieldName()
    {
        return 'ParentId';
    }

    /* 
    * @description: Create Sharing Record
    * @Params :Id,Id
    * @return: SObject
    */	
    public override SObject createSharingRecord(Id recordId, Id userId)
    {
        return new SVMXC__RMA_Shipment_Order__Share(
            UserOrGroupId = userId,
            ParentId = recordId,
            AccessLevel = 'Edit',
            RowCause = Schema.SVMXC__RMA_Shipment_Order__Share.RowCause.Manual
        );
    }

}