force-app/main/default/objects/Promotions__c/Promotions__c.object-meta.xml
<CustomObject>
    <description>Represents a promotion associated with one or more products. Source of majority of the data is ERP (SAP) system</description>
    <label>Promotions</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotions__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This checkbox indicates if promotion is active or not.</description>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <description>This text field denotes primary product line for the promotion.</description>
    <label>Primary Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promo_Type__c.field-meta.xml
<CustomField>
    <fullName>Promo_Type__c</fullName>
    <businessOwnerGroup>Sales_Schema_Owners</businessOwnerGroup>
    <description>Indicates the type of promotion. Managed by users with SL_Promotions Manager permission set. Jira Story # CMCM-10037</description>
    <inlineHelpText>Indicates the type of promotion</inlineHelpText>
    <label>Promo Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Code__c</fullName>
    <description>This field is used to store promo external id which is synced from SAP.</description>
    <externalId>true</externalId>
    <label>Promotion Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBatchtoUpdatePromotypeAndPrimaryLine.cls
/**
*    @author: Vinay 
*    @date:   05-Sep-2024
*    @description:  Test class for BatchtoUpdatePromotypeAndPrimaryLine 
*    Modification Log:
*    ------------------------------------------------------------------------------------
*             Developer                      Date                Description
*             Vinay                        05-Sep-2024        Initial Development
*    ------------------------------------------------------------------------------------ 
*                    
*/

@isTest
public with sharing class TestBatchtoUpdatePromotypeAndPrimaryLine {
    

    
/**
* @authorVinay S Reddy
* @description setup test data for plan records
**/
@testSetup
public static void setupData()
    { 

        Promotions__c testPromotion = new Promotions__c();
        testPromotion.Name = 'Test Record';
        testPromotion.Promotion_Code__c = '1234';
        testPromotion.Primary_Product_Line__c = 'Test Line (Test Promo Type)';
        testPromotion.Active__c = true;
        insert testPromotion;

    }

    @isTest
    /**
* @author Vinay S Reddy
* @description execute the test data
**/
public static void method1(){
 
 
        Test.startTest();
             Database.executeBatch(new BatchtoUpdatePromotypeAndPrimaryLine());
        Test.stopTest();
        List<Promotions__c> promoAfterDataUpdate = new List<Promotions__c>();
        promoAfterDataUpdate = [Select Id ,Name,Primary_Product_Line__c,Promo_Type__c,Active__c From Promotions__c Where Active__c=true Limit 1];
        Assert.areEqual('Test Promo Type',promoAfterDataUpdate[0].Promo_Type__c,'Promo Type is not Matching');
    }

}