force-app/main/default/objects/Promotions__c/Promotions__c.object-meta.xml
<CustomObject>
    <description>Represents a promotion associated with one or more products. Source of majority of the data is ERP (SAP) system</description>
    <label>Promotions</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotions__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <description>This checkbox indicates if approval is required or not for given promotion.</description>
    <defaultValue>false</defaultValue>
    <label>Approval Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <description>This field represent the user who will approve the promotion.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Change_History__c.field-meta.xml
<CustomField>
    <fullName>Change_History__c</fullName>
    <description>This field denotes change history for given promotion.</description>
    <label>Change History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This text field stores country for promotion.</description>
    <inlineHelpText>What countries this promotion targets, if any</inlineHelpText>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <description>DCP-41005: new field to store Customer Description</description>
    <label>Customer Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <description>DCP-41005: new field to store Distribution Channel</description>
    <label>Distribution Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Distribution_Channel_Description__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel_Description__c</fullName>
    <description>DCP-41005: new field to store Distribution Channel Description</description>
    <label>Distribution Channel Description</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Distributor_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Eligible__c</fullName>
    <description>This field is used to identify if distributor is eligible for given promotion.</description>
    <defaultValue>false</defaultValue>
    <label>Distributor Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>This date field indicate effective date for the given promotion.</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>This date field indicate expiration date for the given promotion.</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Limit_View__c.field-meta.xml
<CustomField>
    <fullName>Limit_View__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41005: new field to store Limit View</description>
    <label>Limit View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Marketing_Trade_In__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Trade_In__c</fullName>
    <description>Designates if this promo requires trading-in of a Illumina (internal) or non-Illumina (external) product</description>
    <inlineHelpText>Designates if this promo requires trading-in of a Illumina (internal) or non-Illumina (external) product</inlineHelpText>
    <label>Marketing Trade-In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marketing_Trade_In</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <description>This text field denotes primary product line for the promotion.</description>
    <label>Primary Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promo_Type__c.field-meta.xml
<CustomField>
    <fullName>Promo_Type__c</fullName>
    <businessOwnerGroup>Sales_Schema_Owners</businessOwnerGroup>
    <description>Indicates the type of promotion. Managed by users with SL_Promotions Manager permission set. Jira Story # CMCM-10037</description>
    <inlineHelpText>Indicates the type of promotion</inlineHelpText>
    <label>Promo Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Channel__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Channel__c</fullName>
    <description>This multi-select picklist is used to indicate appropriate channel for promotion.</description>
    <inlineHelpText>Whether the promo is available Online, in Apttus, or both Online and in Apttus</inlineHelpText>
    <label>Promotion Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>F1</fullName>
            </value>
            <value>
                <fullName>F2</fullName>
            </value>
            <value>
                <fullName>F3</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>O1</fullName>
            </value>
            <value>
                <fullName>O2</fullName>
            </value>
            <value>
                <fullName>O3</fullName>
            </value>
            <value>
                <fullName>OL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Channel_Description__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Channel_Description__c</fullName>
    <description>DCP-41005: new field to store Promotion  Channel Description</description>
    <label>Promotion Channel Description</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Online/Quoting</fullName>
            </value>
            <value>
                <fullName>Online/Quoting – One User Per UC</fullName>
            </value>
            <value>
                <fullName>Online/Quoting – Three Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Online/Quoting – Two Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Online Only</fullName>
            </value>
            <value>
                <fullName>Online Only – One Use Per UC</fullName>
            </value>
            <value>
                <fullName>Online Only – Three Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Online Only – Two Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Quoting Only</fullName>
            </value>
            <value>
                <fullName>Quoting Only – One Use Per UC</fullName>
            </value>
            <value>
                <fullName>Quoting Only – Three Uses Per UC</fullName>
            </value>
            <value>
                <fullName>Quoting Only – Two Uses Per UC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Code__c</fullName>
    <description>This field is used to store promo external id which is synced from SAP.</description>
    <externalId>true</externalId>
    <label>Promotion Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Details__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Details__c</fullName>
    <description>This long text area field provides promotion details.</description>
    <label>Promotion Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Promotion_Owner__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Owner__c</fullName>
    <description>This field represents the owner of the promotion.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Redemption_Limit__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Limit__c</fullName>
    <description>This field gives the limit for redemption of promo.</description>
    <inlineHelpText>The number of times an Ultimate Consignee Account can redeem/quote this promotion</inlineHelpText>
    <label>Redemption Limit</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Redemption_Method__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Method__c</fullName>
    <businessOwnerGroup>Sales_Schema_Owners</businessOwnerGroup>
    <description>Indicates if the promotion is implicit (automatically applied) or Explicit (Manually applied). Managed by users with SL_Promotions Manager permission set. Jira Story # CMCM-12045
Data Owner: Cameo Steele / Ken Mudd</description>
    <inlineHelpText>Indicates if the promotion is Implicit (automatically applied) or Explicit (Manually applied)</inlineHelpText>
    <label>Redemption Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Implicit</fullName>
            </value>
            <value>
                <fullName>Explicit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Regions__c.field-meta.xml
<CustomField>
    <fullName>Regions__c</fullName>
    <description>This field is used to identify the regions which the promotion targets.</description>
    <inlineHelpText>What regions this promotion targets</inlineHelpText>
    <label>Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMR</fullName>
            </value>
            <value>
                <fullName>AMEA</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
                <isActive>false</isActive>
                <label>APAC</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <isActive>false</isActive>
                <label>EMEA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Rules_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Rules_Requirements__c</fullName>
    <description>This field denotes the rules and requirements for the promotion.</description>
    <inlineHelpText>Additional rules the promotion must follow in order to be applicable</inlineHelpText>
    <label>Rules &amp; Requirements</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Sales_Description__c.field-meta.xml
<CustomField>
    <fullName>Sales_Description__c</fullName>
    <description>This field denotes the sales description for the given promotion.</description>
    <label>Sales Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>DCP-41005: new field to store Sales Org</description>
    <label>Sales Org</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Stackable__c.field-meta.xml
<CustomField>
    <fullName>Stackable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41005: new field to store Stackable</description>
    <label>Stackable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotions__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <description>test</description>
    <inlineHelpText>Customer facing T&amp;Cs</inlineHelpText>
    <label>Terms and Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Marketing_Trade_In.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <description>Designates if this promo requires trading-in of a Illumina (internal) or non-Illumina (external) product</description>
    <masterLabel>Marketing Trade-In</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>AT01</fullName>
    </customValue>
    <customValue>
        <fullName>AU01</fullName>
    </customValue>
    <customValue>
        <fullName>BE01</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>CA01</fullName>
    </customValue>
    <customValue>
        <fullName>CH01</fullName>
    </customValue>
    <customValue>
        <fullName>CN01</fullName>
    </customValue>
    <customValue>
        <fullName>CN02</fullName>
    </customValue>
    <customValue>
        <fullName>CN03</fullName>
    </customValue>
    <customValue>
        <fullName>DE01</fullName>
    </customValue>
    <customValue>
        <fullName>CO01</fullName>
    </customValue>
    <customValue>
        <fullName>DK01</fullName>
    </customValue>
    <customValue>
        <fullName>ES01</fullName>
    </customValue>
    <customValue>
        <fullName>FI01</fullName>
    </customValue>
    <customValue>
        <fullName>FR01</fullName>
    </customValue>
    <customValue>
        <fullName>FR02</fullName>
    </customValue>
    <customValue>
        <fullName>FR90</fullName>
    </customValue>
    <customValue>
        <fullName>GB01</fullName>
    </customValue>
    <customValue>
        <fullName>GB02</fullName>
    </customValue>
    <customValue>
        <fullName>GB03</fullName>
    </customValue>
    <customValue>
        <fullName>GB90</fullName>
    </customValue>
    <customValue>
        <fullName>HK01</fullName>
    </customValue>
	<customValue>
        <fullName>IE01</fullName>
    </customValue> 
	<customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IS01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>JP01</fullName>
    </customValue>
    <customValue>
        <fullName>KR01</fullName>
    </customValue>
    <customValue>
        <fullName>NL01</fullName>
    </customValue>
    <masterLabel>Sales Org</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PromotionWrapper.cls
/***************************************************************************************************************************************
 * NAME         : PromotionWrapper
 * DESCRIPTION  : Promotion Data Wrapper 
 * @AUTHOR      : Karthik Rayani
 * @DATE        : 08-Sep-2020  
 * 
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 *  Karthik Rayani    08-Sep-2020       DCP-40228-Initial Version.
 *  Rajbabu Boopalan  12-Dec-2024       CMCM-9332 Promo Fiori changes
 ****************************************************************************************************************************************/

Public class PromotionWrapper {

    public String Name;
    public String Promotion_Code;
    public String Expiration_Date;
    public String Effective_Date;
    public String Terms_and_Conditions;
    public String Approval_Required;
    public String Approver;
    public String Change_History;
    public String Country;
    public String Customer_Description;
    public String Distribution_Channel;
    public String Distribution_Channel_Description;
    public String Distributor_Eligible;
    public String Limit_View;
    public String Marketing_Trade_In;
    public String Primary_Product_Line;
    public String Promo_Channel;
    public String Promotion_Channel_Description;
    public String Promotion_Details;
    public String Promotion_Owner;
    public String Redemption_Limit;
    public String Redemption_Method;
    public String Regions;
    public String Rules_Requirements;
    public String Sales_Description;
    public String Sales_Org;
    public String Stackable;
    public String Promo_Type;

    /*
    * @author:Karthik
   */
    public Promotions__c getSobject(PromotionWrapper prw) 
    {
        Promotions__c pr = new Promotions__c();
        pr.Name = prw.Name;
        pr.Promotion_Code__c = prw.Promotion_Code;
        pr.Terms_and_Conditions__c = prw.Terms_and_Conditions;
        if (String.isNotBlank(prw.Expiration_Date))
            pr.Expiration_Date__c = Date.valueOf(prw.Expiration_Date);
        if (String.isNotBlank(prw.Effective_Date))
            pr.Effective_Date__c = Date.valueOf(prw.Effective_Date);
        if (String.isNotBlank(prw.Approval_Required))
            pr.Approval_Required__c = Boolean.valueOf(prw.Approval_Required);
        if(string.isNotBlank(prw.Approver)){
            pr.Approver__c = prw.Approver;
        }
        pr.Change_History__c = prw.Change_History;
        pr.Country__c = prw.Country;
        pr.Customer_Description__c = prw.Customer_Description;
        pr.Distribution_Channel__c = prw.Distribution_Channel;
        pr.Distribution_Channel_Description__c = prw.Distribution_Channel_Description;
        if (String.isNotBlank(prw.Distributor_Eligible))
            pr.Distributor_Eligible__c = Boolean.valueOf(prw.Distributor_Eligible);
        if (String.isNotBlank(prw.Limit_View))
            pr.Limit_View__c = Boolean.valueOf(prw.Limit_View);
        pr.Marketing_Trade_In__c = prw.Marketing_Trade_In;
        pr.Primary_Product_Line__c = prw.Primary_Product_Line;
        pr.Promotion_Channel__c = prw.Promo_Channel;
        pr.Promotion_Channel_Description__c = prw.Promotion_Channel_Description;
        pr.Promotion_Details__c = prw.Promotion_Details;
        if(string.isNotBlank(prw.Promotion_Owner)){
            pr.Promotion_Owner__c = prw.Promotion_Owner;
        }
        pr.Redemption_Limit__c = prw.Redemption_Limit;
        pr.Redemption_Method__c = prw.Redemption_Method;
        pr.Regions__c = prw.Regions;
        pr.Rules_Requirements__c = prw.Rules_Requirements;
        pr.Sales_Description__c = prw.Sales_Description;
        pr.Sales_Org__c = prw.Sales_Org;
        if (String.isNotBlank(prw.Stackable))
            pr.Stackable__c = Boolean.valueOf(prw.Stackable);
        pr.Promo_Type__c = prw.Promo_Type;
        return pr;
    }
    /*
    * @author:Karthik
   */
    public List < Promotions__c > getSobjectList(List < PromotionWrapper > listPromotionWrapper) 
    {
        List < Promotions__c > listPromos = new List < Promotions__c > ();
        for (PromotionWrapper prw: listPromotionWrapper) {
            Promotions__c pr = getSobject(prw);
            
            listPromos.add(pr);
        }
        return listPromos;
    }
}