force-app/main/default/objects/Work_Order_Activity_Rules__c/Work_Order_Activity_Rules__c.object-meta.xml
<CustomObject>
    <description>DCP-43186:  Contains rule entries as records for various requirements related to the work order and activities including documents needed and tool debrief compliance.</description>
    <label>Work Order Activity Rules</label>
    <nameField>
        <label>Work Order Activity Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Activity Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-43186  To activate or deactivate the rule.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <description>DCP-43186  This is to store all the labor activity types. These should match with the labor activity types that are in the work detail object.</description>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Calibration</fullName>
            </value>
            <value>
                <fullName>Cleanup</fullName>
            </value>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Customer Readiness</fullName>
            </value>
            <value>
                <fullName>Customer Service Review</fullName>
            </value>
            <value>
                <fullName>Dedicated Onsite Activities</fullName>
            </value>
            <value>
                <fullName>Depot Service</fullName>
            </value>
            <value>
                <fullName>DRAGEN IVD Platform</fullName>
            </value>
            <value>
                <fullName>Field Compliance Review</fullName>
            </value>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>IQ/OQ</fullName>
            </value>
            <value>
                <fullName>IT Consult</fullName>
            </value>
            <value>
                <fullName>Letter of Acceptance accepted</fullName>
            </value>
            <value>
                <fullName>OQ</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>PQ Training</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Qualification Service Review</fullName>
            </value>
            <value>
                <fullName>Relocation</fullName>
            </value>
            <value>
                <fullName>Remote Support</fullName>
            </value>
            <value>
                <fullName>Repair/Troubleshooting</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Sales Support Activity</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Workflow Config</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <description>DCP-43186 to specify the type of document needed for a given combination of instrument and activity type.</description>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Is_Tool_Debrief_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Tool_Debrief_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-41619 : Is Tool Debrief Mandatory?</description>
    <label>Is Tool Debrief Mandatory?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DCP-43186  Lookup to product</description>
    <label>Product Code</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Order Activity Rules</relationshipLabel>
    <relationshipName>Product_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>DCP-43186 This is to store the material number of the Dx instrument.</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AmpliSeq Library Prep</fullName>
            </value>
            <value>
                <fullName>Archer Targeted RNA</fullName>
            </value>
            <value>
                <fullName>Array-Based Analysis</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2</fullName>
            </value>
            <value>
                <fullName>AutoLoader 2.x</fullName>
            </value>
            <value>
                <fullName>AutoLoader Accessories</fullName>
            </value>
            <value>
                <fullName>AutoLoader Service Contract</fullName>
            </value>
            <value>
                <fullName>Automation Software DX</fullName>
            </value>
            <value>
                <fullName>Automation Software RUO</fullName>
            </value>
            <value>
                <fullName>BAR Service Contract</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Storage</fullName>
            </value>
            <value>
                <fullName>Basespace Cloud Storage + Compute</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cloud Subscriptions</fullName>
            </value>
            <value>
                <fullName>BaseSpace Cohort Analyzer</fullName>
            </value>
            <value>
                <fullName>BaseSpace Correlation Engine</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Accessory</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Platform</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Qualifications</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Software</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite System</fullName>
            </value>
            <value>
                <fullName>BaseSpace Onsite Upgrades</fullName>
            </value>
            <value>
                <fullName>BaseSpace Professional Service</fullName>
            </value>
            <value>
                <fullName>BeadXpress Service Contract</fullName>
            </value>
            <value>
                <fullName>Beadxpress System (220V)</fullName>
            </value>
            <value>
                <fullName>Billable Service</fullName>
            </value>
            <value>
                <fullName>Billable Service Sequencing</fullName>
            </value>
            <value>
                <fullName>BioRad System</fullName>
            </value>
            <value>
                <fullName>BlueGnome Accessory</fullName>
            </value>
            <value>
                <fullName>cBot Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Repair_protocol__c.field-meta.xml
<CustomField>
    <fullName>Repair_protocol__c</fullName>
    <description>This field is used to display Repair protocol  selected multi picklist values for displaying it on Document upload.</description>
    <label>Repair protocol</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
			<value>
				<fullName>Optical: Camera 2 Replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Regenerate data cc files</fullName>
			</value>
			<value>
				<fullName>Optical: Filter Slider replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Filter Wheel replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Camera Assembly replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Objective lens replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Laser replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Z Stage replacement</fullName>
			</value>
			<value>
				<fullName>Electronics: MPCA replacement</fullName>
			</value>
			<value>
				<fullName>Electronics: VIX Controller replacement</fullName>
			</value>
			<value>
				<fullName>Electronics: PSU replacement</fullName>
			</value>
			<value>
				<fullName>Electronics: Framegrabber Card replacement</fullName>
			</value>
			<value>
				<fullName>Electronics: E-Box replacement</fullName>
			</value>
			<value>
				<fullName>Mechanical: Front Door Repair</fullName>
			</value>
			<value>
				<fullName>Mechanical: Drive Chain replacement</fullName>
			</value>
			<value>
				<fullName>Mechanical: Docking Station replacement</fullName>
			</value>
			<value>
				<fullName>Mechanical: XY Stage replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Camera 1 Replacement</fullName>
			</value>
			<value>
				<fullName>Optical: Compensator Repairs</fullName>
			</value>
			<value>
				<fullName>Optical: F4/F8 Miror Replacement</fullName>
			</value>
			<value>
				<fullName>Optical: LED Replacement</fullName>
			</value>
			<value>
				<fullName>Optical: M3 Mirror Inspection &amp; Service</fullName>
			</value>
			<value>
				<fullName>Optical: M3 Mirror Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: Combo Board or Main Board Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: E-Box Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: Power Supply Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: SBC Board Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: Z-Stage Control Board Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: Reagent Cartridge RFID Replacement</fullName>
			</value>
			<value>
				<fullName>Electrical: Flow Cell RFID Replacement</fullName>
			</value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Activity_Rules__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DCP-43186 to specify that a document is Required or is just recommended.</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WorkOrderActivityRulesSelector.cls
/**
*    @author Raja Siva Krishna
*    @date   2020-11-19
*    @description    DCP-43185: WorkOrderActivityRulesSelector class from work order activity rule object
*    Modification Log:
*    ------------------------------------------------------------------------------------ 
*             Developer                      Date                Description
*    ------------------------------------------------------------------------------------
*             Siva                   19/11/2020          Initial Version
*           Prashanth                18/08/2021           Modified
*                    
*/
public with sharing class WorkOrderActivityRulesSelector extends ilib_SObjectSelector {
    private static final String LOG_TITLE = 'WorkOrderActivityRulesSelector';
    private static final String FEATURE_SERVICE_QUERY_LOGS = 'ServiceQueryLogs';
    /**
    *  @author Raja Siva Krishna
    *  @return SObjectType The Schema.SObjectType of the Work_Order_Activity_Rules__c
    **/
    public Schema.SObjectType getSObjectType()
    {
        return Work_Order_Activity_Rules__c.sObjectType;
    }
    
    /**
    *  @author  Raja Siva Krishna
    *  @description Retrieve list of fields for Work_Order_Activity_Rules__c 
    *  @return sObjectFieldList list of Schema.SObjectField
    **/
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Work_Order_Activity_Rules__c.id,
            Work_Order_Activity_Rules__c.Document_Name__c
        }; 
            
    }

   /**
     *  @author Raja Siva Krishna
     *  @description Fetch List of uploaded document names
     *  @param  Id
     *  @return Work_Order_Activity_Rules__c
     **/
    @AuraEnabled(cacheable=true)
    public Static Work_Order_Activity_Rules__c getWorkOrderActivityRuleById(Id recId) 
    {
        try{
            return new WorkOrderActivityRulesSelector().getWorkOrderActivityRuleByIds(recId);
        }catch(Exception e){
            //get exception message
            throw new AuraHandledException(e.getMessage());
            
        }
    } 

    /**
     *  @author Raja Siva Krishna
     *  @description Fetch work order activity rule by id
     *  @param  Id
     *  @return Work_Order_Activity_Rules__c
     **/
    public Work_Order_Activity_Rules__c getWorkOrderActivityRuleByIds(Id recId) 
    {
        ilib_LogQuery logger=null;
		if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger = new ilib_LogQuery(LOG_TITLE + '.getWorkOrderActivityRuleByIds', recId);
		}
        Work_Order_Activity_Rules__c res = (Work_Order_Activity_Rules__c)Database.query(
            newQueryFactory().setCondition('Id =:recId').toSOQL()
        );
        if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger.stop();
		}
		return res;
    } 

    /**
     *  @author Raja Siva Krishna
     *  @description Fetch work order activity rule by id
     *  @param  list of activities, product id, product group 
     *  @return List<Work_Order_Activity_Rules__c>
     **/
    public List<Work_Order_Activity_Rules__c> getWorkOrderActivityRuleByConditions(List<String> activities,String productId, String productGrp) 
    {
        ilib_LogQuery logger=null;
		if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger = new ilib_LogQuery(LOG_TITLE + '.getWorkOrderActivityRuleByConditions', UtilsCollection.serializeIds(new Set<String>(activities))+'|'+productId+'|'+productGrp);
		}
        List<Work_Order_Activity_Rules__c> res =  Database.query(
            newQueryFactory().setCondition('Active__c=True AND Activity_Type__c IN :activities AND (Product_Code__c=:productId OR Product_Group__c=:productGrp)').toSOQL()
        );
        if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger.stop(res.size());
		}
		return res;
    } 

    /**
     *  @author Raja Siva Krishna
     *  @description Fetch work order activity rule by set of WD activities
     *  @param  set of activities 
     *  @return List<Work_Order_Activity_Rules__c>
     **/
    public List<Work_Order_Activity_Rules__c> getWorkOrderActivityRuleByAcitivity(set<String> activities) {
        ilib_LogQuery logger=null;
        if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger = new ilib_LogQuery(LOG_TITLE + '.getWorkOrderActivityRuleByAcitivity', UtilsCollection.serializeIds(activities));
		}
        List<Work_Order_Activity_Rules__c> res = Database.query(
           newQueryFactory()
            .selectField('Activity_Type__c')
            .selectField('Product_Code__c')
            .selectField('Product_Group__c')
            .selectField('Required__c')
            .setCondition('Active__c=True AND Activity_Type__c IN :activities').toSOQL()
        );
        if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger.stop(res.size());
		}
		return res;
    } 
    /**
     *  @author Raja Siva Krishna
     *  @description Fetch work order activity rule by set of WD activities
     *  @param  set of activities 
     *  @return List<Work_Order_Activity_Rules__c>
     **/
    public List<Work_Order_Activity_Rules__c> getActiveWorkOrderActivityRules() {
        ilib_LogQuery logger=null;
        if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger = new ilib_LogQuery(LOG_TITLE + '.getActiveWorkOrderActivityRules');
		}
        List<Work_Order_Activity_Rules__c> res = Database.query(
           newQueryFactory()
            .selectField('Activity_Type__c')
            .selectField('Product_Code__c')
            .selectField('Product_Group__c')
            .selectField('Required__c')
            .selectField('Is_Tool_Debrief_Mandatory__c')
            .selectField('Repair_Protocol__c')
            .setCondition('Active__c=True').toSOQL()
        );
        if(Feature.isOn(FEATURE_SERVICE_QUERY_LOGS)){
			logger.stop(res.size());
		}
		return res;
    } 
}